$pyjs.loaded_modules.cells=function(Q){if($pyjs.loaded_modules.cells.__was_initialized__)return $pyjs.loaded_modules.cells;var m=$pyjs.loaded_modules.cells;m.__repr__=function(){return"<module: cells>"};m.__was_initialized__=!0;if(null===Q||"undefined"==typeof Q)Q="cells";m.__name__=Q;m.pygame=$p.___import___("pyjsdl",null,null,!1);m.math=$p.___import___("math",null);m.random=$p.___import___("random",null);m.os=$p.___import___("os",null);m.load_image=$p.___import___("util.load_image",null,null,!1);
m.sin_table=$p.___import___("util.sin_table",null,null,!1);m.cos_table=$p.___import___("util.cos_table",null,null,!1);m.Evolve=function(){var a={},b;a.__module__="cells";b=$pyjs__bind_method2("genetics",function(d,s,c,D){if(!0===this.__is_instance__)var f=this;else f=arguments[0],d=arguments[1],s=arguments[2],c=arguments[3],D=arguments[4];"undefined"==typeof d&&(d=arguments.callee.__args__[3][1]);"undefined"==typeof s&&(s=arguments.callee.__args__[4][1]);"undefined"==typeof c&&(c=arguments.callee.__args__[5][1]);
"undefined"==typeof D&&(D=arguments.callee.__args__[6][1]);var g,l,H,h,e,b,a,t,w,n,p,r,u,y,B,z,A,I,C,k,E,F,x,G,M,L;if(null===(r=(null===(y=n=f.matrix.evolution)||!1===y||0===y||""===y?0:"object"==typeof y?"function"==typeof y.__nonzero__?y.__nonzero__():"function"==typeof y.__len__?0<y.__len__():1:1)?c:n)||!1===r||0===r||""===r?0:"object"==typeof r?"function"==typeof r.__nonzero__?r.__nonzero__():"function"==typeof r.__len__?0<r.__len__():1:1){f.inherit=d;r=$p.dict([]);n=-1==((p=m.random.random())===
(L=s)?0:typeof p!=typeof L||"number"!=typeof p&&"string"!=typeof p&&"boolean"!=typeof p?$p.cmp(p,L):p==L?0:p<L?-1:1);if(null===(A=(null===(z=h=!(null===(b=d)||!1===b||0===b||""===b?0:"object"==typeof b?"function"==typeof b.__nonzero__?b.__nonzero__():"function"==typeof b.__len__?0<b.__len__():1:1))||!1===z||0===z||""===z?0:"object"==typeof z?"function"==typeof z.__nonzero__?z.__nonzero__():"function"==typeof z.__len__?0<z.__len__():1:1)?h:n)||!1===A||0===A||""===A?0:"object"==typeof A?"function"==
typeof A.__nonzero__?A.__nonzero__():"function"==typeof A.__len__?0<A.__len__():1:1){h=$p.xrange(1,c+1);"undefined"!=typeof(b=h.__array)?z=0:(h=h.__iter__(),z="undefined"!=typeof(b=h.__array)?0:"function"==typeof h.$genfunc?1:-1);for(A=0;"undefined"!=typeof(p=z?0<z?h.next(!0,!1):$p.wrapped_next(h):b[A++]);)r.__setitem__(p,$pyjs_kwargs_call(m.random,"randrange","undefined"!=typeof(x=D).__array?"undefined"!=typeof x.__array[E=p]?x.__array[E]:x.__getitem__(E):x.__getitem__(p),null,[{}]));if(null===n||
!1===n||0===n||""===n?0:"object"==typeof n?"function"==typeof n.__nonzero__?n.__nonzero__():"function"==typeof n.__len__?0<n.__len__():1:1)w=m.random.choice(r.keys()),G=$p.dict([[w,"undefined"!=typeof(F=r).__array?"undefined"!=typeof F.__array[k=w]?F.__array[k]:F.__getitem__(k):F.__getitem__(w)]])}if(null===(B=d)||!1===B||0===B||""===B?0:"object"==typeof B?"function"==typeof B.__nonzero__?B.__nonzero__():"function"==typeof B.__len__?0<B.__len__():1:1){r=d;if(null===(e=1==(0.9===(M=m.random.random())?
0:"number"!=typeof M||"number"!=typeof M&&"string"!=typeof M&&"boolean"!=typeof M?$p.cmp(M,0.9):0.9==M?0:0.9>M?-1:1))||!1===e||0===e||""===e?0:"object"==typeof e?"function"==typeof e.__nonzero__?e.__nonzero__():"function"==typeof e.__len__?0<e.__len__():1:1)for(f="undefined"!=typeof(l=f.matrix.species_group).__array?"undefined"!=typeof l.__array[I=f.species]?l.__array[I]:l.__getitem__(I):l.__getitem__(f.species),I=m.random.choice(f.sprites()).gene,a=l=m.random.sample($p.range(1,(null===(u=r)?0:"undefined"!=
typeof u.__array?u.__array.length:"function"==typeof u.__len__?u.__len__():"undefined"!=typeof u.length?u.length:$p.len(u))+1),Math.floor((null===(a=r)?0:"undefined"!=typeof a.__array?a.__array.length:"function"==typeof a.__len__?a.__len__():"undefined"!=typeof a.length?a.length:$p.len(a))/2)),"undefined"!=typeof(f=a.__array)?l=0:(a=a.__iter__(),l="undefined"!=typeof(f=a.__array)?0:"function"==typeof a.$genfunc?1:-1),u=0;"undefined"!=typeof(e=l?0<l?a.next(!0,!1):$p.wrapped_next(a):f[u++]);)r.__setitem__(e,
"undefined"!=typeof(C=I).__array?"undefined"!=typeof C.__array[g=e]?C.__array[g]:C.__getitem__(g):C.__getitem__(e));(null===n||!1===n||0===n||""===n?0:"object"==typeof n?"function"==typeof n.__nonzero__?n.__nonzero__():"function"==typeof n.__len__?0<n.__len__():1:1)&&r.__setitem__(w,"undefined"!=typeof(H=G).__array?"undefined"!=typeof H.__array[t=w]?H.__array[t]:H.__getitem__(t):H.__getitem__(w))}return r}return null},1,[null,null,["self"],["inherit",null],["mutation_rate",0.5],["genome",null],["alleles",
null]]);a.genetics=b;b=$pyjs__bind_method2("evolution",function(d,s){if(!0===this.__is_instance__)var c=this;else c=arguments[0],d=arguments[1],s=arguments[2];"undefined"==typeof d&&(d=arguments.callee.__args__[3][1]);"undefined"==typeof s&&(s=arguments.callee.__args__[4][1]);var D,f,g,l,b,h,e,a,v,t,w,n,p,r,u,y;if(null===(D=c.life)||!1===D||0===D||""===D?0:"object"==typeof D?"function"==typeof D.__nonzero__?D.__nonzero__():"function"==typeof D.__len__?0<D.__len__():1:1)if(c.exist+=1,c.ingest-=1/d,
c.fitness=c.ingest/s*100,null===(f=1==(100===(v=c.exist)?0:"number"!=typeof v||"number"!=typeof v&&"string"!=typeof v&&"boolean"!=typeof v?$p.cmp(v,100):100==v?0:100>v?-1:1))||!1===f||0===f||""===f?0:"object"==typeof f?"function"==typeof f.__nonzero__?f.__nonzero__():"function"==typeof f.__len__?0<f.__len__():1:1){c.exist=0;if(null===(g=1==((100===(w=c.fitness)?0:"number"!=typeof w||"number"!=typeof w&&"string"!=typeof w&&"boolean"!=typeof w?$p.cmp(w,100):100==w?0:100>w?-1:1)|1))||!1===g||0===g||
""===g?0:"object"==typeof g?"function"==typeof g.__nonzero__?g.__nonzero__():"function"==typeof g.__len__?0<g.__len__():1:1)c.ingest=s/4,(null===(l=-1==((p=c.species.count)===(y=c.species.maximum)?0:typeof p!=typeof y||"number"!=typeof p&&"string"!=typeof p&&"boolean"!=typeof p?$p.cmp(p,y):p==y?0:p<y?-1:1))||!1===l||0===l||""===l?0:"object"==typeof l?"function"==typeof l.__nonzero__?l.__nonzero__():"function"==typeof l.__len__?0<l.__len__():1:1)&&$pyjs_kwargs_call(c.matrix,"add_creature",null,null,
[{clone:!0,identity:c.identity,inherit:c.gene.copy()},c.species,c.x,c.y]);else if(null===(b=1>(0===(u=c.fitness)?0:"number"!=typeof u||"number"!=typeof u&&"string"!=typeof u&&"boolean"!=typeof u?$p.cmp(u,0):0==u?0:0>u?-1:1))||!1===b||0===b||""===b?0:"object"==typeof b?"function"==typeof b.__nonzero__?b.__nonzero__():"function"==typeof b.__len__?0<b.__len__():1:1)if(null===(h=1==((a=m.random.random())===(n=0.9-$p.abs(0.1*c.fitness))?0:typeof a!=typeof n||"number"!=typeof a&&"string"!=typeof a&&"boolean"!=
typeof a?$p.cmp(a,n):a==n?0:a<n?-1:1))||!1===h||0===h||""===h?0:"object"==typeof h?"function"==typeof h.__nonzero__?h.__nonzero__():"function"==typeof h.__len__?0<h.__len__():1:1)c.life=!1;(null===(e=-1==((t=c.species.count)===(r=c.species.minimum)?0:typeof t!=typeof r||"number"!=typeof t&&"string"!=typeof t&&"boolean"!=typeof t?$p.cmp(t,r):t==r?0:t<r?-1:1))||!1===e||0===e||""===e?0:"object"==typeof e?"function"==typeof e.__nonzero__?e.__nonzero__():"function"==typeof e.__len__?0<e.__len__():1:1)&&
c.matrix.add_creature(c.species)}return null},1,[null,null,["self"],["cycle",500],["division_threshold",18]]);a.evolution=b;b=Array($p.object);var x=$p.dict(),k;for(k in a)x.__setitem__(k,a[k]);return $p._create_class("Evolve",$p.tuple(b),x)}();m.Cell=function(){var a={},b;a.__module__="cells";a.image=null;a.count=0;a.minimum=10;a.maximum=100;a.id=0;a.evolving=!1;a.gene=$p.dict([]);a.alleles=$p.dict([]);a.gene_info=$p.dict([]);b=$pyjs__bind_method2("__init__",function(d,s,c,D,f,g,b,a,h){if(!0===this.__is_instance__)var e=
this;else e=arguments[0],d=arguments[1],s=arguments[2],c=arguments[3],D=arguments[4],f=arguments[5],g=arguments[6],b=arguments[7],a=arguments[8],h=arguments[9];"undefined"==typeof D&&(D=arguments.callee.__args__[6][1]);"undefined"==typeof f&&(f=arguments.callee.__args__[7][1]);"undefined"==typeof g&&(g=arguments.callee.__args__[8][1]);"undefined"==typeof b&&(b=arguments.callee.__args__[9][1]);"undefined"==typeof a&&(a=arguments.callee.__args__[10][1]);"undefined"==typeof h&&(h=arguments.callee.__args__[11][1]);
var q,v,t,w,n,p,r,u,y,B,z,A;m.pygame.sprite.Sprite.__init__(e);e.species=e.__class__;e.matrix=d;e.species.count+=1;e.species.id+=1;e.identity=e.species.id;e.gene=$p.dict([]);e.x=s;e.y=c;e.pos_x=$p["float"](e.x);e.pos_y=$p["float"](e.y);e.distance=0;e.direction=m.random.randrange(360);e.direction_adj_i=0;e.direction_adj_f=0;e.move_x=1;e.move_y=1;e.velocity=1;e.reverse=!1;e.reverse_redux=!1;e.rotate=0;e.rotate_count=0;e.interact=0;e.life=!0;e.exist=0;e.ingest=0;e.fitness=100;e.fission=0;if(null===(t=
null===e.species.image)||!1===t||0===t||""===t?0:"object"==typeof t?"function"==typeof t.__nonzero__?t.__nonzero__():"function"==typeof t.__len__?0<t.__len__():1:1){if(null===(q=D)||!1===q||0===q||""===q?0:"object"==typeof q?"function"==typeof q.__nonzero__?q.__nonzero__():"function"==typeof q.__len__?0<q.__len__():1:1)for(e.species.image=$p.list([]),q=m.load_image(D),t=$p.__ass_unpack(q.get_size(),2,null)[0],n=$p.xrange(f),"undefined"!=typeof(t=n.__array)?y=0:(n=n.__iter__(),y="undefined"!=typeof(t=
n.__array)?0:"function"==typeof n.$genfunc?1:-1),w=0;"undefined"!=typeof(y?0<y?n.next(!0,!1):$p.wrapped_next(n):t[w++]);)e.species.image.append(q);q=e.matrix.x*e.matrix.y/225E4;e.species.minimum=$p.float_int(m.math.ceil(("undefined"!=typeof(z=h).__array?"undefined"!=typeof z.__array[0]?z.__array[0]:z.__getitem__(0):z.__getitem__(0))*q));e.species.maximum=$p.float_int(m.math.ceil(("undefined"!=typeof(A=h).__array?"undefined"!=typeof A.__array[1]?A.__array[1]:A.__getitem__(1):A.__getitem__(1))*q))}e.phenotype(e.species,
D,f);if(null===(v=g)||!1===v||0===v||""===v?0:"object"==typeof v?"function"==typeof v.__nonzero__?v.__nonzero__():"function"==typeof v.__len__?0<v.__len__():1:1)e.identity=g;v=$p.__ass_unpack(e.genotype(b,a),2,null);e.gene=v[0];e.trait=v[1];e.rotate_image=!0;e.sensing=!0;e.label_display=!0;e.id_tag=null;try{(null===(p=1>(10===(u="undefined"!=typeof(B=("undefined"!=typeof(r=e.species.image).__array?"undefined"!=typeof r.__array[0]?r.__array[0]:r.__getitem__(0):r.__getitem__(0)).get_size()).__array?
"undefined"!=typeof B.__array[0]?B.__array[0]:B.__getitem__(0):B.__getitem__(0))?0:"number"!=typeof u||"number"!=typeof u&&"string"!=typeof u&&"boolean"!=typeof u?$p.cmp(u,10):10==u?0:10>u?-1:1))||!1===p||0===p||""===p?0:"object"==typeof p?"function"==typeof p.__nonzero__?p.__nonzero__():"function"==typeof p.__len__?0<p.__len__():1:1)?e.label_size=6:e.label_size=10}catch(k){$pyjs.__last_exception__={error:k,module:m},e.label_size=10}e.print_tag=null;e.growth_rate=1;return null},1,[null,null,["self"],
["matrix"],["x"],["y"],["cell_image",null],["frames",1],["identity",null],["inherit",null],["mutation_rate",0.5],["limit",$p.tuple([10,100])]]);a.__init__=b;b=$pyjs__bind_method2("set_trait",function(d,s){return $p.dict([])},1,[null,null,["self"],["gene"]]);a.set_trait=b;b=$pyjs__bind_method2("genotype",function(d,s,c){if(!0===this.__is_instance__)var D=this;else D=d,d=s,s=c;var f,g,b,a,h,e,q,v;c=(null===(e=!(null===(a=d)||!1===a||0===a||""===a?0:"object"==typeof a?"function"==typeof a.__nonzero__?
a.__nonzero__():"function"==typeof a.__len__?0<a.__len__():1:1))||!1===e||0===e||""===e?0:"object"==typeof e?"function"==typeof e.__nonzero__?e.__nonzero__():"function"==typeof e.__len__?0<e.__len__():1:1)?D.species.gene.copy():d;if(null===(h=c.__contains__("File"))||!1===h||0===h||""===h?0:"object"==typeof h?"function"==typeof h.__nonzero__?h.__nonzero__():"function"==typeof h.__len__?0<h.__len__():1:1)c=m.os.path.join("data","undefined"!=typeof(v=c).__array?"undefined"!=typeof v.__array.File?v.__array.File:
v.__getitem__("File"):v.__getitem__("File")),v=$p.open(c,"rb"),c=m.cPickle.load(v),v.close();if(null===(g=(null===(b=q=D.matrix.evolution)||!1===b||0===b||""===b?0:"object"==typeof b?"function"==typeof b.__nonzero__?b.__nonzero__():"function"==typeof b.__len__?0<b.__len__():1:1)?D.species.evolving:q)||!1===g||0===g||""===g?0:"object"==typeof g?"function"==typeof g.__nonzero__?g.__nonzero__():"function"==typeof g.__len__?0<g.__len__():1:1)g=null===(f=c)?0:"undefined"!=typeof f.__array?f.__array.length:
"function"==typeof f.__len__?f.__len__():"undefined"!=typeof f.length?f.length:$p.len(f),f=D.species.alleles.copy(),c=D.genetics(d,s,g,f);d=D.set_trait(c);return $p.tuple([c,d])},1,[null,null,["self"],["inherit"],["mutation_rate"]]);a.genotype=b;b=$pyjs__bind_method2("set_gene",function(d,s){if(!0===this.__is_instance__)var c=this;else c=d,d=s;c.gene=d;c.trait=c.set_trait(d);return null},1,[null,null,["self"],["gene"]]);a.set_gene=b;b=$pyjs__bind_method2("evolve",function(d){(!0===this.__is_instance__?
this:d).evolution();return null},1,[null,null,["self"]]);a.evolve=b;b=$pyjs__bind_method2("phenotype",function(d,s,c,D){if(!0===this.__is_instance__)var f=this;else f=d,d=s,s=c,c=D;var g,b,a,h;if(null===(a=s)||!1===a||0===a||""===a?0:"object"==typeof a?"function"==typeof a.__nonzero__?a.__nonzero__():"function"==typeof a.__len__?0<a.__len__():1:1)f.image=("undefined"!=typeof(g=d.image).__array?"undefined"!=typeof g.__array[0]?g.__array[0]:g.__getitem__(0):g.__getitem__(0)).copy(),f.rect=$pyjs_kwargs_call(f.image,
"get_rect",null,null,[{center:$p.tuple([f.x,f.y])}]),(null===(b=1===(h=c)&&null===h?!0:null===h?!1:"object"!=typeof h&&"function"!=typeof h||"function"!=typeof h.__cmp__?1==h:0===h.__cmp__(1))||!1===b||0===b||""===b?0:"object"==typeof b?"function"==typeof b.__nonzero__?b.__nonzero__():"function"==typeof b.__len__?0<b.__len__():1:1)?f.image_multiframe=0:f.image_multiframe=c,f.image_frame=0,f.image_frame_counter=0;return null},1,[null,null,["self"],["species"],["cell_image"],["frames"]]);a.phenotype=
b;b=$pyjs__bind_method2("life_check",function(d){d=!0===this.__is_instance__?this:d;var s;if(null===(s=d.life)||!1===s||0===s||""===s?0:"object"==typeof s?"function"==typeof s.__nonzero__?s.__nonzero__():"function"==typeof s.__len__?0<s.__len__():1:1)return!0;d.species.count-=1;return!1},1,[null,null,["self"]]);a.life_check=b;b=$pyjs__bind_method2("motion",function(d){(!0===this.__is_instance__?this:d).direction=m.random.randrange(360);return null},1,[null,null,["self"]]);a.motion=b;b=$pyjs__bind_method2("move",
function(d){d=!0===this.__is_instance__?this:d;d.motion();d.locate();return null},1,[null,null,["self"]]);a.move=b;b=$pyjs__bind_method2("sense",function(d){return null},1,[null,null,["self"]]);a.sense=b;b=$pyjs__bind_method2("growth",function(d){return null},1,[null,null,["self"]]);a.growth=b;b=$pyjs__bind_method2("locate",function(d){d=!0===this.__is_instance__?this:d;var s,c,b,f,a,l,H,h,e,q,v=$p.__ass_unpack(d.locate_coordinate(d.velocity,d.direction),2,null);d.x=v[0];d.y=v[1];d.check_interact();
if(null===(f=d.matrix.creature_inview(d))||!1===f||0===f||""===f?0:"object"==typeof f?"function"==typeof f.__nonzero__?f.__nonzero__():"function"==typeof f.__len__?0<f.__len__():1:1){if(null===(e=d.image_multiframe)||!1===e||0===e||""===e?0:"object"==typeof e?"function"==typeof e.__nonzero__?e.__nonzero__():"function"==typeof e.__len__?0<e.__len__():1:1){d.image_frame_counter+=1;if(null===(q=1==(2===(a=d.image_frame_counter)?0:"number"!=typeof a||"number"!=typeof a&&"string"!=typeof a&&"boolean"!=
typeof a?$p.cmp(a,2):2==a?0:2>a?-1:1))||!1===q||0===q||""===q?0:"object"==typeof q?"function"==typeof q.__nonzero__?q.__nonzero__():"function"==typeof q.__len__?0<q.__len__():1:1)if(d.image_frame_counter=0,d.image_frame+=1,null===(H=1==(((s=d.image_frame)===(c=d.image_multiframe)?0:typeof s!=typeof c||"number"!=typeof s&&"string"!=typeof s&&"boolean"!=typeof s?$p.cmp(s,c):s==c?0:s<c?-1:1)|1))||!1===H||0===H||""===H?0:"object"==typeof H?"function"==typeof H.__nonzero__?H.__nonzero__():"function"==
typeof H.__len__?0<H.__len__():1:1)d.image_frame=0;d.rotate_image=!0}if(null===(h=d.rotate_image)||!1===h||0===h||""===h?0:"object"==typeof h?"function"==typeof h.__nonzero__?h.__nonzero__():"function"==typeof h.__len__?0<h.__len__():1:1)d.image=m.pygame.transform.rotozoom("undefined"!=typeof(l=d.species.image).__array?"undefined"!=typeof l.__array[b=d.image_frame]?l.__array[b]:l.__getitem__(b):l.__getitem__(d.image_frame),-d.direction,1),d.rotate_image=!1}d.rect=$pyjs_kwargs_call(d.image,"get_rect",
null,null,[{center:$p.tuple([d.x,d.y])}]);return null},1,[null,null,["self"]]);a.locate=b;b=$pyjs__bind_method2("check_interact",function(d){(!0===this.__is_instance__?this:d).check_edge();return null},1,[null,null,["self"]]);a.check_interact=b;b=$pyjs__bind_method2("check_edge",function(d,s){if(!0===this.__is_instance__)var c=this;else c=arguments[0],d=arguments[1],s=arguments[2];"undefined"==typeof d&&(d=arguments.callee.__args__[3][1]);"undefined"==typeof s&&(s=arguments.callee.__args__[4][1]);
var a,f,b,l,m,h,e,q,v,t,w,n,p,r,u,y,B,z,A,k,C,x,E;C=0+d;h=c.matrix.x-1-d;y=0+s;w=c.matrix.y-1-s;if(null===(z=(null===(A=v=-1==((a=c.x)===C?0:typeof a!=typeof C||"number"!=typeof a&&"string"!=typeof a&&"boolean"!=typeof a?$p.cmp(a,C):a==C?0:a<C?-1:1))||!1===A||0===A||""===A?0:"object"==typeof A?"function"==typeof A.__nonzero__?A.__nonzero__():"function"==typeof A.__len__?0<A.__len__():1:1)?v:(null===(k=q=1==((f=c.x)===h?0:typeof f!=typeof h||"number"!=typeof f&&"string"!=typeof f&&"boolean"!=typeof f?
$p.cmp(f,h):f==h?0:f<h?-1:1))||!1===k||0===k||""===k?0:"object"==typeof k?"function"==typeof k.__nonzero__?k.__nonzero__():"function"==typeof k.__len__?0<k.__len__():1:1)?q:(null===(B=e=-1==((b=c.y)===y?0:typeof b!=typeof y||"number"!=typeof b&&"string"!=typeof b&&"boolean"!=typeof b?$p.cmp(b,y):b==y?0:b<y?-1:1))||!1===B||0===B||""===B?0:"object"==typeof B?"function"==typeof B.__nonzero__?B.__nonzero__():"function"==typeof B.__len__?0<B.__len__():1:1)?e:1==((l=c.y)===w?0:typeof l!=typeof w||"number"!=
typeof l&&"string"!=typeof l&&"boolean"!=typeof l?$p.cmp(l,w):l==w?0:l<w?-1:1))||!1===z||0===z||""===z?0:"object"==typeof z?"function"==typeof z.__nonzero__?z.__nonzero__():"function"==typeof z.__len__?0<z.__len__():1:1){if(null===(x=-1==((u=c.x)===C?0:typeof u!=typeof C||"number"!=typeof u&&"string"!=typeof u&&"boolean"!=typeof u?$p.cmp(u,C):u==C?0:u<C?-1:1))||!1===x||0===x||""===x?0:"object"==typeof x?"function"==typeof x.__nonzero__?x.__nonzero__():"function"==typeof x.__len__?0<x.__len__():1:
1)c.x=C;else if(null===(E=1==((r=c.x)===h?0:typeof r!=typeof h||"number"!=typeof r&&"string"!=typeof r&&"boolean"!=typeof r?$p.cmp(r,h):r==h?0:r<h?-1:1))||!1===E||0===E||""===E?0:"object"==typeof E?"function"==typeof E.__nonzero__?E.__nonzero__():"function"==typeof E.__len__?0<E.__len__():1:1)c.x=h;if(null===(t=-1==((p=c.y)===y?0:typeof p!=typeof y||"number"!=typeof p&&"string"!=typeof p&&"boolean"!=typeof p?$p.cmp(p,y):p==y?0:p<y?-1:1))||!1===t||0===t||""===t?0:"object"==typeof t?"function"==typeof t.__nonzero__?
t.__nonzero__():"function"==typeof t.__len__?0<t.__len__():1:1)c.y=y;else if(null===(m=1==((n=c.y)===w?0:typeof n!=typeof w||"number"!=typeof n&&"string"!=typeof n&&"boolean"!=typeof n?$p.cmp(n,w):n==w?0:n<w?-1:1))||!1===m||0===m||""===m?0:"object"==typeof m?"function"==typeof m.__nonzero__?m.__nonzero__():"function"==typeof m.__len__?0<m.__len__():1:1)c.y=w;a=$p.__ass_unpack($p.tuple([$p["float"](c.x),$p["float"](c.y)]),2,null);c.pos_x=a[0];c.pos_y=a[1];return!0}return!1},1,[null,null,["self"],["margin_x",
0],["margin_y",0]]);a.check_edge=b;b=$pyjs__bind_method2("locate_coordinate",function(d,a,c){if(!0===this.__is_instance__)var b=this;else b=arguments[0],d=arguments[1],a=arguments[2],c=arguments[3];"undefined"==typeof c&&(c=arguments.callee.__args__[5][1]);var f,g,l,k,h,e,q;q=b.pos_x;e=b.pos_y;q+=d*("undefined"!=typeof(l=m.sin_table).__array?"undefined"!=typeof l.__array[h=a]?l.__array[h]:l.__getitem__(h):l.__getitem__(a));e+=-d*("undefined"!=typeof(k=m.cos_table).__array?"undefined"!=typeof k.__array[f=
a]?k.__array[f]:k.__getitem__(f):k.__getitem__(a));if(null===(g=c)||!1===g||0===g||""===g?0:"object"==typeof g?"function"==typeof g.__nonzero__?g.__nonzero__():"function"==typeof g.__len__?0<g.__len__():1:1)b.pos_x=q,b.pos_y=e;return $p.tuple([$p.float_int(q),$p.float_int(e)])},1,[null,null,["self"],["step"],["direction"],["change",!0]]);a.locate_coordinate=b;b=$pyjs__bind_method2("direction_set",function(d,a){!0!==this.__is_instance__&&(d=a);var c,b,f,g;if(null===(b=1==((360===(f=d)?0:"number"!=
typeof f||"number"!=typeof f&&"string"!=typeof f&&"boolean"!=typeof f?$p.cmp(f,360):360==f?0:360>f?-1:1)|1))||!1===b||0===b||""===b?0:"object"==typeof b?"function"==typeof b.__nonzero__?b.__nonzero__():"function"==typeof b.__len__?0<b.__len__():1:1)d-=360;else if(null===(c=-1==(0===(g=d)?0:"number"!=typeof g||"number"!=typeof g&&"string"!=typeof g&&"boolean"!=typeof g?$p.cmp(g,0):0==g?0:0>g?-1:1))||!1===c||0===c||""===c?0:"object"==typeof c?"function"==typeof c.__nonzero__?c.__nonzero__():"function"==
typeof c.__len__?0<c.__len__():1:1)d+=360;return d},1,[null,null,["self"],["direction"]]);a.direction_set=b;b=$pyjs__bind_method2("cell_division",function(d){if(!0===this.__is_instance__)var b=this;else b=arguments[0],d=arguments[1];"undefined"==typeof d&&(d=arguments.callee.__args__[3][1]);var c,a,f,g;if(null===(a=b.fission)||!1===a||0===a||""===a?0:"object"==typeof a?"function"==typeof a.__nonzero__?a.__nonzero__():"function"==typeof a.__len__?0<a.__len__():1:1)if(b.fission+=1,null===(c=1==((f=
b.fission)===(g=d)?0:typeof f!=typeof g||"number"!=typeof f&&"string"!=typeof f&&"boolean"!=typeof f?$p.cmp(f,g):f==g?0:f<g?-1:1))||!1===c||0===c||""===c?0:"object"==typeof c?"function"==typeof c.__nonzero__?c.__nonzero__():"function"==typeof c.__len__?0<c.__len__():1:1)return b.fission=0,!0;return!1},1,[null,null,["self"],["time",500]]);a.cell_division=b;b=$pyjs__bind_method2("activity",function(d){d=!0===this.__is_instance__?this:d;d.move();d.growth();return null},1,[null,null,["self"]]);a.activity=
b;b=$pyjs__bind_method2("update",function(d){d=!0===this.__is_instance__?this:d;var a,c,b,f,g;d.activity();if(null===(f=(null===(a=b=d.matrix.evolution)||!1===a||0===a||""===a?0:"object"==typeof a?"function"==typeof a.__nonzero__?a.__nonzero__():"function"==typeof a.__len__?0<a.__len__():1:1)?d.species.evolving:b)||!1===f||0===f||""===f?0:"object"==typeof f?"function"==typeof f.__nonzero__?f.__nonzero__():"function"==typeof f.__len__?0<f.__len__():1:1)(null===(g=!("pause"===(c=d.species.evolving)&&
null===c||(null===c?0:"object"!=typeof c&&"function"!=typeof c||"function"!=typeof c.__cmp__?"pause"==c:0===c.__cmp__("pause"))))||!1===g||0===g||""===g?0:"object"==typeof g?"function"==typeof g.__nonzero__?g.__nonzero__():"function"==typeof g.__len__?0<g.__len__():1:1)?d.evolve():(d.display_tag(!1),d.species.evolving=!1);return null},1,[null,null,["self"]]);a.update=b;b=[m.pygame.sprite.Sprite,m.Evolve];var x=$p.dict(),k;for(k in a)x.__setitem__(k,a[k]);return $p._create_class("Cell",$p.tuple(b),
x)}();m.Bacterium=function(){var a={},b;a.__module__="cells";a.image=null;a.count=0;a.id=0;a.evolving=!1;a.gene=$p.dict([[1,1],[2,11]]);a.alleles=$p.dict([[1,$p.tuple([0,2])],[2,$p.tuple([2,12])]]);a.gene_info=$p.dict([[1,"Sense[0]"],[2,"Sense[1]"]]);b=$pyjs__bind_method2("__init__",function(d,a,c,b,f,g,l,k,h){if(!0===this.__is_instance__)var e=this;else e=arguments[0],d=arguments[1],a=arguments[2],c=arguments[3],b=arguments[4],f=arguments[5],g=arguments[6],l=arguments[7],k=arguments[8],h=arguments[9];
"undefined"==typeof b&&(b=arguments.callee.__args__[6][1]);"undefined"==typeof f&&(f=arguments.callee.__args__[7][1]);"undefined"==typeof g&&(g=arguments.callee.__args__[8][1]);"undefined"==typeof l&&(l=arguments.callee.__args__[9][1]);"undefined"==typeof k&&(k=arguments.callee.__args__[10][1]);"undefined"==typeof h&&(h=arguments.callee.__args__[11][1]);m.Cell.__init__(e,d,a,c,b,f,g,l,k,h);e.sense_previous=0;e.sense_previous_toxin=0;e.sense_bacteria=1;e.growth_rate=1;e.ingest=25E3;e.max_ingest=1E4;
e.nutrient=0;e.consumption=0;e.velocity=2;return null},1,[null,null,["self"],["matrix"],["x"],["y"],["cell_image","bacterium.png"],["frames",1],["identity",null],["inherit",null],["mutation_rate",0.5],["limit",$p.tuple([90,500])]]);a.__init__=b;b=$pyjs__bind_method2("set_trait",function(d,a){!0!==this.__is_instance__&&(d=a);var c;c=function(){var a,c;return m.random.randrange("undefined"!=typeof(a=d).__array?"undefined"!=typeof a.__array[1]?a.__array[1]:a.__getitem__(1):a.__getitem__(1),"undefined"!=
typeof(c=d).__array?"undefined"!=typeof c.__array[2]?c.__array[2]:c.__getitem__(2):c.__getitem__(2))};c.__name__="$lambda1";c.__bind_type__=0;c.__args__=[null,null];return $p.dict([["sense",c]])},1,[null,null,["self"],["gene"]]);a.set_trait=b;b=$pyjs__bind_method2("evolve",function(d){$pyjs_kwargs_call(!0===this.__is_instance__?this:d,"evolution",null,null,[{cycle:1,division_threshold:1E5}]);return null},1,[null,null,["self"]]);a.evolve=b;b=$pyjs__bind_method2("sense",function(d){if(!0===this.__is_instance__)var a=
this;else a=arguments[0],d=arguments[1];"undefined"==typeof d&&(d=arguments.callee.__args__[3][1]);var c,b,f,g,l,k,h,e,q,v,t,w,n,p,r,u,y,B,z,A,x,C,J,E,F,K;try{(null===(b=a.sensing)||!1===b||0===b||""===b?0:"object"==typeof b?"function"==typeof b.__nonzero__?b.__nonzero__():"function"==typeof b.__len__?0<b.__len__():1:1)?q=1:(null===(f=1==(100===(e="undefined"!=typeof(E="undefined"!=typeof(F=a.matrix.nutrient).__array?"undefined"!=typeof F.__array[J=a.x]?F.__array[J]:F.__getitem__(J):F.__getitem__(a.x)).__array?
"undefined"!=typeof E.__array[x=a.y]?E.__array[x]:E.__getitem__(x):E.__getitem__(a.y))?0:"number"!=typeof e||"number"!=typeof e&&"string"!=typeof e&&"boolean"!=typeof e?$p.cmp(e,100):100==e?0:100>e?-1:1))||!1===f||0===f||""===f?0:"object"==typeof f?"function"==typeof f.__nonzero__?f.__nonzero__():"function"==typeof f.__len__?0<f.__len__():1:1)?q=-1:(a.sensing=!0,q=1);if(null===(g="nutrient"===d)||!1===g||0===g||""===g?0:"object"==typeof g?"function"==typeof g.__nonzero__?g.__nonzero__():"function"==
typeof g.__len__?0<g.__len__():1:1){if(null===(l=1==((h="undefined"!=typeof(A="undefined"!=typeof(C=a.matrix.nutrient).__array?"undefined"!=typeof C.__array[z=a.x]?C.__array[z]:C.__getitem__(z):C.__getitem__(a.x)).__array?"undefined"!=typeof A.__array[r=a.y]?A.__array[r]:A.__getitem__(r):A.__getitem__(a.y))===(k=a.sense_previous)?0:typeof h!=typeof k||"number"!=typeof h&&"string"!=typeof h&&"boolean"!=typeof h?$p.cmp(h,k):h==k?0:h<k?-1:1))||!1===l||0===l||""===l?0:"object"==typeof l?"function"==typeof l.__nonzero__?
l.__nonzero__():"function"==typeof l.__len__?0<l.__len__():1:1)return a.sense_previous="undefined"!=typeof(w="undefined"!=typeof(p=a.matrix.nutrient).__array?"undefined"!=typeof p.__array[n=a.x]?p.__array[n]:p.__getitem__(n):p.__getitem__(a.x)).__array?"undefined"!=typeof w.__array[B=a.y]?w.__array[B]:w.__getitem__(B):w.__getitem__(a.y),0.02*("undefined"!=typeof(y=a.trait).__array?"undefined"!=typeof y.__array.sense?y.__array.sense:y.__getitem__("sense"):y.__getitem__("sense"))()*q;a.sense_previous=
"undefined"!=typeof(v="undefined"!=typeof(u=a.matrix.nutrient).__array?"undefined"!=typeof u.__array[t=a.x]?u.__array[t]:u.__getitem__(t):u.__getitem__(a.x)).__array?"undefined"!=typeof v.__array[K=a.y]?v.__array[K]:v.__getitem__(K):v.__getitem__(a.y);return 0}if(null===(c="toxin"===d)||!1===c||0===c||""===c?0:"object"==typeof c?"function"==typeof c.__nonzero__?c.__nonzero__():"function"==typeof c.__len__?0<c.__len__():1:1)return 0}catch(G){a="undefined"==typeof G.__name__?G.name:G.__name__;$pyjs.__last_exception__=
{error:G,module:m};if(a==$p.IndexError.__name__||$p._isinstance(G,$p.IndexError))return 0;$pyjs.__active_exception_stack__=$pyjs.__last_exception_stack__;$pyjs.__last_exception_stack__=null;throw G;}return null},1,[null,null,["self"],["substance","nutrient"]]);a.sense=b;b=$pyjs__bind_method2("motor_check",function(d){d=!0===this.__is_instance__?this:d;var a,c,b;return(null===(a=1==((c=m.random.random())===(b=0.1*d.velocity-d.sense("nutrient")*d.velocity-d.sense("toxin")*d.velocity)?0:typeof c!=typeof b||
"number"!=typeof c&&"string"!=typeof c&&"boolean"!=typeof c?$p.cmp(c,b):c==b?0:c<b?-1:1))||!1===a||0===a||""===a?0:"object"==typeof a?"function"==typeof a.__nonzero__?a.__nonzero__():"function"==typeof a.__len__?0<a.__len__():1:1)?!0:!1},1,[null,null,["self"]]);a.motor_check=b;b=$pyjs__bind_method2("motion",function(a){a=!0===this.__is_instance__?this:a;var b,c,k,f,g,l;(null===(k=!(null===(c=a.fission)||!1===c||0===c||""===c?0:"object"==typeof c?"function"==typeof c.__nonzero__?c.__nonzero__():"function"==
typeof c.__len__?0<c.__len__():1:1))||!1===k||0===k||""===k?0:"object"==typeof k?"function"==typeof k.__nonzero__?k.__nonzero__():"function"==typeof k.__len__?0<k.__len__():1:1)?(null===(g=a.motor_check())||!1===g||0===g||""===g?0:"object"==typeof g?"function"==typeof g.__nonzero__?g.__nonzero__():"function"==typeof g.__len__?0<g.__len__():1:1)?c=0:(c=m.random.randrange(360),a.rotate_image=!0):(null===(f=1==(0.2===(l=m.random.random())?0:"number"!=typeof l||"number"!=typeof l&&"string"!=typeof l&&
"boolean"!=typeof l?$p.cmp(l,0.2):0.2==l?0:0.2>l?-1:1))||!1===f||0===f||""===f?0:"object"==typeof f?"function"==typeof f.__nonzero__?f.__nonzero__():"function"==typeof f.__len__?0<f.__len__():1:1)?(c=a.direction_set(a.direction+180),c=m.random.choice($p.tuple([a.direction,c]))):c=0;if(null===(b=c)||!1===b||0===b||""===b?0:"object"==typeof b?"function"==typeof b.__nonzero__?b.__nonzero__():"function"==typeof b.__len__?0<b.__len__():1:1)a.direction=c;return null},1,[null,null,["self"]]);a.motion=b;
b=$pyjs__bind_method2("growth",function(a){a=!0===this.__is_instance__?this:a;var b,c,k,f,g,l,x,h,e,q,v,t,w,n,p,r,u,y,B,z,A,I,C,J,E,F,K,G,M,L,S,N,O,P,Q;if(null===(A=(null===(I=k=!(null===(z=a.fission)||!1===z||0===z||""===z?0:"object"==typeof z?"function"==typeof z.__nonzero__?z.__nonzero__():"function"==typeof z.__len__?0<z.__len__():1:1))||!1===I||0===I||""===I?0:"object"==typeof I?"function"==typeof I.__nonzero__?I.__nonzero__():"function"==typeof I.__len__?0<I.__len__():1:1)?-1==((t=a.species.count)===
(n=a.species.maximum)?0:typeof t!=typeof n||"number"!=typeof t&&"string"!=typeof t&&"boolean"!=typeof t?$p.cmp(t,n):t==n?0:t<n?-1:1):k)||!1===A||0===A||""===A?0:"object"==typeof A?"function"==typeof A.__nonzero__?A.__nonzero__():"function"==typeof A.__len__?0<A.__len__():1:1)try{a.nutrient=0.01*("undefined"!=typeof(S="undefined"!=typeof(v=a.matrix.nutrient).__array?"undefined"!=typeof v.__array[M=a.x]?v.__array[M]:v.__getitem__(M):v.__getitem__(a.x)).__array?"undefined"!=typeof S.__array[Q=a.y]?S.__array[Q]:
S.__getitem__(Q):S.__getitem__(a.y));(null===(J=-1==((w=a.nutrient)===(r=a.max_ingest)?0:typeof w!=typeof r||"number"!=typeof w&&"string"!=typeof w&&"boolean"!=typeof w?$p.cmp(w,r):w==r?0:w<r?-1:1))||!1===J||0===J||""===J?0:"object"==typeof J?"function"==typeof J.__nonzero__?J.__nonzero__():"function"==typeof J.__len__?0<J.__len__():1:1)?a.consumption=a.nutrient*a.growth_rate:a.consumption=a.max_ingest*a.growth_rate;a.ingest+=a.consumption;if(null===(E=(null===(C=b=1==(1E5===(p=a.ingest)?0:"number"!=
typeof p||"number"!=typeof p&&"string"!=typeof p&&"boolean"!=typeof p?$p.cmp(p,1E5):1E5==p?0:1E5>p?-1:1))||!1===C||0===C||""===C?0:"object"==typeof C?"function"==typeof C.__nonzero__?C.__nonzero__():"function"==typeof C.__len__?0<C.__len__():1:1)?!(null===(F=a.species.evolving)||!1===F||0===F||""===F?0:"object"==typeof F?"function"==typeof F.__nonzero__?F.__nonzero__():"function"==typeof F.__len__?0<F.__len__():1:1):b)||!1===E||0===E||""===E?0:"object"==typeof E?"function"==typeof E.__nonzero__?E.__nonzero__():
"function"==typeof E.__len__?0<E.__len__():1:1)if(null===(K=!(null===(G=m.random.randrange(10))||!1===G||0===G||""===G?0:"object"==typeof G?"function"==typeof G.__nonzero__?G.__nonzero__():"function"==typeof G.__len__?0<G.__len__():1:1))||!1===K||0===K||""===K?0:"object"==typeof K?"function"==typeof K.__nonzero__?K.__nonzero__():"function"==typeof K.__len__?0<K.__len__():1:1)a.fission=1,a.ingest=0,a.velocity=1;c=a.y;L="undefined"!=typeof(u=a.matrix.nutrient).__array?"undefined"!=typeof u.__array[y=
a.x]?u.__array[y]:u.__getitem__(y):u.__getitem__(a.x);L.__setitem__(c,("undefined"!=typeof L.__array?"undefined"!=typeof L.__array[c]?L.__array[c]:L.__getitem__(c):L.__getitem__(c))-a.consumption);(null===(O=-1==(0===(q="undefined"!=typeof(h="undefined"!=typeof(l=a.matrix.nutrient).__array?"undefined"!=typeof l.__array[g=a.x]?l.__array[g]:l.__getitem__(g):l.__getitem__(a.x)).__array?"undefined"!=typeof h.__array[e=a.y]?h.__array[e]:h.__getitem__(e):h.__getitem__(a.y))?0:"number"!=typeof q||"number"!=
typeof q&&"string"!=typeof q&&"boolean"!=typeof q?$p.cmp(q,0):0==q?0:0>q?-1:1))||!1===O||0===O||""===O?0:"object"==typeof O?"function"==typeof O.__nonzero__?O.__nonzero__():"function"==typeof O.__len__?0<O.__len__():1:1)&&("undefined"!=typeof(x=a.matrix.nutrient).__array?"undefined"!=typeof x.__array[f=a.x]?x.__array[f]:x.__getitem__(f):x.__getitem__(a.x)).__setitem__(a.y,0)}catch(R){b="undefined"==typeof R.__name__?R.name:R.__name__;$pyjs.__last_exception__={error:R,module:m};if(b==$p.IndexError.__name__||
$p._isinstance(R,$p.IndexError))return null;$pyjs.__active_exception_stack__=$pyjs.__last_exception_stack__;$pyjs.__last_exception_stack__=null;throw R;}if(null===(P=a.cell_division())||!1===P||0===P||""===P?0:"object"==typeof P?"function"==typeof P.__nonzero__?P.__nonzero__():"function"==typeof P.__len__?0<P.__len__():1:1)$pyjs_kwargs_call(a.matrix,"add_creature",null,null,[{clone:!0,inherit:a.gene.copy()},a.species,a.x,a.y]),a.velocity=2,(null===(N=-1==(0.9===(B=m.random.random())?0:"number"!=typeof B||
"number"!=typeof B&&"string"!=typeof B&&"boolean"!=typeof B?$p.cmp(B,0.9):0.9==B?0:0.9>B?-1:1))||!1===N||0===N||""===N?0:"object"==typeof N?"function"==typeof N.__nonzero__?N.__nonzero__():"function"==typeof N.__len__?0<N.__len__():1:1)?a.sensing=!0:a.sensing=!1,a.sense_bacteria=1;return null},1,[null,null,["self"]]);a.growth=b;b=$pyjs__bind_method2("activity",function(a){m.Cell.activity(!0===this.__is_instance__?this:a);return null},1,[null,null,["self"]]);a.activity=b;b=Array(m.Cell);var x=$p.dict(),
k;for(k in a)x.__setitem__(k,a[k]);return $p._create_class("Bacterium",$p.tuple(b),x)}();m.Algae=function(){var a={__module__:"cells"},b=Array(m.Cell),x=$p.dict(),k;for(k in a)x.__setitem__(k,a[k]);return $p._create_class("Algae",$p.tuple(b),x)}();m.Paramecium=function(){var a={__module__:"cells"},b=Array(m.Cell),x=$p.dict(),k;for(k in a)x.__setitem__(k,a[k]);return $p._create_class("Paramecium",$p.tuple(b),x)}();m.Amoeba=function(){var a={__module__:"cells"},b=Array(m.Cell),x=$p.dict(),k;for(k in a)x.__setitem__(k,
a[k]);return $p._create_class("Amoeba",$p.tuple(b),x)}();m.Ciliate=function(){var a={__module__:"cells"},b=Array(m.Paramecium),x=$p.dict(),k;for(k in a)x.__setitem__(k,a[k]);return $p._create_class("Ciliate",$p.tuple(b),x)}();return this};
