$pyjs.loaded_modules["microbe_bacterium_app.microbe"]=function(b){if($pyjs.loaded_modules["microbe_bacterium_app.microbe"].__was_initialized__)return $pyjs.loaded_modules["microbe_bacterium_app.microbe"];"undefined"!=typeof $pyjs.loaded_modules.microbe_bacterium_app&&$pyjs.loaded_modules.microbe_bacterium_app.__was_initialized__||$p.___import___("microbe_bacterium_app",null);var a=$pyjs.loaded_modules["microbe_bacterium_app.microbe"];a.__repr__=function(){return"<module: microbe_bacterium_app.microbe>"};
a.__was_initialized__=!0;if(null===b||"undefined"==typeof b)b="microbe_bacterium_app.microbe";a.__name__=b;$pyjs.loaded_modules.microbe_bacterium_app.microbe=$pyjs.loaded_modules["microbe_bacterium_app.microbe"];var g,h,k,r,t,n,p,M,s;a.version="1.23";a.monitoring=!1;a.profiling=!1;try{a.pygame=$p.___import___("pyjsdl","microbe_bacterium_app",null,!1)}catch(u){b="undefined"==typeof u.__name__?u.name:u.__name__;$pyjs.__last_exception__={error:u,module:a};if(b==$p.ImportError.__name__||$p._isinstance(u,
$p.ImportError)){b=$p.ImportError;if(!0===b.__is_instance__)throw $p.TypeError("instance exception may not have a separate value");if($p.isinstance("Pygame and Numpy modules are required.",$p.tuple))throw b.apply(b,"Pygame and Numpy modules are required.".getArray());throw b("Pygame and Numpy modules are required.");}$pyjs.__active_exception_stack__=$pyjs.__last_exception_stack__;$pyjs.__last_exception_stack__=null;throw u;}a.Matrix=$p.___import___("matrix.Matrix","microbe_bacterium_app",null,!1);
a.Control=$p.___import___("control.Control","microbe_bacterium_app",null,!1);a.Bacterium=$p.___import___("cells.Bacterium","microbe_bacterium_app",null,!1);a.util=$p.___import___("util","microbe_bacterium_app");a.program_options=function(){var f,m,z,A,B,b,g,h,k,r,d,e,t,l,q,v,w,x,n,p,C,s,F,G,u,y,I,M,P,N,T,Q,O,c,R,D,E,S;c=$p.dict([["species_added",null],["species_evolving",null],["display_gamma",null]]);try{R=$p.open("config.ini");O=function(){var a,c,f,d,b,m,e;f=$p.list();d=R;"undefined"!=typeof(e=
d.__array)?c=0:(d=d.__iter__(),c="undefined"!=typeof(e=d.__array)?0:"function"==typeof d.$genfunc?1:-1);for(m=0;"undefined"!=typeof(a=c?0<c?d.next(!0,!1):$p.wrapped_next(d):e[m++]);)(null===(b=$p.__getslice(a,0,1).isalpha())||!1===b||0===b||""===b?0:"object"==typeof b?"function"==typeof b.__nonzero__?b.__nonzero__():"function"==typeof b.__len__?0<b.__len__():1:1)&&f.append(a.strip().$$split(" ",1));return f}();O=$p.dict(O);y=c;"undefined"!=typeof(I=y.__array)?e=0:(y=y.__iter__(),e="undefined"!=typeof(I=
y.__array)?0:"function"==typeof y.$genfunc?1:-1);for(M=0;"undefined"!=typeof(T=e?0<e?y.next(!0,!1):$p.wrapped_next(y):I[M++]);)C=T,(null===(d=O.__contains__(C))||!1===d||0===d||""===d?0:"object"==typeof d?"function"==typeof d.__nonzero__?d.__nonzero__():"function"==typeof d.__len__?0<d.__len__():1:1)&&c.__setitem__(C,("undefined"!=typeof(N=O).__array?"undefined"!=typeof N.__array[P=C]?N.__array[P]:N.__getitem__(P):N.__getitem__(C)).strip());R.close()}catch(H){if(d="undefined"==typeof H.__name__?H.name:
H.__name__,$pyjs.__last_exception__={error:H,module:a},d!=("undefined"==typeof IOError?a.IOError:IOError).__name__&&!$p._isinstance(H,"undefined"==typeof IOError?a.IOError:IOError)&&d!=$p.ValueError.__name__&&!$p._isinstance(H,$p.ValueError))throw $pyjs.__active_exception_stack__=$pyjs.__last_exception_stack__,$pyjs.__last_exception_stack__=null,H;}e=$pyjs_kwargs_call(a.optparse,"OptionParser",null,null,[{usage:"%prog [options]",description:"Microbe - Microbial Simulation"}]);e=$pyjs_kwargs_call(a.optparse,
"OptionParser",null,null,[{version:"Microbe "+a.version}]);$pyjs_kwargs_call(e,"set_defaults",null,null,[{evolve:!1}]);$pyjs_kwargs_call(e,"add_option",null,null,[{dest:"license",action:"store_true",help:"display program license"},"--license"]);$pyjs_kwargs_call(e,"add_option",null,null,[{dest:"doc",action:"store_true",help:"display program documentation"},"-d","--doc"]);$pyjs_kwargs_call(e,"add_option",null,null,[{dest:"species_added",action:"store",help:"-s algae:bacterium:paramecium:amoeba:ciliate"},
"-s"]);$pyjs_kwargs_call(e,"add_option",null,null,[{dest:"species_evolving",action:"store",help:"-e bacterium:paramecium:amoeba:ciliate"},"-e"]);$pyjs_kwargs_call(e,"add_option",null,null,[{dest:"display_gamma",action:"store",help:"-g value (value: 0.5 to 3.0)"},"-g"]);e=$p.__ass_unpack(e.parse_args(),2,null)[0];if(null===(l=e.license)||!1===l||0===l||""===l?0:"object"==typeof l?"function"==typeof l.__nonzero__?l.__nonzero__():"function"==typeof l.__len__?0<l.__len__():1:1){try{Q=$p.open("license.txt")}catch(J){if(d=
"undefined"==typeof J.__name__?J.name:J.__name__,$pyjs.__last_exception__={error:J,module:a},d==("undefined"==typeof IOError?a.IOError:IOError).__name__||$p._isinstance(J,"undefined"==typeof IOError?a.IOError:IOError))a.sys.exit();else throw $pyjs.__active_exception_stack__=$pyjs.__last_exception_stack__,$pyjs.__last_exception_stack__=null,J;}d=$p.enumerate(Q);"undefined"!=typeof(I=d.__array)?C=0:(d=d.__iter__(),C="undefined"!=typeof(I=d.__array)?0:"function"==typeof d.$genfunc?1:-1);for(y=0;"undefined"!=
typeof(l=C?0<C?d.next(!0,!1):$p.wrapped_next(d):I[y++]);)if(l=$p.__ass_unpack(l,2,null)[0],null===(q=(null===(w=r=l)||!1===w||0===w||""===w?0:"object"==typeof w?"function"==typeof w.__nonzero__?w.__nonzero__():"function"==typeof w.__len__?0<w.__len__():1:1)?!(null===(x=null!=(F=l)&&null!=(u=20)&&"string"==typeof F?$p.sprintf(F,u):0>(F%=u)&&0<u?F+u:F)||!1===x||0===x||""===x?0:"object"==typeof x?"function"==typeof x.__nonzero__?x.__nonzero__():"function"==typeof x.__len__?0<x.__len__():1:1):r)||!1===
q||0===q||""===q?0:"object"==typeof q?"function"==typeof q.__nonzero__?q.__nonzero__():"function"==typeof q.__len__?0<q.__len__():1:1)if(l=("undefined"==typeof raw_input?a.raw_input:raw_input)("press enter to continue, 'q' to quit: "),null===(v="q"===(E=l)&&null===E?!0:null===E?!1:"object"!=typeof E&&"function"!=typeof E||"function"!=typeof E.__cmp__?"q"==E:0===E.__cmp__("q"))||!1===v||0===v||""===v?0:"object"==typeof v?"function"==typeof v.__nonzero__?v.__nonzero__():"function"==typeof v.__len__?
0<v.__len__():1:1)break;Q.close();a.sys.exit()}if(null===(n=e.doc)||!1===n||0===n||""===n?0:"object"==typeof n?"function"==typeof n.__nonzero__?n.__nonzero__():"function"==typeof n.__len__?0<n.__len__():1:1){try{S=$p.open("readme.txt")}catch(K){if(d="undefined"==typeof K.__name__?K.name:K.__name__,$pyjs.__last_exception__={error:K,module:a},d==("undefined"==typeof IOError?a.IOError:IOError).__name__||$p._isinstance(K,"undefined"==typeof IOError?a.IOError:IOError))a.sys.exit();else throw $pyjs.__active_exception_stack__=
$pyjs.__last_exception_stack__,$pyjs.__last_exception_stack__=null,K;}q=$p.enumerate(S);"undefined"!=typeof(v=q.__array)?r=0:(q=q.__iter__(),r="undefined"!=typeof(v=q.__array)?0:"function"==typeof q.$genfunc?1:-1);for(w=0;"undefined"!=typeof(x=r?0<r?q.next(!0,!1):$p.wrapped_next(q):v[w++]);)if(l=$p.__ass_unpack(x,2,null)[0],null===(z=(null===(p=t=l)||!1===p||0===p||""===p?0:"object"==typeof p?"function"==typeof p.__nonzero__?p.__nonzero__():"function"==typeof p.__len__?0<p.__len__():1:1)?!(null===
(m=null!=(G=l)&&null!=(s=20)&&"string"==typeof G?$p.sprintf(G,s):0>(G%=s)&&0<s?G+s:G)||!1===m||0===m||""===m?0:"object"==typeof m?"function"==typeof m.__nonzero__?m.__nonzero__():"function"==typeof m.__len__?0<m.__len__():1:1):t)||!1===z||0===z||""===z?0:"object"==typeof z?"function"==typeof z.__nonzero__?z.__nonzero__():"function"==typeof z.__len__?0<z.__len__():1:1)if(l=("undefined"==typeof raw_input?a.raw_input:raw_input)("press enter to continue, 'q' to quit: "),null===(A="q"===(D=l)&&null===
D?!0:null===D?!1:"object"!=typeof D&&"function"!=typeof D||"function"!=typeof D.__cmp__?"q"==D:0===D.__cmp__("q"))||!1===A||0===A||""===A?0:"object"==typeof A?"function"==typeof A.__nonzero__?A.__nonzero__():"function"==typeof A.__len__?0<A.__len__():1:1)break;S.close();a.sys.exit()}(null===(B=e.species_added)||!1===B||0===B||""===B?0:"object"==typeof B?"function"==typeof B.__nonzero__?B.__nonzero__():"function"==typeof B.__len__?0<B.__len__():1:1)&&c.__setitem__("species_added",e.species_added);
(null===(b=e.species_evolving)||!1===b||0===b||""===b?0:"object"==typeof b?"function"==typeof b.__nonzero__?b.__nonzero__():"function"==typeof b.__len__?0<b.__len__():1:1)&&c.__setitem__("species_evolving",e.species_evolving);(null===(g=e.display_gamma)||!1===g||0===g||""===g?0:"object"==typeof g?"function"==typeof g.__nonzero__?g.__nonzero__():"function"==typeof g.__len__?0<g.__len__():1:1)&&c.__setitem__("display_gamma",e.display_gamma);if(null===(h="undefined"!=typeof c.__array?"undefined"!=typeof c.__array.species_added?
c.__array.species_added:c.__getitem__("species_added"):c.__getitem__("species_added"))||!1===h||0===h||""===h?0:"object"==typeof h?"function"==typeof h.__nonzero__?h.__nonzero__():"function"==typeof h.__len__?0<h.__len__():1:1)c.__setitem__("species_added",("undefined"!=typeof c.__array?"undefined"!=typeof c.__array.species_added?c.__array.species_added:c.__getitem__("species_added"):c.__getitem__("species_added")).lower().$$split(":")),c.__setitem__("species_added",function(){var a,f,d,b,m,e;d=$p.list();
b="undefined"!=typeof c.__array?"undefined"!=typeof c.__array.species_added?c.__array.species_added:c.__getitem__("species_added"):c.__getitem__("species_added");"undefined"!=typeof(m=b.__array)?e=0:(b=b.__iter__(),e="undefined"!=typeof(m=b.__array)?0:"function"==typeof b.$genfunc?1:-1);for(f=0;"undefined"!=typeof(a=e?0<e?b.next(!0,!1):$p.wrapped_next(b):m[f++]);)d.append(a.strip());return d}());if(null===(k="undefined"!=typeof c.__array?"undefined"!=typeof c.__array.species_evolving?c.__array.species_evolving:
c.__getitem__("species_evolving"):c.__getitem__("species_evolving"))||!1===k||0===k||""===k?0:"object"==typeof k?"function"==typeof k.__nonzero__?k.__nonzero__():"function"==typeof k.__len__?0<k.__len__():1:1)c.__setitem__("species_evolving",("undefined"!=typeof c.__array?"undefined"!=typeof c.__array.species_evolving?c.__array.species_evolving:c.__getitem__("species_evolving"):c.__getitem__("species_evolving")).lower().$$split(":")),c.__setitem__("species_evolving",function(){var a,f,b,d,m,e;d=$p.list();
e="undefined"!=typeof c.__array?"undefined"!=typeof c.__array.species_evolving?c.__array.species_evolving:c.__getitem__("species_evolving"):c.__getitem__("species_evolving");"undefined"!=typeof(m=e.__array)?f=0:(e=e.__iter__(),f="undefined"!=typeof(m=e.__array)?0:"function"==typeof e.$genfunc?1:-1);for(a=0;"undefined"!=typeof(b=f?0<f?e.next(!0,!1):$p.wrapped_next(e):m[a++]);)d.append(b.strip());return d}());if(null===(f="undefined"!=typeof c.__array?"undefined"!=typeof c.__array.display_gamma?c.__array.display_gamma:
c.__getitem__("display_gamma"):c.__getitem__("display_gamma"))||!1===f||0===f||""===f?0:"object"==typeof f?"function"==typeof f.__nonzero__?f.__nonzero__():"function"==typeof f.__len__?0<f.__len__():1:1)try{c.__setitem__("display_gamma",$p["float"]("undefined"!=typeof c.__array?"undefined"!=typeof c.__array.display_gamma?c.__array.display_gamma:c.__getitem__("display_gamma"):c.__getitem__("display_gamma")))}catch(L){if(d="undefined"==typeof L.__name__?L.name:L.__name__,$pyjs.__last_exception__={error:L,
module:a},d==$p.ValueError.__name__||$p._isinstance(L,$p.ValueError))c.__setitem__("display_gamma",null);else throw $pyjs.__active_exception_stack__=$pyjs.__last_exception_stack__,$pyjs.__last_exception_stack__=null,L;}return c};a.program_options.__name__="program_options";a.program_options.__bind_type__=0;a.program_options.__args__=[null,null];a.setup=function(){var f,b,g;g=$p.dict([["algae",!1],["bacterium",!0],["paramecium",!1],["amoeba",!1],["ciliate",!1]]);$p.dict([["bacterium",a.Bacterium]]);
f=$p.dict([]);f.__setitem__("species",g);f.__setitem__("matrix_size",$p.tuple([400,300]));f.__setitem__("display_size",$p.tuple([400,300]));f.__setitem__("gamma",0);b=a.Matrix(f);f=a.Control(b);return $p.tuple([b,f,g])};a.setup.__name__="setup";a.setup.__bind_type__=0;a.setup.__args__=[null,null];a.run=function(){a.pygame.display.update(a.matrix.update_list);a.matrix.update();a.control.update();return null};a.run.__name__="run";a.run.__bind_type__=0;a.run.__args__=[null,null];a.matrix=null;a.control=
null;a.species=null;a.prerun=function(){var f,b,g,h,k;$pyjs_kwargs_call(a.matrix,"setup",null,null,[{algae:"undefined"!=typeof(h=a.species).__array?"undefined"!=typeof h.__array.algae?h.__array.algae:h.__getitem__("algae"):h.__getitem__("algae"),bacterium:"undefined"!=typeof(f=a.species).__array?"undefined"!=typeof f.__array.bacterium?f.__array.bacterium:f.__getitem__("bacterium"):f.__getitem__("bacterium"),paramecium:"undefined"!=typeof(b=a.species).__array?"undefined"!=typeof b.__array.paramecium?
b.__array.paramecium:b.__getitem__("paramecium"):b.__getitem__("paramecium"),amoeba:"undefined"!=typeof(g=a.species).__array?"undefined"!=typeof g.__array.amoeba?g.__array.amoeba:g.__getitem__("amoeba"):g.__getitem__("amoeba"),ciliate:"undefined"!=typeof(k=a.species).__array?"undefined"!=typeof k.__array.ciliate?k.__array.ciliate:k.__getitem__("ciliate"):k.__getitem__("ciliate")}]);f=a.util.load_image("bg-400x300.png");a.matrix.matrix_surface.blit(f,$p.tuple([0,0]));a.pygame.display.setup(a.run);
return null};a.prerun.__name__="prerun";a.prerun.__bind_type__=0;a.prerun.__args__=[null,null];a.main=function(){var b;b=$p.__ass_unpack(a.setup(),3,null);a.matrix=b[0];a.control=b[1];a.species=b[2];b=$p.list(["./data/bacterium.png","./data/bg-400x300.png","./data/icon.png"]);a.pygame.display.setup(a.prerun,b);return null};a.main.__name__="main";a.main.__bind_type__=0;a.main.__args__=[null,null];a.program_setup=function(){var b,g;b=$p.__ass_unpack(a.setup(),2,null)[0];g=a.pygame.time.Clock();return $p.tuple([b,
g])};a.program_setup.__name__="program_setup";a.program_setup.__bind_type__=0;a.program_setup.__args__=[null,null];a.program_exec=function(b,g){a.pygame.display.update(b.update_list);b.update();g.tick(30);return null};a.program_exec.__name__="program_exec";a.program_exec.__bind_type__=0;a.program_exec.__args__=[null,null,["matrix"],["clock"]];if(null===(g="__main__"===(s="undefined"==typeof __name__?a.__name__:__name__)&&null===s?!0:null===s?!1:"object"!=typeof s&&"function"!=typeof s||"function"!=
typeof s.__cmp__?"__main__"==s:0===s.__cmp__("__main__"))||!1===g||0===g||""===g?0:"object"==typeof g?"function"==typeof g.__nonzero__?g.__nonzero__():"function"==typeof g.__len__?0<g.__len__():1:1)if(null===(r=(null===(n=M=!(null===(p=a.monitoring)||!1===p||0===p||""===p?0:"object"==typeof p?"function"==typeof p.__nonzero__?p.__nonzero__():"function"==typeof p.__len__?0<p.__len__():1:1))||!1===n||0===n||""===n?0:"object"==typeof n?"function"==typeof n.__nonzero__?n.__nonzero__():"function"==typeof n.__len__?
0<n.__len__():1:1)?!(null===(t=a.profiling)||!1===t||0===t||""===t?0:"object"==typeof t?"function"==typeof t.__nonzero__?t.__nonzero__():"function"==typeof t.__len__?0<t.__len__():1:1):M)||!1===r||0===r||""===r?0:"object"==typeof r?"function"==typeof r.__nonzero__?r.__nonzero__():"function"==typeof r.__len__?0<r.__len__():1:1)a.main();else if(null===(k=a.monitoring)||!1===k||0===k||""===k?0:"object"==typeof k?"function"==typeof k.__nonzero__?k.__nonzero__():"function"==typeof k.__len__?0<k.__len__():
1:1)a.monitor=$p.___import___("util_dev.monitor","microbe_bacterium_app",null,!1),b=$p.__ass_unpack(a.setup(),2,null),a.matrix=b[0],a.control=b[1],a.print_message=a.interphase.Text(a.matrix.screen),a.monitor(a.matrix,a.control,a.print_message);else if(null===(h=a.profiling)||!1===h||0===h||""===h?0:"object"==typeof h?"function"==typeof h.__nonzero__?h.__nonzero__():"function"==typeof h.__len__?0<h.__len__():1:1)a.profile=$p.___import___("util_dev.profile","microbe_bacterium_app",null,!1),a.profile();
return this};
