$pyjs.loaded_modules["microbe_bacterium_app.control"]=function(H){if($pyjs.loaded_modules["microbe_bacterium_app.control"].__was_initialized__)return $pyjs.loaded_modules["microbe_bacterium_app.control"];"undefined"!=typeof $pyjs.loaded_modules.microbe_bacterium_app&&$pyjs.loaded_modules.microbe_bacterium_app.__was_initialized__||$p.___import___("microbe_bacterium_app",null);var f=$pyjs.loaded_modules["microbe_bacterium_app.control"];f.__repr__=function(){return"<module: microbe_bacterium_app.control>"};
f.__was_initialized__=!0;if(null===H||"undefined"==typeof H)H="microbe_bacterium_app.control";f.__name__=H;$pyjs.loaded_modules.microbe_bacterium_app.control=$pyjs.loaded_modules["microbe_bacterium_app.control"];f.pygame=$p.___import___("pyjsdl","microbe_bacterium_app",null,!1);f.Control=function(){var D={},e;D.__module__="microbe_bacterium_app.control";e=$pyjs__bind_method2("__init__",function(a,c){if(!0===this.__is_instance__)var b=this;else b=a,a=c;b.matrix=a;b.matrix.control=b;b.tool=null;b.direction=
$p.dict([[f.pygame.K_UP,"north"],[f.pygame.K_DOWN,"south"],[f.pygame.K_LEFT,"west"],[f.pygame.K_RIGHT,"east"]]);b.mouse_x=0;b.mouse_y=0;b.quit=!1;b.scroll=!1;b.scroll_x=!1;b.scroll_y=!1;b.scroll_timer=0;b.scroll_edge=!1;b.compass_display=!1;b.compass_use=!0;b.clock=f.pygame.time.Clock();b.panel_displayed=!1;b.newspecies=null;b.tool_activated=!1;b.tool_timer=0;b.tool_timer_i=0;f.pygame.font.init();b.font=f.pygame.font.Font("Arial",24);b.font2=f.pygame.font.Font("Arial",14);b.quit_request=!1;b.pause=
!0;b.pause_program("Microbe","Click to run/pause","[r]estart [p]ause [q]uit");return null},1,[null,null,["self"],["matrix"]]);D.__init__=e;e=$pyjs__bind_method2("use_tool",function(a){a=!0===this.__is_instance__?this:a;var c,b,d,m,h,g,k,r,l,n,s,p,q,G,t,u,e,v,w,x,y,z,B,C,A,E,F;a.tool_timer+=f.pygame.time.get_ticks()-a.tool_timer_i;if(null===(l=-1==(250===(F=a.tool_timer)?0:"number"!=typeof F||"number"!=typeof F&&"string"!=typeof F&&"boolean"!=typeof F?$p.cmp(F,250):250==F?0:250>F?-1:1))||!1===l||0===
l||""===l?0:"object"==typeof l?"function"==typeof l.__nonzero__?l.__nonzero__():"function"==typeof l.__len__?0<l.__len__():1:1)return null;a.tool_timer=0;a.tool_timer_i=f.pygame.time.get_ticks();l=$p.__ass_unpack(f.pygame.mouse.get_pos(),2,null);a.mouse_x=l[0];a.mouse_y=l[1];(null===(g="Add_Gradient"===(B=a.tool)&&null===B?!0:null===B?!1:"object"!=typeof B&&"function"!=typeof B||"function"!=typeof B.__cmp__?"Add_Gradient"==B:0===B.__cmp__("Add_Gradient"))||!1===g||0===g||""===g?0:"object"==typeof g?
"function"==typeof g.__nonzero__?g.__nonzero__():"function"==typeof g.__len__?0<g.__len__():1:1)?$pyjs_kwargs_call(a.matrix,"set_gradient",null,null,[{gradient_type:"Nutrient"},a.mouse_x,a.mouse_y]):(null===(k="Add_Toxin"===(z=a.tool)&&null===z?!0:null===z?!1:"object"!=typeof z&&"function"!=typeof z||"function"!=typeof z.__cmp__?"Add_Toxin"==z:0===z.__cmp__("Add_Toxin"))||!1===k||0===k||""===k?0:"object"==typeof k?"function"==typeof k.__nonzero__?k.__nonzero__():"function"==typeof k.__len__?0<k.__len__():
1:1)?$pyjs_kwargs_call(a.matrix,"set_gradient",null,null,[{gradient_type:"Toxin"},a.mouse_x,a.mouse_y]):(null===(p="Add_Algae"===(A=a.tool)&&null===A?!0:null===A?!1:"object"!=typeof A&&"function"!=typeof A||"function"!=typeof A.__cmp__?"Add_Algae"==A:0===A.__cmp__("Add_Algae"))||!1===p||0===p||""===p?0:"object"==typeof p?"function"==typeof p.__nonzero__?p.__nonzero__():"function"==typeof p.__len__?0<p.__len__():1:1)?a.matrix.add_creature("Algae",a.mouse_x,a.mouse_y):(null===(q="Add_Bacterium"===(C=
a.tool)&&null===C?!0:null===C?!1:"object"!=typeof C&&"function"!=typeof C||"function"!=typeof C.__cmp__?"Add_Bacterium"==C:0===C.__cmp__("Add_Bacterium"))||!1===q||0===q||""===q?0:"object"==typeof q?"function"==typeof q.__nonzero__?q.__nonzero__():"function"==typeof q.__len__?0<q.__len__():1:1)?a.matrix.add_creature("Bacterium",a.mouse_x,a.mouse_y):(null===(n="Add_Paramecium"===(y=a.tool)&&null===y?!0:null===y?!1:"object"!=typeof y&&"function"!=typeof y||"function"!=typeof y.__cmp__?"Add_Paramecium"==
y:0===y.__cmp__("Add_Paramecium"))||!1===n||0===n||""===n?0:"object"==typeof n?"function"==typeof n.__nonzero__?n.__nonzero__():"function"==typeof n.__len__?0<n.__len__():1:1)?a.matrix.add_creature("Paramecium",a.mouse_x,a.mouse_y):(null===(s="Add_Amoeba"===(v=a.tool)&&null===v?!0:null===v?!1:"object"!=typeof v&&"function"!=typeof v||"function"!=typeof v.__cmp__?"Add_Amoeba"==v:0===v.__cmp__("Add_Amoeba"))||!1===s||0===s||""===s?0:"object"==typeof s?"function"==typeof s.__nonzero__?s.__nonzero__():
"function"==typeof s.__len__?0<s.__len__():1:1)?a.matrix.add_creature("Amoeba",a.mouse_x,a.mouse_y):(null===(G="Add_Ciliate"===(w=a.tool)&&null===w?!0:null===w?!1:"object"!=typeof w&&"function"!=typeof w||"function"!=typeof w.__cmp__?"Add_Ciliate"==w:0===w.__cmp__("Add_Ciliate"))||!1===G||0===G||""===G?0:"object"==typeof G?"function"==typeof G.__nonzero__?G.__nonzero__():"function"==typeof G.__len__?0<G.__len__():1:1)?a.matrix.add_creature("Ciliate",a.mouse_x,a.mouse_y):(null===(t="Track"===(x=a.tool)&&
null===x?!0:null===x?!1:"object"!=typeof x&&"function"!=typeof x||"function"!=typeof x.__cmp__?"Track"==x:0===x.__cmp__("Track"))||!1===t||0===t||""===t?0:"object"==typeof t?"function"==typeof t.__nonzero__?t.__nonzero__():"function"==typeof t.__len__?0<t.__len__():1:1)?($pyjs_kwargs_call(a.matrix,"bug_track_set",null,null,[{follow:!0},a.mouse_x,a.mouse_y]),a.panel.info_active(!0),a.panel.initialize=!1,a.tool_activated=!1):(null===(c="Tag"===(e=a.tool)&&null===e?!0:null===e?!1:"object"!=typeof e&&
"function"!=typeof e||"function"!=typeof e.__cmp__?"Tag"==e:0===e.__cmp__("Tag"))||!1===c||0===c||""===c?0:"object"==typeof c?"function"==typeof c.__nonzero__?c.__nonzero__():"function"==typeof c.__len__?0<c.__len__():1:1)?($pyjs_kwargs_call(a.matrix,"bug_track_set",null,null,[{follow:!1},a.mouse_x,a.mouse_y]),a.panel.info_active(!0),a.panel.initialize=!1,a.tool_activated=!1):(null===(b="Evolve"===(u=a.tool)&&null===u?!0:null===u?!1:"object"!=typeof u&&"function"!=typeof u||"function"!=typeof u.__cmp__?
"Evolve"==u:0===u.__cmp__("Evolve"))||!1===b||0===b||""===b?0:"object"==typeof b?"function"==typeof b.__nonzero__?b.__nonzero__():"function"==typeof b.__len__?0<b.__len__():1:1)?(a.matrix.species_evolve_set(a.mouse_x,a.mouse_y),a.tool_activated=!1):(null===(d="Magnify"===(E=a.tool)&&null===E?!0:null===E?!1:"object"!=typeof E&&"function"!=typeof E||"function"!=typeof E.__cmp__?"Magnify"==E:0===E.__cmp__("Magnify"))||!1===d||0===d||""===d?0:"object"==typeof d?"function"==typeof d.__nonzero__?d.__nonzero__():
"function"==typeof d.__len__?0<d.__len__():1:1)?(a.matrix.zoom_activate(!0),a.tool_activated=!1):(null===(m="Load"===(r=a.tool)&&null===r?!0:null===r?!1:"object"!=typeof r&&"function"!=typeof r||"function"!=typeof r.__cmp__?"Load"==r:0===r.__cmp__("Load"))||!1===m||0===m||""===m?0:"object"==typeof m?"function"==typeof m.__nonzero__?m.__nonzero__():"function"==typeof m.__len__?0<m.__len__():1:1)&&(null===(h=a.newspecies)||!1===h||0===h||""===h?0:"object"==typeof h?"function"==typeof h.__nonzero__?
h.__nonzero__():"function"==typeof h.__len__?0<h.__len__():1:1)&&a.matrix.bug_load(a.newspecies);return null},1,[null,null,["self"]]);D.use_tool=e;e=$pyjs__bind_method2("pause_program",function(a,c,b){if(!0===this.__is_instance__)var d=this;else d=arguments[0],a=arguments[1],c=arguments[2],b=arguments[3];"undefined"==typeof c&&(c=arguments.callee.__args__[4][1]);"undefined"==typeof b&&(b=arguments.callee.__args__[5][1]);var m,h,g,k,r,l,n,s,p,q;d.matrix.screen.fill($p.tuple([0,0,0]));m=d.font.render(a,
!0,$p.tuple([100,100,100]));k=d.font.size(a);d.matrix.screen.blit(m,$p.tuple([Math.floor(d.matrix.x/2)-Math.floor(("undefined"!=typeof(q=k).__array?"undefined"!=typeof q.__array[0]?q.__array[0]:q.__getitem__(0):q.__getitem__(0))/2),Math.floor(d.matrix.y/2)-Math.floor(("undefined"!=typeof(p=k).__array?"undefined"!=typeof p.__array[1]?p.__array[1]:p.__getitem__(1):p.__getitem__(1))/2)-12]));if(null===(h=c)||!1===h||0===h||""===h?0:"object"==typeof h?"function"==typeof h.__nonzero__?h.__nonzero__():
"function"==typeof h.__len__?0<h.__len__():1:1)m=d.font2.render(c,!0,$p.tuple([100,100,100])),k=d.font2.size(c),d.matrix.screen.blit(m,$p.tuple([Math.floor(d.matrix.x/2)-Math.floor(("undefined"!=typeof(s=k).__array?"undefined"!=typeof s.__array[0]?s.__array[0]:s.__getitem__(0):s.__getitem__(0))/2),Math.floor(d.matrix.y/2)-Math.floor(("undefined"!=typeof(n=k).__array?"undefined"!=typeof n.__array[1]?n.__array[1]:n.__getitem__(1):n.__getitem__(1))/2)+25]));if(null===(g=b)||!1===g||0===g||""===g?0:"object"==
typeof g?"function"==typeof g.__nonzero__?g.__nonzero__():"function"==typeof g.__len__?0<g.__len__():1:1)m=d.font2.render(b,!0,$p.tuple([100,100,100])),k=d.font2.size(b),d.matrix.screen.blit(m,$p.tuple([Math.floor(d.matrix.x/2)-Math.floor(("undefined"!=typeof(l=k).__array?"undefined"!=typeof l.__array[0]?l.__array[0]:l.__getitem__(0):l.__getitem__(0))/2),Math.floor(d.matrix.y/2)-Math.floor(("undefined"!=typeof(r=k).__array?"undefined"!=typeof r.__array[1]?r.__array[1]:r.__getitem__(1):r.__getitem__(1))/
2)+40]));f.pygame.display.flip();return null},1,[null,null,["self"],["text1"],["text2",null],["text3",null]]);D.pause_program=e;e=$pyjs__bind_method2("matrix_control",function(a){a=!0===this.__is_instance__?this:a;var c,b;(null===(c=!(null===(b=a.pause)||!1===b||0===b||""===b?0:"object"==typeof b?"function"==typeof b.__nonzero__?b.__nonzero__():"function"==typeof b.__len__?0<b.__len__():1:1))||!1===c||0===c||""===c?0:"object"==typeof c?"function"==typeof c.__nonzero__?c.__nonzero__():"function"==
typeof c.__len__?0<c.__len__():1:1)?(a.pause_program("Microbe","Click to run/pause","[r]estart [p]ause [q]uit"),a.pause=!0):(a.matrix.refresh_screen(),a.matrix.update(),a.quit_request=!1,a.pause=!1);return null},1,[null,null,["self"]]);D.matrix_control=e;e=$pyjs__bind_method2("check_events",function(a){a=!0===this.__is_instance__?this:a;var c,b,d,m,h,g,k,r,l,n,s,p,q,e,t,u,D,v,w,x,y,z,B,C,A,E,F;b=f.pygame.event.get();"undefined"!=typeof(D=b.__array)?E=0:(b=b.__iter__(),E="undefined"!=typeof(D=b.__array)?
0:"function"==typeof b.$genfunc?1:-1);for(F=0;"undefined"!=typeof(p=E?0<E?b.next(!0,!1):$p.wrapped_next(b):D[F++]);)if(null===(c=(y=p.type)===(C=f.pygame.MOUSEBUTTONDOWN)&&null===y?!0:null===y?!1:null===C?!1:"object"!=typeof y&&"function"!=typeof y||"function"!=typeof y.__cmp__?"object"!=typeof C&&"function"!=typeof C||"function"!=typeof C.__cmp__?y==C:0===C.__cmp__(y):0===y.__cmp__(C))||!1===c||0===c||""===c?0:"object"==typeof c?"function"==typeof c.__nonzero__?c.__nonzero__():"function"==typeof c.__len__?
0<c.__len__():1:1)(null===(t=1===(B=p.button)&&null===B?!0:null===B?!1:"object"!=typeof B&&"function"!=typeof B||"function"!=typeof B.__cmp__?1==B:0===B.__cmp__(1))||!1===t||0===t||""===t?0:"object"==typeof t?"function"==typeof t.__nonzero__?t.__nonzero__():"function"==typeof t.__len__?0<t.__len__():1:1)&&a.matrix_control();else if(null===(u=(A=p.type)===(h=f.pygame.KEYDOWN)&&null===A?!0:null===A?!1:null===h?!1:"object"!=typeof A&&"function"!=typeof A||"function"!=typeof A.__cmp__?"object"!=typeof h&&
"function"!=typeof h||"function"!=typeof h.__cmp__?A==h:0===h.__cmp__(A):0===A.__cmp__(h))||!1===u||0===u||""===u?0:"object"==typeof u?"function"==typeof u.__nonzero__?u.__nonzero__():"function"==typeof u.__len__?0<u.__len__():1:1)if(null===(x=(g=p.key)===(d=f.pygame.K_p)&&null===g?!0:null===g?!1:null===d?!1:"object"!=typeof g&&"function"!=typeof g||"function"!=typeof g.__cmp__?"object"!=typeof d&&"function"!=typeof d||"function"!=typeof d.__cmp__?g==d:0===d.__cmp__(g):0===g.__cmp__(d))||!1===x||
0===x||""===x?0:"object"==typeof x?"function"==typeof x.__nonzero__?x.__nonzero__():"function"==typeof x.__len__?0<x.__len__():1:1)a.matrix_control();else if(null===(v=(m=p.key)===(l=f.pygame.K_r)&&null===m?!0:null===m?!1:null===l?!1:"object"!=typeof m&&"function"!=typeof m||"function"!=typeof m.__cmp__?"object"!=typeof l&&"function"!=typeof l||"function"!=typeof l.__cmp__?m==l:0===l.__cmp__(m):0===m.__cmp__(l))||!1===v||0===v||""===v?0:"object"==typeof v?"function"==typeof v.__nonzero__?v.__nonzero__():
"function"==typeof v.__len__?0<v.__len__():1:1)a.pause=!1,a.quit_request=!1,a.matrix.restart();else if(null===(e=(n=p.key)===(k=f.pygame.K_q)&&null===n?!0:null===n?!1:null===k?!1:"object"!=typeof n&&"function"!=typeof n||"function"!=typeof n.__cmp__?"object"!=typeof k&&"function"!=typeof k||"function"!=typeof k.__cmp__?n==k:0===k.__cmp__(n):0===n.__cmp__(k))||!1===e||0===e||""===e?0:"object"==typeof e?"function"==typeof e.__nonzero__?e.__nonzero__():"function"==typeof e.__len__?0<e.__len__():1:1)a.pause_program("Microbe",
"Quit (y/n)?"),a.pause=!0,a.quit_request=!0;else if(null===(q=$p.tuple([f.pygame.K_y,f.pygame.K_n]).__contains__(p.key))||!1===q||0===q||""===q?0:"object"==typeof q?"function"==typeof q.__nonzero__?q.__nonzero__():"function"==typeof q.__len__?0<q.__len__():1:1)if(null===(z=a.quit_request)||!1===z||0===z||""===z?0:"object"==typeof z?"function"==typeof z.__nonzero__?z.__nonzero__():"function"==typeof z.__len__?0<z.__len__():1:1)(null===(w=(r=p.key)===(s=f.pygame.K_n)&&null===r?!0:null===r?!1:null===
s?!1:"object"!=typeof r&&"function"!=typeof r||"function"!=typeof r.__cmp__?"object"!=typeof s&&"function"!=typeof s||"function"!=typeof s.__cmp__?r==s:0===s.__cmp__(r):0===r.__cmp__(s))||!1===w||0===w||""===w?0:"object"==typeof w?"function"==typeof w.__nonzero__?w.__nonzero__():"function"==typeof w.__len__?0<w.__len__():1:1)?a.matrix_control():(a.matrix.screen.fill($p.tuple([0,0,0])),f.pygame.display.flip(),f.pygame.time.delay(10),f.pygame.quit(),a.quit=!0);return null},1,[null,null,["self"]]);D.check_events=
e;e=$pyjs__bind_method2("update",function(a){a=!0===this.__is_instance__?this:a;a.check_events();a.clock.tick(30);return a.quit},1,[null,null,["self"]]);D.update=e;e=Array($p.object);var H=$p.dict(),I;for(I in D)H.__setitem__(I,D[I]);return $p._create_class("Control",$p.tuple(e),H)}();return this};
