$pyjs.loaded_modules["pyjsdl.event"]=function(I){if($pyjs.loaded_modules["pyjsdl.event"].__was_initialized__)return $pyjs.loaded_modules["pyjsdl.event"];"undefined"!=typeof $pyjs.loaded_modules.pyjsdl&&$pyjs.loaded_modules.pyjsdl.__was_initialized__||$p.___import___("pyjsdl",null);var b=$pyjs.loaded_modules["pyjsdl.event"];b.__repr__=function(){return"<module: pyjsdl.event>"};b.__was_initialized__=!0;if(null===I||"undefined"==typeof I)I="pyjsdl.event";b.__name__=I;$pyjs.loaded_modules.pyjsdl.event=
$pyjs.loaded_modules["pyjsdl.event"];b.env=$p.___import___("env","pyjsdl");b.time=$p.___import___("time","pyjsdl");b.Const=$p.___import___("locals","pyjsdl",null,!1);b.__docformat__="restructuredtext";b.Event=function(){var m={},f;m.__module__="pyjsdl.event";f=$pyjs__bind_method2("__init__",function(d){d=!0===this.__is_instance__?this:d;var h;d.eventQueue=function(){var d,a,c,h,b;a=$p.list();c=$p.range(256);"undefined"!=typeof(b=c.__array)?d=0:(c=c.__iter__(),d="undefined"!=typeof(b=c.__array)?0:
"function"==typeof c.$genfunc?1:-1);for(h=0;"undefined"!=typeof(d?0<d?c.next(!0,!1):$p.wrapped_next(c):b[h++]);)a.append(null);return a}();d.eventNum=0;d.eventQueueTmp=function(){var d,a,c,h,b;c=$p.list();a=$p.range(256);"undefined"!=typeof(b=a.__array)?d=0:(a=a.__iter__(),d="undefined"!=typeof(b=a.__array)?0:"function"==typeof a.$genfunc?1:-1);for(h=0;"undefined"!=typeof(d?0<d?a.next(!0,!1):$p.wrapped_next(a):b[h++]);)c.append(null);return c}();d.eventNumTmp=0;d.queueLock=!1;d.queueAccess=!1;d.queue=
$p.list([]);d.mousePress=$p.dict([[0,!1],[1,!1],[2,!1]]);d.mouseMove=$p.dict([["x",-1],["y",-1]]);d.mouseMoveRel=$p.dict([["x",null],["y",null]]);d.keyPress=$p.dict([[b.Const.K_ALT,!1],[b.Const.K_CTRL,!1],[b.Const.K_SHIFT,!1]]);d.keyMod=$p.dict([[b.Const.K_ALT,$p.dict([[!0,b.Const.KMOD_ALT],[!1,0]])],[b.Const.K_CTRL,$p.dict([[!0,b.Const.KMOD_CTRL],[!1,0]])],[b.Const.K_SHIFT,$p.dict([[!0,b.Const.KMOD_SHIFT],[!1,0]])]]);d.mouseCursor=!0;d.timer=b.time.Clock();d.eventName=$p.dict([["mousemove","MouseMotion"],
["mousedown","MouseButtonDown"],["mouseup","MouseButtonUp"],["keydown","KeyDown"],["keyup","KeyUp"]]);d.eventType=$p.list("mousemove mousedown mouseup wheel mousewheel DOMMouseScroll keydown keypress keyup".split(" "));d.events=$p.set(d.eventType);d.eventTypes=$p.dict([[b.Const.MOUSEMOTION,$p.list(["mousemove"])],[b.Const.MOUSEBUTTONDOWN,$p.list(["mousedown","wheel","mousewheel","DOMMouseScroll"])],[b.Const.MOUSEBUTTONUP,$p.list(["mouseup"])],[b.Const.KEYDOWN,$p.list(["keydown","keypress"])],[b.Const.KEYUP,
$p.list(["keyup"])]]);(null===(h=b.env.pyjs_mode.optimized)||!1===h||0===h||""===h?0:"object"==typeof h?"function"==typeof h.__nonzero__?h.__nonzero__():"function"==typeof h.__len__?0<h.__len__():1:1)?(d.modKey=$p.set($p.list([b.Const.K_ALT,b.Const.K_CTRL,b.Const.K_SHIFT])),d.specialKey=$p.set($p.list([b.Const.K_UP,b.Const.K_DOWN,b.Const.K_LEFT,b.Const.K_RIGHT,b.Const.K_HOME,b.Const.K_END,b.Const.K_PAGEDOWN,b.Const.K_PAGEUP,b.Const.K_BACKSPACE,b.Const.K_DELETE,b.Const.K_INSERT,b.Const.K_RETURN,b.Const.K_TAB,
b.Const.K_ESCAPE]))):(d.modKey=$p.set(function(){var d,a,c,h,g,l;h=$p.list();g=$p.tuple([b.Const.K_ALT,b.Const.K_CTRL,b.Const.K_SHIFT]);"undefined"!=typeof(l=g.__array)?c=0:(g=g.__iter__(),c="undefined"!=typeof(l=g.__array)?0:"function"==typeof g.$genfunc?1:-1);for(d=0;"undefined"!=typeof(a=c?0<c?g.next(!0,!1):$p.wrapped_next(g):l[d++]);)h.append(a.valueOf());return h}()),d.specialKey=$p.set(function(){var d,a,c,h,g,l;d=$p.list();c=$p.tuple([b.Const.K_UP,b.Const.K_DOWN,b.Const.K_LEFT,b.Const.K_RIGHT,
b.Const.K_HOME,b.Const.K_END,b.Const.K_PAGEDOWN,b.Const.K_PAGEUP,b.Const.K_BACKSPACE,b.Const.K_DELETE,b.Const.K_INSERT,b.Const.K_RETURN,b.Const.K_TAB,b.Const.K_ESCAPE]);"undefined"!=typeof(l=c.__array)?a=0:(c=c.__iter__(),a="undefined"!=typeof(l=c.__array)?0:"function"==typeof c.$genfunc?1:-1);for(g=0;"undefined"!=typeof(h=a?0<a?c.next(!0,!1):$p.wrapped_next(c):l[g++]);)d.append(h.valueOf());return d}()));d.Event="undefined"==typeof UserEvent?b.UserEvent:UserEvent;d._nonimplemented_methods();return null},
1,[null,null,["self"]]);m.__init__=f;f=$pyjs__bind_method2("_lock",function(d){(!0===this.__is_instance__?this:d).queueLock=!0;return null},1,[null,null,["self"]]);m._lock=f;f=$pyjs__bind_method2("_unlock",function(d){(!0===this.__is_instance__?this:d).queueLock=!1;return null},1,[null,null,["self"]]);m._unlock=f;f=$pyjs__bind_method2("_updateQueue",function(d,h){if(!0===this.__is_instance__)var e=this;else e=d,d=h;var a,c,b,g;if(null===(c=!e.events.__contains__(d.type))||!1===c||0===c||""===c?0:
"object"==typeof c?"function"==typeof c.__nonzero__?c.__nonzero__():"function"==typeof c.__len__?0<c.__len__():1:1)return null;e.queueAccess=!0;(null===(g=!(null===(b=e.queueLock)||!1===b||0===b||""===b?0:"object"==typeof b?"function"==typeof b.__nonzero__?b.__nonzero__():"function"==typeof b.__len__?0<b.__len__():1:1))||!1===g||0===g||""===g?0:"object"==typeof g?"function"==typeof g.__nonzero__?g.__nonzero__():"function"==typeof g.__len__?0<g.__len__():1:1)?((null===(a=e.eventNumTmp)||!1===a||0===
a||""===a?0:"object"==typeof a?"function"==typeof a.__nonzero__?a.__nonzero__():"function"==typeof a.__len__?0<a.__len__():1:1)&&e._appendMerge(),e._append(d)):e._appendTmp(d);e.queueAccess=!1;return null},1,[null,null,["self"],["event"]]);m._updateQueue=f;f=$pyjs__bind_method2("_append",function(d,h){if(!0===this.__is_instance__)var e=this;else e=d,d=h;var a,c;if(null===(c=-1==(255===(a=e.eventNum)?0:"number"!=typeof a||"number"!=typeof a&&"string"!=typeof a&&"boolean"!=typeof a?$p.cmp(a,255):255==
a?0:255>a?-1:1))||!1===c||0===c||""===c?0:"object"==typeof c?"function"==typeof c.__nonzero__?c.__nonzero__():"function"==typeof c.__len__?0<c.__len__():1:1)e.eventQueue.__setitem__(e.eventNum,d),e.eventNum+=1;return null},1,[null,null,["self"],["event"]]);m._append=f;f=$pyjs__bind_method2("_appendTmp",function(d,h){if(!0===this.__is_instance__)var e=this;else e=d,d=h;var a,c;if(null===(c=-1==(255===(a=e.eventNumTmp)?0:"number"!=typeof a||"number"!=typeof a&&"string"!=typeof a&&"boolean"!=typeof a?
$p.cmp(a,255):255==a?0:255>a?-1:1))||!1===c||0===c||""===c?0:"object"==typeof c?"function"==typeof c.__nonzero__?c.__nonzero__():"function"==typeof c.__len__?0<c.__len__():1:1)e.eventQueueTmp.__setitem__(e.eventNumTmp,d),e.eventNumTmp+=1;return null},1,[null,null,["self"],["event"]]);m._appendTmp=f;f=$pyjs__bind_method2("_appendMerge",function(d){d=!0===this.__is_instance__?this:d;var h,e,a,c,b,g,l;a=$p.range(d.eventNumTmp);"undefined"!=typeof(c=a.__array)?b=0:(a=a.__iter__(),b="undefined"!=typeof(c=
a.__array)?0:"function"==typeof a.$genfunc?1:-1);for(e=0;"undefined"!=typeof(h=b?0<b?a.next(!0,!1):$p.wrapped_next(a):c[e++]);)d._append("undefined"!=typeof(l=d.eventQueueTmp).__array?"undefined"!=typeof l.__array[g=h]?l.__array[g]:l.__getitem__(g):l.__getitem__(h)),d.eventQueueTmp.__setitem__(h,null);d.eventNumTmp=0;return null},1,[null,null,["self"]]);m._appendMerge=f;f=$pyjs__bind_method2("pump",function(d){d=!0===this.__is_instance__?this:d;var h,e;if(null===(e=1==(250===(h=d.eventNum)?0:"number"!=
typeof h||"number"!=typeof h&&"string"!=typeof h&&"boolean"!=typeof h?$p.cmp(h,250):250==h?0:250>h?-1:1))||!1===e||0===e||""===e?0:"object"==typeof e?"function"==typeof e.__nonzero__?e.__nonzero__():"function"==typeof e.__len__?0<e.__len__():1:1)d._lock(),d._pump(),d._unlock();return null},1,[null,null,["self"]]);m.pump=f;f=$pyjs__bind_method2("_pump",function(d){d=!0===this.__is_instance__?this:d;var h,e,a,c,b,g,l,k;g=$p.__getslice(d.eventQueue,50,d.eventNum);d.eventNum-=50;l=$p.range(d.eventNum);
"undefined"!=typeof(b=l.__array)?a=0:(l=l.__iter__(),a="undefined"!=typeof(b=l.__array)?0:"function"==typeof l.$genfunc?1:-1);for(e=0;"undefined"!=typeof(h=a?0<a?l.next(!0,!1):$p.wrapped_next(l):b[e++]);)d.eventQueue.__setitem__(h,"undefined"!=typeof(k=g).__array?"undefined"!=typeof k.__array[c=h]?k.__array[c]:k.__getitem__(c):k.__getitem__(h));return null},1,[null,null,["self"]]);m._pump=f;f=$pyjs__bind_method2("get",function(d){if(!0===this.__is_instance__)var h=this;else h=arguments[0],d=arguments[1];
"undefined"==typeof d&&(d=arguments.callee.__args__[3][1]);var e,a,c,n,g,l,k,s,q,u,p,f,w,m,y,x,r,t,v,D,B;h._lock();if(null===(e=!(null===(s=d)||!1===s||0===s||""===s?0:"object"==typeof s?"function"==typeof s.__nonzero__?s.__nonzero__():"function"==typeof s.__len__?0<s.__len__():1:1))||!1===e||0===e||""===e?0:"object"==typeof e?"function"==typeof e.__nonzero__?e.__nonzero__():"function"==typeof e.__len__?0<e.__len__():1:1)h.queue=function(){var d,a,e,c,g,k;e=$p.list();a=$p.__getslice(h.eventQueue,
0,h.eventNum);"undefined"!=typeof(c=a.__array)?k=0:(a=a.__iter__(),k="undefined"!=typeof(c=a.__array)?0:"function"==typeof a.$genfunc?1:-1);for(g=0;"undefined"!=typeof(d=k?0<k?a.next(!0,!1):$p.wrapped_next(a):c[g++]);)e.append(("undefined"==typeof JEvent?b.JEvent:JEvent)(d));return e}(),h.eventNum=0;else{e=(null===(a=!(null===(k=$p.isinstance(d,$p.tuple([$p.tuple,$p.list])))||!1===k||0===k||""===k?0:"object"==typeof k?"function"==typeof k.__nonzero__?k.__nonzero__():"function"==typeof k.__len__?0<
k.__len__():1:1))||!1===a||0===a||""===a?0:"object"==typeof a?"function"==typeof a.__nonzero__?a.__nonzero__():"function"==typeof a.__len__?0<a.__len__():1:1)?function(){var a,e,c,b,g,k;e=$p.list();g="undefined"!=typeof(c=h.eventTypes).__array?"undefined"!=typeof c.__array[a=d]?c.__array[a]:c.__getitem__(a):c.__getitem__(d);"undefined"!=typeof(b=g.__array)?c=0:(g=g.__iter__(),c="undefined"!=typeof(b=g.__array)?0:"function"==typeof g.$genfunc?1:-1);for(a=0;"undefined"!=typeof(k=c?0<c?g.next(!0,!1):
$p.wrapped_next(g):b[a++]);)e.append(k);return e}():function(){var a,c,e,b,g,k,n,p,l,f,q,u;e=$p.list();c=d;"undefined"!=typeof(u=c.__array)?n=0:(c=c.__iter__(),n="undefined"!=typeof(u=c.__array)?0:"function"==typeof c.$genfunc?1:-1);for(g=0;"undefined"!=typeof(b=n?0<n?c.next(!0,!1):$p.wrapped_next(c):u[g++]);)for(q="undefined"!=typeof(l=h.eventTypes).__array?"undefined"!=typeof l.__array[p=b]?l.__array[p]:l.__getitem__(p):l.__getitem__(b),"undefined"!=typeof(k=q.__array)?f=0:(q=q.__iter__(),f="undefined"!=
typeof(k=q.__array)?0:"function"==typeof q.$genfunc?1:-1),b=0;"undefined"!=typeof(a=f?0<f?q.next(!0,!1):$p.wrapped_next(q):k[b++]);)e.append(a);return e}();a=$p.list([]);h.queue=$p.list([]);f=$p.range(h.eventNum);"undefined"!=typeof(y=f.__array)?D=0:(f=f.__iter__(),D="undefined"!=typeof(y=f.__array)?0:"function"==typeof f.$genfunc?1:-1);for(s=0;"undefined"!=typeof(k=D?0<D?f.next(!0,!1):$p.wrapped_next(f):y[s++]);)(null===(q=!e.__contains__(("undefined"!=typeof(c=h.eventQueue).__array?"undefined"!=
typeof c.__array[t=k]?c.__array[t]:c.__getitem__(t):c.__getitem__(k)).type))||!1===q||0===q||""===q?0:"object"==typeof q?"function"==typeof q.__nonzero__?q.__nonzero__():"function"==typeof q.__len__?0<q.__len__():1:1)?a.append("undefined"!=typeof(x=h.eventQueue).__array?"undefined"!=typeof x.__array[v=k]?x.__array[v]:x.__getitem__(v):x.__getitem__(k)):h.queue.append(("undefined"==typeof JEvent?b.JEvent:JEvent)("undefined"!=typeof(B=h.eventQueue).__array?"undefined"!=typeof B.__array[r=k]?B.__array[r]:
B.__getitem__(r):B.__getitem__(k)));if(null===(n=!((w=null===a?0:"undefined"!=typeof a.__array?a.__array.length:"function"==typeof a.__len__?a.__len__():"undefined"!=typeof a.length?a.length:$p.len(a))===(p=h.eventNum)&&null===w||(null===w?0:null===p?0:"object"!=typeof w&&"function"!=typeof w||"function"!=typeof w.__cmp__?"object"!=typeof p&&"function"!=typeof p||"function"!=typeof p.__cmp__?w==p:0===p.__cmp__(w):0===w.__cmp__(p))))||!1===n||0===n||""===n?0:"object"==typeof n?"function"==typeof n.__nonzero__?
n.__nonzero__():"function"==typeof n.__len__?0<n.__len__():1:1)for(h.eventNum=null===a?0:"undefined"!=typeof a.__array?a.__array.length:"function"==typeof a.__len__?a.__len__():"undefined"!=typeof a.length?a.length:$p.len(a),c=$p.range(h.eventNum),"undefined"!=typeof(n=c.__array)?q=0:(c=c.__iter__(),q="undefined"!=typeof(n=c.__array)?0:"function"==typeof c.$genfunc?1:-1),p=0;"undefined"!=typeof(w=q?0<q?c.next(!0,!1):$p.wrapped_next(c):n[p++]);)k=w,h.eventQueue.__setitem__(k,"undefined"!=typeof(u=
a).__array?"undefined"!=typeof u.__array[m=k]?u.__array[m]:u.__getitem__(m):u.__getitem__(k));(null===(g=1==(250===(l=h.eventNum)?0:"number"!=typeof l||"number"!=typeof l&&"string"!=typeof l&&"boolean"!=typeof l?$p.cmp(l,250):250==l?0:250>l?-1:1))||!1===g||0===g||""===g?0:"object"==typeof g?"function"==typeof g.__nonzero__?g.__nonzero__():"function"==typeof g.__len__?0<g.__len__():1:1)&&h._pump()}h._unlock();return h.queue},1,[null,null,["self"],["eventType",null]]);m.get=f;f=$pyjs__bind_method2("poll",
function(d){d=!0===this.__is_instance__?this:d;var h,e,a;d._lock();(null===(e=d.eventNum)||!1===e||0===e||""===e?0:"object"==typeof e?"function"==typeof e.__nonzero__?e.__nonzero__():"function"==typeof e.__len__?0<e.__len__():1:1)?(e=("undefined"==typeof JEvent?b.JEvent:JEvent)(d.eventQueue.pop(0)),d.eventNum-=1,d.eventQueue.append(null),(null===(a=1==(250===(h=d.eventNum)?0:"number"!=typeof h||"number"!=typeof h&&"string"!=typeof h&&"boolean"!=typeof h?$p.cmp(h,250):250==h?0:250>h?-1:1))||!1===a||
0===a||""===a?0:"object"==typeof a?"function"==typeof a.__nonzero__?a.__nonzero__():"function"==typeof a.__len__?0<a.__len__():1:1)&&d._pump()):e=d.Event(b.Const.NOEVENT);d._unlock();return e},1,[null,null,["self"]]);m.poll=f;f=$pyjs__bind_method2("wait",function(d){d=!0===this.__is_instance__?this:d;for(var h,e,a;!0!==0&&!0!=="";){if(null===(h=d.eventNum)||!1===h||0===h||""===h?0:"object"==typeof h?"function"==typeof h.__nonzero__?h.__nonzero__():"function"==typeof h.__len__?0<h.__len__():1:1)return d._lock(),
h=("undefined"==typeof JEvent?b.JEvent:JEvent)(d.eventQueue.pop(0)),d.eventNum-=1,d.eventQueue.append(null),(null===(a=1==(250===(e=d.eventNum)?0:"number"!=typeof e||"number"!=typeof e&&"string"!=typeof e&&"boolean"!=typeof e?$p.cmp(e,250):250==e?0:250>e?-1:1))||!1===a||0===a||""===a?0:"object"==typeof a?"function"==typeof a.__nonzero__?a.__nonzero__():"function"==typeof a.__len__?0<a.__len__():1:1)&&d._pump(),d._unlock(),h;d._unlock();break}return null},1,[null,null,["self"]]);m.wait=f;f=$pyjs__bind_method2("peek",
function(d,b){if(!0===this.__is_instance__)var e=this;else e=d,d=b;var a,c,n,g,l,k,f;if(null===(n=!(null===(a=e.eventNum)||!1===a||0===a||""===a?0:"object"==typeof a?"function"==typeof a.__nonzero__?a.__nonzero__():"function"==typeof a.__len__?0<a.__len__():1:1))||!1===n||0===n||""===n?0:"object"==typeof n?"function"==typeof n.__nonzero__?n.__nonzero__():"function"==typeof n.__len__?0<n.__len__():1:1)return!1;a=(null===(l=!(null===(f=$p.isinstance(d,$p.tuple([$p.tuple,$p.list])))||!1===f||0===f||
""===f?0:"object"==typeof f?"function"==typeof f.__nonzero__?f.__nonzero__():"function"==typeof f.__len__?0<f.__len__():1:1))||!1===l||0===l||""===l?0:"object"==typeof l?"function"==typeof l.__nonzero__?l.__nonzero__():"function"==typeof l.__len__?0<l.__len__():1:1)?function(){var a,c,b,h,g,k;h=$p.list();b="undefined"!=typeof(a=e.eventTypes).__array?"undefined"!=typeof a.__array[g=d]?a.__array[g]:a.__getitem__(g):a.__getitem__(d);"undefined"!=typeof(k=b.__array)?a=0:(b=b.__iter__(),a="undefined"!=
typeof(k=b.__array)?0:"function"==typeof b.$genfunc?1:-1);for(g=0;"undefined"!=typeof(c=a?0<a?b.next(!0,!1):$p.wrapped_next(b):k[g++]);)h.append(c);return h}():function(){var a,c,b,h,g,k,n,f,l,s,m,D;h=$p.list();s=d;"undefined"!=typeof(a=s.__array)?c=0:(s=s.__iter__(),c="undefined"!=typeof(a=s.__array)?0:"function"==typeof s.$genfunc?1:-1);for(D=0;"undefined"!=typeof(b=c?0<c?s.next(!0,!1):$p.wrapped_next(s):a[D++]);)for(b="undefined"!=typeof(f=e.eventTypes).__array?"undefined"!=typeof f.__array[k=
b]?f.__array[k]:f.__getitem__(k):f.__getitem__(b),"undefined"!=typeof(n=b.__array)?m=0:(b=b.__iter__(),m="undefined"!=typeof(n=b.__array)?0:"function"==typeof b.$genfunc?1:-1),l=0;"undefined"!=typeof(g=m?0<m?b.next(!0,!1):$p.wrapped_next(b):n[l++]);)h.append(g);return h}();e._lock();l=function(){var a,d,c,b,h,g;b=$p.list();g=$p.__getslice(e.eventQueue,0,e.eventNum);"undefined"!=typeof(a=g.__array)?d=0:(g=g.__iter__(),d="undefined"!=typeof(a=g.__array)?0:"function"==typeof g.$genfunc?1:-1);for(c=0;"undefined"!=
typeof(h=d?0<d?g.next(!0,!1):$p.wrapped_next(g):a[c++]);)b.append(h.type);return b}();(null===(c=1==(250===(g=e.eventNum)?0:"number"!=typeof g||"number"!=typeof g&&"string"!=typeof g&&"boolean"!=typeof g?$p.cmp(g,250):250==g?0:250>g?-1:1))||!1===c||0===c||""===c?0:"object"==typeof c?"function"==typeof c.__nonzero__?c.__nonzero__():"function"==typeof c.__len__?0<c.__len__():1:1)&&e._pump();e._unlock();g=a;"undefined"!=typeof(f=g.__array)?c=0:(g=g.__iter__(),c="undefined"!=typeof(f=g.__array)?0:"function"==
typeof g.$genfunc?1:-1);for(a=0;"undefined"!=typeof(n=c?0<c?g.next(!0,!1):$p.wrapped_next(g):f[a++]);)if(null===(k=l.__contains__(n))||!1===k||0===k||""===k?0:"object"==typeof k?"function"==typeof k.__nonzero__?k.__nonzero__():"function"==typeof k.__len__?0<k.__len__():1:1)return!0;return!1},1,[null,null,["self"],["eventType"]]);m.peek=f;f=$pyjs__bind_method2("clear",function(d){if(!0===this.__is_instance__)var b=this;else b=arguments[0],d=arguments[1];"undefined"==typeof d&&(d=arguments.callee.__args__[3][1]);
var e,a,c,f,g,l,k,s,q,u,p,m,w,F,y,x,r,t,v;if(null===(s=!(null===(e=b.eventNum)||!1===e||0===e||""===e?0:"object"==typeof e?"function"==typeof e.__nonzero__?e.__nonzero__():"function"==typeof e.__len__?0<e.__len__():1:1))||!1===s||0===s||""===s?0:"object"==typeof s?"function"==typeof s.__nonzero__?s.__nonzero__():"function"==typeof s.__len__?0<s.__len__():1:1)return null;b._lock();if(null===(g=null===d)||!1===g||0===g||""===g?0:"object"==typeof g?"function"==typeof g.__nonzero__?g.__nonzero__():"function"==
typeof g.__len__?0<g.__len__():1:1)b.eventNum=0;else{e=(null===(p=!(null===(r=$p.isinstance(d,$p.tuple([$p.tuple,$p.list])))||!1===r||0===r||""===r?0:"object"==typeof r?"function"==typeof r.__nonzero__?r.__nonzero__():"function"==typeof r.__len__?0<r.__len__():1:1))||!1===p||0===p||""===p?0:"object"==typeof p?"function"==typeof p.__nonzero__?p.__nonzero__():"function"==typeof p.__len__?0<p.__len__():1:1)?function(){var a,c,e,g,k,f;k=$p.list();c="undefined"!=typeof(a=b.eventTypes).__array?"undefined"!=
typeof a.__array[e=d]?a.__array[e]:a.__getitem__(e):a.__getitem__(d);"undefined"!=typeof(e=c.__array)?a=0:(c=c.__iter__(),a="undefined"!=typeof(e=c.__array)?0:"function"==typeof c.$genfunc?1:-1);for(g=0;"undefined"!=typeof(f=a?0<a?c.next(!0,!1):$p.wrapped_next(c):e[g++]);)k.append(f);return k}():function(){var a,c,e,g,k,f,n,l,p,m,s,q;m=$p.list();n=d;"undefined"!=typeof(f=n.__array)?l=0:(n=n.__iter__(),l="undefined"!=typeof(f=n.__array)?0:"function"==typeof n.$genfunc?1:-1);for(e=0;"undefined"!=typeof(a=
l?0<l?n.next(!0,!1):$p.wrapped_next(n):f[e++]);)for(a="undefined"!=typeof(k=b.eventTypes).__array?"undefined"!=typeof k.__array[p=a]?k.__array[p]:k.__getitem__(p):k.__getitem__(a),"undefined"!=typeof(q=a.__array)?s=0:(a=a.__iter__(),s="undefined"!=typeof(q=a.__array)?0:"function"==typeof a.$genfunc?1:-1),g=0;"undefined"!=typeof(c=s?0<s?a.next(!0,!1):$p.wrapped_next(a):q[g++]);)m.append(c);return m}();r=$p.list([]);y=$p.range(b.eventNum);"undefined"!=typeof(v=y.__array)?g=0:(y=y.__iter__(),g="undefined"!=
typeof(v=y.__array)?0:"function"==typeof y.$genfunc?1:-1);for(s=0;"undefined"!=typeof(p=g?0<g?y.next(!0,!1):$p.wrapped_next(y):v[s++]);)(null===(a=!e.__contains__(("undefined"!=typeof(c=b.eventQueue).__array?"undefined"!=typeof c.__array[k=p]?c.__array[k]:c.__getitem__(k):c.__getitem__(p)).type))||!1===a||0===a||""===a?0:"object"==typeof a?"function"==typeof a.__nonzero__?a.__nonzero__():"function"==typeof a.__len__?0<a.__len__():1:1)&&r.append("undefined"!=typeof(l=b.eventQueue).__array?"undefined"!=
typeof l.__array[F=p]?l.__array[F]:l.__getitem__(F):l.__getitem__(p));if(null===(t=!((u=null===r?0:"undefined"!=typeof r.__array?r.__array.length:"function"==typeof r.__len__?r.__len__():"undefined"!=typeof r.length?r.length:$p.len(r))===(m=b.eventNum)&&null===u||(null===u?0:null===m?0:"object"!=typeof u&&"function"!=typeof u||"function"!=typeof u.__cmp__?"object"!=typeof m&&"function"!=typeof m||"function"!=typeof m.__cmp__?u==m:0===m.__cmp__(u):0===u.__cmp__(m))))||!1===t||0===t||""===t?0:"object"==
typeof t?"function"==typeof t.__nonzero__?t.__nonzero__():"function"==typeof t.__len__?0<t.__len__():1:1)for(b.eventNum=null===r?0:"undefined"!=typeof r.__array?r.__array.length:"function"==typeof r.__len__?r.__len__():"undefined"!=typeof r.length?r.length:$p.len(r),k=$p.range(b.eventNum),"undefined"!=typeof(a=k.__array)?c=0:(k=k.__iter__(),c="undefined"!=typeof(a=k.__array)?0:"function"==typeof k.$genfunc?1:-1),l=0;"undefined"!=typeof(u=c?0<c?k.next(!0,!1):$p.wrapped_next(k):a[l++]);)p=u,b.eventQueue.__setitem__(p,
"undefined"!=typeof(f=r).__array?"undefined"!=typeof f.__array[x=p]?f.__array[x]:f.__getitem__(x):f.__getitem__(p));(null===(q=1==(250===(w=b.eventNum)?0:"number"!=typeof w||"number"!=typeof w&&"string"!=typeof w&&"boolean"!=typeof w?$p.cmp(w,250):250==w?0:250>w?-1:1))||!1===q||0===q||""===q?0:"object"==typeof q?"function"==typeof q.__nonzero__?q.__nonzero__():"function"==typeof q.__len__?0<q.__len__():1:1)&&b._pump()}b._unlock();return null},1,[null,null,["self"],["eventType",null]]);m.clear=f;f=
$pyjs__bind_method2("event_name",function(d,b){if(!0===this.__is_instance__)var e=this;else e=d,d=b;var a,c,f,g,l,k;a="undefined"!=typeof(g="undefined"!=typeof(l=e.eventTypes).__array?"undefined"!=typeof l.__array[f=d]?l.__array[f]:l.__getitem__(f):l.__getitem__(d)).__array?"undefined"!=typeof g.__array[0]?g.__array[0]:g.__getitem__(0):g.__getitem__(0);return(null===(k=e.eventName.__contains__(a))||!1===k||0===k||""===k?0:"object"==typeof k?"function"==typeof k.__nonzero__?k.__nonzero__():"function"==
typeof k.__len__?0<k.__len__():1:1)?"undefined"!=typeof(c=e.eventName).__array?"undefined"!=typeof c.__array[a]?c.__array[a]:c.__getitem__(a):c.__getitem__(a):null},1,[null,null,["self"],["eventType"]]);m.event_name=f;f=$pyjs__bind_method2("set_blocked",function(d,b){if(!0===this.__is_instance__)var e=this;else e=d,d=b;var a,c,f,g,l,k;if(null===(a=null!==d)||!1===a||0===a||""===a?0:"object"==typeof a?"function"==typeof a.__nonzero__?a.__nonzero__():"function"==typeof a.__len__?0<a.__len__():1:1)for(c=
a=(null===(k=!(null===(g=$p.isinstance(d,$p.tuple([$p.tuple,$p.list])))||!1===g||0===g||""===g?0:"object"==typeof g?"function"==typeof g.__nonzero__?g.__nonzero__():"function"==typeof g.__len__?0<g.__len__():1:1))||!1===k||0===k||""===k?0:"object"==typeof k?"function"==typeof k.__nonzero__?k.__nonzero__():"function"==typeof k.__len__?0<k.__len__():1:1)?function(){var a,c,b,g,h,k;k=$p.list();b="undefined"!=typeof(g=e.eventTypes).__array?"undefined"!=typeof g.__array[a=d]?g.__array[a]:g.__getitem__(a):
g.__getitem__(d);"undefined"!=typeof(h=b.__array)?a=0:(b=b.__iter__(),a="undefined"!=typeof(h=b.__array)?0:"function"==typeof b.$genfunc?1:-1);for(g=0;"undefined"!=typeof(c=a?0<a?b.next(!0,!1):$p.wrapped_next(b):h[g++]);)k.append(c);return k}():function(){var a,c,b,g,h,k,f,l,n,m,t,v;a=$p.list();v=d;"undefined"!=typeof(f=v.__array)?k=0:(v=v.__iter__(),k="undefined"!=typeof(f=v.__array)?0:"function"==typeof v.$genfunc?1:-1);for(c=0;"undefined"!=typeof(b=k?0<k?v.next(!0,!1):$p.wrapped_next(v):f[c++]);)for(h=
"undefined"!=typeof(n=e.eventTypes).__array?"undefined"!=typeof n.__array[m=b]?n.__array[m]:n.__getitem__(m):n.__getitem__(b),"undefined"!=typeof(b=h.__array)?t=0:(h=h.__iter__(),t="undefined"!=typeof(b=h.__array)?0:"function"==typeof h.$genfunc?1:-1),l=0;"undefined"!=typeof(g=t?0<t?h.next(!0,!1):$p.wrapped_next(h):b[l++]);)a.append(g);return a}(),"undefined"!=typeof(a=c.__array)?k=0:(c=c.__iter__(),k="undefined"!=typeof(a=c.__array)?0:"function"==typeof c.$genfunc?1:-1),g=0;"undefined"!=typeof(l=
k?0<k?c.next(!0,!1):$p.wrapped_next(c):a[g++]);)(null===(f=e.events.__contains__(l))||!1===f||0===f||""===f?0:"object"==typeof f?"function"==typeof f.__nonzero__?f.__nonzero__():"function"==typeof f.__len__?0<f.__len__():1:1)&&e.events.remove(l);else for(a=e.eventType,"undefined"!=typeof(f=a.__array)?k=0:(a=a.__iter__(),k="undefined"!=typeof(f=a.__array)?0:"function"==typeof a.$genfunc?1:-1),g=0;"undefined"!=typeof(c=k?0<k?a.next(!0,!1):$p.wrapped_next(a):f[g++]);)e.events.add(c);return null},1,[null,
null,["self"],["eventType"]]);m.set_blocked=f;f=$pyjs__bind_method2("set_allowed",function(d,b){if(!0===this.__is_instance__)var e=this;else e=d,d=b;var a,c,f,g,l;if(null===(a=null!==d)||!1===a||0===a||""===a?0:"object"==typeof a?"function"==typeof a.__nonzero__?a.__nonzero__():"function"==typeof a.__len__?0<a.__len__():1:1)for(l=a=(null===(c=!(null===(f=$p.isinstance(d,$p.tuple([$p.tuple,$p.list])))||!1===f||0===f||""===f?0:"object"==typeof f?"function"==typeof f.__nonzero__?f.__nonzero__():"function"==
typeof f.__len__?0<f.__len__():1:1))||!1===c||0===c||""===c?0:"object"==typeof c?"function"==typeof c.__nonzero__?c.__nonzero__():"function"==typeof c.__len__?0<c.__len__():1:1)?function(){var a,b,c,g,h,f;g=$p.list();h="undefined"!=typeof(c=e.eventTypes).__array?"undefined"!=typeof c.__array[a=d]?c.__array[a]:c.__getitem__(a):c.__getitem__(d);"undefined"!=typeof(a=h.__array)?f=0:(h=h.__iter__(),f="undefined"!=typeof(a=h.__array)?0:"function"==typeof h.$genfunc?1:-1);for(c=0;"undefined"!=typeof(b=
f?0<f?h.next(!0,!1):$p.wrapped_next(h):a[c++]);)g.append(b);return g}():function(){var a,c,b,h,g,f,l,n,m,x,r,t;g=$p.list();h=d;"undefined"!=typeof(r=h.__array)?b=0:(h=h.__iter__(),b="undefined"!=typeof(r=h.__array)?0:"function"==typeof h.$genfunc?1:-1);for(m=0;"undefined"!=typeof(a=b?0<b?h.next(!0,!1):$p.wrapped_next(h):r[m++]);)for(x="undefined"!=typeof(l=e.eventTypes).__array?"undefined"!=typeof l.__array[t=a]?l.__array[t]:l.__getitem__(t):l.__getitem__(a),"undefined"!=typeof(f=x.__array)?a=0:(x=
x.__iter__(),a="undefined"!=typeof(f=x.__array)?0:"function"==typeof x.$genfunc?1:-1),n=0;"undefined"!=typeof(c=a?0<a?x.next(!0,!1):$p.wrapped_next(x):f[n++]);)g.append(c);return g}(),"undefined"!=typeof(f=l.__array)?a=0:(l=l.__iter__(),a="undefined"!=typeof(f=l.__array)?0:"function"==typeof l.$genfunc?1:-1),c=0;"undefined"!=typeof(g=a?0<a?l.next(!0,!1):$p.wrapped_next(l):f[c++]);)e.events.add(g);else e.events.clear();return null},1,[null,null,["self"],["eventType"]]);m.set_allowed=f;f=$pyjs__bind_method2("get_blocked",
function(d,b){if(!0===this.__is_instance__)var e=this;else e=d,d=b;var a,c,f,g,l,k,m;a=$p.list();k="undefined"!=typeof(g=e.eventTypes).__array?"undefined"!=typeof g.__array[f=d]?g.__array[f]:g.__getitem__(f):g.__getitem__(d);"undefined"!=typeof(m=k.__array)?f=0:(k=k.__iter__(),f="undefined"!=typeof(m=k.__array)?0:"function"==typeof k.$genfunc?1:-1);for(g=0;"undefined"!=typeof(l=f?0<f?k.next(!0,!1):$p.wrapped_next(k):m[g++]);)a.append(l);a="undefined"!=typeof a.__array?"undefined"!=typeof a.__array[0]?
a.__array[0]:a.__getitem__(0):a.__getitem__(0);return(null===(c=!e.events.__contains__(a))||!1===c||0===c||""===c?0:"object"==typeof c?"function"==typeof c.__nonzero__?c.__nonzero__():"function"==typeof c.__len__?0<c.__len__():1:1)?!0:!1},1,[null,null,["self"],["eventType"]]);m.get_blocked=f;f=$pyjs__bind_method2("post",function(d,b){if(!0===this.__is_instance__)var e=this;else e=d,d=b;var a;e._lock();e._append(d);(null===(a=!e.events.__contains__(d.type))||!1===a||0===a||""===a?0:"object"==typeof a?
"function"==typeof a.__nonzero__?a.__nonzero__():"function"==typeof a.__len__?0<a.__len__():1:1)&&e.eventTypes.__setitem__(d.type,$p.list([d.type]));e._unlock();return null},1,[null,null,["self"],["event"]]);m.post=f;f=$pyjs__bind_method2("_nonimplemented_methods",function(d){d=!0===this.__is_instance__?this:d;var b;b=function(){$p.tuple($pyjs_array_slice.call(arguments,0,arguments.length));return null};b.__name__="$lambda1";b.__bind_type__=0;b.__args__=["arg",null];d.set_grab=b;b=function(){$p.tuple($pyjs_array_slice.call(arguments,
0,arguments.length));return!1};b.__name__="$lambda2";b.__bind_type__=0;b.__args__=["arg",null];d.get_grab=b;return null},1,[null,null,["self"]]);m._nonimplemented_methods=f;f=Array($p.object);var C=$p.dict(),A;for(A in m)C.__setitem__(A,m[A]);return $p._create_class("Event",$p.tuple(f),C)}();b.UserEvent=function(){var b={},f;b.__module__="pyjsdl.event";b.__slots__=$p.list(["type","attr"]);f=$pyjs__bind_method2("__init__",function(b){if(!0===this.__is_instance__)var f=this,e=$p.tuple($pyjs_array_slice.call(arguments,
1,arguments.length-1)),a=2<=arguments.length?arguments[arguments.length-1]:arguments[arguments.length];else f=arguments[0],b=arguments[1],e=$p.tuple($pyjs_array_slice.call(arguments,2,arguments.length-1)),a=3<=arguments.length?arguments[arguments.length-1]:arguments[arguments.length];null===a||"object"!=typeof a||"dict"!=a.__name__||"undefined"==typeof a.$pyjs_is_kwarg?("undefined"!=typeof a&&e.__array.push(a),a=arguments[arguments.length+1]):delete a.$pyjs_is_kwarg;"undefined"==typeof a&&(a=$p.__empty_dict(),
"undefined"!=typeof b?null!==b&&"undefined"!=typeof b.$pyjs_is_kwarg&&(a=b,b=arguments[2]):"undefined"!=typeof f&&null!==f&&"undefined"!=typeof f.$pyjs_is_kwarg&&(a=f,f=arguments[2]));var c,n,e=(null===(c=e)||!1===c||0===c||""===c?0:"object"==typeof c?"function"==typeof c.__nonzero__?c.__nonzero__():"function"==typeof c.__len__?0<c.__len__():1:1)?"undefined"!=typeof(n=e).__array?"undefined"!=typeof n.__array[0]?n.__array[0]:n.__getitem__(0):n.__getitem__(0):a;$p.object.__setattr__(f,"type",b);$p.object.__setattr__(f,
"attr",e);return null},1,["args",["kwargs"],["self"],["eventType"]]);b.__init__=f;f=$pyjs__bind_method2("__repr__",function(b){b=!0===this.__is_instance__?this:b;return $p.sprintf("%s(%s-UserEvent %r)",$p.tuple([b.__class__,b.type,b.attr]))},1,[null,null,["self"]]);b.__repr__=f;f=$pyjs__bind_method2("__getattr__",function(b,f){if(!0===this.__is_instance__)var e=this;else e=b,b=f;var a,c,n;if(null===(a=e.attr.__contains__(b))||!1===a||0===a||""===a?0:"object"==typeof a?"function"==typeof a.__nonzero__?
a.__nonzero__():"function"==typeof a.__len__?0<a.__len__():1:1)return"undefined"!=typeof(c=e.attr).__array?"undefined"!=typeof c.__array[n=b]?c.__array[n]:c.__getitem__(n):c.__getitem__(b);throw $p.AttributeError($p.sprintf("'Event' object has no attribute '%s'",b));},1,[null,null,["self"],["attr"]]);b.__getattr__=f;f=$pyjs__bind_method2("__setattr__",function(b,f,e){!0!==this.__is_instance__&&(b=f);throw $p.AttributeError($p.sprintf("'Event' object has no attribute '%s'",b));},1,[null,null,["self"],
["attr"],["value"]]);b.__setattr__=f;f=Array($p.object);var C=$p.dict(),A;for(A in b)C.__setitem__(A,b[A]);return $p._create_class("UserEvent",$p.tuple(f),C)}();b.JEvent=function(){var m={},f;m.__module__="pyjsdl.event";m._mouse_pos=$p.tuple([0,0]);m._types=$p.dict([["mousemove",b.Const.MOUSEMOTION],["mousedown",b.Const.MOUSEBUTTONDOWN],["mouseup",b.Const.MOUSEBUTTONUP],["wheel",b.Const.MOUSEBUTTONDOWN],["mousewheel",b.Const.MOUSEBUTTONDOWN],["DOMMouseScroll",b.Const.MOUSEBUTTONDOWN],["keydown",b.Const.KEYDOWN],
["keypress",b.Const.KEYDOWN],["keyup",b.Const.KEYUP]]);m._charCode=$p.dict([[33,b.Const.K_EXCLAIM],[34,b.Const.K_QUOTEDBL],[35,b.Const.K_HASH],[36,b.Const.K_DOLLAR],[38,b.Const.K_AMPERSAND],[39,b.Const.K_QUOTE],[40,b.Const.K_LEFTPAREN],[41,b.Const.K_RIGHTPAREN],[42,b.Const.K_ASTERISK],[43,b.Const.K_PLUS],[44,b.Const.K_COMMA],[45,b.Const.K_MINUS],[46,b.Const.K_PERIOD],[97,b.Const.K_a],[98,b.Const.K_b],[99,b.Const.K_c],[100,b.Const.K_d],[101,b.Const.K_e],[102,b.Const.K_f],[103,b.Const.K_g],[104,b.Const.K_h],
[105,b.Const.K_i],[106,b.Const.K_j],[107,b.Const.K_k],[108,b.Const.K_l],[109,b.Const.K_m],[110,b.Const.K_n],[111,b.Const.K_o],[112,b.Const.K_p],[113,b.Const.K_q],[114,b.Const.K_r],[115,b.Const.K_s],[116,b.Const.K_t],[117,b.Const.K_u],[118,b.Const.K_v],[119,b.Const.K_w],[120,b.Const.K_x],[121,b.Const.K_y],[122,b.Const.K_z]]);f=$pyjs__bind_method2("__init__",function(d,f){if(!0===this.__is_instance__)var e=this;else e=d,d=f;var a,c,n,g,l,k,m,q,u,p,A,w,F,y,x,r,t,v,D,B,C,K,L,I,M,N,O,G,H,E,z,J;e.event=
d;if(null===(y=$p.tuple(["mousedown","mouseup"]).__contains__(d.type))||!1===y||0===y||""===y?0:"object"==typeof y?"function"==typeof y.__nonzero__?y.__nonzero__():"function"==typeof y.__len__?0<y.__len__():1:1)e.type="undefined"!=typeof(g=e.__class__._types).__array?"undefined"!=typeof g.__array[l=d.type]?g.__array[l]:g.__getitem__(l):g.__getitem__(d.type),e.button=d.button+1,e.pos=$p.tuple([("undefined"!=typeof(k=d.pos).__array?"undefined"!=typeof k.__array[0]?k.__array[0]:k.__getitem__(0):k.__getitem__(0))+
b.env.frame.scrollLeft,("undefined"!=typeof(m=d.pos).__array?"undefined"!=typeof m.__array[1]?m.__array[1]:m.__getitem__(1):m.__getitem__(1))+b.env.frame.scrollTop]);else if(null===(v="mousemove"===(B=d.type)&&null===B?!0:null===B?!1:"object"!=typeof B&&"function"!=typeof B||"function"!=typeof B.__cmp__?"mousemove"==B:0===B.__cmp__("mousemove"))||!1===v||0===v||""===v?0:"object"==typeof v?"function"==typeof v.__nonzero__?v.__nonzero__():"function"==typeof v.__len__?0<v.__len__():1:1)e.type="undefined"!=
typeof(n=e.__class__._types).__array?"undefined"!=typeof n.__array[w=d.type]?n.__array[w]:n.__getitem__(w):n.__getitem__(d.type),e.button=d.button+1,e.pos=$p.tuple([("undefined"!=typeof(A=d.pos).__array?"undefined"!=typeof A.__array[0]?A.__array[0]:A.__getitem__(0):A.__getitem__(0))+b.env.frame.scrollLeft,("undefined"!=typeof(F=d.pos).__array?"undefined"!=typeof F.__array[1]?F.__array[1]:F.__getitem__(1):F.__getitem__(1))+b.env.frame.scrollTop]),e.rel=$p.tuple([("undefined"!=typeof(u=e.pos).__array?
"undefined"!=typeof u.__array[0]?u.__array[0]:u.__getitem__(0):u.__getitem__(0))-("undefined"!=typeof(p=e.__class__._mouse_pos).__array?"undefined"!=typeof p.__array[0]?p.__array[0]:p.__getitem__(0):p.__getitem__(0)),("undefined"!=typeof(q=e.pos).__array?"undefined"!=typeof q.__array[1]?q.__array[1]:q.__getitem__(1):q.__getitem__(1))-("undefined"!=typeof(K=e.__class__._mouse_pos).__array?"undefined"!=typeof K.__array[1]?K.__array[1]:K.__getitem__(1):K.__getitem__(1))]),e.__class__._mouse_pos=e.pos;
else if(null===(t=$p.tuple(["wheel","mousewheel","DOMMouseScroll"]).__contains__(d.type))||!1===t||0===t||""===t?0:"object"==typeof t?"function"==typeof t.__nonzero__?t.__nonzero__():"function"==typeof t.__len__?0<t.__len__():1:1)e.type="undefined"!=typeof(C=e.__class__._types).__array?"undefined"!=typeof C.__array[I=d.type]?C.__array[I]:C.__getitem__(I):C.__getitem__(d.type),e.button=d.btn,e.pos=$p.tuple([("undefined"!=typeof(M=d.pos).__array?"undefined"!=typeof M.__array[0]?M.__array[0]:M.__getitem__(0):
M.__getitem__(0))+b.env.frame.scrollLeft,("undefined"!=typeof(L=d.pos).__array?"undefined"!=typeof L.__array[1]?L.__array[1]:L.__getitem__(1):L.__getitem__(1))+b.env.frame.scrollTop]);else if(null===(G=$p.tuple(["keydown","keyup"]).__contains__(d.type))||!1===G||0===G||""===G?0:"object"==typeof G?"function"==typeof G.__nonzero__?G.__nonzero__():"function"==typeof G.__len__?0<G.__len__():1:1)e.type="undefined"!=typeof(N=e.__class__._types).__array?"undefined"!=typeof N.__array[O=d.type]?N.__array[O]:
N.__getitem__(O):N.__getitem__(d.type),e.key=d.keyCode;else if(null===(H="keypress"===(J=d.type)&&null===J?!0:null===J?!1:"object"!=typeof J&&"function"!=typeof J||"function"!=typeof J.__cmp__?"keypress"==J:0===J.__cmp__("keypress"))||!1===H||0===H||""===H?0:"object"==typeof H?"function"==typeof H.__nonzero__?H.__nonzero__():"function"==typeof H.__len__?0<H.__len__():1:1)e.type="undefined"!=typeof(D=e.__class__._types).__array?"undefined"!=typeof D.__array[r=d.type]?D.__array[r]:D.__getitem__(r):
D.__getitem__(d.type),a=(null===(E=d.keyCode)||!1===E||0===E||""===E?0:"object"==typeof E?"function"==typeof E.__nonzero__?E.__nonzero__():"function"==typeof E.__len__?0<E.__len__():1:1)?d.keyCode:d.which,(null===(z=e.__class__._charCode.__contains__(a))||!1===z||0===z||""===z?0:"object"==typeof z?"function"==typeof z.__nonzero__?z.__nonzero__():"function"==typeof z.__len__?0<z.__len__():1:1)?e.key="undefined"!=typeof(c=e.__class__._charCode).__array?"undefined"!=typeof c.__array[a]?c.__array[a]:
c.__getitem__(a):c.__getitem__(a):e.key=a;else for(e.type=d.type,z=d.attr,"undefined"!=typeof(E=z.__array)?c=0:(z=z.__iter__(),c="undefined"!=typeof(E=z.__array)?0:"function"==typeof z.$genfunc?1:-1),n=0;"undefined"!=typeof(g=c?0<c?z.next(!0,!1):$p.wrapped_next(z):E[n++]);)$p.object.__setattr__(e,g,"undefined"!=typeof(x=d.attr).__array?"undefined"!=typeof x.__array[a=g]?x.__array[a]:x.__getitem__(a):x.__getitem__(g));return null},1,[null,null,["self"],["event"]]);m.__init__=f;f=$pyjs__bind_method2("__repr__",
function(b){b=!0===this.__is_instance__?this:b;var f;return(null===(f=$p.hasattr(b.event,"toString"))||!1===f||0===f||""===f?0:"object"==typeof f?"function"==typeof f.__nonzero__?f.__nonzero__():"function"==typeof f.__len__?0<f.__len__():1:1)?$p.sprintf("%s(%s)",$p.tuple([b.__class__,b.event.toString()])):b.event.__repr__()},1,[null,null,["self"]]);m.__repr__=f;f=$pyjs__bind_method2("getEvent",function(b){return(!0===this.__is_instance__?this:b).event},1,[null,null,["self"]]);m.getEvent=f;f=Array($p.object);
var C=$p.dict(),A;for(A in m)C.__setitem__(A,m[A]);return $p._create_class("JEvent",$p.tuple(f),C)}();return this};
