$pyjs.loaded_modules.avatar=function(y){if($pyjs.loaded_modules.avatar.__was_initialized__)return $pyjs.loaded_modules.avatar;var q=$pyjs.loaded_modules.avatar;q.__repr__=function(){return"<module: avatar>"};q.__was_initialized__=!0;if(null===y||"undefined"==typeof y)y="avatar";q.__name__=y;q.env=$p.___import___("env",null);q.engine=q.env.engine;q.Pulse=$p.___import___("pulse.Pulse",null,null,!1);q.load_sound=$p.___import___("util.load_sound",null,null,!1);q.Avatar=function(){var p={},l;p.__module__=
"avatar";p.images=null;p.mask=null;p.sound=null;l=$pyjs__bind_method2("__init__",function(b,c,d){if(!0===this.__is_instance__)var a=this;else a=arguments[0],b=arguments[1],c=arguments[2],d=arguments[3];"undefined"==typeof c&&(c=arguments.callee.__args__[4][1]);"undefined"==typeof d&&(d=arguments.callee.__args__[5][1]);var e,f,g,h,m,k,t,n,l,u,s,r,z,v,w;q.engine.sprite.Sprite.__init__(a);a.matrix=b;a.x=$p["float"](c);a.y=$p["float"](d);if(null===(e=!(null===(k=a.images)||!1===k||0===k||""===k?0:"object"==
typeof k?"function"==typeof k.__nonzero__?k.__nonzero__():"function"==typeof k.__len__?0<k.__len__():1:1))||!1===e||0===e||""===e?0:"object"==typeof e?"function"==typeof e.__nonzero__?e.__nonzero__():"function"==typeof e.__len__?0<e.__len__():1:1)a.images=$p.dict([]),e=q.engine.Surface($p.tuple([50,50]),q.engine.SRCALPHA),t=$p.tuple([80,100,120]),l=$p.tuple([80,100,200]),n=$p.tuple([50,50,200]),k=function(){var a,b,c,d,e,f,g,h;c=$p.list();d=$p.list([$p.tuple([12,0]),$p.tuple([16,10]),$p.tuple([24,
13]),$p.tuple([16,18]),$p.tuple([12,24]),$p.tuple([8,18]),$p.tuple([0,13]),$p.tuple([8,10])]);"undefined"!=typeof(h=d.__array)?b=0:(d=d.__iter__(),b="undefined"!=typeof(h=d.__array)?0:"function"==typeof d.$genfunc?1:-1);for(e=0;"undefined"!=typeof(a=b?0<b?d.next(!0,!1):$p.wrapped_next(d):h[e++]);)c.append($p.tuple([2*("undefined"!=typeof(f=a).__array?"undefined"!=typeof f.__array[0]?f.__array[0]:f.__getitem__(0):f.__getitem__(0)),2*("undefined"!=typeof(g=a).__array?"undefined"!=typeof g.__array[1]?
g.__array[1]:g.__getitem__(1):g.__getitem__(1))]));return c}(),q.engine.draw.polygon(e,t,k,0),k=function(){var a,b,c,d,e,f,g,h;d=$p.list();c=$p.list([$p.tuple([16,11]),$p.tuple([23,13]),$p.tuple([16,17])]);"undefined"!=typeof(h=c.__array)?b=0:(c=c.__iter__(),b="undefined"!=typeof(h=c.__array)?0:"function"==typeof c.$genfunc?1:-1);for(e=0;"undefined"!=typeof(a=b?0<b?c.next(!0,!1):$p.wrapped_next(c):h[e++]);)d.append($p.tuple([2*("undefined"!=typeof(g=a).__array?"undefined"!=typeof g.__array[0]?g.__array[0]:
g.__getitem__(0):g.__getitem__(0)),2*("undefined"!=typeof(f=a).__array?"undefined"!=typeof f.__array[1]?f.__array[1]:f.__getitem__(1):f.__getitem__(1))]));return d}(),q.engine.draw.polygon(e,l,k,0),k=function(){var a,b,c,d,e,f,g,h;e=$p.list();g=$p.list([$p.tuple([8,11]),$p.tuple([1,13]),$p.tuple([8,17])]);"undefined"!=typeof(h=g.__array)?d=0:(g=g.__iter__(),d="undefined"!=typeof(h=g.__array)?0:"function"==typeof g.$genfunc?1:-1);for(a=0;"undefined"!=typeof(c=d?0<d?g.next(!0,!1):$p.wrapped_next(g):
h[a++]);)e.append($p.tuple([2*("undefined"!=typeof(f=c).__array?"undefined"!=typeof f.__array[0]?f.__array[0]:f.__getitem__(0):f.__getitem__(0)),2*("undefined"!=typeof(b=c).__array?"undefined"!=typeof b.__array[1]?b.__array[1]:b.__getitem__(1):b.__getitem__(1))]));return e}(),q.engine.draw.polygon(e,l,k,0),k=function(){var a,b,c,d,e,f,g,h;d=$p.list();h=$p.list([$p.tuple([12,8]),$p.tuple([15,11]),$p.tuple([15,17]),$p.tuple([12,20]),$p.tuple([9,17]),$p.tuple([9,11])]);"undefined"!=typeof(g=h.__array)?
f=0:(h=h.__iter__(),f="undefined"!=typeof(g=h.__array)?0:"function"==typeof h.$genfunc?1:-1);for(e=0;"undefined"!=typeof(c=f?0<f?h.next(!0,!1):$p.wrapped_next(h):g[e++]);)d.append($p.tuple([2*("undefined"!=typeof(b=c).__array?"undefined"!=typeof b.__array[0]?b.__array[0]:b.__getitem__(0):b.__getitem__(0)),2*("undefined"!=typeof(a=c).__array?"undefined"!=typeof a.__array[1]?a.__array[1]:a.__getitem__(1):a.__getitem__(1))]));return d}(),q.engine.draw.polygon(e,n,k,0),a.images.__setitem__("normal",e),
a.mask=q.engine.mask.from_surface("undefined"!=typeof(u=a.images).__array?"undefined"!=typeof u.__array.normal?u.__array.normal:u.__getitem__("normal"):u.__getitem__("normal")),a.sound=$p.dict([]),a.sound.__setitem__("pulse",q.load_sound("pulse.wav")),("undefined"!=typeof(z=a.sound).__array?"undefined"!=typeof z.__array.pulse?z.__array.pulse:z.__getitem__("pulse"):z.__getitem__("pulse")).set_volume(0.1),a.sound.__setitem__("surge",q.load_sound("pulse.wav")),("undefined"!=typeof(g=a.sound).__array?
"undefined"!=typeof g.__array.surge?g.__array.surge:g.__getitem__("surge"):g.__getitem__("surge")).set_volume(0.2),a.sound.__setitem__("spike",q.load_sound("explode.wav")),("undefined"!=typeof(w=a.sound).__array?"undefined"!=typeof w.__array.spike?w.__array.spike:w.__getitem__("spike"):w.__getitem__("spike")).set_volume(0.2),a.sound.__setitem__("shot",q.load_sound("explode.wav")),("undefined"!=typeof(h=a.sound).__array?"undefined"!=typeof h.__array.shot?h.__array.shot:h.__getitem__("shot"):h.__getitem__("shot")).set_volume(0.05),
a.sound.__setitem__("explode",q.load_sound("explode.wav")),("undefined"!=typeof(m=a.sound).__array?"undefined"!=typeof m.__array.explode?m.__array.explode:m.__getitem__("explode"):m.__getitem__("explode")).set_volume(0.1),a.sound.__setitem__("repair",q.load_sound("repair.wav")),("undefined"!=typeof(f=a.sound).__array?"undefined"!=typeof f.__array.repair?f.__array.repair:f.__getitem__("repair"):f.__getitem__("repair")).set_volume(0.2);a.image="undefined"!=typeof(v=a.images).__array?"undefined"!=typeof v.__array.normal?
v.__array.normal:v.__getitem__("normal"):v.__getitem__("normal");a.rect=$pyjs_kwargs_call(a.image,"get_rect",null,null,[{center:$p.tuple([$p.float_int(a.x),$p.float_int(a.y)])}]);a.rect_center=a.rect.inflate(-40,-40);a.width=a.image.get_width();a.height=a.image.get_height();a.radius=Math.floor(a.image.get_width()/2);a.channel=q.engine.mixer.Channel(0);(null===(r=!(null===(s=a.matrix.adjust)||!1===s||0===s||""===s?0:"object"==typeof s?"function"==typeof s.__nonzero__?s.__nonzero__():"function"==typeof s.__len__?
0<s.__len__():1:1))||!1===r||0===r||""===r?0:"object"==typeof r?"function"==typeof r.__nonzero__?r.__nonzero__():"function"==typeof r.__len__?0<r.__len__():1:1)?(a.velocity=5,a.vel=a.velocity,a.vel_max=10):(a.velocity=10,a.vel=a.velocity,a.vel_max=25);a.node_position=$p.list([$p.float_int(a.x),$p.float_int(a.y)]);a.motion=$p.dict([["u",!1],["d",!1],["l",!1],["r",!1]]);a.moving=!1;a.dir="v";a.dirs=$p.dict([["u",-1],["d",1],["l",-1],["r",1]]);a.dir_offset=$p.dict([["u",$p.tuple([0,-1])],["d",$p.tuple([0,
1])],["l",$p.tuple([-1,0])],["r",$p.tuple([1,0])]]);a.orient=$p.dict([["u","v"],["d","v"],["l","h"],["r","h"]]);a.field=$p.dict([["u",50],["d",450],["l",50],["r",450]]);a.control=$p.dict([["z",!1],["x",!1]]);a.active=!1;a.pulse_charge=1;a.pulse_aim="u";a.power=1;a.targets=$p.list([a.matrix.bots]);a.identity="Avatar";a.controls=$p.dict([["u",!1],["d",!1],["l",!1],["r",!1],["z",!1],["x",!1]]);return null},1,[null,null,["self"],["matrix"],["x",null],["y",null]]);p.__init__=l;l=$pyjs__bind_method2("node",
function(b){b=!0===this.__is_instance__?this:b;return b.matrix.nodes.__contains__($p.tuple([$p.float_int(b.x),$p.float_int(b.y)]))},1,[null,null,["self"]]);p.node=l;l=$pyjs__bind_method2("node_thread",function(b){b=!0===this.__is_instance__?this:b;var c,d,a,e,f,g,h;a=$p.list();f=b.matrix.nodex;"undefined"!=typeof(g=f.__array)?h=0:(f=f.__iter__(),h="undefined"!=typeof(g=f.__array)?0:"function"==typeof f.$genfunc?1:-1);for(d=0;"undefined"!=typeof(c=h?0<h?f.next(!0,!1):$p.wrapped_next(f):g[d++]);)a.append("undefined"!=
typeof(e=c).__array?"undefined"!=typeof e.__array[0]?e.__array[0]:e.__getitem__(0):e.__getitem__(0));return a.__contains__(b.x)},1,[null,null,["self"]]);p.node_thread=l;l=$pyjs__bind_method2("set_control",function(b,c,d){if(!0===this.__is_instance__)var a=this;else a=b,b=c,c=d;var e,f,g,h,m,k,t,n;if(null===(k=a.controls.__contains__(b))||!1===k||0===k||""===k?0:"object"==typeof k?"function"==typeof k.__nonzero__?k.__nonzero__():"function"==typeof k.__len__?0<k.__len__():1:1)(null===(m=!((e="undefined"!=
typeof(g=a.controls).__array?"undefined"!=typeof g.__array[h=b]?g.__array[h]:g.__getitem__(h):g.__getitem__(b))===(f=c)&&null===e||(null===e?0:null===f?0:"object"!=typeof e&&"function"!=typeof e||"function"!=typeof e.__cmp__?"object"!=typeof f&&"function"!=typeof f||"function"!=typeof f.__cmp__?e==f:0===f.__cmp__(e):0===e.__cmp__(f))))||!1===m||0===m||""===m?0:"object"==typeof m?"function"==typeof m.__nonzero__?m.__nonzero__():"function"==typeof m.__len__?0<m.__len__():1:1)&&a.controls.__setitem__(b,
c),(null===(n=a.motion.__contains__(b))||!1===n||0===n||""===n?0:"object"==typeof n?"function"==typeof n.__nonzero__?n.__nonzero__():"function"==typeof n.__len__?0<n.__len__():1:1)?(null===(t=c)||!1===t||0===t||""===t?0:"object"==typeof t?"function"==typeof t.__nonzero__?t.__nonzero__():"function"==typeof t.__len__?0<t.__len__():1:1)&&a.motion_state(b):a.control_state(b);return null},1,[null,null,["self"],["ctrl"],["state"]]);p.set_control=l;l=$pyjs__bind_method2("motion_state",function(b){if(!0===
this.__is_instance__)var c=this;else c=arguments[0],b=arguments[1];"undefined"==typeof b&&(b=arguments.callee.__args__[3][1]);var d,a,e,f,g,h,m,k,t,n,l,u,s,r,q,v,w,p,J,E,D,x,G,K,I,L,F,A,B,C,M,N,y,O,H,aa,ba,P,Q,R,S,W,T,X,U,V,Y,Z,$;if(null===(g=(null===(e=p=!(null===(x=c.moving)||!1===x||0===x||""===x?0:"object"==typeof x?"function"==typeof x.__nonzero__?x.__nonzero__():"function"==typeof x.__len__?0<x.__len__():1:1))||!1===e||0===e||""===e?0:"object"==typeof e?"function"==typeof e.__nonzero__?e.__nonzero__():
"function"==typeof e.__len__?0<e.__len__():1:1)?!(null===(f="undefined"!=typeof(Z=c.control).__array?"undefined"!=typeof Z.__array.x?Z.__array.x:Z.__getitem__("x"):Z.__getitem__("x"))||!1===f||0===f||""===f?0:"object"==typeof f?"function"==typeof f.__nonzero__?f.__nonzero__():"function"==typeof f.__len__?0<f.__len__():1:1):p)||!1===g||0===g||""===g?0:"object"==typeof g?"function"==typeof g.__nonzero__?g.__nonzero__():"function"==typeof g.__len__?0<g.__len__():1:1){if(null===(h=b)||!1===h||0===h||
""===h?0:"object"==typeof h?"function"==typeof h.__nonzero__?h.__nonzero__():"function"==typeof h.__len__?0<h.__len__():1:1)p=b;else{p=null;f=c.motion;"undefined"!=typeof(e=f.__array)?h=0:(f=f.__iter__(),h="undefined"!=typeof(e=f.__array)?0:"function"==typeof f.$genfunc?1:-1);for(g=0;"undefined"!=typeof(x=h?0<h?f.next(!0,!1):$p.wrapped_next(f):e[g++]);)if(null===(m="undefined"!=typeof(y=c.controls).__array?"undefined"!=typeof y.__array[r=x]?y.__array[r]:y.__getitem__(r):y.__getitem__(x))||!1===m||
0===m||""===m?0:"object"==typeof m?"function"==typeof m.__nonzero__?m.__nonzero__():"function"==typeof m.__len__?0<m.__len__():1:1){p=x;break}if(null===(t=!(null===(k=p)||!1===k||0===k||""===k?0:"object"==typeof k?"function"==typeof k.__nonzero__?k.__nonzero__():"function"==typeof k.__len__?0<k.__len__():1:1))||!1===t||0===t||""===t?0:"object"==typeof t?"function"==typeof t.__nonzero__?t.__nonzero__():"function"==typeof t.__len__?0<t.__len__():1:1)return null}if(null===(A=(null===(C=H=(null===(n=
J="l"===(P=p)&&null===P?!0:null===P?!1:"object"!=typeof P&&"function"!=typeof P||"function"!=typeof P.__cmp__?"l"==P:0===P.__cmp__("l"))||!1===n||0===n||""===n?0:"object"==typeof n?"function"==typeof n.__nonzero__?n.__nonzero__():"function"==typeof n.__len__?0<n.__len__():1:1)?1==((U="undefined"!=typeof(s=c.node_position).__array?"undefined"!=typeof s.__array[0]?s.__array[0]:s.__getitem__(0):s.__getitem__(0))===(Y="undefined"!=typeof(u=c.field).__array?"undefined"!=typeof u.__array.l?u.__array.l:
u.__getitem__("l"):u.__getitem__("l"))?0:typeof U!=typeof Y||"number"!=typeof U&&"string"!=typeof U&&"boolean"!=typeof U?$p.cmp(U,Y):U==Y?0:U<Y?-1:1):J)||!1===C||0===C||""===C?0:"object"==typeof C?"function"==typeof C.__nonzero__?C.__nonzero__():"function"==typeof C.__len__?0<C.__len__():1:1)?H:(null===(B=ba=(null===(d=E="r"===(R=p)&&null===R?!0:null===R?!1:"object"!=typeof R&&"function"!=typeof R||"function"!=typeof R.__cmp__?"r"==R:0===R.__cmp__("r"))||!1===d||0===d||""===d?0:"object"==typeof d?
"function"==typeof d.__nonzero__?d.__nonzero__():"function"==typeof d.__len__?0<d.__len__():1:1)?-1==((V="undefined"!=typeof(v=c.node_position).__array?"undefined"!=typeof v.__array[0]?v.__array[0]:v.__getitem__(0):v.__getitem__(0))===(W="undefined"!=typeof(q=c.field).__array?"undefined"!=typeof q.__array.r?q.__array.r:q.__getitem__("r"):q.__getitem__("r"))?0:typeof V!=typeof W||"number"!=typeof V&&"string"!=typeof V&&"boolean"!=typeof V?$p.cmp(V,W):V==W?0:V<W?-1:1):E)||!1===B||0===B||""===B?0:"object"==
typeof B?"function"==typeof B.__nonzero__?B.__nonzero__():"function"==typeof B.__len__?0<B.__len__():1:1)?ba:(null===(N=aa=(null===(a=D="u"===(Q=p)&&null===Q?!0:null===Q?!1:"object"!=typeof Q&&"function"!=typeof Q||"function"!=typeof Q.__cmp__?"u"==Q:0===Q.__cmp__("u"))||!1===a||0===a||""===a?0:"object"==typeof a?"function"==typeof a.__nonzero__?a.__nonzero__():"function"==typeof a.__len__?0<a.__len__():1:1)?1==((S="undefined"!=typeof(l=c.node_position).__array?"undefined"!=typeof l.__array[1]?l.__array[1]:
l.__getitem__(1):l.__getitem__(1))===(X="undefined"!=typeof(K=c.field).__array?"undefined"!=typeof K.__array.u?K.__array.u:K.__getitem__("u"):K.__getitem__("u"))?0:typeof S!=typeof X||"number"!=typeof S&&"string"!=typeof S&&"boolean"!=typeof S?$p.cmp(S,X):S==X?0:S<X?-1:1):D)||!1===N||0===N||""===N?0:"object"==typeof N?"function"==typeof N.__nonzero__?N.__nonzero__():"function"==typeof N.__len__?0<N.__len__():1:1)?aa:(null===(M=w="d"===(O=p)&&null===O?!0:null===O?!1:"object"!=typeof O&&"function"!=
typeof O||"function"!=typeof O.__cmp__?"d"==O:0===O.__cmp__("d"))||!1===M||0===M||""===M?0:"object"==typeof M?"function"==typeof M.__nonzero__?M.__nonzero__():"function"==typeof M.__len__?0<M.__len__():1:1)?-1==((T="undefined"!=typeof(I=c.node_position).__array?"undefined"!=typeof I.__array[1]?I.__array[1]:I.__getitem__(1):I.__getitem__(1))===($="undefined"!=typeof(L=c.field).__array?"undefined"!=typeof L.__array.d?L.__array.d:L.__getitem__("d"):L.__getitem__("d"))?0:typeof T!=typeof $||"number"!=
typeof T&&"string"!=typeof T&&"boolean"!=typeof T?$p.cmp(T,$):T==$?0:T<$?-1:1):w)||!1===A||0===A||""===A?0:"object"==typeof A?"function"==typeof A.__nonzero__?A.__nonzero__():"function"==typeof A.__len__?0<A.__len__():1:1)c.motion.__setitem__(p,"undefined"!=typeof(F=c.controls).__array?"undefined"!=typeof F.__array[G=p]?F.__array[G]:F.__getitem__(G):F.__getitem__(p)),c.moving=!0}return null},1,[null,null,["self"],["ctrl",null]]);p.motion_state=l;l=$pyjs__bind_method2("control_state",function(b){if(!0===
this.__is_instance__)var c=this;else c=arguments[0],b=arguments[1];"undefined"==typeof b&&(b=arguments.callee.__args__[3][1]);var d,a,e,f,g,h,m,k,t,n,l,q,s,r;if(null===(d=b)||!1===d||0===d||""===d?0:"object"==typeof d?"function"==typeof d.__nonzero__?d.__nonzero__():"function"==typeof d.__len__?0<d.__len__():1:1)d=b;else for(d=null,n=c.control,"undefined"!=typeof(s=n.__array)?g=0:(n=n.__iter__(),g="undefined"!=typeof(s=n.__array)?0:"function"==typeof n.$genfunc?1:-1),l=0;"undefined"!=typeof(q=g?0<
g?n.next(!0,!1):$p.wrapped_next(n):s[l++]);)if(null===(e="undefined"!=typeof(r=c.controls).__array?"undefined"!=typeof r.__array[m=q]?r.__array[m]:r.__getitem__(m):r.__getitem__(q))||!1===e||0===e||""===e?0:"object"==typeof e?"function"==typeof e.__nonzero__?e.__nonzero__():"function"==typeof e.__len__?0<e.__len__():1:1){d=q;break}c.control.__setitem__(d,"undefined"!=typeof(h=c.controls).__array?"undefined"!=typeof h.__array[t=d]?h.__array[t]:h.__getitem__(t):h.__getitem__(d));(null===(a=d)||!1===
a||0===a||""===a?0:"object"==typeof a?"function"==typeof a.__nonzero__?a.__nonzero__():"function"==typeof a.__len__?0<a.__len__():1:1)?c.active="undefined"!=typeof(k=c.control).__array?"undefined"!=typeof k.__array[f=d]?k.__array[f]:k.__getitem__(f):k.__getitem__(d):c.active=!1;return null},1,[null,null,["self"],["ctrl",null]]);p.control_state=l;l=$pyjs__bind_method2("move",function(b){b=!0===this.__is_instance__?this:b;var c,d,a,e,f,g,h,m,k,t,n,l,q,s,r,p,v,w,y,J,E,D,x,G,K,I,L,F,A,B,C;d=$p.tuple(["u",
"d"]);"undefined"!=typeof(L=d.__array)?w=0:(d=d.__iter__(),w="undefined"!=typeof(L=d.__array)?0:"function"==typeof d.$genfunc?1:-1);for(p=0;"undefined"!=typeof(m=w?0<w?d.next(!0,!1):$p.wrapped_next(d):L[p++]);)if(null===(r="undefined"!=typeof(n=b.motion).__array?"undefined"!=typeof n.__array[q=m]?n.__array[q]:n.__getitem__(q):n.__getitem__(m))||!1===r||0===r||""===r?0:"object"==typeof r?"function"==typeof r.__nonzero__?r.__nonzero__():"function"==typeof r.__len__?0<r.__len__():1:1){if(null===(s=(a=
b.dir)===(e="undefined"!=typeof(l=b.orient).__array?"undefined"!=typeof l.__array[t=m]?l.__array[t]:l.__getitem__(t):l.__getitem__(m))&&null===a?!0:null===a?!1:null===e?!1:"object"!=typeof a&&"function"!=typeof a||"function"!=typeof a.__cmp__?"object"!=typeof e&&"function"!=typeof e||"function"!=typeof e.__cmp__?a==e:0===e.__cmp__(a):0===a.__cmp__(e))||!1===s||0===s||""===s?0:"object"==typeof s?"function"==typeof s.__nonzero__?s.__nonzero__():"function"==typeof s.__len__?0<s.__len__():1:1)b.y+=("undefined"!=
typeof(k=b.dirs).__array?"undefined"!=typeof k.__array[E=m]?k.__array[E]:k.__getitem__(E):k.__getitem__(m))*b.vel;else if(null===(B=b.node())||!1===B||0===B||""===B?0:"object"==typeof B?"function"==typeof B.__nonzero__?B.__nonzero__():"function"==typeof B.__len__?0<B.__len__():1:1)b.dir="v",b.y+=("undefined"!=typeof(D=b.dirs).__array?"undefined"!=typeof D.__array[J=m]?D.__array[J]:D.__getitem__(J):D.__getitem__(m))*b.vel;b.pulse_aim=m;return null}a=$p.tuple(["l","r"]);"undefined"!=typeof(t=a.__array)?
k=0:(a=a.__iter__(),k="undefined"!=typeof(t=a.__array)?0:"function"==typeof a.$genfunc?1:-1);for(e=0;"undefined"!=typeof(m=k?0<k?a.next(!0,!1):$p.wrapped_next(a):t[e++]);)if(null===(C="undefined"!=typeof(v=b.motion).__array?"undefined"!=typeof v.__array[K=m]?v.__array[K]:v.__getitem__(K):v.__getitem__(m))||!1===C||0===C||""===C?0:"object"==typeof C?"function"==typeof C.__nonzero__?C.__nonzero__():"function"==typeof C.__len__?0<C.__len__():1:1){if(null===(F=(f=b.dir)===(g="undefined"!=typeof(I=b.orient).__array?
"undefined"!=typeof I.__array[x=m]?I.__array[x]:I.__getitem__(x):I.__getitem__(m))&&null===f?!0:null===f?!1:null===g?!1:"object"!=typeof f&&"function"!=typeof f||"function"!=typeof f.__cmp__?"object"!=typeof g&&"function"!=typeof g||"function"!=typeof g.__cmp__?f==g:0===g.__cmp__(f):0===f.__cmp__(g))||!1===F||0===F||""===F?0:"object"==typeof F?"function"==typeof F.__nonzero__?F.__nonzero__():"function"==typeof F.__len__?0<F.__len__():1:1)b.x+=("undefined"!=typeof(G=b.dirs).__array?"undefined"!=typeof G.__array[h=
m]?G.__array[h]:G.__getitem__(h):G.__getitem__(m))*b.vel;else if(null===(A=b.node())||!1===A||0===A||""===A?0:"object"==typeof A?"function"==typeof A.__nonzero__?A.__nonzero__():"function"==typeof A.__len__?0<A.__len__():1:1)b.dir="h",b.x+=("undefined"!=typeof(c=b.dirs).__array?"undefined"!=typeof c.__array[y=m]?c.__array[y]:c.__getitem__(y):c.__getitem__(m))*b.vel;b.pulse_aim=m;break}return null},1,[null,null,["self"]]);p.move=l;l=$pyjs__bind_method2("momentum",function(b){b=!0===this.__is_instance__?
this:b;var c,d,a,e,f,g,h,m;if(null===(g=b.moving)||!1===g||0===g||""===g?0:"object"==typeof g?"function"==typeof g.__nonzero__?g.__nonzero__():"function"==typeof g.__len__?0<g.__len__():1:1)if(null===(d=b.node())||!1===d||0===d||""===d?0:"object"==typeof d?"function"==typeof d.__nonzero__?d.__nonzero__():"function"==typeof d.__len__?0<d.__len__():1:1){b.node_position.__setitem__(0,$p.float_int(b.x));b.node_position.__setitem__(1,$p.float_int(b.y));d=b.motion;"undefined"!=typeof(g=d.__array)?h=0:(d=
d.__iter__(),h="undefined"!=typeof(g=d.__array)?0:"function"==typeof d.$genfunc?1:-1);for(m=0;"undefined"!=typeof(c=h?0<h?d.next(!0,!1):$p.wrapped_next(d):g[m++]);)(null===(a="undefined"!=typeof(f=b.motion).__array?"undefined"!=typeof f.__array[e=c]?f.__array[e]:f.__getitem__(e):f.__getitem__(c))||!1===a||0===a||""===a?0:"object"==typeof a?"function"==typeof a.__nonzero__?a.__nonzero__():"function"==typeof a.__len__?0<a.__len__():1:1)&&b.motion.__setitem__(c,!1);b.vel=b.velocity;b.moving=!1;b.motion_state()}return null},
1,[null,null,["self"]]);p.momentum=l;l=$pyjs__bind_method2("action",function(b){b=!0===this.__is_instance__?this:b;var c,d,a;if(null===(d=b.active)||!1===d||0===d||""===d?0:"object"==typeof d?"function"==typeof d.__nonzero__?d.__nonzero__():"function"==typeof d.__len__?0<d.__len__():1:1)(null===(a="undefined"!=typeof(c=b.control).__array?"undefined"!=typeof c.__array.x?c.__array.x:c.__getitem__("x"):c.__getitem__("x"))||!1===a||0===a||""===a?0:"object"==typeof a?"function"==typeof a.__nonzero__?a.__nonzero__():
"function"==typeof a.__len__?0<a.__len__():1:1)?b.node_repair():b.activate_pulse();return null},1,[null,null,["self"]]);p.action=l;l=$pyjs__bind_method2("activate_pulse",function(b){b=!0===this.__is_instance__?this:b;var c,d,a,e,f,g,h,m,k,l,n,p,u,s,r,z,v,w;if(null===(n=(null===(w=p=1==((1===(c=b.pulse_charge)?0:"number"!=typeof c||"number"!=typeof c&&"string"!=typeof c&&"boolean"!=typeof c?$p.cmp(c,1):1==c?0:1>c?-1:1)|1))||!1===w||0===w||""===w?0:"object"==typeof w?"function"==typeof w.__nonzero__?
w.__nonzero__():"function"==typeof w.__len__?0<w.__len__():1:1)?1==(0.1===(u=b.power)?0:"number"!=typeof u||"number"!=typeof u&&"string"!=typeof u&&"boolean"!=typeof u?$p.cmp(u,0.1):0.1==u?0:0.1>u?-1:1):p)||!1===n||0===n||""===n?0:"object"==typeof n?"function"==typeof n.__nonzero__?n.__nonzero__():"function"==typeof n.__len__?0<n.__len__():1:1){c=(null===(k=(null===(l=f=q.engine.key.get_mods()&q.engine.KMOD_CTRL)||!1===l||0===l||""===l?0:"object"==typeof l?"function"==typeof l.__nonzero__?l.__nonzero__():
"function"==typeof l.__len__?0<l.__len__():1:1)?f:!("Avatar"===(a=b.identity)&&null===a||(null===a?0:"object"!=typeof a&&"function"!=typeof a||"function"!=typeof a.__cmp__?"Avatar"==a:0===a.__cmp__("Avatar"))))||!1===k||0===k||""===k?0:"object"==typeof k?"function"==typeof k.__nonzero__?k.__nonzero__():"function"==typeof k.__len__?0<k.__len__():1:1)?b.pulse_aim:"u";if(null===(m="u"===c&&null===c?!0:null===c?!1:"object"!=typeof c&&"function"!=typeof c||"function"!=typeof c.__cmp__?"u"==c:0===c.__cmp__("u"))||
!1===m||0===m||""===m?0:"object"==typeof m?"function"==typeof m.__nonzero__?m.__nonzero__():"function"==typeof m.__len__?0<m.__len__():1:1)v=b.x,z=b.y-b.height/2;if(null===(d="d"===c&&null===c?!0:null===c?!1:"object"!=typeof c&&"function"!=typeof c||"function"!=typeof c.__cmp__?"d"==c:0===c.__cmp__("d"))||!1===d||0===d||""===d?0:"object"==typeof d?"function"==typeof d.__nonzero__?d.__nonzero__():"function"==typeof d.__len__?0<d.__len__():1:1)v=b.x,z=b.y+b.height/2;if(null===(h="l"===c&&null===c?!0:
null===c?!1:"object"!=typeof c&&"function"!=typeof c||"function"!=typeof c.__cmp__?"l"==c:0===c.__cmp__("l"))||!1===h||0===h||""===h?0:"object"==typeof h?"function"==typeof h.__nonzero__?h.__nonzero__():"function"==typeof h.__len__?0<h.__len__():1:1)v=b.x-b.width/2,z=b.y;if(null===(g="r"===c&&null===c?!0:null===c?!1:"object"!=typeof c&&"function"!=typeof c||"function"!=typeof c.__cmp__?"r"==c:0===c.__cmp__("r"))||!1===g||0===g||""===g?0:"object"==typeof g?"function"==typeof g.__nonzero__?g.__nonzero__():
"function"==typeof g.__len__?0<g.__len__():1:1)v=b.x+b.width/2,z=b.y;b.matrix.pulses.add(q.Pulse(b.matrix,v,z,c,b.targets));b.power-=0.01;(null===(s=!(null===(r=q.env.debug)||!1===r||0===r||""===r?0:"object"==typeof r?"function"==typeof r.__nonzero__?r.__nonzero__():"function"==typeof r.__len__?0<r.__len__():1:1))||!1===s||0===s||""===s?0:"object"==typeof s?"function"==typeof s.__nonzero__?s.__nonzero__():"function"==typeof s.__len__?0<s.__len__():1:1)&&("undefined"!=typeof(e=b.sound).__array?"undefined"!=
typeof e.__array.pulse?e.__array.pulse:e.__getitem__("pulse"):e.__getitem__("pulse")).play();b.pulse_charge=0}return null},1,[null,null,["self"]]);p.activate_pulse=l;l=$pyjs__bind_method2("datum_collide",function(b){b=!0===this.__is_instance__?this:b;var c,d,a,e;a=q.engine.sprite.spritecollide(b,b.matrix.data,!1,b.matrix.collide_mask);"undefined"!=typeof(d=a.__array)?b=0:(a=a.__iter__(),b="undefined"!=typeof(d=a.__array)?0:"function"==typeof a.$genfunc?1:-1);for(e=0;"undefined"!=typeof(c=b?0<b?a.next(!0,
!1):$p.wrapped_next(a):d[e++]);)c.damage();return null},1,[null,null,["self"]]);p.datum_collide=l;l=$pyjs__bind_method2("shot",function(b){b=!0===this.__is_instance__?this:b;var c,d,a,e,f;b.power-=0.1;if(null===(e=-1==(0===(f=b.power)?0:"number"!=typeof f||"number"!=typeof f&&"string"!=typeof f&&"boolean"!=typeof f?$p.cmp(f,0):0==f?0:0>f?-1:1))||!1===e||0===e||""===e?0:"object"==typeof e?"function"==typeof e.__nonzero__?e.__nonzero__():"function"==typeof e.__len__?0<e.__len__():1:1)b.power=0;(null===
(d=!(null===(c=q.env.debug)||!1===c||0===c||""===c?0:"object"==typeof c?"function"==typeof c.__nonzero__?c.__nonzero__():"function"==typeof c.__len__?0<c.__len__():1:1))||!1===d||0===d||""===d?0:"object"==typeof d?"function"==typeof d.__nonzero__?d.__nonzero__():"function"==typeof d.__len__?0<d.__len__():1:1)&&("undefined"!=typeof(a=b.sound).__array?"undefined"!=typeof a.__array.shot?a.__array.shot:a.__getitem__("shot"):a.__getitem__("shot")).play();return null},1,[null,null,["self"]]);p.shot=l;l=
$pyjs__bind_method2("energy_surge",function(b,c){if(!0===this.__is_instance__)var d=this;else d=b,b=c;var a,e,f,g,h;d.power+=b;if(null===(f=1==(1===(h=d.power)?0:"number"!=typeof h||"number"!=typeof h&&"string"!=typeof h&&"boolean"!=typeof h?$p.cmp(h,1):1==h?0:1>h?-1:1))||!1===f||0===f||""===f?0:"object"==typeof f?"function"==typeof f.__nonzero__?f.__nonzero__():"function"==typeof f.__len__?0<f.__len__():1:1)d.power=1;(null===(a=!(null===(g=q.env.debug)||!1===g||0===g||""===g?0:"object"==typeof g?
"function"==typeof g.__nonzero__?g.__nonzero__():"function"==typeof g.__len__?0<g.__len__():1:1))||!1===a||0===a||""===a?0:"object"==typeof a?"function"==typeof a.__nonzero__?a.__nonzero__():"function"==typeof a.__len__?0<a.__len__():1:1)&&("undefined"!=typeof(e=d.sound).__array?"undefined"!=typeof e.__array.surge?e.__array.surge:e.__getitem__("surge"):e.__getitem__("surge")).play();return null},1,[null,null,["self"],["level"]]);p.energy_surge=l;l=$pyjs__bind_method2("energy_spike",function(b,c){if(!0===
this.__is_instance__)var d=this;else d=b,b=c;var a,e,f,g,h;d.power-=b;if(null===(a=-1==(0===(h=d.power)?0:"number"!=typeof h||"number"!=typeof h&&"string"!=typeof h&&"boolean"!=typeof h?$p.cmp(h,0):0==h?0:0>h?-1:1))||!1===a||0===a||""===a?0:"object"==typeof a?"function"==typeof a.__nonzero__?a.__nonzero__():"function"==typeof a.__len__?0<a.__len__():1:1)d.power=0;(null===(f=!(null===(e=q.env.debug)||!1===e||0===e||""===e?0:"object"==typeof e?"function"==typeof e.__nonzero__?e.__nonzero__():"function"==
typeof e.__len__?0<e.__len__():1:1))||!1===f||0===f||""===f?0:"object"==typeof f?"function"==typeof f.__nonzero__?f.__nonzero__():"function"==typeof f.__len__?0<f.__len__():1:1)&&("undefined"!=typeof(g=d.sound).__array?"undefined"!=typeof g.__array.spike?g.__array.spike:g.__getitem__("spike"):g.__getitem__("spike")).play();return null},1,[null,null,["self"],["level"]]);p.energy_spike=l;l=$pyjs__bind_method2("regenerate",function(b){b=!0===this.__is_instance__?this:b;var c,d,a,e;if(null===(c=-1==(1===
(e=b.power)?0:"number"!=typeof e||"number"!=typeof e&&"string"!=typeof e&&"boolean"!=typeof e?$p.cmp(e,1):1==e?0:1>e?-1:1))||!1===c||0===c||""===c?0:"object"==typeof c?"function"==typeof c.__nonzero__?c.__nonzero__():"function"==typeof c.__len__?0<c.__len__():1:1)b.power+=0.001;if(null===(d=-1==(1===(a=b.pulse_charge)?0:"number"!=typeof a||"number"!=typeof a&&"string"!=typeof a&&"boolean"!=typeof a?$p.cmp(a,1):1==a?0:1>a?-1:1))||!1===d||0===d||""===d?0:"object"==typeof d?"function"==typeof d.__nonzero__?
d.__nonzero__():"function"==typeof d.__len__?0<d.__len__():1:1)b.pulse_charge+=0.2;return null},1,[null,null,["self"]]);p.regenerate=l;l=$pyjs__bind_method2("node_repair",function(b){b=!0===this.__is_instance__?this:b;var c,d,a,e,f,g,h,l,k,p,n,y,u,s,r,z,v,w,H,J,E,D,x,G;if(null===(u=b.moving)||!1===u||0===u||""===u?0:"object"==typeof u?"function"==typeof u.__nonzero__?u.__nonzero__():"function"==typeof u.__len__?0<u.__len__():1:1)return null;if(null===(c=q.engine.key.get_mods()&q.engine.KMOD_SHIFT)||
!1===c||0===c||""===c?0:"object"==typeof c?"function"==typeof c.__nonzero__?c.__nonzero__():"function"==typeof c.__len__?0<c.__len__():1:1){E=$p.tuple(["u","d","l","r"]);"undefined"!=typeof(u=E.__array)?c=0:(E=E.__iter__(),c="undefined"!=typeof(u=E.__array)?0:"function"==typeof E.$genfunc?1:-1);for(G=0;J="undefined"!=typeof(s=c?0<c?E.next(!0,!1):$p.wrapped_next(E):u[G++]);)if(null===(h="undefined"!=typeof(g=b.controls).__array?"undefined"!=typeof g.__array[d=s]?g.__array[d]:g.__getitem__(d):g.__getitem__(s))||
!1===h||0===h||""===h?0:"object"==typeof h?"function"==typeof h.__nonzero__?h.__nonzero__():"function"==typeof h.__len__?0<h.__len__():1:1){y=b.matrix.node_offset_check(b,"undefined"!=typeof(a=b.dir_offset).__array?"undefined"!=typeof a.__array[e=s]?a.__array[e]:a.__getitem__(e):a.__getitem__(s));break}J||(y=b.matrix.node_offset_check(b,"undefined"!=typeof(f=b.dir_offset).__array?"undefined"!=typeof f.__array[l=b.pulse_aim]?f.__array[l]:f.__getitem__(l):f.__getitem__(b.pulse_aim)))}else y=b.matrix.node_check(b);
if(null===(p=(null===(D=w=y)||!1===D||0===D||""===D?0:"object"==typeof D?"function"==typeof D.__nonzero__?D.__nonzero__():"function"==typeof D.__len__?0<D.__len__():1:1)?y.offline:w)||!1===p||0===p||""===p?0:"object"==typeof p?"function"==typeof p.__nonzero__?p.__nonzero__():"function"==typeof p.__len__?0<p.__len__():1:1)if(null===(k=1==(0.3===(x=b.power)?0:"number"!=typeof x||"number"!=typeof x&&"string"!=typeof x&&"boolean"!=typeof x?$p.cmp(x,0.3):0.3==x?0:0.3>x?-1:1))||!1===k||0===k||""===k?0:
"object"==typeof k?"function"==typeof k.__nonzero__?k.__nonzero__():"function"==typeof k.__len__?0<k.__len__():1:1)y.repair(0.1),b.power-=0.01,(null===(n=!(null===(r=q.env.debug)||!1===r||0===r||""===r?0:"object"==typeof r?"function"==typeof r.__nonzero__?r.__nonzero__():"function"==typeof r.__len__?0<r.__len__():1:1))||!1===n||0===n||""===n?0:"object"==typeof n?"function"==typeof n.__nonzero__?n.__nonzero__():"function"==typeof n.__len__?0<n.__len__():1:1)&&(null===(z=!(null===(v=b.channel.get_busy())||
!1===v||0===v||""===v?0:"object"==typeof v?"function"==typeof v.__nonzero__?v.__nonzero__():"function"==typeof v.__len__?0<v.__len__():1:1))||!1===z||0===z||""===z?0:"object"==typeof z?"function"==typeof z.__nonzero__?z.__nonzero__():"function"==typeof z.__len__?0<z.__len__():1:1)&&b.channel.play("undefined"!=typeof(H=b.sound).__array?"undefined"!=typeof H.__array.repair?H.__array.repair:H.__getitem__("repair"):H.__getitem__("repair"));return null},1,[null,null,["self"]]);p.node_repair=l;l=$pyjs__bind_method2("destroyed",
function(b){b=!0===this.__is_instance__?this:b;b.matrix.avatar=null;b.kill();return null},1,[null,null,["self"]]);p.destroyed=l;l=$pyjs__bind_method2("update",function(b){b=!0===this.__is_instance__?this:b;var c,d,a,e,f;b.action();b.move();b.momentum();b.rect.x=$p.float_int(b.x)-Math.floor(("undefined"!=typeof(c=b.rect).__array?"undefined"!=typeof c.__array[2]?c.__array[2]:c.__getitem__(2):c.__getitem__(2))/2);b.rect.y=$p.float_int(b.y)-Math.floor(("undefined"!=typeof(d=b.rect).__array?"undefined"!=
typeof d.__array[3]?d.__array[3]:d.__getitem__(3):d.__getitem__(3))/2);if(null===(a=b.datum_collide())||!1===a||0===a||""===a?0:"object"==typeof a?"function"==typeof a.__nonzero__?a.__nonzero__():"function"==typeof a.__len__?0<a.__len__():1:1)if(b.power-=0.1,null===(e=-1==(0.01===(f=b.power)?0:"number"!=typeof f||"number"!=typeof f&&"string"!=typeof f&&"boolean"!=typeof f?$p.cmp(f,0.01):0.01==f?0:0.01>f?-1:1))||!1===e||0===e||""===e?0:"object"==typeof e?"function"==typeof e.__nonzero__?e.__nonzero__():
"function"==typeof e.__len__?0<e.__len__():1:1)b.power=0;b.regenerate();return null},1,[null,null,["self"]]);p.update=l;l=Array(q.engine.sprite.Sprite);var y=$p.dict(),H;for(H in p)y.__setitem__(H,p[H]);return $p._create_class("Avatar",$p.tuple(l),y)}();return this};
