$pyjs.loaded_modules.bot=function(v){if($pyjs.loaded_modules.bot.__was_initialized__)return $pyjs.loaded_modules.bot;var m=$pyjs.loaded_modules.bot;m.__repr__=function(){return"<module: bot>"};m.__was_initialized__=!0;if(null===v||"undefined"==typeof v)v="bot";m.__name__=v;m.random=$p.___import___("random",null);m.env=$p.___import___("env",null);m.engine=m.env.engine;m.Avatar=$p.___import___("avatar.Avatar",null,null,!1);m.Charge=$p.___import___("charge.Charge",null,null,!1);m.Bot=function(){var l=
{},k;l.__module__="bot";l.bot_image=!1;l.images=null;l.mask=null;k=$pyjs__bind_method2("__init__",function(b,a,c,f){if(!0===this.__is_instance__)var d=this;else d=b,b=a,a=c,c=f;var g,e,h,I,n;m.Avatar.__init__(d,b,a,c);if(null===(e=!(null===(n=d.bot_image)||!1===n||0===n||""===n?0:"object"==typeof n?"function"==typeof n.__nonzero__?n.__nonzero__():"function"==typeof n.__len__?0<n.__len__():1:1))||!1===e||0===e||""===e?0:"object"==typeof e?"function"==typeof e.__nonzero__?e.__nonzero__():"function"==
typeof e.__len__?0<e.__len__():1:1)b=m.engine.Surface($p.tuple([50,50]),m.engine.SRCALPHA),c=$p.tuple([100,80,120]),e=$p.tuple([200,80,100]),f=$p.tuple([200,50,50]),a=function(){var a,b,c,d,e,f,g,h;c=$p.list();d=$p.list([$p.tuple([12,0]),$p.tuple([16,10]),$p.tuple([24,13]),$p.tuple([16,18]),$p.tuple([12,24]),$p.tuple([8,18]),$p.tuple([0,13]),$p.tuple([8,10])]);"undefined"!=typeof(h=d.__array)?b=0:(d=d.__iter__(),b="undefined"!=typeof(h=d.__array)?0:"function"==typeof d.$genfunc?1:-1);for(e=0;"undefined"!=
typeof(a=b?0<b?d.next(!0,!1):$p.wrapped_next(d):h[e++]);)c.append($p.tuple([2*("undefined"!=typeof(f=a).__array?"undefined"!=typeof f.__array[0]?f.__array[0]:f.__getitem__(0):f.__getitem__(0)),2*("undefined"!=typeof(g=a).__array?"undefined"!=typeof g.__array[1]?g.__array[1]:g.__getitem__(1):g.__getitem__(1))]));return c}(),m.engine.draw.polygon(b,c,a,0),a=function(){var a,b,c,d,e,f,g,h;d=$p.list();c=$p.list([$p.tuple([16,11]),$p.tuple([23,13]),$p.tuple([16,17])]);"undefined"!=typeof(h=c.__array)?
b=0:(c=c.__iter__(),b="undefined"!=typeof(h=c.__array)?0:"function"==typeof c.$genfunc?1:-1);for(e=0;"undefined"!=typeof(a=b?0<b?c.next(!0,!1):$p.wrapped_next(c):h[e++]);)d.append($p.tuple([2*("undefined"!=typeof(g=a).__array?"undefined"!=typeof g.__array[0]?g.__array[0]:g.__getitem__(0):g.__getitem__(0)),2*("undefined"!=typeof(f=a).__array?"undefined"!=typeof f.__array[1]?f.__array[1]:f.__getitem__(1):f.__getitem__(1))]));return d}(),m.engine.draw.polygon(b,e,a,0),a=function(){var b,a,c,d,e,f,g,
h;e=$p.list();g=$p.list([$p.tuple([8,11]),$p.tuple([1,13]),$p.tuple([8,17])]);"undefined"!=typeof(h=g.__array)?d=0:(g=g.__iter__(),d="undefined"!=typeof(h=g.__array)?0:"function"==typeof g.$genfunc?1:-1);for(b=0;"undefined"!=typeof(c=d?0<d?g.next(!0,!1):$p.wrapped_next(g):h[b++]);)e.append($p.tuple([2*("undefined"!=typeof(f=c).__array?"undefined"!=typeof f.__array[0]?f.__array[0]:f.__getitem__(0):f.__getitem__(0)),2*("undefined"!=typeof(a=c).__array?"undefined"!=typeof a.__array[1]?a.__array[1]:a.__getitem__(1):
a.__getitem__(1))]));return e}(),m.engine.draw.polygon(b,e,a,0),a=function(){var a,b,c,d,e,f,g,h;d=$p.list();h=$p.list([$p.tuple([12,8]),$p.tuple([15,11]),$p.tuple([15,17]),$p.tuple([12,20]),$p.tuple([9,17]),$p.tuple([9,11])]);"undefined"!=typeof(g=h.__array)?f=0:(h=h.__iter__(),f="undefined"!=typeof(g=h.__array)?0:"function"==typeof h.$genfunc?1:-1);for(e=0;"undefined"!=typeof(c=f?0<f?h.next(!0,!1):$p.wrapped_next(h):g[e++]);)d.append($p.tuple([2*("undefined"!=typeof(b=c).__array?"undefined"!=typeof b.__array[0]?
b.__array[0]:b.__getitem__(0):b.__getitem__(0)),2*("undefined"!=typeof(a=c).__array?"undefined"!=typeof a.__array[1]?a.__array[1]:a.__getitem__(1):a.__getitem__(1))]));return d}(),m.engine.draw.polygon(b,f,a,0),b=m.engine.transform.flip(b,!0,!0),d.images.__setitem__("normal",b),d.mask=m.engine.mask.from_surface("undefined"!=typeof(h=d.images).__array?"undefined"!=typeof h.__array.normal?h.__array.normal:h.__getitem__("normal"):h.__getitem__("normal")),d.bot_image=b;d.image="undefined"!=typeof(I=d.images).__array?
"undefined"!=typeof I.__array.normal?I.__array.normal:I.__getitem__("normal"):I.__getitem__("normal");d.rect=$pyjs_kwargs_call(d.image,"get_rect",null,null,[{center:$p.tuple([$p.float_int(d.x),$p.float_int(d.y)])}]);d.targets=$p.list([d.matrix.avatars]);d.field=$p.dict([["u",50],["d",350],["l",50],["r",450]]);d.pulse_aim="d";d.nemesis=d.matrix.avatar;d.identity="Bot";d.motion.__setitem__("d",!0);d.moving=!0;d.behaviours=$p.dict([["roam",d.auto_move],["node_attack",d.node_damage],["target",d.target],
["evade",d.evade]]);d.behaviours_types=$p.list(d.behaviours.keys());d.behaviours_special=$p.dict([["move_reverse",d.move_reverse],["move_forward",d.move_forward],["inactive",d.offline],["stalk",d.stalk]]);d.behaviour="undefined"!=typeof(g=d.behaviours).__array?"undefined"!=typeof g.__array.roam?g.__array.roam:g.__getitem__("roam"):g.__getitem__("roam");d.behaviour_type="roam";return null},1,[null,null,["self"],["matrix"],["x"],["y"]]);l.__init__=k;k=$pyjs__bind_method2("behaviour_mode",function(b){b=
!0===this.__is_instance__?this:b;var a,c;b.behaviour="undefined"!=typeof(c=b.behaviours).__array?"undefined"!=typeof c.__array[a=m.random.choice(b.behaviours_types)]?c.__array[a]:c.__getitem__(a):c.__getitem__(m.random.choice(b.behaviours_types));return null},1,[null,null,["self"]]);l.behaviour_mode=k;k=$pyjs__bind_method2("action",function(b){return null},1,[null,null,["self"]]);l.action=k;k=$pyjs__bind_method2("shot",function(b){b=!0===this.__is_instance__?this:b;var a,c,f,d,g,e;m.Avatar.shot(b);
b.behaviour="undefined"!=typeof(f=b.behaviours).__array?"undefined"!=typeof f.__array.evade?f.__array.evade:f.__getitem__("evade"):f.__getitem__("evade");b.behaviour_type="evade";if(null===(c=1>(0===(a=b.power)?0:"number"!=typeof a||"number"!=typeof a&&"string"!=typeof a&&"boolean"!=typeof a?$p.cmp(a,0):0==a?0:0>a?-1:1))||!1===c||0===c||""===c?0:"object"==typeof c?"function"==typeof c.__nonzero__?c.__nonzero__():"function"==typeof c.__len__?0<c.__len__():1:1)(null===(e=!(null===(g=m.env.debug)||!1===
g||0===g||""===g?0:"object"==typeof g?"function"==typeof g.__nonzero__?g.__nonzero__():"function"==typeof g.__len__?0<g.__len__():1:1))||!1===e||0===e||""===e?0:"object"==typeof e?"function"==typeof e.__nonzero__?e.__nonzero__():"function"==typeof e.__len__?0<e.__len__():1:1)&&("undefined"!=typeof(d=b.sound).__array?"undefined"!=typeof d.__array.explode?d.__array.explode:d.__getitem__("explode"):d.__getitem__("explode")).play(),b.kill();return null},1,[null,null,["self"]]);l.shot=k;k=$pyjs__bind_method2("auto_move",
function(b){b=!0===this.__is_instance__?this:b;var a,c,f,d,g,e,h,I,n,k,p,r,q,l,t,s,w,x,y,B,C,z,D,u,E,G,da,H,J,K,L,S,Q,M,F,N,O,P,A,R;if(null===(J=!(null===(a=b.moving)||!1===a||0===a||""===a?0:"object"==typeof a?"function"==typeof a.__nonzero__?a.__nonzero__():"function"==typeof a.__len__?0<a.__len__():1:1))||!1===J||0===J||""===J?0:"object"==typeof J?"function"==typeof J.__nonzero__?J.__nonzero__():"function"==typeof J.__len__?0<J.__len__():1:1){for(a=!1;null===(L=!(null===(K=a)||!1===K||0===K||""===
K?0:"object"==typeof K?"function"==typeof K.__nonzero__?K.__nonzero__():"function"==typeof K.__len__?0<K.__len__():1:1))||!1===L||0===L||""===L?0:"object"==typeof L?"function"==typeof L.__nonzero__?L.__nonzero__():"function"==typeof L.__len__?0<L.__len__():1:1;)if(B=m.random.choice(b.matrix.directions),null===(A=(null===(k=z=(null===(f=E="l"===(G=B)&&null===G?!0:null===G?!1:"object"!=typeof G&&"function"!=typeof G||"function"!=typeof G.__cmp__?"l"==G:0===G.__cmp__("l"))||!1===f||0===f||""===f?0:"object"==
typeof f?"function"==typeof f.__nonzero__?f.__nonzero__():"function"==typeof f.__len__?0<f.__len__():1:1)?1==((F="undefined"!=typeof(q=b.node_position).__array?"undefined"!=typeof q.__array[0]?q.__array[0]:q.__getitem__(0):q.__getitem__(0))===(u="undefined"!=typeof(r=b.field).__array?"undefined"!=typeof r.__array.l?r.__array.l:r.__getitem__("l"):r.__getitem__("l"))?0:typeof F!=typeof u||"number"!=typeof F&&"string"!=typeof F&&"boolean"!=typeof F?$p.cmp(F,u):F==u?0:F<u?-1:1):E)||!1===k||0===k||""===
k?0:"object"==typeof k?"function"==typeof k.__nonzero__?k.__nonzero__():"function"==typeof k.__len__?0<k.__len__():1:1)?z:(null===(e=R=(null===(g=C="r"===(t=B)&&null===t?!0:null===t?!1:"object"!=typeof t&&"function"!=typeof t||"function"!=typeof t.__cmp__?"r"==t:0===t.__cmp__("r"))||!1===g||0===g||""===g?0:"object"==typeof g?"function"==typeof g.__nonzero__?g.__nonzero__():"function"==typeof g.__len__?0<g.__len__():1:1)?-1==((y="undefined"!=typeof(n=b.node_position).__array?"undefined"!=typeof n.__array[0]?
n.__array[0]:n.__getitem__(0):n.__getitem__(0))===(M="undefined"!=typeof(P=b.field).__array?"undefined"!=typeof P.__array.r?P.__array.r:P.__getitem__("r"):P.__getitem__("r"))?0:typeof y!=typeof M||"number"!=typeof y&&"string"!=typeof y&&"boolean"!=typeof y?$p.cmp(y,M):y==M?0:y<M?-1:1):C)||!1===e||0===e||""===e?0:"object"==typeof e?"function"==typeof e.__nonzero__?e.__nonzero__():"function"==typeof e.__len__?0<e.__len__():1:1)?R:(null===(h=D=(null===(d=da="u"===(H=B)&&null===H?!0:null===H?!1:"object"!=
typeof H&&"function"!=typeof H||"function"!=typeof H.__cmp__?"u"==H:0===H.__cmp__("u"))||!1===d||0===d||""===d?0:"object"==typeof d?"function"==typeof d.__nonzero__?d.__nonzero__():"function"==typeof d.__len__?0<d.__len__():1:1)?1==((Q="undefined"!=typeof(O=b.node_position).__array?"undefined"!=typeof O.__array[1]?O.__array[1]:O.__getitem__(1):O.__getitem__(1))===(p="undefined"!=typeof(N=b.field).__array?"undefined"!=typeof N.__array.u?N.__array.u:N.__getitem__("u"):N.__getitem__("u"))?0:typeof Q!=
typeof p||"number"!=typeof Q&&"string"!=typeof Q&&"boolean"!=typeof Q?$p.cmp(Q,p):Q==p?0:Q<p?-1:1):da)||!1===h||0===h||""===h?0:"object"==typeof h?"function"==typeof h.__nonzero__?h.__nonzero__():"function"==typeof h.__len__?0<h.__len__():1:1)?D:(null===(I=w="d"===(x=B)&&null===x?!0:null===x?!1:"object"!=typeof x&&"function"!=typeof x||"function"!=typeof x.__cmp__?"d"==x:0===x.__cmp__("d"))||!1===I||0===I||""===I?0:"object"==typeof I?"function"==typeof I.__nonzero__?I.__nonzero__():"function"==typeof I.__len__?
0<I.__len__():1:1)?-1==((c="undefined"!=typeof(S=b.node_position).__array?"undefined"!=typeof S.__array[1]?S.__array[1]:S.__getitem__(1):S.__getitem__(1))===(l="undefined"!=typeof(s=b.field).__array?"undefined"!=typeof s.__array.d?s.__array.d:s.__getitem__("d"):s.__getitem__("d"))?0:typeof c!=typeof l||"number"!=typeof c&&"string"!=typeof c&&"boolean"!=typeof c?$p.cmp(c,l):c==l?0:c<l?-1:1):w)||!1===A||0===A||""===A?0:"object"==typeof A?"function"==typeof A.__nonzero__?A.__nonzero__():"function"==
typeof A.__len__?0<A.__len__():1:1)a=!0;b.motion.__setitem__(B,!0);b.moving=!0}return null},1,[null,null,["self"]]);l.auto_move=k;k=$pyjs__bind_method2("momentum",function(b){b=!0===this.__is_instance__?this:b;var a,c,f,d,g,e,h;m.Avatar.momentum(b);if(null===(c=!(null===(a=b.moving)||!1===a||0===a||""===a?0:"object"==typeof a?"function"==typeof a.__nonzero__?a.__nonzero__():"function"==typeof a.__len__?0<a.__len__():1:1))||!1===c||0===c||""===c?0:"object"==typeof c?"function"==typeof c.__nonzero__?
c.__nonzero__():"function"==typeof c.__len__?0<c.__len__():1:1){if(null===(g="move_reverse"===(f=b.behaviour_type)&&null===f?!0:null===f?!1:"object"!=typeof f&&"function"!=typeof f||"function"!=typeof f.__cmp__?"move_reverse"==f:0===f.__cmp__("move_reverse"))||!1===g||0===g||""===g?0:"object"==typeof g?"function"==typeof g.__nonzero__?g.__nonzero__():"function"==typeof g.__len__?0<g.__len__():1:1)return null;(null===(e=!(null===(d=b.matrix.charge_check(b))||!1===d||0===d||""===d?0:"object"==typeof d?
"function"==typeof d.__nonzero__?d.__nonzero__():"function"==typeof d.__len__?0<d.__len__():1:1))||!1===e||0===e||""===e?0:"object"==typeof e?"function"==typeof e.__nonzero__?e.__nonzero__():"function"==typeof e.__len__?0<e.__len__():1:1)?(b.behaviour=null,b.behaviour_type=null):(b.behaviour="undefined"!=typeof(h=b.behaviours).__array?"undefined"!=typeof h.__array.roam?h.__array.roam:h.__getitem__("roam"):h.__getitem__("roam"),b.behaviour_type="roam")}return null},1,[null,null,["self"]]);l.momentum=
k;k=$pyjs__bind_method2("auto_shoot",function(b){b=!0===this.__is_instance__?this:b;var a,c;(null===(c=1==(0.95===(a=m.random.random())?0:"number"!=typeof a||"number"!=typeof a&&"string"!=typeof a&&"boolean"!=typeof a?$p.cmp(a,0.95):0.95==a?0:0.95>a?-1:1))||!1===c||0===c||""===c?0:"object"==typeof c?"function"==typeof c.__nonzero__?c.__nonzero__():"function"==typeof c.__len__?0<c.__len__():1:1)&&b.activate_pulse();return null},1,[null,null,["self"]]);l.auto_shoot=k;k=$pyjs__bind_method2("target",
function(b){b=!0===this.__is_instance__?this:b;var a,c,f,d,g,e,h,k,n,m,p,r,q,l,t,s,w,x,y,B,C,z,D,u,E;if(null===(k=!(null===(n=b.matrix.node_damage_check(b.nemesis))||!1===n||0===n||""===n?0:"object"==typeof n?"function"==typeof n.__nonzero__?n.__nonzero__():"function"==typeof n.__len__?0<n.__len__():1:1))||!1===k||0===k||""===k?0:"object"==typeof k?"function"==typeof k.__nonzero__?k.__nonzero__():"function"==typeof k.__len__?0<k.__len__():1:1)return b.behaviour=null,b.behaviour_type=null;if(null===
(m=!(null===(p=b.moving)||!1===p||0===p||""===p?0:"object"==typeof p?"function"==typeof p.__nonzero__?p.__nonzero__():"function"==typeof p.__len__?0<p.__len__():1:1))||!1===m||0===m||""===m?0:"object"==typeof m?"function"==typeof m.__nonzero__?m.__nonzero__():"function"==typeof m.__len__?0<m.__len__():1:1)if(null===(q=(d=b.x)===(g=b.nemesis.x)&&null===d?!0:null===d?!1:null===g?!1:"object"!=typeof d&&"function"!=typeof d||"function"!=typeof d.__cmp__?"object"!=typeof g&&"function"!=typeof g||"function"!=
typeof g.__cmp__?d==g:0===g.__cmp__(d):0===d.__cmp__(g))||!1===q||0===q||""===q?0:"object"==typeof q?"function"==typeof q.__nonzero__?q.__nonzero__():"function"==typeof q.__len__?0<q.__len__():1:1){if(null===(r=-1==((x=b.y)===(t=b.nemesis.y)?0:typeof x!=typeof t||"number"!=typeof x&&"string"!=typeof x&&"boolean"!=typeof x?$p.cmp(x,t):x==t?0:x<t?-1:1))||!1===r||0===r||""===r?0:"object"==typeof r?"function"==typeof r.__nonzero__?r.__nonzero__():"function"==typeof r.__len__?0<r.__len__():1:1)b.pulse_aim=
"d";else if(null===(D=1==((l=b.y)===(w=b.nemesis.y)?0:typeof l!=typeof w||"number"!=typeof l&&"string"!=typeof l&&"boolean"!=typeof l?$p.cmp(l,w):l==w?0:l<w?-1:1))||!1===D||0===D||""===D?0:"object"==typeof D?"function"==typeof D.__nonzero__?D.__nonzero__():"function"==typeof D.__len__?0<D.__len__():1:1)b.pulse_aim="u";b.activate_pulse()}else if(null===(u=(e=b.y)===(h=b.nemesis.y)&&null===e?!0:null===e?!1:null===h?!1:"object"!=typeof e&&"function"!=typeof e||"function"!=typeof e.__cmp__?"object"!=
typeof h&&"function"!=typeof h||"function"!=typeof h.__cmp__?e==h:0===h.__cmp__(e):0===e.__cmp__(h))||!1===u||0===u||""===u?0:"object"==typeof u?"function"==typeof u.__nonzero__?u.__nonzero__():"function"==typeof u.__len__?0<u.__len__():1:1){if(null===(C=1==((s=b.x)===(B=b.nemesis.x)?0:typeof s!=typeof B||"number"!=typeof s&&"string"!=typeof s&&"boolean"!=typeof s?$p.cmp(s,B):s==B?0:s<B?-1:1))||!1===C||0===C||""===C?0:"object"==typeof C?"function"==typeof C.__nonzero__?C.__nonzero__():"function"==
typeof C.__len__?0<C.__len__():1:1)b.pulse_aim="l";else if(null===(z=-1==((y=b.x)===(a=b.nemesis.x)?0:typeof y!=typeof a||"number"!=typeof y&&"string"!=typeof y&&"boolean"!=typeof y?$p.cmp(y,a):y==a?0:y<a?-1:1))||!1===z||0===z||""===z?0:"object"==typeof z?"function"==typeof z.__nonzero__?z.__nonzero__():"function"==typeof z.__len__?0<z.__len__():1:1)b.pulse_aim="r";b.activate_pulse()}else a=(null===(E=1==((c=b.x)===(f=b.nemesis.x)?0:typeof c!=typeof f||"number"!=typeof c&&"string"!=typeof c&&"boolean"!=
typeof c?$p.cmp(c,f):c==f?0:c<f?-1:1))||!1===E||0===E||""===E?0:"object"==typeof E?"function"==typeof E.__nonzero__?E.__nonzero__():"function"==typeof E.__len__?0<E.__len__():1:1)?"l":"r",b.motion.__setitem__(a,!0),b.moving=!0;return null},1,[null,null,["self"]]);l.target=k;k=$pyjs__bind_method2("stalk",function(b){b=!0===this.__is_instance__?this:b;var a,c,f,d,g,e,h,k;if(null===(e=b.moving)||!1===e||0===e||""===e?0:"object"==typeof e?"function"==typeof e.__nonzero__?e.__nonzero__():"function"==typeof e.__len__?
0<e.__len__():1:1)return null;e=$p.list([]);(null===(h=1==((a=b.x)===(c=b.nemesis.x)?0:typeof a!=typeof c||"number"!=typeof a&&"string"!=typeof a&&"boolean"!=typeof a?$p.cmp(a,c):a==c?0:a<c?-1:1))||!1===h||0===h||""===h?0:"object"==typeof h?"function"==typeof h.__nonzero__?h.__nonzero__():"function"==typeof h.__len__?0<h.__len__():1:1)?e.append("l"):e.append("r");(null===(k=1==((f=b.y)===(d=b.nemesis.y)?0:typeof f!=typeof d||"number"!=typeof f&&"string"!=typeof f&&"boolean"!=typeof f?$p.cmp(f,d):
f==d?0:f<d?-1:1))||!1===k||0===k||""===k?0:"object"==typeof k?"function"==typeof k.__nonzero__?k.__nonzero__():"function"==typeof k.__len__?0<k.__len__():1:1)?e.append("u"):e.append("d");a=(null===e||!1===e||0===e||""===e?0:"object"==typeof e?"function"==typeof e.__nonzero__?e.__nonzero__():"function"==typeof e.__len__?0<e.__len__():1:1)?m.random.choice(e):null;(null===(g=!(null===a||!1===a||0===a||""===a?0:"object"==typeof a?"function"==typeof a.__nonzero__?a.__nonzero__():"function"==typeof a.__len__?
0<a.__len__():1:1))||!1===g||0===g||""===g?0:"object"==typeof g?"function"==typeof g.__nonzero__?g.__nonzero__():"function"==typeof g.__len__?0<g.__len__():1:1)?(b.behaviour=null,b.behaviour_type=null):(b.motion.__setitem__(a,!0),b.moving=!0);return a},1,[null,null,["self"]]);l.stalk=k;k=$pyjs__bind_method2("evade",function(b){b=!0===this.__is_instance__?this:b;var a,c,f,d,g,e,h,k,n,l,p,r,q,ca,t,s,w,x,y,B,C,z,D,u,E,G,da,H,J,K,L,S,Q,M,F,N,O,P,A,R,T,v,ga,ha,U,V,W,X,Y,Z,$,ea,aa,fa,ba,ia;if(null===(R=
b.moving)||!1===R||0===R||""===R?0:"object"==typeof R?"function"==typeof R.__nonzero__?R.__nonzero__():"function"==typeof R.__len__?0<R.__len__():1:1)return null;if(null===(A=1==(100===(a=b.matrix.separation(b,b.nemesis))?0:"number"!=typeof a||"number"!=typeof a&&"string"!=typeof a&&"boolean"!=typeof a?$p.cmp(a,100):100==a?0:100>a?-1:1))||!1===A||0===A||""===A?0:"object"==typeof A?"function"==typeof A.__nonzero__?A.__nonzero__():"function"==typeof A.__len__?0<A.__len__():1:1)return b.behaviour=null,
b.behaviour_type=null;a=$p.list([]);if(null===(P=(aa=b.x)===(fa=b.nemesis.x)&&null===aa?!0:null===aa?!1:null===fa?!1:"object"!=typeof aa&&"function"!=typeof aa||"function"!=typeof aa.__cmp__?"object"!=typeof fa&&"function"!=typeof fa||"function"!=typeof fa.__cmp__?aa==fa:0===fa.__cmp__(aa):0===aa.__cmp__(fa))||!1===P||0===P||""===P?0:"object"==typeof P?"function"==typeof P.__nonzero__?P.__nonzero__():"function"==typeof P.__len__?0<P.__len__():1:1)(null===(O=1==((c="undefined"!=typeof(d=b.node_position).__array?
"undefined"!=typeof d.__array[0]?d.__array[0]:d.__getitem__(0):d.__getitem__(0))===(ca="undefined"!=typeof(f=b.field).__array?"undefined"!=typeof f.__array.l?f.__array.l:f.__getitem__("l"):f.__getitem__("l"))?0:typeof c!=typeof ca||"number"!=typeof c&&"string"!=typeof c&&"boolean"!=typeof c?$p.cmp(c,ca):c==ca?0:c<ca?-1:1))||!1===O||0===O||""===O?0:"object"==typeof O?"function"==typeof O.__nonzero__?O.__nonzero__():"function"==typeof O.__len__?0<O.__len__():1:1)?a.append("l"):a.append("r"),(null===
(N=-1==((q="undefined"!=typeof(s=b.node_position).__array?"undefined"!=typeof s.__array[0]?s.__array[0]:s.__getitem__(0):s.__getitem__(0))===(r="undefined"!=typeof(w=b.field).__array?"undefined"!=typeof w.__array.r?w.__array.r:w.__getitem__("r"):w.__getitem__("r"))?0:typeof q!=typeof r||"number"!=typeof q&&"string"!=typeof q&&"boolean"!=typeof q?$p.cmp(q,r):q==r?0:q<r?-1:1))||!1===N||0===N||""===N?0:"object"==typeof N?"function"==typeof N.__nonzero__?N.__nonzero__():"function"==typeof N.__len__?0<
N.__len__():1:1)?a.append("r"):a.append("l");else if(null===(F=(ba=b.y)===(ea=b.nemesis.y)&&null===ba?!0:null===ba?!1:null===ea?!1:"object"!=typeof ba&&"function"!=typeof ba||"function"!=typeof ba.__cmp__?"object"!=typeof ea&&"function"!=typeof ea||"function"!=typeof ea.__cmp__?ba==ea:0===ea.__cmp__(ba):0===ba.__cmp__(ea))||!1===F||0===F||""===F?0:"object"==typeof F?"function"==typeof F.__nonzero__?F.__nonzero__():"function"==typeof F.__len__?0<F.__len__():1:1)(null===(M=1==((p="undefined"!=typeof(x=
b.node_position).__array?"undefined"!=typeof x.__array[1]?x.__array[1]:x.__getitem__(1):x.__getitem__(1))===(l="undefined"!=typeof(y=b.field).__array?"undefined"!=typeof y.__array.u?y.__array.u:y.__getitem__("u"):y.__getitem__("u"))?0:typeof p!=typeof l||"number"!=typeof p&&"string"!=typeof p&&"boolean"!=typeof p?$p.cmp(p,l):p==l?0:p<l?-1:1))||!1===M||0===M||""===M?0:"object"==typeof M?"function"==typeof M.__nonzero__?M.__nonzero__():"function"==typeof M.__len__?0<M.__len__():1:1)?a.append("u"):a.append("d"),
(null===(T=-1==((n="undefined"!=typeof(t=b.node_position).__array?"undefined"!=typeof t.__array[1]?t.__array[1]:t.__getitem__(1):t.__getitem__(1))===(k="undefined"!=typeof(S=b.field).__array?"undefined"!=typeof S.__array.d?S.__array.d:S.__getitem__("d"):S.__getitem__("d"))?0:typeof n!=typeof k||"number"!=typeof n&&"string"!=typeof n&&"boolean"!=typeof n?$p.cmp(n,k):n==k?0:n<k?-1:1))||!1===T||0===T||""===T?0:"object"==typeof T?"function"==typeof T.__nonzero__?T.__nonzero__():"function"==typeof T.__len__?
0<T.__len__():1:1)?a.append("d"):a.append("u");if(null===a||!1===a||0===a||""===a?0:"object"==typeof a?"function"==typeof a.__nonzero__?a.__nonzero__():"function"==typeof a.__len__?0<a.__len__():1:1)return c=m.random.choice(a),b.motion.__setitem__(c,!0),b.moving=!0,c;(null===(X=1==((h=b.x)===(e=b.nemesis.x)?0:typeof h!=typeof e||"number"!=typeof h&&"string"!=typeof h&&"boolean"!=typeof h?$p.cmp(h,e):h==e?0:h<e?-1:1))||!1===X||0===X||""===X?0:"object"==typeof X?"function"==typeof X.__nonzero__?X.__nonzero__():
"function"==typeof X.__len__?0<X.__len__():1:1)?(null===(Y=-1==((g="undefined"!=typeof(Q=b.node_position).__array?"undefined"!=typeof Q.__array[0]?Q.__array[0]:Q.__getitem__(0):Q.__getitem__(0))===(D="undefined"!=typeof(K=b.field).__array?"undefined"!=typeof K.__array.r?K.__array.r:K.__getitem__("r"):K.__getitem__("r"))?0:typeof g!=typeof D||"number"!=typeof g&&"string"!=typeof g&&"boolean"!=typeof g?$p.cmp(g,D):g==D?0:g<D?-1:1))||!1===Y||0===Y||""===Y?0:"object"==typeof Y?"function"==typeof Y.__nonzero__?
Y.__nonzero__():"function"==typeof Y.__len__?0<Y.__len__():1:1)?a.append("r"):a.append("l"):(null===(Z=1==((u="undefined"!=typeof(L=b.node_position).__array?"undefined"!=typeof L.__array[0]?L.__array[0]:L.__getitem__(0):L.__getitem__(0))===(C="undefined"!=typeof(J=b.field).__array?"undefined"!=typeof J.__array.l?J.__array.l:J.__getitem__("l"):J.__getitem__("l"))?0:typeof u!=typeof C||"number"!=typeof u&&"string"!=typeof u&&"boolean"!=typeof u?$p.cmp(u,C):u==C?0:u<C?-1:1))||!1===Z||0===Z||""===Z?0:
"object"==typeof Z?"function"==typeof Z.__nonzero__?Z.__nonzero__():"function"==typeof Z.__len__?0<Z.__len__():1:1)?a.append("l"):a.append("r");(null===($=1==((z=b.y)===(da=b.nemesis.y)?0:typeof z!=typeof da||"number"!=typeof z&&"string"!=typeof z&&"boolean"!=typeof z?$p.cmp(z,da):z==da?0:z<da?-1:1))||!1===$||0===$||""===$?0:"object"==typeof $?"function"==typeof $.__nonzero__?$.__nonzero__():"function"==typeof $.__len__?0<$.__len__():1:1)?(null===(U=-1==((H="undefined"!=typeof(ga=b.node_position).__array?
"undefined"!=typeof ga.__array[1]?ga.__array[1]:ga.__getitem__(1):ga.__getitem__(1))===(E="undefined"!=typeof(v=b.field).__array?"undefined"!=typeof v.__array.d?v.__array.d:v.__getitem__("d"):v.__getitem__("d"))?0:typeof H!=typeof E||"number"!=typeof H&&"string"!=typeof H&&"boolean"!=typeof H?$p.cmp(H,E):H==E?0:H<E?-1:1))||!1===U||0===U||""===U?0:"object"==typeof U?"function"==typeof U.__nonzero__?U.__nonzero__():"function"==typeof U.__len__?0<U.__len__():1:1)?a.append("d"):a.append("u"):(null===
(V=1==((G="undefined"!=typeof(ia=b.node_position).__array?"undefined"!=typeof ia.__array[1]?ia.__array[1]:ia.__getitem__(1):ia.__getitem__(1))===(B="undefined"!=typeof(ha=b.field).__array?"undefined"!=typeof ha.__array.u?ha.__array.u:ha.__getitem__("u"):ha.__getitem__("u"))?0:typeof G!=typeof B||"number"!=typeof G&&"string"!=typeof G&&"boolean"!=typeof G?$p.cmp(G,B):G==B?0:G<B?-1:1))||!1===V||0===V||""===V?0:"object"==typeof V?"function"==typeof V.__nonzero__?V.__nonzero__():"function"==typeof V.__len__?
0<V.__len__():1:1)?a.append("u"):a.append("d");c=(null===a||!1===a||0===a||""===a?0:"object"==typeof a?"function"==typeof a.__nonzero__?a.__nonzero__():"function"==typeof a.__len__?0<a.__len__():1:1)?m.random.choice(a):null;if(null===(W=c)||!1===W||0===W||""===W?0:"object"==typeof W?"function"==typeof W.__nonzero__?W.__nonzero__():"function"==typeof W.__len__?0<W.__len__():1:1)b.motion.__setitem__(c,!0),b.moving=!0;return c},1,[null,null,["self"]]);l.evade=k;k=$pyjs__bind_method2("move_destination",
function(b,a){return null},1,[null,null,["self"],["position"]]);l.move_destination=k;k=$pyjs__bind_method2("move_forward",function(b){b=!0===this.__is_instance__?this:b;var a,c,f,d,g,e;if(null===(d=!(null===(f=b.moving)||!1===f||0===f||""===f?0:"object"==typeof f?"function"==typeof f.__nonzero__?f.__nonzero__():"function"==typeof f.__len__?0<f.__len__():1:1))||!1===d||0===d||""===d?0:"object"==typeof d?"function"==typeof d.__nonzero__?d.__nonzero__():"function"==typeof d.__len__?0<d.__len__():1:1)(null===
(a=1==((g=b.y)===(e="undefined"!=typeof(c=b.field).__array?"undefined"!=typeof c.__array.u?c.__array.u:c.__getitem__("u"):c.__getitem__("u"))?0:typeof g!=typeof e||"number"!=typeof g&&"string"!=typeof g&&"boolean"!=typeof g?$p.cmp(g,e):g==e?0:g<e?-1:1))||!1===a||0===a||""===a?0:"object"==typeof a?"function"==typeof a.__nonzero__?a.__nonzero__():"function"==typeof a.__len__?0<a.__len__():1:1)?(b.behaviour=null,b.behaviour_type=null):(b.motion.__setitem__("d",!0),b.moving=!0);return null},1,[null,null,
["self"]]);l.move_forward=k;k=$pyjs__bind_method2("move_reverse",function(b){b=!0===this.__is_instance__?this:b;var a,c,f,d,g,e,h;if(null===(f=!(null===(a=b.moving)||!1===a||0===a||""===a?0:"object"==typeof a?"function"==typeof a.__nonzero__?a.__nonzero__():"function"==typeof a.__len__?0<a.__len__():1:1))||!1===f||0===f||""===f?0:"object"==typeof f?"function"==typeof f.__nonzero__?f.__nonzero__():"function"==typeof f.__len__?0<f.__len__():1:1)b.field.__setitem__("u",-1E3),(null===(c=-1==((e=b.y)===
(h="undefined"!=typeof(g=b.field).__array?"undefined"!=typeof g.__array.u?g.__array.u:g.__getitem__("u"):g.__getitem__("u"))?0:typeof e!=typeof h||"number"!=typeof e&&"string"!=typeof e&&"boolean"!=typeof e?$p.cmp(e,h):e==h?0:e<h?-1:1))||!1===c||0===c||""===c?0:"object"==typeof c?"function"==typeof c.__nonzero__?c.__nonzero__():"function"==typeof c.__len__?0<c.__len__():1:1)?(b.behaviour="undefined"!=typeof(d=b.behaviours_special).__array?"undefined"!=typeof d.__array.inactive?d.__array.inactive:
d.__getitem__("inactive"):d.__getitem__("inactive"),b.behaviour_type="inactive"):(b.motion.__setitem__("u",!0),b.moving=!0);return null},1,[null,null,["self"]]);l.move_reverse=k;k=$pyjs__bind_method2("offline",function(b){b=!0===this.__is_instance__?this:b;var a,c,f;if(null===(a=1==(0.3===(f=b.power)?0:"number"!=typeof f||"number"!=typeof f&&"string"!=typeof f&&"boolean"!=typeof f?$p.cmp(f,0.3):0.3==f?0:0.3>f?-1:1))||!1===a||0===a||""===a?0:"object"==typeof a?"function"==typeof a.__nonzero__?a.__nonzero__():
"function"==typeof a.__len__?0<a.__len__():1:1)b.behaviour="undefined"!=typeof(c=b.behaviours_special).__array?"undefined"!=typeof c.__array.move_forward?c.__array.move_forward:c.__getitem__("move_forward"):c.__getitem__("move_forward"),b.behaviour_type="move_forward";return null},1,[null,null,["self"]]);l.offline=k;k=$pyjs__bind_method2("retreat",function(b){b=!0===this.__is_instance__?this:b;var a;b.behaviour="undefined"!=typeof(a=b.behaviours_special).__array?"undefined"!=typeof a.__array.move_reverse?
a.__array.move_reverse:a.__getitem__("move_reverse"):a.__getitem__("move_reverse");b.behaviour_type="move_reverse";return null},1,[null,null,["self"]]);l.retreat=k;k=$pyjs__bind_method2("node_damage",function(b){if(!0===this.__is_instance__)var a=this;else a=arguments[0],b=arguments[1];"undefined"==typeof b&&(b=arguments.callee.__args__[3][1]);var c,f,d,g,e,h,k,l,v,p,r,q,ca,t,s,w;if(null===(p=(null===(l=k=-1==(0.2===(s=a.power)?0:"number"!=typeof s||"number"!=typeof s&&"string"!=typeof s&&"boolean"!=
typeof s?$p.cmp(s,0.2):0.2==s?0:0.2>s?-1:1))||!1===l||0===l||""===l?0:"object"==typeof l?"function"==typeof l.__nonzero__?l.__nonzero__():"function"==typeof l.__len__?0<l.__len__():1:1)?k:1==(0.1===(w=m.random.random())?0:"number"!=typeof w||"number"!=typeof w&&"string"!=typeof w&&"boolean"!=typeof w?$p.cmp(w,0.1):0.1==w?0:0.1>w?-1:1))||!1===p||0===p||""===p?0:"object"==typeof p?"function"==typeof p.__nonzero__?p.__nonzero__():"function"==typeof p.__len__?0<p.__len__():1:1)return a.behaviour=null,
a.behaviour_type=null;if(null===(q=!(null===(v=b)||!1===v||0===v||""===v?0:"object"==typeof v?"function"==typeof v.__nonzero__?v.__nonzero__():"function"==typeof v.__len__?0<v.__len__():1:1))||!1===q||0===q||""===q?0:"object"==typeof q?"function"==typeof q.__nonzero__?q.__nonzero__():"function"==typeof q.__len__?0<q.__len__():1:1){if(c=a.matrix.node_check(a),null===(d=(null===c||!1===c||0===c||""===c?0:"object"==typeof c?"function"==typeof c.__nonzero__?c.__nonzero__():"function"==typeof c.__len__?
0<c.__len__():1:1)?(null===(g=ca=!(null===(r=c.offline)||!1===r||0===r||""===r?0:"object"==typeof r?"function"==typeof r.__nonzero__?r.__nonzero__():"function"==typeof r.__len__?0<r.__len__():1:1))||!1===g||0===g||""===g?0:"object"==typeof g?"function"==typeof g.__nonzero__?g.__nonzero__():"function"==typeof g.__len__?0<g.__len__():1:1)?!(1===(e="undefined"!=typeof(h=c.id).__array?"undefined"!=typeof h.__array[1]?h.__array[1]:h.__getitem__(1):h.__getitem__(1))&&null===e||(null===e?0:"object"!=typeof e&&
"function"!=typeof e||"function"!=typeof e.__cmp__?1==e:0===e.__cmp__(1))):ca:c)||!1===d||0===d||""===d?0:"object"==typeof d?"function"==typeof d.__nonzero__?d.__nonzero__():"function"==typeof d.__len__?0<d.__len__():1:1)d=m.Charge(a.matrix,a.x,a.y,90),a.matrix.charges.add(d)}else d=m.Charge(a.matrix,"undefined"!=typeof(c=b).__array?"undefined"!=typeof c.__array[0]?c.__array[0]:c.__getitem__(0):c.__getitem__(0),"undefined"!=typeof(t=b).__array?"undefined"!=typeof t.__array[1]?t.__array[1]:t.__getitem__(1):
t.__getitem__(1),90),a.matrix.charges.add(d);a.behaviour="undefined"!=typeof(f=a.behaviours).__array?"undefined"!=typeof f.__array.roam?f.__array.roam:f.__getitem__("roam"):f.__getitem__("roam");a.behaviour_type="roam";return null},1,[null,null,["self"],["position",null]]);l.node_damage=k;k=$pyjs__bind_method2("update",function(b){b=!0===this.__is_instance__?this:b;var a,c,f;(null===(f=!(null===(c=b.behaviour)||!1===c||0===c||""===c?0:"object"==typeof c?"function"==typeof c.__nonzero__?c.__nonzero__():
"function"==typeof c.__len__?0<c.__len__():1:1))||!1===f||0===f||""===f?0:"object"==typeof f?"function"==typeof f.__nonzero__?f.__nonzero__():"function"==typeof f.__len__?0<f.__len__():1:1)&&b.behaviour_mode();(null===(a=b.behaviour)||!1===a||0===a||""===a?0:"object"==typeof a?"function"==typeof a.__nonzero__?a.__nonzero__():"function"==typeof a.__len__?0<a.__len__():1:1)&&b.behaviour();m.Avatar.update(b);return null},1,[null,null,["self"]]);l.update=k;k=Array(m.Avatar);var v=$p.dict(),ja;for(ja in l)v.__setitem__(ja,
l[ja]);return $p._create_class("Bot",$p.tuple(k),v)}();return this};
