$pyjs.loaded_modules.charge=function(n){if($pyjs.loaded_modules.charge.__was_initialized__)return $pyjs.loaded_modules.charge;var d=$pyjs.loaded_modules.charge;d.__repr__=function(){return"<module: charge>"};d.__was_initialized__=!0;if(null===n||"undefined"==typeof n)n="charge";d.__name__=n;d.env=$p.___import___("env",null);d.engine=d.env.engine;d.load_sound=$p.___import___("util.load_sound",null,null,!1);d.Charge=function(){var k={},m;k.__module__="charge";k.images=null;k.radius=null;k.sound=null;
m=$pyjs__bind_method2("__init__",function(a,c,f,l,s){if(!0===this.__is_instance__)var b=this;else b=a,a=c,c=f,f=l,l=s;var h,g,e,k,m,n,q,r,p;d.engine.sprite.Sprite.__init__(b);b.matrix=a;b.x=$p.float_int(c);b.y=$p.float_int(f);if(null===(m=!(null===(p=b.images)||!1===p||0===p||""===p?0:"object"==typeof p?"function"==typeof p.__nonzero__?p.__nonzero__():"function"==typeof p.__len__?0<p.__len__():1:1))||!1===m||0===m||""===m?0:"object"==typeof m?"function"==typeof m.__nonzero__?m.__nonzero__():"function"==
typeof m.__len__?0<m.__len__():1:1)b.images=$p.dict([]),f=$p.tuple([100,0,0]),s=$p.tuple([200,0,0]),c=$p.tuple([50,50,50]),a=d.engine.Surface($p.tuple([22,22]),d.engine.SRCALPHA),h=function(){var a,b,f,c,d,h,g,e;f=$p.list();c=$p.list([$p.tuple([5,0]),$p.tuple([10,2]),$p.tuple([10,8]),$p.tuple([5,10]),$p.tuple([0,8]),$p.tuple([0,2])]);"undefined"!=typeof(e=c.__array)?b=0:(c=c.__iter__(),b="undefined"!=typeof(e=c.__array)?0:"function"==typeof c.$genfunc?1:-1);for(d=0;"undefined"!=typeof(a=b?0<b?c.next(!0,
!1):$p.wrapped_next(c):e[d++]);)f.append($p.tuple([2*("undefined"!=typeof(h=a).__array?"undefined"!=typeof h.__array[0]?h.__array[0]:h.__getitem__(0):h.__getitem__(0)),2*("undefined"!=typeof(g=a).__array?"undefined"!=typeof g.__array[1]?g.__array[1]:g.__getitem__(1):g.__getitem__(1))]));return f}(),d.engine.draw.polygon(a,f,h,0),d.engine.draw.polygon(a,f,h,1),b.images.__setitem__("normal",a),a=d.engine.Surface($p.tuple([22,22]),d.engine.SRCALPHA),h=function(){var a,b,c,f,h,g,d,e;f=$p.list();c=$p.list([$p.tuple([5,
1]),$p.tuple([9,3]),$p.tuple([9,7]),$p.tuple([5,9]),$p.tuple([0,7]),$p.tuple([0,3])]);"undefined"!=typeof(e=c.__array)?b=0:(c=c.__iter__(),b="undefined"!=typeof(e=c.__array)?0:"function"==typeof c.$genfunc?1:-1);for(h=0;"undefined"!=typeof(a=b?0<b?c.next(!0,!1):$p.wrapped_next(c):e[h++]);)f.append($p.tuple([2*("undefined"!=typeof(d=a).__array?"undefined"!=typeof d.__array[0]?d.__array[0]:d.__getitem__(0):d.__getitem__(0)),2*("undefined"!=typeof(g=a).__array?"undefined"!=typeof g.__array[1]?g.__array[1]:
g.__getitem__(1):g.__getitem__(1))]));return f}(),d.engine.draw.polygon(a,s,h,0),d.engine.draw.polygon(a,s,h,1),f=function(){var a,b,c,f,g,d,e,l;g=$p.list();e=$p.range(0,null===(a=h)?0:"undefined"!=typeof a.__array?a.__array.length:"function"==typeof a.__len__?a.__len__():"undefined"!=typeof a.length?a.length:$p.len(a),2);"undefined"!=typeof(l=e.__array)?f=0:(e=e.__iter__(),f="undefined"!=typeof(l=e.__array)?0:"function"==typeof e.$genfunc?1:-1);for(a=0;"undefined"!=typeof(c=f?0<f?e.next(!0,!1):$p.wrapped_next(e):
l[a++]);)g.append("undefined"!=typeof(d=h).__array?"undefined"!=typeof d.__array[b=c]?d.__array[b]:d.__getitem__(b):d.__getitem__(c));return g}(),d.engine.draw.polygon(a,c,f,1),f=function(){var a,b,c,f,e,d,g,l;f=$p.list();l=$p.range(1,null===(e=h)?0:"undefined"!=typeof e.__array?e.__array.length:"function"==typeof e.__len__?e.__len__():"undefined"!=typeof e.length?e.length:$p.len(e),2);"undefined"!=typeof(g=l.__array)?d=0:(l=l.__iter__(),d="undefined"!=typeof(g=l.__array)?0:"function"==typeof l.$genfunc?
1:-1);for(e=0;"undefined"!=typeof(c=d?0<d?l.next(!0,!1):$p.wrapped_next(l):g[e++]);)f.append("undefined"!=typeof(a=h).__array?"undefined"!=typeof a.__array[b=c]?a.__array[b]:a.__getitem__(b):a.__getitem__(c));return f}(),d.engine.draw.polygon(a,c,f,1),d.engine.draw.line(a,c,"undefined"!=typeof(q=h).__array?"undefined"!=typeof q.__array[0]?q.__array[0]:q.__getitem__(0):q.__getitem__(0),"undefined"!=typeof(g=h).__array?"undefined"!=typeof g.__array[3]?g.__array[3]:g.__getitem__(3):g.__getitem__(3),
1),d.engine.draw.line(a,c,$p.tuple([18,10]),$p.tuple([0,10]),1),b.images.__setitem__("blink",a),b.radius=Math.floor(a.get_width()/2),b.sound=$p.dict([]),b.sound.__setitem__("explode",d.load_sound("explode.wav")),("undefined"!=typeof(n=b.sound).__array?"undefined"!=typeof n.__array.explode?n.__array.explode:n.__getitem__("explode"):n.__getitem__("explode")).set_volume(0.15);b.image="undefined"!=typeof(r=b.images).__array?"undefined"!=typeof r.__array.normal?r.__array.normal:r.__getitem__("normal"):
r.__getitem__("normal");b.current_image="normal";b.rect=$pyjs_kwargs_call(b.image,"get_rect",null,null,[{center:$p.tuple([b.x,b.y])}]);b.image_timer=2;b.timer=l;(null===(k=!(null===(e=b.matrix.adjust)||!1===e||0===e||""===e?0:"object"==typeof e?"function"==typeof e.__nonzero__?e.__nonzero__():"function"==typeof e.__len__?0<e.__len__():1:1))||!1===k||0===k||""===k?0:"object"==typeof k?"function"==typeof k.__nonzero__?k.__nonzero__():"function"==typeof k.__len__?0<k.__len__():1:1)?b.tick_value=1:b.tick_value=
2;b.node_attached=null;b.level=1;return null},1,[null,null,["self"],["matrix"],["x"],["y"],["time"]]);k.__init__=m;m=$pyjs__bind_method2("tick",function(a){a=!0===this.__is_instance__?this:a;var c,f;a.timer-=a.tick_value;return(null===(f=1==((0===(c=a.timer)?0:"number"!=typeof c||"number"!=typeof c&&"string"!=typeof c&&"boolean"!=typeof c?$p.cmp(c,0):0==c?0:0>c?-1:1)|1))||!1===f||0===f||""===f?0:"object"==typeof f?"function"==typeof f.__nonzero__?f.__nonzero__():"function"==typeof f.__len__?0<f.__len__():
1:1)?!0:!1},1,[null,null,["self"]]);k.tick=m;m=$pyjs__bind_method2("detonate",function(a){a=!0===this.__is_instance__?this:a;var c,f,l,k,b,h,g,e;l=d.engine.sprite.spritecollide(a,a.matrix.network,!1,d.engine.sprite.collide_circle);"undefined"!=typeof(h=l.__array)?k=0:(l=l.__iter__(),k="undefined"!=typeof(h=l.__array)?0:"function"==typeof l.$genfunc?1:-1);for(f=0;"undefined"!=typeof(c=k?0<k?l.next(!0,!1):$p.wrapped_next(l):h[f++]);)c.damage(a.level);(null===(e=!(null===(g=d.env.debug)||!1===g||0===
g||""===g?0:"object"==typeof g?"function"==typeof g.__nonzero__?g.__nonzero__():"function"==typeof g.__len__?0<g.__len__():1:1))||!1===e||0===e||""===e?0:"object"==typeof e?"function"==typeof e.__nonzero__?e.__nonzero__():"function"==typeof e.__len__?0<e.__len__():1:1)&&("undefined"!=typeof(b=a.sound).__array?"undefined"!=typeof b.__array.explode?b.__array.explode:b.__getitem__("explode"):b.__getitem__("explode")).play();a.kill();return null},1,[null,null,["self"]]);k.detonate=m;m=$pyjs__bind_method2("update",
function(a){a=!0===this.__is_instance__?this:a;var c,f,d,k,b,h,g,e;a.image_timer-=1;if(null===(g=!(null===(h=a.image_timer)||!1===h||0===h||""===h?0:"object"==typeof h?"function"==typeof h.__nonzero__?h.__nonzero__():"function"==typeof h.__len__?0<h.__len__():1:1))||!1===g||0===g||""===g?0:"object"==typeof g?"function"==typeof g.__nonzero__?g.__nonzero__():"function"==typeof g.__len__?0<g.__len__():1:1)(null===(b="normal"===(d=a.current_image)&&null===d?!0:null===d?!1:"object"!=typeof d&&"function"!=
typeof d||"function"!=typeof d.__cmp__?"normal"==d:0===d.__cmp__("normal"))||!1===b||0===b||""===b?0:"object"==typeof b?"function"==typeof b.__nonzero__?b.__nonzero__():"function"==typeof b.__len__?0<b.__len__():1:1)?(a.image="undefined"!=typeof(e=a.images).__array?"undefined"!=typeof e.__array.blink?e.__array.blink:e.__getitem__("blink"):e.__getitem__("blink"),a.current_image="blink"):(a.image="undefined"!=typeof(k=a.images).__array?"undefined"!=typeof k.__array.normal?k.__array.normal:k.__getitem__("normal"):
k.__getitem__("normal"),a.current_image="normal"),a.image_timer=2;(null===(c=!(null===(f=a.tick())||!1===f||0===f||""===f?0:"object"==typeof f?"function"==typeof f.__nonzero__?f.__nonzero__():"function"==typeof f.__len__?0<f.__len__():1:1))||!1===c||0===c||""===c?0:"object"==typeof c?"function"==typeof c.__nonzero__?c.__nonzero__():"function"==typeof c.__len__?0<c.__len__():1:1)&&a.detonate();return null},1,[null,null,["self"]]);k.update=m;m=Array(d.engine.sprite.Sprite);var n=$p.dict(),t;for(t in k)n.__setitem__(t,
k[t]);return $p._create_class("Charge",$p.tuple(m),n)}();return this};
