$pyjs.loaded_modules.datum=function(k){if($pyjs.loaded_modules.datum.__was_initialized__)return $pyjs.loaded_modules.datum;var c=$pyjs.loaded_modules.datum;c.__repr__=function(){return"<module: datum>"};c.__was_initialized__=!0;if(null===k||"undefined"==typeof k)k="datum";c.__name__=k;c.env=$p.___import___("env",null);c.engine=c.env.engine;c.load_sound=$p.___import___("util.load_sound",null,null,!1);c.Datum=function(){var f={},h;f.__module__="datum";f.images=null;f.masks=null;f.radius=null;f.sound=
null;h=$pyjs__bind_method2("__init__",function(a,e,g,d,l){if(!0===this.__is_instance__)var b=this;else b=a,a=e,e=g,g=d,d=l;var s,f,h,t,m,n,k,p,q,r;c.engine.sprite.Sprite.__init__(b);b.matrix=a;b.x=$p["float"](e);b.y=$p["float"](g);b.dtype=d;if(null===(n=!(null===(r=b.images)||!1===r||0===r||""===r?0:"object"==typeof r?"function"==typeof r.__nonzero__?r.__nonzero__():"function"==typeof r.__len__?0<r.__len__():1:1))||!1===n||0===n||""===n?0:"object"==typeof n?"function"==typeof n.__nonzero__?n.__nonzero__():
"function"==typeof n.__len__?0<n.__len__():1:1)b.images=$p.dict([]),a=c.engine.Surface($p.tuple([11,11]),c.engine.SRCALPHA),g=$p.tuple([0,200,0]),l=$p.tuple([0,150,0]),d=$p.tuple([200,0,0]),e=$p.list([$p.tuple([5,0]),$p.tuple([10,2]),$p.tuple([10,8]),$p.tuple([5,10]),$p.tuple([0,8]),$p.tuple([0,2])]),c.engine.draw.polygon(a,g,e,0),c.engine.draw.polygon(a,g,e,1),b.images.__setitem__("hibit",a),a=c.engine.Surface($p.tuple([11,11]),c.engine.SRCALPHA),e=$p.list([$p.tuple([5,1]),$p.tuple([9,3]),$p.tuple([9,
7]),$p.tuple([5,9]),$p.tuple([0,7]),$p.tuple([0,3])]),c.engine.draw.polygon(a,l,e,0),c.engine.draw.polygon(a,l,e,1),b.images.__setitem__("lobit",a),a=c.engine.Surface($p.tuple([11,11]),c.engine.SRCALPHA),e=$p.list([$p.tuple([5,1]),$p.tuple([9,3]),$p.tuple([9,7]),$p.tuple([5,9]),$p.tuple([0,7]),$p.tuple([0,3])]),c.engine.draw.polygon(a,d,e,0),c.engine.draw.polygon(a,d,e,1),b.images.__setitem__("lobit_corrupt",a),b.masks=$p.dict([]),b.masks.__setitem__("hibit",c.engine.mask.from_surface("undefined"!=
typeof(m=b.images).__array?"undefined"!=typeof m.__array.hibit?m.__array.hibit:m.__getitem__("hibit"):m.__getitem__("hibit"))),b.masks.__setitem__("lobit",c.engine.mask.from_surface("undefined"!=typeof(t=b.images).__array?"undefined"!=typeof t.__array.lobit?t.__array.lobit:t.__getitem__("lobit"):t.__getitem__("lobit"))),b.masks.__setitem__("lobit_corrupt",c.engine.mask.from_surface("undefined"!=typeof(h=b.images).__array?"undefined"!=typeof h.__array.lobit_corrupt?h.__array.lobit_corrupt:h.__getitem__("lobit_corrupt"):
h.__getitem__("lobit_corrupt"))),b.radius=Math.floor(a.get_width()/2),b.sound=$p.dict([]),b.sound.__setitem__("blip",c.load_sound("blip.wav")),("undefined"!=typeof(f=b.sound).__array?"undefined"!=typeof f.__array.blip?f.__array.blip:f.__getitem__("blip"):f.__getitem__("blip")).set_volume(0.5);b.image="undefined"!=typeof(s=b.images).__array?"undefined"!=typeof s.__array.hibit?s.__array.hibit:s.__getitem__("hibit"):s.__getitem__("hibit");b.mask="undefined"!=typeof(k=b.masks).__array?"undefined"!=typeof k.__array.hibit?
k.__array.hibit:k.__getitem__("hibit"):k.__getitem__("hibit");b.current_image="hibit";b.rect=c.engine.Rect(0,0,11,11);b.rect.x=$p.float_int(b.x)-Math.floor(b.image.get_width()/2);b.rect.y=$p.float_int(b.y)-Math.floor(b.image.get_height()/2);(null===(q=!(null===(p=b.matrix.adjust)||!1===p||0===p||""===p?0:"object"==typeof p?"function"==typeof p.__nonzero__?p.__nonzero__():"function"==typeof p.__len__?0<p.__len__():1:1))||!1===q||0===q||""===q?0:"object"==typeof q?"function"==typeof q.__nonzero__?q.__nonzero__():
"function"==typeof q.__len__?0<q.__len__():1:1)?b.vel=5:b.vel=10;b.state_changed=!1;b.direction="d";return b.node_previous=null},1,[null,null,["self"],["matrix"],["x"],["y"],["dtype"]]);f.__init__=h;h=$pyjs__bind_method2("state_change",function(a){a=!0===this.__is_instance__?this:a;var e,g,d,l,b,c,f,h,k,m;(null===(c="hibit"===(l=a.current_image)&&null===l?!0:null===l?!1:"object"!=typeof l&&"function"!=typeof l||"function"!=typeof l.__cmp__?"hibit"==l:0===l.__cmp__("hibit"))||!1===c||0===c||""===c?
0:"object"==typeof c?"function"==typeof c.__nonzero__?c.__nonzero__():"function"==typeof c.__len__?0<c.__len__():1:1)?((null===(b="noncorrupt"===(d=a.dtype)&&null===d?!0:null===d?!1:"object"!=typeof d&&"function"!=typeof d||"function"!=typeof d.__cmp__?"noncorrupt"==d:0===d.__cmp__("noncorrupt"))||!1===b||0===b||""===b?0:"object"==typeof b?"function"==typeof b.__nonzero__?b.__nonzero__():"function"==typeof b.__len__?0<b.__len__():1:1)?(a.image="undefined"!=typeof(k=a.images).__array?"undefined"!=
typeof k.__array.lobit?k.__array.lobit:k.__getitem__("lobit"):k.__getitem__("lobit"),a.mask="undefined"!=typeof(f=a.masks).__array?"undefined"!=typeof f.__array.lobit?f.__array.lobit:f.__getitem__("lobit"):f.__getitem__("lobit")):(a.image="undefined"!=typeof(h=a.images).__array?"undefined"!=typeof h.__array.lobit_corrupt?h.__array.lobit_corrupt:h.__getitem__("lobit_corrupt"):h.__getitem__("lobit_corrupt"),a.mask="undefined"!=typeof(e=a.masks).__array?"undefined"!=typeof e.__array.lobit_corrupt?e.__array.lobit_corrupt:
e.__getitem__("lobit_corrupt"):e.__getitem__("lobit_corrupt")),a.current_image="lobit"):(a.image="undefined"!=typeof(g=a.images).__array?"undefined"!=typeof g.__array.hibit?g.__array.hibit:g.__getitem__("hibit"):g.__getitem__("hibit"),a.mask="undefined"!=typeof(m=a.masks).__array?"undefined"!=typeof m.__array.hibit?m.__array.hibit:m.__getitem__("hibit"):m.__getitem__("hibit"),a.current_image="hibit");a.rect.x=$p.float_int(a.x)-Math.floor(a.image.get_width()/2);a.rect.y=$p.float_int(a.y)-Math.floor(a.image.get_height()/
2);a.state_changed=!0;return null},1,[null,null,["self"]]);f.state_change=h;h=$pyjs__bind_method2("damage",function(a){a=!0===this.__is_instance__?this:a;var e,g,d;a.matrix.nexus.data_loss(a);(null===(d=!(null===(g=c.env.debug)||!1===g||0===g||""===g?0:"object"==typeof g?"function"==typeof g.__nonzero__?g.__nonzero__():"function"==typeof g.__len__?0<g.__len__():1:1))||!1===d||0===d||""===d?0:"object"==typeof d?"function"==typeof d.__nonzero__?d.__nonzero__():"function"==typeof d.__len__?0<d.__len__():
1:1)&&("undefined"!=typeof(e=a.sound).__array?"undefined"!=typeof e.__array.blip?e.__array.blip:e.__getitem__("blip"):e.__getitem__("blip")).play();return null},1,[null,null,["self"]]);f.damage=h;h=$pyjs__bind_method2("move",function(a){a=!0===this.__is_instance__?this:a;var e,g,d,c,b,f;if(null===(f="d"===(b=a.direction)&&null===b?!0:null===b?!1:"object"!=typeof b&&"function"!=typeof b||"function"!=typeof b.__cmp__?"d"==b:0===b.__cmp__("d"))||!1===f||0===f||""===f?0:"object"==typeof f?"function"==
typeof f.__nonzero__?f.__nonzero__():"function"==typeof f.__len__?0<f.__len__():1:1)a.y+=a.vel,a.rect.y=$p.float_int(a.y)-Math.floor(a.image.get_height()/2);else if(null===(e="l"===(c=a.direction)&&null===c?!0:null===c?!1:"object"!=typeof c&&"function"!=typeof c||"function"!=typeof c.__cmp__?"l"==c:0===c.__cmp__("l"))||!1===e||0===e||""===e?0:"object"==typeof e?"function"==typeof e.__nonzero__?e.__nonzero__():"function"==typeof e.__len__?0<e.__len__():1:1)a.x-=a.vel,a.rect.x=$p.float_int(a.x)-Math.floor(a.image.get_width()/
2);else if(null===(g="r"===(d=a.direction)&&null===d?!0:null===d?!1:"object"!=typeof d&&"function"!=typeof d||"function"!=typeof d.__cmp__?"r"==d:0===d.__cmp__("r"))||!1===g||0===g||""===g?0:"object"==typeof g?"function"==typeof g.__nonzero__?g.__nonzero__():"function"==typeof g.__len__?0<g.__len__():1:1)a.x+=a.vel,a.rect.x=$p.float_int(a.x)-Math.floor(a.image.get_width()/2);return null},1,[null,null,["self"]]);f.move=h;h=$pyjs__bind_method2("update",function(a){a=!0===this.__is_instance__?this:a;
var e,c,d,f;(null===(c=!(null===(e=a.state_changed)||!1===e||0===e||""===e?0:"object"==typeof e?"function"==typeof e.__nonzero__?e.__nonzero__():"function"==typeof e.__len__?0<e.__len__():1:1))||!1===c||0===c||""===c?0:"object"==typeof c?"function"==typeof c.__nonzero__?c.__nonzero__():"function"==typeof c.__len__?0<c.__len__():1:1)?e=a.matrix.node_check(a):(a.state_changed=!1,e=null);(null===(d=e)||!1===d||0===d||""===d?0:"object"==typeof d?"function"==typeof d.__nonzero__?d.__nonzero__():"function"==
typeof d.__len__?0<d.__len__():1:1)?(d=e.communicate(a),(null===(f=!(null===d||!1===d||0===d||""===d?0:"object"==typeof d?"function"==typeof d.__nonzero__?d.__nonzero__():"function"==typeof d.__len__?0<d.__len__():1:1))||!1===f||0===f||""===f?0:"object"==typeof f?"function"==typeof f.__nonzero__?f.__nonzero__():"function"==typeof f.__len__?0<f.__len__():1:1)&&a.matrix.nexus.data_loss(a),a.direction=d,a.node_previous=e.id,a.state_change()):a.move();return null},1,[null,null,["self"]]);f.update=h;h=
Array(c.engine.sprite.Sprite);var k=$p.dict(),u;for(u in f)k.__setitem__(u,f[u]);return $p._create_class("Datum",$p.tuple(h),k)}();return this};
