$pyjs.loaded_modules.genericpath=function(s){if($pyjs.loaded_modules.genericpath.__was_initialized__)return $pyjs.loaded_modules.genericpath;var a=$pyjs.loaded_modules.genericpath;a.__repr__=function(){return"<module: genericpath>"};a.__was_initialized__=!0;if(null===s||"undefined"==typeof s)s="genericpath";a.__name__=s;a.os=$p.___import___("os",null);a.stat=$p.___import___("stat",null);a.__all__=$p.list("commonprefix exists getatime getctime getmtime getsize isdir isfile".split(" "));a.exists=function(e){try{a.os.stat(e)}catch(d){e=
"undefined"==typeof d.__name__?d.name:d.__name__;$pyjs.__last_exception__={error:d,module:a};if(e==a.os.error.__name__||$p._isinstance(d,a.os.error))return!1;$pyjs.__active_exception_stack__=$pyjs.__last_exception_stack__;$pyjs.__last_exception_stack__=null;throw d;}return!0};a.exists.__name__="exists";a.exists.__bind_type__=0;a.exists.__args__=[null,null,["path"]];a.isfile=function(e){var d;try{d=a.os.stat(e)}catch(b){e="undefined"==typeof b.__name__?b.name:b.__name__;$pyjs.__last_exception__={error:b,
module:a};if(e==a.os.error.__name__||$p._isinstance(b,a.os.error))return!1;$pyjs.__active_exception_stack__=$pyjs.__last_exception_stack__;$pyjs.__last_exception_stack__=null;throw b;}return a.stat.S_ISREG(d.st_mode)};a.isfile.__name__="isfile";a.isfile.__bind_type__=0;a.isfile.__args__=[null,null,["path"]];a.isdir=function(e){var d;try{d=a.os.stat(e)}catch(b){e="undefined"==typeof b.__name__?b.name:b.__name__;$pyjs.__last_exception__={error:b,module:a};if(e==a.os.error.__name__||$p._isinstance(b,
a.os.error))return!1;$pyjs.__active_exception_stack__=$pyjs.__last_exception_stack__;$pyjs.__last_exception_stack__=null;throw b;}return a.stat.S_ISDIR(d.st_mode)};a.isdir.__name__="isdir";a.isdir.__bind_type__=0;a.isdir.__args__=[null,null,["s"]];a.getsize=function(e){return a.os.stat(e).st_size};a.getsize.__name__="getsize";a.getsize.__bind_type__=0;a.getsize.__args__=[null,null,["filename"]];a.getmtime=function(e){return a.os.stat(e).st_mtime};a.getmtime.__name__="getmtime";a.getmtime.__bind_type__=
0;a.getmtime.__args__=[null,null,["filename"]];a.getatime=function(e){return a.os.stat(e).st_atime};a.getatime.__name__="getatime";a.getatime.__bind_type__=0;a.getatime.__args__=[null,null,["filename"]];a.getctime=function(e){return a.os.stat(e).st_ctime};a.getctime.__name__="getctime";a.getctime.__bind_type__=0;a.getctime.__args__=[null,null,["filename"]];a.commonprefix=function(a){var d,b,l,p,c,f,g,m,n,h,k,q;if(null===(c=!(null===a||!1===a||0===a||""===a?0:"object"==typeof a?"function"==typeof a.__nonzero__?
a.__nonzero__():"function"==typeof a.__len__?0<a.__len__():1:1))||!1===c||0===c||""===c?0:"object"==typeof c?"function"==typeof c.__nonzero__?c.__nonzero__():"function"==typeof c.__len__?0<c.__len__():1:1)return"";c=$p.min(a);p=$p.max(a);g=$p.enumerate(c);"undefined"!=typeof(n=g.__array)?a=0:(g=g.__iter__(),a="undefined"!=typeof(n=g.__array)?0:"function"==typeof g.$genfunc?1:-1);for(q=0;"undefined"!=typeof(b=a?0<a?g.next(!0,!1):$p.wrapped_next(g):n[q++]);)if(d=$p.__ass_unpack(b,2,null),b=d[0],d=d[1],
null===(l=!((f=d)===(m="undefined"!=typeof(h=p).__array?"undefined"!=typeof h.__array[k=b]?h.__array[k]:h.__getitem__(k):h.__getitem__(b))&&null===f||(null===f?0:null===m?0:"object"!=typeof f&&"function"!=typeof f||"function"!=typeof f.__cmp__?"object"!=typeof m&&"function"!=typeof m||"function"!=typeof m.__cmp__?f==m:0===m.__cmp__(f):0===f.__cmp__(m))))||!1===l||0===l||""===l?0:"object"==typeof l?"function"==typeof l.__nonzero__?l.__nonzero__():"function"==typeof l.__len__?0<l.__len__():1:1)return $p.__getslice(c,
0,b);return c};a.commonprefix.__name__="commonprefix";a.commonprefix.__bind_type__=0;a.commonprefix.__args__=[null,null,["m"]];a._splitext=function(a,d,b,l){var p,c,f,g,m,n,h,k,q,r;d=a.rfind(d);if(null===b||!1===b||0===b||""===b?0:"object"==typeof b?"function"==typeof b.__nonzero__?b.__nonzero__():"function"==typeof b.__len__?0<b.__len__():1:1)b=a.rfind(b),d=$p.max(d,b);b=a.rfind(l);if(null===(c=1==(b===(r=d)?0:typeof b!=typeof r||"number"!=typeof b&&"string"!=typeof b&&"boolean"!=typeof b?$p.cmp(b,
r):b==r?0:b<r?-1:1))||!1===c||0===c||""===c?0:"object"==typeof c?"function"==typeof c.__nonzero__?c.__nonzero__():"function"==typeof c.__len__?0<c.__len__():1:1)for(c=d+1;null===(h=-1==((f=c)===(p=b)?0:typeof f!=typeof p||"number"!=typeof f&&"string"!=typeof f&&"boolean"!=typeof f?$p.cmp(f,p):f==p?0:f<p?-1:1))||!1===h||0===h||""===h?0:"object"==typeof h?"function"==typeof h.__nonzero__?h.__nonzero__():"function"==typeof h.__len__?0<h.__len__():1:1;){if(null===(k=!((g="undefined"!=typeof(q=a).__array?
"undefined"!=typeof q.__array[m=c]?q.__array[m]:q.__getitem__(m):q.__getitem__(c))===(n=l)&&null===g||(null===g?0:null===n?0:"object"!=typeof g&&"function"!=typeof g||"function"!=typeof g.__cmp__?"object"!=typeof n&&"function"!=typeof n||"function"!=typeof n.__cmp__?g==n:0===n.__cmp__(g):0===g.__cmp__(n))))||!1===k||0===k||""===k?0:"object"==typeof k?"function"==typeof k.__nonzero__?k.__nonzero__():"function"==typeof k.__len__?0<k.__len__():1:1)return $p.tuple([$p.__getslice(a,0,b),$p.__getslice(a,
b,null)]);c+=1}return $p.tuple([a,""])};a._splitext.__name__="_splitext";a._splitext.__bind_type__=0;a._splitext.__args__=[null,null,["p"],["sep"],["altsep"],["extsep"]];return this};
