$pyjs.loaded_modules["interface"]=function(f){if($pyjs.loaded_modules["interface"].__was_initialized__)return $pyjs.loaded_modules["interface"];var g=$pyjs.loaded_modules["interface"];g.__repr__=function(){return"<module: interface>"};g.__was_initialized__=!0;if(null===f||"undefined"==typeof f)f="interface";g.__name__=f;g.env=$p.___import___("env",null);g.engine=g.env.engine;g.interphase=$p.___import___("interphase",null);g.interphase.init(g.engine);g.MatrixInterface=function(){var d={},b;d.__module__=
"interface";b=$pyjs__bind_method2("__init__",function(a,b,c,h){if(!0===this.__is_instance__)var e=this;else e=a,a=b,b=c,c=h;e.matrix=b;e.control=c;$pyjs_kwargs_call(g.interphase.Interface,"__init__",null,null,[{position:$p.tuple([Math.floor(e.matrix.width/2),e.matrix.height-50]),color:$p.tuple([15,30,50]),size:$p.tuple([200,100]),control_minsize:$p.tuple([35,35]),control_size:"auto",control_response:100,moveable:!1,position_offset:$p.tuple([0,98]),font_color:$p.tuple([50,150,200]),scroll_button:"vertical"},
e,a]);e.get_control("Activate").set_active(!1);return null},1,[null,null,["self"],["identity"],["matrix"],["control"]]);d.__init__=b;b=$pyjs__bind_method2("add_controls",function(a){a=!0===this.__is_instance__?this:a;$pyjs_kwargs_call(a,"add",null,null,[{identity:"Control",control_type:"function_toggle",position:$p.tuple([100,90]),size:"auto_width",font_color:$p.tuple([125,175,200]),control_list:$p.list(["Help","Main"]),link:$p.list([$p.list(["Bootup"]),$p.list(["Guide"])]),link_activated:!0,control_outline:!0}]);
$pyjs_kwargs_call(a,"add",null,null,[{identity:"Bootup",control_type:"control_toggle",position:$p.tuple([100,50]),size:"auto",font_color:$p.tuple([125,175,200]),control_list:$p.list(["Bootup"]),tip_list:$p.list(["Nexus activate"])}]);$pyjs_kwargs_call(a,"add",null,null,[{identity:"Activate",control_type:"control_toggle",position:$p.tuple([100,50]),size:"auto",font_color:$p.tuple([125,175,200]),control_list:$p.list(["Pause","Activate"]),tip_list:$p.list(["Nexus pause","Nexus activate"])}]);$pyjs_kwargs_call(a,
"add",null,null,[{identity:"DataProcessedTop",control_type:"label",position:$p.tuple([60,44]),size:$p.tuple([40,20]),font_color:$p.tuple([125,175,200]),control_list:$p.list(["0"]),tip_list:$p.list(["Nexus Data Integration"])}]);$pyjs_kwargs_call(a,"add",null,null,[{identity:"DataProcessed",control_type:"label",position:$p.tuple([60,84]),size:$p.tuple([40,20]),font_color:$p.tuple([125,175,200]),control_list:$p.list(["0"]),tip_list:$p.list(["Nexus Data Integration"])}]);$pyjs_kwargs_call(a,"add",null,
null,[{identity:"DataProcessedTopLabel",control_type:"label",position:$p.tuple([60,24]),size:$p.tuple([40,20]),font_color:$p.tuple([125,175,200]),control_list:$p.list(["Top"]),tip_list:$p.list(["Nexus Data Integration"])}]);$pyjs_kwargs_call(a,"add",null,null,[{identity:"DataProcessedLabel",control_type:"label",position:$p.tuple([60,64]),size:$p.tuple([40,20]),font_color:$p.tuple([125,175,200]),control_list:$p.list(["Current"]),tip_list:$p.list(["Nexus Data Integration"])}]);$pyjs_kwargs_call(a,"add",
null,null,[{identity:"Guide",control_type:"textbox",position:$p.tuple([100,50]),size:$p.tuple([170,70]),color:$p.tuple([49,57,65]),font_color:$p.tuple([125,175,200]),font_size:10,font_type:"arial",control_list:$p.list([a.control.guide]),label_display:!1}]);return null},1,[null,null,["self"]]);d.add_controls=b;b=$pyjs__bind_method2("set_data_processed",function(a,b){if(!0===this.__is_instance__)var c=this;else c=a,a=b;c.get_control("DataProcessed").set_value($p.str(a));return null},1,[null,null,["self"],
["dataprocessed"]]);d.set_data_processed=b;b=$pyjs__bind_method2("set_data_processed_top",function(a,b){if(!0===this.__is_instance__)var c=this;else c=a,a=b;c.get_control("DataProcessedTop").set_value($p.str(a));return null},1,[null,null,["self"],["dataprocessed"]]);d.set_data_processed_top=b;b=$pyjs__bind_method2("reset",function(a){a=!0===this.__is_instance__?this:a;a.control.set_panel_display();a.get_control("Activate").set_active(!1);a.get_control("Bootup").set_active(!0);return null},1,[null,
null,["self"]]);d.reset=b;b=$pyjs__bind_method2("update",function(a){a=!0===this.__is_instance__?this:a;var b,c,h,e,d,s,k,l,m,n,p,f,u,t,q,r;c=g.interphase.Interface.update(a);if(null===(m=c.control)||!1===m||0===m||""===m?0:"object"==typeof m?"function"==typeof m.__nonzero__?m.__nonzero__():"function"==typeof m.__len__?0<m.__len__():1:1)if(null===(k="Bootup"===(e=c.control)&&null===e?!0:null===e?!1:"object"!=typeof e&&"function"!=typeof e||"function"!=typeof e.__cmp__?"Bootup"==e:0===e.__cmp__("Bootup"))||
!1===k||0===k||""===k?0:"object"==typeof k?"function"==typeof k.__nonzero__?k.__nonzero__():"function"==typeof k.__len__?0<k.__len__():1:1)a.control.set_panel_display(),("undefined"!=typeof(u=c.controls).__array?"undefined"!=typeof u.__array.Bootup?u.__array.Bootup:u.__getitem__("Bootup"):u.__getitem__("Bootup")).set_active(!1),("undefined"!=typeof(f=c.controls).__array?"undefined"!=typeof f.__array.Activate?f.__array.Activate:f.__getitem__("Activate"):f.__getitem__("Activate")).set_active(!0),a.matrix.nexus.initiation_activate();
else if(null===(l="Activate"===(h=c.control)&&null===h?!0:null===h?!1:"object"!=typeof h&&"function"!=typeof h||"function"!=typeof h.__cmp__?"Activate"==h:0===h.__cmp__("Activate"))||!1===l||0===l||""===l?0:"object"==typeof l?"function"==typeof l.__nonzero__?l.__nonzero__():"function"==typeof l.__len__?0<l.__len__():1:1){if(null===(p=!(null===(n=a.matrix.nexus.initiate)||!1===n||0===n||""===n?0:"object"==typeof n?"function"==typeof n.__nonzero__?n.__nonzero__():"function"==typeof n.__len__?0<n.__len__():
1:1))||!1===p||0===p||""===p?0:"object"==typeof p?"function"==typeof p.__nonzero__?p.__nonzero__():"function"==typeof p.__len__?0<p.__len__():1:1)return("undefined"!=typeof(b=c.controls).__array?"undefined"!=typeof b.__array[t=c.control]?b.__array[t]:b.__getitem__(t):b.__getitem__(c.control)).next(),null;(null===(q="Pause"===(s=c.value)&&null===s?!0:null===s?!1:"object"!=typeof s&&"function"!=typeof s||"function"!=typeof s.__cmp__?"Pause"==s:0===s.__cmp__("Pause"))||!1===q||0===q||""===q?0:"object"==
typeof q?"function"==typeof q.__nonzero__?q.__nonzero__():"function"==typeof q.__len__?0<q.__len__():1:1)?a.matrix.set_active(!0):(null===(r="Activate"===(d=c.value)&&null===d?!0:null===d?!1:"object"!=typeof d&&"function"!=typeof d||"function"!=typeof d.__cmp__?"Activate"==d:0===d.__cmp__("Activate"))||!1===r||0===r||""===r?0:"object"==typeof r?"function"==typeof r.__nonzero__?r.__nonzero__():"function"==typeof r.__len__?0<r.__len__():1:1)&&a.matrix.set_active(!1)}return null},1,[null,null,["self"]]);
d.update=b;b=Array(g.interphase.Interface);var f=$p.dict(),t;for(t in d)f.__setitem__(t,d[t]);return $p._create_class("MatrixInterface",$p.tuple(b),f)}();return this};
