$pyjs.loaded_modules.nexus=function(l){if($pyjs.loaded_modules.nexus.__was_initialized__)return $pyjs.loaded_modules.nexus;var a=$pyjs.loaded_modules.nexus;a.__repr__=function(){return"<module: nexus>"};a.__was_initialized__=!0;if(null===l||"undefined"==typeof l)l="nexus";a.__name__=l;var b,g,h,k,e,c,d,f;a.os=$p.___import___("os",null);a.sys=$p.___import___("sys",null);(null===(c=$p.tuple(["posix","nt","os2","ce","riscos"]).__contains__(a.os.$$name))||!1===c||0===c||""===c?0:"object"==typeof c?"function"==
typeof c.__nonzero__?c.__nonzero__():"function"==typeof c.__len__?0<c.__len__():1:1)?(a.engine=$p.___import___("pygame",null,null,!1),a.platform="pc"):(null===(e="java"===(h=a.os.$$name)&&null===h?!0:null===h?!1:"object"!=typeof h&&"function"!=typeof h||"function"!=typeof h.__cmp__?"java"==h:0===h.__cmp__("java"))||!1===e||0===e||""===e?0:"object"==typeof e?"function"==typeof e.__nonzero__?e.__nonzero__():"function"==typeof e.__len__?0<e.__len__():1:1)?(a.engine=$p.___import___("pyj2d",null,null,
!1),a.platform="jvm"):(a.engine=$p.___import___("pyjsdl",null,null,!1),a.platform="js");a.env=$p.___import___("env",null);a.env.engine=a.engine;a.env.platform=a.platform;a.Matrix=$p.___import___("matrix.Matrix",null,null,!1);a.setup=function(m,n){var b,e,c,d;a.engine.init();a.engine.display.set_mode($p.tuple([m,n]));a.engine.event.set_blocked(a.engine.MOUSEMOTION);$pyjs_kwargs_call(a.engine.mixer,"init",null,null,[{size:-16,channels:2,buffer:4096},11025]);if(null===(d=(null===(b=e=a.engine.mixer)||
!1===b||0===b||""===b?0:"object"==typeof b?"function"==typeof b.__nonzero__?b.__nonzero__():"function"==typeof b.__len__?0<b.__len__():1:1)?!(null===(c=a.engine.mixer.get_init())||!1===c||0===c||""===c?0:"object"==typeof c?"function"==typeof c.__nonzero__?c.__nonzero__():"function"==typeof c.__len__?0<c.__len__():1:1):e)||!1===d||0===d||""===d?0:"object"==typeof d?"function"==typeof d.__nonzero__?d.__nonzero__():"function"==typeof d.__len__?0<d.__len__():1:1)a.engine.mixer=null;return null};a.setup.__name__=
"setup";a.setup.__bind_type__=0;a.setup.__args__=[null,null,["width"],["height"]];a.matrix=null;a.run_js=function(){a.matrix.update();a.engine.display.update(a.matrix.update_rect);a.matrix.control.clock.tick(30);return null};a.run_js.__name__="run_js";a.run_js.__bind_type__=0;a.run_js.__args__=[null,null];a.prerun_js=function(){a.matrix=a.Matrix();a.engine.display.update(a.matrix.update_rect);a.engine.display.setup(a.run_js);return null};a.prerun_js.__name__="prerun_js";a.prerun_js.__bind_type__=
0;a.prerun_js.__args__=[null,null];a.main_js=function(){a.setup(500,500);a.engine.display.setup(a.prerun_js);return null};a.main_js.__name__="main_js";a.main_js.__bind_type__=0;a.main_js.__args__=[null,null];a.run=function(){for(var b,c;null===(c=!(null===(b=a.matrix.quit)||!1===b||0===b||""===b?0:"object"==typeof b?"function"==typeof b.__nonzero__?b.__nonzero__():"function"==typeof b.__len__?0<b.__len__():1:1))||!1===c||0===c||""===c?0:"object"==typeof c?"function"==typeof c.__nonzero__?c.__nonzero__():
"function"==typeof c.__len__?0<c.__len__():1:1;)a.matrix.update(),a.engine.display.update(a.matrix.update_rect),a.matrix.control.clock.tick(30);a.matrix.shutdown();a.engine.quit();return null};a.run.__name__="run";a.run.__bind_type__=0;a.run.__args__=[null,null];a.prerun=function(){a.matrix=a.Matrix();a.engine.display.update(a.matrix.update_rect);a.run();return null};a.prerun.__name__="prerun";a.prerun.__bind_type__=0;a.prerun.__args__=[null,null];a.main=function(){a.setup(500,500);a.prerun();return null};
a.main.__name__="main";a.main.__bind_type__=0;a.main.__args__=[null,null];if(null===(d="__main__"===(g="undefined"==typeof __name__?a.__name__:__name__)&&null===g?!0:null===g?!1:"object"!=typeof g&&"function"!=typeof g||"function"!=typeof g.__cmp__?"__main__"==g:0===g.__cmp__("__main__"))||!1===d||0===d||""===d?0:"object"==typeof d?"function"==typeof d.__nonzero__?d.__nonzero__():"function"==typeof d.__len__?0<d.__len__():1:1)(null===(f=$p.tuple(["pc","jvm"]).__contains__(a.platform))||!1===f||0===
f||""===f?0:"object"==typeof f?"function"==typeof f.__nonzero__?f.__nonzero__():"function"==typeof f.__len__?0<f.__len__():1:1)?a.main():(null===(b="js"===(k=a.platform)&&null===k?!0:null===k?!1:"object"!=typeof k&&"function"!=typeof k||"function"!=typeof k.__cmp__?"js"==k:0===k.__cmp__("js"))||!1===b||0===b||""===b?0:"object"==typeof b?"function"==typeof b.__nonzero__?b.__nonzero__():"function"==typeof b.__len__?0<b.__len__():1:1)&&a.main_js();return this};
