$pyjs.loaded_modules.pulse=function(q){if($pyjs.loaded_modules.pulse.__was_initialized__)return $pyjs.loaded_modules.pulse;var m=$pyjs.loaded_modules.pulse;m.__repr__=function(){return"<module: pulse>"};m.__was_initialized__=!0;if(null===q||"undefined"==typeof q)q="pulse";m.__name__=q;m.env=$p.___import___("env",null);m.engine=m.env.engine;m.Pulse=function(){var n={},p;n.__module__="pulse";n.images=null;n.masks=null;n.radius=null;p=$pyjs__bind_method2("__init__",function(a,d,e,c,g,k){if(!0===this.__is_instance__)var b=
this;else b=a,a=d,d=e,e=c,c=g,g=k;var f,l,h,n,p,q,r,s,t,u;m.engine.sprite.Sprite.__init__(b);b.matrix=a;b.x=$p["float"](d);b.y=$p["float"](e);b.direction=c;if(null===(r=!(null===(s=b.images)||!1===s||0===s||""===s?0:"object"==typeof s?"function"==typeof s.__nonzero__?s.__nonzero__():"function"==typeof s.__len__?0<s.__len__():1:1))||!1===r||0===r||""===r?0:"object"==typeof r?"function"==typeof r.__nonzero__?r.__nonzero__():"function"==typeof r.__len__?0<r.__len__():1:1)b.images=$p.dict([]),a=$p.tuple([200,
200,200]),d=m.engine.Surface($p.tuple([11,11]),m.engine.SRCALPHA),e=$p.list([$p.tuple([5,0]),$p.tuple([9,1]),$p.tuple([10,5]),$p.tuple([9,9]),$p.tuple([5,10]),$p.tuple([1,9]),$p.tuple([0,5]),$p.tuple([1,1])]),m.engine.draw.polygon(d,a,e,0),m.engine.draw.polygon(d,a,e,1),b.images.__setitem__("hibit",d),d=m.engine.Surface($p.tuple([11,11]),m.engine.SRCALPHA),e=$p.list([$p.tuple([5,2]),$p.tuple([7,3]),$p.tuple([8,5]),$p.tuple([7,7]),$p.tuple([5,8]),$p.tuple([3,7]),$p.tuple([2,5]),$p.tuple([3,3])]),m.engine.draw.polygon(d,
a,e,0),m.engine.draw.polygon(d,a,e,1),b.images.__setitem__("lobit",d),b.masks=$p.dict([]),b.masks.__setitem__("hibit",m.engine.mask.from_surface("undefined"!=typeof(q=b.images).__array?"undefined"!=typeof q.__array.hibit?q.__array.hibit:q.__getitem__("hibit"):q.__getitem__("hibit"))),b.masks.__setitem__("lobit",m.engine.mask.from_surface("undefined"!=typeof(p=b.images).__array?"undefined"!=typeof p.__array.lobit?p.__array.lobit:p.__getitem__("lobit"):p.__getitem__("lobit"))),b.radius=Math.floor(d.get_width()/
2);b.image="undefined"!=typeof(n=b.images).__array?"undefined"!=typeof n.__array.hibit?n.__array.hibit:n.__getitem__("hibit"):n.__getitem__("hibit");b.mask="undefined"!=typeof(l=b.masks).__array?"undefined"!=typeof l.__array.hibit?l.__array.hibit:l.__getitem__("hibit"):l.__getitem__("hibit");b.current_image="hibit";b.image_timer=2;b.rect=$pyjs_kwargs_call(b.image,"get_rect",null,null,[{center:$p.tuple([$p.float_int(b.x),$p.float_int(b.y)])}]);(null===(f=!(null===(u=b.matrix.adjust)||!1===u||0===u||
""===u?0:"object"==typeof u?"function"==typeof u.__nonzero__?u.__nonzero__():"function"==typeof u.__len__?0<u.__len__():1:1))||!1===f||0===f||""===f?0:"object"==typeof f?"function"==typeof f.__nonzero__?f.__nonzero__():"function"==typeof f.__len__?0<f.__len__():1:1)?(null===(t=$p.tuple(["u","l"]).__contains__(c))||!1===t||0===t||""===t?0:"object"==typeof t?"function"==typeof t.__nonzero__?t.__nonzero__():"function"==typeof t.__len__?0<t.__len__():1:1)?b.vel=-10:b.vel=10:(null===(h=$p.tuple(["u","l"]).__contains__(c))||
!1===h||0===h||""===h?0:"object"==typeof h?"function"==typeof h.__nonzero__?h.__nonzero__():"function"==typeof h.__len__?0<h.__len__():1:1)?b.vel=-20:b.vel=20;b.targets=g;return null},1,[null,null,["self"],["matrix"],["x"],["y"],["direction"],["targets"]]);n.__init__=p;p=$pyjs__bind_method2("hit",function(a){a=!0===this.__is_instance__?this:a;var d,e,c,g,k,b,f,l,h;e=a.targets;"undefined"!=typeof(k=e.__array)?l=0:(e=e.__iter__(),l="undefined"!=typeof(k=e.__array)?0:"function"==typeof e.$genfunc?1:
-1);for(h=0;"undefined"!=typeof(g=l?0<l?e.next(!0,!1):$p.wrapped_next(e):k[h++]);)if(g=m.engine.sprite.spritecollide(a,g,!1,a.matrix.collide_mask),null===(c=g)||!1===c||0===c||""===c?0:"object"==typeof c?"function"==typeof c.__nonzero__?c.__nonzero__():"function"==typeof c.__len__?0<c.__len__():1:1)return("undefined"!=typeof(d=g).__array?"undefined"!=typeof d.__array[0]?d.__array[0]:d.__getitem__(0):d.__getitem__(0)).shot(),!0;c=$p.list([a.matrix.data]);"undefined"!=typeof(k=c.__array)?d=0:(c=c.__iter__(),
d="undefined"!=typeof(k=c.__array)?0:"function"==typeof c.$genfunc?1:-1);for(e=0;"undefined"!=typeof(g=d?0<d?c.next(!0,!1):$p.wrapped_next(c):k[e++]);)if(g=m.engine.sprite.spritecollide(a,g,!1,a.matrix.collide_mask),null===(f=g)||!1===f||0===f||""===f?0:"object"==typeof f?"function"==typeof f.__nonzero__?f.__nonzero__():"function"==typeof f.__len__?0<f.__len__():1:1)return("undefined"!=typeof(b=g).__array?"undefined"!=typeof b.__array[0]?b.__array[0]:b.__getitem__(0):b.__getitem__(0)).damage(),!0;
return!1},1,[null,null,["self"]]);n.hit=p;p=$pyjs__bind_method2("move",function(a){a=!0===this.__is_instance__?this:a;var d,e,c,g,k,b,f,l,h;(null===(c=$p.tuple(["u","d"]).__contains__(a.direction))||!1===c||0===c||""===c?0:"object"==typeof c?"function"==typeof c.__nonzero__?c.__nonzero__():"function"==typeof c.__len__?0<c.__len__():1:1)?(null===(d=-1==(-25===(l=$compare1=a.y)?0:"number"==typeof l?-25==l?0:-25<l?-1:1:$p.cmp(-25,l))&&-1==((f=$compare1)===(g=$compare2=a.matrix.height)?0:typeof f!=typeof g||
"number"!=typeof f&&"string"!=typeof f&&"boolean"!=typeof f?$p.cmp(f,g):f==g?0:f<g?-1:1))||!1===d||0===d||""===d?0:"object"==typeof d?"function"==typeof d.__nonzero__?d.__nonzero__():"function"==typeof d.__len__?0<d.__len__():1:1)?(a.y+=a.vel,a.rect.y=$p.float_int(a.y)):a.kill():(null===(e=-1==(-25===(b=$compare3=a.y)?0:"number"==typeof b?-25==b?0:-25<b?-1:1:$p.cmp(-25,b))&&-1==((k=$compare3)===(h=$compare4=a.matrix.height)?0:typeof k!=typeof h||"number"!=typeof k&&"string"!=typeof k&&"boolean"!=
typeof k?$p.cmp(k,h):k==h?0:k<h?-1:1))||!1===e||0===e||""===e?0:"object"==typeof e?"function"==typeof e.__nonzero__?e.__nonzero__():"function"==typeof e.__len__?0<e.__len__():1:1)?(a.x+=a.vel,a.rect.x=$p.float_int(a.x)):a.kill();return null},1,[null,null,["self"]]);n.move=p;p=$pyjs__bind_method2("update",function(a){a=!0===this.__is_instance__?this:a;var d,e,c,g,k,b,f,l,h;a.image_timer-=1;if(null===(e=!(null===(d=a.image_timer)||!1===d||0===d||""===d?0:"object"==typeof d?"function"==typeof d.__nonzero__?
d.__nonzero__():"function"==typeof d.__len__?0<d.__len__():1:1))||!1===e||0===e||""===e?0:"object"==typeof e?"function"==typeof e.__nonzero__?e.__nonzero__():"function"==typeof e.__len__?0<e.__len__():1:1)(null===(c="hibit"===(b=a.current_image)&&null===b?!0:null===b?!1:"object"!=typeof b&&"function"!=typeof b||"function"!=typeof b.__cmp__?"hibit"==b:0===b.__cmp__("hibit"))||!1===c||0===c||""===c?0:"object"==typeof c?"function"==typeof c.__nonzero__?c.__nonzero__():"function"==typeof c.__len__?0<
c.__len__():1:1)?(a.image="undefined"!=typeof(l=a.images).__array?"undefined"!=typeof l.__array.lobit?l.__array.lobit:l.__getitem__("lobit"):l.__getitem__("lobit"),a.mask="undefined"!=typeof(k=a.masks).__array?"undefined"!=typeof k.__array.lobit?k.__array.lobit:k.__getitem__("lobit"):k.__getitem__("lobit"),a.current_image="lobit"):(a.image="undefined"!=typeof(f=a.images).__array?"undefined"!=typeof f.__array.hibit?f.__array.hibit:f.__getitem__("hibit"):f.__getitem__("hibit"),a.mask="undefined"!=typeof(h=
a.masks).__array?"undefined"!=typeof h.__array.hibit?h.__array.hibit:h.__getitem__("hibit"):h.__getitem__("hibit"),a.current_image="hibit"),a.image_timer=2;a.move();(null===(g=a.hit())||!1===g||0===g||""===g?0:"object"==typeof g?"function"==typeof g.__nonzero__?g.__nonzero__():"function"==typeof g.__len__?0<g.__len__():1:1)&&a.kill();return null},1,[null,null,["self"]]);n.update=p;p=Array(m.engine.sprite.Sprite);var q=$p.dict(),v;for(v in n)q.__setitem__(v,n[v]);return $p._create_class("Pulse",$p.tuple(p),
q)}();return this};
