$pyjs.loaded_modules["pyjsdl.draw"]=function(A){if($pyjs.loaded_modules["pyjsdl.draw"].__was_initialized__)return $pyjs.loaded_modules["pyjsdl.draw"];"undefined"!=typeof $pyjs.loaded_modules.pyjsdl&&$pyjs.loaded_modules.pyjsdl.__was_initialized__||$p.___import___("pyjsdl",null);var q=$pyjs.loaded_modules["pyjsdl.draw"];q.__repr__=function(){return"<module: pyjsdl.draw>"};q.__was_initialized__=!0;if(null===A||"undefined"==typeof A)A="pyjsdl.draw";q.__name__=A;$pyjs.loaded_modules.pyjsdl.draw=$pyjs.loaded_modules["pyjsdl.draw"];
q.pi=$p.___import___("math.pi","pyjsdl",null,!1);q.Rect=$p.___import___("rect.Rect","pyjsdl",null,!1);q.Surface=$p.___import___("surface.Surface","pyjsdl",null,!1);q.Color=$p.___import___("color.Color","pyjsdl",null,!1);q.__docformat__="restructuredtext";q.Draw=function(){var v={},r;v.__module__="pyjsdl.draw";r=$pyjs__bind_method2("__init__",function(a){(!0===this.__is_instance__?this:a).rad_deg=180/q.pi;return null},1,[null,null,["self"]]);v.__init__=r;r=$pyjs__bind_method2("rect",function(a,f,m,
k){!0!==this.__is_instance__&&(a=arguments[1],f=arguments[2],m=arguments[3],k=arguments[4]);"undefined"==typeof k&&(k=arguments.callee.__args__[6][1]);var h,c,b,d,e,g;g=(null===(b=$p.hasattr(m,"width"))||!1===b||0===b||""===b?0:"object"==typeof b?"function"==typeof b.__nonzero__?b.__nonzero__():"function"==typeof b.__len__?0<b.__len__():1:1)?m:q.Rect(m);a.beginPath();(null===(h=k)||!1===h||0===h||""===h?0:"object"==typeof h?"function"==typeof h.__nonzero__?h.__nonzero__():"function"==typeof h.__len__?
0<h.__len__():1:1)?(a.setLineWidth(k),(null===(c=$p.hasattr(f,"a"))||!1===c||0===c||""===c?0:"object"==typeof c?"function"==typeof c.__nonzero__?c.__nonzero__():"function"==typeof c.__len__?0<c.__len__():1:1)?a.setStrokeStyle(f):a.setStrokeStyle(q.Color(f)),a.rect(g.x,g.y,g.width,g.height),a.stroke()):((null===(d=$p.hasattr(f,"a"))||!1===d||0===d||""===d?0:"object"==typeof d?"function"==typeof d.__nonzero__?d.__nonzero__():"function"==typeof d.__len__?0<d.__len__():1:1)?a.setFillStyle(f):a.setFillStyle(q.Color(f)),
a.fillRect(g.x,g.y,g.width,g.height));return(null===(e=a._display)||!1===e||0===e||""===e?0:"object"==typeof e?"function"==typeof e.__nonzero__?e.__nonzero__():"function"==typeof e.__len__?0<e.__len__():1:1)?a._display._surface_rect.clip(g):a.get_rect().clip(g)},1,[null,null,["self"],["surface"],["color"],["rect"],["width",0]]);v.rect=r;r=$pyjs__bind_method2("circle",function(a,f,m,k,h){!0!==this.__is_instance__&&(a=arguments[1],f=arguments[2],m=arguments[3],k=arguments[4],h=arguments[5]);"undefined"==
typeof h&&(h=arguments.callee.__args__[7][1]);var c,b,d,e,g,l,n,p,u,s;a.beginPath();a.arc("undefined"!=typeof(p=m).__array?"undefined"!=typeof p.__array[0]?p.__array[0]:p.__getitem__(0):p.__getitem__(0),"undefined"!=typeof(n=m).__array?"undefined"!=typeof n.__array[1]?n.__array[1]:n.__getitem__(1):n.__getitem__(1),k,0,2*q.pi,!1);(null===(c=h)||!1===c||0===c||""===c?0:"object"==typeof c?"function"==typeof c.__nonzero__?c.__nonzero__():"function"==typeof c.__len__?0<c.__len__():1:1)?(a.setLineWidth(h),
(null===(b=$p.hasattr(f,"a"))||!1===b||0===b||""===b?0:"object"==typeof b?"function"==typeof b.__nonzero__?b.__nonzero__():"function"==typeof b.__len__?0<b.__len__():1:1)?a.setStrokeStyle(f):a.setStrokeStyle(q.Color(f)),a.stroke()):((null===(g=$p.hasattr(f,"a"))||!1===g||0===g||""===g?0:"object"==typeof g?"function"==typeof g.__nonzero__?g.__nonzero__():"function"==typeof g.__len__?0<g.__len__():1:1)?a.setFillStyle(f):a.setFillStyle(q.Color(f)),a.fill());return(null===(s=a._display)||!1===s||0===
s||""===s?0:"object"==typeof s?"function"==typeof s.__nonzero__?s.__nonzero__():"function"==typeof s.__len__?0<s.__len__():1:1)?a._display._surface_rect.clip(q.Rect(("undefined"!=typeof(l=m).__array?"undefined"!=typeof l.__array[0]?l.__array[0]:l.__getitem__(0):l.__getitem__(0))-k,("undefined"!=typeof(e=m).__array?"undefined"!=typeof e.__array[1]?e.__array[1]:e.__getitem__(1):e.__getitem__(1))-k,2*k,2*k)):a.get_rect().clip(q.Rect(("undefined"!=typeof(d=m).__array?"undefined"!=typeof d.__array[0]?
d.__array[0]:d.__getitem__(0):d.__getitem__(0))-k,("undefined"!=typeof(u=m).__array?"undefined"!=typeof u.__array[1]?u.__array[1]:u.__getitem__(1):u.__getitem__(1))-k,2*k,2*k))},1,[null,null,["self"],["surface"],["color"],["position"],["radius"],["width",0]]);v.circle=r;r=$pyjs__bind_method2("ellipse",function(a,f,m,k){!0!==this.__is_instance__&&(a=arguments[1],f=arguments[2],m=arguments[3],k=arguments[4]);"undefined"==typeof k&&(k=arguments.callee.__args__[6][1]);var h,c,b,d,e,g,l,n,p;l=(null===
(e=$p.hasattr(m,"width"))||!1===e||0===e||""===e?0:"object"==typeof e?"function"==typeof e.__nonzero__?e.__nonzero__():"function"==typeof e.__len__?0<e.__len__():1:1)?m:q.Rect(m);a.saveContext();a.translate(l.x+$p.float_int(l.width/2),l.y+$p.float_int(l.height/2));(null===(h=1==(((n=l.width)===(p=l.height)?0:typeof n!=typeof p||"number"!=typeof n&&"string"!=typeof n&&"boolean"!=typeof n?$p.cmp(n,p):n==p?0:n<p?-1:1)|1))||!1===h||0===h||""===h?0:"object"==typeof h?"function"==typeof h.__nonzero__?h.__nonzero__():
"function"==typeof h.__len__?0<h.__len__():1:1)?(a.scale(l.width/l.height,1),h=l.height/2):(a.scale(1,l.height/l.width),h=l.width/2);a.beginPath();a.arc(0,0,h,0,2*q.pi,!1);(null===(c=k)||!1===c||0===c||""===c?0:"object"==typeof c?"function"==typeof c.__nonzero__?c.__nonzero__():"function"==typeof c.__len__?0<c.__len__():1:1)?(a.setLineWidth(k),(null===(g=$p.hasattr(f,"a"))||!1===g||0===g||""===g?0:"object"==typeof g?"function"==typeof g.__nonzero__?g.__nonzero__():"function"==typeof g.__len__?0<g.__len__():
1:1)?a.setStrokeStyle(f):a.setStrokeStyle(q.Color(f)),a.stroke()):((null===(b=$p.hasattr(f,"a"))||!1===b||0===b||""===b?0:"object"==typeof b?"function"==typeof b.__nonzero__?b.__nonzero__():"function"==typeof b.__len__?0<b.__len__():1:1)?a.setFillStyle(f):a.setFillStyle(q.Color(f)),a.fill());a.restoreContext();return(null===(d=a._display)||!1===d||0===d||""===d?0:"object"==typeof d?"function"==typeof d.__nonzero__?d.__nonzero__():"function"==typeof d.__len__?0<d.__len__():1:1)?a._display._surface_rect.clip(l):
a.get_rect().clip(l)},1,[null,null,["self"],["surface"],["color"],["rect"],["width",0]]);v.ellipse=r;r=$pyjs__bind_method2("arc",function(a,f,m,k,h,c){!0!==this.__is_instance__&&(a=arguments[1],f=arguments[2],m=arguments[3],k=arguments[4],h=arguments[5],c=arguments[6]);"undefined"==typeof c&&(c=arguments.callee.__args__[8][1]);var b,d,e,g,l,n,p,u,s,w,z,x,y,t,r;t=(null===(y=$p.hasattr(m,"width"))||!1===y||0===y||""===y?0:"object"==typeof y?"function"==typeof y.__nonzero__?y.__nonzero__():"function"==
typeof y.__len__?0<y.__len__():1:1)?m:q.Rect(m);(null===(e=(x=t.width)===(z=t.height)&&null===x?!0:null===x?!1:null===z?!1:"object"!=typeof x&&"function"!=typeof x||"function"!=typeof x.__cmp__?"object"!=typeof z&&"function"!=typeof z||"function"!=typeof z.__cmp__?x==z:0===z.__cmp__(x):0===x.__cmp__(z))||!1===e||0===e||""===e?0:"object"==typeof e?"function"==typeof e.__nonzero__?e.__nonzero__():"function"==typeof e.__len__?0<e.__len__():1:1)?(a.beginPath(),a.arc(t.x+$p.float_int(t.width/2),t.y+$p.float_int(t.height/
2),$p.float_int(t.width/2),-k,-h,!0),(null===(b=c)||!1===b||0===b||""===b?0:"object"==typeof b?"function"==typeof b.__nonzero__?b.__nonzero__():"function"==typeof b.__len__?0<b.__len__():1:1)?(a.setLineWidth(c),(null===(d=$p.hasattr(f,"a"))||!1===d||0===d||""===d?0:"object"==typeof d?"function"==typeof d.__nonzero__?d.__nonzero__():"function"==typeof d.__len__?0<d.__len__():1:1)?a.setStrokeStyle(f):a.setStrokeStyle(q.Color(f)),a.stroke()):(a.closePath(),(null===(p=$p.hasattr(f,"a"))||!1===p||0===
p||""===p?0:"object"==typeof p?"function"==typeof p.__nonzero__?p.__nonzero__():"function"==typeof p.__len__?0<p.__len__():1:1)?a.setFillStyle(f):a.setFillStyle(q.Color(f)),a.fill())):(b=(null===(n=-1==((r=t.width)===(w=t.height)?0:typeof r!=typeof w||"number"!=typeof r&&"string"!=typeof r&&"boolean"!=typeof r?$p.cmp(r,w):r==w?0:r<w?-1:1))||!1===n||0===n||""===n?0:"object"==typeof n?"function"==typeof n.__nonzero__?n.__nonzero__():"function"==typeof n.__len__?0<n.__len__():1:1)?t.height:t.width,n=
q.Surface($p.tuple([b,b])),n.beginPath(),w=$p.float_int(b/2),n.arc(w,w,w,-k,-h,!0),(null===(u=c)||!1===u||0===u||""===u?0:"object"==typeof u?"function"==typeof u.__nonzero__?u.__nonzero__():"function"==typeof u.__len__?0<u.__len__():1:1)?(n.setLineWidth(c),(null===(s=$p.hasattr(f,"a"))||!1===s||0===s||""===s?0:"object"==typeof s?"function"==typeof s.__nonzero__?s.__nonzero__():"function"==typeof s.__len__?0<s.__len__():1:1)?a.setStrokeStyle(f):a.setStrokeStyle(q.Color(f)),n.stroke()):(a.closePath(),
(null===(g=$p.hasattr(f,"a"))||!1===g||0===g||""===g?0:"object"==typeof g?"function"==typeof g.__nonzero__?g.__nonzero__():"function"==typeof g.__len__?0<g.__len__():1:1)?a.setFillStyle(f):a.setFillStyle(q.Color(f)),n.fill()),a.drawImage(n.canvas,0,0,b,b,t.x,t.y,t.width,t.height));return(null===(l=a._display)||!1===l||0===l||""===l?0:"object"==typeof l?"function"==typeof l.__nonzero__?l.__nonzero__():"function"==typeof l.__len__?0<l.__len__():1:1)?a._display._surface_rect.clip(t):a.get_rect().clip(t)},
1,[null,null,["self"],["surface"],["color"],["rect"],["start_angle"],["stop_angle"],["width",1]]);v.arc=r;r=$pyjs__bind_method2("polygon",function(a,f,m,k){!0!==this.__is_instance__&&(a=arguments[1],f=arguments[2],m=arguments[3],k=arguments[4]);"undefined"==typeof k&&(k=arguments.callee.__args__[6][1]);var h,c,b,d,e,g,l,n,p;a.beginPath();$pyjs_kwargs_call(a,"moveTo","undefined"!=typeof(c=m).__array?"undefined"!=typeof c.__array[0]?c.__array[0]:c.__getitem__(0):c.__getitem__(0),null,[{}]);c=$p.__getslice(m,
1,null);"undefined"!=typeof(g=c.__array)?n=0:(c=c.__iter__(),n="undefined"!=typeof(g=c.__array)?0:"function"==typeof c.$genfunc?1:-1);for(p=0;"undefined"!=typeof(h=n?0<n?c.next(!0,!1):$p.wrapped_next(c):g[p++]);)$pyjs_kwargs_call(a,"lineTo",h,null,[{}]);a.closePath();(null===(e=k)||!1===e||0===e||""===e?0:"object"==typeof e?"function"==typeof e.__nonzero__?e.__nonzero__():"function"==typeof e.__len__?0<e.__len__():1:1)?(a.setLineWidth(k),(null===(b=$p.hasattr(f,"a"))||!1===b||0===b||""===b?0:"object"==
typeof b?"function"==typeof b.__nonzero__?b.__nonzero__():"function"==typeof b.__len__?0<b.__len__():1:1)?a.setStrokeStyle(f):a.setStrokeStyle(q.Color(f)),a.stroke()):((null===(d=$p.hasattr(f,"a"))||!1===d||0===d||""===d?0:"object"==typeof d?"function"==typeof d.__nonzero__?d.__nonzero__():"function"==typeof d.__len__?0<d.__len__():1:1)?a.setFillStyle(f):a.setFillStyle(q.Color(f)),a.fill());b=function(){var a,b,d,c,e,g,f;e=$p.list();c=m;"undefined"!=typeof(f=c.__array)?d=0:(c=c.__iter__(),d="undefined"!=
typeof(f=c.__array)?0:"function"==typeof c.$genfunc?1:-1);for(g=0;"undefined"!=typeof(b=d?0<d?c.next(!0,!1):$p.wrapped_next(c):f[g++]);)e.append("undefined"!=typeof(a=b).__array?"undefined"!=typeof a.__array[0]?a.__array[0]:a.__getitem__(0):a.__getitem__(0));return e}();d=function(){var a,c,b,d,e,g,f;d=$p.list();g=m;"undefined"!=typeof(b=g.__array)?f=0:(g=g.__iter__(),f="undefined"!=typeof(b=g.__array)?0:"function"==typeof g.$genfunc?1:-1);for(a=0;"undefined"!=typeof(c=f?0<f?g.next(!0,!1):$p.wrapped_next(g):
b[a++]);)d.append("undefined"!=typeof(e=c).__array?"undefined"!=typeof e.__array[1]?e.__array[1]:e.__getitem__(1):e.__getitem__(1));return d}();e=$p.__ass_unpack($p.tuple([$p.min(b),$p.max(b)]),2,null);b=e[0];e=e[1];c=$p.__ass_unpack($p.tuple([$p.min(d),$p.max(d)]),2,null);d=c[0];c=c[1];return(null===(l=a._display)||!1===l||0===l||""===l?0:"object"==typeof l?"function"==typeof l.__nonzero__?l.__nonzero__():"function"==typeof l.__len__?0<l.__len__():1:1)?a._display._surface_rect.clip(q.Rect(b,d,e-
b+1,c-d+1)):a.get_rect().clip(q.Rect(b,d,e-b+1,c-d+1))},1,[null,null,["self"],["surface"],["color"],["pointlist"],["width",0]]);v.polygon=r;r=$pyjs__bind_method2("line",function(a,f,m,k,h){!0!==this.__is_instance__&&(a=arguments[1],f=arguments[2],m=arguments[3],k=arguments[4],h=arguments[5]);"undefined"==typeof h&&(h=arguments.callee.__args__[7][1]);var c,b,d,e,g;a.beginPath();$pyjs_kwargs_call(a,"moveTo",m,null,[{}]);$pyjs_kwargs_call(a,"lineTo",k,null,[{}]);a.setLineWidth(h);(null===(c=$p.hasattr(f,
"a"))||!1===c||0===c||""===c?0:"object"==typeof c?"function"==typeof c.__nonzero__?c.__nonzero__():"function"==typeof c.__len__?0<c.__len__():1:1)?a.setStrokeStyle(f):a.setStrokeStyle(q.Color(f));a.stroke();c=function(){var a,c,b,d,e,g,f;c=$p.list();f=$p.tuple([m,k]);"undefined"!=typeof(g=f.__array)?e=0:(f=f.__iter__(),e="undefined"!=typeof(g=f.__array)?0:"function"==typeof f.$genfunc?1:-1);for(d=0;"undefined"!=typeof(a=e?0<e?f.next(!0,!1):$p.wrapped_next(f):g[d++]);)c.append("undefined"!=typeof(b=
a).__array?"undefined"!=typeof b.__array[0]?b.__array[0]:b.__getitem__(0):b.__getitem__(0));return c}();g=function(){var a,b,c,d,e,g,f;d=$p.list();e=$p.tuple([m,k]);"undefined"!=typeof(g=e.__array)?f=0:(e=e.__iter__(),f="undefined"!=typeof(g=e.__array)?0:"function"==typeof e.$genfunc?1:-1);for(c=0;"undefined"!=typeof(a=f?0<f?e.next(!0,!1):$p.wrapped_next(e):g[c++]);)d.append("undefined"!=typeof(b=a).__array?"undefined"!=typeof b.__array[1]?b.__array[1]:b.__getitem__(1):b.__getitem__(1));return d}();
e=$p.__ass_unpack($p.tuple([$p.min(c),$p.max(c)]),2,null);c=e[0];e=e[1];b=$p.__ass_unpack($p.tuple([$p.min(g),$p.max(g)]),2,null);g=b[0];b=b[1];return(null===(d=a._display)||!1===d||0===d||""===d?0:"object"==typeof d?"function"==typeof d.__nonzero__?d.__nonzero__():"function"==typeof d.__len__?0<d.__len__():1:1)?a._display._surface_rect.clip(q.Rect(c,g,e-c+1,b-g+1)):a.get_rect().clip(q.Rect(c,g,e-c+1,b-g+1))},1,[null,null,["self"],["surface"],["color"],["point1"],["point2"],["width",1]]);v.line=r;
r=$pyjs__bind_method2("lines",function(a,f,m,k,h){!0!==this.__is_instance__&&(a=arguments[1],f=arguments[2],m=arguments[3],k=arguments[4],h=arguments[5]);"undefined"==typeof h&&(h=arguments.callee.__args__[7][1]);var c,b,d,e,g,l,n,p;a.beginPath();$pyjs_kwargs_call(a,"moveTo","undefined"!=typeof(d=k).__array?"undefined"!=typeof d.__array[0]?d.__array[0]:d.__getitem__(0):d.__getitem__(0),null,[{}]);d=$p.__getslice(k,1,null);"undefined"!=typeof(n=d.__array)?e=0:(d=d.__iter__(),e="undefined"!=typeof(n=
d.__array)?0:"function"==typeof d.$genfunc?1:-1);for(l=0;"undefined"!=typeof(c=e?0<e?d.next(!0,!1):$p.wrapped_next(d):n[l++]);)$pyjs_kwargs_call(a,"lineTo",c,null,[{}]);(null===(b=m)||!1===b||0===b||""===b?0:"object"==typeof b?"function"==typeof b.__nonzero__?b.__nonzero__():"function"==typeof b.__len__?0<b.__len__():1:1)&&a.closePath();a.setLineWidth(h);(null===(p=$p.hasattr(f,"a"))||!1===p||0===p||""===p?0:"object"==typeof p?"function"==typeof p.__nonzero__?p.__nonzero__():"function"==typeof p.__len__?
0<p.__len__():1:1)?a.setStrokeStyle(f):a.setStrokeStyle(q.Color(f));a.stroke();b=function(){var a,b,c,d,e,f,g;c=$p.list();b=k;"undefined"!=typeof(d=b.__array)?g=0:(b=b.__iter__(),g="undefined"!=typeof(d=b.__array)?0:"function"==typeof b.$genfunc?1:-1);for(f=0;"undefined"!=typeof(a=g?0<g?b.next(!0,!1):$p.wrapped_next(b):d[f++]);)c.append("undefined"!=typeof(e=a).__array?"undefined"!=typeof e.__array[0]?e.__array[0]:e.__getitem__(0):e.__getitem__(0));return c}();d=function(){var a,b,c,d,e,g,f;c=$p.list();
f=k;"undefined"!=typeof(e=f.__array)?d=0:(f=f.__iter__(),d="undefined"!=typeof(e=f.__array)?0:"function"==typeof f.$genfunc?1:-1);for(a=0;"undefined"!=typeof(b=d?0<d?f.next(!0,!1):$p.wrapped_next(f):e[a++]);)c.append("undefined"!=typeof(g=b).__array?"undefined"!=typeof g.__array[1]?g.__array[1]:g.__getitem__(1):g.__getitem__(1));return c}();p=$p.__ass_unpack($p.tuple([$p.min(b),$p.max(b)]),2,null);b=p[0];p=p[1];e=$p.__ass_unpack($p.tuple([$p.min(d),$p.max(d)]),2,null);d=e[0];e=e[1];return(null===
(g=a._display)||!1===g||0===g||""===g?0:"object"==typeof g?"function"==typeof g.__nonzero__?g.__nonzero__():"function"==typeof g.__len__?0<g.__len__():1:1)?a._display._surface_rect.clip(q.Rect(b,d,p-b+1,e-d+1)):a.get_rect().clip(q.Rect(b,d,p-b+1,e-d+1))},1,[null,null,["self"],["surface"],["color"],["closed"],["pointlist"],["width",1]]);v.lines=r;r=$pyjs__bind_method2("aaline",function(a,f,m,k,h){if(!0===this.__is_instance__)var c=this;else c=arguments[0],a=arguments[1],f=arguments[2],m=arguments[3],
k=arguments[4],h=arguments[5];"undefined"==typeof h&&(h=arguments.callee.__args__[7][1]);return c.line(a,f,m,k,h)},1,[null,null,["self"],["surface"],["color"],["point1"],["point2"],["blend",1]]);v.aaline=r;r=$pyjs__bind_method2("aalines",function(a,f,m,k,h){if(!0===this.__is_instance__)var c=this;else c=arguments[0],a=arguments[1],f=arguments[2],m=arguments[3],k=arguments[4],h=arguments[5];"undefined"==typeof h&&(h=arguments.callee.__args__[7][1]);return c.lines(a,f,m,k,h)},1,[null,null,["self"],
["surface"],["color"],["closed"],["pointlist"],["blend",1]]);v.aalines=r;r=Array($p.object);var A=$p.dict(),B;for(B in v)A.__setitem__(B,v[B]);return $p._create_class("Draw",$p.tuple(r),A)}();return this};
