$pyjs.loaded_modules.spike=function(e){if($pyjs.loaded_modules.spike.__was_initialized__)return $pyjs.loaded_modules.spike;var a=$pyjs.loaded_modules.spike;a.__repr__=function(){return"<module: spike>"};a.__was_initialized__=!0;if(null===e||"undefined"==typeof e)e="spike";a.__name__=e;a.env=$p.___import___("env",null);a.engine=a.env.engine;a.Surge=$p.___import___("surge.Surge",null,null,!1);a.Spike=function(){var g={},k;g.__module__="spike";k=$pyjs__bind_method2("__init__",function(m,e,n,h){if(!0===
this.__is_instance__)var c=this;else c=m,m=e,e=n,n=h;var b,d,f,k,g,l;if(null===(b=!(null===(d=c.images)||!1===d||0===d||""===d?0:"object"==typeof d?"function"==typeof d.__nonzero__?d.__nonzero__():"function"==typeof d.__len__?0<d.__len__():1:1))||!1===b||0===b||""===b?0:"object"==typeof b?"function"==typeof b.__nonzero__?b.__nonzero__():"function"==typeof b.__len__?0<b.__len__():1:1){c.images=$p.dict([]);d=$p.tuple([200,0,0]);k=$p.tuple([100,0,0]);h=a.engine.Surface($p.tuple([22,22]),a.engine.SRCALPHA);
b=function(){var b,a,d,c,h,f,e,g;d=$p.list();c=$p.list([$p.tuple([5,0]),$p.tuple([9,1]),$p.tuple([10,5]),$p.tuple([9,9]),$p.tuple([5,10]),$p.tuple([1,9]),$p.tuple([0,5]),$p.tuple([1,1])]);"undefined"!=typeof(g=c.__array)?a=0:(c=c.__iter__(),a="undefined"!=typeof(g=c.__array)?0:"function"==typeof c.$genfunc?1:-1);for(h=0;"undefined"!=typeof(b=a?0<a?c.next(!0,!1):$p.wrapped_next(c):g[h++]);)d.append($p.tuple([2*("undefined"!=typeof(f=b).__array?"undefined"!=typeof f.__array[0]?f.__array[0]:f.__getitem__(0):
f.__getitem__(0)),2*("undefined"!=typeof(e=b).__array?"undefined"!=typeof e.__array[1]?e.__array[1]:e.__getitem__(1):e.__getitem__(1))]));return d}();a.engine.draw.polygon(h,d,b,0);a.engine.draw.polygon(h,d,b,1);c.images.__setitem__("hibit",h);h=a.engine.Surface($p.tuple([22,22]),a.engine.SRCALPHA);b=function(){var c,b,a,d,h,f,e,g;d=$p.list();a=$p.list([$p.tuple([5,2]),$p.tuple([7,3]),$p.tuple([8,5]),$p.tuple([7,7]),$p.tuple([5,8]),$p.tuple([3,7]),$p.tuple([2,5]),$p.tuple([3,3])]);"undefined"!=typeof(g=
a.__array)?b=0:(a=a.__iter__(),b="undefined"!=typeof(g=a.__array)?0:"function"==typeof a.$genfunc?1:-1);for(h=0;"undefined"!=typeof(c=b?0<b?a.next(!0,!1):$p.wrapped_next(a):g[h++]);)d.append($p.tuple([2*("undefined"!=typeof(e=c).__array?"undefined"!=typeof e.__array[0]?e.__array[0]:e.__getitem__(0):e.__getitem__(0)),2*("undefined"!=typeof(f=c).__array?"undefined"!=typeof f.__array[1]?f.__array[1]:f.__getitem__(1):f.__getitem__(1))]));return d}();a.engine.draw.polygon(h,k,b,0);a.engine.draw.polygon(h,
k,b,1);c.images.__setitem__("lobit",h);if(null===(f=null===c.masks)||!1===f||0===f||""===f?0:"object"==typeof f?"function"==typeof f.__nonzero__?f.__nonzero__():"function"==typeof f.__len__?0<f.__len__():1:1)c.masks=$p.dict([]);c.masks.__setitem__("hibit",a.engine.mask.from_surface("undefined"!=typeof(g=c.images).__array?"undefined"!=typeof g.__array.hibit?g.__array.hibit:g.__getitem__("hibit"):g.__getitem__("hibit")));c.masks.__setitem__("lobit",a.engine.mask.from_surface("undefined"!=typeof(l=c.images).__array?
"undefined"!=typeof l.__array.lobit?l.__array.lobit:l.__getitem__("lobit"):l.__getitem__("lobit")));c.radius=Math.floor(h.get_width()/2)}a.Surge.__init__(c,m,e,n);c.level=0.5;return null},1,[null,null,["self"],["matrix"],["x"],["y"]]);g.__init__=k;k=$pyjs__bind_method2("hit",function(e){e=!0===this.__is_instance__?this:e;var g,k,h,c,b,d,f;b=e.targets;"undefined"!=typeof(f=b.__array)?c=0:(b=b.__iter__(),c="undefined"!=typeof(f=b.__array)?0:"function"==typeof b.$genfunc?1:-1);for(g=0;"undefined"!=typeof(k=
c?0<c?b.next(!0,!1):$p.wrapped_next(b):f[g++]);)if(k=a.engine.sprite.spritecollide(e,k,!1,a.engine.sprite.collide_mask),null===(d=k)||!1===d||0===d||""===d?0:"object"==typeof d?"function"==typeof d.__nonzero__?d.__nonzero__():"function"==typeof d.__len__?0<d.__len__():1:1)return("undefined"!=typeof(h=k).__array?"undefined"!=typeof h.__array[0]?h.__array[0]:h.__getitem__(0):h.__getitem__(0)).energy_spike(e.level),!0;return!1},1,[null,null,["self"]]);g.hit=k;k=Array(a.Surge);var e=$p.dict(),p;for(p in g)e.__setitem__(p,
g[p]);return $p._create_class("Spike",$p.tuple(k),e)}();return this};
