$pyjs.loaded_modules.surge=function(f){if($pyjs.loaded_modules.surge.__was_initialized__)return $pyjs.loaded_modules.surge;var b=$pyjs.loaded_modules.surge;b.__repr__=function(){return"<module: surge>"};b.__was_initialized__=!0;if(null===f||"undefined"==typeof f)f="surge";b.__name__=f;b.env=$p.___import___("env",null);b.engine=b.env.engine;b.Pulse=$p.___import___("pulse.Pulse",null,null,!1);b.Surge=function(){var g={},d;g.__module__="surge";d=$pyjs__bind_method2("__init__",function(m,f,n,k){if(!0===
this.__is_instance__)var c=this;else c=m,m=f,f=n,n=k;var a,e,h,d,g,l;k=$p.list([m.avatars]);if(null===(a=!(null===(e=c.images)||!1===e||0===e||""===e?0:"object"==typeof e?"function"==typeof e.__nonzero__?e.__nonzero__():"function"==typeof e.__len__?0<e.__len__():1:1))||!1===a||0===a||""===a?0:"object"==typeof a?"function"==typeof a.__nonzero__?a.__nonzero__():"function"==typeof a.__len__?0<a.__len__():1:1){c.images=$p.dict([]);a=$p.tuple([100,100,200]);e=b.engine.Surface($p.tuple([22,22]),b.engine.SRCALPHA);
l=function(){var a,b,e,c,h,d,f,g;e=$p.list();c=$p.list([$p.tuple([5,0]),$p.tuple([9,1]),$p.tuple([10,5]),$p.tuple([9,9]),$p.tuple([5,10]),$p.tuple([1,9]),$p.tuple([0,5]),$p.tuple([1,1])]);"undefined"!=typeof(g=c.__array)?b=0:(c=c.__iter__(),b="undefined"!=typeof(g=c.__array)?0:"function"==typeof c.$genfunc?1:-1);for(h=0;"undefined"!=typeof(a=b?0<b?c.next(!0,!1):$p.wrapped_next(c):g[h++]);)e.append($p.tuple([2*("undefined"!=typeof(d=a).__array?"undefined"!=typeof d.__array[0]?d.__array[0]:d.__getitem__(0):
d.__getitem__(0)),2*("undefined"!=typeof(f=a).__array?"undefined"!=typeof f.__array[1]?f.__array[1]:f.__getitem__(1):f.__getitem__(1))]));return e}();b.engine.draw.polygon(e,a,l,0);b.engine.draw.polygon(e,a,l,1);c.images.__setitem__("hibit",e);e=b.engine.Surface($p.tuple([22,22]),b.engine.SRCALPHA);l=function(){var c,b,a,e,h,d,f,g;e=$p.list();a=$p.list([$p.tuple([5,2]),$p.tuple([7,3]),$p.tuple([8,5]),$p.tuple([7,7]),$p.tuple([5,8]),$p.tuple([3,7]),$p.tuple([2,5]),$p.tuple([3,3])]);"undefined"!=typeof(g=
a.__array)?b=0:(a=a.__iter__(),b="undefined"!=typeof(g=a.__array)?0:"function"==typeof a.$genfunc?1:-1);for(h=0;"undefined"!=typeof(c=b?0<b?a.next(!0,!1):$p.wrapped_next(a):g[h++]);)e.append($p.tuple([2*("undefined"!=typeof(f=c).__array?"undefined"!=typeof f.__array[0]?f.__array[0]:f.__getitem__(0):f.__getitem__(0)),2*("undefined"!=typeof(d=c).__array?"undefined"!=typeof d.__array[1]?d.__array[1]:d.__getitem__(1):d.__getitem__(1))]));return e}();b.engine.draw.polygon(e,a,l,0);b.engine.draw.polygon(e,
a,l,1);c.images.__setitem__("lobit",e);if(null===(h=null===c.masks)||!1===h||0===h||""===h?0:"object"==typeof h?"function"==typeof h.__nonzero__?h.__nonzero__():"function"==typeof h.__len__?0<h.__len__():1:1)c.masks=$p.dict([]);c.masks.__setitem__("hibit",b.engine.mask.from_surface("undefined"!=typeof(d=c.images).__array?"undefined"!=typeof d.__array.hibit?d.__array.hibit:d.__getitem__("hibit"):d.__getitem__("hibit")));c.masks.__setitem__("lobit",b.engine.mask.from_surface("undefined"!=typeof(g=c.images).__array?
"undefined"!=typeof g.__array.lobit?g.__array.lobit:g.__getitem__("lobit"):g.__getitem__("lobit")));c.radius=Math.floor(e.get_width()/2)}b.Pulse.__init__(c,m,f,n,"d",k);c.level=0.5;return null},1,[null,null,["self"],["matrix"],["x"],["y"]]);g.__init__=d;d=$pyjs__bind_method2("hit",function(d){d=!0===this.__is_instance__?this:d;var f,g,k,c,a,e,h;a=d.targets;"undefined"!=typeof(e=a.__array)?c=0:(a=a.__iter__(),c="undefined"!=typeof(e=a.__array)?0:"function"==typeof a.$genfunc?1:-1);for(f=0;"undefined"!=
typeof(g=c?0<c?a.next(!0,!1):$p.wrapped_next(a):e[f++]);)if(g=b.engine.sprite.spritecollide(d,g,!1,b.engine.sprite.collide_mask),null===(h=g)||!1===h||0===h||""===h?0:"object"==typeof h?"function"==typeof h.__nonzero__?h.__nonzero__():"function"==typeof h.__len__?0<h.__len__():1:1)return("undefined"!=typeof(k=g).__array?"undefined"!=typeof k.__array[0]?k.__array[0]:k.__getitem__(0):k.__getitem__(0)).energy_surge(d.level),!0;return!1},1,[null,null,["self"]]);g.hit=d;d=Array(b.Pulse);var f=$p.dict(),
p;for(p in g)f.__setitem__(p,g[p]);return $p._create_class("Surge",$p.tuple(d),f)}();return this};
