$pyjs.loaded_modules.util=function(n){if($pyjs.loaded_modules.util.__was_initialized__)return $pyjs.loaded_modules.util;var b=$pyjs.loaded_modules.util;b.__repr__=function(){return"<module: util>"};b.__was_initialized__=!0;if(null===n||"undefined"==typeof n)n="util";b.__name__=n;var g,h;b.os=$p.___import___("os",null);b.env=$p.___import___("env",null);b.engine=b.env.engine;try{b.Timer=$p.___import___("threading.Timer",null,null,!1)}catch(p){if(n="undefined"==typeof p.__name__?p.name:p.__name__,$pyjs.__last_exception__=
{error:p,module:b},n!=$p.ImportError.__name__&&!$p._isinstance(p,$p.ImportError))throw $pyjs.__active_exception_stack__=$pyjs.__last_exception_stack__,$pyjs.__last_exception_stack__=null,p;}b.load_image=function(c){c=b.os.path.join("data",c);return b.engine.image.load(c)};b.load_image.__name__="load_image";b.load_image.__bind_type__=0;b.load_image.__args__=[null,null,["file_name"]];b.load_sound=function(c){var a,f,d,e,k,l,m,g,h;b.No_Sound=function(){var b={},e;b.__module__="util";e=$pyjs__bind_method2("play",
function(b){return null},1,[null,null,["self"]]);b.play=e;e=Array(pyjslib.object);var k=$p.dict(),a;for(a in b)k.__setitem__(a,b[a]);return $p._create_class("No_Sound",$p.tuple(e),k)}();if(null===(m=(null===(d=f=!(null===(k=b.engine.mixer)||!1===k||0===k||""===k?0:"object"==typeof k?"function"==typeof k.__nonzero__?k.__nonzero__():"function"==typeof k.__len__?0<k.__len__():1:1))||!1===d||0===d||""===d?0:"object"==typeof d?"function"==typeof d.__nonzero__?d.__nonzero__():"function"==typeof d.__len__?
0<d.__len__():1:1)?f:!(null===(e=b.engine.mixer.get_init())||!1===e||0===e||""===e?0:"object"==typeof e?"function"==typeof e.__nonzero__?e.__nonzero__():"function"==typeof e.__len__?0<e.__len__():1:1))||!1===m||0===m||""===m?0:"object"==typeof m?"function"==typeof m.__nonzero__?m.__nonzero__():"function"==typeof m.__len__?0<m.__len__():1:1)return b.No_Sound();c=b.os.path.join("data",c);if(null===(g=!("js"===(a=b.env.platform)&&null===a||(null===a?0:"object"!=typeof a&&"function"!=typeof a||"function"!=
typeof a.__cmp__?"js"==a:0===a.__cmp__("js"))))||!1===g||0===g||""===g?0:"object"==typeof g?"function"==typeof g.__nonzero__?g.__nonzero__():"function"==typeof g.__len__?0<g.__len__():1:1)if(null===(l=b.os.path.exists(c))||!1===l||0===l||""===l?0:"object"==typeof l?"function"==typeof l.__nonzero__?l.__nonzero__():"function"==typeof l.__len__?0<l.__len__():1:1)a=b.engine.mixer.Sound(c);else return b.No_Sound;else a=b.engine.mixer.Sound(("undefined"!=typeof(h=c.$$split(".")).__array?"undefined"!=typeof h.__array[0]?
h.__array[0]:h.__getitem__(0):h.__getitem__(0))+".mp3");return a};b.load_sound.__name__="load_sound";b.load_sound.__bind_type__=0;b.load_sound.__args__=[null,null,["file_name"]];b.timers=$p.dict([]);b.EventTimer=function(){var c={},a;c.__module__="util";a=$pyjs__bind_method2("__init__",function(b,a,c){if(!0===this.__is_instance__)var d=this;else d=b,b=a,a=c;d.eventid=b;d.time=a;d.timer=null;d.repeat=!0;return null},1,[null,null,["self"],["eventid"],["time"]]);c.__init__=a;a=$pyjs__bind_method2("run",
function(e){e=!0===this.__is_instance__?this:e;var a;b.engine.event.post(b.engine.event.Event(e.eventid));(null===(a=e.repeat)||!1===a||0===a||""===a?0:"object"==typeof a?"function"==typeof a.__nonzero__?a.__nonzero__():"function"==typeof a.__len__?0<a.__len__():1:1)&&e.start();return null},1,[null,null,["self"]]);c.run=a;a=$pyjs__bind_method2("start",function(a){a=!0===this.__is_instance__?this:a;a.repeat=!0;a.timer=b.Timer(a.time/1E3,a.run,$p.list([]));a.timer.start();return null},1,[null,null,
["self"]]);c.start=a;a=$pyjs__bind_method2("cancel",function(a){a=!0===this.__is_instance__?this:a;var b;if(null===(b=a.timer)||!1===b||0===b||""===b?0:"object"==typeof b?"function"==typeof b.__nonzero__?b.__nonzero__():"function"==typeof b.__len__?0<b.__len__():1:1)a.timer.cancel(),a.timer=null;a.repeat=!1;return null},1,[null,null,["self"]]);c.cancel=a;a=Array(pyjslib.object);var f=$p.dict(),d;for(d in c)f.__setitem__(d,c[d]);return $p._create_class("EventTimer",$p.tuple(a),f)}();b.set_timer=function(c,
a){var f,d,e;(null===(d=!b.timers.__contains__(c))||!1===d||0===d||""===d?0:"object"==typeof d?"function"==typeof d.__nonzero__?d.__nonzero__():"function"==typeof d.__len__?0<d.__len__():1:1)&&b.timers.__setitem__(c,b.EventTimer(c,a));(null===a||!1===a||0===a||""===a?0:"object"==typeof a?"function"==typeof a.__nonzero__?a.__nonzero__():"function"==typeof a.__len__?0<a.__len__():1:1)?("undefined"!=typeof(e=b.timers).__array?"undefined"!=typeof e.__array[c]?e.__array[c]:e.__getitem__(c):e.__getitem__(c)).start():
("undefined"!=typeof(f=b.timers).__array?"undefined"!=typeof f.__array[c]?f.__array[c]:f.__getitem__(c):f.__getitem__(c)).cancel();return null};b.set_timer.__name__="set_timer";b.set_timer.__bind_type__=0;b.set_timer.__args__=[null,null,["eventid"],["milliseconds"]];b.EventTimerJS=function(){var c={},a;c.__module__="util";a=$pyjs__bind_method2("__init__",function(a,b,c){if(!0===this.__is_instance__)var d=this;else d=a,a=b,b=c;d.eventid=a;d.time=b;d.repeat=!0;return null},1,[null,null,["self"],["eventid"],
["time"]]);c.__init__=a;a=$pyjs__bind_method2("run",function(a){a=!0===this.__is_instance__?this:a;var c;b.engine.event.post(b.engine.event.Event(a.eventid));(null===(c=a.repeat)||!1===c||0===c||""===c?0:"object"==typeof c?"function"==typeof c.__nonzero__?c.__nonzero__():"function"==typeof c.__len__?0<c.__len__():1:1)&&a.start();return null},1,[null,null,["self"]]);c.run=a;a=$pyjs__bind_method2("start",function(a){a=!0===this.__is_instance__?this:a;a.repeat=!0;b.engine.time.timeout(a.time,a);return null},
1,[null,null,["self"]]);c.start=a;a=$pyjs__bind_method2("cancel",function(a){(!0===this.__is_instance__?this:a).repeat=!1;return null},1,[null,null,["self"]]);c.cancel=a;a=Array(pyjslib.object);var f=$p.dict(),d;for(d in c)f.__setitem__(d,c[d]);return $p._create_class("EventTimerJS",$p.tuple(a),f)}();b.set_timer_js=function(c,a){var f,d;(null===(d=!b.timers.__contains__(c))||!1===d||0===d||""===d?0:"object"==typeof d?"function"==typeof d.__nonzero__?d.__nonzero__():"function"==typeof d.__len__?0<
d.__len__():1:1)&&b.timers.__setitem__(c,b.EventTimerJS(c,a));("undefined"!=typeof(f=b.timers).__array?"undefined"!=typeof f.__array[c]?f.__array[c]:f.__getitem__(c):f.__getitem__(c)).start();return null};b.set_timer_js.__name__="set_timer_js";b.set_timer_js.__bind_type__=0;b.set_timer_js.__args__=[null,null,["eventid"],["milliseconds"]];if(null===(g="js"===(h=b.env.platform)&&null===h?!0:null===h?!1:"object"!=typeof h&&"function"!=typeof h||"function"!=typeof h.__cmp__?"js"==h:0===h.__cmp__("js"))||
!1===g||0===g||""===g?0:"object"==typeof g?"function"==typeof g.__nonzero__?g.__nonzero__():"function"==typeof g.__len__?0<g.__len__():1:1)b.set_timer=b.set_timer_js;return this};
