$pyjs.loaded_modules.GradientDemo=function(h){if($pyjs.loaded_modules.GradientDemo.__was_initialized__)return $pyjs.loaded_modules.GradientDemo;var a=$pyjs.loaded_modules.GradientDemo;a.__repr__=function(){return"<module: GradientDemo>"};a.__was_initialized__=!0;if(null===h||"undefined"==typeof h)h="GradientDemo";a.__name__=h;a.__track_lines__=[];try{a.__track_lines__[1]='GradientDemo.py, line 1:\n    """';a.__track_lines__[20]="GradientDemo.py, line 20:\n    from pyjamas.ui.Composite import Composite";
a.__track_lines__[21]="GradientDemo.py, line 21:\n    from pyjamas.ui.HTML import HTML";a.__track_lines__[22]="GradientDemo.py, line 22:\n    from pyjamas.ui.VerticalPanel import VerticalPanel";a.__track_lines__[24]="GradientDemo.py, line 24:\n    from pyjamas.Canvas.Color import Color";a.__track_lines__[26]="GradientDemo.py, line 26:\n    from SimpleCanvasDemo import SimpleCanvasDemo";a.__track_lines__[28]="GradientDemo.py, line 28:\n    class GradientDemoControls (Composite):";a.__track_lines__[29]=
"GradientDemo.py, line 29:\n    def __init__(self):";a.__track_lines__[30]="GradientDemo.py, line 30:\n    layout = VerticalPanel()";a.__track_lines__[31]="GradientDemo.py, line 31:\n    layout.add(HTML(";a.__track_lines__[33]="GradientDemo.py, line 33:\n    Composite.__init__(self, layout)";a.__track_lines__[37]='GradientDemo.py, line 37:\n    """*';a.__track_lines__[40]="GradientDemo.py, line 40:\n    class GradientDemo (SimpleCanvasDemo):";a.__track_lines__[42]="GradientDemo.py, line 42:\n    def __init__(self, theCanvas):";
a.__track_lines__[43]="GradientDemo.py, line 43:\n    SimpleCanvasDemo.__init__(self, theCanvas)";a.__track_lines__[45]="GradientDemo.py, line 45:\n    self.width = 400";a.__track_lines__[46]="GradientDemo.py, line 46:\n    self.height = 400";a.__track_lines__[47]='GradientDemo.py, line 47:\n    self.demoName = "Gradients"';a.__track_lines__[50]="GradientDemo.py, line 50:\n    def createControls(self):";a.__track_lines__[51]="GradientDemo.py, line 51:\n    self.controls = GradientDemoControls()";
a.__track_lines__[54]="GradientDemo.py, line 54:\n    def drawDemo(self):";a.__track_lines__[55]="GradientDemo.py, line 55:\n    self.canvas.resize(self.width, self.height)";a.__track_lines__[59]="GradientDemo.py, line 59:\n    self.canvas.saveContext()";a.__track_lines__[62]="GradientDemo.py, line 62:\n    lingrad = self.canvas.createLinearGradient(0, 0, 0, 150)";a.__track_lines__[63]='GradientDemo.py, line 63:\n    lingrad.addColorStop(0.0, Color("#00ABEB"))';a.__track_lines__[64]='GradientDemo.py, line 64:\n    lingrad.addColorStop(0.5, Color("#fff"))';
a.__track_lines__[65]='GradientDemo.py, line 65:\n    lingrad.addColorStop(0.5, Color("#26C000"))';a.__track_lines__[66]='GradientDemo.py, line 66:\n    lingrad.addColorStop(1, Color("#fff"))';a.__track_lines__[68]="GradientDemo.py, line 68:\n    lingrad2 = self.canvas.createLinearGradient(0, 50, 0, 95)";a.__track_lines__[69]='GradientDemo.py, line 69:\n    lingrad2.addColorStop(0.5, Color("#000"))';a.__track_lines__[70]='GradientDemo.py, line 70:\n    lingrad2.addColorStop(1, Color("rgba(0,0,0,0)"))';
a.__track_lines__[73]="GradientDemo.py, line 73:\n    self.canvas.setFillStyle(lingrad)";a.__track_lines__[74]="GradientDemo.py, line 74:\n    self.canvas.setStrokeStyle(lingrad2)";a.__track_lines__[77]="GradientDemo.py, line 77:\n    self.canvas.fillRect(10, 10, 130, 130)";a.__track_lines__[78]="GradientDemo.py, line 78:\n    self.canvas.strokeRect(50, 50, 50, 50)";a.__track_lines__[80]="GradientDemo.py, line 80:\n    self.canvas.restoreContext()";a.__track_lines__[84]="GradientDemo.py, line 84:\n    self.canvas.saveContext()";
a.__track_lines__[85]="GradientDemo.py, line 85:\n    self.canvas.translate(150, 150)";a.__track_lines__[87]="GradientDemo.py, line 87:\n    radgrad = self.canvas.createRadialGradient(45, 45, 10, 52, 50, 30)";a.__track_lines__[88]='GradientDemo.py, line 88:\n    radgrad.addColorStop(0, Color("#A7D30C"))';a.__track_lines__[89]='GradientDemo.py, line 89:\n    radgrad.addColorStop(0.9, Color("#019F62"))';a.__track_lines__[90]='GradientDemo.py, line 90:\n    radgrad.addColorStop(1, Color("rgba(1,159,98,0)"))';
a.__track_lines__[92]="GradientDemo.py, line 92:\n    radgrad2 = self.canvas.createRadialGradient(105, 105, 20, 112, 120, 50)";a.__track_lines__[93]='GradientDemo.py, line 93:\n    radgrad2.addColorStop(0, Color("#FF5F98"))';a.__track_lines__[94]='GradientDemo.py, line 94:\n    radgrad2.addColorStop(0.75, Color("#FF0188"))';a.__track_lines__[95]='GradientDemo.py, line 95:\n    radgrad2.addColorStop(1, Color("rgba(255,1,136,0)"))';a.__track_lines__[97]="GradientDemo.py, line 97:\n    radgrad3 = self.canvas.createRadialGradient(95, 15, 15, 102, 20, 40)";
a.__track_lines__[98]='GradientDemo.py, line 98:\n    radgrad3.addColorStop(0, Color("#00C9FF"))';a.__track_lines__[99]='GradientDemo.py, line 99:\n    radgrad3.addColorStop(0.8, Color("#00B5E2"))';a.__track_lines__[100]='GradientDemo.py, line 100:\n    radgrad3.addColorStop(1, Color("rgba(0,201,255,0)"))';a.__track_lines__[102]="GradientDemo.py, line 102:\n    radgrad4 = self.canvas.createRadialGradient(0, 150, 50, 0, 140, 90)";a.__track_lines__[103]='GradientDemo.py, line 103:\n    radgrad4.addColorStop(0, Color("#F4F201"))';
a.__track_lines__[104]='GradientDemo.py, line 104:\n    radgrad4.addColorStop(0.8, Color("#E4C700"))';a.__track_lines__[105]='GradientDemo.py, line 105:\n    radgrad4.addColorStop(1, Color("rgba(228,199,0,0)"))';a.__track_lines__[108]="GradientDemo.py, line 108:\n    self.canvas.setFillStyle(radgrad4)";a.__track_lines__[109]="GradientDemo.py, line 109:\n    self.canvas.fillRect(0, 0, 150, 150)";a.__track_lines__[110]="GradientDemo.py, line 110:\n    self.canvas.setFillStyle(radgrad3)";a.__track_lines__[111]=
"GradientDemo.py, line 111:\n    self.canvas.fillRect(0, 0, 150, 150)";a.__track_lines__[112]="GradientDemo.py, line 112:\n    self.canvas.setFillStyle(radgrad2)";a.__track_lines__[113]="GradientDemo.py, line 113:\n    self.canvas.fillRect(0, 0, 150, 150)";a.__track_lines__[114]="GradientDemo.py, line 114:\n    self.canvas.setFillStyle(radgrad)";a.__track_lines__[115]="GradientDemo.py, line 115:\n    self.canvas.fillRect(0, 0, 150, 150)";a.__track_lines__[117]="GradientDemo.py, line 117:\n    self.canvas.restoreContext()";
a.__track_lines__[120]="GradientDemo.py, line 120:\n    def stopDemo(self):";a.__track_lines__[121]="GradientDemo.py, line 121:\n    pass";var e=new $p["int"](0),l=new $p["int"](1),q=new $p["int"](130),w=new $p["int"](102),x=new $p["int"](40),r=new $p["int"](105),n=new $p["int"](10),y=new $p["int"](140),s=new $p["int"](45),z=new $p["int"](112),t=new $p["int"](15),m=new $p["int"](400),k=new $p["int"](50),A=new $p["int"](52),f=new $p["int"](150),B=new $p["int"](120),u=new $p["int"](20),C=new $p["int"](90),
D=new $p["int"](30),v=new $p["int"](95);$pyjs.track.module="GradientDemo";$pyjs.track.lineno=1;$pyjs.track.lineno=20;$pyjs.track={module:$pyjs.track.module,lineno:$pyjs.track.lineno};$pyjs.trackstack.push($pyjs.track);a.Composite=$p.___import___("pyjamas.ui.Composite.Composite",null,null,!1);$pyjs.trackstack.pop();$pyjs.track=$pyjs.trackstack.pop();$pyjs.trackstack.push($pyjs.track);$pyjs.track.lineno=21;$pyjs.track={module:$pyjs.track.module,lineno:$pyjs.track.lineno};$pyjs.trackstack.push($pyjs.track);
a.HTML=$p.___import___("pyjamas.ui.HTML.HTML",null,null,!1);$pyjs.trackstack.pop();$pyjs.track=$pyjs.trackstack.pop();$pyjs.trackstack.push($pyjs.track);$pyjs.track.lineno=22;$pyjs.track={module:$pyjs.track.module,lineno:$pyjs.track.lineno};$pyjs.trackstack.push($pyjs.track);a.VerticalPanel=$p.___import___("pyjamas.ui.VerticalPanel.VerticalPanel",null,null,!1);$pyjs.trackstack.pop();$pyjs.track=$pyjs.trackstack.pop();$pyjs.trackstack.push($pyjs.track);$pyjs.track.lineno=24;$pyjs.track={module:$pyjs.track.module,
lineno:$pyjs.track.lineno};$pyjs.trackstack.push($pyjs.track);a.Color=$p.___import___("pyjamas.Canvas.Color.Color",null,null,!1);$pyjs.trackstack.pop();$pyjs.track=$pyjs.trackstack.pop();$pyjs.trackstack.push($pyjs.track);$pyjs.track.lineno=26;$pyjs.track={module:$pyjs.track.module,lineno:$pyjs.track.lineno};$pyjs.trackstack.push($pyjs.track);a.SimpleCanvasDemo=$p.___import___("SimpleCanvasDemo.SimpleCanvasDemo",null,null,!1);$pyjs.trackstack.pop();$pyjs.track=$pyjs.trackstack.pop();$pyjs.trackstack.push($pyjs.track);
$pyjs.track.lineno=28;a.GradientDemoControls=function(){var e={},d;e.__module__="GradientDemo";e.__md5__="b615640297555feda93c2572f01a5ccb";$pyjs.track.lineno=29;d=$pyjs__bind_method2("__init__",function(){if(!0===this.__is_instance__){var b=this;$pyjs.options.arg_count&&0!=arguments.length&&$pyjs__exception_func_param(arguments.callee.__name__,1,1,arguments.length+1)}else b=arguments[0],$pyjs.options.arg_is_instance&&!0!==b.__is_instance__&&$pyjs__exception_func_instance_expected(arguments.callee.__name__,
arguments.callee.__class__.__name__,b),$pyjs.options.arg_count&&1!=arguments.length&&$pyjs__exception_func_param(arguments.callee.__name__,1,1,arguments.length);$pyjs.options.arg_instance_type&&"b615640297555feda93c2572f01a5ccb"!==b.prototype.__md5__&&($p._isinstance(b,arguments.callee.__class__)||$pyjs__exception_func_instance_expected(arguments.callee.__name__,arguments.callee.__class__.__name__,b));var c;$pyjs.track={module:"GradientDemo",lineno:29};$pyjs.trackstack.push($pyjs.track);$pyjs.track.module=
"GradientDemo";$pyjs.track.lineno=29;$pyjs.track.lineno=30;c=a.VerticalPanel();$pyjs.track.lineno=31;c.add(a.HTML('<b style="color:#f00;">Stroke Gradients currently not working correctly in IE. RadialGradients are not supported in VML. Contributor assistance welcome :).</b>'));$pyjs.track.lineno=33;a.Composite.__init__(b,c);$pyjs.trackstack.pop();$pyjs.track=$pyjs.trackstack.pop();$pyjs.trackstack.push($pyjs.track);return null},1,[null,null,["self"]]);e.__init__=d;$pyjs.track.lineno=28;d=Array(a.Composite);
var f=$p.dict(),k;for(k in e)f.__setitem__(k,e[k]);return $p._create_class("GradientDemoControls",$p.tuple(d),f)}();$pyjs.track.lineno=37;$pyjs.track.lineno=40;a.GradientDemo=function(){var g={},d;g.__module__="GradientDemo";g.__md5__="9dc8b9c7d98cef5f2ef4c8de93f47af1";$pyjs.track.lineno=42;d=$pyjs__bind_method2("__init__",function(b){if(!0===this.__is_instance__){var c=this;$pyjs.options.arg_count&&1!=arguments.length&&$pyjs__exception_func_param(arguments.callee.__name__,2,2,arguments.length+1)}else c=
arguments[0],b=arguments[1],$pyjs.options.arg_is_instance&&!0!==c.__is_instance__&&$pyjs__exception_func_instance_expected(arguments.callee.__name__,arguments.callee.__class__.__name__,c),$pyjs.options.arg_count&&2!=arguments.length&&$pyjs__exception_func_param(arguments.callee.__name__,2,2,arguments.length);$pyjs.options.arg_instance_type&&"9dc8b9c7d98cef5f2ef4c8de93f47af1"!==c.prototype.__md5__&&($p._isinstance(c,arguments.callee.__class__)||$pyjs__exception_func_instance_expected(arguments.callee.__name__,
arguments.callee.__class__.__name__,c));$pyjs.track={module:"GradientDemo",lineno:42};$pyjs.trackstack.push($pyjs.track);$pyjs.track.module="GradientDemo";$pyjs.track.lineno=42;$pyjs.track.lineno=43;a.SimpleCanvasDemo.__init__(c,b);$pyjs.track.lineno=45;c.__is_instance__&&"function"==typeof c.__setattr__?c.__setattr__("width",m):$p.setattr(c,"width",m);$pyjs.track.lineno=46;c.__is_instance__&&"function"==typeof c.__setattr__?c.__setattr__("height",m):$p.setattr(c,"height",m);$pyjs.track.lineno=47;
c.__is_instance__&&"function"==typeof c.__setattr__?c.__setattr__("demoName","Gradients"):$p.setattr(c,"demoName","Gradients");$pyjs.trackstack.pop();$pyjs.track=$pyjs.trackstack.pop();$pyjs.trackstack.push($pyjs.track);return null},1,[null,null,["self"],["theCanvas"]]);g.__init__=d;$pyjs.track.lineno=50;d=$pyjs__bind_method2("createControls",function(){if(!0===this.__is_instance__){var b=this;$pyjs.options.arg_count&&0!=arguments.length&&$pyjs__exception_func_param(arguments.callee.__name__,1,1,
arguments.length+1)}else b=arguments[0],$pyjs.options.arg_is_instance&&!0!==b.__is_instance__&&$pyjs__exception_func_instance_expected(arguments.callee.__name__,arguments.callee.__class__.__name__,b),$pyjs.options.arg_count&&1!=arguments.length&&$pyjs__exception_func_param(arguments.callee.__name__,1,1,arguments.length);$pyjs.options.arg_instance_type&&"9dc8b9c7d98cef5f2ef4c8de93f47af1"!==b.prototype.__md5__&&($p._isinstance(b,arguments.callee.__class__)||$pyjs__exception_func_instance_expected(arguments.callee.__name__,
arguments.callee.__class__.__name__,b));$pyjs.track={module:"GradientDemo",lineno:50};$pyjs.trackstack.push($pyjs.track);$pyjs.track.module="GradientDemo";$pyjs.track.lineno=50;$pyjs.track.lineno=51;b.__is_instance__&&"function"==typeof b.__setattr__?b.__setattr__("controls",a.GradientDemoControls()):$p.setattr(b,"controls",a.GradientDemoControls());$pyjs.trackstack.pop();$pyjs.track=$pyjs.trackstack.pop();$pyjs.trackstack.push($pyjs.track);return null},1,[null,null,["self"]]);g.createControls=d;
$pyjs.track.lineno=54;d=$pyjs__bind_method2("drawDemo",function(){if(!0===this.__is_instance__){var b=this;$pyjs.options.arg_count&&0!=arguments.length&&$pyjs__exception_func_param(arguments.callee.__name__,1,1,arguments.length+1)}else b=arguments[0],$pyjs.options.arg_is_instance&&!0!==b.__is_instance__&&$pyjs__exception_func_instance_expected(arguments.callee.__name__,arguments.callee.__class__.__name__,b),$pyjs.options.arg_count&&1!=arguments.length&&$pyjs__exception_func_param(arguments.callee.__name__,
1,1,arguments.length);$pyjs.options.arg_instance_type&&"9dc8b9c7d98cef5f2ef4c8de93f47af1"!==b.prototype.__md5__&&($p._isinstance(b,arguments.callee.__class__)||$pyjs__exception_func_instance_expected(arguments.callee.__name__,arguments.callee.__class__.__name__,b));var c,d,g,h;$pyjs.track={module:"GradientDemo",lineno:54};$pyjs.trackstack.push($pyjs.track);$pyjs.track.module="GradientDemo";$pyjs.track.lineno=54;$pyjs.track.lineno=55;b.canvas.resize($p.getattr(b,"width"),$p.getattr(b,"height"));$pyjs.track.lineno=
59;b.canvas.saveContext();$pyjs.track.lineno=62;d=b.canvas.createLinearGradient(e,e,e,f);$pyjs.track.lineno=63;d.addColorStop(0,a.Color("#00ABEB"));$pyjs.track.lineno=64;d.addColorStop(0.5,a.Color("#fff"));$pyjs.track.lineno=65;d.addColorStop(0.5,a.Color("#26C000"));$pyjs.track.lineno=66;d.addColorStop(l,a.Color("#fff"));$pyjs.track.lineno=68;c=b.canvas.createLinearGradient(e,k,e,v);$pyjs.track.lineno=69;c.addColorStop(0.5,a.Color("#000"));$pyjs.track.lineno=70;c.addColorStop(l,a.Color("rgba(0,0,0,0)"));
$pyjs.track.lineno=73;b.canvas.setFillStyle(d);$pyjs.track.lineno=74;b.canvas.setStrokeStyle(c);$pyjs.track.lineno=77;b.canvas.fillRect(n,n,q,q);$pyjs.track.lineno=78;b.canvas.strokeRect(k,k,k,k);$pyjs.track.lineno=80;b.canvas.restoreContext();$pyjs.track.lineno=84;b.canvas.saveContext();$pyjs.track.lineno=85;b.canvas.translate(f,f);$pyjs.track.lineno=87;h=b.canvas.createRadialGradient(s,s,n,A,k,D);$pyjs.track.lineno=88;h.addColorStop(e,a.Color("#A7D30C"));$pyjs.track.lineno=89;h.addColorStop(0.9,
a.Color("#019F62"));$pyjs.track.lineno=90;h.addColorStop(l,a.Color("rgba(1,159,98,0)"));$pyjs.track.lineno=92;g=b.canvas.createRadialGradient(r,r,u,z,B,k);$pyjs.track.lineno=93;g.addColorStop(e,a.Color("#FF5F98"));$pyjs.track.lineno=94;g.addColorStop(0.75,a.Color("#FF0188"));$pyjs.track.lineno=95;g.addColorStop(l,a.Color("rgba(255,1,136,0)"));$pyjs.track.lineno=97;d=b.canvas.createRadialGradient(v,t,t,w,u,x);$pyjs.track.lineno=98;d.addColorStop(e,a.Color("#00C9FF"));$pyjs.track.lineno=99;d.addColorStop(0.8,
a.Color("#00B5E2"));$pyjs.track.lineno=100;d.addColorStop(l,a.Color("rgba(0,201,255,0)"));$pyjs.track.lineno=102;c=b.canvas.createRadialGradient(e,f,k,e,y,C);$pyjs.track.lineno=103;c.addColorStop(e,a.Color("#F4F201"));$pyjs.track.lineno=104;c.addColorStop(0.8,a.Color("#E4C700"));$pyjs.track.lineno=105;c.addColorStop(l,a.Color("rgba(228,199,0,0)"));$pyjs.track.lineno=108;b.canvas.setFillStyle(c);$pyjs.track.lineno=109;b.canvas.fillRect(e,e,f,f);$pyjs.track.lineno=110;b.canvas.setFillStyle(d);$pyjs.track.lineno=
111;b.canvas.fillRect(e,e,f,f);$pyjs.track.lineno=112;b.canvas.setFillStyle(g);$pyjs.track.lineno=113;b.canvas.fillRect(e,e,f,f);$pyjs.track.lineno=114;b.canvas.setFillStyle(h);$pyjs.track.lineno=115;b.canvas.fillRect(e,e,f,f);$pyjs.track.lineno=117;b.canvas.restoreContext();$pyjs.trackstack.pop();$pyjs.track=$pyjs.trackstack.pop();$pyjs.trackstack.push($pyjs.track);return null},1,[null,null,["self"]]);g.drawDemo=d;$pyjs.track.lineno=120;d=$pyjs__bind_method2("stopDemo",function(){if(!0===this.__is_instance__){var a=
this;$pyjs.options.arg_count&&0!=arguments.length&&$pyjs__exception_func_param(arguments.callee.__name__,1,1,arguments.length+1)}else a=arguments[0],$pyjs.options.arg_is_instance&&!0!==a.__is_instance__&&$pyjs__exception_func_instance_expected(arguments.callee.__name__,arguments.callee.__class__.__name__,a),$pyjs.options.arg_count&&1!=arguments.length&&$pyjs__exception_func_param(arguments.callee.__name__,1,1,arguments.length);$pyjs.options.arg_instance_type&&"9dc8b9c7d98cef5f2ef4c8de93f47af1"!==
a.prototype.__md5__&&($p._isinstance(a,arguments.callee.__class__)||$pyjs__exception_func_instance_expected(arguments.callee.__name__,arguments.callee.__class__.__name__,a));$pyjs.track={module:"GradientDemo",lineno:120};$pyjs.trackstack.push($pyjs.track);$pyjs.track.module="GradientDemo";$pyjs.track.lineno=120;$pyjs.track.lineno=121;$pyjs.trackstack.pop();$pyjs.track=$pyjs.trackstack.pop();$pyjs.trackstack.push($pyjs.track);return null},1,[null,null,["self"]]);g.stopDemo=d;$pyjs.track.lineno=40;
d=Array(a.SimpleCanvasDemo);var h=$p.dict(),p;for(p in g)h.__setitem__(p,g[p]);return $p._create_class("GradientDemo",$p.tuple(d),h)}()}catch(E){throw $p._errorMapping(E);}return this};
