$pyjs.loaded_modules.Hello=function(b){if($pyjs.loaded_modules.Hello.__was_initialized__)return $pyjs.loaded_modules.Hello;var a=$pyjs.loaded_modules.Hello;a.__repr__=function(){return"<module: Hello>"};a.__was_initialized__=!0;if(null===b||"undefined"==typeof b)b="Hello";a.__name__=b;a.__track_lines__=[];try{a.__track_lines__[1]="Hello.py, line 1:\n    import pyjd # this is dummy in pyjs.",a.__track_lines__[2]="Hello.py, line 2:\n    from pyjamas.ui.RootPanel import RootPanel",a.__track_lines__[3]=
"Hello.py, line 3:\n    from pyjamas.ui.Button import Button",a.__track_lines__[4]="Hello.py, line 4:\n    from pyjamas.ui.HTML import HTML",a.__track_lines__[5]="Hello.py, line 5:\n    from pyjamas.ui.Label import Label",a.__track_lines__[6]="Hello.py, line 6:\n    from pyjamas import Window",a.__track_lines__[8]="Hello.py, line 8:\n    import pygwt",a.__track_lines__[10]="Hello.py, line 10:\n    def greet(fred):",a.__track_lines__[11]='Hello.py, line 11:\n    fred.setText("No, really click me!")',
a.__track_lines__[12]='Hello.py, line 12:\n    Window.alert("Hello, AJAX!")',a.__track_lines__[14]="Hello.py, line 14:\n    if __name__ == '__main__':",a.__track_lines__[15]='Hello.py, line 15:\n    pyjd.setup("public/Hello.html?fred=foo#me")',a.__track_lines__[16]="Hello.py, line 16:\n    b = Button(\"Click me\", greet, StyleName='teststyle')",a.__track_lines__[17]="Hello.py, line 17:\n    h = HTML(\"<b>Hello World</b> (html)\", StyleName='teststyle')",a.__track_lines__[18]="Hello.py, line 18:\n    l = Label(\"Hello World (label)\", StyleName='teststyle')",
a.__track_lines__[19]='Hello.py, line 19:\n    base = HTML("Hello from %s" % pygwt.getModuleBaseURL(),',a.__track_lines__[21]="Hello.py, line 21:\n    RootPanel().add(b)",a.__track_lines__[22]="Hello.py, line 22:\n    RootPanel().add(h)",a.__track_lines__[23]="Hello.py, line 23:\n    RootPanel().add(l)",a.__track_lines__[24]="Hello.py, line 24:\n    RootPanel().add(base)",a.__track_lines__[25]="Hello.py, line 25:\n    pyjd.run()",$pyjs.track.module="Hello",$pyjs.track.lineno=1,$pyjs.track.lineno=
1,$pyjs.track={module:$pyjs.track.module,lineno:$pyjs.track.lineno},$pyjs.trackstack.push($pyjs.track),a.pyjd=$p.___import___("pyjd",null),$pyjs.trackstack.pop(),$pyjs.track=$pyjs.trackstack.pop(),$pyjs.trackstack.push($pyjs.track),$pyjs.track.lineno=2,$pyjs.track={module:$pyjs.track.module,lineno:$pyjs.track.lineno},$pyjs.trackstack.push($pyjs.track),a.RootPanel=$p.___import___("pyjamas.ui.RootPanel.RootPanel",null,null,!1),$pyjs.trackstack.pop(),$pyjs.track=$pyjs.trackstack.pop(),$pyjs.trackstack.push($pyjs.track),
$pyjs.track.lineno=3,$pyjs.track={module:$pyjs.track.module,lineno:$pyjs.track.lineno},$pyjs.trackstack.push($pyjs.track),a.Button=$p.___import___("pyjamas.ui.Button.Button",null,null,!1),$pyjs.trackstack.pop(),$pyjs.track=$pyjs.trackstack.pop(),$pyjs.trackstack.push($pyjs.track),$pyjs.track.lineno=4,$pyjs.track={module:$pyjs.track.module,lineno:$pyjs.track.lineno},$pyjs.trackstack.push($pyjs.track),a.HTML=$p.___import___("pyjamas.ui.HTML.HTML",null,null,!1),$pyjs.trackstack.pop(),$pyjs.track=$pyjs.trackstack.pop(),
$pyjs.trackstack.push($pyjs.track),$pyjs.track.lineno=5,$pyjs.track={module:$pyjs.track.module,lineno:$pyjs.track.lineno},$pyjs.trackstack.push($pyjs.track),a.Label=$p.___import___("pyjamas.ui.Label.Label",null,null,!1),$pyjs.trackstack.pop(),$pyjs.track=$pyjs.trackstack.pop(),$pyjs.trackstack.push($pyjs.track),$pyjs.track.lineno=6,$pyjs.track={module:$pyjs.track.module,lineno:$pyjs.track.lineno},$pyjs.trackstack.push($pyjs.track),a.Window=$p.___import___("pyjamas.Window",null,null,!1),$pyjs.trackstack.pop(),
$pyjs.track=$pyjs.trackstack.pop(),$pyjs.trackstack.push($pyjs.track),$pyjs.track.lineno=8,$pyjs.track={module:$pyjs.track.module,lineno:$pyjs.track.lineno},$pyjs.trackstack.push($pyjs.track),a.pygwt=$p.___import___("pygwt",null),$pyjs.trackstack.pop(),$pyjs.track=$pyjs.trackstack.pop(),$pyjs.trackstack.push($pyjs.track),$pyjs.track.lineno=10,a.greet=function(b){$pyjs.options.arg_count&&1!=arguments.length&&$pyjs__exception_func_param(arguments.callee.__name__,1,1,arguments.length);$pyjs.track={module:"Hello",
lineno:10};$pyjs.trackstack.push($pyjs.track);$pyjs.track.module="Hello";$pyjs.track.lineno=10;$pyjs.track.lineno=11;b.setText("No, really click me!");$pyjs.track.lineno=12;a.Window.alert("Hello, AJAX!");$pyjs.trackstack.pop();$pyjs.track=$pyjs.trackstack.pop();$pyjs.trackstack.push($pyjs.track);return null},a.greet.__name__="greet",a.greet.__bind_type__=0,a.greet.__args__=[null,null,["fred"]],$pyjs.track.lineno=14,$p.bool($p.op_eq("undefined"==typeof __name__?a.__name__:__name__,"__main__"))&&($pyjs.track.lineno=
15,a.pyjd.setup("public/Hello.html?fred=foo#me"),$pyjs.track.lineno=16,a.b=$pyjs_kwargs_call(null,a.Button,null,null,[{StyleName:"teststyle"},"Click me",a.greet]),$pyjs.track.lineno=17,a.h=$pyjs_kwargs_call(null,a.HTML,null,null,[{StyleName:"teststyle"},"<b>Hello World</b> (html)"]),$pyjs.track.lineno=18,a.l=$pyjs_kwargs_call(null,a.Label,null,null,[{StyleName:"teststyle"},"Hello World (label)"]),$pyjs.track.lineno=19,a.base=$pyjs_kwargs_call(null,a.HTML,null,null,[{StyleName:"teststyle"},$p.sprintf("Hello from %s",
a.pygwt.getModuleBaseURL())]),$pyjs.track.lineno=21,a.RootPanel().add(a.b),$pyjs.track.lineno=22,a.RootPanel().add(a.h),$pyjs.track.lineno=23,a.RootPanel().add(a.l),$pyjs.track.lineno=24,a.RootPanel().add(a.base),$pyjs.track.lineno=25,a.pyjd.run())}catch(c){throw $p._errorMapping(c);}return this};
