$pyjs.loaded_modules.LogoDemo=function(h){if($pyjs.loaded_modules.LogoDemo.__was_initialized__)return $pyjs.loaded_modules.LogoDemo;var a=$pyjs.loaded_modules.LogoDemo;a.__repr__=function(){return"<module: LogoDemo>"};a.__was_initialized__=!0;if(null===h||"undefined"==typeof h)h="LogoDemo";a.__name__=h;a.__track_lines__=[];try{a.__track_lines__[128]="LogoDemo.py, line 128:\n    self.rotation += 0.1";a.__track_lines__[1]='LogoDemo.py, line 1:\n    """';a.__track_lines__[130]="LogoDemo.py, line 130:\n    self.canvas.restoreContext()";
a.__track_lines__[134]="LogoDemo.py, line 134:\n    def onTimer(self, timer):";a.__track_lines__[135]="LogoDemo.py, line 135:\n    if not self.run:";a.__track_lines__[136]="LogoDemo.py, line 136:\n    return";a.__track_lines__[137]="LogoDemo.py, line 137:\n    self.renderingLoop()";a.__track_lines__[138]="LogoDemo.py, line 138:\n    timer.schedule(10)";a.__track_lines__[20]="LogoDemo.py, line 20:\n    from pyjamas.Timer import Timer";a.__track_lines__[21]="LogoDemo.py, line 21:\n    from pyjamas import Window";
a.__track_lines__[22]="LogoDemo.py, line 22:\n    from pyjamas import DOM";a.__track_lines__[23]="LogoDemo.py, line 23:\n    from pyjamas.ui.Composite import Composite";a.__track_lines__[24]="LogoDemo.py, line 24:\n    from pyjamas.ui.VerticalPanel import VerticalPanel";a.__track_lines__[25]="LogoDemo.py, line 25:\n    from pyjamas.Canvas.ImageLoader import loadImages";a.__track_lines__[27]="LogoDemo.py, line 27:\n    from SimpleCanvasDemo import SimpleCanvasDemo";a.__track_lines__[32]="LogoDemo.py, line 32:\n    class LogoDemoControls(Composite):";
a.__track_lines__[33]="LogoDemo.py, line 33:\n    def __init__(self):";a.__track_lines__[34]="LogoDemo.py, line 34:\n    Composite.__init__(self, VerticalPanel())";a.__track_lines__[36]='LogoDemo.py, line 36:\n    """*';a.__track_lines__[39]="LogoDemo.py, line 39:\n    class LogoDemo(SimpleCanvasDemo):";a.__track_lines__[47]="LogoDemo.py, line 47:\n    def __init__(self, theCanvas):";a.__track_lines__[48]="LogoDemo.py, line 48:\n    SimpleCanvasDemo.__init__(self, theCanvas)";a.__track_lines__[49]=
"LogoDemo.py, line 49:\n    self.height = 400";a.__track_lines__[50]="LogoDemo.py, line 50:\n    self.width = 600";a.__track_lines__[51]='LogoDemo.py, line 51:\n    self.demoName = "Pyjamas Logo"';a.__track_lines__[53]='LogoDemo.py, line 53:\n    """';a.__track_lines__[57]="LogoDemo.py, line 57:\n    self.img = None";a.__track_lines__[59]="LogoDemo.py, line 59:\n    self.rotation = 0.1";a.__track_lines__[61]="LogoDemo.py, line 61:\n    self.run = False";a.__track_lines__[63]="LogoDemo.py, line 63:\n    def createControls(self):";
a.__track_lines__[64]="LogoDemo.py, line 64:\n    self.controls = LogoDemoControls()";a.__track_lines__[67]="LogoDemo.py, line 67:\n    def drawDemo(self):";a.__track_lines__[69]="LogoDemo.py, line 69:\n    self.canvas.resize(self.width,self.height)";a.__track_lines__[74]='LogoDemo.py, line 74:\n    imageUrls = ["./pyjamas.128x128.png"]';a.__track_lines__[77]="LogoDemo.py, line 77:\n    if self.img is None:";a.__track_lines__[81]="LogoDemo.py, line 81:\n    loadImages(imageUrls, self)";a.__track_lines__[85]=
"LogoDemo.py, line 85:\n    if self.isImageLoaded(self.img):";a.__track_lines__[86]="LogoDemo.py, line 86:\n    self.run = True";a.__track_lines__[88]="LogoDemo.py, line 88:\n    Timer(1, self)";a.__track_lines__[90]='LogoDemo.py, line 90:\n    Window.alert("Refresh the page to reload the image.")';a.__track_lines__[93]="LogoDemo.py, line 93:\n    def onImagesLoaded(self, imageHandles):";a.__track_lines__[96]="LogoDemo.py, line 96:\n    self.img = imageHandles[0]";a.__track_lines__[97]="LogoDemo.py, line 97:\n    self.run = True";
a.__track_lines__[98]="LogoDemo.py, line 98:\n    Timer(1, self)";a.__track_lines__[101]="LogoDemo.py, line 101:\n    def stopDemo(self):";a.__track_lines__[102]="LogoDemo.py, line 102:\n    self.run = False";a.__track_lines__[105]="LogoDemo.py, line 105:\n    def isImageLoaded(self, imgElem):";a.__track_lines__[106]='LogoDemo.py, line 106:\n    return hasattr(imgElem, "__isLoaded") and imgElem.__isLoaded';a.__track_lines__[108]="LogoDemo.py, line 108:\n    def renderingLoop(self):";a.__track_lines__[109]=
"LogoDemo.py, line 109:\n    self.canvas.saveContext()";a.__track_lines__[111]="LogoDemo.py, line 111:\n    self.canvas.clear()";a.__track_lines__[120]="LogoDemo.py, line 120:\n    self.canvas.drawImage(self.img, 84, 74)";a.__track_lines__[123]="LogoDemo.py, line 123:\n    self.canvas.translate(300, 200)";a.__track_lines__[124]="LogoDemo.py, line 124:\n    self.canvas.rotate(self.rotation)";a.__track_lines__[125]="LogoDemo.py, line 125:\n    self.canvas.scale(.9, .9)";a.__track_lines__[127]="LogoDemo.py, line 127:\n    self.canvas.drawImage(self.img, 0, 0)";
var k=new $p["int"](0),l=new $p["int"](1),p=new $p["int"](200),q=new $p["int"](74),r=new $p["int"](300),m=new $p["int"](400),s=new $p["int"](84),n=new $p["int"](600),t=new $p["int"](10);$pyjs.track.module="LogoDemo";$pyjs.track.lineno=1;$pyjs.track.lineno=20;$pyjs.track={module:$pyjs.track.module,lineno:$pyjs.track.lineno};$pyjs.trackstack.push($pyjs.track);a.Timer=$p.___import___("pyjamas.Timer.Timer",null,null,!1);$pyjs.trackstack.pop();$pyjs.track=$pyjs.trackstack.pop();$pyjs.trackstack.push($pyjs.track);
$pyjs.track.lineno=21;$pyjs.track={module:$pyjs.track.module,lineno:$pyjs.track.lineno};$pyjs.trackstack.push($pyjs.track);a.Window=$p.___import___("pyjamas.Window",null,null,!1);$pyjs.trackstack.pop();$pyjs.track=$pyjs.trackstack.pop();$pyjs.trackstack.push($pyjs.track);$pyjs.track.lineno=22;$pyjs.track={module:$pyjs.track.module,lineno:$pyjs.track.lineno};$pyjs.trackstack.push($pyjs.track);a.DOM=$p.___import___("pyjamas.DOM",null,null,!1);$pyjs.trackstack.pop();$pyjs.track=$pyjs.trackstack.pop();
$pyjs.trackstack.push($pyjs.track);$pyjs.track.lineno=23;$pyjs.track={module:$pyjs.track.module,lineno:$pyjs.track.lineno};$pyjs.trackstack.push($pyjs.track);a.Composite=$p.___import___("pyjamas.ui.Composite.Composite",null,null,!1);$pyjs.trackstack.pop();$pyjs.track=$pyjs.trackstack.pop();$pyjs.trackstack.push($pyjs.track);$pyjs.track.lineno=24;$pyjs.track={module:$pyjs.track.module,lineno:$pyjs.track.lineno};$pyjs.trackstack.push($pyjs.track);a.VerticalPanel=$p.___import___("pyjamas.ui.VerticalPanel.VerticalPanel",
null,null,!1);$pyjs.trackstack.pop();$pyjs.track=$pyjs.trackstack.pop();$pyjs.trackstack.push($pyjs.track);$pyjs.track.lineno=25;$pyjs.track={module:$pyjs.track.module,lineno:$pyjs.track.lineno};$pyjs.trackstack.push($pyjs.track);a.loadImages=$p.___import___("pyjamas.Canvas.ImageLoader.loadImages",null,null,!1);$pyjs.trackstack.pop();$pyjs.track=$pyjs.trackstack.pop();$pyjs.trackstack.push($pyjs.track);$pyjs.track.lineno=27;$pyjs.track={module:$pyjs.track.module,lineno:$pyjs.track.lineno};$pyjs.trackstack.push($pyjs.track);
a.SimpleCanvasDemo=$p.___import___("SimpleCanvasDemo.SimpleCanvasDemo",null,null,!1);$pyjs.trackstack.pop();$pyjs.track=$pyjs.trackstack.pop();$pyjs.trackstack.push($pyjs.track);$pyjs.track.lineno=32;a.LogoDemoControls=function(){var e={},d;e.__module__="LogoDemo";e.__md5__="06ea103ce0c4ae1d4635c37a2d8409de";$pyjs.track.lineno=33;d=$pyjs__bind_method2("__init__",function(){if(!0===this.__is_instance__){var b=this;$pyjs.options.arg_count&&0!=arguments.length&&$pyjs__exception_func_param(arguments.callee.__name__,
1,1,arguments.length+1)}else b=arguments[0],$pyjs.options.arg_is_instance&&!0!==b.__is_instance__&&$pyjs__exception_func_instance_expected(arguments.callee.__name__,arguments.callee.__class__.__name__,b),$pyjs.options.arg_count&&1!=arguments.length&&$pyjs__exception_func_param(arguments.callee.__name__,1,1,arguments.length);$pyjs.options.arg_instance_type&&"06ea103ce0c4ae1d4635c37a2d8409de"!==b.prototype.__md5__&&($p._isinstance(b,arguments.callee.__class__)||$pyjs__exception_func_instance_expected(arguments.callee.__name__,
arguments.callee.__class__.__name__,b));$pyjs.track={module:"LogoDemo",lineno:33};$pyjs.trackstack.push($pyjs.track);$pyjs.track.module="LogoDemo";$pyjs.track.lineno=33;$pyjs.track.lineno=34;a.Composite.__init__(b,a.VerticalPanel());$pyjs.trackstack.pop();$pyjs.track=$pyjs.trackstack.pop();$pyjs.trackstack.push($pyjs.track);return null},1,[null,null,["self"]]);e.__init__=d;$pyjs.track.lineno=32;d=Array(a.Composite);var g=$p.dict(),f;for(f in e)g.__setitem__(f,e[f]);return $p._create_class("LogoDemoControls",
$p.tuple(d),g)}();$pyjs.track.lineno=36;$pyjs.track.lineno=39;a.LogoDemo=function(){var e={},d;e.__module__="LogoDemo";e.__md5__="fe3e46eefe371d13bc9d9b45c5deaf3c";$pyjs.track.lineno=47;d=$pyjs__bind_method2("__init__",function(b){if(!0===this.__is_instance__){var c=this;$pyjs.options.arg_count&&1!=arguments.length&&$pyjs__exception_func_param(arguments.callee.__name__,2,2,arguments.length+1)}else c=arguments[0],b=arguments[1],$pyjs.options.arg_is_instance&&!0!==c.__is_instance__&&$pyjs__exception_func_instance_expected(arguments.callee.__name__,
arguments.callee.__class__.__name__,c),$pyjs.options.arg_count&&2!=arguments.length&&$pyjs__exception_func_param(arguments.callee.__name__,2,2,arguments.length);$pyjs.options.arg_instance_type&&"fe3e46eefe371d13bc9d9b45c5deaf3c"!==c.prototype.__md5__&&($p._isinstance(c,arguments.callee.__class__)||$pyjs__exception_func_instance_expected(arguments.callee.__name__,arguments.callee.__class__.__name__,c));$pyjs.track={module:"LogoDemo",lineno:47};$pyjs.trackstack.push($pyjs.track);$pyjs.track.module=
"LogoDemo";$pyjs.track.lineno=47;$pyjs.track.lineno=48;a.SimpleCanvasDemo.__init__(c,b);$pyjs.track.lineno=49;c.__is_instance__&&"function"==typeof c.__setattr__?c.__setattr__("height",m):$p.setattr(c,"height",m);$pyjs.track.lineno=50;c.__is_instance__&&"function"==typeof c.__setattr__?c.__setattr__("width",n):$p.setattr(c,"width",n);$pyjs.track.lineno=51;c.__is_instance__&&"function"==typeof c.__setattr__?c.__setattr__("demoName","Pyjamas Logo"):$p.setattr(c,"demoName","Pyjamas Logo");$pyjs.track.lineno=
53;$pyjs.track.lineno=57;c.__is_instance__&&"function"==typeof c.__setattr__?c.__setattr__("img",null):$p.setattr(c,"img",null);$pyjs.track.lineno=59;c.__is_instance__&&"function"==typeof c.__setattr__?c.__setattr__("rotation",0.1):$p.setattr(c,"rotation",0.1);$pyjs.track.lineno=61;c.__is_instance__&&"function"==typeof c.__setattr__?c.__setattr__("run",!1):$p.setattr(c,"run",!1);$pyjs.trackstack.pop();$pyjs.track=$pyjs.trackstack.pop();$pyjs.trackstack.push($pyjs.track);return null},1,[null,null,
["self"],["theCanvas"]]);e.__init__=d;$pyjs.track.lineno=63;d=$pyjs__bind_method2("createControls",function(){if(!0===this.__is_instance__){var b=this;$pyjs.options.arg_count&&0!=arguments.length&&$pyjs__exception_func_param(arguments.callee.__name__,1,1,arguments.length+1)}else b=arguments[0],$pyjs.options.arg_is_instance&&!0!==b.__is_instance__&&$pyjs__exception_func_instance_expected(arguments.callee.__name__,arguments.callee.__class__.__name__,b),$pyjs.options.arg_count&&1!=arguments.length&&
$pyjs__exception_func_param(arguments.callee.__name__,1,1,arguments.length);$pyjs.options.arg_instance_type&&"fe3e46eefe371d13bc9d9b45c5deaf3c"!==b.prototype.__md5__&&($p._isinstance(b,arguments.callee.__class__)||$pyjs__exception_func_instance_expected(arguments.callee.__name__,arguments.callee.__class__.__name__,b));$pyjs.track={module:"LogoDemo",lineno:63};$pyjs.trackstack.push($pyjs.track);$pyjs.track.module="LogoDemo";$pyjs.track.lineno=63;$pyjs.track.lineno=64;b.__is_instance__&&"function"==
typeof b.__setattr__?b.__setattr__("controls",a.LogoDemoControls()):$p.setattr(b,"controls",a.LogoDemoControls());$pyjs.trackstack.pop();$pyjs.track=$pyjs.trackstack.pop();$pyjs.trackstack.push($pyjs.track);return null},1,[null,null,["self"]]);e.createControls=d;$pyjs.track.lineno=67;d=$pyjs__bind_method2("drawDemo",function(){if(!0===this.__is_instance__){var b=this;$pyjs.options.arg_count&&0!=arguments.length&&$pyjs__exception_func_param(arguments.callee.__name__,1,1,arguments.length+1)}else b=
arguments[0],$pyjs.options.arg_is_instance&&!0!==b.__is_instance__&&$pyjs__exception_func_instance_expected(arguments.callee.__name__,arguments.callee.__class__.__name__,b),$pyjs.options.arg_count&&1!=arguments.length&&$pyjs__exception_func_param(arguments.callee.__name__,1,1,arguments.length);$pyjs.options.arg_instance_type&&"fe3e46eefe371d13bc9d9b45c5deaf3c"!==b.prototype.__md5__&&($p._isinstance(b,arguments.callee.__class__)||$pyjs__exception_func_instance_expected(arguments.callee.__name__,arguments.callee.__class__.__name__,
b));var c;$pyjs.track={module:"LogoDemo",lineno:67};$pyjs.trackstack.push($pyjs.track);$pyjs.track.module="LogoDemo";$pyjs.track.lineno=67;$pyjs.track.lineno=69;b.canvas.resize($p.getattr(b,"width"),$p.getattr(b,"height"));$pyjs.track.lineno=74;c=$p.list(["./pyjamas.128x128.png"]);$pyjs.track.lineno=77;$p.bool($p.op_is($p.getattr(b,"img"),null))?($pyjs.track.lineno=81,a.loadImages(c,b)):($pyjs.track.lineno=85,$p.bool(b.isImageLoaded($p.getattr(b,"img")))?($pyjs.track.lineno=86,b.__is_instance__&&
"function"==typeof b.__setattr__?b.__setattr__("run",!0):$p.setattr(b,"run",!0),$pyjs.track.lineno=88,a.Timer(l,b)):($pyjs.track.lineno=90,a.Window.alert("Refresh the page to reload the image.")));$pyjs.trackstack.pop();$pyjs.track=$pyjs.trackstack.pop();$pyjs.trackstack.push($pyjs.track);return null},1,[null,null,["self"]]);e.drawDemo=d;$pyjs.track.lineno=93;d=$pyjs__bind_method2("onImagesLoaded",function(b){if(!0===this.__is_instance__){var c=this;$pyjs.options.arg_count&&1!=arguments.length&&$pyjs__exception_func_param(arguments.callee.__name__,
2,2,arguments.length+1)}else c=arguments[0],b=arguments[1],$pyjs.options.arg_is_instance&&!0!==c.__is_instance__&&$pyjs__exception_func_instance_expected(arguments.callee.__name__,arguments.callee.__class__.__name__,c),$pyjs.options.arg_count&&2!=arguments.length&&$pyjs__exception_func_param(arguments.callee.__name__,2,2,arguments.length);$pyjs.options.arg_instance_type&&"fe3e46eefe371d13bc9d9b45c5deaf3c"!==c.prototype.__md5__&&($p._isinstance(c,arguments.callee.__class__)||$pyjs__exception_func_instance_expected(arguments.callee.__name__,
arguments.callee.__class__.__name__,c));$pyjs.track={module:"LogoDemo",lineno:93};$pyjs.trackstack.push($pyjs.track);$pyjs.track.module="LogoDemo";$pyjs.track.lineno=93;$pyjs.track.lineno=96;c.__is_instance__&&"function"==typeof c.__setattr__?c.__setattr__("img",b.__getitem__(k)):$p.setattr(c,"img",b.__getitem__(k));$pyjs.track.lineno=97;c.__is_instance__&&"function"==typeof c.__setattr__?c.__setattr__("run",!0):$p.setattr(c,"run",!0);$pyjs.track.lineno=98;a.Timer(l,c);$pyjs.trackstack.pop();$pyjs.track=
$pyjs.trackstack.pop();$pyjs.trackstack.push($pyjs.track);return null},1,[null,null,["self"],["imageHandles"]]);e.onImagesLoaded=d;$pyjs.track.lineno=101;d=$pyjs__bind_method2("stopDemo",function(){if(!0===this.__is_instance__){var b=this;$pyjs.options.arg_count&&0!=arguments.length&&$pyjs__exception_func_param(arguments.callee.__name__,1,1,arguments.length+1)}else b=arguments[0],$pyjs.options.arg_is_instance&&!0!==b.__is_instance__&&$pyjs__exception_func_instance_expected(arguments.callee.__name__,
arguments.callee.__class__.__name__,b),$pyjs.options.arg_count&&1!=arguments.length&&$pyjs__exception_func_param(arguments.callee.__name__,1,1,arguments.length);$pyjs.options.arg_instance_type&&"fe3e46eefe371d13bc9d9b45c5deaf3c"!==b.prototype.__md5__&&($p._isinstance(b,arguments.callee.__class__)||$pyjs__exception_func_instance_expected(arguments.callee.__name__,arguments.callee.__class__.__name__,b));$pyjs.track={module:"LogoDemo",lineno:101};$pyjs.trackstack.push($pyjs.track);$pyjs.track.module=
"LogoDemo";$pyjs.track.lineno=101;$pyjs.track.lineno=102;b.__is_instance__&&"function"==typeof b.__setattr__?b.__setattr__("run",!1):$p.setattr(b,"run",!1);$pyjs.trackstack.pop();$pyjs.track=$pyjs.trackstack.pop();$pyjs.trackstack.push($pyjs.track);return null},1,[null,null,["self"]]);e.stopDemo=d;$pyjs.track.lineno=105;d=$pyjs__bind_method2("isImageLoaded",function(b){if(!0===this.__is_instance__){var a=this;$pyjs.options.arg_count&&1!=arguments.length&&$pyjs__exception_func_param(arguments.callee.__name__,
2,2,arguments.length+1)}else a=arguments[0],b=arguments[1],$pyjs.options.arg_is_instance&&!0!==a.__is_instance__&&$pyjs__exception_func_instance_expected(arguments.callee.__name__,arguments.callee.__class__.__name__,a),$pyjs.options.arg_count&&2!=arguments.length&&$pyjs__exception_func_param(arguments.callee.__name__,2,2,arguments.length);$pyjs.options.arg_instance_type&&"fe3e46eefe371d13bc9d9b45c5deaf3c"!==a.prototype.__md5__&&($p._isinstance(a,arguments.callee.__class__)||$pyjs__exception_func_instance_expected(arguments.callee.__name__,
arguments.callee.__class__.__name__,a));var d;$pyjs.track={module:"LogoDemo",lineno:105};$pyjs.trackstack.push($pyjs.track);$pyjs.track.module="LogoDemo";$pyjs.track.lineno=105;$pyjs.track.lineno=106;$pyjs.track.lineno=106;a=$p.bool(d=$p.hasattr(b,"__isLoaded"))?$p.getattr(b,"__isLoaded"):d;$pyjs.trackstack.pop();$pyjs.track=$pyjs.trackstack.pop();$pyjs.trackstack.push($pyjs.track);return a},1,[null,null,["self"],["imgElem"]]);e.isImageLoaded=d;$pyjs.track.lineno=108;d=$pyjs__bind_method2("renderingLoop",
function(){if(!0===this.__is_instance__){var a=this;$pyjs.options.arg_count&&0!=arguments.length&&$pyjs__exception_func_param(arguments.callee.__name__,1,1,arguments.length+1)}else a=arguments[0],$pyjs.options.arg_is_instance&&!0!==a.__is_instance__&&$pyjs__exception_func_instance_expected(arguments.callee.__name__,arguments.callee.__class__.__name__,a),$pyjs.options.arg_count&&1!=arguments.length&&$pyjs__exception_func_param(arguments.callee.__name__,1,1,arguments.length);$pyjs.options.arg_instance_type&&
"fe3e46eefe371d13bc9d9b45c5deaf3c"!==a.prototype.__md5__&&($p._isinstance(a,arguments.callee.__class__)||$pyjs__exception_func_instance_expected(arguments.callee.__name__,arguments.callee.__class__.__name__,a));$pyjs.track={module:"LogoDemo",lineno:108};$pyjs.trackstack.push($pyjs.track);$pyjs.track.module="LogoDemo";$pyjs.track.lineno=108;$pyjs.track.lineno=109;a.canvas.saveContext();$pyjs.track.lineno=111;a.canvas.clear();$pyjs.track.lineno=120;a.canvas.drawImage($p.getattr(a,"img"),s,q);$pyjs.track.lineno=
123;a.canvas.translate(r,p);$pyjs.track.lineno=124;a.canvas.rotate($p.getattr(a,"rotation"));$pyjs.track.lineno=125;a.canvas.scale(0.9,0.9);$pyjs.track.lineno=127;a.canvas.drawImage($p.getattr(a,"img"),k,k);$pyjs.track.lineno=128;a.__is_instance__&&"function"==typeof a.__setattr__?a.__setattr__("rotation",$p.__op_add($p.getattr(a,"rotation"),0.1)):$p.setattr(a,"rotation",$p.__op_add($p.getattr(a,"rotation"),0.1));$pyjs.track.lineno=130;a.canvas.restoreContext();$pyjs.trackstack.pop();$pyjs.track=
$pyjs.trackstack.pop();$pyjs.trackstack.push($pyjs.track);return null},1,[null,null,["self"]]);e.renderingLoop=d;$pyjs.track.lineno=134;d=$pyjs__bind_method2("onTimer",function(a){if(!0===this.__is_instance__){var c=this;$pyjs.options.arg_count&&1!=arguments.length&&$pyjs__exception_func_param(arguments.callee.__name__,2,2,arguments.length+1)}else c=arguments[0],a=arguments[1],$pyjs.options.arg_is_instance&&!0!==c.__is_instance__&&$pyjs__exception_func_instance_expected(arguments.callee.__name__,
arguments.callee.__class__.__name__,c),$pyjs.options.arg_count&&2!=arguments.length&&$pyjs__exception_func_param(arguments.callee.__name__,2,2,arguments.length);$pyjs.options.arg_instance_type&&"fe3e46eefe371d13bc9d9b45c5deaf3c"!==c.prototype.__md5__&&($p._isinstance(c,arguments.callee.__class__)||$pyjs__exception_func_instance_expected(arguments.callee.__name__,arguments.callee.__class__.__name__,c));$pyjs.track={module:"LogoDemo",lineno:134};$pyjs.trackstack.push($pyjs.track);$pyjs.track.module=
"LogoDemo";$pyjs.track.lineno=134;$pyjs.track.lineno=135;if($p.bool(!$p.bool($p.getattr(c,"run"))))return $pyjs.track.lineno=136,$pyjs.track.lineno=136,$pyjs.trackstack.pop(),$pyjs.track=$pyjs.trackstack.pop(),$pyjs.trackstack.push($pyjs.track),null;$pyjs.track.lineno=137;c.renderingLoop();$pyjs.track.lineno=138;a.schedule(t);$pyjs.trackstack.pop();$pyjs.track=$pyjs.trackstack.pop();$pyjs.trackstack.push($pyjs.track);return null},1,[null,null,["self"],["timer"]]);e.onTimer=d;$pyjs.track.lineno=39;
d=Array(a.SimpleCanvasDemo);var g=$p.dict(),f;for(f in e)g.__setitem__(f,e[f]);return $p._create_class("LogoDemo",$p.tuple(d),g)}()}catch(u){throw $p._errorMapping(u);}return this};
