$pyjs.loaded_modules.math=function(l){if($pyjs.loaded_modules.math.__was_initialized__)return $pyjs.loaded_modules.math;var a=$pyjs.loaded_modules.math;a.__repr__=function(){return"<module: math>"};a.__was_initialized__=!0;if(null===l||"undefined"==typeof l)l="math";a.__name__=l;a.__track_lines__=[];try{a.__track_lines__[1]="math.py, line 1:\n    from __pyjamas__ import JS";a.__track_lines__[3]="math.py, line 3:\n    def ceil(x): return float(JS(\"Math['ceil'](@{{x}}['valueOf']())\"))";a.__track_lines__[4]=
"math.py, line 4:\n    def fabs(x): return float(JS(\"Math['abs'](@{{x}}['valueOf']())\"))";a.__track_lines__[5]="math.py, line 5:\n    def floor(x): return float(JS(\"Math['floor'](@{{x}}['valueOf']())\"))";a.__track_lines__[6]="math.py, line 6:\n    def exp(x): return float(JS(\"Math['exp'](@{{x}}['valueOf']())\"))";a.__track_lines__[7]="math.py, line 7:\n    def log(x, base=None):";a.__track_lines__[8]="math.py, line 8:\n    if base is None:";a.__track_lines__[9]="math.py, line 9:\n    return float(JS(\"Math['log'](@{{x}}['valueOf']())\"))";
a.__track_lines__[10]="math.py, line 10:\n    return float(JS(\"Math['log'](@{{x}}['valueOf']()) / Math['log'](@{{base}}['valueOf']())\"))";a.__track_lines__[11]="math.py, line 11:\n    def pow(x, y): return float(JS(\"Math['pow'](@{{x}}['valueOf'](), @{{y}}['valueOf']())\"))";a.__track_lines__[12]="math.py, line 12:\n    def sqrt(x): return float(JS(\"Math['sqrt'](@{{x}}['valueOf']())\"))";a.__track_lines__[13]="math.py, line 13:\n    def cos(x): return float(JS(\"Math['cos'](@{{x}}['valueOf']())\"))";
a.__track_lines__[14]="math.py, line 14:\n    def sin(x): return float(JS(\"Math['sin'](@{{x}}['valueOf']())\"))";a.__track_lines__[15]="math.py, line 15:\n    def tan(x): return float(JS(\"Math['tan'](@{{x}}['valueOf']())\"))";a.__track_lines__[16]="math.py, line 16:\n    def acos(x): return float(JS(\"Math['acos'](@{{x}}['valueOf']())\"))";a.__track_lines__[17]="math.py, line 17:\n    def asin(x): return float(JS(\"Math['asin'](@{{x}}['valueOf']())\"))";a.__track_lines__[18]="math.py, line 18:\n    def atan(x): return float(JS(\"Math['atan'](@{{x}}['valueOf']())\"))";
a.__track_lines__[19]="math.py, line 19:\n    def atan2(x, y): return float(JS(\"Math['atan2'](@{{x}}['valueOf'](), @{{y}}['valueOf']())\"))";a.__track_lines__[21]="math.py, line 21:\n    pi = float(JS(\"Math['PI']\"))";a.__track_lines__[22]="math.py, line 22:\n    e = float(JS(\"Math['E']\"))";a.__track_lines__[23]="math.py, line 23:\n    __log10__ = float(JS(\"Math['LN10']\"))";a.__track_lines__[24]="math.py, line 24:\n    __log2__ = log(2)";a.__track_lines__[27]="math.py, line 27:\n    def fsum(x):";
a.__track_lines__[28]="math.py, line 28:\n    xx = [(fabs(v), i) for i, v in enumerate(x)]";a.__track_lines__[29]="math.py, line 29:\n    xx.sort()";a.__track_lines__[30]="math.py, line 30:\n    sum = 0";a.__track_lines__[31]="math.py, line 31:\n    for i in xx:";a.__track_lines__[32]="math.py, line 32:\n    sum += x[i[1]]";a.__track_lines__[33]="math.py, line 33:\n    return sum";a.__track_lines__[35]="math.py, line 35:\n    def frexp(x):";a.__track_lines__[36]="math.py, line 36:\n    global __log2__";
a.__track_lines__[37]="math.py, line 37:\n    if x == 0:";a.__track_lines__[38]="math.py, line 38:\n    return (0.0, 0)";a.__track_lines__[40]="math.py, line 40:\n    e = int(log(abs(x))/__log2__) + 1";a.__track_lines__[41]="math.py, line 41:\n    m = x / (2.**e)";a.__track_lines__[42]="math.py, line 42:\n    return (m,e)";a.__track_lines__[44]="math.py, line 44:\n    def ldexp(x, i):";a.__track_lines__[45]="math.py, line 45:\n    return x * (2**i)";a.__track_lines__[47]="math.py, line 47:\n    def log10 (arg):";
a.__track_lines__[48]="math.py, line 48:\n    return log(arg) / __log10__";a.__track_lines__[50]="math.py, line 50:\n    def degrees(x):";a.__track_lines__[51]="math.py, line 51:\n    return x * 180 / pi";a.__track_lines__[53]="math.py, line 53:\n    def radians(x):";a.__track_lines__[54]="math.py, line 54:\n    return x * pi / 180";a.__track_lines__[56]="math.py, line 56:\n    def hypot(x, y):";a.__track_lines__[58]="math.py, line 58:\n    x = abs(x)";a.__track_lines__[59]="math.py, line 59:\n    y = abs(y)";
a.__track_lines__[60]="math.py, line 60:\n    x, y = max(x, y), min(x, y)";a.__track_lines__[61]="math.py, line 61:\n    return x * sqrt(1 + (y/x) * (y/x))";var m=new $p["int"](0),p=new $p["int"](1),h=new $p["int"](2),g=new $p["int"](180);$pyjs.track.module="math";$pyjs.track.lineno=1;$pyjs.track.lineno=1;$pyjs.track.lineno=3;a.ceil=function(a){$pyjs.options.arg_count&&1!=arguments.length&&$pyjs__exception_func_param(arguments.callee.__name__,1,1,arguments.length);$pyjs.track={module:"math",lineno:3};
$pyjs.trackstack.push($pyjs.track);$pyjs.track.module="math";$pyjs.track.lineno=3;$pyjs.track.lineno=3;$pyjs.track.lineno=3;var b=$p["float"](Math.ceil(a.valueOf()));$pyjs.trackstack.pop();$pyjs.track=$pyjs.trackstack.pop();$pyjs.trackstack.push($pyjs.track);return b};a.ceil.__name__="ceil";a.ceil.__bind_type__=0;a.ceil.__args__=[null,null,["x"]];$pyjs.track.lineno=4;a.fabs=function(a){$pyjs.options.arg_count&&1!=arguments.length&&$pyjs__exception_func_param(arguments.callee.__name__,1,1,arguments.length);
$pyjs.track={module:"math",lineno:4};$pyjs.trackstack.push($pyjs.track);$pyjs.track.module="math";$pyjs.track.lineno=4;$pyjs.track.lineno=4;$pyjs.track.lineno=4;var b=$p["float"](Math.abs(a.valueOf()));$pyjs.trackstack.pop();$pyjs.track=$pyjs.trackstack.pop();$pyjs.trackstack.push($pyjs.track);return b};a.fabs.__name__="fabs";a.fabs.__bind_type__=0;a.fabs.__args__=[null,null,["x"]];$pyjs.track.lineno=5;a.floor=function(a){$pyjs.options.arg_count&&1!=arguments.length&&$pyjs__exception_func_param(arguments.callee.__name__,
1,1,arguments.length);$pyjs.track={module:"math",lineno:5};$pyjs.trackstack.push($pyjs.track);$pyjs.track.module="math";$pyjs.track.lineno=5;$pyjs.track.lineno=5;$pyjs.track.lineno=5;var b=$p["float"](Math.floor(a.valueOf()));$pyjs.trackstack.pop();$pyjs.track=$pyjs.trackstack.pop();$pyjs.trackstack.push($pyjs.track);return b};a.floor.__name__="floor";a.floor.__bind_type__=0;a.floor.__args__=[null,null,["x"]];$pyjs.track.lineno=6;a.exp=function(a){$pyjs.options.arg_count&&1!=arguments.length&&$pyjs__exception_func_param(arguments.callee.__name__,
1,1,arguments.length);$pyjs.track={module:"math",lineno:6};$pyjs.trackstack.push($pyjs.track);$pyjs.track.module="math";$pyjs.track.lineno=6;$pyjs.track.lineno=6;$pyjs.track.lineno=6;var b=$p["float"](Math.exp(a.valueOf()));$pyjs.trackstack.pop();$pyjs.track=$pyjs.trackstack.pop();$pyjs.trackstack.push($pyjs.track);return b};a.exp.__name__="exp";a.exp.__bind_type__=0;a.exp.__args__=[null,null,["x"]];$pyjs.track.lineno=7;a.log=function(a,b){$pyjs.options.arg_count&&(1>arguments.length||2<arguments.length)&&
$pyjs__exception_func_param(arguments.callee.__name__,1,2,arguments.length);"undefined"==typeof b&&(b=arguments.callee.__args__[3][1]);$pyjs.track={module:"math",lineno:7};$pyjs.trackstack.push($pyjs.track);$pyjs.track.module="math";$pyjs.track.lineno=7;$pyjs.track.lineno=8;if($p.bool($p.op_is(b,null))){$pyjs.track.lineno=9;$pyjs.track.lineno=9;var c=$p["float"](Math.log(a.valueOf()));$pyjs.trackstack.pop();$pyjs.track=$pyjs.trackstack.pop();$pyjs.trackstack.push($pyjs.track);return c}$pyjs.track.lineno=
10;$pyjs.track.lineno=10;c=$p["float"](Math.log(a.valueOf())/Math.log(b.valueOf()));$pyjs.trackstack.pop();$pyjs.track=$pyjs.trackstack.pop();$pyjs.trackstack.push($pyjs.track);return c};a.log.__name__="log";a.log.__bind_type__=0;a.log.__args__=[null,null,["x"],["base",null]];$pyjs.track.lineno=11;a.pow=function(a,b){$pyjs.options.arg_count&&2!=arguments.length&&$pyjs__exception_func_param(arguments.callee.__name__,2,2,arguments.length);$pyjs.track={module:"math",lineno:11};$pyjs.trackstack.push($pyjs.track);
$pyjs.track.module="math";$pyjs.track.lineno=11;$pyjs.track.lineno=11;$pyjs.track.lineno=11;var c=$p["float"](Math.pow(a.valueOf(),b.valueOf()));$pyjs.trackstack.pop();$pyjs.track=$pyjs.trackstack.pop();$pyjs.trackstack.push($pyjs.track);return c};a.pow.__name__="pow";a.pow.__bind_type__=0;a.pow.__args__=[null,null,["x"],["y"]];$pyjs.track.lineno=12;a.sqrt=function(a){$pyjs.options.arg_count&&1!=arguments.length&&$pyjs__exception_func_param(arguments.callee.__name__,1,1,arguments.length);$pyjs.track=
{module:"math",lineno:12};$pyjs.trackstack.push($pyjs.track);$pyjs.track.module="math";$pyjs.track.lineno=12;$pyjs.track.lineno=12;$pyjs.track.lineno=12;var b=$p["float"](Math.sqrt(a.valueOf()));$pyjs.trackstack.pop();$pyjs.track=$pyjs.trackstack.pop();$pyjs.trackstack.push($pyjs.track);return b};a.sqrt.__name__="sqrt";a.sqrt.__bind_type__=0;a.sqrt.__args__=[null,null,["x"]];$pyjs.track.lineno=13;a.cos=function(a){$pyjs.options.arg_count&&1!=arguments.length&&$pyjs__exception_func_param(arguments.callee.__name__,
1,1,arguments.length);$pyjs.track={module:"math",lineno:13};$pyjs.trackstack.push($pyjs.track);$pyjs.track.module="math";$pyjs.track.lineno=13;$pyjs.track.lineno=13;$pyjs.track.lineno=13;var b=$p["float"](Math.cos(a.valueOf()));$pyjs.trackstack.pop();$pyjs.track=$pyjs.trackstack.pop();$pyjs.trackstack.push($pyjs.track);return b};a.cos.__name__="cos";a.cos.__bind_type__=0;a.cos.__args__=[null,null,["x"]];$pyjs.track.lineno=14;a.sin=function(a){$pyjs.options.arg_count&&1!=arguments.length&&$pyjs__exception_func_param(arguments.callee.__name__,
1,1,arguments.length);$pyjs.track={module:"math",lineno:14};$pyjs.trackstack.push($pyjs.track);$pyjs.track.module="math";$pyjs.track.lineno=14;$pyjs.track.lineno=14;$pyjs.track.lineno=14;var b=$p["float"](Math.sin(a.valueOf()));$pyjs.trackstack.pop();$pyjs.track=$pyjs.trackstack.pop();$pyjs.trackstack.push($pyjs.track);return b};a.sin.__name__="sin";a.sin.__bind_type__=0;a.sin.__args__=[null,null,["x"]];$pyjs.track.lineno=15;a.tan=function(a){$pyjs.options.arg_count&&1!=arguments.length&&$pyjs__exception_func_param(arguments.callee.__name__,
1,1,arguments.length);$pyjs.track={module:"math",lineno:15};$pyjs.trackstack.push($pyjs.track);$pyjs.track.module="math";$pyjs.track.lineno=15;$pyjs.track.lineno=15;$pyjs.track.lineno=15;var b=$p["float"](Math.tan(a.valueOf()));$pyjs.trackstack.pop();$pyjs.track=$pyjs.trackstack.pop();$pyjs.trackstack.push($pyjs.track);return b};a.tan.__name__="tan";a.tan.__bind_type__=0;a.tan.__args__=[null,null,["x"]];$pyjs.track.lineno=16;a.acos=function(a){$pyjs.options.arg_count&&1!=arguments.length&&$pyjs__exception_func_param(arguments.callee.__name__,
1,1,arguments.length);$pyjs.track={module:"math",lineno:16};$pyjs.trackstack.push($pyjs.track);$pyjs.track.module="math";$pyjs.track.lineno=16;$pyjs.track.lineno=16;$pyjs.track.lineno=16;var b=$p["float"](Math.acos(a.valueOf()));$pyjs.trackstack.pop();$pyjs.track=$pyjs.trackstack.pop();$pyjs.trackstack.push($pyjs.track);return b};a.acos.__name__="acos";a.acos.__bind_type__=0;a.acos.__args__=[null,null,["x"]];$pyjs.track.lineno=17;a.asin=function(a){$pyjs.options.arg_count&&1!=arguments.length&&$pyjs__exception_func_param(arguments.callee.__name__,
1,1,arguments.length);$pyjs.track={module:"math",lineno:17};$pyjs.trackstack.push($pyjs.track);$pyjs.track.module="math";$pyjs.track.lineno=17;$pyjs.track.lineno=17;$pyjs.track.lineno=17;var b=$p["float"](Math.asin(a.valueOf()));$pyjs.trackstack.pop();$pyjs.track=$pyjs.trackstack.pop();$pyjs.trackstack.push($pyjs.track);return b};a.asin.__name__="asin";a.asin.__bind_type__=0;a.asin.__args__=[null,null,["x"]];$pyjs.track.lineno=18;a.atan=function(a){$pyjs.options.arg_count&&1!=arguments.length&&$pyjs__exception_func_param(arguments.callee.__name__,
1,1,arguments.length);$pyjs.track={module:"math",lineno:18};$pyjs.trackstack.push($pyjs.track);$pyjs.track.module="math";$pyjs.track.lineno=18;$pyjs.track.lineno=18;$pyjs.track.lineno=18;var b=$p["float"](Math.atan(a.valueOf()));$pyjs.trackstack.pop();$pyjs.track=$pyjs.trackstack.pop();$pyjs.trackstack.push($pyjs.track);return b};a.atan.__name__="atan";a.atan.__bind_type__=0;a.atan.__args__=[null,null,["x"]];$pyjs.track.lineno=19;a.atan2=function(a,b){$pyjs.options.arg_count&&2!=arguments.length&&
$pyjs__exception_func_param(arguments.callee.__name__,2,2,arguments.length);$pyjs.track={module:"math",lineno:19};$pyjs.trackstack.push($pyjs.track);$pyjs.track.module="math";$pyjs.track.lineno=19;$pyjs.track.lineno=19;$pyjs.track.lineno=19;var c=$p["float"](Math.atan2(a.valueOf(),b.valueOf()));$pyjs.trackstack.pop();$pyjs.track=$pyjs.trackstack.pop();$pyjs.trackstack.push($pyjs.track);return c};a.atan2.__name__="atan2";a.atan2.__bind_type__=0;a.atan2.__args__=[null,null,["x"],["y"]];$pyjs.track.lineno=
21;a.pi=$p["float"](Math.PI);$pyjs.track.lineno=22;a.e=$p["float"](Math.E);$pyjs.track.lineno=23;a.__log10__=$p["float"](Math.LN10);$pyjs.track.lineno=24;a.__log2__=a.log(h);$pyjs.track.lineno=27;a.fsum=function(d){$pyjs.options.arg_count&&1!=arguments.length&&$pyjs__exception_func_param(arguments.callee.__name__,1,1,arguments.length);var b,c,e,f;$pyjs.track={module:"math",lineno:27};$pyjs.trackstack.push($pyjs.track);$pyjs.track.module="math";$pyjs.track.lineno=27;$pyjs.track.lineno=28;var k;b=$p.list();
e=$pyjs.trackstack.length;f=$p.enumerate(d);for(f=$p.__iter_prepare(f,!1);"undefined"!=typeof $p.__wrapped_next(f).$nextval;)k=$p.__ass_unpack(f.$nextval,2,null),c=k[0],k=k[1],b.append($p.tuple([a.fabs(k),c]));$pyjs.trackstack.length>e&&($pyjs.trackstack=$pyjs.trackstack.slice(0,e),$pyjs.track=$pyjs.trackstack.slice(-1)[0]);$pyjs.track.module="math";$pyjs.track.lineno=29;b.sort();$pyjs.track.lineno=30;e=m;$pyjs.track.lineno=31;f=$pyjs.trackstack.length;for(b=$p.__iter_prepare(b,!1);"undefined"!=typeof $p.__wrapped_next(b).$nextval;)c=
b.$nextval,$pyjs.track.lineno=32,e=$p.__op_add(e,d.__getitem__(c.__getitem__(p)));$pyjs.trackstack.length>f&&($pyjs.trackstack=$pyjs.trackstack.slice(0,f),$pyjs.track=$pyjs.trackstack.slice(-1)[0]);$pyjs.track.module="math";$pyjs.track.lineno=33;$pyjs.track.lineno=33;b=e;$pyjs.trackstack.pop();$pyjs.track=$pyjs.trackstack.pop();$pyjs.trackstack.push($pyjs.track);return b};a.fsum.__name__="fsum";a.fsum.__bind_type__=0;a.fsum.__args__=[null,null,["x"]];$pyjs.track.lineno=35;a.frexp=function(d){$pyjs.options.arg_count&&
1!=arguments.length&&$pyjs__exception_func_param(arguments.callee.__name__,1,1,arguments.length);var b,c,e,f;$pyjs.track={module:"math",lineno:35};$pyjs.trackstack.push($pyjs.track);$pyjs.track.module="math";$pyjs.track.lineno=35;$pyjs.track.lineno=36;$pyjs.track.lineno=37;if($p.bool($p.op_eq(d,m)))return $pyjs.track.lineno=38,$pyjs.track.lineno=38,b=$p.tuple([0,m]),$pyjs.trackstack.pop(),$pyjs.track=$pyjs.trackstack.pop(),$pyjs.trackstack.push($pyjs.track),b;$pyjs.track.lineno=40;b=$p.__op_add($p["int"](typeof(e=
a.log($p.abs(d)))==typeof(c=a.__log2__)&&"number"==typeof e&&0!==c?e/c:$p.op_div(e,c)),p);$pyjs.track.lineno=41;c=typeof d==typeof(f="number"==typeof b?Math.pow(2,b):$p.op_pow(2,b))&&"number"==typeof d&&0!==f?d/f:$p.op_div(d,f);$pyjs.track.lineno=42;$pyjs.track.lineno=42;b=$p.tuple([c,b]);$pyjs.trackstack.pop();$pyjs.track=$pyjs.trackstack.pop();$pyjs.trackstack.push($pyjs.track);return b};a.frexp.__name__="frexp";a.frexp.__bind_type__=0;a.frexp.__args__=[null,null,["x"]];$pyjs.track.lineno=44;a.ldexp=
function(a,b){$pyjs.options.arg_count&&2!=arguments.length&&$pyjs__exception_func_param(arguments.callee.__name__,2,2,arguments.length);var c;$pyjs.track={module:"math",lineno:44};$pyjs.trackstack.push($pyjs.track);$pyjs.track.module="math";$pyjs.track.lineno=44;$pyjs.track.lineno=45;$pyjs.track.lineno=45;var e=typeof a==typeof(c=typeof h==typeof b&&"number"==typeof h?Math.pow(h,b):$p.op_pow(h,b))&&"number"==typeof a?a*c:$p.op_mul(a,c);$pyjs.trackstack.pop();$pyjs.track=$pyjs.trackstack.pop();$pyjs.trackstack.push($pyjs.track);
return e};a.ldexp.__name__="ldexp";a.ldexp.__bind_type__=0;a.ldexp.__args__=[null,null,["x"],["i"]];$pyjs.track.lineno=47;a.log10=function(d){$pyjs.options.arg_count&&1!=arguments.length&&$pyjs__exception_func_param(arguments.callee.__name__,1,1,arguments.length);var b,c;$pyjs.track={module:"math",lineno:47};$pyjs.trackstack.push($pyjs.track);$pyjs.track.module="math";$pyjs.track.lineno=47;$pyjs.track.lineno=48;$pyjs.track.lineno=48;var e=typeof(b=a.log(d))==typeof(c=a.__log10__)&&"number"==typeof b&&
0!==c?b/c:$p.op_div(b,c);$pyjs.trackstack.pop();$pyjs.track=$pyjs.trackstack.pop();$pyjs.trackstack.push($pyjs.track);return e};a.log10.__name__="log10";a.log10.__bind_type__=0;a.log10.__args__=[null,null,["arg"]];$pyjs.track.lineno=50;a.degrees=function(d){$pyjs.options.arg_count&&1!=arguments.length&&$pyjs__exception_func_param(arguments.callee.__name__,1,1,arguments.length);var b,c;$pyjs.track={module:"math",lineno:50};$pyjs.trackstack.push($pyjs.track);$pyjs.track.module="math";$pyjs.track.lineno=
50;$pyjs.track.lineno=51;$pyjs.track.lineno=51;var e=typeof(c=typeof d==typeof g&&"number"==typeof d?d*g:$p.op_mul(d,g))==typeof(b=a.pi)&&"number"==typeof c&&0!==b?c/b:$p.op_div(c,b);$pyjs.trackstack.pop();$pyjs.track=$pyjs.trackstack.pop();$pyjs.trackstack.push($pyjs.track);return e};a.degrees.__name__="degrees";a.degrees.__bind_type__=0;a.degrees.__args__=[null,null,["x"]];$pyjs.track.lineno=53;a.radians=function(d){$pyjs.options.arg_count&&1!=arguments.length&&$pyjs__exception_func_param(arguments.callee.__name__,
1,1,arguments.length);var b,c;$pyjs.track={module:"math",lineno:53};$pyjs.trackstack.push($pyjs.track);$pyjs.track.module="math";$pyjs.track.lineno=53;$pyjs.track.lineno=54;$pyjs.track.lineno=54;var e=typeof(b=typeof d==typeof(c=a.pi)&&"number"==typeof d?d*c:$p.op_mul(d,c))==typeof g&&"number"==typeof b&&0!==g?b/g:$p.op_div(b,g);$pyjs.trackstack.pop();$pyjs.track=$pyjs.trackstack.pop();$pyjs.trackstack.push($pyjs.track);return e};a.radians.__name__="radians";a.radians.__bind_type__=0;a.radians.__args__=
[null,null,["x"]];$pyjs.track.lineno=56;a.hypot=function(d,b){$pyjs.options.arg_count&&2!=arguments.length&&$pyjs__exception_func_param(arguments.callee.__name__,2,2,arguments.length);var c,e,f,k,g,h,l,m;$pyjs.track={module:"math",lineno:56};$pyjs.trackstack.push($pyjs.track);$pyjs.track.module="math";$pyjs.track.lineno=56;$pyjs.track.lineno=58;d=$p.abs(d);$pyjs.track.lineno=59;b=$p.abs(b);$pyjs.track.lineno=60;var n=$p.__ass_unpack($p.tuple([$p.max(d,b),$p.min(d,b)]),2,null);d=n[0];b=n[1];$pyjs.track.lineno=
61;$pyjs.track.lineno=61;n=typeof(l=d)==typeof(c=a.sqrt($p.__op_add(p,typeof(h=typeof(f=b)==typeof(k=d)&&"number"==typeof f&&0!==k?f/k:$p.op_div(f,k))==typeof(m=typeof(g=b)==typeof(e=d)&&"number"==typeof g&&0!==e?g/e:$p.op_div(g,e))&&"number"==typeof h?h*m:$p.op_mul(h,m))))&&"number"==typeof l?l*c:$p.op_mul(l,c);$pyjs.trackstack.pop();$pyjs.track=$pyjs.trackstack.pop();$pyjs.trackstack.push($pyjs.track);return n};a.hypot.__name__="hypot";a.hypot.__bind_type__=0;a.hypot.__args__=[null,null,["x"],["y"]]}catch(q){throw $p._errorMapping(q);
}return this};
