$pyjs.loaded_modules.pygwt=function(d){if($pyjs.loaded_modules.pygwt.__was_initialized__)return $pyjs.loaded_modules.pygwt;var a=$pyjs.loaded_modules.pygwt;a.__repr__=function(){return"<module: pygwt>"};a.__was_initialized__=!0;if(null===d||"undefined"==typeof d)d="pygwt";a.__name__=d;a.__track_lines__=[];try{a.__track_lines__[1]="pygwt.py, line 1:\n    from __pyjamas__ import get_main_frame, doc, JS";a.__track_lines__[3]="pygwt.py, line 3:\n    sNextHashId = 0";a.__track_lines__[5]="pygwt.py, line 5:\n    def getNextHashId():";
a.__track_lines__[6]="pygwt.py, line 6:\n    global sNextHashId";a.__track_lines__[7]="pygwt.py, line 7:\n    sNextHashId += 1";a.__track_lines__[8]="pygwt.py, line 8:\n    return sNextHashId";a.__track_lines__[10]="pygwt.py, line 10:\n    def getHashCode(o):";a.__track_lines__[11]='pygwt.py, line 11:\n    JS("""';a.__track_lines__[16]="pygwt.py, line 16:\n    def getModuleName():";a.__track_lines__[17]="pygwt.py, line 17:\n    import os";a.__track_lines__[18]="pygwt.py, line 18:\n    import sys";
a.__track_lines__[19]="pygwt.py, line 19:\n    mod_name = sys.argv[0]";a.__track_lines__[20]="pygwt.py, line 20:\n    mod_name = os.path.split(mod_name)[1]";a.__track_lines__[21]="pygwt.py, line 21:\n    mod_name = os.path.spliext(mod_name)[0]";a.__track_lines__[22]="pygwt.py, line 22:\n    return mod_name";a.__track_lines__[24]="pygwt.py, line 24:\n    def getModuleBaseURL():";a.__track_lines__[25]="pygwt.py, line 25:\n    import os.path";a.__track_lines__[28]="pygwt.py, line 28:\n    s = get_main_frame().getUri()";
a.__track_lines__[31]="pygwt.py, line 31:\n    s = os.path.dirname(s)";a.__track_lines__[33]="pygwt.py, line 33:\n    if len(s) > 0:";a.__track_lines__[34]='pygwt.py, line 34:\n    return s + "/"';a.__track_lines__[35]='pygwt.py, line 35:\n    return ""';a.__track_lines__[37]="pygwt.py, line 37:\n    def getImageBaseURL(images=False):";a.__track_lines__[38]="pygwt.py, line 38:\n    import pyjd";a.__track_lines__[40]="pygwt.py, line 40:\n    if images:";a.__track_lines__[41]="pygwt.py, line 41:\n    if isinstance(images, str):";
a.__track_lines__[42]="pygwt.py, line 42:\n    return getModuleBaseURL() + images + '/'";a.__track_lines__[44]='pygwt.py, line 44:\n    return getModuleBaseURL() + "images/"';a.__track_lines__[46]="pygwt.py, line 46:\n    return getModuleBaseURL()";var e=new $p["int"](0),f=new $p["int"](1);$pyjs.track.module="pygwt";$pyjs.track.lineno=1;$pyjs.track.lineno=1;$pyjs.track.lineno=3;a.sNextHashId=e;$pyjs.track.lineno=5;a.getNextHashId=function(){$pyjs.options.arg_count&&0!=arguments.length&&$pyjs__exception_func_param(arguments.callee.__name__,
0,0,arguments.length);$pyjs.track={module:"pygwt",lineno:5};$pyjs.trackstack.push($pyjs.track);$pyjs.track.module="pygwt";$pyjs.track.lineno=5;$pyjs.track.lineno=6;$pyjs.track.lineno=7;a.sNextHashId=$p.__op_add(a.sNextHashId,f);$pyjs.track.lineno=8;$pyjs.track.lineno=8;var b=a.sNextHashId;$pyjs.trackstack.pop();$pyjs.track=$pyjs.trackstack.pop();$pyjs.trackstack.push($pyjs.track);return b};a.getNextHashId.__name__="getNextHashId";a.getNextHashId.__bind_type__=0;a.getNextHashId.__args__=[null,null];
$pyjs.track.lineno=10;a.getHashCode=function(a){$pyjs.options.arg_count&&1!=arguments.length&&$pyjs__exception_func_param(arguments.callee.__name__,1,1,arguments.length);return null==a?0:a.$H?a.$H:a.$H=pygwt_getNextHashId()};a.getHashCode.__name__="getHashCode";a.getHashCode.__bind_type__=0;a.getHashCode.__args__=[null,null,["o"]];$pyjs.track.lineno=16;a.getModuleName=function(){$pyjs.options.arg_count&&0!=arguments.length&&$pyjs__exception_func_param(arguments.callee.__name__,0,0,arguments.length);
var a,c;$pyjs.track={module:"pygwt",lineno:16};$pyjs.trackstack.push($pyjs.track);$pyjs.track.module="pygwt";$pyjs.track.lineno=16;$pyjs.track.lineno=17;$pyjs.track={module:$pyjs.track.module,lineno:$pyjs.track.lineno};$pyjs.trackstack.push($pyjs.track);c=$p.___import___("os",null);$pyjs.trackstack.pop();$pyjs.track=$pyjs.trackstack.pop();$pyjs.trackstack.push($pyjs.track);$pyjs.track.lineno=18;$pyjs.track={module:$pyjs.track.module,lineno:$pyjs.track.lineno};$pyjs.trackstack.push($pyjs.track);a=
$p.___import___("sys",null);$pyjs.trackstack.pop();$pyjs.track=$pyjs.trackstack.pop();$pyjs.trackstack.push($pyjs.track);$pyjs.track.lineno=19;a=$p.getattr(a,"argv").__getitem__(e);$pyjs.track.lineno=20;a=c.path.$$split(a).__getitem__(f);$pyjs.track.lineno=21;a=c.path.spliext(a).__getitem__(e);$pyjs.track.lineno=22;$pyjs.track.lineno=22;c=a;$pyjs.trackstack.pop();$pyjs.track=$pyjs.trackstack.pop();$pyjs.trackstack.push($pyjs.track);return c};a.getModuleName.__name__="getModuleName";a.getModuleName.__bind_type__=
0;a.getModuleName.__args__=[null,null];$pyjs.track.lineno=24;a.getModuleBaseURL=function(){$pyjs.options.arg_count&&0!=arguments.length&&$pyjs__exception_func_param(arguments.callee.__name__,0,0,arguments.length);var b,c;$pyjs.track={module:"pygwt",lineno:24};$pyjs.trackstack.push($pyjs.track);$pyjs.track.module="pygwt";$pyjs.track.lineno=24;$pyjs.track.lineno=25;$pyjs.track={module:$pyjs.track.module,lineno:$pyjs.track.lineno};$pyjs.trackstack.push($pyjs.track);c=$p.___import___("os.path",null);
$pyjs.trackstack.pop();$pyjs.track=$pyjs.trackstack.pop();$pyjs.trackstack.push($pyjs.track);$pyjs.track.lineno=28;b=a.get_main_frame().getUri();$pyjs.track.lineno=31;b=c.path.dirname(b);$pyjs.track.lineno=33;if($p.bool(1==$p.cmp($p.len(b),e)))return $pyjs.track.lineno=34,$pyjs.track.lineno=34,b=$p.__op_add(b,"/"),$pyjs.trackstack.pop(),$pyjs.track=$pyjs.trackstack.pop(),$pyjs.trackstack.push($pyjs.track),b;$pyjs.track.lineno=35;$pyjs.track.lineno=35;b="";$pyjs.trackstack.pop();$pyjs.track=$pyjs.trackstack.pop();
$pyjs.trackstack.push($pyjs.track);return b};a.getModuleBaseURL.__name__="getModuleBaseURL";a.getModuleBaseURL.__bind_type__=0;a.getModuleBaseURL.__args__=[null,null];$pyjs.track.lineno=37;a.getImageBaseURL=function(b){$pyjs.options.arg_count&&(0>arguments.length||1<arguments.length)&&$pyjs__exception_func_param(arguments.callee.__name__,0,1,arguments.length);"undefined"==typeof b&&(b=arguments.callee.__args__[2][1]);$pyjs.track={module:"pygwt",lineno:37};$pyjs.trackstack.push($pyjs.track);$pyjs.track.module=
"pygwt";$pyjs.track.lineno=37;$pyjs.track.lineno=38;$pyjs.track={module:$pyjs.track.module,lineno:$pyjs.track.lineno};$pyjs.trackstack.push($pyjs.track);$p.___import___("pyjd",null);$pyjs.trackstack.pop();$pyjs.track=$pyjs.trackstack.pop();$pyjs.trackstack.push($pyjs.track);$pyjs.track.lineno=40;if($p.bool(b))if($pyjs.track.lineno=41,$p.bool($p.isinstance(b,$p.str))){$pyjs.track.lineno=42;$pyjs.track.lineno=42;var c=$p.__op_add($p.__op_add(a.getModuleBaseURL(),b),"/")}else $pyjs.track.lineno=44,$pyjs.track.lineno=
44,c=$p.__op_add(a.getModuleBaseURL(),"images/");else $pyjs.track.lineno=46,$pyjs.track.lineno=46,c=a.getModuleBaseURL();$pyjs.trackstack.pop();$pyjs.track=$pyjs.trackstack.pop();$pyjs.trackstack.push($pyjs.track);return c};a.getImageBaseURL.__name__="getImageBaseURL";a.getImageBaseURL.__bind_type__=0;a.getImageBaseURL.__args__=[null,null,["images",!1]]}catch(g){throw $p._errorMapping(g);}return this};
