$pyjs.loaded_modules["pyjamas.ui.Image"]=function(g){if($pyjs.loaded_modules["pyjamas.ui.Image"].__was_initialized__)return $pyjs.loaded_modules["pyjamas.ui.Image"];"undefined"!=typeof $pyjs.loaded_modules["pyjamas.ui"]&&$pyjs.loaded_modules["pyjamas.ui"].__was_initialized__||$p.___import___("pyjamas.ui",null);var a=$pyjs.loaded_modules["pyjamas.ui.Image"];a.__repr__=function(){return"<module: pyjamas.ui.Image>"};a.__was_initialized__=!0;if(null===g||"undefined"==typeof g)g="pyjamas.ui.Image";a.__name__=
g;a.__track_lines__=[];$pyjs.loaded_modules["pyjamas.ui"].Image=$pyjs.loaded_modules["pyjamas.ui.Image"];try{a.__track_lines__[1]="pyjamas.ui.Image.py, line 1:\n    # Copyright 2006 James Tauber and contributors",a.__track_lines__[15]="pyjamas.ui.Image.py, line 15:\n    from pyjamas import DOM",a.__track_lines__[16]="pyjamas.ui.Image.py, line 16:\n    from pyjamas import Factory",a.__track_lines__[18]="pyjamas.ui.Image.py, line 18:\n    from pyjamas.ui.Widget import Widget",a.__track_lines__[19]=
"pyjamas.ui.Image.py, line 19:\n    from pyjamas.ui import Event",a.__track_lines__[20]="pyjamas.ui.Image.py, line 20:\n    from pyjamas.ui.MouseListener import MouseHandler",a.__track_lines__[21]="pyjamas.ui.Image.py, line 21:\n    from pyjamas.ui.ClickListener import ClickHandler",a.__track_lines__[23]="pyjamas.ui.Image.py, line 23:\n    prefetchImages = {}",a.__track_lines__[25]="pyjamas.ui.Image.py, line 25:\n    class Image(Widget, MouseHandler, ClickHandler):",a.__track_lines__[27]='pyjamas.ui.Image.py, line 27:\n    _props = [("url", "Url", "Url", None),',
a.__track_lines__[30]='pyjamas.ui.Image.py, line 30:\n    def __init__(self, url="", **kwargs):',a.__track_lines__[31]="pyjamas.ui.Image.py, line 31:\n    if not kwargs.has_key('StyleName'): kwargs['StyleName']=\"gwt-Image\"",a.__track_lines__[32]="pyjamas.ui.Image.py, line 32:\n    if url: kwargs['Url'] = url",a.__track_lines__[34]="pyjamas.ui.Image.py, line 34:\n    self.setElement(kwargs.pop('Element', None) or DOM.createImg())",a.__track_lines__[35]="pyjamas.ui.Image.py, line 35:\n    Widget.__init__(self, **kwargs)",
a.__track_lines__[36]="pyjamas.ui.Image.py, line 36:\n    MouseHandler.__init__(self)",a.__track_lines__[37]="pyjamas.ui.Image.py, line 37:\n    ClickHandler.__init__(self)",a.__track_lines__[38]="pyjamas.ui.Image.py, line 38:\n    self.sinkEvents(Event.ONLOAD | Event.ONERROR)",a.__track_lines__[39]="pyjamas.ui.Image.py, line 39:\n    self.loadListeners = []",a.__track_lines__[42]="pyjamas.ui.Image.py, line 41:\n    @classmethod ... def _getProps(self):",a.__track_lines__[43]="pyjamas.ui.Image.py, line 43:\n    return Widget._getProps() + self._props",
a.__track_lines__[45]="pyjamas.ui.Image.py, line 45:\n    def addLoadListener(self, listener):",a.__track_lines__[46]="pyjamas.ui.Image.py, line 46:\n    self.loadListeners.append(listener)",a.__track_lines__[48]="pyjamas.ui.Image.py, line 48:\n    def removeLoadListener(self, listener):",a.__track_lines__[49]="pyjamas.ui.Image.py, line 49:\n    self.loadListeners.remove(listener)",a.__track_lines__[51]="pyjamas.ui.Image.py, line 51:\n    def getUrl(self):",a.__track_lines__[52]='pyjamas.ui.Image.py, line 52:\n    return DOM.getAttribute(self.getElement(), "src")',
a.__track_lines__[54]="pyjamas.ui.Image.py, line 54:\n    def onBrowserEvent(self, event):",a.__track_lines__[55]="pyjamas.ui.Image.py, line 55:\n    Widget.onBrowserEvent(self, event)",a.__track_lines__[56]="pyjamas.ui.Image.py, line 56:\n    type = DOM.eventGetType(event)",a.__track_lines__[57]='pyjamas.ui.Image.py, line 57:\n    if type == "load":',a.__track_lines__[58]="pyjamas.ui.Image.py, line 58:\n    for listener in self.loadListeners:",a.__track_lines__[59]="pyjamas.ui.Image.py, line 59:\n    listener.onImageLoad(self)",
a.__track_lines__[61]="pyjamas.ui.Image.py, line 61:\n    for listener in self.loadListeners:",a.__track_lines__[62]="pyjamas.ui.Image.py, line 62:\n    listener.onImageError(self)",a.__track_lines__[64]="pyjamas.ui.Image.py, line 64:\n    def prefetch(self, url):",a.__track_lines__[65]="pyjamas.ui.Image.py, line 65:\n    img = DOM.createImg()",a.__track_lines__[66]='pyjamas.ui.Image.py, line 66:\n    DOM.setElemAttribute(img, "src", url)',a.__track_lines__[67]="pyjamas.ui.Image.py, line 67:\n    prefetchImages[url] = img",
a.__track_lines__[69]="pyjamas.ui.Image.py, line 69:\n    def setUrl(self, url):",a.__track_lines__[70]='pyjamas.ui.Image.py, line 70:\n    DOM.setElemAttribute(self.getElement(), "src", url)',a.__track_lines__[72]="pyjamas.ui.Image.py, line 72:\n    Factory.registerClass('pyjamas.ui.Image', 'Image', Image)",$pyjs.track.module="pyjamas.ui.Image",$pyjs.track.lineno=1,$pyjs.track.lineno=15,$pyjs.track={module:$pyjs.track.module,lineno:$pyjs.track.lineno},$pyjs.trackstack.push($pyjs.track),a.DOM=$p.___import___("pyjamas.DOM",
"pyjamas.ui",null,!1),$pyjs.trackstack.pop(),$pyjs.track=$pyjs.trackstack.pop(),$pyjs.trackstack.push($pyjs.track),$pyjs.track.lineno=16,$pyjs.track={module:$pyjs.track.module,lineno:$pyjs.track.lineno},$pyjs.trackstack.push($pyjs.track),a.Factory=$p.___import___("pyjamas.Factory","pyjamas.ui",null,!1),$pyjs.trackstack.pop(),$pyjs.track=$pyjs.trackstack.pop(),$pyjs.trackstack.push($pyjs.track),$pyjs.track.lineno=18,$pyjs.track={module:$pyjs.track.module,lineno:$pyjs.track.lineno},$pyjs.trackstack.push($pyjs.track),
a.Widget=$p.___import___("pyjamas.ui.Widget.Widget","pyjamas.ui",null,!1),$pyjs.trackstack.pop(),$pyjs.track=$pyjs.trackstack.pop(),$pyjs.trackstack.push($pyjs.track),$pyjs.track.lineno=19,$pyjs.track={module:$pyjs.track.module,lineno:$pyjs.track.lineno},$pyjs.trackstack.push($pyjs.track),a.Event=$p.___import___("pyjamas.ui.Event","pyjamas.ui",null,!1),$pyjs.trackstack.pop(),$pyjs.track=$pyjs.trackstack.pop(),$pyjs.trackstack.push($pyjs.track),$pyjs.track.lineno=20,$pyjs.track={module:$pyjs.track.module,
lineno:$pyjs.track.lineno},$pyjs.trackstack.push($pyjs.track),a.MouseHandler=$p.___import___("pyjamas.ui.MouseListener.MouseHandler","pyjamas.ui",null,!1),$pyjs.trackstack.pop(),$pyjs.track=$pyjs.trackstack.pop(),$pyjs.trackstack.push($pyjs.track),$pyjs.track.lineno=21,$pyjs.track={module:$pyjs.track.module,lineno:$pyjs.track.lineno},$pyjs.trackstack.push($pyjs.track),a.ClickHandler=$p.___import___("pyjamas.ui.ClickListener.ClickHandler","pyjamas.ui",null,!1),$pyjs.trackstack.pop(),$pyjs.track=$pyjs.trackstack.pop(),
$pyjs.trackstack.push($pyjs.track),$pyjs.track.lineno=23,a.prefetchImages=$p.dict([]),$pyjs.track.lineno=25,a.Image=function(){var f={},d;f.__module__="pyjamas.ui.Image";f.__md5__="4e38dcc0ce4e414475e2615c5a3ae37f";$pyjs.track.lineno=27;f._props=$p.list([$p.tuple(["url","Url","Url",null])]);$pyjs.track.lineno=30;d=$pyjs__bind_method2("__init__",function(c){if(!0===this.__is_instance__){var b=this,e=2<=arguments.length?arguments[arguments.length-1]:arguments[arguments.length];null===e||"object"!=typeof e||
"dict"!=e.__name__||"undefined"==typeof e.$pyjs_is_kwarg?e=arguments[arguments.length+1]:delete e.$pyjs_is_kwarg;$pyjs.options.arg_count&&(0>arguments.length||2<arguments.length)&&$pyjs__exception_func_param(arguments.callee.__name__,1,3,arguments.length+1)}else b=arguments[0],c=arguments[1],e=3<=arguments.length?arguments[arguments.length-1]:arguments[arguments.length],null===e||"object"!=typeof e||"dict"!=e.__name__||"undefined"==typeof e.$pyjs_is_kwarg?e=arguments[arguments.length+1]:delete e.$pyjs_is_kwarg,
$pyjs.options.arg_is_instance&&!0!==b.__is_instance__&&$pyjs__exception_func_instance_expected(arguments.callee.__name__,arguments.callee.__class__.__name__,b),$pyjs.options.arg_count&&(1>arguments.length||3<arguments.length)&&$pyjs__exception_func_param(arguments.callee.__name__,1,3,arguments.length);$pyjs.options.arg_instance_type&&"4e38dcc0ce4e414475e2615c5a3ae37f"!==b.prototype.__md5__&&($p._isinstance(b,arguments.callee.__class__)||$pyjs__exception_func_instance_expected(arguments.callee.__name__,
arguments.callee.__class__.__name__,b));"undefined"==typeof e&&(e=$p.__empty_dict(),"undefined"!=typeof c?null!==c&&"undefined"!=typeof c.$pyjs_is_kwarg&&(e=c,c=arguments[2]):"undefined"!=typeof b&&null!==b&&"undefined"!=typeof b.$pyjs_is_kwarg&&(e=b,b=arguments[2]));"undefined"==typeof c&&(c=arguments.callee.__args__[3][1]);var d;$pyjs.track={module:"pyjamas.ui.Image",lineno:30};$pyjs.trackstack.push($pyjs.track);$pyjs.track.module="pyjamas.ui.Image";$pyjs.track.lineno=30;$pyjs.track.lineno=31;$p.bool(!$p.bool(e.has_key("StyleName")))&&
($pyjs.track.lineno=31,e.__setitem__("StyleName","gwt-Image"));$pyjs.track.lineno=32;$p.bool(c)&&($pyjs.track.lineno=32,e.__setitem__("Url",c));$pyjs.track.lineno=34;b.setElement($p.bool(d=e.pop("Element",null))?d:a.DOM.createImg());$pyjs.track.lineno=35;$pyjs_kwargs_call(a.Widget,"__init__",null,e,[{},b]);$pyjs.track.lineno=36;a.MouseHandler.__init__(b);$pyjs.track.lineno=37;a.ClickHandler.__init__(b);$pyjs.track.lineno=38;b.sinkEvents($p.op_bitor2($p.getattr(a.Event,"ONLOAD"),$p.getattr(a.Event,
"ONERROR")));$pyjs.track.lineno=39;b.__is_instance__&&"function"==typeof b.__setattr__?b.__setattr__("loadListeners",$p.list([])):$p.setattr(b,"loadListeners",$p.list([]));$pyjs.trackstack.pop();$pyjs.track=$pyjs.trackstack.pop();$pyjs.trackstack.push($pyjs.track);return null},1,[null,["kwargs"],["self"],["url",""]]);f.__init__=d;$pyjs.track.lineno=42;d=$pyjs__bind_method2("_getProps",function(){$pyjs.options.arg_is_instance&&!0!==this.__is_instance__&&!1!==this.__is_instance__&&$pyjs__exception_func_class_expected(arguments.callee.__name__,
arguments.callee.__class__.__name__);$pyjs.options.arg_count&&0!=arguments.length&&$pyjs__exception_func_param(arguments.callee.__name__,1,0,arguments.length);var c=this.prototype;$pyjs.track={module:"pyjamas.ui.Image",lineno:42};$pyjs.trackstack.push($pyjs.track);$pyjs.track.module="pyjamas.ui.Image";$pyjs.track.lineno=42;$pyjs.track.lineno=43;$pyjs.track.lineno=43;c=$p.__op_add(a.Widget._getProps(),$p.getattr(c,"_props"));$pyjs.trackstack.pop();$pyjs.track=$pyjs.trackstack.pop();$pyjs.trackstack.push($pyjs.track);
return c},2,[null,null,["self"]]);f._getProps=d;$pyjs.track.lineno=45;d=$pyjs__bind_method2("addLoadListener",function(a){if(!0===this.__is_instance__){var b=this;$pyjs.options.arg_count&&1!=arguments.length&&$pyjs__exception_func_param(arguments.callee.__name__,2,2,arguments.length+1)}else b=arguments[0],a=arguments[1],$pyjs.options.arg_is_instance&&!0!==b.__is_instance__&&$pyjs__exception_func_instance_expected(arguments.callee.__name__,arguments.callee.__class__.__name__,b),$pyjs.options.arg_count&&
2!=arguments.length&&$pyjs__exception_func_param(arguments.callee.__name__,2,2,arguments.length);$pyjs.options.arg_instance_type&&"4e38dcc0ce4e414475e2615c5a3ae37f"!==b.prototype.__md5__&&($p._isinstance(b,arguments.callee.__class__)||$pyjs__exception_func_instance_expected(arguments.callee.__name__,arguments.callee.__class__.__name__,b));$pyjs.track={module:"pyjamas.ui.Image",lineno:45};$pyjs.trackstack.push($pyjs.track);$pyjs.track.module="pyjamas.ui.Image";$pyjs.track.lineno=45;$pyjs.track.lineno=
46;b.loadListeners.append(a);$pyjs.trackstack.pop();$pyjs.track=$pyjs.trackstack.pop();$pyjs.trackstack.push($pyjs.track);return null},1,[null,null,["self"],["listener"]]);f.addLoadListener=d;$pyjs.track.lineno=48;d=$pyjs__bind_method2("removeLoadListener",function(a){if(!0===this.__is_instance__){var b=this;$pyjs.options.arg_count&&1!=arguments.length&&$pyjs__exception_func_param(arguments.callee.__name__,2,2,arguments.length+1)}else b=arguments[0],a=arguments[1],$pyjs.options.arg_is_instance&&!0!==
b.__is_instance__&&$pyjs__exception_func_instance_expected(arguments.callee.__name__,arguments.callee.__class__.__name__,b),$pyjs.options.arg_count&&2!=arguments.length&&$pyjs__exception_func_param(arguments.callee.__name__,2,2,arguments.length);$pyjs.options.arg_instance_type&&"4e38dcc0ce4e414475e2615c5a3ae37f"!==b.prototype.__md5__&&($p._isinstance(b,arguments.callee.__class__)||$pyjs__exception_func_instance_expected(arguments.callee.__name__,arguments.callee.__class__.__name__,b));$pyjs.track=
{module:"pyjamas.ui.Image",lineno:48};$pyjs.trackstack.push($pyjs.track);$pyjs.track.module="pyjamas.ui.Image";$pyjs.track.lineno=48;$pyjs.track.lineno=49;b.loadListeners.remove(a);$pyjs.trackstack.pop();$pyjs.track=$pyjs.trackstack.pop();$pyjs.trackstack.push($pyjs.track);return null},1,[null,null,["self"],["listener"]]);f.removeLoadListener=d;$pyjs.track.lineno=51;d=$pyjs__bind_method2("getUrl",function(){if(!0===this.__is_instance__){var c=this;$pyjs.options.arg_count&&0!=arguments.length&&$pyjs__exception_func_param(arguments.callee.__name__,
1,1,arguments.length+1)}else c=arguments[0],$pyjs.options.arg_is_instance&&!0!==c.__is_instance__&&$pyjs__exception_func_instance_expected(arguments.callee.__name__,arguments.callee.__class__.__name__,c),$pyjs.options.arg_count&&1!=arguments.length&&$pyjs__exception_func_param(arguments.callee.__name__,1,1,arguments.length);$pyjs.options.arg_instance_type&&"4e38dcc0ce4e414475e2615c5a3ae37f"!==c.prototype.__md5__&&($p._isinstance(c,arguments.callee.__class__)||$pyjs__exception_func_instance_expected(arguments.callee.__name__,
arguments.callee.__class__.__name__,c));$pyjs.track={module:"pyjamas.ui.Image",lineno:51};$pyjs.trackstack.push($pyjs.track);$pyjs.track.module="pyjamas.ui.Image";$pyjs.track.lineno=51;$pyjs.track.lineno=52;$pyjs.track.lineno=52;c=a.DOM.getAttribute(c.getElement(),"src");$pyjs.trackstack.pop();$pyjs.track=$pyjs.trackstack.pop();$pyjs.trackstack.push($pyjs.track);return c},1,[null,null,["self"]]);f.getUrl=d;$pyjs.track.lineno=54;d=$pyjs__bind_method2("onBrowserEvent",function(c){if(!0===this.__is_instance__){var b=
this;$pyjs.options.arg_count&&1!=arguments.length&&$pyjs__exception_func_param(arguments.callee.__name__,2,2,arguments.length+1)}else b=arguments[0],c=arguments[1],$pyjs.options.arg_is_instance&&!0!==b.__is_instance__&&$pyjs__exception_func_instance_expected(arguments.callee.__name__,arguments.callee.__class__.__name__,b),$pyjs.options.arg_count&&2!=arguments.length&&$pyjs__exception_func_param(arguments.callee.__name__,2,2,arguments.length);$pyjs.options.arg_instance_type&&"4e38dcc0ce4e414475e2615c5a3ae37f"!==
b.prototype.__md5__&&($p._isinstance(b,arguments.callee.__class__)||$pyjs__exception_func_instance_expected(arguments.callee.__name__,arguments.callee.__class__.__name__,b));var e,d,f;$pyjs.track={module:"pyjamas.ui.Image",lineno:54};$pyjs.trackstack.push($pyjs.track);$pyjs.track.module="pyjamas.ui.Image";$pyjs.track.lineno=54;$pyjs.track.lineno=55;a.Widget.onBrowserEvent(b,c);$pyjs.track.lineno=56;f=a.DOM.eventGetType(c);$pyjs.track.lineno=57;if($p.bool($p.op_eq(f,"load"))){$pyjs.track.lineno=58;
f=$pyjs.trackstack.length;d=$p.getattr(b,"loadListeners");for(e=$p.__iter_prepare(d,!1);"undefined"!=typeof $p.__wrapped_next(e).$nextval;)d=e.$nextval,$pyjs.track.lineno=59,d.onImageLoad(b);$pyjs.trackstack.length>f&&($pyjs.trackstack=$pyjs.trackstack.slice(0,f),$pyjs.track=$pyjs.trackstack.slice(-1)[0]);$pyjs.track.module="pyjamas.ui.Image"}else if($p.bool($p.op_eq(f,"error"))){$pyjs.track.lineno=61;f=$pyjs.trackstack.length;d=$p.getattr(b,"loadListeners");for(e=$p.__iter_prepare(d,!1);"undefined"!=
typeof $p.__wrapped_next(e).$nextval;)d=e.$nextval,$pyjs.track.lineno=62,d.onImageError(b);$pyjs.trackstack.length>f&&($pyjs.trackstack=$pyjs.trackstack.slice(0,f),$pyjs.track=$pyjs.trackstack.slice(-1)[0]);$pyjs.track.module="pyjamas.ui.Image"}$pyjs.trackstack.pop();$pyjs.track=$pyjs.trackstack.pop();$pyjs.trackstack.push($pyjs.track);return null},1,[null,null,["self"],["event"]]);f.onBrowserEvent=d;$pyjs.track.lineno=64;d=$pyjs__bind_method2("prefetch",function(c){if(!0===this.__is_instance__){var b=
this;$pyjs.options.arg_count&&1!=arguments.length&&$pyjs__exception_func_param(arguments.callee.__name__,2,2,arguments.length+1)}else b=arguments[0],c=arguments[1],$pyjs.options.arg_is_instance&&!0!==b.__is_instance__&&$pyjs__exception_func_instance_expected(arguments.callee.__name__,arguments.callee.__class__.__name__,b),$pyjs.options.arg_count&&2!=arguments.length&&$pyjs__exception_func_param(arguments.callee.__name__,2,2,arguments.length);$pyjs.options.arg_instance_type&&"4e38dcc0ce4e414475e2615c5a3ae37f"!==
b.prototype.__md5__&&($p._isinstance(b,arguments.callee.__class__)||$pyjs__exception_func_instance_expected(arguments.callee.__name__,arguments.callee.__class__.__name__,b));$pyjs.track={module:"pyjamas.ui.Image",lineno:64};$pyjs.trackstack.push($pyjs.track);$pyjs.track.module="pyjamas.ui.Image";$pyjs.track.lineno=64;$pyjs.track.lineno=65;b=a.DOM.createImg();$pyjs.track.lineno=66;a.DOM.setElemAttribute(b,"src",c);$pyjs.track.lineno=67;a.prefetchImages.__setitem__(c,b);$pyjs.trackstack.pop();$pyjs.track=
$pyjs.trackstack.pop();$pyjs.trackstack.push($pyjs.track);return null},1,[null,null,["self"],["url"]]);f.prefetch=d;$pyjs.track.lineno=69;d=$pyjs__bind_method2("setUrl",function(c){if(!0===this.__is_instance__){var b=this;$pyjs.options.arg_count&&1!=arguments.length&&$pyjs__exception_func_param(arguments.callee.__name__,2,2,arguments.length+1)}else b=arguments[0],c=arguments[1],$pyjs.options.arg_is_instance&&!0!==b.__is_instance__&&$pyjs__exception_func_instance_expected(arguments.callee.__name__,
arguments.callee.__class__.__name__,b),$pyjs.options.arg_count&&2!=arguments.length&&$pyjs__exception_func_param(arguments.callee.__name__,2,2,arguments.length);$pyjs.options.arg_instance_type&&"4e38dcc0ce4e414475e2615c5a3ae37f"!==b.prototype.__md5__&&($p._isinstance(b,arguments.callee.__class__)||$pyjs__exception_func_instance_expected(arguments.callee.__name__,arguments.callee.__class__.__name__,b));$pyjs.track={module:"pyjamas.ui.Image",lineno:69};$pyjs.trackstack.push($pyjs.track);$pyjs.track.module=
"pyjamas.ui.Image";$pyjs.track.lineno=69;$pyjs.track.lineno=70;a.DOM.setElemAttribute(b.getElement(),"src",c);$pyjs.trackstack.pop();$pyjs.track=$pyjs.trackstack.pop();$pyjs.trackstack.push($pyjs.track);return null},1,[null,null,["self"],["url"]]);f.setUrl=d;$pyjs.track.lineno=25;d=[a.Widget,a.MouseHandler,a.ClickHandler];var g=$p.dict(),h;for(h in f)g.__setitem__(h,f[h]);return $p._create_class("Image",$p.tuple(d),g)}(),$pyjs.track.lineno=72,a.Factory.registerClass("pyjamas.ui.Image","Image",a.Image)}catch(k){throw $p._errorMapping(k);
}return this};
