$pyjs.loaded_modules["pyjamas.ui.Label"]=function(h){if($pyjs.loaded_modules["pyjamas.ui.Label"].__was_initialized__)return $pyjs.loaded_modules["pyjamas.ui.Label"];"undefined"!=typeof $pyjs.loaded_modules["pyjamas.ui"]&&$pyjs.loaded_modules["pyjamas.ui"].__was_initialized__||$p.___import___("pyjamas.ui",null);var a=$pyjs.loaded_modules["pyjamas.ui.Label"];a.__repr__=function(){return"<module: pyjamas.ui.Label>"};a.__was_initialized__=!0;if(null===h||"undefined"==typeof h)h="pyjamas.ui.Label";a.__name__=
h;a.__track_lines__=[];$pyjs.loaded_modules["pyjamas.ui"].Label=$pyjs.loaded_modules["pyjamas.ui.Label"];try{a.__track_lines__[1]="pyjamas.ui.Label.py, line 1:\n    # Copyright 2006 James Tauber and contributors",a.__track_lines__[15]="pyjamas.ui.Label.py, line 15:\n    from pyjamas import DOM",a.__track_lines__[16]="pyjamas.ui.Label.py, line 16:\n    from pyjamas import Factory",a.__track_lines__[17]="pyjamas.ui.Label.py, line 17:\n    from pyjamas.ui.InnerText import InnerText",a.__track_lines__[19]=
"pyjamas.ui.Label.py, line 19:\n    from pyjamas.ui.Widget import Widget",a.__track_lines__[20]="pyjamas.ui.Label.py, line 20:\n    from pyjamas.ui.MouseListener import MouseHandler",a.__track_lines__[21]="pyjamas.ui.Label.py, line 21:\n    from pyjamas.ui.ClickListener import ClickHandler",a.__track_lines__[23]="pyjamas.ui.Label.py, line 23:\n    class Label(Widget, MouseHandler, ClickHandler, InnerText):",a.__track_lines__[25]='pyjamas.ui.Label.py, line 25:\n    _props = [("label", "Label", "Text", None),',
a.__track_lines__[30]="pyjamas.ui.Label.py, line 30:\n    def __init__(self, text=None, wordWrap=True, **kwargs):",a.__track_lines__[31]="pyjamas.ui.Label.py, line 31:\n    kwargs['StyleName'] = kwargs.get('StyleName', \"gwt-Label\")",a.__track_lines__[32]="pyjamas.ui.Label.py, line 32:\n    kwargs['WordWrap'] = kwargs.get('WordWrap', wordWrap)",a.__track_lines__[33]="pyjamas.ui.Label.py, line 33:\n    kwargs['HorizontalAlignment'] = kwargs.get('HorizontalAlignment', \"\")",a.__track_lines__[34]=
"pyjamas.ui.Label.py, line 34:\n    if text:",a.__track_lines__[35]="pyjamas.ui.Label.py, line 35:\n    kwargs['Text'] = text",a.__track_lines__[36]="pyjamas.ui.Label.py, line 36:\n    self.setElement(kwargs.pop('Element', None) or DOM.createDiv())",a.__track_lines__[37]='pyjamas.ui.Label.py, line 37:\n    self.horzAlign = ""',a.__track_lines__[39]="pyjamas.ui.Label.py, line 39:\n    Widget.__init__(self, **kwargs)",a.__track_lines__[40]="pyjamas.ui.Label.py, line 40:\n    MouseHandler.__init__(self)",
a.__track_lines__[41]="pyjamas.ui.Label.py, line 41:\n    ClickHandler.__init__(self)",a.__track_lines__[44]="pyjamas.ui.Label.py, line 43:\n    @classmethod ... def _getProps(self):",a.__track_lines__[45]="pyjamas.ui.Label.py, line 45:\n    return Widget._getProps() + InnerText._getProps() + self._props",a.__track_lines__[47]="pyjamas.ui.Label.py, line 47:\n    def getHorizontalAlignment(self):",a.__track_lines__[48]="pyjamas.ui.Label.py, line 48:\n    return self.horzAlign",a.__track_lines__[50]=
"pyjamas.ui.Label.py, line 50:\n    def getWordWrap(self):",a.__track_lines__[51]='pyjamas.ui.Label.py, line 51:\n    ws = DOM.getStyleAttribute(self.getElement(), "whiteSpace")',a.__track_lines__[52]='pyjamas.ui.Label.py, line 52:\n    return ws != "nowrap"',a.__track_lines__[54]="pyjamas.ui.Label.py, line 54:\n    def setHorizontalAlignment(self, align):",a.__track_lines__[55]="pyjamas.ui.Label.py, line 55:\n    self.horzAlign = align",a.__track_lines__[56]='pyjamas.ui.Label.py, line 56:\n    DOM.setStyleAttribute(self.getElement(), "textAlign", align)',
a.__track_lines__[58]="pyjamas.ui.Label.py, line 58:\n    def setWordWrap(self, wrap):",a.__track_lines__[59]='pyjamas.ui.Label.py, line 59:\n    style = wrap and "normal" or "nowrap"',a.__track_lines__[60]='pyjamas.ui.Label.py, line 60:\n    DOM.setStyleAttribute(self.getElement(), "whiteSpace", style)',a.__track_lines__[62]="pyjamas.ui.Label.py, line 62:\n    Factory.registerClass('pyjamas.ui.Label', 'Label', Label)",$pyjs.track.module="pyjamas.ui.Label",$pyjs.track.lineno=1,$pyjs.track.lineno=
15,$pyjs.track={module:$pyjs.track.module,lineno:$pyjs.track.lineno},$pyjs.trackstack.push($pyjs.track),a.DOM=$p.___import___("pyjamas.DOM","pyjamas.ui",null,!1),$pyjs.trackstack.pop(),$pyjs.track=$pyjs.trackstack.pop(),$pyjs.trackstack.push($pyjs.track),$pyjs.track.lineno=16,$pyjs.track={module:$pyjs.track.module,lineno:$pyjs.track.lineno},$pyjs.trackstack.push($pyjs.track),a.Factory=$p.___import___("pyjamas.Factory","pyjamas.ui",null,!1),$pyjs.trackstack.pop(),$pyjs.track=$pyjs.trackstack.pop(),
$pyjs.trackstack.push($pyjs.track),$pyjs.track.lineno=17,$pyjs.track={module:$pyjs.track.module,lineno:$pyjs.track.lineno},$pyjs.trackstack.push($pyjs.track),a.InnerText=$p.___import___("pyjamas.ui.InnerText.InnerText","pyjamas.ui",null,!1),$pyjs.trackstack.pop(),$pyjs.track=$pyjs.trackstack.pop(),$pyjs.trackstack.push($pyjs.track),$pyjs.track.lineno=19,$pyjs.track={module:$pyjs.track.module,lineno:$pyjs.track.lineno},$pyjs.trackstack.push($pyjs.track),a.Widget=$p.___import___("pyjamas.ui.Widget.Widget",
"pyjamas.ui",null,!1),$pyjs.trackstack.pop(),$pyjs.track=$pyjs.trackstack.pop(),$pyjs.trackstack.push($pyjs.track),$pyjs.track.lineno=20,$pyjs.track={module:$pyjs.track.module,lineno:$pyjs.track.lineno},$pyjs.trackstack.push($pyjs.track),a.MouseHandler=$p.___import___("pyjamas.ui.MouseListener.MouseHandler","pyjamas.ui",null,!1),$pyjs.trackstack.pop(),$pyjs.track=$pyjs.trackstack.pop(),$pyjs.trackstack.push($pyjs.track),$pyjs.track.lineno=21,$pyjs.track={module:$pyjs.track.module,lineno:$pyjs.track.lineno},
$pyjs.trackstack.push($pyjs.track),a.ClickHandler=$p.___import___("pyjamas.ui.ClickListener.ClickHandler","pyjamas.ui",null,!1),$pyjs.trackstack.pop(),$pyjs.track=$pyjs.trackstack.pop(),$pyjs.trackstack.push($pyjs.track),$pyjs.track.lineno=23,a.Label=function(){var g={},f;g.__module__="pyjamas.ui.Label";g.__md5__="e8a3a048ee47bf9a6435560f671efb67";$pyjs.track.lineno=25;g._props=$p.list([$p.tuple(["label","Label","Text",null]),$p.tuple(["wordwrap","Word Wrap","WordWrap",null]),$p.tuple(["horzAlign",
"Horizontal Alignment","HorizontalAlignment",null])]);$pyjs.track.lineno=30;f=$pyjs__bind_method2("__init__",function(b,d){if(!0===this.__is_instance__){var e=this,c=3<=arguments.length?arguments[arguments.length-1]:arguments[arguments.length];null===c||"object"!=typeof c||"dict"!=c.__name__||"undefined"==typeof c.$pyjs_is_kwarg?c=arguments[arguments.length+1]:delete c.$pyjs_is_kwarg;$pyjs.options.arg_count&&(0>arguments.length||3<arguments.length)&&$pyjs__exception_func_param(arguments.callee.__name__,
1,4,arguments.length+1)}else e=arguments[0],b=arguments[1],d=arguments[2],c=4<=arguments.length?arguments[arguments.length-1]:arguments[arguments.length],null===c||"object"!=typeof c||"dict"!=c.__name__||"undefined"==typeof c.$pyjs_is_kwarg?c=arguments[arguments.length+1]:delete c.$pyjs_is_kwarg,$pyjs.options.arg_is_instance&&!0!==e.__is_instance__&&$pyjs__exception_func_instance_expected(arguments.callee.__name__,arguments.callee.__class__.__name__,e),$pyjs.options.arg_count&&(1>arguments.length||
4<arguments.length)&&$pyjs__exception_func_param(arguments.callee.__name__,1,4,arguments.length);$pyjs.options.arg_instance_type&&"e8a3a048ee47bf9a6435560f671efb67"!==e.prototype.__md5__&&($p._isinstance(e,arguments.callee.__class__)||$pyjs__exception_func_instance_expected(arguments.callee.__name__,arguments.callee.__class__.__name__,e));"undefined"==typeof c&&(c=$p.__empty_dict(),"undefined"!=typeof d?null!==d&&"undefined"!=typeof d.$pyjs_is_kwarg&&(c=d,d=arguments[3]):"undefined"!=typeof b?null!==
b&&"undefined"!=typeof b.$pyjs_is_kwarg&&(c=b,b=arguments[3]):"undefined"!=typeof e&&null!==e&&"undefined"!=typeof e.$pyjs_is_kwarg&&(c=e,e=arguments[3]));"undefined"==typeof b&&(b=arguments.callee.__args__[3][1]);"undefined"==typeof d&&(d=arguments.callee.__args__[4][1]);var f;$pyjs.track={module:"pyjamas.ui.Label",lineno:30};$pyjs.trackstack.push($pyjs.track);$pyjs.track.module="pyjamas.ui.Label";$pyjs.track.lineno=30;$pyjs.track.lineno=31;c.__setitem__("StyleName",c.get("StyleName","gwt-Label"));
$pyjs.track.lineno=32;c.__setitem__("WordWrap",c.get("WordWrap",d));$pyjs.track.lineno=33;c.__setitem__("HorizontalAlignment",c.get("HorizontalAlignment",""));$pyjs.track.lineno=34;$p.bool(b)&&($pyjs.track.lineno=35,c.__setitem__("Text",b));$pyjs.track.lineno=36;e.setElement($p.bool(f=c.pop("Element",null))?f:a.DOM.createDiv());$pyjs.track.lineno=37;e.__is_instance__&&"function"==typeof e.__setattr__?e.__setattr__("horzAlign",""):$p.setattr(e,"horzAlign","");$pyjs.track.lineno=39;$pyjs_kwargs_call(a.Widget,
"__init__",null,c,[{},e]);$pyjs.track.lineno=40;a.MouseHandler.__init__(e);$pyjs.track.lineno=41;a.ClickHandler.__init__(e);$pyjs.trackstack.pop();$pyjs.track=$pyjs.trackstack.pop();$pyjs.trackstack.push($pyjs.track);return null},1,[null,["kwargs"],["self"],["text",null],["wordWrap",!0]]);g.__init__=f;$pyjs.track.lineno=44;f=$pyjs__bind_method2("_getProps",function(){$pyjs.options.arg_is_instance&&!0!==this.__is_instance__&&!1!==this.__is_instance__&&$pyjs__exception_func_class_expected(arguments.callee.__name__,
arguments.callee.__class__.__name__);$pyjs.options.arg_count&&0!=arguments.length&&$pyjs__exception_func_param(arguments.callee.__name__,1,0,arguments.length);var b=this.prototype;$pyjs.track={module:"pyjamas.ui.Label",lineno:44};$pyjs.trackstack.push($pyjs.track);$pyjs.track.module="pyjamas.ui.Label";$pyjs.track.lineno=44;$pyjs.track.lineno=45;$pyjs.track.lineno=45;b=$p.__op_add($p.__op_add(a.Widget._getProps(),a.InnerText._getProps()),$p.getattr(b,"_props"));$pyjs.trackstack.pop();$pyjs.track=$pyjs.trackstack.pop();
$pyjs.trackstack.push($pyjs.track);return b},2,[null,null,["self"]]);g._getProps=f;$pyjs.track.lineno=47;f=$pyjs__bind_method2("getHorizontalAlignment",function(){if(!0===this.__is_instance__){var a=this;$pyjs.options.arg_count&&0!=arguments.length&&$pyjs__exception_func_param(arguments.callee.__name__,1,1,arguments.length+1)}else a=arguments[0],$pyjs.options.arg_is_instance&&!0!==a.__is_instance__&&$pyjs__exception_func_instance_expected(arguments.callee.__name__,arguments.callee.__class__.__name__,
a),$pyjs.options.arg_count&&1!=arguments.length&&$pyjs__exception_func_param(arguments.callee.__name__,1,1,arguments.length);$pyjs.options.arg_instance_type&&"e8a3a048ee47bf9a6435560f671efb67"!==a.prototype.__md5__&&($p._isinstance(a,arguments.callee.__class__)||$pyjs__exception_func_instance_expected(arguments.callee.__name__,arguments.callee.__class__.__name__,a));$pyjs.track={module:"pyjamas.ui.Label",lineno:47};$pyjs.trackstack.push($pyjs.track);$pyjs.track.module="pyjamas.ui.Label";$pyjs.track.lineno=
47;$pyjs.track.lineno=48;$pyjs.track.lineno=48;a=$p.getattr(a,"horzAlign");$pyjs.trackstack.pop();$pyjs.track=$pyjs.trackstack.pop();$pyjs.trackstack.push($pyjs.track);return a},1,[null,null,["self"]]);g.getHorizontalAlignment=f;$pyjs.track.lineno=50;f=$pyjs__bind_method2("getWordWrap",function(){if(!0===this.__is_instance__){var b=this;$pyjs.options.arg_count&&0!=arguments.length&&$pyjs__exception_func_param(arguments.callee.__name__,1,1,arguments.length+1)}else b=arguments[0],$pyjs.options.arg_is_instance&&
!0!==b.__is_instance__&&$pyjs__exception_func_instance_expected(arguments.callee.__name__,arguments.callee.__class__.__name__,b),$pyjs.options.arg_count&&1!=arguments.length&&$pyjs__exception_func_param(arguments.callee.__name__,1,1,arguments.length);$pyjs.options.arg_instance_type&&"e8a3a048ee47bf9a6435560f671efb67"!==b.prototype.__md5__&&($p._isinstance(b,arguments.callee.__class__)||$pyjs__exception_func_instance_expected(arguments.callee.__name__,arguments.callee.__class__.__name__,b));$pyjs.track=
{module:"pyjamas.ui.Label",lineno:50};$pyjs.trackstack.push($pyjs.track);$pyjs.track.module="pyjamas.ui.Label";$pyjs.track.lineno=50;$pyjs.track.lineno=51;b=a.DOM.getStyleAttribute(b.getElement(),"whiteSpace");$pyjs.track.lineno=52;$pyjs.track.lineno=52;b=!$p.op_eq(b,"nowrap");$pyjs.trackstack.pop();$pyjs.track=$pyjs.trackstack.pop();$pyjs.trackstack.push($pyjs.track);return b},1,[null,null,["self"]]);g.getWordWrap=f;$pyjs.track.lineno=54;f=$pyjs__bind_method2("setHorizontalAlignment",function(b){if(!0===
this.__is_instance__){var d=this;$pyjs.options.arg_count&&1!=arguments.length&&$pyjs__exception_func_param(arguments.callee.__name__,2,2,arguments.length+1)}else d=arguments[0],b=arguments[1],$pyjs.options.arg_is_instance&&!0!==d.__is_instance__&&$pyjs__exception_func_instance_expected(arguments.callee.__name__,arguments.callee.__class__.__name__,d),$pyjs.options.arg_count&&2!=arguments.length&&$pyjs__exception_func_param(arguments.callee.__name__,2,2,arguments.length);$pyjs.options.arg_instance_type&&
"e8a3a048ee47bf9a6435560f671efb67"!==d.prototype.__md5__&&($p._isinstance(d,arguments.callee.__class__)||$pyjs__exception_func_instance_expected(arguments.callee.__name__,arguments.callee.__class__.__name__,d));$pyjs.track={module:"pyjamas.ui.Label",lineno:54};$pyjs.trackstack.push($pyjs.track);$pyjs.track.module="pyjamas.ui.Label";$pyjs.track.lineno=54;$pyjs.track.lineno=55;d.__is_instance__&&"function"==typeof d.__setattr__?d.__setattr__("horzAlign",b):$p.setattr(d,"horzAlign",b);$pyjs.track.lineno=
56;a.DOM.setStyleAttribute(d.getElement(),"textAlign",b);$pyjs.trackstack.pop();$pyjs.track=$pyjs.trackstack.pop();$pyjs.trackstack.push($pyjs.track);return null},1,[null,null,["self"],["align"]]);g.setHorizontalAlignment=f;$pyjs.track.lineno=58;f=$pyjs__bind_method2("setWordWrap",function(b){if(!0===this.__is_instance__){var d=this;$pyjs.options.arg_count&&1!=arguments.length&&$pyjs__exception_func_param(arguments.callee.__name__,2,2,arguments.length+1)}else d=arguments[0],b=arguments[1],$pyjs.options.arg_is_instance&&
!0!==d.__is_instance__&&$pyjs__exception_func_instance_expected(arguments.callee.__name__,arguments.callee.__class__.__name__,d),$pyjs.options.arg_count&&2!=arguments.length&&$pyjs__exception_func_param(arguments.callee.__name__,2,2,arguments.length);$pyjs.options.arg_instance_type&&"e8a3a048ee47bf9a6435560f671efb67"!==d.prototype.__md5__&&($p._isinstance(d,arguments.callee.__class__)||$pyjs__exception_func_instance_expected(arguments.callee.__name__,arguments.callee.__class__.__name__,d));var e,
c,f;$pyjs.track={module:"pyjamas.ui.Label",lineno:58};$pyjs.trackstack.push($pyjs.track);$pyjs.track.module="pyjamas.ui.Label";$pyjs.track.lineno=58;$pyjs.track.lineno=59;e=$p.bool(c=$p.bool(f=b)?"normal":f)?c:"nowrap";$pyjs.track.lineno=60;a.DOM.setStyleAttribute(d.getElement(),"whiteSpace",e);$pyjs.trackstack.pop();$pyjs.track=$pyjs.trackstack.pop();$pyjs.trackstack.push($pyjs.track);return null},1,[null,null,["self"],["wrap"]]);g.setWordWrap=f;$pyjs.track.lineno=23;f=[a.Widget,a.MouseHandler,a.ClickHandler,
a.InnerText];var h=$p.dict(),k;for(k in g)h.__setitem__(k,g[k]);return $p._create_class("Label",$p.tuple(f),h)}(),$pyjs.track.lineno=62,a.Factory.registerClass("pyjamas.ui.Label","Label",a.Label)}catch(l){throw $p._errorMapping(l);}return this};
