$pyjs.loaded_modules["pyjamas.Canvas.Color"]=function(c){if($pyjs.loaded_modules["pyjamas.Canvas.Color"].__was_initialized__)return $pyjs.loaded_modules["pyjamas.Canvas.Color"];"undefined"!=typeof $pyjs.loaded_modules["pyjamas.Canvas"]&&$pyjs.loaded_modules["pyjamas.Canvas"].__was_initialized__||$p.___import___("pyjamas.Canvas",null);var a=$pyjs.loaded_modules["pyjamas.Canvas.Color"];a.__repr__=function(){return"<module: pyjamas.Canvas.Color>"};a.__was_initialized__=!0;if(null===c||"undefined"==typeof c)c=
"pyjamas.Canvas.Color";a.__name__=c;a.__track_lines__=[];$pyjs.loaded_modules["pyjamas.Canvas"].Color=$pyjs.loaded_modules["pyjamas.Canvas.Color"];try{a.__track_lines__[1]='pyjamas.Canvas.Color.py, line 1:\n    """',a.__track_lines__[18]='pyjamas.Canvas.Color.py, line 18:\n    """*',a.__track_lines__[23]="pyjamas.Canvas.Color.py, line 23:\n    class Color:",a.__track_lines__[29]='pyjamas.Canvas.Color.py, line 29:\n    """*',a.__track_lines__[37]='pyjamas.Canvas.Color.py, line 37:\n    """*',a.__track_lines__[46]=
"pyjamas.Canvas.Color.py, line 46:\n    def __init__(self, r, g=None, b=None, a=None):",a.__track_lines__[47]="pyjamas.Canvas.Color.py, line 47:\n    if g is None and b is None and a is None:",a.__track_lines__[48]="pyjamas.Canvas.Color.py, line 48:\n    self.colorStr = r",a.__track_lines__[50]='pyjamas.Canvas.Color.py, line 50:\n    self.colorStr = "rgb(%d,%d,%d)" % (r, g, b)',a.__track_lines__[52]='pyjamas.Canvas.Color.py, line 52:\n    self.colorStr = "rgba(%d,%d,%d,%f)" % (r, g, b, a)',a.__track_lines__[54]=
"pyjamas.Canvas.Color.py, line 54:\n    def __str__(self):",a.__track_lines__[55]="pyjamas.Canvas.Color.py, line 55:\n    return self.colorStr",a.__track_lines__[59]='pyjamas.Canvas.Color.py, line 59:\n    """',a.__track_lines__[63]='pyjamas.Canvas.Color.py, line 63:\n    ALPHA_GREY = Color("rgba(0,0,0,0.3)")',a.__track_lines__[64]='pyjamas.Canvas.Color.py, line 64:\n    ALPHA_RED = Color("rgba(255,0,0,0.3)")',a.__track_lines__[65]='pyjamas.Canvas.Color.py, line 65:\n    BLACK = Color("#000000")',
a.__track_lines__[66]='pyjamas.Canvas.Color.py, line 66:\n    BLUE = Color("#318ce0")',a.__track_lines__[67]='pyjamas.Canvas.Color.py, line 67:\n    BLUEVIOLET = Color("#8a2be2")',a.__track_lines__[68]='pyjamas.Canvas.Color.py, line 68:\n    CYAN = Color("#5fa2e0")',a.__track_lines__[69]='pyjamas.Canvas.Color.py, line 69:\n    GREEN = Color("#23ef24")',a.__track_lines__[70]='pyjamas.Canvas.Color.py, line 70:\n    GREY = Color("#a9a9a9")',a.__track_lines__[71]='pyjamas.Canvas.Color.py, line 71:\n    LIGHTGREY = Color("#eeeeee")',
a.__track_lines__[72]='pyjamas.Canvas.Color.py, line 72:\n    ORANGE = Color("#f88247")',a.__track_lines__[73]='pyjamas.Canvas.Color.py, line 73:\n    PEACH = Color("#ffd393")',a.__track_lines__[74]='pyjamas.Canvas.Color.py, line 74:\n    PINK = Color("#ff00ff")',a.__track_lines__[75]='pyjamas.Canvas.Color.py, line 75:\n    RED = Color("#ff0000")',a.__track_lines__[76]='pyjamas.Canvas.Color.py, line 76:\n    SKY_BLUE = Color("#c6defa")',a.__track_lines__[77]='pyjamas.Canvas.Color.py, line 77:\n    WHITE = Color("#ffffff")',
a.__track_lines__[78]='pyjamas.Canvas.Color.py, line 78:\n    YELLOW = Color("yellow")',a.__track_lines__[79]='pyjamas.Canvas.Color.py, line 79:\n    DARK_ORANGE = Color("#c44607")',a.__track_lines__[80]='pyjamas.Canvas.Color.py, line 80:\n    BRIGHT_ORANGE = Color("#fb5c0c")',a.__track_lines__[81]='pyjamas.Canvas.Color.py, line 81:\n    DARK_BLUE = Color("#0c6ac1")',$pyjs.track.module="pyjamas.Canvas.Color",$pyjs.track.lineno=1,$pyjs.track.lineno=18,$pyjs.track.lineno=23,a.Color=function(){var a=
{},d;a.__module__="pyjamas.Canvas.Color";a.__md5__="94470218b72a20018606c993f1203541";$pyjs.track.lineno=29;$pyjs.track.lineno=37;$pyjs.track.lineno=46;d=$pyjs__bind_method2("__init__",function(a,e,f,c){if(!0===this.__is_instance__){var b=this;$pyjs.options.arg_count&&(1>arguments.length||4<arguments.length)&&$pyjs__exception_func_param(arguments.callee.__name__,2,5,arguments.length+1)}else b=arguments[0],a=arguments[1],e=arguments[2],f=arguments[3],c=arguments[4],$pyjs.options.arg_is_instance&&!0!==
b.__is_instance__&&$pyjs__exception_func_instance_expected(arguments.callee.__name__,arguments.callee.__class__.__name__,b),$pyjs.options.arg_count&&(2>arguments.length||5<arguments.length)&&$pyjs__exception_func_param(arguments.callee.__name__,2,5,arguments.length);$pyjs.options.arg_instance_type&&"94470218b72a20018606c993f1203541"!==b.prototype.__md5__&&($p._isinstance(b,arguments.callee.__class__)||$pyjs__exception_func_instance_expected(arguments.callee.__name__,arguments.callee.__class__.__name__,
b));"undefined"==typeof e&&(e=arguments.callee.__args__[4][1]);"undefined"==typeof f&&(f=arguments.callee.__args__[5][1]);"undefined"==typeof c&&(c=arguments.callee.__args__[6][1]);var d,g;$pyjs.track={module:"pyjamas.Canvas.Color",lineno:46};$pyjs.trackstack.push($pyjs.track);$pyjs.track.module="pyjamas.Canvas.Color";$pyjs.track.lineno=46;$pyjs.track.lineno=47;$p.bool($p.bool(d=$p.op_is(e,null))?$p.bool(g=$p.op_is(f,null))?$p.op_is(c,null):g:d)?($pyjs.track.lineno=48,b.__is_instance__&&"function"==
typeof b.__setattr__?b.__setattr__("colorStr",a):$p.setattr(b,"colorStr",a)):$p.bool($p.op_is(c,null))?($pyjs.track.lineno=50,b.__is_instance__&&"function"==typeof b.__setattr__?b.__setattr__("colorStr",$p.sprintf("rgb(%d,%d,%d)",$p.tuple([a,e,f]))):$p.setattr(b,"colorStr",$p.sprintf("rgb(%d,%d,%d)",$p.tuple([a,e,f])))):($pyjs.track.lineno=52,b.__is_instance__&&"function"==typeof b.__setattr__?b.__setattr__("colorStr",$p.sprintf("rgba(%d,%d,%d,%f)",$p.tuple([a,e,f,c]))):$p.setattr(b,"colorStr",$p.sprintf("rgba(%d,%d,%d,%f)",
$p.tuple([a,e,f,c]))));$pyjs.trackstack.pop();$pyjs.track=$pyjs.trackstack.pop();$pyjs.trackstack.push($pyjs.track);return null},1,[null,null,["self"],["r"],["g",null],["b",null],["a",null]]);a.__init__=d;$pyjs.track.lineno=54;d=$pyjs__bind_method2("__str__",function(){if(!0===this.__is_instance__){var a=this;$pyjs.options.arg_count&&0!=arguments.length&&$pyjs__exception_func_param(arguments.callee.__name__,1,1,arguments.length+1)}else a=arguments[0],$pyjs.options.arg_is_instance&&!0!==a.__is_instance__&&
$pyjs__exception_func_instance_expected(arguments.callee.__name__,arguments.callee.__class__.__name__,a),$pyjs.options.arg_count&&1!=arguments.length&&$pyjs__exception_func_param(arguments.callee.__name__,1,1,arguments.length);$pyjs.options.arg_instance_type&&"94470218b72a20018606c993f1203541"!==a.prototype.__md5__&&($p._isinstance(a,arguments.callee.__class__)||$pyjs__exception_func_instance_expected(arguments.callee.__name__,arguments.callee.__class__.__name__,a));$pyjs.track={module:"pyjamas.Canvas.Color",
lineno:54};$pyjs.trackstack.push($pyjs.track);$pyjs.track.module="pyjamas.Canvas.Color";$pyjs.track.lineno=54;$pyjs.track.lineno=55;$pyjs.track.lineno=55;a=$p.getattr(a,"colorStr");$pyjs.trackstack.pop();$pyjs.track=$pyjs.trackstack.pop();$pyjs.trackstack.push($pyjs.track);return a},1,[null,null,["self"]]);a.__str__=d;$pyjs.track.lineno=23;d=Array(pyjslib.object);var c=$p.dict(),g;for(g in a)c.__setitem__(g,a[g]);return $p._create_class("Color",$p.tuple(d),c)}(),$pyjs.track.lineno=59,$pyjs.track.lineno=
63,a.ALPHA_GREY=a.Color("rgba(0,0,0,0.3)"),$pyjs.track.lineno=64,a.ALPHA_RED=a.Color("rgba(255,0,0,0.3)"),$pyjs.track.lineno=65,a.BLACK=a.Color("#000000"),$pyjs.track.lineno=66,a.BLUE=a.Color("#318ce0"),$pyjs.track.lineno=67,a.BLUEVIOLET=a.Color("#8a2be2"),$pyjs.track.lineno=68,a.CYAN=a.Color("#5fa2e0"),$pyjs.track.lineno=69,a.GREEN=a.Color("#23ef24"),$pyjs.track.lineno=70,a.GREY=a.Color("#a9a9a9"),$pyjs.track.lineno=71,a.LIGHTGREY=a.Color("#eeeeee"),$pyjs.track.lineno=72,a.ORANGE=a.Color("#f88247"),
$pyjs.track.lineno=73,a.PEACH=a.Color("#ffd393"),$pyjs.track.lineno=74,a.PINK=a.Color("#ff00ff"),$pyjs.track.lineno=75,a.RED=a.Color("#ff0000"),$pyjs.track.lineno=76,a.SKY_BLUE=a.Color("#c6defa"),$pyjs.track.lineno=77,a.WHITE=a.Color("#ffffff"),$pyjs.track.lineno=78,a.YELLOW=a.Color("yellow"),$pyjs.track.lineno=79,a.DARK_ORANGE=a.Color("#c44607"),$pyjs.track.lineno=80,a.BRIGHT_ORANGE=a.Color("#fb5c0c"),$pyjs.track.lineno=81,a.DARK_BLUE=a.Color("#0c6ac1")}catch(h){throw $p._errorMapping(h);}return this};
