$pyjs.loaded_modules["pyjamas.ui.Button"]=function(g){if($pyjs.loaded_modules["pyjamas.ui.Button"].__was_initialized__)return $pyjs.loaded_modules["pyjamas.ui.Button"];"undefined"!=typeof $pyjs.loaded_modules["pyjamas.ui"]&&$pyjs.loaded_modules["pyjamas.ui"].__was_initialized__||$p.___import___("pyjamas.ui",null);var a=$pyjs.loaded_modules["pyjamas.ui.Button"];a.__repr__=function(){return"<module: pyjamas.ui.Button>"};a.__was_initialized__=!0;if(null===g||"undefined"==typeof g)g="pyjamas.ui.Button";
a.__name__=g;a.__track_lines__=[];$pyjs.loaded_modules["pyjamas.ui"].Button=$pyjs.loaded_modules["pyjamas.ui.Button"];try{a.__track_lines__[1]="pyjamas.ui.Button.py, line 1:\n    # Copyright 2006 James Tauber and contributors",a.__track_lines__[16]="pyjamas.ui.Button.py, line 16:\n    from pyjamas import DOM",a.__track_lines__[17]="pyjamas.ui.Button.py, line 17:\n    from pyjamas import Factory",a.__track_lines__[19]="pyjamas.ui.Button.py, line 19:\n    from pyjamas.ui.ButtonBase import ButtonBase",
a.__track_lines__[21]="pyjamas.ui.Button.py, line 21:\n    class Button(ButtonBase):",a.__track_lines__[23]="pyjamas.ui.Button.py, line 23:\n    def __init__(self, html=None, listener=None, **kwargs):",a.__track_lines__[31]="pyjamas.ui.Button.py, line 31:\n    if not kwargs.has_key('StyleName'): kwargs['StyleName']=\"gwt-Button\"",a.__track_lines__[32]="pyjamas.ui.Button.py, line 32:\n    if html: kwargs['HTML'] = html",a.__track_lines__[33]="pyjamas.ui.Button.py, line 33:\n    if kwargs.has_key('Element'):",
a.__track_lines__[34]="pyjamas.ui.Button.py, line 34:\n    element = kwargs.pop('Element')",a.__track_lines__[36]="pyjamas.ui.Button.py, line 36:\n    element = DOM.createButton()",a.__track_lines__[37]="pyjamas.ui.Button.py, line 37:\n    ButtonBase.__init__(self, element, **kwargs)",a.__track_lines__[38]="pyjamas.ui.Button.py, line 38:\n    self.adjustType(self.getElement())",a.__track_lines__[39]="pyjamas.ui.Button.py, line 39:\n    if listener is not None:",a.__track_lines__[40]="pyjamas.ui.Button.py, line 40:\n    self.addClickListener(listener)",
a.__track_lines__[42]="pyjamas.ui.Button.py, line 42:\n    def adjustType(self, button):",a.__track_lines__[43]="pyjamas.ui.Button.py, line 43:\n    if button.type == 'submit':",a.__track_lines__[44]="pyjamas.ui.Button.py, line 44:\n    try:",a.__track_lines__[45]='pyjamas.ui.Button.py, line 45:\n    DOM.setAttribute(button, "type", "button")',a.__track_lines__[47]="pyjamas.ui.Button.py, line 47:\n    pass",a.__track_lines__[49]="pyjamas.ui.Button.py, line 49:\n    def click(self):",a.__track_lines__[53]=
"pyjamas.ui.Button.py, line 53:\n    self.getElement().click()",a.__track_lines__[55]="pyjamas.ui.Button.py, line 55:\n    Factory.registerClass('pyjamas.ui.Button', 'Button', Button)",$pyjs.track.module="pyjamas.ui.Button",$pyjs.track.lineno=1,$pyjs.track.lineno=16,$pyjs.track={module:$pyjs.track.module,lineno:$pyjs.track.lineno},$pyjs.trackstack.push($pyjs.track),a.DOM=$p.___import___("pyjamas.DOM","pyjamas.ui",null,!1),$pyjs.trackstack.pop(),$pyjs.track=$pyjs.trackstack.pop(),$pyjs.trackstack.push($pyjs.track),
$pyjs.track.lineno=17,$pyjs.track={module:$pyjs.track.module,lineno:$pyjs.track.lineno},$pyjs.trackstack.push($pyjs.track),a.Factory=$p.___import___("pyjamas.Factory","pyjamas.ui",null,!1),$pyjs.trackstack.pop(),$pyjs.track=$pyjs.trackstack.pop(),$pyjs.trackstack.push($pyjs.track),$pyjs.track.lineno=19,$pyjs.track={module:$pyjs.track.module,lineno:$pyjs.track.lineno},$pyjs.trackstack.push($pyjs.track),a.ButtonBase=$p.___import___("pyjamas.ui.ButtonBase.ButtonBase","pyjamas.ui",null,!1),$pyjs.trackstack.pop(),
$pyjs.track=$pyjs.trackstack.pop(),$pyjs.trackstack.push($pyjs.track),$pyjs.track.lineno=21,a.Button=function(){var h={},f;h.__module__="pyjamas.ui.Button";h.__md5__="a98f43761b0f790179dec9721e2e6c46";$pyjs.track.lineno=23;f=$pyjs__bind_method2("__init__",function(e,c){if(!0===this.__is_instance__){var d=this,b=3<=arguments.length?arguments[arguments.length-1]:arguments[arguments.length];null===b||"object"!=typeof b||"dict"!=b.__name__||"undefined"==typeof b.$pyjs_is_kwarg?b=arguments[arguments.length+
1]:delete b.$pyjs_is_kwarg;$pyjs.options.arg_count&&(0>arguments.length||3<arguments.length)&&$pyjs__exception_func_param(arguments.callee.__name__,1,4,arguments.length+1)}else d=arguments[0],e=arguments[1],c=arguments[2],b=4<=arguments.length?arguments[arguments.length-1]:arguments[arguments.length],null===b||"object"!=typeof b||"dict"!=b.__name__||"undefined"==typeof b.$pyjs_is_kwarg?b=arguments[arguments.length+1]:delete b.$pyjs_is_kwarg,$pyjs.options.arg_is_instance&&!0!==d.__is_instance__&&$pyjs__exception_func_instance_expected(arguments.callee.__name__,
arguments.callee.__class__.__name__,d),$pyjs.options.arg_count&&(1>arguments.length||4<arguments.length)&&$pyjs__exception_func_param(arguments.callee.__name__,1,4,arguments.length);$pyjs.options.arg_instance_type&&"a98f43761b0f790179dec9721e2e6c46"!==d.prototype.__md5__&&($p._isinstance(d,arguments.callee.__class__)||$pyjs__exception_func_instance_expected(arguments.callee.__name__,arguments.callee.__class__.__name__,d));"undefined"==typeof b&&(b=$p.__empty_dict(),"undefined"!=typeof c?null!==c&&
"undefined"!=typeof c.$pyjs_is_kwarg&&(b=c,c=arguments[3]):"undefined"!=typeof e?null!==e&&"undefined"!=typeof e.$pyjs_is_kwarg&&(b=e,e=arguments[3]):"undefined"!=typeof d&&null!==d&&"undefined"!=typeof d.$pyjs_is_kwarg&&(b=d,d=arguments[3]));"undefined"==typeof e&&(e=arguments.callee.__args__[3][1]);"undefined"==typeof c&&(c=arguments.callee.__args__[4][1]);var f;$pyjs.track={module:"pyjamas.ui.Button",lineno:23};$pyjs.trackstack.push($pyjs.track);$pyjs.track.module="pyjamas.ui.Button";$pyjs.track.lineno=
23;$pyjs.track.lineno=31;$p.bool(!$p.bool(b.has_key("StyleName")))&&($pyjs.track.lineno=31,b.__setitem__("StyleName","gwt-Button"));$pyjs.track.lineno=32;$p.bool(e)&&($pyjs.track.lineno=32,b.__setitem__("HTML",e));$pyjs.track.lineno=33;$p.bool(b.has_key("Element"))?($pyjs.track.lineno=34,f=b.pop("Element")):($pyjs.track.lineno=36,f=a.DOM.createButton());$pyjs.track.lineno=37;$pyjs_kwargs_call(a.ButtonBase,"__init__",null,b,[{},d,f]);$pyjs.track.lineno=38;d.adjustType(d.getElement());$pyjs.track.lineno=
39;$p.bool(!$p.op_is(c,null))&&($pyjs.track.lineno=40,d.addClickListener(c));$pyjs.trackstack.pop();$pyjs.track=$pyjs.trackstack.pop();$pyjs.trackstack.push($pyjs.track);return null},1,[null,["kwargs"],["self"],["html",null],["listener",null]]);h.__init__=f;$pyjs.track.lineno=42;f=$pyjs__bind_method2("adjustType",function(e){if(!0===this.__is_instance__){var c=this;$pyjs.options.arg_count&&1!=arguments.length&&$pyjs__exception_func_param(arguments.callee.__name__,2,2,arguments.length+1)}else c=arguments[0],
e=arguments[1],$pyjs.options.arg_is_instance&&!0!==c.__is_instance__&&$pyjs__exception_func_instance_expected(arguments.callee.__name__,arguments.callee.__class__.__name__,c),$pyjs.options.arg_count&&2!=arguments.length&&$pyjs__exception_func_param(arguments.callee.__name__,2,2,arguments.length);$pyjs.options.arg_instance_type&&"a98f43761b0f790179dec9721e2e6c46"!==c.prototype.__md5__&&($p._isinstance(c,arguments.callee.__class__)||$pyjs__exception_func_instance_expected(arguments.callee.__name__,
arguments.callee.__class__.__name__,c));$pyjs.track={module:"pyjamas.ui.Button",lineno:42};$pyjs.trackstack.push($pyjs.track);$pyjs.track.module="pyjamas.ui.Button";$pyjs.track.lineno=42;$pyjs.track.lineno=43;if($p.bool($p.op_eq($p.getattr(e,"type"),"submit"))){$pyjs.track.lineno=44;c=$pyjs.trackstack.length;try{$pyjs.track.lineno=45,a.DOM.setAttribute(e,"type","button")}catch(d){$pyjs.__last_exception_stack__=sys.save_exception_stack(c-1),$pyjs.__active_exception_stack__=null,d=$p._errorMapping(d),
$pyjs.__last_exception__={error:d,module:a},$pyjs.trackstack.length>c&&($pyjs.trackstack=$pyjs.trackstack.slice(0,c),$pyjs.track=$pyjs.trackstack.slice(-1)[0]),$pyjs.track.module="pyjamas.ui.Button",$pyjs.track.lineno=47}}$pyjs.trackstack.pop();$pyjs.track=$pyjs.trackstack.pop();$pyjs.trackstack.push($pyjs.track);return null},1,[null,null,["self"],["button"]]);h.adjustType=f;$pyjs.track.lineno=49;f=$pyjs__bind_method2("click",function(){if(!0===this.__is_instance__){var a=this;$pyjs.options.arg_count&&
0!=arguments.length&&$pyjs__exception_func_param(arguments.callee.__name__,1,1,arguments.length+1)}else a=arguments[0],$pyjs.options.arg_is_instance&&!0!==a.__is_instance__&&$pyjs__exception_func_instance_expected(arguments.callee.__name__,arguments.callee.__class__.__name__,a),$pyjs.options.arg_count&&1!=arguments.length&&$pyjs__exception_func_param(arguments.callee.__name__,1,1,arguments.length);$pyjs.options.arg_instance_type&&"a98f43761b0f790179dec9721e2e6c46"!==a.prototype.__md5__&&($p._isinstance(a,
arguments.callee.__class__)||$pyjs__exception_func_instance_expected(arguments.callee.__name__,arguments.callee.__class__.__name__,a));$pyjs.track={module:"pyjamas.ui.Button",lineno:49};$pyjs.trackstack.push($pyjs.track);$pyjs.track.module="pyjamas.ui.Button";$pyjs.track.lineno=49;$pyjs.track.lineno=53;a.getElement().click();$pyjs.trackstack.pop();$pyjs.track=$pyjs.trackstack.pop();$pyjs.trackstack.push($pyjs.track);return null},1,[null,null,["self"]]);h.click=f;$pyjs.track.lineno=21;f=Array(a.ButtonBase);
var g=$p.dict(),k;for(k in h)g.__setitem__(k,h[k]);return $p._create_class("Button",$p.tuple(f),g)}(),$pyjs.track.lineno=55,a.Factory.registerClass("pyjamas.ui.Button","Button",a.Button)}catch(l){throw $p._errorMapping(l);}return this};
