$pyjs.loaded_modules["pyjamas.ui.HTML"]=function(h){if($pyjs.loaded_modules["pyjamas.ui.HTML"].__was_initialized__)return $pyjs.loaded_modules["pyjamas.ui.HTML"];"undefined"!=typeof $pyjs.loaded_modules["pyjamas.ui"]&&$pyjs.loaded_modules["pyjamas.ui"].__was_initialized__||$p.___import___("pyjamas.ui",null);var a=$pyjs.loaded_modules["pyjamas.ui.HTML"];a.__repr__=function(){return"<module: pyjamas.ui.HTML>"};a.__was_initialized__=!0;if(null===h||"undefined"==typeof h)h="pyjamas.ui.HTML";a.__name__=
h;a.__track_lines__=[];$pyjs.loaded_modules["pyjamas.ui"].HTML=$pyjs.loaded_modules["pyjamas.ui.HTML"];try{a.__track_lines__[1]="pyjamas.ui.HTML.py, line 1:\n    # Copyright 2006 James Tauber and contributors",a.__track_lines__[15]="pyjamas.ui.HTML.py, line 15:\n    from pyjamas import DOM",a.__track_lines__[16]="pyjamas.ui.HTML.py, line 16:\n    from pyjamas import Factory",a.__track_lines__[18]="pyjamas.ui.HTML.py, line 18:\n    from pyjamas.ui.Label import Label",a.__track_lines__[19]="pyjamas.ui.HTML.py, line 19:\n    from pyjamas.ui import Event",
a.__track_lines__[20]="pyjamas.ui.HTML.py, line 20:\n    from pyjamas.ui.InnerHTML import InnerHTML",a.__track_lines__[21]="pyjamas.ui.HTML.py, line 21:\n    from pyjamas.ui.Widget import Widget",a.__track_lines__[23]="pyjamas.ui.HTML.py, line 23:\n    class HTML(Label, InnerHTML):",a.__track_lines__[25]="pyjamas.ui.HTML.py, line 25:\n    _props = [",a.__track_lines__[30]="pyjamas.ui.HTML.py, line 30:\n    def __init__(self, html=None, wordWrap=True, **kwargs):",a.__track_lines__[31]="pyjamas.ui.HTML.py, line 31:\n    kwargs['StyleName'] = kwargs.get('StyleName', \"gwt-HTML\")",
a.__track_lines__[32]="pyjamas.ui.HTML.py, line 32:\n    if html:",a.__track_lines__[33]="pyjamas.ui.HTML.py, line 33:\n    kwargs['HTML'] = html",a.__track_lines__[34]="pyjamas.ui.HTML.py, line 34:\n    Label.__init__(self, wordWrap=wordWrap, **kwargs)",a.__track_lines__[35]="pyjamas.ui.HTML.py, line 35:\n    self.sinkEvents(Event.ONCLICK | Event.MOUSEEVENTS)",a.__track_lines__[38]="pyjamas.ui.HTML.py, line 37:\n    @classmethod ... def _getProps(self):",a.__track_lines__[39]="pyjamas.ui.HTML.py, line 39:\n    return Widget._getProps() + self._props",
a.__track_lines__[41]="pyjamas.ui.HTML.py, line 41:\n    def _setWeirdProps(self, props, builderstate):",a.__track_lines__[42]='pyjamas.ui.HTML.py, line 42:\n    if props.has_key("label"):',a.__track_lines__[43]="pyjamas.ui.HTML.py, line 43:\n    props['text'] = props['label']",a.__track_lines__[44]="pyjamas.ui.HTML.py, line 44:\n    del props['label']",a.__track_lines__[45]='pyjamas.ui.HTML.py, line 45:\n    if not props.has_key("text"):',a.__track_lines__[46]="pyjamas.ui.HTML.py, line 46:\n    return",
a.__track_lines__[47]='pyjamas.ui.HTML.py, line 47:\n    txt = props["text"]',a.__track_lines__[48]='pyjamas.ui.HTML.py, line 48:\n    if props.get("html", False):',a.__track_lines__[49]="pyjamas.ui.HTML.py, line 49:\n    self.setHTML(txt)",a.__track_lines__[51]="pyjamas.ui.HTML.py, line 51:\n    self.setText(txt)",a.__track_lines__[54]="pyjamas.ui.HTML.py, line 54:\n    Factory.registerClass('pyjamas.ui.HTML', 'HTML', HTML)",$pyjs.track.module="pyjamas.ui.HTML",$pyjs.track.lineno=1,$pyjs.track.lineno=
15,$pyjs.track={module:$pyjs.track.module,lineno:$pyjs.track.lineno},$pyjs.trackstack.push($pyjs.track),a.DOM=$p.___import___("pyjamas.DOM","pyjamas.ui",null,!1),$pyjs.trackstack.pop(),$pyjs.track=$pyjs.trackstack.pop(),$pyjs.trackstack.push($pyjs.track),$pyjs.track.lineno=16,$pyjs.track={module:$pyjs.track.module,lineno:$pyjs.track.lineno},$pyjs.trackstack.push($pyjs.track),a.Factory=$p.___import___("pyjamas.Factory","pyjamas.ui",null,!1),$pyjs.trackstack.pop(),$pyjs.track=$pyjs.trackstack.pop(),
$pyjs.trackstack.push($pyjs.track),$pyjs.track.lineno=18,$pyjs.track={module:$pyjs.track.module,lineno:$pyjs.track.lineno},$pyjs.trackstack.push($pyjs.track),a.Label=$p.___import___("pyjamas.ui.Label.Label","pyjamas.ui",null,!1),$pyjs.trackstack.pop(),$pyjs.track=$pyjs.trackstack.pop(),$pyjs.trackstack.push($pyjs.track),$pyjs.track.lineno=19,$pyjs.track={module:$pyjs.track.module,lineno:$pyjs.track.lineno},$pyjs.trackstack.push($pyjs.track),a.Event=$p.___import___("pyjamas.ui.Event","pyjamas.ui",
null,!1),$pyjs.trackstack.pop(),$pyjs.track=$pyjs.trackstack.pop(),$pyjs.trackstack.push($pyjs.track),$pyjs.track.lineno=20,$pyjs.track={module:$pyjs.track.module,lineno:$pyjs.track.lineno},$pyjs.trackstack.push($pyjs.track),a.InnerHTML=$p.___import___("pyjamas.ui.InnerHTML.InnerHTML","pyjamas.ui",null,!1),$pyjs.trackstack.pop(),$pyjs.track=$pyjs.trackstack.pop(),$pyjs.trackstack.push($pyjs.track),$pyjs.track.lineno=21,$pyjs.track={module:$pyjs.track.module,lineno:$pyjs.track.lineno},$pyjs.trackstack.push($pyjs.track),
a.Widget=$p.___import___("pyjamas.ui.Widget.Widget","pyjamas.ui",null,!1),$pyjs.trackstack.pop(),$pyjs.track=$pyjs.trackstack.pop(),$pyjs.trackstack.push($pyjs.track),$pyjs.track.lineno=23,a.HTML=function(){var f={},g;f.__module__="pyjamas.ui.HTML";f.__md5__="01380b8e0b796daf0f7a870c367aab8c";$pyjs.track.lineno=25;f._props=$p.list([$p.tuple(["wordwrap","Word Wrap","WordWrap",null]),$p.tuple(["horzAlign","Horizontal Alignment","HorizontalAlignment",null])]);$pyjs.track.lineno=30;g=$pyjs__bind_method2("__init__",
function(d,e){if(!0===this.__is_instance__){var c=this,b=3<=arguments.length?arguments[arguments.length-1]:arguments[arguments.length];null===b||"object"!=typeof b||"dict"!=b.__name__||"undefined"==typeof b.$pyjs_is_kwarg?b=arguments[arguments.length+1]:delete b.$pyjs_is_kwarg;$pyjs.options.arg_count&&(0>arguments.length||3<arguments.length)&&$pyjs__exception_func_param(arguments.callee.__name__,1,4,arguments.length+1)}else c=arguments[0],d=arguments[1],e=arguments[2],b=4<=arguments.length?arguments[arguments.length-
1]:arguments[arguments.length],null===b||"object"!=typeof b||"dict"!=b.__name__||"undefined"==typeof b.$pyjs_is_kwarg?b=arguments[arguments.length+1]:delete b.$pyjs_is_kwarg,$pyjs.options.arg_is_instance&&!0!==c.__is_instance__&&$pyjs__exception_func_instance_expected(arguments.callee.__name__,arguments.callee.__class__.__name__,c),$pyjs.options.arg_count&&(1>arguments.length||4<arguments.length)&&$pyjs__exception_func_param(arguments.callee.__name__,1,4,arguments.length);$pyjs.options.arg_instance_type&&
"01380b8e0b796daf0f7a870c367aab8c"!==c.prototype.__md5__&&($p._isinstance(c,arguments.callee.__class__)||$pyjs__exception_func_instance_expected(arguments.callee.__name__,arguments.callee.__class__.__name__,c));"undefined"==typeof b&&(b=$p.__empty_dict(),"undefined"!=typeof e?null!==e&&"undefined"!=typeof e.$pyjs_is_kwarg&&(b=e,e=arguments[3]):"undefined"!=typeof d?null!==d&&"undefined"!=typeof d.$pyjs_is_kwarg&&(b=d,d=arguments[3]):"undefined"!=typeof c&&null!==c&&"undefined"!=typeof c.$pyjs_is_kwarg&&
(b=c,c=arguments[3]));"undefined"==typeof d&&(d=arguments.callee.__args__[3][1]);"undefined"==typeof e&&(e=arguments.callee.__args__[4][1]);$pyjs.track={module:"pyjamas.ui.HTML",lineno:30};$pyjs.trackstack.push($pyjs.track);$pyjs.track.module="pyjamas.ui.HTML";$pyjs.track.lineno=30;$pyjs.track.lineno=31;b.__setitem__("StyleName",b.get("StyleName","gwt-HTML"));$pyjs.track.lineno=32;$p.bool(d)&&($pyjs.track.lineno=33,b.__setitem__("HTML",d));$pyjs.track.lineno=34;$pyjs_kwargs_call(a.Label,"__init__",
null,b,[{wordWrap:e},c]);$pyjs.track.lineno=35;c.sinkEvents($p.op_bitor2($p.getattr(a.Event,"ONCLICK"),$p.getattr(a.Event,"MOUSEEVENTS")));$pyjs.trackstack.pop();$pyjs.track=$pyjs.trackstack.pop();$pyjs.trackstack.push($pyjs.track);return null},1,[null,["kwargs"],["self"],["html",null],["wordWrap",!0]]);f.__init__=g;$pyjs.track.lineno=38;g=$pyjs__bind_method2("_getProps",function(){$pyjs.options.arg_is_instance&&!0!==this.__is_instance__&&!1!==this.__is_instance__&&$pyjs__exception_func_class_expected(arguments.callee.__name__,
arguments.callee.__class__.__name__);$pyjs.options.arg_count&&0!=arguments.length&&$pyjs__exception_func_param(arguments.callee.__name__,1,0,arguments.length);var d=this.prototype;$pyjs.track={module:"pyjamas.ui.HTML",lineno:38};$pyjs.trackstack.push($pyjs.track);$pyjs.track.module="pyjamas.ui.HTML";$pyjs.track.lineno=38;$pyjs.track.lineno=39;$pyjs.track.lineno=39;d=$p.__op_add(a.Widget._getProps(),$p.getattr(d,"_props"));$pyjs.trackstack.pop();$pyjs.track=$pyjs.trackstack.pop();$pyjs.trackstack.push($pyjs.track);
return d},2,[null,null,["self"]]);f._getProps=g;$pyjs.track.lineno=41;g=$pyjs__bind_method2("_setWeirdProps",function(a,e){if(!0===this.__is_instance__){var c=this;$pyjs.options.arg_count&&2!=arguments.length&&$pyjs__exception_func_param(arguments.callee.__name__,3,3,arguments.length+1)}else c=arguments[0],a=arguments[1],e=arguments[2],$pyjs.options.arg_is_instance&&!0!==c.__is_instance__&&$pyjs__exception_func_instance_expected(arguments.callee.__name__,arguments.callee.__class__.__name__,c),$pyjs.options.arg_count&&
3!=arguments.length&&$pyjs__exception_func_param(arguments.callee.__name__,3,3,arguments.length);$pyjs.options.arg_instance_type&&"01380b8e0b796daf0f7a870c367aab8c"!==c.prototype.__md5__&&($p._isinstance(c,arguments.callee.__class__)||$pyjs__exception_func_instance_expected(arguments.callee.__name__,arguments.callee.__class__.__name__,c));var b;$pyjs.track={module:"pyjamas.ui.HTML",lineno:41};$pyjs.trackstack.push($pyjs.track);$pyjs.track.module="pyjamas.ui.HTML";$pyjs.track.lineno=41;$pyjs.track.lineno=
42;$p.bool(a.has_key("label"))&&($pyjs.track.lineno=43,a.__setitem__("text",a.__getitem__("label")),$pyjs.track.lineno=44,a.__delitem__("label"));$pyjs.track.lineno=45;if($p.bool(!$p.bool(a.has_key("text"))))return $pyjs.track.lineno=46,$pyjs.track.lineno=46,$pyjs.trackstack.pop(),$pyjs.track=$pyjs.trackstack.pop(),$pyjs.trackstack.push($pyjs.track),null;$pyjs.track.lineno=47;b=a.__getitem__("text");$pyjs.track.lineno=48;$p.bool(a.get("html",!1))?($pyjs.track.lineno=49,c.setHTML(b)):($pyjs.track.lineno=
51,c.setText(b));$pyjs.trackstack.pop();$pyjs.track=$pyjs.trackstack.pop();$pyjs.trackstack.push($pyjs.track);return null},1,[null,null,["self"],["props"],["builderstate"]]);f._setWeirdProps=g;$pyjs.track.lineno=23;g=[a.Label,a.InnerHTML];var h=$p.dict(),k;for(k in f)h.__setitem__(k,f[k]);return $p._create_class("HTML",$p.tuple(g),h)}(),$pyjs.track.lineno=54,a.Factory.registerClass("pyjamas.ui.HTML","HTML",a.HTML)}catch(l){throw $p._errorMapping(l);}return this};
