$pyjs.loaded_modules["pyjamas.ui.Event"]=function(d){if($pyjs.loaded_modules["pyjamas.ui.Event"].__was_initialized__)return $pyjs.loaded_modules["pyjamas.ui.Event"];"undefined"!=typeof $pyjs.loaded_modules["pyjamas.ui"]&&$pyjs.loaded_modules["pyjamas.ui"].__was_initialized__||$p.___import___("pyjamas.ui",null);var a=$pyjs.loaded_modules["pyjamas.ui.Event"];a.__repr__=function(){return"<module: pyjamas.ui.Event>"};a.__was_initialized__=!0;if(null===d||"undefined"==typeof d)d="pyjamas.ui.Event";a.__name__=
d;a.__track_lines__=[];$pyjs.loaded_modules["pyjamas.ui"].Event=$pyjs.loaded_modules["pyjamas.ui.Event"];try{a.__track_lines__[1]="pyjamas.ui.Event.py, line 1:\n    # Copyright 2006 James Tauber and contributors";a.__track_lines__[2]="pyjamas.ui.Event.py, line 2:\n    # Copyright (C) 2009 Luke Kenneth Casson Leighton <lkcl@lkcl.net>";a.__track_lines__[3]="pyjamas.ui.Event.py, line 3:\n    #";a.__track_lines__[20]="pyjamas.ui.Event.py, line 20:\n    BUTTON_LEFT   = 1";a.__track_lines__[21]="pyjamas.ui.Event.py, line 21:\n    BUTTON_MIDDLE = 4";
a.__track_lines__[22]="pyjamas.ui.Event.py, line 22:\n    BUTTON_RIGHT  = 2";a.__track_lines__[24]="pyjamas.ui.Event.py, line 24:\n    ONBLUR        = 0x01000";a.__track_lines__[25]="pyjamas.ui.Event.py, line 25:\n    ONCHANGE      = 0x00400";a.__track_lines__[26]="pyjamas.ui.Event.py, line 26:\n    ONCLICK       = 0x00001";a.__track_lines__[27]="pyjamas.ui.Event.py, line 27:\n    ONCONTEXTMENU = 0x20000";a.__track_lines__[28]="pyjamas.ui.Event.py, line 28:\n    ONDBLCLICK    = 0x00002";a.__track_lines__[29]=
"pyjamas.ui.Event.py, line 29:\n    ONERROR       = 0x10000";a.__track_lines__[30]="pyjamas.ui.Event.py, line 30:\n    ONFOCUS       = 0x00800";a.__track_lines__[31]="pyjamas.ui.Event.py, line 31:\n    ONKEYDOWN     = 0x00080";a.__track_lines__[32]="pyjamas.ui.Event.py, line 32:\n    ONKEYPRESS    = 0x00100";a.__track_lines__[33]="pyjamas.ui.Event.py, line 33:\n    ONKEYUP       = 0x00200";a.__track_lines__[34]="pyjamas.ui.Event.py, line 34:\n    ONLOAD        = 0x08000";a.__track_lines__[35]="pyjamas.ui.Event.py, line 35:\n    ONLOSECAPTURE = 0x02000";
a.__track_lines__[36]="pyjamas.ui.Event.py, line 36:\n    ONMOUSEDOWN   = 0x00004";a.__track_lines__[37]="pyjamas.ui.Event.py, line 37:\n    ONMOUSEMOVE   = 0x00040";a.__track_lines__[38]="pyjamas.ui.Event.py, line 38:\n    ONMOUSEOUT    = 0x00020";a.__track_lines__[39]="pyjamas.ui.Event.py, line 39:\n    ONMOUSEOVER   = 0x00010";a.__track_lines__[40]="pyjamas.ui.Event.py, line 40:\n    ONMOUSEUP     = 0x00008";a.__track_lines__[41]="pyjamas.ui.Event.py, line 41:\n    ONMOUSEWHEEL  = 0x40000";a.__track_lines__[42]=
"pyjamas.ui.Event.py, line 42:\n    ONSCROLL      = 0x04000";a.__track_lines__[43]="pyjamas.ui.Event.py, line 43:\n    ONINPUT       = 0x80000";a.__track_lines__[44]="pyjamas.ui.Event.py, line 44:\n    DRAGEVENTS    = 0x100000";a.__track_lines__[45]="pyjamas.ui.Event.py, line 45:\n    DROPEVENTS    = 0x200000";a.__track_lines__[47]="pyjamas.ui.Event.py, line 47:\n    FOCUSEVENTS   = 0x01800 # ONFOCUS | ONBLUR";a.__track_lines__[48]="pyjamas.ui.Event.py, line 48:\n    KEYEVENTS     = 0x00380 # ONKEYDOWN | ONKEYPRESS | ONKEYUP";
a.__track_lines__[49]="pyjamas.ui.Event.py, line 49:\n    MOUSEEVENTS   = 0x0007C # ONMOUSEDOWN | ONMOUSEUP | ONMOUSEMOVE | ONMOUSEOVER | ONMOUSEOUT";a.__track_lines__[51]="pyjamas.ui.Event.py, line 51:\n    eventbits = {";a.__track_lines__[79]="pyjamas.ui.Event.py, line 79:\n    eventmap = {";a.__track_lines__[87]="pyjamas.ui.Event.py, line 87:\n    def _create_eventmap():";a.__track_lines__[88]="pyjamas.ui.Event.py, line 88:\n    for bit, bitmap in eventbits.iteritems():";a.__track_lines__[89]=
"pyjamas.ui.Event.py, line 89:\n    eventmap[bitmap[0]] = bit";a.__track_lines__[91]="pyjamas.ui.Event.py, line 2:\n    # Copyright (C) 2009 Luke Kenneth Casson Leighton <lkcl@lkcl.net> ... def init():";a.__track_lines__[94]="pyjamas.ui.Event.py, line 94:\n    init()";var k=new $p["int"](4096),f=new $p["int"](1),g=new $p["int"](2),h=new $p["int"](4),l=new $p["int"](8192),m=new $p["int"](8),n=new $p["int"](128),p=new $p["int"](256),q=new $p["int"](16),r=new $p["int"](512),C=new $p["int"](0),b=new $p["int"](524288),
s=new $p["int"](32),t=new $p["int"](131072),D=new $p["int"](896),c=new $p["int"](262144),u=new $p["int"](1024),v=new $p["int"](16384),w=new $p["int"](1048576),x=new $p["int"](32768),y=new $p["int"](64),z=new $p["int"](2048),A=new $p["int"](2097152),B=new $p["int"](65536),E=new $p["int"](6144),F=new $p["int"](124);$pyjs.track.module="pyjamas.ui.Event";$pyjs.track.lineno=1;$pyjs.track.lineno=20;a.BUTTON_LEFT=f;$pyjs.track.lineno=21;a.BUTTON_MIDDLE=h;$pyjs.track.lineno=22;a.BUTTON_RIGHT=g;$pyjs.track.lineno=
24;a.ONBLUR=k;$pyjs.track.lineno=25;a.ONCHANGE=u;$pyjs.track.lineno=26;a.ONCLICK=f;$pyjs.track.lineno=27;a.ONCONTEXTMENU=t;$pyjs.track.lineno=28;a.ONDBLCLICK=g;$pyjs.track.lineno=29;a.ONERROR=B;$pyjs.track.lineno=30;a.ONFOCUS=z;$pyjs.track.lineno=31;a.ONKEYDOWN=n;$pyjs.track.lineno=32;a.ONKEYPRESS=p;$pyjs.track.lineno=33;a.ONKEYUP=r;$pyjs.track.lineno=34;a.ONLOAD=x;$pyjs.track.lineno=35;a.ONLOSECAPTURE=l;$pyjs.track.lineno=36;a.ONMOUSEDOWN=h;$pyjs.track.lineno=37;a.ONMOUSEMOVE=y;$pyjs.track.lineno=
38;a.ONMOUSEOUT=s;$pyjs.track.lineno=39;a.ONMOUSEOVER=q;$pyjs.track.lineno=40;a.ONMOUSEUP=m;$pyjs.track.lineno=41;a.ONMOUSEWHEEL=c;$pyjs.track.lineno=42;a.ONSCROLL=v;$pyjs.track.lineno=43;a.ONINPUT=b;$pyjs.track.lineno=44;a.DRAGEVENTS=w;$pyjs.track.lineno=45;a.DROPEVENTS=A;$pyjs.track.lineno=47;a.FOCUSEVENTS=E;$pyjs.track.lineno=48;a.KEYEVENTS=D;$pyjs.track.lineno=49;a.MOUSEEVENTS=F;$pyjs.track.lineno=51;a.eventbits=$p.dict([[f,$p.tuple(["click",$p.list(["click"])])],[g,$p.tuple(["dblclick",$p.list(["dblclick"])])],
[h,$p.tuple(["mousedown",$p.list(["mousedown"])])],[m,$p.tuple(["mouseup",$p.list(["mouseup"])])],[q,$p.tuple(["mouseover",$p.list(["mouseover"])])],[s,$p.tuple(["mouseout",$p.list(["mouseout"])])],[y,$p.tuple(["mousemove",$p.list(["mousemove"])])],[n,$p.tuple(["keydown",$p.list(["keydown"])])],[p,$p.tuple(["keypress",$p.list(["keypress"])])],[r,$p.tuple(["keyup",$p.list(["keyup"])])],[u,$p.tuple(["change",$p.list(["change"])])],[z,$p.tuple(["focus",$p.list(["focus"])])],[k,$p.tuple(["blur",$p.list(["blur"])])],
[l,$p.tuple(["losecapture",$p.list(["losecapture"])])],[v,$p.tuple(["scroll",$p.list(["scroll"])])],[x,$p.tuple(["load",$p.list(["load"])])],[B,$p.tuple(["error",$p.list(["error"])])],[t,$p.tuple(["contextmenu",$p.list(["contextmenu"])])],[c,$p.tuple(["mousewheel",$p.list(["mousewheel"])])],[b,$p.tuple(["input",$p.list(["input"])])],[w,$p.tuple(["dragevents",$p.list(["drag","dragstart","dragend"])])],[A,$p.tuple(["dropevents",$p.list(["drop","dragenter","dragover","dragleave"])])]]);$pyjs.track.lineno=
79;a.eventmap=$p.dict([["mousewheel",c],["mousescroll",c],["DOMMouseScroll",c],["input",b],["propertychange",b]]);$pyjs.track.lineno=87;a._create_eventmap=function(){$pyjs.options.arg_count&&0!=arguments.length&&$pyjs__exception_func_param(arguments.callee.__name__,0,0,arguments.length);var b,c,d,e;$pyjs.track={module:"pyjamas.ui.Event",lineno:87};$pyjs.trackstack.push($pyjs.track);$pyjs.track.module="pyjamas.ui.Event";$pyjs.track.lineno=87;$pyjs.track.lineno=88;c=$pyjs.trackstack.length;b=a.eventbits.iteritems();
for(b=$p.__iter_prepare(b,!1);"undefined"!=typeof $p.__wrapped_next(b).$nextval;)e=$p.__ass_unpack(b.$nextval,2,null),d=e[0],e=e[1],$pyjs.track.lineno=89,a.eventmap.__setitem__(e.__getitem__(C),d);$pyjs.trackstack.length>c&&($pyjs.trackstack=$pyjs.trackstack.slice(0,c),$pyjs.track=$pyjs.trackstack.slice(-1)[0]);$pyjs.track.module="pyjamas.ui.Event";$pyjs.trackstack.pop();$pyjs.track=$pyjs.trackstack.pop();$pyjs.trackstack.push($pyjs.track);return null};a._create_eventmap.__name__="_create_eventmap";
a._create_eventmap.__bind_type__=0;a._create_eventmap.__args__=[null,null];$pyjs.track.lineno=91;a.init=function(){$pyjs.options.arg_count&&0!=arguments.length&&$pyjs__exception_func_param(arguments.callee.__name__,0,0,arguments.length);$pyjs.track={module:"pyjamas.ui.Event",lineno:91};$pyjs.trackstack.push($pyjs.track);$pyjs.track.module="pyjamas.ui.Event";$pyjs.track.lineno=91;$pyjs.track.lineno=2;a.eventbits.__setitem__(b,$p.tuple(["propertychange",$p.list(["propertychange"])]));$pyjs.track.lineno=
3;a._create_eventmap();$pyjs.trackstack.pop();$pyjs.track=$pyjs.trackstack.pop();$pyjs.trackstack.push($pyjs.track);return null};a.init.__name__="init";a.init.__bind_type__=0;a.init.__args__=[null,null];$pyjs.track.lineno=94;a.init()}catch(G){throw $p._errorMapping(G);}return this};
