$pyjs.loaded_modules.SimpleCanvasDemo=function(d){if($pyjs.loaded_modules.SimpleCanvasDemo.__was_initialized__)return $pyjs.loaded_modules.SimpleCanvasDemo;var a=$pyjs.loaded_modules.SimpleCanvasDemo;a.__repr__=function(){return"<module: SimpleCanvasDemo>"};a.__was_initialized__=!0;if(null===d||"undefined"==typeof d)d="SimpleCanvasDemo";a.__name__=d;a.__track_lines__=[];try{a.__track_lines__[32]="SimpleCanvasDemo.py, line 32:\n    self.height = 400";a.__track_lines__[1]='SimpleCanvasDemo.py, line 1:\n    """';
a.__track_lines__[34]="SimpleCanvasDemo.py, line 34:\n    self.canvas = theCanvas";a.__track_lines__[35]="SimpleCanvasDemo.py, line 35:\n    self.controls = None";a.__track_lines__[37]="SimpleCanvasDemo.py, line 37:\n    def getControls(self):";a.__track_lines__[38]="SimpleCanvasDemo.py, line 38:\n    if self.controls is None:";a.__track_lines__[33]="SimpleCanvasDemo.py, line 33:\n    self.width = 400";a.__track_lines__[41]="SimpleCanvasDemo.py, line 41:\n    return self.controls";a.__track_lines__[39]=
"SimpleCanvasDemo.py, line 39:\n    self.createControls()";a.__track_lines__[44]="SimpleCanvasDemo.py, line 44:\n    def getName(self):";a.__track_lines__[45]="SimpleCanvasDemo.py, line 45:\n    return self.demoName";a.__track_lines__[19]="SimpleCanvasDemo.py, line 19:\n    from pyjamas.ui.Composite import Composite";a.__track_lines__[22]='SimpleCanvasDemo.py, line 22:\n    """*';a.__track_lines__[29]="SimpleCanvasDemo.py, line 29:\n    class SimpleCanvasDemo:";a.__track_lines__[31]="SimpleCanvasDemo.py, line 31:\n    def __init__(self, theCanvas):";
var e=new $p["int"](400);$pyjs.track.module="SimpleCanvasDemo";$pyjs.track.lineno=1;$pyjs.track.lineno=19;$pyjs.track={module:$pyjs.track.module,lineno:$pyjs.track.lineno};$pyjs.trackstack.push($pyjs.track);a.Composite=$p.___import___("pyjamas.ui.Composite.Composite",null,null,!1);$pyjs.trackstack.pop();$pyjs.track=$pyjs.trackstack.pop();$pyjs.trackstack.push($pyjs.track);$pyjs.track.lineno=22;$pyjs.track.lineno=29;a.SimpleCanvasDemo=function(){var a={},c;a.__module__="SimpleCanvasDemo";a.__md5__=
"6fb62d1188ba4c1a74ecd150afda29be";$pyjs.track.lineno=31;c=$pyjs__bind_method2("__init__",function(a){if(!0===this.__is_instance__){var b=this;$pyjs.options.arg_count&&1!=arguments.length&&$pyjs__exception_func_param(arguments.callee.__name__,2,2,arguments.length+1)}else b=arguments[0],a=arguments[1],$pyjs.options.arg_is_instance&&!0!==b.__is_instance__&&$pyjs__exception_func_instance_expected(arguments.callee.__name__,arguments.callee.__class__.__name__,b),$pyjs.options.arg_count&&2!=arguments.length&&
$pyjs__exception_func_param(arguments.callee.__name__,2,2,arguments.length);$pyjs.options.arg_instance_type&&"6fb62d1188ba4c1a74ecd150afda29be"!==b.prototype.__md5__&&($p._isinstance(b,arguments.callee.__class__)||$pyjs__exception_func_instance_expected(arguments.callee.__name__,arguments.callee.__class__.__name__,b));$pyjs.track={module:"SimpleCanvasDemo",lineno:31};$pyjs.trackstack.push($pyjs.track);$pyjs.track.module="SimpleCanvasDemo";$pyjs.track.lineno=31;$pyjs.track.lineno=32;b.__is_instance__&&
"function"==typeof b.__setattr__?b.__setattr__("height",e):$p.setattr(b,"height",e);$pyjs.track.lineno=33;b.__is_instance__&&"function"==typeof b.__setattr__?b.__setattr__("width",e):$p.setattr(b,"width",e);$pyjs.track.lineno=34;b.__is_instance__&&"function"==typeof b.__setattr__?b.__setattr__("canvas",a):$p.setattr(b,"canvas",a);$pyjs.track.lineno=35;b.__is_instance__&&"function"==typeof b.__setattr__?b.__setattr__("controls",null):$p.setattr(b,"controls",null);$pyjs.trackstack.pop();$pyjs.track=
$pyjs.trackstack.pop();$pyjs.trackstack.push($pyjs.track);return null},1,[null,null,["self"],["theCanvas"]]);a.__init__=c;$pyjs.track.lineno=37;c=$pyjs__bind_method2("getControls",function(){if(!0===this.__is_instance__){var a=this;$pyjs.options.arg_count&&0!=arguments.length&&$pyjs__exception_func_param(arguments.callee.__name__,1,1,arguments.length+1)}else a=arguments[0],$pyjs.options.arg_is_instance&&!0!==a.__is_instance__&&$pyjs__exception_func_instance_expected(arguments.callee.__name__,arguments.callee.__class__.__name__,
a),$pyjs.options.arg_count&&1!=arguments.length&&$pyjs__exception_func_param(arguments.callee.__name__,1,1,arguments.length);$pyjs.options.arg_instance_type&&"6fb62d1188ba4c1a74ecd150afda29be"!==a.prototype.__md5__&&($p._isinstance(a,arguments.callee.__class__)||$pyjs__exception_func_instance_expected(arguments.callee.__name__,arguments.callee.__class__.__name__,a));$pyjs.track={module:"SimpleCanvasDemo",lineno:37};$pyjs.trackstack.push($pyjs.track);$pyjs.track.module="SimpleCanvasDemo";$pyjs.track.lineno=
37;$pyjs.track.lineno=38;$p.bool($p.op_is($p.getattr(a,"controls"),null))&&($pyjs.track.lineno=39,a.createControls());$pyjs.track.lineno=41;$pyjs.track.lineno=41;a=$p.getattr(a,"controls");$pyjs.trackstack.pop();$pyjs.track=$pyjs.trackstack.pop();$pyjs.trackstack.push($pyjs.track);return a},1,[null,null,["self"]]);a.getControls=c;$pyjs.track.lineno=44;c=$pyjs__bind_method2("getName",function(){if(!0===this.__is_instance__){var a=this;$pyjs.options.arg_count&&0!=arguments.length&&$pyjs__exception_func_param(arguments.callee.__name__,
1,1,arguments.length+1)}else a=arguments[0],$pyjs.options.arg_is_instance&&!0!==a.__is_instance__&&$pyjs__exception_func_instance_expected(arguments.callee.__name__,arguments.callee.__class__.__name__,a),$pyjs.options.arg_count&&1!=arguments.length&&$pyjs__exception_func_param(arguments.callee.__name__,1,1,arguments.length);$pyjs.options.arg_instance_type&&"6fb62d1188ba4c1a74ecd150afda29be"!==a.prototype.__md5__&&($p._isinstance(a,arguments.callee.__class__)||$pyjs__exception_func_instance_expected(arguments.callee.__name__,
arguments.callee.__class__.__name__,a));$pyjs.track={module:"SimpleCanvasDemo",lineno:44};$pyjs.trackstack.push($pyjs.track);$pyjs.track.module="SimpleCanvasDemo";$pyjs.track.lineno=44;$pyjs.track.lineno=45;$pyjs.track.lineno=45;a=$p.getattr(a,"demoName");$pyjs.trackstack.pop();$pyjs.track=$pyjs.trackstack.pop();$pyjs.trackstack.push($pyjs.track);return a},1,[null,null,["self"]]);a.getName=c;$pyjs.track.lineno=29;c=Array(pyjslib.object);var d=$p.dict(),f;for(f in a)d.__setitem__(f,a[f]);return $p._create_class("SimpleCanvasDemo",
$p.tuple(c),d)}()}catch(g){throw $p._errorMapping(g);}return this};
