$pyjs.loaded_modules["pyjsdl.surface"]=function(x){if($pyjs.loaded_modules["pyjsdl.surface"].__was_initialized__)return $pyjs.loaded_modules["pyjsdl.surface"];"undefined"!=typeof $pyjs.loaded_modules.pyjsdl&&$pyjs.loaded_modules.pyjsdl.__was_initialized__||$p.___import___("pyjsdl",null);var n=$pyjs.loaded_modules["pyjsdl.surface"];n.__repr__=function(){return"<module: pyjsdl.surface>"};n.__was_initialized__=!0;if(null===x||"undefined"==typeof x)x="pyjsdl.surface";n.__name__=x;$pyjs.loaded_modules.pyjsdl.surface=
$pyjs.loaded_modules["pyjsdl.surface"];n.Rect=$p.___import___("rect.Rect","pyjsdl",null,!1);n.rectPool=$p.___import___("rect.rectPool","pyjsdl",null,!1);n.Color=$p.___import___("color.Color","pyjsdl",null,!1);n.HTML5Canvas=$p.___import___("pyjsobj.HTML5Canvas","pyjsdl",null,!1);n.__docformat__="restructuredtext";n.Surface=function(){var g={},b;g.__module__="pyjsdl.surface";b=$pyjs__bind_method2("__init__",function(a){if(!0===this.__is_instance__)var f=this,c=$p.tuple($pyjs_array_slice.call(arguments,
1,arguments.length-1)),d=2<=arguments.length?arguments[arguments.length-1]:arguments[arguments.length];else f=arguments[0],a=arguments[1],c=$p.tuple($pyjs_array_slice.call(arguments,2,arguments.length-1)),d=3<=arguments.length?arguments[arguments.length-1]:arguments[arguments.length];null===d||"object"!=typeof d||"dict"!=d.__name__||"undefined"==typeof d.$pyjs_is_kwarg?("undefined"!=typeof d&&c.__array.push(d),d=arguments[arguments.length+1]):delete d.$pyjs_is_kwarg;"undefined"==typeof d&&($p.__empty_dict(),
"undefined"!=typeof a?null!==a&&"undefined"!=typeof a.$pyjs_is_kwarg&&(a=arguments[2]):"undefined"!=typeof f&&null!==f&&"undefined"!=typeof f.$pyjs_is_kwarg&&(f=arguments[2]));var e,m;f.width=$p.float_int("undefined"!=typeof(m=a).__array?"undefined"!=typeof m.__array[0]?m.__array[0]:m.__getitem__(0):m.__getitem__(0));f.height=$p.float_int("undefined"!=typeof(e=a).__array?"undefined"!=typeof e.__array[1]?e.__array[1]:e.__getitem__(1):e.__getitem__(1));n.HTML5Canvas.__init__(f,f.width,f.height);f._display=
null;f._super_surface=null;f._offset=$p.tuple([0,0]);f._colorkey=null;f._nonimplemented_methods();return null},1,["args",["kwargs"],["self"],["size"]]);g.__init__=b;b=$pyjs__bind_method2("__repr__",function(a){a=!0===this.__is_instance__?this:a;return $p.sprintf("%s(%d,%d)",$p.tuple([a.__class__,a.width,a.height]))},1,[null,null,["self"]]);g.__repr__=b;b=$pyjs__bind_method2("get_size",function(a){a=!0===this.__is_instance__?this:a;return $p.tuple([a.width,a.height])},1,[null,null,["self"]]);g.get_size=
b;b=$pyjs__bind_method2("get_width",function(a){return(!0===this.__is_instance__?this:a).width},1,[null,null,["self"]]);g.get_width=b;b=$pyjs__bind_method2("get_height",function(a){return(!0===this.__is_instance__?this:a).height},1,[null,null,["self"]]);g.get_height=b;b=$pyjs__bind_method2("resize",function(a,f,c){if(!0===this.__is_instance__)var d=this;else d=a,a=f,f=c;d.width=$p.float_int(a);d.height=$p.float_int(f);n.HTML5Canvas.resize(d,d.width,d.height);return null},1,[null,null,["self"],["width"],
["height"]]);g.resize=b;b=$pyjs__bind_method2("get_rect",function(){if(!0===this.__is_instance__)var a=this,f=1<=arguments.length?arguments[arguments.length-1]:arguments[arguments.length];else a=arguments[0],f=2<=arguments.length?arguments[arguments.length-1]:arguments[arguments.length];null===f||"object"!=typeof f||"dict"!=f.__name__||"undefined"==typeof f.$pyjs_is_kwarg?f=arguments[arguments.length+1]:delete f.$pyjs_is_kwarg;"undefined"==typeof f&&(f=$p.__empty_dict(),"undefined"!=typeof a&&null!==
a&&"undefined"!=typeof a.$pyjs_is_kwarg&&(f=a,a=arguments[1]));var c,d,e,m,A,h,b;h=n.Rect(0,0,a.width,a.height);e=f;"undefined"!=typeof(a=e.__array)?b=0:(e=e.__iter__(),b="undefined"!=typeof(a=e.__array)?0:"function"==typeof e.$genfunc?1:-1);for(d=0;"undefined"!=typeof(c=b?0<b?e.next(!0,!1):$p.wrapped_next(e):a[d++]);)h.__setattr__(c,"undefined"!=typeof(A=f).__array?"undefined"!=typeof A.__array[m=c]?A.__array[m]:A.__getitem__(m):A.__getitem__(c));return h},1,[null,["attr"],["self"]]);g.get_rect=
b;b=$pyjs__bind_method2("copy",function(a){a=!0===this.__is_instance__?this:a;var f;f=n.Surface($p.tuple([a.width,a.height]));f.drawImage(a.canvas,0,0);return f},1,[null,null,["self"]]);g.copy=b;b=$pyjs__bind_method2("subsurface",function(a,f){if(!0===this.__is_instance__)var c=this;else c=a,a=f;var d,e,m,b,h,q,l,g,r,k,p,t;if(null===(h=$p.tuple(["t","f"]).__contains__(a))||!1===h||0===h||""===h?0:"object"==typeof h?"function"==typeof h.__nonzero__?h.__nonzero__():"function"==typeof h.__len__?0<h.__len__():
1:1){if(null===(b=!(null===(m=c._super_surface)||!1===m||0===m||""===m?0:"object"==typeof m?"function"==typeof m.__nonzero__?m.__nonzero__():"function"==typeof m.__len__?0<m.__len__():1:1))||!1===b||0===b||""===b?0:"object"==typeof b?"function"==typeof b.__nonzero__?b.__nonzero__():"function"==typeof b.__len__?0<b.__len__():1:1)return null;(null===(g="t"===(e=a)&&null===e?!0:null===e?!1:"object"!=typeof e&&"function"!=typeof e||"function"!=typeof e.__cmp__?"t"==e:0===e.__cmp__("t"))||!1===g||0===
g||""===g?0:"object"==typeof g?"function"==typeof g.__nonzero__?g.__nonzero__():"function"==typeof g.__len__?0<g.__len__():1:1)?c.drawImage(c._super_surface.canvas,"undefined"!=typeof(l=c._offset).__array?"undefined"!=typeof l.__array[0]?l.__array[0]:l.__getitem__(0):l.__getitem__(0),"undefined"!=typeof(q=c._offset).__array?"undefined"!=typeof q.__array[1]?q.__array[1]:q.__getitem__(1):q.__getitem__(1),c.width,c.height,0,0,c.width,c.height):c._super_surface.drawImage(c.canvas,"undefined"!=typeof(r=
c._offset).__array?"undefined"!=typeof r.__array[0]?r.__array[0]:r.__getitem__(0):r.__getitem__(0),"undefined"!=typeof(k=c._offset).__array?"undefined"!=typeof k.__array[1]?k.__array[1]:k.__getitem__(1):k.__getitem__(1));return null}e=(null===(p=$p.hasattr(a,"width"))||!1===p||0===p||""===p?0:"object"==typeof p?"function"==typeof p.__nonzero__?p.__nonzero__():"function"==typeof p.__len__?0<p.__len__():1:1)?a:n.Rect(a);if(null===(t=!(null===(d=c.get_rect().contains(e))||!1===d||0===d||""===d?0:"object"==
typeof d?"function"==typeof d.__nonzero__?d.__nonzero__():"function"==typeof d.__len__?0<d.__len__():1:1))||!1===t||0===t||""===t?0:"object"==typeof t?"function"==typeof t.__nonzero__?t.__nonzero__():"function"==typeof t.__len__?0<t.__len__():1:1)throw $p.ValueError("subsurface outside surface area");d=c.getSubimage(e.x,e.y,e.width,e.height);d._super_surface=c;d._offset=$p.tuple([e.x,e.y]);d._colorkey=c._colorkey;return d},1,[null,null,["self"],["rect"]]);g.subsurface=b;b=$pyjs__bind_method2("getSubimage",
function(a,f,c,d,e){if(!0===this.__is_instance__)var m=this;else m=a,a=f,f=c,c=d,d=e;e=n.Surface($p.tuple([c,d]));e.drawImage(m.canvas,a,f,c,d,0,0,c,d);return e},1,[null,null,["self"],["x"],["y"],["width"],["height"]]);g.getSubimage=b;b=$pyjs__bind_method2("blit",function(a,f,c){if(!0===this.__is_instance__)var d=this;else d=arguments[0],a=arguments[1],f=arguments[2],c=arguments[3];"undefined"==typeof c&&(c=arguments.callee.__args__[5][1]);var e,m,b,h,q,l,g,r,k,p,t,u,s,v,w;(null===(p=!(null===(k=
c)||!1===k||0===k||""===k?0:"object"==typeof k?"function"==typeof k.__nonzero__?k.__nonzero__():"function"==typeof k.__len__?0<k.__len__():1:1))||!1===p||0===p||""===p?0:"object"==typeof p?"function"==typeof p.__nonzero__?p.__nonzero__():"function"==typeof p.__len__?0<p.__len__():1:1)?(k=n.rectPool.get("undefined"!=typeof(t=f).__array?"undefined"!=typeof t.__array[0]?t.__array[0]:t.__getitem__(0):t.__getitem__(0),"undefined"!=typeof(u=f).__array?"undefined"!=typeof u.__array[1]?u.__array[1]:u.__getitem__(1):
u.__getitem__(1),a.width,a.height),d.impl.canvasContext.drawImage(a.canvas,k.x,k.y)):(k=n.rectPool.get("undefined"!=typeof(b=f).__array?"undefined"!=typeof b.__array[0]?b.__array[0]:b.__getitem__(0):b.__getitem__(0),"undefined"!=typeof(h=f).__array?"undefined"!=typeof h.__array[1]?h.__array[1]:h.__getitem__(1):h.__getitem__(1),"undefined"!=typeof(w=c).__array?"undefined"!=typeof w.__array[2]?w.__array[2]:w.__getitem__(2):w.__getitem__(2),"undefined"!=typeof(q=c).__array?"undefined"!=typeof q.__array[3]?
q.__array[3]:q.__getitem__(3):q.__getitem__(3)),d.impl.canvasContext.drawImage(a.canvas,"undefined"!=typeof(l=c).__array?"undefined"!=typeof l.__array[0]?l.__array[0]:l.__getitem__(0):l.__getitem__(0),"undefined"!=typeof(g=c).__array?"undefined"!=typeof g.__array[1]?g.__array[1]:g.__getitem__(1):g.__getitem__(1),"undefined"!=typeof(s=c).__array?"undefined"!=typeof s.__array[2]?s.__array[2]:s.__getitem__(2):s.__getitem__(2),"undefined"!=typeof(r=c).__array?"undefined"!=typeof r.__array[3]?r.__array[3]:
r.__getitem__(3):r.__getitem__(3),k.x,k.y,"undefined"!=typeof(e=c).__array?"undefined"!=typeof e.__array[2]?e.__array[2]:e.__getitem__(2):e.__getitem__(2),"undefined"!=typeof(v=c).__array?"undefined"!=typeof v.__array[3]?v.__array[3]:v.__getitem__(3):v.__getitem__(3)));d=((null===(m=d._display)||!1===m||0===m||""===m?0:"object"==typeof m?"function"==typeof m.__nonzero__?m.__nonzero__():"function"==typeof m.__len__?0<m.__len__():1:1)?d._display._surface_rect:d.get_rect()).clip(k);n.rectPool.append(k);
return d},1,[null,null,["self"],["surface"],["position"],["area",null]]);g.blit=b;b=$pyjs__bind_method2("_blits",function(a,f){if(!0===this.__is_instance__)var c=this;else c=a,a=f;var d,e,m,b,h;e=c.impl.canvasContext;c=a;"undefined"!=typeof(h=c.__array)?b=0:(c=c.__iter__(),b="undefined"!=typeof(h=c.__array)?0:"function"==typeof c.$genfunc?1:-1);for(m=0;"undefined"!=typeof(d=b?0<b?c.next(!0,!1):$p.wrapped_next(c):h[m++]);)e.drawImage(d.image.canvas,d.rect.x,d.rect.y);return null},1,[null,null,["self"],
["surfaces"]]);g._blits=b;b=$pyjs__bind_method2("_blit_clear",function(a,f,c){if(!0===this.__is_instance__)var d=this;else d=a,a=f,f=c;var e,m,b,h,g,l,n,r;c=d.impl.canvasContext;d=(null===(e=d._display)||!1===e||0===e||""===e?0:"object"==typeof e?"function"==typeof e.__nonzero__?e.__nonzero__():"function"==typeof e.__len__?0<e.__len__():1:1)?d._display._surface_rect:d.get_rect();g=f;"undefined"!=typeof(f=g.__array)?r=0:(g=g.__iter__(),r="undefined"!=typeof(f=g.__array)?0:"function"==typeof g.$genfunc?
1:-1);for(e=0;"undefined"!=typeof(h=r?0<r?g.next(!0,!1):$p.wrapped_next(g):f[e++]);)(null===(m=d.contains(h))||!1===m||0===m||""===m?0:"object"==typeof m?"function"==typeof m.__nonzero__?m.__nonzero__():"function"==typeof m.__len__?0<m.__len__():1:1)?c.drawImage(a.canvas,h.x,h.y,h.width,h.height,h.x,h.y,h.width,h.height):(h=d.clip(h),(null===(b=(null===(l=n=h.width)||!1===l||0===l||""===l?0:"object"==typeof l?"function"==typeof l.__nonzero__?l.__nonzero__():"function"==typeof l.__len__?0<l.__len__():
1:1)?h.height:n)||!1===b||0===b||""===b?0:"object"==typeof b?"function"==typeof b.__nonzero__?b.__nonzero__():"function"==typeof b.__len__?0<b.__len__():1:1)&&c.drawImage(a.canvas,h.x,h.y,h.width,h.height,h.x,h.y,h.width,h.height));return null},1,[null,null,["self"],["surface"],["rect_list"]]);g._blit_clear=b;b=$pyjs__bind_method2("set_colorkey",function(a,f){if(!0===this.__is_instance__)var c=this;else c=arguments[0],a=arguments[1],f=arguments[2];"undefined"==typeof f&&(f=arguments.callee.__args__[4][1]);
var d,e;if(null===(d=c._colorkey)||!1===d||0===d||""===d?0:"object"==typeof d?"function"==typeof d.__nonzero__?d.__nonzero__():"function"==typeof d.__len__?0<d.__len__():1:1)c._colorkey=null;if(null===(e=a)||!1===e||0===e||""===e?0:"object"==typeof e?"function"==typeof e.__nonzero__?e.__nonzero__():"function"==typeof e.__len__?0<e.__len__():1:1)try{a=n.Color(a),c._colorkey=a,c.replace_color($p.tuple([a.r,a.g,a.b]))}catch(b){$pyjs.__last_exception__={error:b,module:n}}return null},1,[null,null,["self"],
["color"],["flags",null]]);g.set_colorkey=b;b=$pyjs__bind_method2("get_colorkey",function(a){a=!0===this.__is_instance__?this:a;try{return $p.tuple([a._colorkey.r,a._colorkey.g,a._colorkey.b,255])}catch(f){a="undefined"==typeof f.__name__?f.name:f.__name__;$pyjs.__last_exception__={error:f,module:n};if(a==$p.TypeError.__name__||$p._isinstance(f,$p.TypeError)||a==$p.AttributeError.__name__||$p._isinstance(f,$p.AttributeError))return null;$pyjs.__active_exception_stack__=$pyjs.__last_exception_stack__;
$pyjs.__last_exception_stack__=null;throw f;}},1,[null,null,["self"]]);g.get_colorkey=b;b=$pyjs__bind_method2("_getPixel",function(a,f,c){!0!==this.__is_instance__&&(a=f,f=c);return a.data[f]},1,[null,null,["self"],["imagedata"],["index"]]);g._getPixel=b;b=$pyjs__bind_method2("_setPixel",function(a,f,c,d){!0!==this.__is_instance__&&(a=f,f=c,c=d);c=$p.str(c);a.data[f]=c;return null},1,[null,null,["self"],["imagedata"],["index"],["dat"]]);g._setPixel=b;b=$pyjs__bind_method2("replace_color",function(a,
f){if(!0===this.__is_instance__)var c=this;else c=arguments[0],a=arguments[1],f=arguments[2];"undefined"==typeof f&&(f=arguments.callee.__args__[4][1]);var d,e,b,g,h,q,l,s,r,k,p,t,u,y,v,w,z,x;w=c.impl.getImageData(0,0,c.width,c.height);u=(null===(h=$p.hasattr(a,"a"))||!1===h||0===h||""===h?0:"object"==typeof h?"function"==typeof h.__nonzero__?h.__nonzero__():"function"==typeof h.__len__?0<h.__len__():1:1)?a:n.Color(a);h=(null===(d=f)||!1===d||0===d||""===d?0:"object"==typeof d?"function"==typeof d.__nonzero__?
d.__nonzero__():"function"==typeof d.__len__?0<d.__len__():1:1)?(null===(e=$p.hasattr(f,"a"))||!1===e||0===e||""===e?0:"object"==typeof e?"function"==typeof e.__nonzero__?e.__nonzero__():"function"==typeof e.__len__?0<e.__len__():1:1)?f:n.Color(f):n.Color(u.r,u.g,u.b,0);d=$p.tuple([u.r,u.g,u.b,u.a]);u=$p.tuple([h.r,h.g,h.b,h.a]);e=$p.xrange(0,null===(l=w.data)?0:"undefined"!=typeof l.__array?l.__array.length:"function"==typeof l.__len__?l.__len__():"undefined"!=typeof l.length?l.length:$p.len(l),
4);"undefined"!=typeof(x=e.__array)?l=0:(e=e.__iter__(),l="undefined"!=typeof(x=e.__array)?0:"function"==typeof e.$genfunc?1:-1);for(h=0;"undefined"!=typeof(b=l?0<l?e.next(!0,!1):$p.wrapped_next(e):x[h++]);)if(z=b,null===(k=(p=$p.tuple([c._getPixel(w,z),c._getPixel(w,z+1),c._getPixel(w,z+2),c._getPixel(w,z+3)]))===(v=d)&&null===p?!0:null===p?!1:null===v?!1:"object"!=typeof p&&"function"!=typeof p||"function"!=typeof p.__cmp__?"object"!=typeof v&&"function"!=typeof v||"function"!=typeof v.__cmp__?
p==v:0===v.__cmp__(p):0===p.__cmp__(v))||!1===k||0===k||""===k?0:"object"==typeof k?"function"==typeof k.__nonzero__?k.__nonzero__():"function"==typeof k.__len__?0<k.__len__():1:1)for(q=$p.range(4),"undefined"!=typeof(b=q.__array)?r=0:(q=q.__iter__(),r="undefined"!=typeof(b=q.__array)?0:"function"==typeof q.$genfunc?1:-1),y=0;"undefined"!=typeof(g=r?0<r?q.next(!0,!1):$p.wrapped_next(q):b[y++]);)c._setPixel(w,z+g,"undefined"!=typeof(s=u).__array?"undefined"!=typeof s.__array[t=g]?s.__array[t]:s.__getitem__(t):
s.__getitem__(g));c.impl.putImageData(w,0,0,0,0,c.width,c.height);return null},1,[null,null,["self"],["color"],["new_color",null]]);g.replace_color=b;b=$pyjs__bind_method2("get_at",function(a,f){if(!0===this.__is_instance__)var c=this;else c=a,a=f;var d,e,b;b=c.impl.getImageData("undefined"!=typeof(e=a).__array?"undefined"!=typeof e.__array[0]?e.__array[0]:e.__getitem__(0):e.__getitem__(0),"undefined"!=typeof(d=a).__array?"undefined"!=typeof d.__array[1]?d.__array[1]:d.__getitem__(1):d.__getitem__(1),
1,1);return $p.tuple([c._getPixel(b,0),c._getPixel(b,1),c._getPixel(b,2),c._getPixel(b,3)])},1,[null,null,["self"],["pos"]]);g.get_at=b;b=$pyjs__bind_method2("set_at",function(a,f,c){if(!0===this.__is_instance__)var d=this;else d=a,a=f,f=c;var e,b,g,h,q,l,s,r,k;c=d.impl.getImageData("undefined"!=typeof(q=a).__array?"undefined"!=typeof q.__array[0]?q.__array[0]:q.__getitem__(0):q.__getitem__(0),"undefined"!=typeof(g=a).__array?"undefined"!=typeof g.__array[1]?g.__array[1]:g.__getitem__(1):g.__getitem__(1),
1,1);f=(null===(e=$p.hasattr(f,"a"))||!1===e||0===e||""===e?0:"object"==typeof e?"function"==typeof e.__nonzero__?e.__nonzero__():"function"==typeof e.__len__?0<e.__len__():1:1)?f:n.Color(f);e=$p.range(4);"undefined"!=typeof(l=e.__array)?g=0:(e=e.__iter__(),g="undefined"!=typeof(l=e.__array)?0:"function"==typeof e.$genfunc?1:-1);for(q=0;"undefined"!=typeof(b=g?0<g?e.next(!0,!1):$p.wrapped_next(e):l[q++]);)d._setPixel(c,b,"undefined"!=typeof(h=f).__array?"undefined"!=typeof h.__array[s=b]?h.__array[s]:
h.__getitem__(s):h.__getitem__(b));d.impl.putImageData(c,"undefined"!=typeof(r=a).__array?"undefined"!=typeof r.__array[0]?r.__array[0]:r.__getitem__(0):r.__getitem__(0),"undefined"!=typeof(k=a).__array?"undefined"!=typeof k.__array[1]?k.__array[1]:k.__getitem__(1):k.__getitem__(1),0,0,1,1);return null},1,[null,null,["self"],["pos"],["color"]]);g.set_at=b;b=$pyjs__bind_method2("fill",function(a,f){if(!0===this.__is_instance__)var c=this;else c=arguments[0],a=arguments[1],f=arguments[2];"undefined"==
typeof a&&(a=arguments.callee.__args__[3][1]);"undefined"==typeof f&&(f=arguments.callee.__args__[4][1]);var d,e,b,g,h,q,l,s,r,k,p,t;if(null===(q=null===a)||!1===q||0===q||""===q?0:"object"==typeof q?"function"==typeof q.__nonzero__?q.__nonzero__():"function"==typeof q.__len__?0<q.__len__():1:1)return n.HTML5Canvas.fill(c),null;c.beginPath();if(null===(h=a)||!1===h||0===h||""===h?0:"object"==typeof h?"function"==typeof h.__nonzero__?h.__nonzero__():"function"==typeof h.__len__?0<h.__len__():1:1){(null===
(d=$p.hasattr(a,"a"))||!1===d||0===d||""===d?0:"object"==typeof d?"function"==typeof d.__nonzero__?d.__nonzero__():"function"==typeof d.__len__?0<d.__len__():1:1)?c.setFillStyle(a):c.setFillStyle(n.Color(a));if(null===(g=!(null===(e=f)||!1===e||0===e||""===e?0:"object"==typeof e?"function"==typeof e.__nonzero__?e.__nonzero__():"function"==typeof e.__len__?0<e.__len__():1:1))||!1===g||0===g||""===g?0:"object"==typeof g?"function"==typeof g.__nonzero__?g.__nonzero__():"function"==typeof g.__len__?0<
g.__len__():1:1)b=n.Rect(0,0,c.width,c.height);else if(d=(null===(b=c._display)||!1===b||0===b||""===b?0:"object"==typeof b?"function"==typeof b.__nonzero__?b.__nonzero__():"function"==typeof b.__len__?0<b.__len__():1:1)?c._display._surface_rect:c.get_rect(),b=(null===(l=$p.hasattr(f,"width"))||!1===l||0===l||""===l?0:"object"==typeof l?"function"==typeof l.__nonzero__?l.__nonzero__():"function"==typeof l.__len__?0<l.__len__():1:1)?d.clip(f):d.clip(n.Rect(f)),null===(k=(null===(p=s=!(null===(r=b.width)||
!1===r||0===r||""===r?0:"object"==typeof r?"function"==typeof r.__nonzero__?r.__nonzero__():"function"==typeof r.__len__?0<r.__len__():1:1))||!1===p||0===p||""===p?0:"object"==typeof p?"function"==typeof p.__nonzero__?p.__nonzero__():"function"==typeof p.__len__?0<p.__len__():1:1)?s:!(null===(t=b.height)||!1===t||0===t||""===t?0:"object"==typeof t?"function"==typeof t.__nonzero__?t.__nonzero__():"function"==typeof t.__len__?0<t.__len__():1:1))||!1===k||0===k||""===k?0:"object"==typeof k?"function"==
typeof k.__nonzero__?k.__nonzero__():"function"==typeof k.__len__?0<k.__len__():1:1)return b;c.fillRect(b.x,b.y,b.width,b.height)}else b=n.Rect(0,0,c.width,c.height),c.clear();return b},1,[null,null,["self"],["color",null],["rect",null]]);g.fill=b;b=$pyjs__bind_method2("get_parent",function(a){return(!0===this.__is_instance__?this:a)._super_surface},1,[null,null,["self"]]);g.get_parent=b;b=$pyjs__bind_method2("get_offset",function(a){return(!0===this.__is_instance__?this:a)._offset},1,[null,null,
["self"]]);g.get_offset=b;b=$pyjs__bind_method2("_nonimplemented_methods",function(a){var b=!0===this.__is_instance__?this:a;a=function(){$p.tuple($pyjs_array_slice.call(arguments,0,arguments.length));return b};a.__name__="$lambda1";a.__bind_type__=0;a.__args__=["arg",null];b.convert=a;a=function(){$p.tuple($pyjs_array_slice.call(arguments,0,arguments.length));return b};a.__name__="$lambda2";a.__bind_type__=0;a.__args__=["arg",null];b.convert_alpha=a;a=function(){$p.tuple($pyjs_array_slice.call(arguments,
0,arguments.length));return null};a.__name__="$lambda3";a.__bind_type__=0;a.__args__=["arg",null];b.set_alpha=a;a=function(){$p.tuple($pyjs_array_slice.call(arguments,0,arguments.length));return null};a.__name__="$lambda4";a.__bind_type__=0;a.__args__=["arg",null];b.get_alpha=a;a=function(){$p.tuple($pyjs_array_slice.call(arguments,0,arguments.length));return null};a.__name__="$lambda5";a.__bind_type__=0;a.__args__=["arg",null];b.lock=a;a=function(){$p.tuple($pyjs_array_slice.call(arguments,0,arguments.length));
return null};a.__name__="$lambda6";a.__bind_type__=0;a.__args__=["arg",null];b.unlock=a;a=function(){$p.tuple($pyjs_array_slice.call(arguments,0,arguments.length));return!1};a.__name__="$lambda7";a.__bind_type__=0;a.__args__=["arg",null];b.mustlock=a;a=function(){$p.tuple($pyjs_array_slice.call(arguments,0,arguments.length));return!1};a.__name__="$lambda8";a.__bind_type__=0;a.__args__=["arg",null];b.get_locked=a;a=function(){$p.tuple($pyjs_array_slice.call(arguments,0,arguments.length));return $p.tuple([])};
a.__name__="$lambda9";a.__bind_type__=0;a.__args__=["arg",null];b.get_locks=a;return null},1,[null,null,["self"]]);g._nonimplemented_methods=b;b=Array(n.HTML5Canvas);var y=$p.dict(),s;for(s in g)y.__setitem__(s,g[s]);return $p._create_class("Surface",$p.tuple(b),y)}();n.Surf=function(){var g={},b;g.__module__="pyjsdl.surface";b=$pyjs__bind_method2("__init__",function(a,b){if(!0===this.__is_instance__)var c=this;else c=a,a=b;var d;c.canvas=a;d=a.getElement();d=$p.__ass_unpack($p.tuple([d.width,d.height]),
2,null);c.width=d[0];c.height=d[1];c.get_size=n.Surface.get_size;c.get_width=n.Surface.get_width;c.get_height=n.Surface.get_height;c.get_rect=n.Surface.get_rect;c._nonimplemented_methods=n.Surface._nonimplemented_methods;c._nonimplemented_methods();return null},1,[null,null,["self"],["image"]]);g.__init__=b;b=Array(pyjslib.object);var y=$p.dict(),s;for(s in g)y.__setitem__(s,g[s]);return $p._create_class("Surf",$p.tuple(b),y)}();n.IndexSizeError=function(){var g={__module__:"pyjsdl.surface"},b=Array($p.Exception),
n=$p.dict(),s;for(s in g)n.__setitem__(s,g[s]);return $p._create_class("IndexSizeError",$p.tuple(b),n)}();return this};
