$pyjs.loaded_modules["pyjsdl.mouse"]=function(m){if($pyjs.loaded_modules["pyjsdl.mouse"].__was_initialized__)return $pyjs.loaded_modules["pyjsdl.mouse"];"undefined"!=typeof $pyjs.loaded_modules.pyjsdl&&$pyjs.loaded_modules.pyjsdl.__was_initialized__||$p.___import___("pyjsdl",null);var h=$pyjs.loaded_modules["pyjsdl.mouse"];h.__repr__=function(){return"<module: pyjsdl.mouse>"};h.__was_initialized__=!0;if(null===m||"undefined"==typeof m)m="pyjsdl.mouse";h.__name__=m;$pyjs.loaded_modules.pyjsdl.mouse=
$pyjs.loaded_modules["pyjsdl.mouse"];h.env=$p.___import___("env","pyjsdl");h.pyjsdl=$p.___import___("pyjsdl.event","pyjsdl");h.DOM=$p.___import___("pyjsobj.DOM","pyjsdl",null,!1);h.__docformat__="restructuredtext";h.Mouse=function(){var k={},c;k.__module__="pyjsdl.mouse";c=$pyjs__bind_method2("__init__",function(a){a=!0===this.__is_instance__?this:a;a.mousePress=h.pyjsdl.event.mousePress;a.mouseMove=h.pyjsdl.event.mouseMove;a.mouseMoveRel=h.pyjsdl.event.mouseMoveRel;a.mouseCursor=h.pyjsdl.event.mouseCursor;
a._nonimplemented_methods();return null},1,[null,null,["self"]]);k.__init__=c;c=$pyjs__bind_method2("get_pressed",function(a){a=!0===this.__is_instance__?this:a;var b,d,l;return $p.tuple(["undefined"!=typeof(l=a.mousePress).__array?"undefined"!=typeof l.__array[0]?l.__array[0]:l.__getitem__(0):l.__getitem__(0),"undefined"!=typeof(d=a.mousePress).__array?"undefined"!=typeof d.__array[1]?d.__array[1]:d.__getitem__(1):d.__getitem__(1),"undefined"!=typeof(b=a.mousePress).__array?"undefined"!=typeof b.__array[2]?
b.__array[2]:b.__getitem__(2):b.__getitem__(2)])},1,[null,null,["self"]]);k.get_pressed=c;c=$pyjs__bind_method2("get_pos",function(a){a=!0===this.__is_instance__?this:a;var b,d,l,e,f,g,c;return(null===(d=!(-1===(b="undefined"!=typeof(e=a.mouseMove).__array?"undefined"!=typeof e.__array.x?e.__array.x:e.__getitem__("x"):e.__getitem__("x"))&&null===b||(null===b?0:"object"!=typeof b&&"function"!=typeof b||"function"!=typeof b.__cmp__?-1==b:0===b.__cmp__(-1))))||!1===d||0===d||""===d?0:"object"==typeof d?
"function"==typeof d.__nonzero__?d.__nonzero__():"function"==typeof d.__len__?0<d.__len__():1:1)?$p.tuple([("undefined"!=typeof(l=a.mouseMove).__array?"undefined"!=typeof l.__array.x?l.__array.x:l.__getitem__("x"):l.__getitem__("x"))+h.env.frame.scrollLeft,("undefined"!=typeof(g=a.mouseMove).__array?"undefined"!=typeof g.__array.y?g.__array.y:g.__getitem__("y"):g.__getitem__("y"))+h.env.frame.scrollTop]):$p.tuple(["undefined"!=typeof(c=a.mouseMove).__array?"undefined"!=typeof c.__array.x?c.__array.x:
c.__getitem__("x"):c.__getitem__("x"),"undefined"!=typeof(f=a.mouseMove).__array?"undefined"!=typeof f.__array.y?f.__array.y:f.__getitem__("y"):f.__getitem__("y")])},1,[null,null,["self"]]);k.get_pos=c;c=$pyjs__bind_method2("get_rel",function(a){a=!0===this.__is_instance__?this:a;var b,d,l,e,f,g,c,k,m,q,r,s;try{g=$p.tuple([("undefined"!=typeof(m=a.mouseMove).__array?"undefined"!=typeof m.__array.x?m.__array.x:m.__getitem__("x"):m.__getitem__("x"))-("undefined"!=typeof(q=a.mouseMoveRel).__array?"undefined"!=
typeof q.__array.x?q.__array.x:q.__getitem__("x"):q.__getitem__("x")),("undefined"!=typeof(l=a.mouseMove).__array?"undefined"!=typeof l.__array.y?l.__array.y:l.__getitem__("y"):l.__getitem__("y"))-("undefined"!=typeof(s=a.mouseMoveRel).__array?"undefined"!=typeof s.__array.y?s.__array.y:s.__getitem__("y"):s.__getitem__("y"))]);var p=$p.__ass_unpack($p.tuple(["undefined"!=typeof(e=a.mouseMove).__array?"undefined"!=typeof e.__array.x?e.__array.x:e.__getitem__("x"):e.__getitem__("x"),"undefined"!=typeof(f=
a.mouseMove).__array?"undefined"!=typeof f.__array.y?f.__array.y:f.__getitem__("y"):f.__getitem__("y")]),2,null);a.mouseMoveRel.__setitem__("x",p[0]);a.mouseMoveRel.__setitem__("y",p[1])}catch(n){if(g="undefined"==typeof n.__name__?n.name:n.__name__,$pyjs.__last_exception__={error:n,module:h},g==$p.TypeError.__name__||$p._isinstance(n,$p.TypeError)){if(g=$p.tuple([0,0]),null===(k=!(-1===(c="undefined"!=typeof(d=a.mouseMove).__array?"undefined"!=typeof d.__array.x?d.__array.x:d.__getitem__("x"):d.__getitem__("x"))&&
null===c||(null===c?0:"object"!=typeof c&&"function"!=typeof c||"function"!=typeof c.__cmp__?-1==c:0===c.__cmp__(-1))))||!1===k||0===k||""===k?0:"object"==typeof k?"function"==typeof k.__nonzero__?k.__nonzero__():"function"==typeof k.__len__?0<k.__len__():1:1)d=$p.__ass_unpack($p.tuple(["undefined"!=typeof(r=a.mouseMove).__array?"undefined"!=typeof r.__array.x?r.__array.x:r.__getitem__("x"):r.__getitem__("x"),"undefined"!=typeof(b=a.mouseMove).__array?"undefined"!=typeof b.__array.y?b.__array.y:b.__getitem__("y"):
b.__getitem__("y")]),2,null),a.mouseMoveRel.__setitem__("x",d[0]),a.mouseMoveRel.__setitem__("y",d[1])}else throw $pyjs.__active_exception_stack__=$pyjs.__last_exception_stack__,$pyjs.__last_exception_stack__=null,n;}return g},1,[null,null,["self"]]);k.get_rel=c;c=$pyjs__bind_method2("set_visible",function(a,b){if(!0===this.__is_instance__)var d=this;else d=a,a=b;var c,e,f,g;if(null===(c=a)||!1===c||0===c||""===c?0:"object"==typeof c?"function"==typeof c.__nonzero__?c.__nonzero__():"function"==typeof c.__len__?
0<c.__len__():1:1){if(null===(g=!(null===(f=d.mouseCursor)||!1===f||0===f||""===f?0:"object"==typeof f?"function"==typeof f.__nonzero__?f.__nonzero__():"function"==typeof f.__len__?0<f.__len__():1:1))||!1===g||0===g||""===g?0:"object"==typeof g?"function"==typeof g.__nonzero__?g.__nonzero__():"function"==typeof g.__len__?0<g.__len__():1:1)h.DOM.setStyleAttribute(h.env.canvas.getElement(),"cursor","default"),d.mouseCursor=!0}else if(null===(e=d.mouseCursor)||!1===e||0===e||""===e?0:"object"==typeof e?
"function"==typeof e.__nonzero__?e.__nonzero__():"function"==typeof e.__len__?0<e.__len__():1:1)h.DOM.setStyleAttribute(h.env.canvas.getElement(),"cursor","none"),d.mouseCursor=!1;return d.mouseCursor},1,[null,null,["self"],["visible"]]);k.set_visible=c;c=$pyjs__bind_method2("_nonimplemented_methods",function(a){a=!0===this.__is_instance__?this:a;var b;b=function(){$p.tuple($pyjs_array_slice.call(arguments,0,arguments.length));return null};b.__name__="$lambda1";b.__bind_type__=0;b.__args__=["arg",
null];a.set_pos=b;b=function(){$p.tuple($pyjs_array_slice.call(arguments,0,arguments.length));return!0};b.__name__="$lambda2";b.__bind_type__=0;b.__args__=["arg",null];a.get_focused=b;b=function(){$p.tuple($pyjs_array_slice.call(arguments,0,arguments.length));return null};b.__name__="$lambda3";b.__bind_type__=0;b.__args__=["arg",null];a.set_cursor=b;b=function(){$p.tuple($pyjs_array_slice.call(arguments,0,arguments.length));return $p.tuple([])};b.__name__="$lambda4";b.__bind_type__=0;b.__args__=["arg",
null];a.get_cursor=b;return null},1,[null,null,["self"]]);k._nonimplemented_methods=c;c=Array($p.object);var m=$p.dict(),p;for(p in k)m.__setitem__(p,k[p]);return $p._create_class("Mouse",$p.tuple(c),m)}();return this};
