$pyjs.loaded_modules["pyjsdl.time"]=function(p){if($pyjs.loaded_modules["pyjsdl.time"].__was_initialized__)return $pyjs.loaded_modules["pyjsdl.time"];"undefined"!=typeof $pyjs.loaded_modules.pyjsdl&&$pyjs.loaded_modules.pyjsdl.__was_initialized__||$p.___import___("pyjsdl",null);var l=$pyjs.loaded_modules["pyjsdl.time"];l.__repr__=function(){return"<module: pyjsdl.time>"};l.__was_initialized__=!0;if(null===p||"undefined"==typeof p)p="pyjsdl.time";l.__name__=p;$pyjs.loaded_modules.pyjsdl.time=$pyjs.loaded_modules["pyjsdl.time"];
l.pyjsdl=$p.___import___("pyjsdl.event","pyjsdl");l.env=$p.___import___("env","pyjsdl");l.__docformat__="restructuredtext";l.Clock=function(){var d={},c;d.__module__="pyjsdl.time";c=$pyjs__bind_method2("__init__",function(b){b=!0===this.__is_instance__?this:b;b.time_init=b.time();var a,n,k,c,g;n=$p.list();k=$p.range(10);"undefined"!=typeof(g=k.__array)?a=0:(k=k.__iter__(),a="undefined"!=typeof(g=k.__array)?0:"function"==typeof k.$genfunc?1:-1);for(c=0;"undefined"!=typeof(a?0<a?k.next(!0,!1):$p.wrapped_next(k):
g[c++]);)n.append(0);b.time_diff=n;b.pos=0;b.tick=b._tick_init;return null},1,[null,null,["self"]]);d.__init__=c;c=$pyjs__bind_method2("get_time",function(b){b=!0===this.__is_instance__?this:b;var a,n;return"undefined"!=typeof(n=b.time_diff).__array?"undefined"!=typeof n.__array[a=b.pos]?n.__array[a]:n.__getitem__(a):n.__getitem__(b.pos)},1,[null,null,["self"]]);d.get_time=c;c=$pyjs__bind_method2("_tick_init",function(b){if(!0===this.__is_instance__)var a=this;else a=arguments[0],b=arguments[1];"undefined"==
typeof b&&(b=arguments.callee.__args__[3][1]);var n,k,c,g,e,d,h,f,m;if(null===(g=!(null===(d=l.env.canvas.time_wait)||!1===d||0===d||""===d?0:"object"==typeof d?"function"==typeof d.__nonzero__?d.__nonzero__():"function"==typeof d.__len__?0<d.__len__():1:1))||!1===g||0===g||""===g?0:"object"==typeof g?"function"==typeof g.__nonzero__?g.__nonzero__():"function"==typeof g.__len__?0<g.__len__():1:1)g=a.time();else return a.time_init+=l.env.canvas.time_wait,null;d=g-a.time_init;a.time_init=g;(null===
(e=-1==(9===(f=a.pos)?0:"number"!=typeof f||"number"!=typeof f&&"string"!=typeof f&&"boolean"!=typeof f?$p.cmp(f,9):9==f?0:9>f?-1:1))||!1===e||0===e||""===e?0:"object"==typeof e?"function"==typeof e.__nonzero__?e.__nonzero__():"function"==typeof e.__len__?0<e.__len__():1:1)?(a.pos+=1,a.time_diff.__setitem__(a.pos,d),(null===(h=b)||!1===h||0===h||""===h?0:"object"==typeof h?"function"==typeof h.__nonzero__?h.__nonzero__():"function"==typeof h.__len__?0<h.__len__():1:1)&&l.env.canvas.set_timeout(1E3/
b-("undefined"!=typeof(c=a.time_diff).__array?"undefined"!=typeof c.__array[n=a.pos]?c.__array[n]:c.__getitem__(n):c.__getitem__(a.pos)))):(a.pos=0,a.time_diff.__setitem__(a.pos,d),a.tick=a._tick);return"undefined"!=typeof(k=a.time_diff).__array?"undefined"!=typeof k.__array[m=a.pos]?k.__array[m]:k.__getitem__(m):k.__getitem__(a.pos)},1,[null,null,["self"],["framerate",0]]);d._tick_init=c;c=$pyjs__bind_method2("_tick",function(b){if(!0===this.__is_instance__)var a=this;else a=arguments[0],b=arguments[1];
"undefined"==typeof b&&(b=arguments.callee.__args__[3][1]);var c,k,d,g,e,f,h;if(null===(g=!(null===(k=l.env.canvas.time_wait)||!1===k||0===k||""===k?0:"object"==typeof k?"function"==typeof k.__nonzero__?k.__nonzero__():"function"==typeof k.__len__?0<k.__len__():1:1))||!1===g||0===g||""===g?0:"object"==typeof g?"function"==typeof g.__nonzero__?g.__nonzero__():"function"==typeof g.__len__?0<g.__len__():1:1)k=a.time();else return a.time_init+=l.env.canvas.time_wait,null;g=k-a.time_init;a.time_init=k;
(null===(e=-1==(9===(h=a.pos)?0:"number"!=typeof h||"number"!=typeof h&&"string"!=typeof h&&"boolean"!=typeof h?$p.cmp(h,9):9==h?0:9>h?-1:1))||!1===e||0===e||""===e?0:"object"==typeof e?"function"==typeof e.__nonzero__?e.__nonzero__():"function"==typeof e.__len__?0<e.__len__():1:1)?(a.pos+=1,a.time_diff.__setitem__(a.pos,g)):(a.pos=0,a.time_diff.__setitem__(a.pos,g),(null===(d=b)||!1===d||0===d||""===d?0:"object"==typeof d?"function"==typeof d.__nonzero__?d.__nonzero__():"function"==typeof d.__len__?
0<d.__len__():1:1)&&l.env.canvas.set_timeout(1E3/b-$p.sum(a.time_diff)/10));return"undefined"!=typeof(f=a.time_diff).__array?"undefined"!=typeof f.__array[c=a.pos]?f.__array[c]:f.__getitem__(c):f.__getitem__(a.pos)},1,[null,null,["self"],["framerate",0]]);d._tick=c;c=$pyjs__bind_method2("tick_busy_loop",function(b){if(!0===this.__is_instance__)var a=this;else a=arguments[0],b=arguments[1];"undefined"==typeof b&&(b=arguments.callee.__args__[3][1]);return a.tick(b)},1,[null,null,["self"],["framerate",
0]]);d.tick_busy_loop=c;c=$pyjs__bind_method2("get_fps",function(b){return 1E3/($p.sum((!0===this.__is_instance__?this:b).time_diff)/10)},1,[null,null,["self"]]);d.get_fps=c;c=$pyjs__bind_method2("time",function(b){return(new Date).getTime()},1,[null,null,["self"]]);d.time=c;c=Array($p.object);var m=$p.dict(),f;for(f in d)m.__setitem__(f,d[f]);return $p._create_class("Clock",$p.tuple(c),m)}();l.Time=function(){var d={},c;d.__module__="pyjsdl.time";c=$pyjs__bind_method2("__init__",function(b){var a=
!0===this.__is_instance__?this:b;a._time_init=a.time();b=function(){return a.wait()};b.__name__="$lambda1";b.__bind_type__=0;b.__args__=[null,null];a.run=b;a.Clock=l.Clock;return null},1,[null,null,["self"]]);d.__init__=c;c=$pyjs__bind_method2("get_ticks",function(b){b=!0===this.__is_instance__?this:b;return b.time()-b._time_init},1,[null,null,["self"]]);d.get_ticks=c;c=$pyjs__bind_method2("delay",function(b,a){if(!0===this.__is_instance__)var c=this;else c=b,b=a;var d,f,g,e;for(g=c.time();null===
(e=-1==((d=c.time()-g)===(f=b)?0:typeof d!=typeof f||"number"!=typeof d&&"string"!=typeof d&&"boolean"!=typeof d?$p.cmp(d,f):d==f?0:d<f?-1:1))||!1===e||0===e||""===e?0:"object"==typeof e?"function"==typeof e.__nonzero__?e.__nonzero__():"function"==typeof e.__len__?0<e.__len__():1:1;);return c.time()-g},1,[null,null,["self"],["time"]]);d.delay=c;c=$pyjs__bind_method2("wait",function(b){if(!0===this.__is_instance__)var a=this;else a=arguments[0],b=arguments[1];"undefined"==typeof b&&(b=arguments.callee.__args__[3][1]);
var c;(null===(c=b)||!1===c||0===c||""===c?0:"object"==typeof c?"function"==typeof c.__nonzero__?c.__nonzero__():"function"==typeof c.__len__?0<c.__len__():1:1)?(l.env.canvas.set_timeWait(b),a.timeout(b,a)):l.env.canvas.set_timeWait(b);return null},1,[null,null,["self"],["time",0]]);d.wait=c;c=$pyjs__bind_method2("set_timer",function(b,a,c){!0!==this.__is_instance__&&(b=a,a=c);var d,f,g,e,m,h;(null===(e=!l._EventTimer.timers.__contains__(b))||!1===e||0===e||""===e?0:"object"==typeof e?"function"==
typeof e.__nonzero__?e.__nonzero__():"function"==typeof e.__len__?0<e.__len__():1:1)&&l._EventTimer.timers.__setitem__(b,("undefined"==typeof _EventTimer?l._EventTimer:_EventTimer)(b));(null===(h=a)||!1===h||0===h||""===h?0:"object"==typeof h?"function"==typeof h.__nonzero__?h.__nonzero__():"function"==typeof h.__len__?0<h.__len__():1:1)?("undefined"!=typeof(m=l._EventTimer.timers).__array?"undefined"!=typeof m.__array[d=b]?m.__array[d]:m.__getitem__(d):m.__getitem__(b)).start(a):("undefined"!=typeof(f=
l._EventTimer.timers).__array?"undefined"!=typeof f.__array[g=b]?f.__array[g]:f.__getitem__(g):f.__getitem__(b)).cancel();return null},1,[null,null,["self"],["eventid"],["time"]]);d.set_timer=c;c=$pyjs__bind_method2("time",function(b){return(new Date).getTime()},1,[null,null,["self"]]);d.time=c;c=$pyjs__bind_method2("timeout",function(b,a){!0!==this.__is_instance__&&(b=arguments[1],a=arguments[2]);"undefined"==typeof b&&(b=arguments.callee.__args__[3][1]);"undefined"==typeof a&&(a=arguments.callee.__args__[4][1]);
var c;c=function(){return a.run()};c.__name__="$lambda2";c.__bind_type__=0;c.__args__=[null,null];$wnd.setTimeout(function(){c()},b)},1,[null,null,["self"],["time",null],["obj",null]]);d.timeout=c;c=Array($p.object);var m=$p.dict(),f;for(f in d)m.__setitem__(f,d[f]);return $p._create_class("Time",$p.tuple(c),m)}();l._EventTimer=function(){var d={},c;d.__module__="pyjsdl.time";d.timers=$p.dict([]);c=$pyjs__bind_method2("__init__",function(b,a){if(!0===this.__is_instance__)var c=this;else c=b,b=a;c.eventid=
b;c.time=0;c.timer=null;c.repeat=!0;return null},1,[null,null,["self"],["eventid"]]);d.__init__=c;c=$pyjs__bind_method2("run",function(b){b=!0===this.__is_instance__?this:b;var a;l.pyjsdl.event.post(l.pyjsdl.event.Event(b.eventid));(null===(a=b.repeat)||!1===a||0===a||""===a?0:"object"==typeof a?"function"==typeof a.__nonzero__?a.__nonzero__():"function"==typeof a.__len__?0<a.__len__():1:1)&&b.timeout();return null},1,[null,null,["self"]]);d.run=c;c=$pyjs__bind_method2("timeout",function(b){var a=
!0===this.__is_instance__?this:b;b=$wnd.setTimeout(function(){a.run()},a.time);a.timer=b;return null},1,[null,null,["self"]]);d.timeout=c;c=$pyjs__bind_method2("start",function(b,a){if(!0===this.__is_instance__)var c=this;else c=b,b=a;var d;(null===(d=c.timer)||!1===d||0===d||""===d?0:"object"==typeof d?"function"==typeof d.__nonzero__?d.__nonzero__():"function"==typeof d.__len__?0<d.__len__():1:1)&&c.cancel();c.time=b;c.repeat=!0;c.timeout();return null},1,[null,null,["self"],["time"]]);d.start=
c;c=$pyjs__bind_method2("cancel",function(b){b=!0===this.__is_instance__?this:b;var a;if(null===(a=b.timer)||!1===a||0===a||""===a?0:"object"==typeof a?"function"==typeof a.__nonzero__?a.__nonzero__():"function"==typeof a.__len__?0<a.__len__():1:1)$wnd.clearTimeout(b.timer),b.timer=null;b.repeat=!1;return null},1,[null,null,["self"]]);d.cancel=c;c=Array(pyjslib.object);var m=$p.dict(),f;for(f in d)m.__setitem__(f,d[f]);return $p._create_class("_EventTimer",$p.tuple(c),m)}();return this};
