$pyjs.loaded_modules["pyjsdl.surface"]=function(W){if($pyjs.loaded_modules["pyjsdl.surface"].__was_initialized__)return $pyjs.loaded_modules["pyjsdl.surface"];"undefined"!=typeof $pyjs.loaded_modules.pyjsdl&&$pyjs.loaded_modules.pyjsdl.__was_initialized__||$p.___import___("pyjsdl",null);var n=$pyjs.loaded_modules["pyjsdl.surface"];n.__repr__=function(){return"<module: pyjsdl.surface>"};n.__was_initialized__=!0;if(null===W||"undefined"==typeof W)W="pyjsdl.surface";n.__name__=W;$pyjs.loaded_modules.pyjsdl.surface=
$pyjs.loaded_modules["pyjsdl.surface"];var y,V,m;n.HTML5Canvas=$p.___import___("pyjsdl.pyjsobj.HTML5Canvas","pyjsdl",null,!1);n.Rect=$p.___import___("pyjsdl.rect.Rect","pyjsdl",null,!1);n.rectPool=$p.___import___("pyjsdl.rect.rectPool","pyjsdl",null,!1);n.Color=$p.___import___("pyjsdl.color.Color","pyjsdl",null,!1);n.sys=$p.___import___("sys","pyjsdl");if(null===(m=-1==((y=n.sys.version_info)===(V=$p.tuple([3]))?0:typeof y!=typeof V||"number"!=typeof y&&"string"!=typeof y&&"boolean"!=typeof y?$p.cmp(y,
V):y==V?0:y<V?-1:1))||!1===m||0===m||""===m?0:"object"==typeof m?"function"==typeof m.__nonzero__?m.__nonzero__():"function"==typeof m.__len__?0<m.__len__():1:1)n.range=$p.xrange;n.__docformat__="restructuredtext";n.Surface=function(){var g={},b;g.__module__="pyjsdl.surface";b=$pyjs__bind_method2("__init__",function(a){if(!0===this.__is_instance__)var e=this,c=$p.tuple($pyjs_array_slice.call(arguments,1,arguments.length-1)),d=2<=arguments.length?arguments[arguments.length-1]:arguments[arguments.length];
else e=arguments[0],a=arguments[1],c=$p.tuple($pyjs_array_slice.call(arguments,2,arguments.length-1)),d=3<=arguments.length?arguments[arguments.length-1]:arguments[arguments.length];null===d||"object"!=typeof d||"dict"!=d.__name__||"undefined"==typeof d.$pyjs_is_kwarg?("undefined"!=typeof d&&c.__array.push(d),d=arguments[arguments.length+1]):delete d.$pyjs_is_kwarg;"undefined"==typeof d&&($p.__empty_dict(),"undefined"!=typeof a?null!==a&&"undefined"!=typeof a.$pyjs_is_kwarg&&(a=arguments[2]):"undefined"!=
typeof e&&null!==e&&"undefined"!=typeof e.$pyjs_is_kwarg&&(e=arguments[2]));var f,B;e.width=$p.float_int("undefined"!=typeof(B=a).__array?"undefined"!=typeof B.__array[0]?B.__array[0]:B.__getitem__(0):B.__getitem__(0));e.height=$p.float_int("undefined"!=typeof(f=a).__array?"undefined"!=typeof f.__array[1]?f.__array[1]:f.__getitem__(1):f.__getitem__(1));n.HTML5Canvas.__init__(e,e.width,e.height);n.HTML5Canvas.resize(e,e.width,e.height);e._display=null;e._super_surface=null;e._offset=$p.tuple([0,0]);
e._colorkey=null;e._stroke_style=null;e._fill_style=null;e._nonimplemented_methods();return null},1,["args",["kwargs"],["self"],["size"]]);g.__init__=b;b=$pyjs__bind_method2("__str__",function(a){a=!0===this.__is_instance__?this:a;return $p.sprintf("%s(%d,%d)",$p.tuple([a.__class__,a.width,a.height]))},1,[null,null,["self"]]);g.__str__=b;b=$pyjs__bind_method2("__repr__",function(a){a=!0===this.__is_instance__?this:a;return $p.sprintf("%s(%d,%d)",$p.tuple([a.__class__,a.width,a.height]))},1,[null,
null,["self"]]);g.__repr__=b;b=$pyjs__bind_method2("get_size",function(a){a=!0===this.__is_instance__?this:a;return $p.tuple([a.width,a.height])},1,[null,null,["self"]]);g.get_size=b;b=$pyjs__bind_method2("get_width",function(a){return(!0===this.__is_instance__?this:a).width},1,[null,null,["self"]]);g.get_width=b;b=$pyjs__bind_method2("get_height",function(a){return(!0===this.__is_instance__?this:a).height},1,[null,null,["self"]]);g.get_height=b;b=$pyjs__bind_method2("resize",function(a,e,c){if(!0===
this.__is_instance__)var d=this;else d=a,a=e,e=c;d.width=$p.float_int(a);d.height=$p.float_int(e);n.HTML5Canvas.resize(d,d.width,d.height);return null},1,[null,null,["self"],["width"],["height"]]);g.resize=b;b=$pyjs__bind_method2("get_rect",function(){if(!0===this.__is_instance__)var a=this,e=1<=arguments.length?arguments[arguments.length-1]:arguments[arguments.length];else a=arguments[0],e=2<=arguments.length?arguments[arguments.length-1]:arguments[arguments.length];null===e||"object"!=typeof e||
"dict"!=e.__name__||"undefined"==typeof e.$pyjs_is_kwarg?e=arguments[arguments.length+1]:delete e.$pyjs_is_kwarg;"undefined"==typeof e&&(e=$p.__empty_dict(),"undefined"!=typeof a&&null!==a&&"undefined"!=typeof a.$pyjs_is_kwarg&&(e=a,a=arguments[1]));var c,d,f,B,h,b,k;b=n.Rect(0,0,a.width,a.height);B=e;"undefined"!=typeof(a=B.__array)?k=0:(B=B.__iter__(),k="undefined"!=typeof(a=B.__array)?0:"function"==typeof B.$genfunc?1:-1);for(f=0;"undefined"!=typeof(c=k?0<k?B.next(!0,!1):$p.wrapped_next(B):a[f++]);)$p.setattr(b,
c,"undefined"!=typeof(d=e).__array?"undefined"!=typeof d.__array[h=c]?d.__array[h]:d.__getitem__(h):d.__getitem__(c));return b},1,[null,["attr"],["self"]]);g.get_rect=b;b=$pyjs__bind_method2("copy",function(a){a=!0===this.__is_instance__?this:a;var e;e=n.Surface($p.tuple([a.width,a.height]));e.drawImage(a.canvas,0,0);return e},1,[null,null,["self"]]);g.copy=b;b=$pyjs__bind_method2("subsurface",function(a,e){if(!0===this.__is_instance__)var c=this;else c=a,a=e;var d,f,b,h,l,k,g,v,q,p,r,t;if(null===
(l=$p.tuple(["t","f"]).__contains__(a))||!1===l||0===l||""===l?0:"object"==typeof l?"function"==typeof l.__nonzero__?l.__nonzero__():"function"==typeof l.__len__?0<l.__len__():1:1){if(null===(d=!(null===(k=c._super_surface)||!1===k||0===k||""===k?0:"object"==typeof k?"function"==typeof k.__nonzero__?k.__nonzero__():"function"==typeof k.__len__?0<k.__len__():1:1))||!1===d||0===d||""===d?0:"object"==typeof d?"function"==typeof d.__nonzero__?d.__nonzero__():"function"==typeof d.__len__?0<d.__len__():
1:1)return null;(null===(f="t"===(h=a)&&null===h?!0:null===h?!1:"object"!=typeof h&&"function"!=typeof h||"function"!=typeof h.__cmp__?"t"==h:0===h.__cmp__("t"))||!1===f||0===f||""===f?0:"object"==typeof f?"function"==typeof f.__nonzero__?f.__nonzero__():"function"==typeof f.__len__?0<f.__len__():1:1)?c.drawImage(c._super_surface.canvas,"undefined"!=typeof(q=c._offset).__array?"undefined"!=typeof q.__array[0]?q.__array[0]:q.__getitem__(0):q.__getitem__(0),"undefined"!=typeof(v=c._offset).__array?
"undefined"!=typeof v.__array[1]?v.__array[1]:v.__getitem__(1):v.__getitem__(1),c.width,c.height,0,0,c.width,c.height):c._super_surface.drawImage(c.canvas,"undefined"!=typeof(r=c._offset).__array?"undefined"!=typeof r.__array[0]?r.__array[0]:r.__getitem__(0):r.__getitem__(0),"undefined"!=typeof(t=c._offset).__array?"undefined"!=typeof t.__array[1]?t.__array[1]:t.__getitem__(1):t.__getitem__(1));return null}d=(null===(b=$p.hasattr(a,"width"))||!1===b||0===b||""===b?0:"object"==typeof b?"function"==
typeof b.__nonzero__?b.__nonzero__():"function"==typeof b.__len__?0<b.__len__():1:1)?a:n.Rect(a);if(null===(p=!(null===(g=c.get_rect().contains(d))||!1===g||0===g||""===g?0:"object"==typeof g?"function"==typeof g.__nonzero__?g.__nonzero__():"function"==typeof g.__len__?0<g.__len__():1:1))||!1===p||0===p||""===p?0:"object"==typeof p?"function"==typeof p.__nonzero__?p.__nonzero__():"function"==typeof p.__len__?0<p.__len__():1:1)throw $p.ValueError("subsurface outside surface area");b=c.getSubimage(d.x,
d.y,d.width,d.height);b._super_surface=c;b._offset=$p.tuple([d.x,d.y]);b._colorkey=c._colorkey;return b},1,[null,null,["self"],["rect"]]);g.subsurface=b;b=$pyjs__bind_method2("getSubimage",function(a,e,c,d,f){if(!0===this.__is_instance__)var b=this;else b=a,a=e,e=c,c=d,d=f;f=n.Surface($p.tuple([c,d]));f.drawImage(b.canvas,a,e,c,d,0,0,c,d);return f},1,[null,null,["self"],["x"],["y"],["width"],["height"]]);g.getSubimage=b;b=$pyjs__bind_method2("blit",function(a,e,c){if(!0===this.__is_instance__)var d=
this;else d=arguments[0],a=arguments[1],e=arguments[2],c=arguments[3];"undefined"==typeof c&&(c=arguments.callee.__args__[5][1]);var f,b,h,l,k,g,v,q,p,r,t,s,w,u,A;(null===(f=!(null===(p=c)||!1===p||0===p||""===p?0:"object"==typeof p?"function"==typeof p.__nonzero__?p.__nonzero__():"function"==typeof p.__len__?0<p.__len__():1:1))||!1===f||0===f||""===f?0:"object"==typeof f?"function"==typeof f.__nonzero__?f.__nonzero__():"function"==typeof f.__len__?0<f.__len__():1:1)?(f=n.rectPool.get("undefined"!=
typeof(t=e).__array?"undefined"!=typeof t.__array[0]?t.__array[0]:t.__getitem__(0):t.__getitem__(0),"undefined"!=typeof(s=e).__array?"undefined"!=typeof s.__array[1]?s.__array[1]:s.__getitem__(1):s.__getitem__(1),a.width,a.height),d.impl.canvasContext.drawImage(a.canvas,f.x,f.y)):(f=n.rectPool.get("undefined"!=typeof(u=e).__array?"undefined"!=typeof u.__array[0]?u.__array[0]:u.__getitem__(0):u.__getitem__(0),"undefined"!=typeof(k=e).__array?"undefined"!=typeof k.__array[1]?k.__array[1]:k.__getitem__(1):
k.__getitem__(1),"undefined"!=typeof(r=c).__array?"undefined"!=typeof r.__array[2]?r.__array[2]:r.__getitem__(2):r.__getitem__(2),"undefined"!=typeof(g=c).__array?"undefined"!=typeof g.__array[3]?g.__array[3]:g.__getitem__(3):g.__getitem__(3)),d.impl.canvasContext.drawImage(a.canvas,"undefined"!=typeof(v=c).__array?"undefined"!=typeof v.__array[0]?v.__array[0]:v.__getitem__(0):v.__getitem__(0),"undefined"!=typeof(l=c).__array?"undefined"!=typeof l.__array[1]?l.__array[1]:l.__getitem__(1):l.__getitem__(1),
"undefined"!=typeof(A=c).__array?"undefined"!=typeof A.__array[2]?A.__array[2]:A.__getitem__(2):A.__getitem__(2),"undefined"!=typeof(b=c).__array?"undefined"!=typeof b.__array[3]?b.__array[3]:b.__getitem__(3):b.__getitem__(3),f.x,f.y,"undefined"!=typeof(h=c).__array?"undefined"!=typeof h.__array[2]?h.__array[2]:h.__getitem__(2):h.__getitem__(2),"undefined"!=typeof(w=c).__array?"undefined"!=typeof w.__array[3]?w.__array[3]:w.__getitem__(3):w.__getitem__(3)));d=((null===(q=d._display)||!1===q||0===
q||""===q?0:"object"==typeof q?"function"==typeof q.__nonzero__?q.__nonzero__():"function"==typeof q.__len__?0<q.__len__():1:1)?d._display._surface_rect:d.get_rect()).clip(f);n.rectPool.append(f);return d},1,[null,null,["self"],["surface"],["position"],["area",null]]);g.blit=b;b=$pyjs__bind_method2("_blits",function(a,e){if(!0===this.__is_instance__)var c=this;else c=a,a=e;var d,f,b,h,l,k;b=c.impl.canvasContext;f=a;"undefined"!=typeof(k=f.__array)?c=0:(f=f.__iter__(),c="undefined"!=typeof(k=f.__array)?
0:"function"==typeof f.$genfunc?1:-1);for(h=0;"undefined"!=typeof(d=c?0<c?f.next(!0,!1):$p.wrapped_next(f):k[h++]);)l=$p.__ass_unpack(d,2,null),d=l[0],l=l[1],b.drawImage(d.canvas,l.x,l.y);return null},1,[null,null,["self"],["surfaces"]]);g._blits=b;b=$pyjs__bind_method2("_blit_clear",function(a,e,c){if(!0===this.__is_instance__)var d=this;else d=a,a=e,e=c;var f,b,h;c=d.impl.canvasContext;f=e;"undefined"!=typeof(b=f.__array)?e=0:(f=f.__iter__(),e="undefined"!=typeof(b=f.__array)?0:"function"==typeof f.$genfunc?
1:-1);for(d=0;"undefined"!=typeof(h=e?0<e?f.next(!0,!1):$p.wrapped_next(f):b[d++]);)c.drawImage(a.canvas,h.x,h.y,h.width,h.height,h.x,h.y,h.width,h.height);return null},1,[null,null,["self"],["surface"],["rect_list"]]);g._blit_clear=b;b=$pyjs__bind_method2("set_colorkey",function(a,e){if(!0===this.__is_instance__)var c=this;else c=arguments[0],a=arguments[1],e=arguments[2];"undefined"==typeof e&&(e=arguments.callee.__args__[4][1]);var d,f;if(null===(f=c._colorkey)||!1===f||0===f||""===f?0:"object"==
typeof f?"function"==typeof f.__nonzero__?f.__nonzero__():"function"==typeof f.__len__?0<f.__len__():1:1)c.replace_color($p.tuple([0,0,0,0]),c._colorkey),c._colorkey=null;if(null===(d=a)||!1===d||0===d||""===d?0:"object"==typeof d?"function"==typeof d.__nonzero__?d.__nonzero__():"function"==typeof d.__len__?0<d.__len__():1:1)c._colorkey=n.Color(a),c.replace_color(c._colorkey);return null},1,[null,null,["self"],["color"],["flags",null]]);g.set_colorkey=b;b=$pyjs__bind_method2("get_colorkey",function(a){a=
!0===this.__is_instance__?this:a;var e;return(null===(e=a._colorkey)||!1===e||0===e||""===e?0:"object"==typeof e?"function"==typeof e.__nonzero__?e.__nonzero__():"function"==typeof e.__len__?0<e.__len__():1:1)?$p.tuple([a._colorkey.r,a._colorkey.g,a._colorkey.b,a._colorkey.a]):null},1,[null,null,["self"]]);g.get_colorkey=b;b=$pyjs__bind_method2("_getPixel",function(a,e,c){!0!==this.__is_instance__&&(a=e,e=c);return a.data[e]},1,[null,null,["self"],["imagedata"],["index"]]);g._getPixel=b;b=$pyjs__bind_method2("_setPixel",
function(a,e,c,d){!0!==this.__is_instance__&&(a=e,e=c,c=d);c=$p.str(c);a.data[e]=c;return null},1,[null,null,["self"],["imagedata"],["index"],["dat"]]);g._setPixel=b;b=$pyjs__bind_method2("replace_color",function(a,e){if(!0===this.__is_instance__)var c=this;else c=arguments[0],a=arguments[1],e=arguments[2];"undefined"==typeof e&&(e=arguments.callee.__args__[4][1]);var d,f,b,h,l,k,g,v,q,p,r,t,s,w,u,A,m,D,C,E,F,G,z,y,H,P,I,J,Q,K,x,R,S,L,M,T,N,U,O;z=c.impl.getImageData(0,0,c.width,c.height);s=(null===
(h=$p.hasattr(a,"a"))||!1===h||0===h||""===h?0:"object"==typeof h?"function"==typeof h.__nonzero__?h.__nonzero__():"function"==typeof h.__len__?0<h.__len__():1:1)?a:n.Color(a);(null===(l=null===e)||!1===l||0===l||""===l?0:"object"==typeof l?"function"==typeof l.__nonzero__?l.__nonzero__():"function"==typeof l.__len__?0<l.__len__():1:1)?h=!0:(w=(null===(k=$p.hasattr(e,"a"))||!1===k||0===k||""===k?0:"object"==typeof k?"function"==typeof k.__nonzero__?k.__nonzero__():"function"==typeof k.__len__?0<k.__len__():
1:1)?e:n.Color(e),h=!1);if(null===(d=h)||!1===d||0===d||""===d?0:"object"==typeof d?"function"==typeof d.__nonzero__?d.__nonzero__():"function"==typeof d.__len__?0<d.__len__():1:1)for(r=$p.__ass_unpack($p.tuple([s.r,s.g,s.b,s.a]),4,null),h=r[0],d=r[1],s=r[2],l=r[3],w=0,r=n.range(0,null===(R=z.data)?0:"undefined"!=typeof R.__array?R.__array.length:"function"==typeof R.__len__?R.__len__():"undefined"!=typeof R.length?R.length:$p.len(R),4),"undefined"!=typeof(t=r.__array)?g=0:(r=r.__iter__(),g="undefined"!=
typeof(t=r.__array)?0:"function"==typeof r.$genfunc?1:-1),C=0;"undefined"!=typeof(u=g?0<g?r.next(!0,!1):$p.wrapped_next(r):t[C++]);)x=u,(null===(D=(null===(f=v=(M=c._getPixel(z,x))===(U=h)&&null===M?!0:null===M?!1:null===U?!1:"object"!=typeof M&&"function"!=typeof M||"function"!=typeof M.__cmp__?"object"!=typeof U&&"function"!=typeof U||"function"!=typeof U.__cmp__?M==U:0===U.__cmp__(M):0===M.__cmp__(U))||!1===f||0===f||""===f?0:"object"==typeof f?"function"==typeof f.__nonzero__?f.__nonzero__():
"function"==typeof f.__len__?0<f.__len__():1:1)?(null===(m=q=(O=c._getPixel(z,x+1))===(T=d)&&null===O?!0:null===O?!1:null===T?!1:"object"!=typeof O&&"function"!=typeof O||"function"!=typeof O.__cmp__?"object"!=typeof T&&"function"!=typeof T||"function"!=typeof T.__cmp__?O==T:0===T.__cmp__(O):0===O.__cmp__(T))||!1===m||0===m||""===m?0:"object"==typeof m?"function"==typeof m.__nonzero__?m.__nonzero__():"function"==typeof m.__len__?0<m.__len__():1:1)?(null===(b=p=(N=c._getPixel(z,x+2))===(S=s)&&null===
N?!0:null===N?!1:null===S?!1:"object"!=typeof N&&"function"!=typeof N||"function"!=typeof N.__cmp__?"object"!=typeof S&&"function"!=typeof S||"function"!=typeof S.__cmp__?N==S:0===S.__cmp__(N):0===N.__cmp__(S))||!1===b||0===b||""===b?0:"object"==typeof b?"function"==typeof b.__nonzero__?b.__nonzero__():"function"==typeof b.__len__?0<b.__len__():1:1)?(L=c._getPixel(z,x+3))===(A=l)&&null===L?!0:null===L?!1:null===A?!1:"object"!=typeof L&&"function"!=typeof L||"function"!=typeof L.__cmp__?"object"!=
typeof A&&"function"!=typeof A||"function"!=typeof A.__cmp__?L==A:0===A.__cmp__(L):0===L.__cmp__(A):p:q:v)||!1===D||0===D||""===D?0:"object"==typeof D?"function"==typeof D.__nonzero__?D.__nonzero__():"function"==typeof D.__len__?0<D.__len__():1:1)&&c._setPixel(z,x+3,w);else for(l=$p.__ass_unpack($p.tuple([s.r,s.g,s.b,s.a]),4,null),h=l[0],d=l[1],s=l[2],l=l[3],p=$p.__ass_unpack($p.tuple([w.r,w.g,w.b,w.a]),4,null),q=p[0],f=p[1],v=p[2],w=p[3],p=n.range(0,null===(x=z.data)?0:"undefined"!=typeof x.__array?
x.__array.length:"function"==typeof x.__len__?x.__len__():"undefined"!=typeof x.length?x.length:$p.len(x),4),"undefined"!=typeof(m=p.__array)?D=0:(p=p.__iter__(),D="undefined"!=typeof(m=p.__array)?0:"function"==typeof p.$genfunc?1:-1),b=0;"undefined"!=typeof(A=D?0<D?p.next(!0,!1):$p.wrapped_next(p):m[b++]);)if(x=A,null===(F=(null===(G=r=(H=c._getPixel(z,x))===(P=h)&&null===H?!0:null===H?!1:null===P?!1:"object"!=typeof H&&"function"!=typeof H||"function"!=typeof H.__cmp__?"object"!=typeof P&&"function"!=
typeof P||"function"!=typeof P.__cmp__?H==P:0===P.__cmp__(H):0===H.__cmp__(P))||!1===G||0===G||""===G?0:"object"==typeof G?"function"==typeof G.__nonzero__?G.__nonzero__():"function"==typeof G.__len__?0<G.__len__():1:1)?(null===(E=g=(I=c._getPixel(z,x+1))===(C=d)&&null===I?!0:null===I?!1:null===C?!1:"object"!=typeof I&&"function"!=typeof I||"function"!=typeof I.__cmp__?"object"!=typeof C&&"function"!=typeof C||"function"!=typeof C.__cmp__?I==C:0===C.__cmp__(I):0===I.__cmp__(C))||!1===E||0===E||""===
E?0:"object"==typeof E?"function"==typeof E.__nonzero__?E.__nonzero__():"function"==typeof E.__len__?0<E.__len__():1:1)?(null===(u=t=(J=c._getPixel(z,x+2))===(Q=s)&&null===J?!0:null===J?!1:null===Q?!1:"object"!=typeof J&&"function"!=typeof J||"function"!=typeof J.__cmp__?"object"!=typeof Q&&"function"!=typeof Q||"function"!=typeof Q.__cmp__?J==Q:0===Q.__cmp__(J):0===J.__cmp__(Q))||!1===u||0===u||""===u?0:"object"==typeof u?"function"==typeof u.__nonzero__?u.__nonzero__():"function"==typeof u.__len__?
0<u.__len__():1:1)?(K=c._getPixel(z,x+3))===(y=l)&&null===K?!0:null===K?!1:null===y?!1:"object"!=typeof K&&"function"!=typeof K||"function"!=typeof K.__cmp__?"object"!=typeof y&&"function"!=typeof y||"function"!=typeof y.__cmp__?K==y:0===y.__cmp__(K):0===K.__cmp__(y):t:g:r)||!1===F||0===F||""===F?0:"object"==typeof F?"function"==typeof F.__nonzero__?F.__nonzero__():"function"==typeof F.__len__?0<F.__len__():1:1)c._setPixel(z,x,q),c._setPixel(z,x+1,f),c._setPixel(z,x+2,v),c._setPixel(z,x+3,w);c.impl.putImageData(z,
0,0,0,0,c.width,c.height);return null},1,[null,null,["self"],["color"],["new_color",null]]);g.replace_color=b;b=$pyjs__bind_method2("get_at",function(a,e){if(!0===this.__is_instance__)var c=this;else c=a,a=e;var d,b,g;g=c.impl.getImageData("undefined"!=typeof(d=a).__array?"undefined"!=typeof d.__array[0]?d.__array[0]:d.__getitem__(0):d.__getitem__(0),"undefined"!=typeof(b=a).__array?"undefined"!=typeof b.__array[1]?b.__array[1]:b.__getitem__(1):b.__getitem__(1),1,1);return n.Color(function(){var a,
e,d,b,f,q;d=$p.list();q=$p.tuple([0,1,2,3]);"undefined"!=typeof(f=q.__array)?e=0:(q=q.__iter__(),e="undefined"!=typeof(f=q.__array)?0:"function"==typeof q.$genfunc?1:-1);for(a=0;"undefined"!=typeof(b=e?0<e?q.next(!0,!1):$p.wrapped_next(q):f[a++]);)d.append(c._getPixel(g,b));return d}())},1,[null,null,["self"],["pos"]]);g.get_at=b;b=$pyjs__bind_method2("set_at",function(a,e,c){if(!0===this.__is_instance__)var d=this;else d=a,a=e,e=c;var b,g,h,l,k,m;if(null===(l=!((h=d._fill_style)===(g=e)&&null===
h||(null===h?0:null===g?0:"object"!=typeof h&&"function"!=typeof h||"function"!=typeof h.__cmp__?"object"!=typeof g&&"function"!=typeof g||"function"!=typeof g.__cmp__?h==g:0===g.__cmp__(h):0===h.__cmp__(g))))||!1===l||0===l||""===l?0:"object"==typeof l?"function"==typeof l.__nonzero__?l.__nonzero__():"function"==typeof l.__len__?0<l.__len__():1:1)d._fill_style=e,e=(null===(b=$p.hasattr(e,"a"))||!1===b||0===b||""===b?0:"object"==typeof b?"function"==typeof b.__nonzero__?b.__nonzero__():"function"==
typeof b.__len__?0<b.__len__():1:1)?e:n.Color(e),d.setFillStyle(e);d.fillRect("undefined"!=typeof(k=a).__array?"undefined"!=typeof k.__array[0]?k.__array[0]:k.__getitem__(0):k.__getitem__(0),"undefined"!=typeof(m=a).__array?"undefined"!=typeof m.__array[1]?m.__array[1]:m.__getitem__(1):m.__getitem__(1),1,1);return null},1,[null,null,["self"],["pos"],["color"]]);g.set_at=b;b=$pyjs__bind_method2("fill",function(a,e){if(!0===this.__is_instance__)var c=this;else c=arguments[0],a=arguments[1],e=arguments[2];
"undefined"==typeof a&&(a=arguments.callee.__args__[3][1]);"undefined"==typeof e&&(e=arguments.callee.__args__[4][1]);var b,f,g,h,l,k,m,v,q,p,r,t,s,w,u;if(null===(b=null===a)||!1===b||0===b||""===b?0:"object"==typeof b?"function"==typeof b.__nonzero__?b.__nonzero__():"function"==typeof b.__len__?0<b.__len__():1:1)return n.HTML5Canvas.fill(c),null;if(null===(q=a)||!1===q||0===q||""===q?0:"object"==typeof q?"function"==typeof q.__nonzero__?q.__nonzero__():"function"==typeof q.__len__?0<q.__len__():
1:1){if(null===(p=!((h=c._fill_style)===(l=a)&&null===h||(null===h?0:null===l?0:"object"!=typeof h&&"function"!=typeof h||"function"!=typeof h.__cmp__?"object"!=typeof l&&"function"!=typeof l||"function"!=typeof l.__cmp__?h==l:0===l.__cmp__(h):0===h.__cmp__(l))))||!1===p||0===p||""===p?0:"object"==typeof p?"function"==typeof p.__nonzero__?p.__nonzero__():"function"==typeof p.__len__?0<p.__len__():1:1)c._fill_style=a,(null===(m=$p.hasattr(a,"a"))||!1===m||0===m||""===m?0:"object"==typeof m?"function"==
typeof m.__nonzero__?m.__nonzero__():"function"==typeof m.__len__?0<m.__len__():1:1)?c.setFillStyle(a):c.setFillStyle(n.Color(a));if(null===(s=!(null===(v=e)||!1===v||0===v||""===v?0:"object"==typeof v?"function"==typeof v.__nonzero__?v.__nonzero__():"function"==typeof v.__len__?0<v.__len__():1:1))||!1===s||0===s||""===s?0:"object"==typeof s?"function"==typeof s.__nonzero__?s.__nonzero__():"function"==typeof s.__len__?0<s.__len__():1:1)k=n.Rect(0,0,c.width,c.height);else if(b=(null===(k=c._display)||
!1===k||0===k||""===k?0:"object"==typeof k?"function"==typeof k.__nonzero__?k.__nonzero__():"function"==typeof k.__len__?0<k.__len__():1:1)?c._display._surface_rect:c.get_rect(),k=(null===(r=$p.hasattr(e,"width"))||!1===r||0===r||""===r?0:"object"==typeof r?"function"==typeof r.__nonzero__?r.__nonzero__():"function"==typeof r.__len__?0<r.__len__():1:1)?b.clip(e):b.clip(n.Rect(e)),null===(f=(null===(w=g=!(null===(t=k.width)||!1===t||0===t||""===t?0:"object"==typeof t?"function"==typeof t.__nonzero__?
t.__nonzero__():"function"==typeof t.__len__?0<t.__len__():1:1))||!1===w||0===w||""===w?0:"object"==typeof w?"function"==typeof w.__nonzero__?w.__nonzero__():"function"==typeof w.__len__?0<w.__len__():1:1)?g:!(null===(u=k.height)||!1===u||0===u||""===u?0:"object"==typeof u?"function"==typeof u.__nonzero__?u.__nonzero__():"function"==typeof u.__len__?0<u.__len__():1:1))||!1===f||0===f||""===f?0:"object"==typeof f?"function"==typeof f.__nonzero__?f.__nonzero__():"function"==typeof f.__len__?0<f.__len__():
1:1)return k;c.fillRect(k.x,k.y,k.width,k.height)}else k=n.Rect(0,0,c.width,c.height),c.clear();return k},1,[null,null,["self"],["color",null],["rect",null]]);g.fill=b;b=$pyjs__bind_method2("get_parent",function(a){return(!0===this.__is_instance__?this:a)._super_surface},1,[null,null,["self"]]);g.get_parent=b;b=$pyjs__bind_method2("get_offset",function(a){return(!0===this.__is_instance__?this:a)._offset},1,[null,null,["self"]]);g.get_offset=b;b=$pyjs__bind_method2("toDataURL",function(a){if(!0===
this.__is_instance__)var b=this;else b=arguments[0],a=arguments[1];"undefined"==typeof a&&(a=arguments.callee.__args__[3][1]);var c,d;return(null===(c=!(null===(d=a)||!1===d||0===d||""===d?0:"object"==typeof d?"function"==typeof d.__nonzero__?d.__nonzero__():"function"==typeof d.__len__?0<d.__len__():1:1))||!1===c||0===c||""===c?0:"object"==typeof c?"function"==typeof c.__nonzero__?c.__nonzero__():"function"==typeof c.__len__?0<c.__len__():1:1)?b.canvas.toDataURL():b.canvas.toDataURL(a)},1,[null,
null,["self"],["datatype",null]]);g.toDataURL=b;b=$pyjs__bind_method2("_nonimplemented_methods",function(a){var b=!0===this.__is_instance__?this:a;a=function(){$p.tuple($pyjs_array_slice.call(arguments,0,arguments.length));return b};a.__name__="$lambda1";a.__bind_type__=0;a.__args__=["arg",null];b.convert=a;a=function(){$p.tuple($pyjs_array_slice.call(arguments,0,arguments.length));return b};a.__name__="$lambda2";a.__bind_type__=0;a.__args__=["arg",null];b.convert_alpha=a;a=function(){$p.tuple($pyjs_array_slice.call(arguments,
0,arguments.length));return null};a.__name__="$lambda3";a.__bind_type__=0;a.__args__=["arg",null];b.set_alpha=a;a=function(){$p.tuple($pyjs_array_slice.call(arguments,0,arguments.length));return null};a.__name__="$lambda4";a.__bind_type__=0;a.__args__=["arg",null];b.get_alpha=a;a=function(){$p.tuple($pyjs_array_slice.call(arguments,0,arguments.length));return null};a.__name__="$lambda5";a.__bind_type__=0;a.__args__=["arg",null];b.lock=a;a=function(){$p.tuple($pyjs_array_slice.call(arguments,0,arguments.length));
return null};a.__name__="$lambda6";a.__bind_type__=0;a.__args__=["arg",null];b.unlock=a;a=function(){$p.tuple($pyjs_array_slice.call(arguments,0,arguments.length));return!1};a.__name__="$lambda7";a.__bind_type__=0;a.__args__=["arg",null];b.mustlock=a;a=function(){$p.tuple($pyjs_array_slice.call(arguments,0,arguments.length));return!1};a.__name__="$lambda8";a.__bind_type__=0;a.__args__=["arg",null];b.get_locked=a;a=function(){$p.tuple($pyjs_array_slice.call(arguments,0,arguments.length));return $p.tuple([])};
a.__name__="$lambda9";a.__bind_type__=0;a.__args__=["arg",null];b.get_locks=a;return null},1,[null,null,["self"]]);g._nonimplemented_methods=b;b=Array(n.HTML5Canvas);var m=$p.dict(),C;for(C in g)m.__setitem__(C,g[C]);return $p._create_class("Surface",$p.tuple(b),m)}();n.Surf=function(){var g={},b;g.__module__="pyjsdl.surface";b=$pyjs__bind_method2("__init__",function(a,b){if(!0===this.__is_instance__)var c=this;else c=a,a=b;c.canvas=a;var d=$p.__ass_unpack($p.tuple([c.canvas.width,c.canvas.height]),
2,null);c.width=d[0];c.height=d[1];c._nonimplemented_methods();return null},1,[null,null,["self"],["image"]]);g.__init__=b;b=$pyjs__bind_method2("get_size",function(a){a=!0===this.__is_instance__?this:a;return $p.tuple([a.width,a.height])},1,[null,null,["self"]]);g.get_size=b;b=$pyjs__bind_method2("get_width",function(a){return(!0===this.__is_instance__?this:a).width},1,[null,null,["self"]]);g.get_width=b;b=$pyjs__bind_method2("get_height",function(a){return(!0===this.__is_instance__?this:a).height},
1,[null,null,["self"]]);g.get_height=b;b=$pyjs__bind_method2("_nonimplemented_methods",function(a){var b=!0===this.__is_instance__?this:a;a=function(){$p.tuple($pyjs_array_slice.call(arguments,0,arguments.length));return b};a.__name__="$lambda10";a.__bind_type__=0;a.__args__=["arg",null];b.convert=a;a=function(){$p.tuple($pyjs_array_slice.call(arguments,0,arguments.length));return b};a.__name__="$lambda11";a.__bind_type__=0;a.__args__=["arg",null];b.convert_alpha=a;a=function(){$p.tuple($pyjs_array_slice.call(arguments,
0,arguments.length));return null};a.__name__="$lambda12";a.__bind_type__=0;a.__args__=["arg",null];b.set_alpha=a;a=function(){$p.tuple($pyjs_array_slice.call(arguments,0,arguments.length));return null};a.__name__="$lambda13";a.__bind_type__=0;a.__args__=["arg",null];b.get_alpha=a;a=function(){$p.tuple($pyjs_array_slice.call(arguments,0,arguments.length));return null};a.__name__="$lambda14";a.__bind_type__=0;a.__args__=["arg",null];b.lock=a;a=function(){$p.tuple($pyjs_array_slice.call(arguments,0,
arguments.length));return null};a.__name__="$lambda15";a.__bind_type__=0;a.__args__=["arg",null];b.unlock=a;a=function(){$p.tuple($pyjs_array_slice.call(arguments,0,arguments.length));return!1};a.__name__="$lambda16";a.__bind_type__=0;a.__args__=["arg",null];b.mustlock=a;a=function(){$p.tuple($pyjs_array_slice.call(arguments,0,arguments.length));return!1};a.__name__="$lambda17";a.__bind_type__=0;a.__args__=["arg",null];b.get_locked=a;a=function(){$p.tuple($pyjs_array_slice.call(arguments,0,arguments.length));
return $p.tuple([])};a.__name__="$lambda18";a.__bind_type__=0;a.__args__=["arg",null];b.get_locks=a;return null},1,[null,null,["self"]]);g._nonimplemented_methods=b;b=Array($p.object);var m=$p.dict(),n;for(n in g)m.__setitem__(n,g[n]);return $p._create_class("Surf",$p.tuple(b),m)}();n.IndexSizeError=function(){var g={__module__:"pyjsdl.surface"},b=Array($p.Exception),m=$p.dict(),n;for(n in g)m.__setitem__(n,g[n]);return $p._create_class("IndexSizeError",$p.tuple(b),m)}();return this};
