$pyjs.loaded_modules["pyjsdl.mask"]=function(fa){if($pyjs.loaded_modules["pyjsdl.mask"].__was_initialized__)return $pyjs.loaded_modules["pyjsdl.mask"];"undefined"!=typeof $pyjs.loaded_modules.pyjsdl&&$pyjs.loaded_modules.pyjsdl.__was_initialized__||$p.___import___("pyjsdl",null);var h=$pyjs.loaded_modules["pyjsdl.mask"];h.__repr__=function(){return"<module: pyjsdl.mask>"};h.__was_initialized__=!0;if(null===fa||"undefined"==typeof fa)fa="pyjsdl.mask";h.__name__=fa;$pyjs.loaded_modules.pyjsdl.mask=
$pyjs.loaded_modules["pyjsdl.mask"];var y,A,r;h.BitSet=$p.___import___("pyjsdl.pyjsarray.BitSet","pyjsdl",null,!1);h.Color=$p.___import___("pyjsdl.color.Color","pyjsdl",null,!1);h.sys=$p.___import___("sys","pyjsdl");if(null===(r=-1==((y=h.sys.version_info)===(A=$p.tuple([3]))?0:typeof y!=typeof A||"number"!=typeof y&&"string"!=typeof y&&"boolean"!=typeof y?$p.cmp(y,A):y==A?0:y<A?-1:1))||!1===r||0===r||""===r?0:"object"==typeof r?"function"==typeof r.__nonzero__?r.__nonzero__():"function"==typeof r.__len__?
0<r.__len__():1:1)h.range=$p.xrange;h.__docformat__="restructuredtext";h.from_surface=function(d,a){"undefined"==typeof a&&(a=arguments.callee.__args__[3][1]);var l,g,c,m,k,b,e,f,t,x,n,B,p,s,C,v,q,w;s=("undefined"==typeof Mask?h.Mask:Mask)($p.tuple([d.width,d.height]));if(null===(b=!(null===(c=s.bit)||!1===c||0===c||""===c?0:"object"==typeof c?"function"==typeof c.__nonzero__?c.__nonzero__():"function"==typeof c.__len__?0<c.__len__():1:1))||!1===b||0===b||""===b?0:"object"==typeof b?"function"==typeof b.__nonzero__?
b.__nonzero__():"function"==typeof b.__len__?0<b.__len__():1:1)return null;b=d.impl.getImageData(0,0,d.width,d.height);m=$p.__ass_unpack($p.tuple([4*d.width,d.height]),2,null);c=m[0];p=h.range(0,m[1]);"undefined"!=typeof(m=p.__array)?n=0:(p=p.__iter__(),n="undefined"!=typeof(m=p.__array)?0:"function"==typeof p.$genfunc?1:-1);for(v=0;"undefined"!=typeof(l=n?0<n?p.next(!0,!1):$p.wrapped_next(p):m[v++]);)for(q=l,k=0,C=q*c+3,g=h.range(0,c,4),"undefined"!=typeof(w=g.__array)?l=0:(g=g.__iter__(),l="undefined"!=
typeof(w=g.__array)?0:"function"==typeof g.$genfunc?1:-1),e=0;"undefined"!=typeof(x=l?0<l?g.next(!0,!1):$p.wrapped_next(g):w[e++]);)(null===(f=1==((B=d._getPixel(b,C+x))===(t=a)?0:typeof B!=typeof t||"number"!=typeof B&&"string"!=typeof B&&"boolean"!=typeof B?$p.cmp(B,t):B==t?0:B<t?-1:1))||!1===f||0===f||""===f?0:"object"==typeof f?"function"==typeof f.__nonzero__?f.__nonzero__():"function"==typeof f.__len__?0<f.__len__():1:1)&&s.set_at($p.tuple([k,q])),k+=1;return s};h.from_surface.__name__="from_surface";
h.from_surface.__bind_type__=0;h.from_surface.__args__=[null,null,["surface"],["threshold",127]];h.from_threshold=function(d,a,l){"undefined"==typeof l&&(l=arguments.callee.__args__[4][1]);var g,c,m,k,b,e,f,t,x,n,B,p,s,C,v,q,w,Xa,Ya,r,y,D,z,G,A,H,I,J,fa,Za,Ia,$a,Ma,P,ab,K,ia,Q,E,ja,Na,Ja,Ka,R,bb,ga,S,ka,la,ma,na,Oa,oa,Pa,pa,Qa,qa,Ra,ra,Sa,sa,T,Ta,F,ta,U,ua,cb,va,db,wa,Ua,xa,Va,ya,za,V,W,L,M,X,N,Y,O,Z,Aa,$,Ba,aa,La,ba,Ca,ca,da,ea,Da,u,Ea,Wa,Fa,Ga,Ha,eb,ha;Fa=("undefined"==typeof Mask?h.Mask:Mask)($p.tuple([d.width,
d.height]));if(null===(z=!(null===(H=Fa.bit)||!1===H||0===H||""===H?0:"object"==typeof H?"function"==typeof H.__nonzero__?H.__nonzero__():"function"==typeof H.__len__?0<H.__len__():1:1))||!1===z||0===z||""===z?0:"object"==typeof z?"function"==typeof z.__nonzero__?z.__nonzero__():"function"==typeof z.__len__?0<z.__len__():1:1)return null;K=d.impl.getImageData(0,0,d.width,d.height);if(null===(G=(M=l)===(W=$p.tuple([0,0,0,255]))&&null===M?!0:null===M?!1:null===W?!1:"object"!=typeof M&&"function"!=typeof M||
"function"!=typeof M.__cmp__?"object"!=typeof W&&"function"!=typeof W||"function"!=typeof W.__cmp__?M==W:0===W.__cmp__(M):0===M.__cmp__(W))||!1===G||0===G||""===G?0:"object"==typeof G?"function"==typeof G.__nonzero__?G.__nonzero__():"function"==typeof G.__len__?0<G.__len__():1:1){a=h.Color(a);a=$p.tuple([a.r,a.g,a.b]);var fb=$p.__ass_unpack($p.tuple([4*d.width,d.height]),2,null);ga=fb[0];Ja=fb[1];p=h.range(0,Ja);"undefined"!=typeof(Na=p.__array)?La=0:(p=p.__iter__(),La="undefined"!=typeof(Na=p.__array)?
0:"function"==typeof p.$genfunc?1:-1);for(db=0;"undefined"!=typeof(bb=La?0<La?p.next(!0,!1):$p.wrapped_next(p):Na[db++]);)for(ha=bb,ca=0,u=ha*ga,R=h.range(0,ga,4),"undefined"!=typeof(Ta=R.__array)?x=0:(R=R.__iter__(),x="undefined"!=typeof(Ta=R.__array)?0:"function"==typeof R.$genfunc?1:-1),eb=0;"undefined"!=typeof(Za=x?0<x?R.next(!0,!1):$p.wrapped_next(R):Ta[eb++]);)Ia=Za,F=u+Ia,(null===(c=(null===(I=q=(L=d._getPixel(K,F))===(Y="undefined"!=typeof(na=a).__array?"undefined"!=typeof na.__array[0]?na.__array[0]:
na.__getitem__(0):na.__getitem__(0))&&null===L?!0:null===L?!1:null===Y?!1:"object"!=typeof L&&"function"!=typeof L||"function"!=typeof L.__cmp__?"object"!=typeof Y&&"function"!=typeof Y||"function"!=typeof Y.__cmp__?L==Y:0===Y.__cmp__(L):0===L.__cmp__(Y))||!1===I||0===I||""===I?0:"object"==typeof I?"function"==typeof I.__nonzero__?I.__nonzero__():"function"==typeof I.__len__?0<I.__len__():1:1)?(null===(J=w=(O=d._getPixel(K,F+1))===(X="undefined"!=typeof(ma=a).__array?"undefined"!=typeof ma.__array[1]?
ma.__array[1]:ma.__getitem__(1):ma.__getitem__(1))&&null===O?!0:null===O?!1:null===X?!1:"object"!=typeof O&&"function"!=typeof O||"function"!=typeof O.__cmp__?"object"!=typeof X&&"function"!=typeof X||"function"!=typeof X.__cmp__?O==X:0===X.__cmp__(O):0===O.__cmp__(X))||!1===J||0===J||""===J?0:"object"==typeof J?"function"==typeof J.__nonzero__?J.__nonzero__():"function"==typeof J.__len__?0<J.__len__():1:1)?(null===(g=Xa=(N=d._getPixel(K,F+2))===(V="undefined"!=typeof(la=a).__array?"undefined"!=typeof la.__array[2]?
la.__array[2]:la.__getitem__(2):la.__getitem__(2))&&null===N?!0:null===N?!1:null===V?!1:"object"!=typeof N&&"function"!=typeof N||"function"!=typeof N.__cmp__?"object"!=typeof V&&"function"!=typeof V||"function"!=typeof V.__cmp__?N==V:0===V.__cmp__(N):0===N.__cmp__(V))||!1===g||0===g||""===g?0:"object"==typeof g?"function"==typeof g.__nonzero__?g.__nonzero__():"function"==typeof g.__len__?0<g.__len__():1:1)?1==(((da=d._getPixel(K,F+3))===(Da="undefined"!=typeof(ka=l).__array?"undefined"!=typeof ka.__array[3]?
ka.__array[3]:ka.__getitem__(3):ka.__getitem__(3))?0:typeof da!=typeof Da||"number"!=typeof da&&"string"!=typeof da&&"boolean"!=typeof da?$p.cmp(da,Da):da==Da?0:da<Da?-1:1)|1):Xa:w:q)||!1===c||0===c||""===c?0:"object"==typeof c?"function"==typeof c.__nonzero__?c.__nonzero__():"function"==typeof c.__len__?0<c.__len__():1:1)&&Fa.set_at($p.tuple([ca,ha])),ca+=1}else{a=h.Color(a);E=$p.dict([]);T=$p.enumerate($p.tuple(["r","g","b"]));"undefined"!=typeof(Ma=T.__array)?Ka=0:(T=T.__iter__(),Ka="undefined"!=
typeof(Ma=T.__array)?0:"function"==typeof T.$genfunc?1:-1);for(s=0;"undefined"!=typeof($a=Ka?0<Ka?T.next(!0,!1):$p.wrapped_next(T):Ma[s++]);){var gb=$p.__ass_unpack($a,2,null);u=gb[0];ia=gb[1];(null===(m="undefined"!=typeof(k=l).__array?"undefined"!=typeof k.__array[Qa=u]?k.__array[Qa]:k.__getitem__(Qa):k.__getitem__(u))||!1===m||0===m||""===m?0:"object"==typeof m?"function"==typeof m.__nonzero__?m.__nonzero__():"function"==typeof m.__len__?0<m.__len__():1:1)?(E.__setitem__(ia+"1",("undefined"!=typeof(qa=
a).__array?"undefined"!=typeof qa.__array[Ra=u]?qa.__array[Ra]:qa.__getitem__(Ra):qa.__getitem__(u))-("undefined"!=typeof(ra=l).__array?"undefined"!=typeof ra.__array[Oa=u]?ra.__array[Oa]:ra.__getitem__(Oa):ra.__getitem__(u))-1),E.__setitem__(ia+"2",("undefined"!=typeof(oa=a).__array?"undefined"!=typeof oa.__array[Pa=u]?oa.__array[Pa]:oa.__getitem__(Pa):oa.__getitem__(u))+("undefined"!=typeof(pa=l).__array?"undefined"!=typeof pa.__array[Sa=u]?pa.__array[Sa]:pa.__getitem__(Sa):pa.__getitem__(u))+1)):
(E.__setitem__(ia+"1",("undefined"!=typeof(sa=a).__array?"undefined"!=typeof sa.__array[Ua=u]?sa.__array[Ua]:sa.__getitem__(Ua):sa.__getitem__(u))-1),E.__setitem__(ia+"2",("undefined"!=typeof(wa=a).__array?"undefined"!=typeof wa.__array[Va=u]?wa.__array[Va]:wa.__getitem__(Va):wa.__getitem__(u))+1))}E.__setitem__("a",("undefined"!=typeof(xa=l).__array?"undefined"!=typeof xa.__array[3]?xa.__array[3]:xa.__getitem__(3):xa.__getitem__(3))-1);var hb=$p.__ass_unpack($p.tuple([4*d.width,d.height]),2,null);
ga=hb[0];Ja=hb[1];P=h.range(0,Ja);"undefined"!=typeof(D=P.__array)?B=0:(P=P.__iter__(),B="undefined"!=typeof(D=P.__array)?0:"function"==typeof P.$genfunc?1:-1);for(ab=0;"undefined"!=typeof(cb=B?0<B?P.next(!0,!1):$p.wrapped_next(P):D[ab++]);)for(ha=cb,ca=0,u=ha*ga,S=h.range(0,ga,4),"undefined"!=typeof(Wa=S.__array)?C=0:(S=S.__iter__(),C="undefined"!=typeof(Wa=S.__array)?0:"function"==typeof S.$genfunc?1:-1),A=0;"undefined"!=typeof(fa=C?0<C?S.next(!0,!1):$p.wrapped_next(S):Wa[A++]);)Ia=fa,F=u+Ia,(null===
(f=(null===(v=Ya=-1==((ea="undefined"!=typeof(ya=E).__array?"undefined"!=typeof ya.__array.r1?ya.__array.r1:ya.__getitem__("r1"):ya.__getitem__("r1"))===(Ga=$compare1=d._getPixel(K,F))?0:typeof ea!=typeof Ga||"number"!=typeof ea&&"string"!=typeof ea&&"boolean"!=typeof ea?$p.cmp(ea,Ga):ea==Ga?0:ea<Ga?-1:1)&&-1==((U=$compare1)===(ja=$compare2="undefined"!=typeof(za=E).__array?"undefined"!=typeof za.__array.r2?za.__array.r2:za.__getitem__("r2"):za.__getitem__("r2"))?0:typeof U!=typeof ja||"number"!=
typeof U&&"string"!=typeof U&&"boolean"!=typeof U?$p.cmp(U,ja):U==ja?0:U<ja?-1:1))||!1===v||0===v||""===v?0:"object"==typeof v?"function"==typeof v.__nonzero__?v.__nonzero__():"function"==typeof v.__len__?0<v.__len__():1:1)?(null===(b=r=-1==((Q="undefined"!=typeof(va=E).__array?"undefined"!=typeof va.__array.g1?va.__array.g1:va.__getitem__("g1"):va.__getitem__("g1"))===(n=$compare3=d._getPixel(K,F+1))?0:typeof Q!=typeof n||"number"!=typeof Q&&"string"!=typeof Q&&"boolean"!=typeof Q?$p.cmp(Q,n):Q==
n?0:Q<n?-1:1)&&-1==((aa=$compare3)===(Aa=$compare4="undefined"!=typeof(Ha=E).__array?"undefined"!=typeof Ha.__array.g2?Ha.__array.g2:Ha.__getitem__("g2"):Ha.__getitem__("g2"))?0:typeof aa!=typeof Aa||"number"!=typeof aa&&"string"!=typeof aa&&"boolean"!=typeof aa?$p.cmp(aa,Aa):aa==Aa?0:aa<Aa?-1:1))||!1===b||0===b||""===b?0:"object"==typeof b?"function"==typeof b.__nonzero__?b.__nonzero__():"function"==typeof b.__len__?0<b.__len__():1:1)?(null===(e=y=-1==((Z="undefined"!=typeof(ua=E).__array?"undefined"!=
typeof ua.__array.b1?ua.__array.b1:ua.__getitem__("b1"):ua.__getitem__("b1"))===(Ba=$compare5=d._getPixel(K,F+2))?0:typeof Z!=typeof Ba||"number"!=typeof Z&&"string"!=typeof Z&&"boolean"!=typeof Z?$p.cmp(Z,Ba):Z==Ba?0:Z<Ba?-1:1)&&-1==(($=$compare5)===(Ca=$compare6="undefined"!=typeof(ta=E).__array?"undefined"!=typeof ta.__array.b2?ta.__array.b2:ta.__getitem__("b2"):ta.__getitem__("b2"))?0:typeof $!=typeof Ca||"number"!=typeof $&&"string"!=typeof $&&"boolean"!=typeof $?$p.cmp($,Ca):$==Ca?0:$<Ca?-1:
1))||!1===e||0===e||""===e?0:"object"==typeof e?"function"==typeof e.__nonzero__?e.__nonzero__():"function"==typeof e.__len__?0<e.__len__():1:1)?1==((ba=d._getPixel(K,F+3))===(t="undefined"!=typeof(Ea=E).__array?"undefined"!=typeof Ea.__array.a?Ea.__array.a:Ea.__getitem__("a"):Ea.__getitem__("a"))?0:typeof ba!=typeof t||"number"!=typeof ba&&"string"!=typeof ba&&"boolean"!=typeof ba?$p.cmp(ba,t):ba==t?0:ba<t?-1:1):y:r:Ya)||!1===f||0===f||""===f?0:"object"==typeof f?"function"==typeof f.__nonzero__?
f.__nonzero__():"function"==typeof f.__len__?0<f.__len__():1:1)&&Fa.set_at($p.tuple([ca,ha])),ca+=1}return Fa};h.from_threshold.__name__="from_threshold";h.from_threshold.__bind_type__=0;h.from_threshold.__args__=[null,null,["surface"],["color"],["threshold",$p.tuple([0,0,0,255])]];h.Mask=function(){var d={},a;d.__module__="pyjsdl.mask";a=$pyjs__bind_method2("__init__",function(c,m){if(!0===this.__is_instance__)var k=this;else k=c,c=m;var b,e,f,a;k.width=$p.float_int("undefined"!=typeof(b=c).__array?
"undefined"!=typeof b.__array[0]?b.__array[0]:b.__getitem__(0):b.__getitem__(0));k.height=$p.float_int("undefined"!=typeof(e=c).__array?"undefined"!=typeof e.__array[1]?e.__array[1]:e.__getitem__(1):e.__getitem__(1));k.bit=$p.list([]);f=h.range(k.height);"undefined"!=typeof(e=f.__array)?a=0:(f=f.__iter__(),a="undefined"!=typeof(e=f.__array)?0:"function"==typeof f.$genfunc?1:-1);for(b=0;"undefined"!=typeof(a?0<a?f.next(!0,!1):$p.wrapped_next(f):e[b++]);)k.bit.append(h.BitSet(k.width));return null},
1,[null,null,["self"],["size"]]);d.__init__=a;a=$pyjs__bind_method2("__str__",function(c){return(!0===this.__is_instance__?this:c).toString()},1,[null,null,["self"]]);d.__str__=a;a=$pyjs__bind_method2("__repr__",function(c){c=!0===this.__is_instance__?this:c;return $p.sprintf("%s(%r)",$p.tuple([c.__class__,c.__dict__]))},1,[null,null,["self"]]);d.__repr__=a;a=$pyjs__bind_method2("get_size",function(c){c=!0===this.__is_instance__?this:c;return $p.tuple([c.width,c.height])},1,[null,null,["self"]]);
d.get_size=a;a=$pyjs__bind_method2("get_at",function(c,m){if(!0===this.__is_instance__)var k=this;else k=c,c=m;var b,e,f,a,d;return("undefined"!=typeof(a=k.bit).__array?"undefined"!=typeof a.__array[e="undefined"!=typeof(b=c).__array?"undefined"!=typeof b.__array[d=1]?b.__array[d]:b.__getitem__(d):b.__getitem__(1)]?a.__array[e]:a.__getitem__(e):a.__getitem__("undefined"!=typeof(b=c).__array?"undefined"!=typeof b.__array[d=1]?b.__array[d]:b.__getitem__(d):b.__getitem__(1))).get("undefined"!=typeof(f=
c).__array?"undefined"!=typeof f.__array[0]?f.__array[0]:f.__getitem__(0):f.__getitem__(0))},1,[null,null,["self"],["pos"]]);d.get_at=a;a=$pyjs__bind_method2("set_at",function(c,m){if(!0===this.__is_instance__)var a=this;else a=arguments[0],c=arguments[1],m=arguments[2];"undefined"==typeof m&&(m=arguments.callee.__args__[4][1]);var b,e,f,d,h;("undefined"!=typeof(f=a.bit).__array?"undefined"!=typeof f.__array[d="undefined"!=typeof(b=c).__array?"undefined"!=typeof b.__array[e=1]?b.__array[e]:b.__getitem__(e):
b.__getitem__(1)]?f.__array[d]:f.__getitem__(d):f.__getitem__("undefined"!=typeof(b=c).__array?"undefined"!=typeof b.__array[e=1]?b.__array[e]:b.__getitem__(e):b.__getitem__(1))).set("undefined"!=typeof(h=c).__array?"undefined"!=typeof h.__array[0]?h.__array[0]:h.__getitem__(0):h.__getitem__(0),m);return null},1,[null,null,["self"],["pos"],["value",1]]);d.set_at=a;a=$pyjs__bind_method2("fill",function(c){var m,a,b,e;c=(!0===this.__is_instance__?this:c).bit;"undefined"!=typeof(e=c.__array)?b=0:(c=
c.__iter__(),b="undefined"!=typeof(e=c.__array)?0:"function"==typeof c.$genfunc?1:-1);for(a=0;"undefined"!=typeof(m=b?0<b?c.next(!0,!1):$p.wrapped_next(c):e[a++]);)m.fill();return null},1,[null,null,["self"]]);d.fill=a;a=$pyjs__bind_method2("clear",function(c){var m,a,b,e;b=(!0===this.__is_instance__?this:c).bit;"undefined"!=typeof(c=b.__array)?a=0:(b=b.__iter__(),a="undefined"!=typeof(c=b.__array)?0:"function"==typeof b.$genfunc?1:-1);for(e=0;"undefined"!=typeof(m=a?0<a?b.next(!0,!1):$p.wrapped_next(b):
c[e++]);)m.clear();return null},1,[null,null,["self"]]);d.clear=a;a=$pyjs__bind_method2("invert",function(c){c=!0===this.__is_instance__?this:c;var a,d,b,e,f;a=c.bit;"undefined"!=typeof(e=a.__array)?d=0:(a=a.__iter__(),d="undefined"!=typeof(e=a.__array)?0:"function"==typeof a.$genfunc?1:-1);for(f=0;"undefined"!=typeof(b=d?0<d?a.next(!0,!1):$p.wrapped_next(a):e[f++]);)b.flip(0,c.width);return null},1,[null,null,["self"]]);d.invert=a;a=$pyjs__bind_method2("count",function(c){var a=!0===this.__is_instance__?
this:c,d,b,e,f;c=0;e=a.bit;"undefined"!=typeof(d=e.__array)?a=0:(e=e.__iter__(),a="undefined"!=typeof(d=e.__array)?0:"function"==typeof e.$genfunc?1:-1);for(f=0;"undefined"!=typeof(b=a?0<a?e.next(!0,!1):$p.wrapped_next(e):d[f++]);)c+=b.cardinality();return c},1,[null,null,["self"]]);d.count=a;a=$pyjs__bind_method2("overlap",function(c,a,d){if(!0===this.__is_instance__)var b=this;else b=c,c=a,a=d;var e,f,t,x,n,g,p,s,C,v,q,w,l,r,y,A,D,z;(null===(t=1==(0===(x="undefined"!=typeof(z=a).__array?"undefined"!=
typeof z.__array[0]?z.__array[0]:z.__getitem__(0):z.__getitem__(0))?0:"number"!=typeof x||"number"!=typeof x&&"string"!=typeof x&&"boolean"!=typeof x?$p.cmp(x,0):0==x?0:0>x?-1:1))||!1===t||0===t||""===t?0:"object"==typeof t?"function"==typeof t.__nonzero__?t.__nonzero__():"function"==typeof t.__len__?0<t.__len__():1:1)?(d="undefined"!=typeof(l=a).__array?"undefined"!=typeof l.__array[0]?l.__array[0]:l.__getitem__(0):l.__getitem__(0),l=0):(d=0,l=-("undefined"!=typeof(A=a).__array?"undefined"!=typeof A.__array[0]?
A.__array[0]:A.__getitem__(0):A.__getitem__(0)));(null===(e=1==(0===(n="undefined"!=typeof(v=a).__array?"undefined"!=typeof v.__array[1]?v.__array[1]:v.__getitem__(1):v.__getitem__(1))?0:"number"!=typeof n||"number"!=typeof n&&"string"!=typeof n&&"boolean"!=typeof n?$p.cmp(n,0):0==n?0:0>n?-1:1))||!1===e||0===e||""===e?0:"object"==typeof e?"function"==typeof e.__nonzero__?e.__nonzero__():"function"==typeof e.__len__?0<e.__len__():1:1)?(e="undefined"!=typeof(q=a).__array?"undefined"!=typeof q.__array[1]?
q.__array[1]:q.__getitem__(1):q.__getitem__(1),a=0):(e=0,a=-("undefined"!=typeof(s=a).__array?"undefined"!=typeof s.__array[1]?s.__array[1]:s.__getitem__(1):s.__getitem__(1)));s=$p.min(b.width-d,c.width-l);q=$p.min(b.height-e,c.height-a);if(null===(p=(null===(f=w=1==(0===s?0:"number"!=typeof s||"number"!=typeof s&&"string"!=typeof s&&"boolean"!=typeof s?$p.cmp(s,0):0==s?0:0>s?-1:1))||!1===f||0===f||""===f?0:"object"==typeof f?"function"==typeof f.__nonzero__?f.__nonzero__():"function"==typeof f.__len__?
0<f.__len__():1:1)?1==(0===q?0:"number"!=typeof q||"number"!=typeof q&&"string"!=typeof q&&"boolean"!=typeof q?$p.cmp(q,0):0==q?0:0>q?-1:1):w)||!1===p||0===p||""===p?0:"object"==typeof p?"function"==typeof p.__nonzero__?p.__nonzero__():"function"==typeof p.__len__?0<p.__len__():1:1)for(w=h.range(q),"undefined"!=typeof(f=w.__array)?q=0:(w=w.__iter__(),q="undefined"!=typeof(f=w.__array)?0:"function"==typeof w.$genfunc?1:-1),p=0;"undefined"!=typeof(n=q?0<q?w.next(!0,!1):$p.wrapped_next(w):f[p++]);)if(null===
(D=("undefined"!=typeof(C=b.bit).__array?"undefined"!=typeof C.__array[r=e+n]?C.__array[r]:C.__getitem__(r):C.__getitem__(e+n)).get(d,d+s).intersects(("undefined"!=typeof(g=c.bit).__array?"undefined"!=typeof g.__array[y=a+n]?g.__array[y]:g.__getitem__(y):g.__getitem__(a+n)).get(l,l+s)))||!1===D||0===D||""===D?0:"object"==typeof D?"function"==typeof D.__nonzero__?D.__nonzero__():"function"==typeof D.__len__?0<D.__len__():1:1)return!0;return null},1,[null,null,["self"],["mask"],["offset"]]);d.overlap=
a;a=$pyjs__bind_method2("toString",function(a){if(!0===this.__is_instance__)var d=this;else d=arguments[0],a=arguments[1];"undefined"==typeof a&&(a=arguments.callee.__args__[3][1]);var k,b,e,f,l,g,n,r;e=$p.dict([[!0,"undefined"!=typeof(b=a).__array?"undefined"!=typeof b.__array[0]?b.__array[0]:b.__getitem__(0):b.__getitem__(0)],[!1,"undefined"!=typeof(k=a).__array?"undefined"!=typeof k.__array[1]?k.__array[1]:k.__getitem__(1):k.__getitem__(1)]]);f=$p.list([]);g=d.bit;"undefined"!=typeof(k=g.__array)?
b=0:(g=g.__iter__(),b="undefined"!=typeof(k=g.__array)?0:"function"==typeof g.$genfunc?1:-1);for(n=0;"undefined"!=typeof(r=b?0<b?g.next(!0,!1):$p.wrapped_next(g):k[n++]);)l=r,f.append("\n"),f.extend(function(){var a,b,c,f,g,k,n,r;k=$p.list();b=h.range(d.width);"undefined"!=typeof(g=b.__array)?r=0:(b=b.__iter__(),r="undefined"!=typeof(g=b.__array)?0:"function"==typeof b.$genfunc?1:-1);for(n=0;"undefined"!=typeof(f=r?0<r?b.next(!0,!1):$p.wrapped_next(b):g[n++]);)k.append("undefined"!=typeof(c=e).__array?
"undefined"!=typeof c.__array[a=l.get(f)]?c.__array[a]:c.__getitem__(a):c.__getitem__(l.get(f)));return k}());return"".join(f)},1,[null,null,["self"],["bit",$p.tuple(["1","0"])]]);d.toString=a;a=Array($p.object);var l=$p.dict(),g;for(g in d)l.__setitem__(g,d[g]);return $p._create_class("Mask",$p.tuple(a),l)}();return this};
