$pyjs.loaded_modules["pyjsdl.util"]=function(s){if($pyjs.loaded_modules["pyjsdl.util"].__was_initialized__)return $pyjs.loaded_modules["pyjsdl.util"];"undefined"!=typeof $pyjs.loaded_modules.pyjsdl&&$pyjs.loaded_modules.pyjsdl.__was_initialized__||$p.___import___("pyjsdl",null);var d=$pyjs.loaded_modules["pyjsdl.util"];d.__repr__=function(){return"<module: pyjsdl.util>"};d.__was_initialized__=!0;if(null===s||"undefined"==typeof s)s="pyjsdl.util";d.__name__=s;$pyjs.loaded_modules.pyjsdl.util=$pyjs.loaded_modules["pyjsdl.util"];
d.Time=$p.___import___("pyjsdl.time.Time","pyjsdl",null,!1);d.Rect=$p.___import___("pyjsdl.rect.Rect","pyjsdl",null,!1);d.env=$p.___import___("pyjsdl.env","pyjsdl",null,!1);d.Timer=function(){var b={},a;b.__module__="pyjsdl.util";a=$pyjs__bind_method2("__init__",function(h,l){if(!0===this.__is_instance__)var c=this;else c=arguments[0],h=arguments[1],l=arguments[2];"undefined"==typeof h&&(h=arguments.callee.__args__[3][1]);"undefined"==typeof l&&(l=arguments.callee.__args__[4][1]);c.time=d.Time();
c.time_i=c.get_time();c.dtime=$p.list([]);c.number=0;c.log=null;c.log_list=null;c.log_num=0;c.log_scroll=!0;c.set_log(h,l);return null},1,[null,null,["self"],["log","console"],["log_length",5]]);b.__init__=a;a=$pyjs__bind_method2("get_time",function(h){return(!0===this.__is_instance__?this:h).time.time()},1,[null,null,["self"]]);b.get_time=a;a=$pyjs__bind_method2("set_time",function(h){h=!0===this.__is_instance__?this:h;h.time_i=h.get_time();return null},1,[null,null,["self"]]);b.set_time=a;a=$pyjs__bind_method2("lap_time",
function(h,l,c,e){if(!0===this.__is_instance__)var a=this;else a=arguments[0],h=arguments[1],l=arguments[2],c=arguments[3],e=arguments[4];"undefined"==typeof h&&(h=arguments.callee.__args__[3][1]);"undefined"==typeof l&&(l=arguments.callee.__args__[4][1]);"undefined"==typeof c&&(c=arguments.callee.__args__[5][1]);"undefined"==typeof e&&(e=arguments.callee.__args__[6][1]);var f,b,d,k,p,q,r,g;if(null===(k=null===h)||!1===k||0===k||""===k?0:"object"==typeof k?"function"==typeof k.__nonzero__?k.__nonzero__():
"function"==typeof k.__len__?0<k.__len__():1:1)h=a.time_i;if(null===(f=null===l)||!1===f||0===f||""===f?0:"object"==typeof f?"function"==typeof f.__nonzero__?f.__nonzero__():"function"==typeof f.__len__?0<f.__len__():1:1)l=a.get_time();a.dtime.append(l-h);a.number+=1;if(null===(d=1==(((r=a.number)===(g=c)?0:typeof r!=typeof g||"number"!=typeof r&&"string"!=typeof r&&"boolean"!=typeof r?$p.cmp(r,g):r==g?0:r<g?-1:1)|1))||!1===d||0===d||""===d?0:"object"==typeof d?"function"==typeof d.__nonzero__?d.__nonzero__():
"function"==typeof d.__len__?0<d.__len__():1:1){f=$p.sum(a.dtime)/c;a.dtime=$p.list([]);a.number=0;if(null===(p=e)||!1===p||0===p||""===p?0:"object"==typeof p?"function"==typeof p.__nonzero__?p.__nonzero__():"function"==typeof p.__len__?0<p.__len__():1:1)(null===(q="console"===(b=a.log_type)&&null===b?!0:null===b?!1:"object"!=typeof b&&"function"!=typeof b||"function"!=typeof b.__cmp__?"console"==b:0===b.__cmp__("console"))||!1===q||0===q||""===q?0:"object"==typeof q?"function"==typeof q.__nonzero__?
q.__nonzero__():"function"==typeof q.__len__?0<q.__len__():1:1)?(a.log_num+=1,$p.sprintf("Time %d: %s",$p.tuple([a.log_num,f]))):(a.log_num+=1,b=$p.sprintf("Time %d: %s",$p.tuple([a.log_num,f])),a.print_log(b));return f}return null},1,[null,null,["self"],["time_i",null],["time_f",null],["number",100],["print_result",!0]]);b.lap_time=a;a=$pyjs__bind_method2("set_log",function(a,l){if(!0===this.__is_instance__)var c=this;else c=arguments[0],a=arguments[1],l=arguments[2];"undefined"==typeof l&&(l=arguments.callee.__args__[4][1]);
var e,b,f,n,g,k;if(null===(f=$p.tuple(["console","textarea"]).__contains__(a))||!1===f||0===f||""===f?0:"object"==typeof f?"function"==typeof f.__nonzero__?f.__nonzero__():"function"==typeof f.__len__?0<f.__len__():1:1)if(c.log_type=a,null===(n="textarea"===(e=a)&&null===e?!0:null===e?!1:"object"!=typeof e&&"function"!=typeof e||"function"!=typeof e.__cmp__?"textarea"==e:0===e.__cmp__("textarea"))||!1===n||0===n||""===n?0:"object"==typeof n?"function"==typeof n.__nonzero__?n.__nonzero__():"function"==
typeof n.__len__?0<n.__len__():1:1){if(null===(k=!(null===(g=c.log)||!1===g||0===g||""===g?0:"object"==typeof g?"function"==typeof g.__nonzero__?g.__nonzero__():"function"==typeof g.__len__?0<g.__len__():1:1))||!1===k||0===k||""===k?0:"object"==typeof k?"function"==typeof k.__nonzero__?k.__nonzero__():"function"==typeof k.__len__?0<k.__len__():1:1)e=$p.tuple([d.env.canvas.surface.width-5,102]),c.log=d.env.canvas.surface._display.Textarea(e),c.log.setReadonly(!0),c.log.addMouseListener(c),e=function(c,
a,h){return null},e.__name__="$lambda1",e.__bind_type__=0,e.__args__=[null,null,["sender"],["x"],["y"]],c.onMouseUp=e,e=function(c,a,h){return null},e.__name__="$lambda2",e.__bind_type__=0,e.__args__=[null,null,["sender"],["x"],["y"]],c.onMouseMove=e,e=function(c){return null},e.__name__="$lambda3",e.__bind_type__=0,e.__args__=[null,null,["sender"]],c.onMouseEnter=e,c.log_list=function(){var c,a,h,b,e;a=$p.list();h=$p.range(l);"undefined"!=typeof(e=h.__array)?c=0:(h=h.__iter__(),c="undefined"!=typeof(e=
h.__array)?0:"function"==typeof h.$genfunc?1:-1);for(b=0;"undefined"!=typeof(c?0<c?h.next(!0,!1):$p.wrapped_next(h):e[b++]);)a.append("");return a}();c.log.toggle(!0)}else if(null===(b=c.log)||!1===b||0===b||""===b?0:"object"==typeof b?"function"==typeof b.__nonzero__?b.__nonzero__():"function"==typeof b.__len__?0<b.__len__():1:1)c.log.toggle(!1),c.log_list=$p.list([]);return null},1,[null,null,["self"],["log"],["log_length",5]]);b.set_log=a;a=$pyjs__bind_method2("onMouseDown",function(a,b,c,e){(!0===
this.__is_instance__?this:a).log_scroll=!1;return null},1,[null,null,["self"],["sender"],["x"],["y"]]);b.onMouseDown=a;a=$pyjs__bind_method2("onMouseLeave",function(a,b){(!0===this.__is_instance__?this:a).log_scroll=!0;return null},1,[null,null,["self"],["sender"]]);b.onMouseLeave=a;a=$pyjs__bind_method2("print_log",function(a,b){if(!0===this.__is_instance__)var c=this;else c=a,a=b;var e,d,f,g;(null===(f="console"===(d=c.log_type)&&null===d?!0:null===d?!1:"object"!=typeof d&&"function"!=typeof d||
"function"!=typeof d.__cmp__?"console"==d:0===d.__cmp__("console"))||!1===f||0===f||""===f?0:"object"==typeof f?"function"==typeof f.__nonzero__?f.__nonzero__():"function"==typeof f.__len__?0<f.__len__():1:1)||(c.log_list.pop(0),c.log_list.append(a+"\n"),a="".join(c.log_list),c.log.setText(a),(null===(g=c.log_scroll)||!1===g||0===g||""===g?0:"object"==typeof g?"function"==typeof g.__nonzero__?g.__nonzero__():"function"==typeof g.__len__?0<g.__len__():1:1)&&c.log.setCursorPos(null===(e=a)?0:"undefined"!=
typeof e.__array?e.__array.length:"function"==typeof e.__len__?e.__len__():"undefined"!=typeof e.length?e.length:$p.len(e)));return null},1,[null,null,["self"],["text"]]);b.print_log=a;a=Array($p.object);var g=$p.dict(),m;for(m in b)g.__setitem__(m,b[m]);return $p._create_class("Timer",$p.tuple(a),g)}();d.PyjsMode=function(){var b={},a;b.__module__="pyjsdl.util";a=$pyjs__bind_method2("__init__",function(a){a=!0===this.__is_instance__?this:a;a.getattr_call=a.test_getattr();a.eq_call=a.test_eq();var b=
$p.__ass_unpack(a.test_mode(),2,null);a.strict=b[0];a.optimized=b[1];return null},1,[null,null,["self"]]);b.__init__=a;a=$pyjs__bind_method2("test_mode",function(a){a=!0===this.__is_instance__?this:a;var b,c,e;return(null===(e=(null===(c=b=a.getattr_call)||!1===c||0===c||""===c?0:"object"==typeof c?"function"==typeof c.__nonzero__?c.__nonzero__():"function"==typeof c.__len__?0<c.__len__():1:1)?a.eq_call:b)||!1===e||0===e||""===e?0:"object"==typeof e?"function"==typeof e.__nonzero__?e.__nonzero__():
"function"==typeof e.__len__?0<e.__len__():1:1)?$p.tuple([!0,!1]):$p.tuple([!1,!0])},1,[null,null,["self"]]);b.test_mode=a;a=$pyjs__bind_method2("test_getattr",function(a){var b,c;return(c=d.Rect(0,0,20,20).center)===(b=$p.tuple([10,10]))&&null===c?!0:null===c?!1:null===b?!1:"object"!=typeof c&&"function"!=typeof c||"function"!=typeof c.__cmp__?"object"!=typeof b&&"function"!=typeof b||"function"!=typeof b.__cmp__?c==b:0===b.__cmp__(c):0===c.__cmp__(b)},1,[null,null,["self"]]);b.test_getattr=a;a=
$pyjs__bind_method2("test_eq",function(a){var b,c;return(c=d.Rect(0,0,20,20))===(b=d.Rect(0,0,20,20))&&null===c?!0:null===c?!1:null===b?!1:"object"!=typeof c&&"function"!=typeof c||"function"!=typeof c.__cmp__?"object"!=typeof b&&"function"!=typeof b||"function"!=typeof b.__cmp__?c==b:0===b.__cmp__(c):0===c.__cmp__(b)},1,[null,null,["self"]]);b.test_eq=a;a=Array(pyjslib.object);var g=$p.dict(),m;for(m in b)g.__setitem__(m,b[m]);return $p._create_class("PyjsMode",$p.tuple(a),g)}();d.env.set_env("pyjs_mode",
d.PyjsMode());d.$$call=function(b,a,d){"undefined"==typeof d&&(d=arguments.callee.__args__[4][1]);return a.apply(b,d.getArray())};d.$$call.__name__="call";d.$$call.__bind_type__=0;d.$$call.__args__=[null,null,["obj"],["func"],["args",$p.tuple([])]];d._dict=function(){var b={},a;b.__module__="pyjsdl.util";a=$pyjs__bind_method2("values",function(a){return $p.dict.values(!0===this.__is_instance__?this:a).__iter__()},1,[null,null,["self"]]);b.values=a;a=$pyjs__bind_method2("keys",function(a){return $p.dict.__iter__(!0===
this.__is_instance__?this:a)},1,[null,null,["self"]]);b.keys=a;a=$pyjs__bind_method2("items",function(a){return $p.dict.items(!0===this.__is_instance__?this:a).__iter__()},1,[null,null,["self"]]);b.items=a;a=Array($p.dict);var d=$p.dict(),m;for(m in b)d.__setitem__(m,b[m]);return $p._create_class("_dict",$p.tuple(a),d)}();d._next=function(b){return b.next()};d._next.__name__="_next";d._next.__bind_type__=0;d._next.__args__=[null,null,["obj"]];try{d._range=$p.xrange}catch(t){if(s="undefined"==typeof t.__name__?
t.name:t.__name__,$pyjs.__last_exception__={error:t,module:d},s==$p.NameError.__name__||$p._isinstance(t,$p.NameError))d._range=$p.range;else throw $pyjs.__active_exception_stack__=$pyjs.__last_exception_stack__,$pyjs.__last_exception_stack__=null,t;}return this};
