$pyjs.loaded_modules["pyjsdl.time"]=function(q){if($pyjs.loaded_modules["pyjsdl.time"].__was_initialized__)return $pyjs.loaded_modules["pyjsdl.time"];"undefined"!=typeof $pyjs.loaded_modules.pyjsdl&&$pyjs.loaded_modules.pyjsdl.__was_initialized__||$p.___import___("pyjsdl",null);var f=$pyjs.loaded_modules["pyjsdl.time"];f.__repr__=function(){return"<module: pyjsdl.time>"};f.__was_initialized__=!0;if(null===q||"undefined"==typeof q)q="pyjsdl.time";f.__name__=q;$pyjs.loaded_modules.pyjsdl.time=$pyjs.loaded_modules["pyjsdl.time"];
f.env=$p.___import___("pyjsdl.env","pyjsdl",null,!1);f.performanceNowInit=$p.___import___("pyjsdl.pyjsobj.performanceNowInit","pyjsdl",null,!1);f.__docformat__="restructuredtext";f.Clock=function(){var a={},c;a.__module__="pyjsdl.time";a._wnd=null;c=$pyjs__bind_method2("__init__",function(b){b=!0===this.__is_instance__?this:b;b._time=b.time();b._time_init=b._time;b._time_diff=0;b._framerate=0;return null},1,[null,null,["self"]]);a.__init__=c;c=$pyjs__bind_method2("get_time",function(b){return(!0===
this.__is_instance__?this:b)._time_diff},1,[null,null,["self"]]);a.get_time=c;c=$pyjs__bind_method2("tick",function(b){if(!0===this.__is_instance__)var g=this;else g=arguments[0],b=arguments[1];"undefined"==typeof b&&(b=arguments.callee.__args__[3][1]);var k,c,d,e,h,a,m;if(null===(h=(null===(a=c=!((d=g._framerate)===(k=b)&&null===d||(null===d?0:null===k?0:"object"!=typeof d&&"function"!=typeof d||"function"!=typeof d.__cmp__?"object"!=typeof k&&"function"!=typeof k||"function"!=typeof k.__cmp__?d==
k:0===k.__cmp__(d):0===d.__cmp__(k))))||!1===a||0===a||""===a?0:"object"==typeof a?"function"==typeof a.__nonzero__?a.__nonzero__():"function"==typeof a.__len__?0<a.__len__():1:1)?!(null===(e=f.env.canvas._pause)||!1===e||0===e||""===e?0:"object"==typeof e?"function"==typeof e.__nonzero__?e.__nonzero__():"function"==typeof e.__len__?0<e.__len__():1:1):c)||!1===h||0===h||""===h?0:"object"==typeof h?"function"==typeof h.__nonzero__?h.__nonzero__():"function"==typeof h.__len__?0<h.__len__():1:1)g._framerate=
b,(null===(m=b)||!1===m||0===m||""===m?0:"object"==typeof m?"function"==typeof m.__nonzero__?m.__nonzero__():"function"==typeof m.__len__?0<m.__len__():1:1)?f.env.canvas._framerate=1E3/b:f.env.canvas._framerate=0;g._time=g.time();g._time_diff=g._time-g._time_init;g._time_init=g._time;return g._time_diff},1,[null,null,["self"],["framerate",0]]);a.tick=c;c=$pyjs__bind_method2("tick_busy_loop",function(b){if(!0===this.__is_instance__)var g=this;else g=arguments[0],b=arguments[1];"undefined"==typeof b&&
(b=arguments.callee.__args__[3][1]);return g.tick(b)},1,[null,null,["self"],["framerate",0]]);a.tick_busy_loop=c;c=$pyjs__bind_method2("get_fps",function(b){var g,k;return(null===(k=!(null===(g=f.env.canvas._pause)||!1===g||0===g||""===g?0:"object"==typeof g?"function"==typeof g.__nonzero__?g.__nonzero__():"function"==typeof g.__len__?0<g.__len__():1:1))||!1===k||0===k||""===k?0:"object"==typeof k?"function"==typeof k.__nonzero__?k.__nonzero__():"function"==typeof k.__len__?0<k.__len__():1:1)?1E3/
f.env.canvas._frametime:0},1,[null,null,["self"]]);a.get_fps=c;c=$pyjs__bind_method2("time",function(b){return(!0===this.__is_instance__?this:b)._wnd.performance.now()},1,[null,null,["self"]]);a.time=c;c=Array($p.object);var p=$p.dict(),l;for(l in a)p.__setitem__(l,a[l]);return $p._create_class("Clock",$p.tuple(c),p)}();f.Time=function(){var a={},c;a.__module__="pyjsdl.time";a._wnd=null;c=$pyjs__bind_method2("__init__",function(b){var g=!0===this.__is_instance__?this:b;g.Clock=f.Clock;f.Time._wnd=
f.performanceNowInit();f.Clock._wnd=f.Time._wnd;g._time_init=g.time();g._framerate=0;g._timers=$p.dict([]);b=function(){return g.wait()};b.__name__="$lambda1";b.__bind_type__=0;b.__args__=[null,null];g.run=b;return null},1,[null,null,["self"]]);a.__init__=c;c=$pyjs__bind_method2("get_ticks",function(b){b=!0===this.__is_instance__?this:b;return b.time()-b._time_init},1,[null,null,["self"]]);a.get_ticks=c;c=$pyjs__bind_method2("delay",function(b,g){if(!0===this.__is_instance__)var k=this;else k=b,b=
g;var c,d,e,a;for(e=k.time();!0!==0&&!0!=="";)if(null===(a=1==((c=k.time()-e)===(d=b)?0:typeof c!=typeof d||"number"!=typeof c&&"string"!=typeof c&&"boolean"!=typeof c?$p.cmp(c,d):c==d?0:c<d?-1:1))||!1===a||0===a||""===a?0:"object"==typeof a?"function"==typeof a.__nonzero__?a.__nonzero__():"function"==typeof a.__len__?0<a.__len__():1:1)return k.time()-e;return null},1,[null,null,["self"],["time"]]);a.delay=c;c=$pyjs__bind_method2("wait",function(b){if(!0===this.__is_instance__)var g=this;else g=arguments[0],
b=arguments[1];"undefined"==typeof b&&(b=arguments.callee.__args__[3][1]);var c,a,d,e;if(null===(d=b)||!1===d||0===d||""===d?0:"object"==typeof d?"function"==typeof d.__nonzero__?d.__nonzero__():"function"==typeof d.__len__?0<d.__len__():1:1){if(null===(a=!(null===(c=f.env.canvas._pause)||!1===c||0===c||""===c?0:"object"==typeof c?"function"==typeof c.__nonzero__?c.__nonzero__():"function"==typeof c.__len__?0<c.__len__():1:1))||!1===a||0===a||""===a?0:"object"==typeof a?"function"==typeof a.__nonzero__?
a.__nonzero__():"function"==typeof a.__len__?0<a.__len__():1:1)g._framerate=f.env.canvas._framerate,f.env.canvas._framerate=10*b,f.env.canvas._pause=!0,g.timeout(b,g)}else if(null===(e=f.env.canvas._pause)||!1===e||0===e||""===e?0:"object"==typeof e?"function"==typeof e.__nonzero__?e.__nonzero__():"function"==typeof e.__len__?0<e.__len__():1:1)f.env.canvas._framerate=g._framerate,f.env.canvas._rendertime=g.time(),f.env.canvas._pause=!1;return b},1,[null,null,["self"],["time",0]]);a.wait=c;c=$pyjs__bind_method2("set_timer",
function(b,g,c){if(!0===this.__is_instance__)var a=this;else a=arguments[0],b=arguments[1],g=arguments[2],c=arguments[3];"undefined"==typeof c&&(c=arguments.callee.__args__[5][1]);var d,e,h,n,m,l;if(null===(d=$p.hasattr(b,"type"))||!1===d||0===d||""===d?0:"object"==typeof d?"function"==typeof d.__nonzero__?d.__nonzero__():"function"==typeof d.__len__?0<d.__len__():1:1)d=b.type,(null===(e=!a._timers.__contains__(d))||!1===e||0===e||""===e?0:"object"==typeof e?"function"==typeof e.__nonzero__?e.__nonzero__():
"function"==typeof e.__len__?0<e.__len__():1:1)&&a._timers.__setitem__(d,("undefined"==typeof _EventTimer?f._EventTimer:_EventTimer)(b));else if(d=b,null===(h=!a._timers.__contains__(d))||!1===h||0===h||""===h?0:"object"==typeof h?"function"==typeof h.__nonzero__?h.__nonzero__():"function"==typeof h.__len__?0<h.__len__():1:1)e=f.env.event.Event(d),a._timers.__setitem__(d,("undefined"==typeof _EventTimer?f._EventTimer:_EventTimer)(e));e=!(null===(n=c)||!1===n||0===n||""===n?0:"object"==typeof n?"function"==
typeof n.__nonzero__?n.__nonzero__():"function"==typeof n.__len__?0<n.__len__():1:1);("undefined"!=typeof(l=a._timers).__array?"undefined"!=typeof l.__array[m=d]?l.__array[m]:l.__getitem__(m):l.__getitem__(d)).set_timer(g,e);return null},1,[null,null,["self"],["event"],["time"],["once",!1]]);a.set_timer=c;c=$pyjs__bind_method2("_stop_timers",function(b){b=!0===this.__is_instance__?this:b;var c,a,f,d,e,h,l;f=b._timers;"undefined"!=typeof(d=f.__array)?a=0:(f=f.__iter__(),a="undefined"!=typeof(d=f.__array)?
0:"function"==typeof f.$genfunc?1:-1);for(l=0;"undefined"!=typeof(c=a?0<a?f.next(!0,!1):$p.wrapped_next(f):d[l++]);)("undefined"!=typeof(h=b._timers).__array?"undefined"!=typeof h.__array[e=c]?h.__array[e]:h.__getitem__(e):h.__getitem__(c)).set_timer(0,!1);return null},1,[null,null,["self"]]);a._stop_timers=c;c=$pyjs__bind_method2("time",function(b){return(!0===this.__is_instance__?this:b)._wnd.performance.now()},1,[null,null,["self"]]);a.time=c;c=$pyjs__bind_method2("timeout",function(b,c){!0!==
this.__is_instance__&&(b=arguments[1],c=arguments[2]);"undefined"==typeof b&&(b=arguments.callee.__args__[3][1]);"undefined"==typeof c&&(c=arguments.callee.__args__[4][1]);var a;a=function(){return c.run()};a.__name__="$lambda2";a.__bind_type__=0;a.__args__=[null,null];$wnd.setTimeout(a,b)},1,[null,null,["self"],["time",null],["obj",null]]);a.timeout=c;c=Array($p.object);var p=$p.dict(),l;for(l in a)p.__setitem__(l,a[l]);return $p._create_class("Time",$p.tuple(c),p)}();f._EventTimer=function(){var a=
{},c;a.__module__="pyjsdl.time";c=$pyjs__bind_method2("__init__",function(b,c){if(!0===this.__is_instance__)var a=this;else a=b,b=c;a.event=b;a.timer=null;a.time=0;a.repeat=!0;return null},1,[null,null,["self"],["event"]]);a.__init__=c;c=$pyjs__bind_method2("set_timer",function(b,a,c){if(!0===this.__is_instance__)var f=this;else f=b,b=a,a=c;var d,e;if(null===(e=f.timer)||!1===e||0===e||""===e?0:"object"==typeof e?"function"==typeof e.__nonzero__?e.__nonzero__():"function"==typeof e.__len__?0<e.__len__():
1:1)f.repeat=!1,f.clear_timeout();if(null===(d=b)||!1===d||0===d||""===d?0:"object"==typeof d?"function"==typeof d.__nonzero__?d.__nonzero__():"function"==typeof d.__len__?0<d.__len__():1:1)f.time=b,f.repeat=a,f.set_timeout();return null},1,[null,null,["self"],["time"],["repeat"]]);a.set_timer=c;c=$pyjs__bind_method2("set_timeout",function(b){var a=!0===this.__is_instance__?this:b;b=function(){return a.run()};b.__name__="$lambda3";b.__bind_type__=0;b.__args__=[null,null];b=$wnd.setTimeout(b,a.time);
a.timer=b;return null},1,[null,null,["self"]]);a.set_timeout=c;c=$pyjs__bind_method2("clear_timeout",function(b){b=!0===this.__is_instance__?this:b;$wnd.clearTimeout(b.timer);return b.timer=null},1,[null,null,["self"]]);a.clear_timeout=c;c=$pyjs__bind_method2("run",function(b){b=!0===this.__is_instance__?this:b;var a;f.env.event.post(b.event);(null===(a=b.repeat)||!1===a||0===a||""===a?0:"object"==typeof a?"function"==typeof a.__nonzero__?a.__nonzero__():"function"==typeof a.__len__?0<a.__len__():
1:1)&&b.set_timeout();return null},1,[null,null,["self"]]);a.run=c;c=Array(pyjslib.object);var p=$p.dict(),l;for(l in a)p.__setitem__(l,a[l]);return $p._create_class("_EventTimer",$p.tuple(c),p)}();return this};
