'use strict';import{AssertionError,AttributeError,BaseException,DeprecationWarning,Exception,IndexError,IterableError,KeyError,NotImplementedError,RuntimeWarning,StopIteration,UserWarning,ValueError,Warning,__JsIterator__,__PyIterator__,__Terminal__,__add__,__and__,__call__,__class__,__envir__,__eq__,__floordiv__,__ge__,__get__,__getcm__,__getitem__,__getslice__,__getsm__,__gt__,__i__,__iadd__,__iand__,__idiv__,__ijsmod__,__ilshift__,__imatmul__,__imod__,__imul__,__in__,__init__,__ior__,__ipow__,
__irshift__,__isub__,__ixor__,__jsUsePyNext__,__jsmod__,__k__,__kwargtrans__,__le__,__lshift__,__lt__,__matmul__,__mergefields__,__mergekwargtrans__,__mod__,__mul__,__ne__,__neg__,__nest__,__or__,__pow__,__pragma__,__pyUseJsNext__,__rshift__,__setitem__,__setproperty__,__setslice__,__sort__,__specialattrib__,__sub__,__super__,__t__,__terminal__,__truediv__,__withblock__,__xor__,_sort,abs,all,any,assert,bin,bool,bytearray,bytes,callable,chr,delattr,dict,dir,divmod,enumerate,filter,float,getattr,hasattr,
hex,input,int,isinstance,issubclass,len,list,map,max,min,object,oct,ord,pow,print,property,py_TypeError,py_iter,py_metatype,py_next,py_reversed,py_typeof,range,repr,round,set,setattr,sorted,str,sum,tuple,zip}from"./org.transcrypt.__runtime__.js";import{ACTIVEEVENT,APPACTIVE,APPFOCUSMOUSE,APPINPUTFOCUS,APPMOUSEFOCUS,DOUBLEBUF,FULLSCREEN,HWACCEL,HWPALETTE,HWSURFACE,KEYDOWN,KEYUP,KMOD_ALT,KMOD_CAPS,KMOD_CTRL,KMOD_LALT,KMOD_LCTRL,KMOD_LMETA,KMOD_LSHIFT,KMOD_META,KMOD_MODE,KMOD_NONE,KMOD_NUM,KMOD_RALT,
KMOD_RCTRL,KMOD_RMETA,KMOD_RSHIFT,KMOD_SHIFT,K_0,K_1,K_2,K_3,K_4,K_5,K_6,K_7,K_8,K_9,K_ALT,K_AMPERSAND,K_ASTERISK,K_AT,K_BACKQUOTE,K_BACKSLASH,K_BACKSPACE,K_BREAK,K_CAPSLOCK,K_CARET,K_CLEAR,K_COLON,K_COMMA,K_CTRL,K_DELETE,K_DOLLAR,K_DOWN,K_END,K_EQUALS,K_ESCAPE,K_EURO,K_EXCLAIM,K_F1,K_F10,K_F11,K_F12,K_F13,K_F14,K_F15,K_F2,K_F3,K_F4,K_F5,K_F6,K_F7,K_F8,K_F9,K_GREATER,K_HASH,K_HELP,K_HOME,K_INSERT,K_KP0,K_KP1,K_KP2,K_KP3,K_KP4,K_KP5,K_KP6,K_KP7,K_KP8,K_KP9,K_KP_DIVIDE,K_KP_ENTER,K_KP_EQUALS,K_KP_MINUS,
K_KP_MULTIPLY,K_KP_PERIOD,K_KP_PLUS,K_LALT,K_LCTRL,K_LEFT,K_LEFTBRACKET,K_LEFTPAREN,K_LESS,K_LMETA,K_LSHIFT,K_LSUPER,K_MENU,K_MINUS,K_MODE,K_NUMLOCK,K_PAGEDOWN,K_PAGEUP,K_PAUSE,K_PERIOD,K_PLUS,K_POWER,K_PRINT,K_QUESTION,K_QUOTE,K_QUOTEDBL,K_RALT,K_RCTRL,K_RETURN,K_RIGHT,K_RIGHTBRACKET,K_RIGHTPAREN,K_RMETA,K_RSHIFT,K_RSUPER,K_SCROLLLOCK,K_SCROLLOCK,K_SEMICOLON,K_SHIFT,K_SLASH,K_SPACE,K_SYSREQ,K_TAB,K_UNDERSCORE,K_UNKNOWN,K_UP,K_a,K_b,K_c,K_d,K_e,K_f,K_g,K_h,K_i,K_j,K_k,K_l,K_m,K_n,K_o,K_p,K_q,K_r,
K_s,K_t,K_u,K_v,K_w,K_x,K_y,K_z,MOUSEBUTTONDOWN,MOUSEBUTTONUP,MOUSEMOTION,NOEVENT,NOFRAME,NUMEVENTS,OPENGL,QUIT,RESIZABLE,RLEACCEL,RLEACCELOK,SRCALPHA,SRCCOLORKEY,SWSURFACE,SYSWMEVENT,USEREVENT}from"./pyjsdl.constants.js";import*as version from"./pyjsdl.version.js";import*as cursors from"./pyjsdl.cursors.js";import*as sprite from"./pyjsdl.sprite.js";import*as font from"./pyjsdl.font.js";import*as mask from"./pyjsdl.mask.js";import*as surfarray from"./pyjsdl.surfarray.js";import*as surface from"./pyjsdl.surface.js";
import*as transform from"./pyjsdl.transform.js";import*as draw from"./pyjsdl.draw.js";import{Vector2}from"./pyjsdl.vector.js";import{Time}from"./pyjsdl.time.js";import{Mixer}from"./pyjsdl.mixer.js";import{Color}from"./pyjsdl.color.js";import{Mouse}from"./pyjsdl.mouse.js";import{Key}from"./pyjsdl.key.js";import{Event}from"./pyjsdl.event.js";import{Image}from"./pyjsdl.image.js";import{Rect}from"./pyjsdl.rect.js";import{Surface}from"./pyjsdl.surface.js";import{Display}from"./pyjsdl.display.js";import*as util from"./pyjsdl.util.js";
import*as env from"./pyjsdl.env.js";export{K_CAPSLOCK,K_KP4,K_SCROLLLOCK,K_F7,K_UP,K_F3,surfarray,K_RIGHT,Rect,K_q,K_COMMA,K_RCTRL,KMOD_MODE,K_k,K_CLEAR,version,sprite,K_KP8,K_F1,K_v,APPMOUSEFOCUS,Mixer,K_LEFT,Vector2,K_z,K_RIGHTBRACKET,K_a,Key,K_POWER,K_F8,Image,KMOD_NUM,K_HELP,K_F2,SRCALPHA,K_MINUS,surface,K_QUOTEDBL,K_g,K_ESCAPE,K_KP6,K_6,K_CARET,K_KP7,K_COLON,util,K_u,K_BACKSPACE,K_HOME,K_h,KEYUP,K_F13,K_LMETA,K_7,K_PAGEDOWN,K_PLUS,K_4,K_F4,RLEACCELOK,KMOD_RCTRL,K_DELETE,KMOD_META,K_KP3,K_RETURN,
K_DOLLAR,K_1,KMOD_ALT,K_KP_DIVIDE,K_BREAK,K_KP_PLUS,K_RSHIFT,K_r,K_RMETA,K_EXCLAIM,K_d,K_BACKQUOTE,K_F11,K_3,K_p,K_LSUPER,K_n,K_LCTRL,cursors,K_KP_MULTIPLY,DOUBLEBUF,K_RIGHTPAREN,RLEACCEL,Display,K_CTRL,ACTIVEEVENT,HWACCEL,K_ASTERISK,Event,K_AT,KMOD_RSHIFT,K_SEMICOLON,FULLSCREEN,K_i,K_NUMLOCK,KMOD_RALT,K_GREATER,NUMEVENTS,K_DOWN,K_F10,KMOD_RMETA,K_END,K_j,K_9,K_LALT,K_x,K_F6,KMOD_LMETA,KMOD_NONE,SRCCOLORKEY,K_KP2,K_F5,MOUSEMOTION,Surface,Time,K_KP_PERIOD,font,K_s,K_w,APPINPUTFOCUS,K_0,K_SLASH,K_RALT,
K_8,KMOD_LSHIFT,KMOD_LCTRL,K_b,K_2,APPACTIVE,K_BACKSLASH,K_EURO,MOUSEBUTTONUP,K_AMPERSAND,K_KP0,SWSURFACE,K_UNKNOWN,MOUSEBUTTONDOWN,KMOD_CTRL,K_m,transform,K_c,Mouse,K_TAB,APPFOCUSMOUSE,K_F9,K_INSERT,K_SCROLLOCK,K_KP_MINUS,K_SYSREQ,K_f,K_LESS,OPENGL,K_LEFTPAREN,K_UNDERSCORE,env,KMOD_SHIFT,K_KP5,KEYDOWN,K_F15,K_MODE,K_EQUALS,RESIZABLE,K_l,Color,K_o,K_RSUPER,K_PAGEUP,draw,HWSURFACE,K_KP9,K_HASH,K_ALT,K_SPACE,K_y,K_e,K_F14,K_t,K_QUESTION,USEREVENT,K_PERIOD,HWPALETTE,NOEVENT,K_SHIFT,K_MENU,K_KP1,KMOD_LALT,
K_F12,K_LSHIFT,mask,KMOD_CAPS,SYSWMEVENT,K_QUOTE,K_KP_ENTER,K_LEFTBRACKET,K_PRINT,K_KP_EQUALS,NOFRAME,QUIT,K_PAUSE,K_5};var __name__="pyjsdl";export var __version__="0.26";var __left0__=null;export var time=__left0__;export var display=__left0__;export var image=__left0__;export var event=__left0__;export var key=__left0__;export var mouse=__left0__;export var mixer=__left0__;export var _initialized=false;export var init=function(){if(_initialized)return;else _initialized=true;event=Event();env.set_env("event",
event);time=Time();display=Display();image=Image();mixer=Mixer();mouse=Mouse();key=Key();version.set_ver(__version__)};init();export var setup=function(callback,images){if(typeof images=="undefined"||images!=null&&images.hasOwnProperty("__kwargtrans__"))var images=null;display.setup(callback,images)};export var set_callback=function(callback){display.set_callback(callback)};export var setup_images=function(images){display.set_images(images)};export var quit=function(){var canvas=display.get_canvas();
canvas.stop();mixer.quit();time._stop_timers()};export var error=__class__("error",[Exception],{__module__:__name__});export var bounding_rect_return=function(setting){surface.bounding_rect_return(setting);draw.bounding_rect_return(setting)};export{__name__};

//# sourceMappingURL=pyjsdl.map