'use strict';import{AssertionError,AttributeError,BaseException,DeprecationWarning,Exception,IndexError,IterableError,KeyError,NotImplementedError,RuntimeWarning,StopIteration,UserWarning,ValueError,Warning,__JsIterator__,__PyIterator__,__Terminal__,__add__,__and__,__call__,__class__,__envir__,__eq__,__floordiv__,__ge__,__get__,__getcm__,__getitem__,__getslice__,__getsm__,__gt__,__i__,__iadd__,__iand__,__idiv__,__ijsmod__,__ilshift__,__imatmul__,__imod__,__imul__,__in__,__init__,__ior__,__ipow__,
__irshift__,__isub__,__ixor__,__jsUsePyNext__,__jsmod__,__k__,__kwargtrans__,__le__,__lshift__,__lt__,__matmul__,__mergefields__,__mergekwargtrans__,__mod__,__mul__,__ne__,__neg__,__nest__,__or__,__pow__,__pragma__,__pyUseJsNext__,__rshift__,__setitem__,__setproperty__,__setslice__,__sort__,__specialattrib__,__sub__,__super__,__t__,__terminal__,__truediv__,__withblock__,__xor__,_sort,abs,all,any,assert,bin,bool,bytearray,bytes,callable,chr,delattr,dict,dir,divmod,enumerate,filter,float,getattr,hasattr,
hex,input,int,isinstance,issubclass,len,list,map,max,min,object,oct,ord,pow,print,property,py_TypeError,py_iter,py_metatype,py_next,py_reversed,py_typeof,range,repr,round,set,setattr,sorted,str,sum,tuple,zip}from"./org.transcrypt.__runtime__.js";var __name__="pyjsdl.color";export var __docformat__="restructuredtext";export var Color=__class__("Color",[object],{__module__:__name__,get __init__(){return __get__(this,function(self){var color=tuple([].slice.apply(arguments).slice(1));var ln=__call__(len,
null,color);if(__eq__(ln,1)){var _color=__getitem__(color,0);if(__call__(isinstance,null,_color,tuple([tuple,list,Color])))var ln=__call__(len,null,_color)}else var _color=color;if(__eq__(ln,4)){self.r=__getitem__(_color,0);self.g=__getitem__(_color,1);self.b=__getitem__(_color,2);self.a=__getitem__(_color,3)}else if(__eq__(ln,3)){self.r=__getitem__(_color,0);self.g=__getitem__(_color,1);self.b=__getitem__(_color,2);self.a=255}else if(!__call__(isinstance,null,_color,str)){self.r=__and__(__rshift__(_color,
16),255);self.g=__and__(__rshift__(_color,8),255);self.b=__and__(_color,255);self.a=__and__(__rshift__(_color,24),255)}else{var _color=function(){var __accu0__=_color;return __call__(__accu0__.lower,__accu0__)}();if(function(){var __accu0__=_color;return __call__(__accu0__.startswith,__accu0__,"#")}())var _color=__getslice__(_color,1,null,1);else if(function(){var __accu0__=_color;return __call__(__accu0__.startswith,__accu0__,"0x")}())var _color=__getslice__(_color,2,null,1);if(__eq__(__call__(len,
null,_color),6))var _color=__call__(__iadd__,null,_color,"ff");self.r=__call__(parseInt,null,__getslice__(_color,0,2,1),16);self.g=__call__(parseInt,null,__getslice__(_color,2,4,1),16);self.b=__call__(parseInt,null,__getslice__(_color,4,6,1),16);self.a=__call__(parseInt,null,__getslice__(_color,6,8,1),16)}})},get __str__(){return __get__(this,function(self){return"rgba({}, {}, {}, {})".format(self.r,self.g,self.b,self.a/255)})},get __repr__(){return __get__(this,function(self){return"({}, {}, {}, {})".format(self.r,
self.g,self.b,self.a)})},get __getitem__(){return __get__(this,function(self,index){return dict({0:self.r,1:self.g,2:self.b,3:self.a})[index]})},get __setitem__(){return __get__(this,function(self,index,val){if(index==0)self.r=val;else if(index==1)self.g=val;else if(index==2)self.b=val;else if(index==3)self.a=val})},get __iter__(){return __get__(this,function(self){return py_iter([self.r,self.g,self.b,self.a])})},[Symbol.iterator](){return this.__iter__()},get __len__(){return __get__(this,function(self){return 4})},
get __eq__(){return __get__(this,function(self,other){if(hasattr(other,"a"))return self.r==other.r&&self.g==other.g&&self.b==other.b&&self.a==other.a;else if(len(other)==4)return self.a==other[3]&&self.r==other[0]&&self.g==other[1]&&self.b==other[2];else return self.r==other[0]&&self.g==other[1]&&self.b==other[2]})},get __ne__(){return __get__(this,function(self,other){if(hasattr(other,"a"))return self.r!=other.r||self.g!=other.g||self.b!=other.b||self.a!=other.a;else if(len(other)==4)return self.a!=
other[3]||self.r!=other[0]||self.g!=other[1]||self.b!=other[2];else return self.r!=other[0]||self.g!=other[1]||self.b!=other[2]})},get __add__(){return __get__(this,function(self,other){var r=self.r+other.r;if(r>255)var r=255;var g=self.g+other.g;if(g>255)var g=255;var b=self.b+other.b;if(b>255)var b=255;var a=self.a+other.a;if(a>255)var a=255;return self.__class__(r,g,b,a)})},get __sub__(){return __get__(this,function(self,other){var r=self.r-other.r;if(r<0)var r=0;var g=self.g-other.g;if(g<0)var g=
0;var b=self.b-other.b;if(b<0)var b=0;var a=self.a-other.a;if(a<0)var a=0;return self.__class__(r,g,b,a)})},get __mul__(){return __get__(this,function(self,other){var r=self.r*other.r;if(r>255)var r=255;var g=self.g*other.g;if(g>255)var g=255;var b=self.b*other.b;if(b>255)var b=255;var a=self.a*other.a;if(a>255)var a=255;return self.__class__(r,g,b,a)})},get __floordiv__(){return __get__(this,function(self,other){var r=other.r!=0?Math.floor(self.r/other.r):0;var g=other.g!=0?Math.floor(self.g/other.g):
0;var b=other.b!=0?Math.floor(self.b/other.b):0;var a=other.a!=0?Math.floor(self.a/other.a):0;return self.__class__(r,g,b,a)})},get __mod__(){return __get__(this,function(self,other){var r=other.r!=0?__mod__(self.r,other.r):0;var g=other.g!=0?__mod__(self.g,other.g):0;var b=other.b!=0?__mod__(self.b,other.b):0;var a=other.a!=0?__mod__(self.a,other.a):0;return self.__class__(r,g,b,a)})},get __iadd__(){return __get__(this,function(self,other){self.r+=other.r;if(self.r>255)self.r=255;self.g+=other.g;
if(self.g>255)self.g=255;self.b+=other.b;if(self.b>255)self.b=255;self.a+=other.a;if(self.a>255)self.a=255;return self})},get __isub__(){return __get__(this,function(self,other){self.r-=other.r;if(self.r<0)self.r=0;self.g-=other.g;if(self.g<0)self.g=0;self.b-=other.b;if(self.b<0)self.b=0;self.a-=other.a;if(self.a<0)self.a=0;return self})},get __imul__(){return __get__(this,function(self,other){self.r*=other.r;if(self.r>255)self.r=255;self.g*=other.g;if(self.g>255)self.g=255;self.b*=other.b;if(self.b>
255)self.b=255;self.a*=other.a;if(self.a>255)self.a=255;return self})},get __ifloordiv__(){return __get__(this,function(self,other){self.r=other.r!=0?Math.floor(self.r/other.r):0;self.g=other.g!=0?Math.floor(self.g/other.g):0;self.b=other.b!=0?Math.floor(self.b/other.b):0;self.a=other.a!=0?Math.floor(self.a/other.a):0;return self})},get __imod__(){return __get__(this,function(self,other){self.r=other.r!=0?__mod__(self.r,other.r):0;self.g=other.g!=0?__mod__(self.g,other.g):0;self.b=other.b!=0?__mod__(self.b,
other.b):0;self.a=other.a!=0?__mod__(self.a,other.a):0;return self})},get __invert__(){return __get__(this,function(self){return self.__class__(~self.r+256,~self.g+256,~self.b+256,~self.a+256)})},get normalize(){return __get__(this,function(self){return tuple([self.r/255,self.g/255,self.b/255,self.a/255])})},get correct_gamma(){return __get__(this,function(self,gamma){return self.__class__(round(Math.pow(self.r/255,gamma)*255),round(Math.pow(self.g/255,gamma)*255),round(Math.pow(self.b/255,gamma)*
255),round(Math.pow(self.a/255,gamma)*255))})},get premul_alpha(){return __get__(this,function(self){return self.__class__(round(self.r*(self.a/255)),round(self.g*(self.a/255)),round(self.b*(self.a/255)),self.a)})},get lerp(){return __get__(this,function(self,color,t){if(t<0||t>1){var __except0__=ValueError("Argument t must be in range 0 to 1");__except0__.__cause__=null;throw __except0__;}if(hasattr(color,"a"))return self.__class__(round(self.r*(1-t)+color.r*t),round(self.g*(1-t)+color.g*t),round(self.b*
(1-t)+color.b*t),round(self.a*(1-t)+color.a*t));else if(len(color)==3)return self.__class__(round(self.r*(1-t)+color[0]*t),round(self.g*(1-t)+color[1]*t),round(self.b*(1-t)+color[2]*t),round(self.a*(1-t)+255*t));else if(len(color)==4)return self.__class__(round(self.r*(1-t)+color[0]*t),round(self.g*(1-t)+color[1]*t),round(self.b*(1-t)+color[2]*t),round(self.a*(1-t)+color[3]*t));else{var __except0__=ValueError("invalid color argument");__except0__.__cause__=null;throw __except0__;}})},get py_update(){return __get__(this,
function(self){var color=tuple([].slice.apply(arguments).slice(1));var ln=__call__(len,null,color);if(__eq__(ln,1)){var _color=__getitem__(color,0);if(__call__(isinstance,null,_color,tuple([tuple,list,Color])))var ln=__call__(len,null,_color)}else var _color=color;if(__eq__(ln,4)){self.r=__getitem__(_color,0);self.g=__getitem__(_color,1);self.b=__getitem__(_color,2);self.a=__getitem__(_color,3)}else if(__eq__(ln,3)){self.r=__getitem__(_color,0);self.g=__getitem__(_color,1);self.b=__getitem__(_color,
2);self.a=255}else if(!__call__(isinstance,null,_color,str)){self.r=__and__(__rshift__(_color,16),255);self.g=__and__(__rshift__(_color,8),255);self.b=__and__(_color,255);self.a=__and__(__rshift__(_color,24),255)}else{var _color=function(){var __accu0__=_color;return __call__(__accu0__.lower,__accu0__)}();if(function(){var __accu0__=_color;return __call__(__accu0__.startswith,__accu0__,"#")}())var _color=__getslice__(_color,1,null,1);else if(function(){var __accu0__=_color;return __call__(__accu0__.startswith,
__accu0__,"0x")}())var _color=__getslice__(_color,2,null,1);if(__eq__(__call__(len,null,_color),6))var _color=__call__(__iadd__,null,_color,"ff");self.r=__call__(parseInt,null,__getslice__(_color,0,2,1),16);self.g=__call__(parseInt,null,__getslice__(_color,2,4,1),16);self.b=__call__(parseInt,null,__getslice__(_color,4,6,1),16);self.a=__call__(parseInt,null,__getslice__(_color,6,8,1),16)}})},get _get_cmy(){return __get__(this,function(self){return _rgb_to_cmy(self.r,self.g,self.b)})},get _set_cmy(){return __get__(this,
function(self,val){var __left0__=_cmy_to_rgb(...val);self.r=__left0__[0];self.g=__left0__[1];self.b=__left0__[2]})},get _get_hsva(){return __get__(this,function(self){return _rgba_to_hsva(self.r,self.g,self.b,self.a)})},get _set_hsva(){return __get__(this,function(self,val){var __left0__=_hsva_to_rgba(...val);self.r=__left0__[0];self.g=__left0__[1];self.b=__left0__[2];self.a=__left0__[3]})},get _get_hsla(){return __get__(this,function(self){return _rgba_to_hsla(self.r,self.g,self.b,self.a)})},get _set_hsla(){return __get__(this,
function(self,val){var __left0__=_hsla_to_rgba(...val);self.r=__left0__[0];self.g=__left0__[1];self.b=__left0__[2];self.a=__left0__[3]})},get update(){return __get__(this,function(self){var color=tuple([].slice.apply(arguments).slice(1));self.py_update(...color)})},get toString(){return __get__(this,function(self){return self.__str__()})}});Object.defineProperty(Color,"hsla",property.call(Color,Color._get_hsla,Color._set_hsla));Object.defineProperty(Color,"hsva",property.call(Color,Color._get_hsva,
Color._set_hsva));Object.defineProperty(Color,"cmy",property.call(Color,Color._get_cmy,Color._set_cmy));export var _rgb_to_cmy=function(r,g,b){var __left0__=tuple([r/255,g/255,b/255]);var r=__left0__[0];var g=__left0__[1];var b=__left0__[2];var __left0__=tuple([1-r,1-g,1-b]);var c=__left0__[0];var m=__left0__[1];var y=__left0__[2];return tuple([c,m,y])};export var _cmy_to_rgb=function(c,m,y){var __left0__=tuple([1-c,1-m,1-y]);var r=__left0__[0];var g=__left0__[1];var b=__left0__[2];return tuple([int(r*
255),int(g*255),int(b*255)])};export var _rgba_to_hsva=function(r,g,b,a){var __left0__=tuple([r/255,g/255,b/255,a/255]);var r=__left0__[0];var g=__left0__[1];var b=__left0__[2];var a=__left0__[3];var c_max=max(r,g,b);var c_min=min(r,g,b);var delta=c_max-c_min;if(delta==0)var h=0;else if(c_max==r)var h=__mod__(60*((g-b)/delta)+360,360);else if(c_max==g)var h=__mod__(60*((b-r)/delta)+120,360);else if(c_max==b)var h=__mod__(60*((r-g)/delta)+240,360);if(c_max==0)var s=0;else var s=delta/c_max;var v=c_max;
return tuple([h,s*100,v*100,a*100])};export var _hsva_to_rgba=function(h,s,v,a){var __left0__=tuple([h/360,s/100,v/100,a/100]);var h=__left0__[0];var s=__left0__[1];var v=__left0__[2];var a=__left0__[3];var i=int(h*6);var f=h*6-i;var p=v*(1-s);var q=v*(1-s*f);var t=v*(1-s*(1-f));var i=__mod__(i,6);if(i==0){var __left0__=tuple([v,t,p]);var r=__left0__[0];var g=__left0__[1];var b=__left0__[2]}else if(i==1){var __left0__=tuple([q,v,p]);var r=__left0__[0];var g=__left0__[1];var b=__left0__[2]}else if(i==
2){var __left0__=tuple([p,v,t]);var r=__left0__[0];var g=__left0__[1];var b=__left0__[2]}else if(i==3){var __left0__=tuple([p,q,v]);var r=__left0__[0];var g=__left0__[1];var b=__left0__[2]}else if(i==4){var __left0__=tuple([t,p,v]);var r=__left0__[0];var g=__left0__[1];var b=__left0__[2]}else if(i==5){var __left0__=tuple([v,p,q]);var r=__left0__[0];var g=__left0__[1];var b=__left0__[2]}return tuple([int(r*255),int(g*255),int(b*255),int(a*255)])};export var _rgba_to_hsla=function(r,g,b,a){var __left0__=
tuple([r/255,g/255,b/255,a/255]);var r=__left0__[0];var g=__left0__[1];var b=__left0__[2];var a=__left0__[3];var cmax=max(r,g,b);var cmin=min(r,g,b);var delta=cmax-cmin;var l=(cmax+cmin)/2;if(delta==0)var s=0;else var s=delta/(1-abs(2*l-1));if(delta==0)var h=0;else if(cmax==r)var h=__mod__(60*((g-b)/delta)+360,360);else if(cmax==g)var h=__mod__(60*((b-r)/delta)+120,360);else if(cmax==b)var h=__mod__(60*((r-g)/delta)+240,360);return tuple([h,s*100,l*100,a*100])};export var _hsla_to_rgba=function(h,
s,l,a){var __left0__=tuple([h/360,s/100,l/100,a/100]);var h=__left0__[0];var s=__left0__[1];var l=__left0__[2];var a=__left0__[3];var q=l<.5?l*(1+s):l+s-l*s;var p=2*l-q;var t=h+1/3;if(t<0)t++;else if(t>1)t--;if(t<1/6)var r=p+(q-p)*6*t;else if(t<1/2)var r=q;else if(t<2/3)var r=p+(q-p)*(2/3-t)*6;else var r=p;var t=h;if(t<0)t++;else if(t>1)t--;if(t<1/6)var g=p+(q-p)*6*t;else if(t<1/2)var g=q;else if(t<2/3)var g=p+(q-p)*(2/3-t)*6;else var g=p;var t=h-1/3;if(t<0)t++;else if(t>1)t--;if(t<1/6)var b=p+(q-
p)*6*t;else if(t<1/2)var b=q;else if(t<2/3)var b=p+(q-p)*(2/3-t)*6;else var b=p;return tuple([int(r*255),int(g*255),int(b*255),int(a*255)])};

//# sourceMappingURL=pyjsdl.color.map