'use strict';import{AssertionError,AttributeError,BaseException,DeprecationWarning,Exception,IndexError,IterableError,KeyError,NotImplementedError,RuntimeWarning,StopIteration,UserWarning,ValueError,Warning,__JsIterator__,__PyIterator__,__Terminal__,__add__,__and__,__call__,__class__,__envir__,__eq__,__floordiv__,__ge__,__get__,__getcm__,__getitem__,__getslice__,__getsm__,__gt__,__i__,__iadd__,__iand__,__idiv__,__ijsmod__,__ilshift__,__imatmul__,__imod__,__imul__,__in__,__init__,__ior__,__ipow__,
__irshift__,__isub__,__ixor__,__jsUsePyNext__,__jsmod__,__k__,__kwargtrans__,__le__,__lshift__,__lt__,__matmul__,__mergefields__,__mergekwargtrans__,__mod__,__mul__,__ne__,__neg__,__nest__,__or__,__pow__,__pragma__,__pyUseJsNext__,__rshift__,__setitem__,__setproperty__,__setslice__,__sort__,__specialattrib__,__sub__,__super__,__t__,__terminal__,__truediv__,__withblock__,__xor__,_sort,abs,all,any,assert,bin,bool,bytearray,bytes,callable,chr,delattr,dict,dir,divmod,enumerate,filter,float,getattr,hex,
input,int,isinstance,issubclass,len,list,map,max,min,object,oct,ord,pow,print,property,py_TypeError,py_iter,py_metatype,py_next,py_reversed,py_typeof,range,repr,round,set,setattr,sorted,str,sum,tuple,zip}from"./org.transcrypt.__runtime__.js";import{hasattr_v2 as hasattr}from"./pyjsdl.pyjsobj.js";import{atan2,cos,floor,pi,sin}from"./math.js";var __name__="pyjsdl.vector";export var Vector2=__class__("Vector2",[object],{__module__:__name__,__slots__:["_x","_y"],get __init__(){return __get__(this,function(self,
x,y){if(typeof x=="undefined"||x!=null&&x.hasOwnProperty("__kwargtrans__"))var x=null;if(typeof y=="undefined"||y!=null&&y.hasOwnProperty("__kwargtrans__"))var y=null;if(y!==null){self._x=float(x);self._y=float(y)}else if(x!==null){self._x=__call__(float,null,__getitem__(x,0));self._y=__call__(float,null,__getitem__(x,1))}else{self._x=0;self._y=0}})},get _get_x(){return __get__(this,function(self){return self._x})},get _set_x(){return __get__(this,function(self,val){self._x=float(val)})},get x(){return __get__(this,
x.deleter(function(self){var __except0__=py_TypeError("Cannot delete the x attribute");__except0__.__cause__=null;throw __except0__;}))},get _get_y(){return __get__(this,function(self){return self._y})},get _set_y(){return __get__(this,function(self,val){self._y=float(val)})},get y(){return __get__(this,y.deleter(function(self){var __except0__=py_TypeError("Cannot delete the y attribute");__except0__.__cause__=null;throw __except0__;}))},get __str__(){return __get__(this,function(self){return"[{}, {}]".format(self._x,
self._y)})},get __repr__(){return __get__(this,function(self){return"<{}({}, {})>".format(self.__class__.__name__,self._x,self._y)})},get __getitem__(){return __get__(this,function(self,index){if(__in__(index,tuple([0,-2])))return self._x;else if(__in__(index,tuple([1,-1])))return self._y;else if(isinstance(index,slice))return[self._x,self._y][index];else{var __except0__=IndexError;__except0__.__cause__=null;throw __except0__;}})},get __setitem__(){return __get__(this,function(self,index,val){if(index==
0)self._x=float(val);else if(index==1)self._y=float(val);else if(isinstance(index,slice)){var l=[self._x,self._y];l[index]=val;if(len(l)!=2){var __except0__=ValueError;__except0__.__cause__=null;throw __except0__;}self._x=float(l[0]);self._y=float(l[1])}else{var __except0__=IndexError;__except0__.__cause__=null;throw __except0__;}})},get __delitem__(){return __get__(this,function(self,index){var __except0__=py_TypeError("Deletion of vector components is not supported");__except0__.__cause__=null;
throw __except0__;})},get __getslice__(){return __get__(this,function(self,start,stop){return[self._x,self._y].__getslice__(start,stop,1)})},get __setslice__(){return __get__(this,function(self,lower,upper,val){var l=[self._x,self._y];l.__setslice__(lower,upper,null,val);if(len(l)!=2){var __except0__=ValueError;__except0__.__cause__=null;throw __except0__;}self._x=float(l[0]);self._y=float(l[1])})},get __iter__(){return __get__(this,function*(self){for(var val of tuple([self._x,self._y]))yield val})},
[Symbol.iterator](){return this.__iter__()},get __len__(){return __get__(this,function(self){return 2})},get __bool__(){return __get__(this,function(self){return bool(self._x||self._y)})},get __nonzero__(){return __get__(this,function(self){return bool(self._x||self._y)})},get dot(){return __get__(this,function(self,vector){if(hasattr(vector,"_x"))return self._x*vector._x+self._y*vector._y;else return self._x*vector[0]+self._y*vector[1]})},get cross(){return __get__(this,function(self,vector){if(hasattr(vector,
"_x"))return self._x*vector._y-self._y*vector._x;else return self._x*vector[0]-self._y*vector[1]})},get magnitude(){return __get__(this,function(self){return Math.pow(Math.pow(self._x,2)+Math.pow(self._y,2),.5)})},get magnitude_squared(){return __get__(this,function(self){return Math.pow(self._x,2)+Math.pow(self._y,2)})},get length(){return __get__(this,function(self){return Math.pow(Math.pow(self._x,2)+Math.pow(self._y,2),.5)})},get length_squared(){return __get__(this,function(self){return Math.pow(self._x,
2)+Math.pow(self._y,2)})},get normalize(){return __get__(this,function(self){var mag=self.magnitude();if(mag==0){var __except0__=ValueError("Cannot normalize vector of zero length");__except0__.__cause__=null;throw __except0__;}return self.__class__(self._x/mag,self._y/mag)})},get normalize_ip(){return __get__(this,function(self){var mag=self.magnitude();if(mag==0){var __except0__=ValueError("Cannot normalize vector of zero length");__except0__.__cause__=null;throw __except0__;}self._x/=mag;self._y/=
mag;return null})},get is_normalized(){return __get__(this,function(self){return self.magnitude()==1})},get scale_to_length(){return __get__(this,function(self,length){var mag=self.magnitude();if(mag==0){var __except0__=ValueError("Cannot scale vector of zero length");__except0__.__cause__=null;throw __except0__;}self._x=self._x/mag*length;self._y=self._y/mag*length;return null})},get reflect(){return __get__(this,function(self,vector){if(hasattr(vector,"_x")){var vector_x=vector._x;var vector_y=
vector._y}else{var vector_x=vector[0];var vector_y=vector[1]}var vn=self._x*vector_x+self._y*vector_y;var nn=vector_x*vector_x+vector_y*vector_y;if(nn==0){var __except0__=ValueError("Cannot reflect from normal of zero length");__except0__.__cause__=null;throw __except0__;}var c=2*vn/nn;return self.__class__(self._x-vector_x*c,self._y-vector_y*c)})},get reflect_ip(){return __get__(this,function(self,vector){if(hasattr(vector,"_x")){var vector_x=vector._x;var vector_y=vector._y}else{var vector_x=vector[0];
var vector_y=vector[1]}var vn=self._x*vector_x+self._y*vector_y;var nn=vector_x*vector_x+vector_y*vector_y;if(nn==0){var __except0__=ValueError("Cannot reflect from normal of zero length");__except0__.__cause__=null;throw __except0__;}var c=2*vn/nn;self._x-=vector_x*c;self._y-=vector_y*c;return null})},get distance_to(){return __get__(this,function(self,vector){if(hasattr(vector,"_x"))return Math.pow(Math.pow(self._x-vector._x,2)+Math.pow(self._y-vector._y,2),.5);else return Math.pow(Math.pow(self._x-
vector[0],2)+Math.pow(self._y-vector[1],2),.5)})},get distance_squared_to(){return __get__(this,function(self,vector){if(hasattr(vector,"_x"))return Math.pow(self._x-vector._x,2)+Math.pow(self._y-vector._y,2);else return Math.pow(self._x-vector[0],2)+Math.pow(self._y-vector[1],2)})},get lerp(){return __get__(this,function(self,vector,t){if(t<0||t>1){var __except0__=ValueError("Argument t must be in range 0 to 1");__except0__.__cause__=null;throw __except0__;}if(hasattr(vector,"_x"))return self.__class__(self._x*
(1-t)+vector._x*t,self._y*(1-t)+vector._y*t);else return self.__class__(self._x*(1-t)+vector[0]*t,self._y*(1-t)+vector[1]*t)})},get slerp(){return __get__(this,function(self,vector,t){if(t<-1||t>1){var __except0__=ValueError("Argument t must be in range -1 to 1");__except0__.__cause__=null;throw __except0__;}if(hasattr(vector,"_x")){var vector_x=vector._x;var vector_y=vector._y}else{var vector_x=vector[0];var vector_y=vector[1]}var smag=Math.pow(Math.pow(self._x,2)+Math.pow(self._y,2),.5);var vmag=
Math.pow(Math.pow(vector_x,2)+Math.pow(vector_y,2),.5);if(smag==0||vmag==0){var __except0__=ValueError("Cannot use slerp with zero-vector");__except0__.__cause__=null;throw __except0__;}var sx=self._x/smag;var sy=self._y/smag;var vx=vector_x/vmag;var vy=vector_y/vmag;var theta=atan2(vy,vx)-atan2(sy,sx);var _theta=abs(theta);if(_theta-pi>1E-6)theta-=2*pi*(theta/_theta);else if(-1E-6<_theta-pi&&_theta-pi<1E-6){var __except0__=ValueError("Cannot use slerp on 180 degrees");__except0__.__cause__=null;
throw __except0__;}if(t<0){var t=-t;theta-=2*pi*(theta/abs(theta))}var sin_theta=sin(theta);if(sin_theta){var a=sin((1-t)*theta)/sin_theta;var b=sin(t*theta)/sin_theta}else{var a=1;var b=0}var v=self.__class__(sx*a+vx*b,sy*a+vy*b);var smag=(1-t)*smag+t*vmag;v.x*=smag;v.y*=smag;return v})},get elementwise(){return __get__(this,function(self){return VectorElementwiseProxy(self)})},get rotate(){return __get__(this,function(self,angle){var rad=angle/180*pi;var c=round(cos(rad),6);var s=round(sin(rad),
6);return self.__class__(c*self._x-s*self._y,s*self._x+c*self._y)})},get rotate_rad(){return __get__(this,function(self,angle){var c=cos(angle);var s=sin(angle);return self.__class__(c*self._x-s*self._y,s*self._x+c*self._y)})},get rotate_ip(){return __get__(this,function(self,angle){var r=angle/180*pi;var c=round(cos(r),6);var s=round(sin(r),6);var x=self._x;var y=self._y;self._x=c*x-s*y;self._y=s*x+c*y;return null})},get rotate_ip_rad(){return __get__(this,function(self,angle){var c=cos(angle);var s=
sin(angle);var x=self._x;var y=self._y;self._x=c*x-s*y;self._y=s*x+c*y;return null})},get angle_to(){return __get__(this,function(self,vector){if(hasattr(vector,"_x"))return(atan2(vector._y,vector._x)-atan2(self._y,self._x))*(180/pi);else return(atan2(vector[1],vector[0])-atan2(self._y,self._x))*(180/pi)})},get as_polar(){return __get__(this,function(self){var r=self.magnitude();var phi=atan2(self._y,self._x)*(180/pi);return tuple([r,phi])})},get from_polar(){return __get__(this,function(self,coordinate){if(len(coordinate)!=
2){var __except0__=py_TypeError("coodinate must be of length 2");__except0__.__cause__=null;throw __except0__;}var r=coordinate[0];var phi=coordinate[1]*(pi/180);self._x=round(r*cos(phi),6);self._y=round(r*sin(phi),6);return null})},get copy(){return __get__(this,function(self){return self.__class__(self._x,self._y)})},get py_update(){return __get__(this,function(self,x,y){if(typeof x=="undefined"||x!=null&&x.hasOwnProperty("__kwargtrans__"))var x=null;if(typeof y=="undefined"||y!=null&&y.hasOwnProperty("__kwargtrans__"))var y=
null;if(y!==null){self._x=float(x);self._y=float(y)}else if(x!==null){self._x=__call__(float,null,__getitem__(x,0));self._y=__call__(float,null,__getitem__(x,1))}else{self._x=0;self._y=0}})},get __pos__(){return __get__(this,function(self){return self.__class__(self._x,self._y)})},get __neg__(){return __get__(this,function(self){return self.__class__(-self._x,-self._y)})},get __add__(){return __get__(this,function(self,other){if(hasattr(other,"_x"))return self.__class__(self._x+other._x,self._y+other._y);
else if(hasattr(other,"__iter__"))return function(){var __accu0__=self;return __call__(__accu0__.__class__,__accu0__,__add__(self._x,__getitem__(other,0)),__add__(self._y,__getitem__(other,1)))}();else{var __except0__=py_TypeError("unsupported operand");__except0__.__cause__=null;throw __except0__;}})},get __sub__(){return __get__(this,function(self,other){if(hasattr(other,"_x"))return self.__class__(self._x-other._x,self._y-other._y);else if(hasattr(other,"__iter__"))return function(){var __accu0__=
self;return __call__(__accu0__.__class__,__accu0__,__sub__(self._x,__getitem__(other,0)),__sub__(self._y,__getitem__(other,1)))}();else{var __except0__=py_TypeError("unsupported operand");__except0__.__cause__=null;throw __except0__;}})},get __mul__(){return __get__(this,function(self,other){if(hasattr(other,"_x"))return self._x*other._x+self._y*other._y;else if(hasattr(other,"__iter__"))if(!hasattr(other,"_v"))return self._x*other[0]+self._y*other[1];else return function(){var __accu0__=self;return __call__(__accu0__.__class__,
__accu0__,__mul__(self._x,__getitem__(other,0)),__mul__(self._y,__getitem__(other,1)))}();else return self.__class__(self._x*other,self._y*other)})},get __div__(){return __get__(this,function(self,other){if(hasattr(other,"_x")){var __except0__=py_TypeError("unsupported operand");__except0__.__cause__=null;throw __except0__;}else if(hasattr(other,"__iter__"))if(!hasattr(other,"_v"))return self.__class__(self._x/other[0],self._y/other[1]);else return function(){var __accu0__=self;return __call__(__accu0__.__class__,
__accu0__,__truediv__(self._x,__getitem__(other,0)),__truediv__(self._y,__getitem__(other,1)))}();else return self.__class__(self._x/other,self._y/other)})},get __truediv__(){return __get__(this,function(self,other){if(hasattr(other,"_x")){var __except0__=py_TypeError("unsupported operand");__except0__.__cause__=null;throw __except0__;}else if(hasattr(other,"__iter__"))if(!hasattr(other,"_v"))return self.__class__(self._x/other[0],self._y/other[1]);else return function(){var __accu0__=self;return __call__(__accu0__.__class__,
__accu0__,__truediv__(self._x,__getitem__(other,0)),__truediv__(self._y,__getitem__(other,1)))}();else return self.__class__(self._x/other,self._y/other)})},get __floordiv__(){return __get__(this,function(self,other){if(hasattr(other,"_x")){var __except0__=py_TypeError("unsupported operand");__except0__.__cause__=null;throw __except0__;}else if(hasattr(other,"__iter__"))if(!hasattr(other,"_v"))return self.__class__(floor(self._x/other[0]),floor(self._y/other[1]));else return function(){var __accu0__=
self;return __call__(__accu0__.__class__,__accu0__,__call__(floor,null,__truediv__(self._x,__getitem__(other,0))),__call__(floor,null,__truediv__(self._y,__getitem__(other,1))))}();else return self.__class__(floor(self._x/other),floor(self._y/other))})},get __eq__(){return __get__(this,function(self,other){if(hasattr(other,"_x"))return abs(self._x-other._x)<1E-6&&abs(self._y-other._y)<1E-6;else if(hasattr(other,"__iter__"))return __lt__(__call__(abs,null,__sub__(self._x,__getitem__(other,0))),1E-6)&&
__lt__(__call__(abs,null,__sub__(self._y,__getitem__(other,1))),1E-6);else return false})},get __ne__(){return __get__(this,function(self,other){if(hasattr(other,"_x"))return abs(self._x-other._x)>1E-6||abs(self._y-other._y)>1E-6;else if(hasattr(other,"__iter__"))return __gt__(__call__(abs,null,__sub__(self._x,__getitem__(other,0))),1E-6)||__gt__(__call__(abs,null,__sub__(self._y,__getitem__(other,1))),1E-6);else return true})},get __gt__(){return __get__(this,function(self,other){if(!hasattr(other,
"_v")){var __except0__=py_TypeError("operation not supported");__except0__.__cause__=null;throw __except0__;}return other.__lt__(self)})},get __ge__(){return __get__(this,function(self,other){if(!hasattr(other,"_v")){var __except0__=py_TypeError("operation not supported");__except0__.__cause__=null;throw __except0__;}return other.__le__(self)})},get __lt__(){return __get__(this,function(self,other){if(!hasattr(other,"_v")){var __except0__=py_TypeError("operation not supported");__except0__.__cause__=
null;throw __except0__;}return other.__gt__(self)})},get __le__(){return __get__(this,function(self,other){if(!hasattr(other,"_v")){var __except0__=py_TypeError("operation not supported");__except0__.__cause__=null;throw __except0__;}return other.__ge__(self)})},get __radd__(){return __get__(this,function(self,other){if(hasattr(other,"__iter__"))return self.__class__(self._x+other[0],self._y+other[1]);else{var __except0__=py_TypeError("unsupported operand");__except0__.__cause__=null;throw __except0__;
}})},get __rsub__(){return __get__(this,function(self,other){if(hasattr(other,"__iter__"))return self.__class__(other[0]-self._x,other[1]-self._y);else{var __except0__=py_TypeError("unsupported operand");__except0__.__cause__=null;throw __except0__;}})},get __rmul__(){return __get__(this,function(self,other){if(hasattr(other,"__iter__"))return self._x*other[0]+self._y*other[1];else return self.__class__(self._x*other,self._y*other)})},get __rdiv__(){return __get__(this,function(self,other){if(!hasattr(other,
"_v")){var __except0__=py_TypeError("unsupported operand");__except0__.__cause__=null;throw __except0__;}else return self.__class__(other[0]/self._x,other[1]/self._y)})},get __rtruediv__(){return __get__(this,function(self,other){if(!hasattr(other,"_v")){var __except0__=py_TypeError("unsupported operand");__except0__.__cause__=null;throw __except0__;}else return self.__class__(other[0]/self._x,other[1]/self._y)})},get __rfloordiv__(){return __get__(this,function(self,other){if(!hasattr(other,"_v")){var __except0__=
py_TypeError("unsupported operand");__except0__.__cause__=null;throw __except0__;}else return self.__class__(floor(other[0]/self._x),floor(other[1]/self._y))})},get __iadd__(){return __get__(this,function(self,other){if(hasattr(other,"_x")){self._x+=other._x;self._y+=other._y}else if(hasattr(other,"__iter__")){self._x=__call__(__iadd__,null,self._x,__getitem__(other,0));self._y=__call__(__iadd__,null,self._y,__getitem__(other,1))}else{var __except0__=py_TypeError("unsupported operand");__except0__.__cause__=
null;throw __except0__;}return self})},get __isub__(){return __get__(this,function(self,other){if(hasattr(other,"_x")){self._x-=other._x;self._y-=other._y}else if(hasattr(other,"__iter__")){self._x=__call__(__isub__,null,self._x,__getitem__(other,0));self._y=__call__(__isub__,null,self._y,__getitem__(other,1))}else{var __except0__=py_TypeError("unsupported operand");__except0__.__cause__=null;throw __except0__;}return self})},get __imul__(){return __get__(this,function(self,other){if(hasattr(other,
"_x"))return self._x*other._x+self._y*other._y;else if(hasattr(other,"__iter__"))if(!hasattr(other,"_v"))return self._x*other[0]+self._y*other[1];else{self._x=__call__(__imul__,null,self._x,__getitem__(other,0));self._y=__call__(__imul__,null,self._y,__getitem__(other,1))}else{self._x*=other;self._y*=other}return self})},get __idiv__(){return __get__(this,function(self,other){if(hasattr(other,"__iter__"))if(!hasattr(other,"_v")){var __except0__=py_TypeError("unsupported operand");__except0__.__cause__=
null;throw __except0__;}else{self._x=__call__(__idiv__,null,self._x,__getitem__(other,0));self._y=__call__(__idiv__,null,self._y,__getitem__(other,1))}else{self._x/=other;self._y/=other}return self})},get __itruediv__(){return __get__(this,function(self,other){if(hasattr(other,"__iter__"))if(!hasattr(other,"_v")){var __except0__=py_TypeError("unsupported operand");__except0__.__cause__=null;throw __except0__;}else{self._x=__call__(__idiv__,null,self._x,__getitem__(other,0));self._y=__call__(__idiv__,
null,self._y,__getitem__(other,1))}else{self._x/=other;self._y/=other}return self})},get __ifloordiv__(){return __get__(this,function(self,other){if(hasattr(other,"__iter__"))if(!hasattr(other,"_v")){var __except0__=py_TypeError("unsupported operand");__except0__.__cause__=null;throw __except0__;}else{self._x=__call__(float,null,__call__(floor,null,__truediv__(self._x,__getitem__(other,0))));self._y=__call__(float,null,__call__(floor,null,__truediv__(self._y,__getitem__(other,1))))}else{self._x=float(floor(self._x/
other));self._y=float(floor(self._y/other))}return self})},get update(){return __get__(this,function(self,x,y){if(typeof x=="undefined"||x!=null&&x.hasOwnProperty("__kwargtrans__"))var x=null;if(typeof y=="undefined"||y!=null&&y.hasOwnProperty("__kwargtrans__"))var y=null;self.py_update(x,y)})},get toString(){return __get__(this,function(self){return self.__str__()})}});Object.defineProperty(Vector2,"y",property.call(Vector2,Vector2._get_y,Vector2._set_y));Object.defineProperty(Vector2,"x",property.call(Vector2,
Vector2._get_x,Vector2._set_x));export var VectorElementwiseProxy=__class__("VectorElementwiseProxy",[object],{__module__:__name__,get __init__(){return __get__(this,function(self,vector){self._v=vector})},get __str__(){return __get__(this,function(self){return"<{} object>".format(self.__class__.__name__)})},get __repr__(){return __get__(this,function(self){return"<{} object>".format(self.__class__.__name__)})},get __getitem__(){return __get__(this,function(self,index){if(__in__(index,tuple([0,-2])))return self._v._x;
else if(__in__(index,tuple([1,-1])))return self._v._y})},get __iter__(){return __get__(this,function*(self){for(var val of tuple([self._v._x,self._v._y]))yield val})},[Symbol.iterator](){return this.__iter__()},get __len__(){return __get__(this,function(self){return 2})},get __bool__(){return __get__(this,function(self){return bool(self._v._x||self._v._y)})},get __nonzero__(){return __get__(this,function(self){return bool(self._v._x||self._v._y)})},get __pos__(){return __get__(this,function(self){return self._v.__class__(self._v._x,
self._v._y)})},get __neg__(){return __get__(this,function(self){return self._v.__class__(-self._v._x,-self._v._y)})},get __abs__(){return __get__(this,function(self){return tuple([abs(self._v._x),abs(self._v._y)])})},get __add__(){return __get__(this,function(self,other){if(hasattr(other,"_x"))return self._v.__class__(self._v._x+other._x,self._v._y+other._y);else if(hasattr(other,"__iter__"))return function(){var __accu0__=self._v;return __call__(__accu0__.__class__,__accu0__,__add__(self._v._x,__getitem__(other,
0)),__add__(self._v._y,__getitem__(other,1)))}();else return self._v.__class__(self._v._x+other,self._v._y+other)})},get __sub__(){return __get__(this,function(self,other){if(hasattr(other,"_x"))return self._v.__class__(self._v._x-other._x,self._v._y-other._y);else if(hasattr(other,"__iter__"))return function(){var __accu0__=self._v;return __call__(__accu0__.__class__,__accu0__,__sub__(self._v._x,__getitem__(other,0)),__sub__(self._v._y,__getitem__(other,1)))}();else return self._v.__class__(self._v._x-
other,self._v._y-other)})},get __mul__(){return __get__(this,function(self,other){if(hasattr(other,"_x"))return self._v.__class__(self._v._x*other._x,self._v._y*other._y);else if(hasattr(other,"__iter__"))return function(){var __accu0__=self._v;return __call__(__accu0__.__class__,__accu0__,__mul__(self._v._x,__getitem__(other,0)),__mul__(self._v._y,__getitem__(other,1)))}();else return self._v.__class__(self._v._x*other,self._v._y*other)})},get __div__(){return __get__(this,function(self,other){if(hasattr(other,
"_x"))return self._v.__class__(self._v._x/other._x,self._v._y/other._y);else if(hasattr(other,"__iter__"))return function(){var __accu0__=self._v;return __call__(__accu0__.__class__,__accu0__,__truediv__(self._v._x,__getitem__(other,0)),__truediv__(self._v._y,__getitem__(other,1)))}();else return self._v.__class__(self._v._x/other,self._v._y/other)})},get __truediv__(){return __get__(this,function(self,other){if(hasattr(other,"_x"))return self._v.__class__(self._v._x/other._x,self._v._y/other._y);
else if(hasattr(other,"__iter__"))return function(){var __accu0__=self._v;return __call__(__accu0__.__class__,__accu0__,__truediv__(self._v._x,__getitem__(other,0)),__truediv__(self._v._y,__getitem__(other,1)))}();else return self._v.__class__(self._v._x/other,self._v._y/other)})},get __floordiv__(){return __get__(this,function(self,other){if(hasattr(other,"_x"))return self._v.__class__(floor(self._v._x/other._x),floor(self._v._y/other._y));else if(hasattr(other,"__iter__"))return function(){var __accu0__=
self._v;return __call__(__accu0__.__class__,__accu0__,__call__(floor,null,__truediv__(self._v._x,__getitem__(other,0))),__call__(floor,null,__truediv__(self._v._y,__getitem__(other,1))))}();else return self._v.__class__(floor(self._v._x/other),floor(self._v._y/other))})},get __pow__(){return __get__(this,function(self,other){if(hasattr(other,"_x")){if(__mod__(other._x,1)&&self._v._x<0||__mod__(other._y,1)&&self._v._y<0){var __except0__=ValueError("negative number cannot be raised to a fractional power");
__except0__.__cause__=null;throw __except0__;}return self._v.__class__(Math.pow(self._v._x,other._x),Math.pow(self._v._y,other._y))}else if(hasattr(other,"__iter__")){if(__mod__(__getitem__(other,0),1)&&__lt__(self._v._x,0)||__mod__(__getitem__(other,1),1)&&__lt__(self._v._y,0)){var __except0__=__call__(ValueError,null,"negative number cannot be raised to a fractional power");__except0__.__cause__=null;throw __except0__;}return function(){var __accu0__=self._v;return __call__(__accu0__.__class__,
__accu0__,__pow__(self._v._x,__getitem__(other,0)),__pow__(self._v._y,__getitem__(other,1)))}()}else{if(__mod__(other,1)&&(self._v._x<0||self._v._y<0)){var __except0__=ValueError("negative number cannot be raised to a fractional power");__except0__.__cause__=null;throw __except0__;}return self._v.__class__(Math.pow(self._v._x,other),Math.pow(self._v._y,other))}})},get __mod__(){return __get__(this,function(self,other){if(hasattr(other,"_x"))return self._v.__class__(__mod__(self._v._x,other._x),__mod__(self._v._y,
other._y));else if(hasattr(other,"__iter__"))return function(){var __accu0__=self._v;return __call__(__accu0__.__class__,__accu0__,__mod__(self._v._x,__getitem__(other,0)),__mod__(self._v._y,__getitem__(other,1)))}();else return self._v.__class__(__mod__(self._v._x,other),__mod__(self._v._y,other))})},get __eq__(){return __get__(this,function(self,other){if(hasattr(other,"_x"))return abs(self._v._x-other._x)<1E-6&&abs(self._v._y-other._y)<1E-6;else if(hasattr(other,"__iter__"))return __lt__(__call__(abs,
null,__sub__(self._v._x,__getitem__(other,0))),1E-6)&&__lt__(__call__(abs,null,__sub__(self._v._y,__getitem__(other,1))),1E-6);else return false})},get __ne__(){return __get__(this,function(self,other){if(hasattr(other,"_x"))return abs(self._v._x-other._x)>1E-6||abs(self._v._y-other._y)>1E-6;else if(hasattr(other,"__iter__"))return __gt__(__call__(abs,null,__sub__(self._v._x,__getitem__(other,0))),1E-6)||__gt__(__call__(abs,null,__sub__(self._v._y,__getitem__(other,1))),1E-6);else return true})},
get __gt__(){return __get__(this,function(self,other){if(hasattr(other,"_x"))return bool(self._v._x>other._x&&self._v._y>other._y);else if(hasattr(other,"__iter__"))return __call__(bool,null,__gt__(self._v._x,__getitem__(other,0))&&__gt__(self._v._y,__getitem__(other,1)));else return bool(self._v._x>other&&self._v._y>other)})},get __ge__(){return __get__(this,function(self,other){if(hasattr(other,"_x"))return bool(self._v._x>=other._x&&self._v._y>=other._y);else if(hasattr(other,"__iter__"))return __call__(bool,
null,__ge__(self._v._x,__getitem__(other,0))&&__ge__(self._v._y,__getitem__(other,1)));else return bool(self._v._x>=other&&self._v._y>=other)})},get __lt__(){return __get__(this,function(self,other){if(hasattr(other,"_x"))return bool(self._v._x<other._x&&self._v._y<other._y);else if(hasattr(other,"__iter__"))return __call__(bool,null,__lt__(self._v._x,__getitem__(other,0))&&__lt__(self._v._y,__getitem__(other,1)));else return bool(self._v._x<other&&self._v._y<other)})},get __le__(){return __get__(this,
function(self,other){if(hasattr(other,"_x"))return bool(self._v._x<=other._x&&self._v._y<=other._y);else if(hasattr(other,"__iter__"))return __call__(bool,null,__le__(self._v._x,__getitem__(other,0))&&__le__(self._v._y,__getitem__(other,1)));else return bool(self._v._x<=other&&self._v._y<=other)})},get __radd__(){return __get__(this,function(self,other){if(hasattr(other,"_x"))return self._v.__class__(self._v._x+other._x,self._v._y+other._y);else if(hasattr(other,"__iter__"))return function(){var __accu0__=
self._v;return __call__(__accu0__.__class__,__accu0__,__add__(self._v._x,__getitem__(other,0)),__add__(self._v._y,__getitem__(other,1)))}();else return self._v.__class__(self._v._x+other,self._v._y+other)})},get __rsub__(){return __get__(this,function(self,other){if(hasattr(other,"_x"))return self._v.__class__(other._x-self._v._x,other._y-self._v._y);else if(hasattr(other,"__iter__"))return function(){var __accu0__=self._v;return __call__(__accu0__.__class__,__accu0__,__sub__(__getitem__(other,0),
self._v._x),__sub__(__getitem__(other,1),self._v._y))}();else return self._v.__class__(other-self._v._x,other-self._v._y)})},get __rmul__(){return __get__(this,function(self,other){if(hasattr(other,"_x"))return self._v.__class__(self._v._x*other._x,self._v._y*other._y);else if(hasattr(other,"__iter__"))return function(){var __accu0__=self._v;return __call__(__accu0__.__class__,__accu0__,__mul__(self._v._x,__getitem__(other,0)),__mul__(self._v._y,__getitem__(other,1)))}();else return self._v.__class__(self._v._x*
other,self._v._y*other)})},get __rdiv__(){return __get__(this,function(self,other){if(hasattr(other,"_x"))return self._v.__class__(other._x/self._v._x,other._y/self._v._y);else if(hasattr(other,"__iter__"))return function(){var __accu0__=self._v;return __call__(__accu0__.__class__,__accu0__,__truediv__(__getitem__(other,0),self._v._x),__truediv__(__getitem__(other,1),self._v._y))}();else return self._v.__class__(other/self._v._x,other/self._v._y)})},get __rtruediv__(){return __get__(this,function(self,
other){if(hasattr(other,"_x"))return self._v.__class__(other._x/self._v._x,other._y/self._v._y);else if(hasattr(other,"__iter__"))return function(){var __accu0__=self._v;return __call__(__accu0__.__class__,__accu0__,__truediv__(__getitem__(other,0),self._v._x),__truediv__(__getitem__(other,1),self._v._y))}();else return self._v.__class__(other/self._v._x,other/self._v._y)})},get __rfloordiv__(){return __get__(this,function(self,other){if(hasattr(other,"_x"))return self._v.__class__(floor(other._x/
self._v._x),floor(other._y/self._v._y));else if(hasattr(other,"__iter__"))return function(){var __accu0__=self._v;return __call__(__accu0__.__class__,__accu0__,__call__(floor,null,__truediv__(__getitem__(other,0),self._v._x)),__call__(floor,null,__truediv__(__getitem__(other,1),self._v._y)))}();else return self._v.__class__(floor(other/self._v._x),floor(other/self._v._y))})},get __rpow__(){return __get__(this,function(self,other){if(hasattr(other,"_x")){if(other._x<0&&__mod__(self._v._x,1)||other._y<
0&&__mod__(self._v._y,1)){var __except0__=ValueError("negative number cannot be raised to a fractional power");__except0__.__cause__=null;throw __except0__;}return self._v.__class__(Math.pow(other._x,self._v._x),Math.pow(other._y,self._v._y))}else if(hasattr(other,"__iter__")){if(__lt__(__getitem__(other,0),0)&&__mod__(self._v._x,1)||__lt__(__getitem__(other,1),0)&&__mod__(self._v._y,1)){var __except0__=__call__(ValueError,null,"negative number cannot be raised to a fractional power");__except0__.__cause__=
null;throw __except0__;}return function(){var __accu0__=self._v;return __call__(__accu0__.__class__,__accu0__,__pow__(__getitem__(other,0),self._v._x),__pow__(__getitem__(other,1),self._v._y))}()}else{if(other<0&&(__mod__(self._v._x,1)||__mod__(self._v._y,1))){var __except0__=ValueError("negative number cannot be raised to a fractional power");__except0__.__cause__=null;throw __except0__;}return self._v.__class__(Math.pow(other,self._v._x),Math.pow(other,self._v._y))}})},get __rmod__(){return __get__(this,
function(self,other){if(hasattr(other,"_x"))return self._v.__class__(__mod__(other._x,self._v._x),__mod__(other._y,self._v._y));else if(hasattr(other,"__iter__"))return function(){var __accu0__=self._v;return __call__(__accu0__.__class__,__accu0__,__mod__(__getitem__(other,0),self._v._x),__mod__(__getitem__(other,1),self._v._y))}();else return self._v.__class__(__mod__(other,self._v._x),__mod__(other,self._v._y))})}});

//# sourceMappingURL=pyjsdl.vector.map