$pyjs.loaded_modules["interface"]=function(A){if($pyjs.loaded_modules["interface"].__was_initialized__)return $pyjs.loaded_modules["interface"];var l=$pyjs.loaded_modules["interface"];l.__repr__=function(){return"<module: interface>"};l.__was_initialized__=!0;if(null===A||"undefined"==typeof A)A="interface";l.__name__=A;l.env=$p.___import___("env",null);l.pygame=l.env.engine;l.interphase=l.env["interface"];l.MatrixInterface=function(){var n={},g;n.__module__="interface";g=$pyjs__bind_method2("__init__",
function(b,e){if(!0===this.__is_instance__)var a=this;else a=b,b=e;var f,c,d;a.matrix=b;$pyjs_kwargs_call(l.interphase.Interface,"__init__",null,null,[{position:$p.tuple([Math.floor(a.matrix.width*l.env.size/2),a.matrix.height*l.env.size-47]),color:$p.tuple([15,30,50]),size:$p.tuple([350,96]),control_minsize:$p.tuple([41,41]),control_size:"auto",control_response:100,moveable:!1,position_offset:$p.tuple([0,88]),font_color:$p.tuple([50,150,200]),button_image:"button.png",scroll_button:"vertical"},a]);
l.pygame.draw.rect(a.get_panel_image(!0),$p.tuple([50,60,100]),$p.tuple([162,28,178,48]),1);f=l.pygame.Surface($p.tuple([100,100]),l.pygame.SRCALPHA);f.fill($p.tuple([50,50,50,150]));$pyjs_kwargs_call(a,"set_control_image",null,null,[{surface:f}]);a.dir=$p.dict([["N",$p.tuple([0,-1])],["S",$p.tuple([0,1])],["W",$p.tuple([-1,0])],["E",$p.tuple([1,0])],["NW",$p.tuple([-1,-1])],["NE",$p.tuple([1,-1])],["SW",$p.tuple([-1,1])],["SE",$p.tuple([1,1])]]);f=$p.__ass_unpack(a.get_size(),2,null);a.width=f[0];
a.height=f[1];a.set_moveable();a.set_moveable("Fixed");a.panel_up=!0;if(null===(d="js"===(c=l.env.platform)&&null===c?!0:null===c?!1:"object"!=typeof c&&"function"!=typeof c||"function"!=typeof c.__cmp__?"js"==c:0===c.__cmp__("js"))||!1===d||0===d||""===d?0:"object"==typeof d?"function"==typeof d.__nonzero__?d.__nonzero__():"function"==typeof d.__len__?0<d.__len__():1:1)a.add_controls_js(),l.pygame.display.textbox_init();return null},1,[null,null,["self"],["matrix"]]);n.__init__=g;g=$pyjs__bind_method2("add_controls",
function(b){b=!0===this.__is_instance__?this:b;var e,a,f,c,d,q,h,l,k;$pyjs_kwargs_call(b,"add",null,null,[{identity:"Reset",control_type:"control_toggle",position:$p.tuple([26,19]),size:"min_width",control_list:$p.list(["Reset"]),tip_list:$p.list(["Reset matrix"]),control_outline:!0}]);$pyjs_kwargs_call(b,"add",null,null,[{identity:"Clear",control_type:"control_toggle",position:$p.tuple([26,39]),size:"min_width",control_list:$p.list(["Clear"]),tip_list:$p.list(["Clear matrix"]),control_outline:!0}]);
$pyjs_kwargs_call(b,"add",null,null,[{identity:"Edit",control_type:"control_toggle",position:$p.tuple([26,59]),size:"min_width",control_list:$p.list(["Edit"]),tip_list:$p.list(["Edit matrix"]),control_response:0,control_outline:!0,activated_toggle:"lock"}]);$pyjs_kwargs_call(b,"add",null,null,[{identity:"PatternLoad",control_type:"control_toggle",position:$p.tuple([235,86]),size:"auto_width",control_list:$p.list(["LOAD"]),font_size:8,tip_list:$p.list(["Retrieve from file"]),control_response:0,control_outline:!0}]);
$pyjs_kwargs_call(b,"add",null,null,[{identity:"PatternGet",control_type:"control_toggle",position:$p.tuple([265,86]),size:"auto_width",control_list:$p.list(["GET"]),font_size:8,tip_list:$p.list(["Retrieve from clipboard"]),control_response:0,control_outline:!0}]);$pyjs_kwargs_call(b,"add",null,null,[{identity:"Patterns",control_type:"control_select",position:$p.tuple([250,18]),size:$p.tuple([64,18]),control_list:$p.list(["Patterns"]),tip_list:$p.list(["Game of Life Patterns"]),activated_toggle:!1,
control_response:200,control_outline:!0,split_text:!1}]);$pyjs_kwargs_call(b,"add",null,null,[{identity:"PatternInfo",control_type:"textbox",position:$p.tuple([251,52]),size:$p.tuple([176,46]),color:$p.tuple([50,50,50]),font_color:$p.tuple([255,255,255]),font_type:"courier",font_size:8,control_list:$p.list([]),tip_list:$p.list(["Pattern Information"]),activated_toggle:!1,control_outline:!0}]);$pyjs_kwargs_call(b,"add",null,null,[{identity:"Rate",control_type:"control_select",position:$p.tuple([26,
79]),size:"min_width",control_list:$p.list(["Rate 1","Rate 2","Rate 3","Rate 4"]),tip_list:$p.list(["Processing rate"]),split_text:!1,control_response:200,control_outline:!0,reverse:!0}]);q=$p.tuple([$p.tuple(["N",$p.list(["North"]),$p.list(["control_n.png"]),$p.tuple([111,25])]),$p.tuple(["S",$p.list(["South"]),$p.list(["control_s.png"]),$p.tuple([111,75])]),$p.tuple(["W",$p.list(["West"]),$p.list(["control_w.png"]),$p.tuple([86,50])]),$p.tuple(["E",$p.list(["East"]),$p.list(["control_e.png"]),$p.tuple([136,
50])])]);"undefined"!=typeof(h=q.__array)?e=0:(q=q.__iter__(),e="undefined"!=typeof(h=q.__array)?0:"function"==typeof q.$genfunc?1:-1);for(k=0;"undefined"!=typeof(a=e?0<e?q.next(!0,!1):$p.wrapped_next(q):h[k++]);)d=$p.__ass_unpack(a,4,null),a=d[0],c=d[1],f=d[2],d=d[3],$pyjs_kwargs_call(b,"add",null,null,[{identity:a,control_type:"control_toggle",position:d,size:$p.tuple([25,25]),control_list:$p.list([""]),tip_list:c,control_image:f,control_response:25}]);e=$p.tuple([$p.tuple(["NW",$p.list(["North-West"]),
$p.tuple([86,25])]),$p.tuple(["NE",$p.list(["North-East"]),$p.tuple([136,25])]),$p.tuple(["SW",$p.list(["South-West"]),$p.tuple([86,75])]),$p.tuple(["SE",$p.list(["South-East"]),$p.tuple([136,75])]),$p.tuple(["X",$p.list(["Center"]),$p.tuple([111,50])])]);"undefined"!=typeof(k=e.__array)?h=0:(e=e.__iter__(),h="undefined"!=typeof(k=e.__array)?0:"function"==typeof e.$genfunc?1:-1);for(q=0;"undefined"!=typeof(a=h?0<h?e.next(!0,!1):$p.wrapped_next(e):k[q++]);)d=$p.__ass_unpack(a,3,null),a=d[0],c=d[1],
d=d[2],$pyjs_kwargs_call(b,"add",null,null,[{identity:a,control_type:"control_toggle",position:d,size:$p.tuple([25,25]),control_list:$p.list([""]),tip_list:c,control_response:25}]);$pyjs_kwargs_call(b,"add",null,null,[{identity:"__TopFix",control_type:"control_toggle",position:$p.tuple([Math.floor(("undefined"!=typeof(l=b.get_size()).__array?"undefined"!=typeof l.__array[0]?l.__array[0]:l.__getitem__(0):l.__getitem__(0))/2),4]),size:$p.tuple([340,8]),control_list:$p.list([""]),control_image:"none",
control_response:0,control_outline:!1}]);$pyjs_kwargs_call(b,"add",null,null,[{identity:"__Fix",control_type:"control_toggle",position:$p.tuple([324,86]),color:$p.tuple([0,20,30]),font_color:$p.tuple([0,120,160]),font_size:8,control_list:$p.list(["!"]),control_response:0,control_outline:!0}]);$pyjs_kwargs_call(b,"add",null,null,[{identity:"__Help",control_type:"control_toggle",position:$p.tuple([340,86]),color:$p.tuple([0,20,30]),font_color:$p.tuple([0,120,160]),font_size:8,control_list:$p.list(["?"]),
control_response:0,control_outline:!0}]);b.ctrl_patterns=b.get_control("Patterns");b.ctrl_patterninfo=b.get_control("PatternInfo");b.ctrl_patterninfo.set_active(!1);b.ctrl_topfix=b.get_control("__TopFix");b.ctrl_topfix.set_enabled(!1);return null},1,[null,null,["self"]]);n.add_controls=g;g=$pyjs__bind_method2("add_controls_js",function(b){$pyjs_kwargs_call(!0===this.__is_instance__?this:b,"add",null,null,[{identity:"Textbox",control_type:"control_toggle",position:$p.tuple([280,86]),size:"auto_width",
control_list:$p.list(["v","^"]),font_size:8,tip_list:$p.list(["Toggle Textbox"]),control_response:0,control_outline:!0}]);return null},1,[null,null,["self"]]);n.add_controls_js=g;g=$pyjs__bind_method2("load_pattern",function(b){b=!0===this.__is_instance__?this:b;var e,a,f,c,d,q;if(null===(c=!(null===(e="js"===(f=l.env.platform)&&null===f?!0:null===f?!1:"object"!=typeof f&&"function"!=typeof f||"function"!=typeof f.__cmp__?"js"==f:0===f.__cmp__("js"))||!1===e||0===e||""===e?0:"object"==typeof e?"function"==
typeof e.__nonzero__?e.__nonzero__():"function"==typeof e.__len__?0<e.__len__():1:1))||!1===c||0===c||""===c?0:"object"==typeof c?"function"==typeof c.__nonzero__?c.__nonzero__():"function"==typeof c.__len__?0<c.__len__():1:1)try{q=$p.open("pattern.txt"),a=q.read(),q.close()}catch(h){if(e="undefined"==typeof h.__name__?h.name:h.__name__,$pyjs.__last_exception__={error:h,module:l},e==("undefined"==typeof IOError?l.IOError:IOError).__name__||$p._isinstance(h,"undefined"==typeof IOError?l.IOError:IOError))try{a=
$p.___import___("pattern.patterns",null,null,!1)}catch(g){e="undefined"==typeof g.__name__?g.name:g.__name__;$pyjs.__last_exception__={error:g,module:l};if(e==$p.ImportError.__name__||$p._isinstance(g,$p.ImportError))return null;$pyjs.__active_exception_stack__=$pyjs.__last_exception_stack__;$pyjs.__last_exception_stack__=null;throw g;}else throw $pyjs.__active_exception_stack__=$pyjs.__last_exception_stack__,$pyjs.__last_exception_stack__=null,h;}else try{a=$p.___import___("pattern.patterns",null,
null,!1)}catch(k){e="undefined"==typeof k.__name__?k.name:k.__name__;$pyjs.__last_exception__={error:k,module:l};if(e==$p.ImportError.__name__||$p._isinstance(k,$p.ImportError))return null;$pyjs.__active_exception_stack__=$pyjs.__last_exception_stack__;$pyjs.__last_exception_stack__=null;throw k;}(null===(d=a)||!1===d||0===d||""===d?0:"object"==typeof d?"function"==typeof d.__nonzero__?d.__nonzero__():"function"==typeof d.__len__?0<d.__len__():1:1)&&b.register_pattern(a);return null},1,[null,null,
["self"]]);n.load_pattern=g;g=$pyjs__bind_method2("retrieve_pattern",function(b){b=!0===this.__is_instance__?this:b;var e;e=b.get_clipboard();(null===e||!1===e||0===e||""===e?0:"object"==typeof e?"function"==typeof e.__nonzero__?e.__nonzero__():"function"==typeof e.__len__?0<e.__len__():1:1)&&b.register_pattern(e);return null},1,[null,null,["self"]]);n.retrieve_pattern=g;g=$pyjs__bind_method2("register_pattern",function(b,e){if(!0===this.__is_instance__)var a=this;else a=b,b=e;var f,c,d,q,h,l,k,g,
u,v,x,r,s,t,n,y,w,p,m,z;m=a.matrix.pattern_id;k=$p.list([]);u=b.$$split("\n");"undefined"!=typeof(n=u.__array)?q=0:(u=u.__iter__(),q="undefined"!=typeof(n=u.__array)?0:"function"==typeof u.$genfunc?1:-1);for(l=0;w="undefined"!=typeof(z=q?0<q?u.next(!0,!1):$p.wrapped_next(u):n[l++]);)if(w=z,!(null===(s=w.startswith("//"))||!1===s||0===s||""===s?0:"object"==typeof s?"function"==typeof s.__nonzero__?s.__nonzero__():"function"==typeof s.__len__?0<s.__len__():1:1))if(null===(t=w.strip())||!1===t||0===
t||""===t?0:"object"==typeof t?"function"==typeof t.__nonzero__?t.__nonzero__():"function"==typeof t.__len__?0<t.__len__():1:1)k.append(w);else if(null===(h=k)||!1===h||0===h||""===h?0:"object"==typeof h?"function"==typeof h.__nonzero__?h.__nonzero__():"function"==typeof h.__len__?0<h.__len__():1:1)a.set_pattern("\n".join(k)),$p.__setslice(k,0,null,$p.list([]));!w&&(null===k||!1===k||0===k||""===k?0:"object"==typeof k?"function"==typeof k.__nonzero__?k.__nonzero__():"function"==typeof k.__len__?0<
k.__len__():1:1)&&a.set_pattern("\n".join(k));if(null===(f=(r=a.matrix.pattern_id)===m&&null===r?!0:null===r?!1:null===m?!1:"object"!=typeof r&&"function"!=typeof r||"function"!=typeof r.__cmp__?"object"!=typeof m&&"function"!=typeof m||"function"!=typeof m.__cmp__?r==m:0===m.__cmp__(r):0===r.__cmp__(m))||!1===f||0===f||""===f?0:"object"==typeof f?"function"==typeof f.__nonzero__?f.__nonzero__():"function"==typeof f.__len__?0<f.__len__():1:1)return null;(null===(d=!(null===(c=a.ctrl_patterninfo.is_active())||
!1===c||0===c||""===c?0:"object"==typeof c?"function"==typeof c.__nonzero__?c.__nonzero__():"function"==typeof c.__len__?0<c.__len__():1:1))||!1===d||0===d||""===d?0:"object"==typeof d?"function"==typeof d.__nonzero__?d.__nonzero__():"function"==typeof d.__len__?0<d.__len__():1:1)&&a.ctrl_patterninfo.set_active(!0);(null===(v=a.ctrl_patterns.is_activated())||!1===v||0===v||""===v?0:"object"==typeof v?"function"==typeof v.__nonzero__?v.__nonzero__():"function"==typeof v.__len__?0<v.__len__():1:1)&&
a.ctrl_patterns.set_activated(!1);a.ctrl_patterns.set_tip($p.list(["Game of Life Patterns"]));(null===m||!1===m||0===m||""===m?0:"object"==typeof m?"function"==typeof m.__nonzero__?m.__nonzero__():"function"==typeof m.__len__?0<m.__len__():1:1)?a.ctrl_patterns.set_list_index(m):a.ctrl_patterns.reset();a.ctrl_patterninfo.set_value("undefined"!=typeof(x=a.matrix.patterns).__array?"undefined"!=typeof x.__array[y=$p.float_int("undefined"!=typeof(p=a.ctrl_patterns.get_value().$$split(" ")).__array?"undefined"!=
typeof p.__array[g=-1]?p.__array[g]:p.__getitem__(g):p.__getitem__(-1))]?x.__array[y]:x.__getitem__(y):x.__getitem__($p.float_int("undefined"!=typeof(p=a.ctrl_patterns.get_value().$$split(" ")).__array?"undefined"!=typeof p.__array[g=-1]?p.__array[g]:p.__getitem__(g):p.__getitem__(-1))));return null},1,[null,null,["self"],["patterns"]]);n.register_pattern=g;g=$pyjs__bind_method2("set_pattern",function(b,e){if(!0===this.__is_instance__)var a=this;else a=b,b=e;var f,c;a.matrix.pattern_id+=1;a.matrix.patterns.__setitem__(a.matrix.pattern_id,
b);(null===(c=1==(1===(f=a.matrix.pattern_id)?0:"number"!=typeof f||"number"!=typeof f&&"string"!=typeof f&&"boolean"!=typeof f?$p.cmp(f,1):1==f?0:1>f?-1:1))||!1===c||0===c||""===c?0:"object"==typeof c?"function"==typeof c.__nonzero__?c.__nonzero__():"function"==typeof c.__len__?0<c.__len__():1:1)?$pyjs_kwargs_call(a.ctrl_patterns,"set_list",null,null,[{append:!0},$p.list(["Pattern "+$p.str(a.matrix.pattern_id)])]):a.ctrl_patterns.set_list($p.list(["Pattern "+$p.str(a.matrix.pattern_id)]));return null},
1,[null,null,["self"],["pattern"]]);n.set_pattern=g;g=$pyjs__bind_method2("get_pattern",function(b){b=!0===this.__is_instance__?this:b;var e,a,f,c,d,g,h;return(null===(d=(null===(c=f=b.matrix.patterns)||!1===c||0===c||""===c?0:"object"==typeof c?"function"==typeof c.__nonzero__?c.__nonzero__():"function"==typeof c.__len__?0<c.__len__():1:1)?b.ctrl_patterns.is_activated():f)||!1===d||0===d||""===d?0:"object"==typeof d?"function"==typeof d.__nonzero__?d.__nonzero__():"function"==typeof d.__len__?0<
d.__len__():1:1)?"undefined"!=typeof(g=b.matrix.patterns).__array?"undefined"!=typeof g.__array[e=$p.float_int("undefined"!=typeof(h=b.ctrl_patterns.value.$$split(" ")).__array?"undefined"!=typeof h.__array[a=-1]?h.__array[a]:h.__getitem__(a):h.__getitem__(-1))]?g.__array[e]:g.__getitem__(e):g.__getitem__($p.float_int("undefined"!=typeof(h=b.ctrl_patterns.value.$$split(" ")).__array?"undefined"!=typeof h.__array[a=-1]?h.__array[a]:h.__getitem__(a):h.__getitem__(-1))):null},1,[null,null,["self"]]);
n.get_pattern=g;g=$pyjs__bind_method2("edit_enable",function(b){if(!0===this.__is_instance__)var e=this;else e=arguments[0],b=arguments[1];"undefined"==typeof b&&(b=arguments.callee.__args__[3][1]);var a,f,c,d,e=e.get_control("Edit");(null===(a=b)||!1===a||0===a||""===a?0:"object"==typeof a?"function"==typeof a.__nonzero__?a.__nonzero__():"function"==typeof a.__len__?0<a.__len__():1:1)?(null===(d=!(null===(f=e.is_activated())||!1===f||0===f||""===f?0:"object"==typeof f?"function"==typeof f.__nonzero__?
f.__nonzero__():"function"==typeof f.__len__?0<f.__len__():1:1))||!1===d||0===d||""===d?0:"object"==typeof d?"function"==typeof d.__nonzero__?d.__nonzero__():"function"==typeof d.__len__?0<d.__len__():1:1)&&e.set_activated(!0):(null===(c=e.is_activated())||!1===c||0===c||""===c?0:"object"==typeof c?"function"==typeof c.__nonzero__?c.__nonzero__():"function"==typeof c.__len__?0<c.__len__():1:1)&&e.set_activated(!1);return null},1,[null,null,["self"],["setting",!0]]);n.edit_enable=g;g=$pyjs__bind_method2("update",
function(b){b=!0===this.__is_instance__?this:b;var e,a,f,c,d,g,h,n,k,C,u,v,x,r,s,t,D,y,w,p,m,z,E,F,G,H,I,A,B,M,N,O,L,P,R,Q,J,K;a=l.interphase.Interface.update(b);if(null===(u=a.control)||!1===u||0===u||""===u?0:"object"==typeof u?"function"==typeof u.__nonzero__?u.__nonzero__():"function"==typeof u.__len__?0<u.__len__():1:1)(null===(C=$p.tuple("N S W E NW NE SW SE".split(" ")).__contains__(a.control))||!1===C||0===C||""===C?0:"object"==typeof C?"function"==typeof C.__nonzero__?C.__nonzero__():"function"==
typeof C.__len__?0<C.__len__():1:1)?b.matrix.view_scroll("undefined"!=typeof(O=b.dir).__array?"undefined"!=typeof O.__array[L=a.control]?O.__array[L]:O.__getitem__(L):O.__getitem__(a.control)):(null===(h="X"===(K=a.control)&&null===K?!0:null===K?!1:"object"!=typeof K&&"function"!=typeof K||"function"!=typeof K.__cmp__?"X"==K:0===K.__cmp__("X"))||!1===h||0===h||""===h?0:"object"==typeof h?"function"==typeof h.__nonzero__?h.__nonzero__():"function"==typeof h.__len__?0<h.__len__():1:1)?b.matrix.view_reset():
(null===(g="Reset"===(J=a.control)&&null===J?!0:null===J?!1:"object"!=typeof J&&"function"!=typeof J||"function"!=typeof J.__cmp__?"Reset"==J:0===J.__cmp__("Reset"))||!1===g||0===g||""===g?0:"object"==typeof g?"function"==typeof g.__nonzero__?g.__nonzero__():"function"==typeof g.__len__?0<g.__len__():1:1)?b.matrix.reset_matrix():(null===(k="Clear"===(G=a.control)&&null===G?!0:null===G?!1:"object"!=typeof G&&"function"!=typeof G||"function"!=typeof G.__cmp__?"Clear"==G:0===G.__cmp__("Clear"))||!1===
k||0===k||""===k?0:"object"==typeof k?"function"==typeof k.__nonzero__?k.__nonzero__():"function"==typeof k.__len__?0<k.__len__():1:1)?b.matrix.clear_matrix():(null===(n="Edit"===(H=a.control)&&null===H?!0:null===H?!1:"object"!=typeof H&&"function"!=typeof H||"function"!=typeof H.__cmp__?"Edit"==H:0===H.__cmp__("Edit"))||!1===n||0===n||""===n?0:"object"==typeof n?"function"==typeof n.__nonzero__?n.__nonzero__():"function"==typeof n.__len__?0<n.__len__():1:1)?(null===(r=("undefined"!=typeof(P=a.controls).__array?
"undefined"!=typeof P.__array[A=a.control]?P.__array[A]:P.__getitem__(A):P.__getitem__(a.control)).is_activated())||!1===r||0===r||""===r?0:"object"==typeof r?"function"==typeof r.__nonzero__?r.__nonzero__():"function"==typeof r.__len__?0<r.__len__():1:1)?b.matrix.edit_matrix():b.matrix.activate():(null===(x="Patterns"===(I=a.control)&&null===I?!0:null===I?!1:"object"!=typeof I&&"function"!=typeof I||"function"!=typeof I.__cmp__?"Patterns"==I:0===I.__cmp__("Patterns"))||!1===x||0===x||""===x?0:"object"==
typeof x?"function"==typeof x.__nonzero__?x.__nonzero__():"function"==typeof x.__len__?0<x.__len__():1:1)?(null===(D=b.matrix.patterns)||!1===D||0===D||""===D?0:"object"==typeof D?"function"==typeof D.__nonzero__?D.__nonzero__():"function"==typeof D.__len__?0<D.__len__():1:1)?b.ctrl_patterninfo.set_value("undefined"!=typeof(N=b.matrix.patterns).__array?"undefined"!=typeof N.__array[R=$p.float_int("undefined"!=typeof(B=a.value.$$split(" ")).__array?"undefined"!=typeof B.__array[M=-1]?B.__array[M]:
B.__getitem__(M):B.__getitem__(-1))]?N.__array[R]:N.__getitem__(R):N.__getitem__($p.float_int("undefined"!=typeof(B=a.value.$$split(" ")).__array?"undefined"!=typeof B.__array[M=-1]?B.__array[M]:B.__getitem__(M):B.__getitem__(-1)))):b.ctrl_patterns.set_activated(!1):(null===(y="PatternLoad"===(v=a.control)&&null===v?!0:null===v?!1:"object"!=typeof v&&"function"!=typeof v||"function"!=typeof v.__cmp__?"PatternLoad"==v:0===v.__cmp__("PatternLoad"))||!1===y||0===y||""===y?0:"object"==typeof y?"function"==
typeof y.__nonzero__?y.__nonzero__():"function"==typeof y.__len__?0<y.__len__():1:1)?b.load_pattern():(null===(s="PatternGet"===(e=a.control)&&null===e?!0:null===e?!1:"object"!=typeof e&&"function"!=typeof e||"function"!=typeof e.__cmp__?"PatternGet"==e:0===e.__cmp__("PatternGet"))||!1===s||0===s||""===s?0:"object"==typeof s?"function"==typeof s.__nonzero__?s.__nonzero__():"function"==typeof s.__len__?0<s.__len__():1:1)?b.retrieve_pattern():(null===(t="Textbox"===(f=a.control)&&null===f?!0:null===
f?!1:"object"!=typeof f&&"function"!=typeof f||"function"!=typeof f.__cmp__?"Textbox"==f:0===f.__cmp__("Textbox"))||!1===t||0===t||""===t?0:"object"==typeof t?"function"==typeof t.__nonzero__?t.__nonzero__():"function"==typeof t.__len__?0<t.__len__():1:1)?l.pygame.display.textarea.toggle():(null===(m="Rate"===(c=a.control)&&null===c?!0:null===c?!1:"object"!=typeof c&&"function"!=typeof c||"function"!=typeof c.__cmp__?"Rate"==c:0===c.__cmp__("Rate"))||!1===m||0===m||""===m?0:"object"==typeof m?"function"==
typeof m.__nonzero__?m.__nonzero__():"function"==typeof m.__len__?0<m.__len__():1:1)?b.matrix.set_tick($p.float_int("undefined"!=typeof(Q=a.value.$$split(" ")).__array?"undefined"!=typeof Q.__array[-1]?Q.__array[-1]:Q.__getitem__(-1):Q.__getitem__(-1))):(null===(z=$p.tuple(["__Fix","__TopFix"]).__contains__(a.control))||!1===z||0===z||""===z?0:"object"==typeof z?"function"==typeof z.__nonzero__?z.__nonzero__():"function"==typeof z.__len__?0<z.__len__():1:1)?(b.set_moveable("Fixed"),b.panel_up=!(null===
(w=b.panel_up)||!1===w||0===w||""===w?0:"object"==typeof w?"function"==typeof w.__nonzero__?w.__nonzero__():"function"==typeof w.__len__?0<w.__len__():1:1),(null===(p=b.panel_up)||!1===p||0===p||""===p?0:"object"==typeof p?"function"==typeof p.__nonzero__?p.__nonzero__():"function"==typeof p.__len__?0<p.__len__():1:1)?b.ctrl_topfix.set_enabled(!1):b.ctrl_topfix.set_enabled(!0)):(null===(E="__Help"===(d=a.control)&&null===d?!0:null===d?!1:"object"!=typeof d&&"function"!=typeof d||"function"!=typeof d.__cmp__?
"__Help"==d:0===d.__cmp__("__Help"))||!1===E||0===E||""===E?0:"object"==typeof E?"function"==typeof E.__nonzero__?E.__nonzero__():"function"==typeof E.__len__?0<E.__len__():1:1)&&b.set_tips_display(),b.matrix.panel_update=!0;if(null===(F=a.panel_update)||!1===F||0===F||""===F?0:"object"==typeof F?"function"==typeof F.__nonzero__?F.__nonzero__():"function"==typeof F.__len__?0<F.__len__():1:1)b.matrix.panel_update=!0;return null},1,[null,null,["self"]]);n.update=g;g=Array(l.interphase.Interface);var A=
$p.dict(),L;for(L in n)A.__setitem__(L,n[L]);return $p._create_class("MatrixInterface",$p.tuple(g),A)}();return this};
