$pyjs.loaded_modules["pyjsdl.color"]=function(da){if($pyjs.loaded_modules["pyjsdl.color"].__was_initialized__)return $pyjs.loaded_modules["pyjsdl.color"];"undefined"!=typeof $pyjs.loaded_modules.pyjsdl&&$pyjs.loaded_modules.pyjsdl.__was_initialized__||$p.___import___("pyjsdl",null);var ea=$pyjs.loaded_modules["pyjsdl.color"];ea.__repr__=function(){return"<module: pyjsdl.color>"};ea.__was_initialized__=!0;if(null===da||"undefined"==typeof da)da="pyjsdl.color";ea.__name__=da;$pyjs.loaded_modules.pyjsdl.color=
$pyjs.loaded_modules["pyjsdl.color"];ea._Color=$p.___import___("pyjsdl.pyjsobj.Color","pyjsdl",null,!1);ea.__docformat__="restructuredtext";ea.Color=function(){var p={},f;p.__module__="pyjsdl.color";f=$pyjs__bind_method2("__init__",function(){if(!0===this.__is_instance__)var a=this,n=$p.tuple($pyjs_array_slice.call(arguments,0,arguments.length));else a=arguments[0],n=$p.tuple($pyjs_array_slice.call(arguments,1,arguments.length));var b,d,c,e,h,g,A,s,r,f,B,T,U,m,t,q,l,k;d=null===(k=n)?0:"undefined"!=
typeof k.__array?k.__array.length:"function"==typeof k.__len__?k.__len__():"undefined"!=typeof k.length?k.length:$p.len(k);if(null===(s=1===(e=d)&&null===e?!0:null===e?!1:"object"!=typeof e&&"function"!=typeof e||"function"!=typeof e.__cmp__?1==e:0===e.__cmp__(1))||!1===s||0===s||""===s?0:"object"==typeof s?"function"==typeof s.__nonzero__?s.__nonzero__():"function"==typeof s.__len__?0<s.__len__():1:1)if(n="undefined"!=typeof(U=n).__array?"undefined"!=typeof U.__array[0]?U.__array[0]:U.__getitem__(0):
U.__getitem__(0),null===(g=$p.hasattr(n,"__len__"))||!1===g||0===g||""===g?0:"object"==typeof g?"function"==typeof g.__nonzero__?g.__nonzero__():"function"==typeof g.__len__?0<g.__len__():1:1)d=null===(l=n)?0:"undefined"!=typeof l.__array?l.__array.length:"function"==typeof l.__len__?l.__len__():"undefined"!=typeof l.length?l.length:$p.len(l);(null===(A=4===(c=d)&&null===c?!0:null===c?!1:"object"!=typeof c&&"function"!=typeof c||"function"!=typeof c.__cmp__?4==c:0===c.__cmp__(4))||!1===A||0===A||
""===A?0:"object"==typeof A?"function"==typeof A.__nonzero__?A.__nonzero__():"function"==typeof A.__len__?0<A.__len__():1:1)?(m=$p.__ass_unpack($p.tuple(["undefined"!=typeof(T=n).__array?"undefined"!=typeof T.__array[0]?T.__array[0]:T.__getitem__(0):T.__getitem__(0),"undefined"!=typeof(B=n).__array?"undefined"!=typeof B.__array[1]?B.__array[1]:B.__getitem__(1):B.__getitem__(1),"undefined"!=typeof(f=n).__array?"undefined"!=typeof f.__array[2]?f.__array[2]:f.__getitem__(2):f.__getitem__(2),"undefined"!=
typeof(r=n).__array?"undefined"!=typeof r.__array[3]?r.__array[3]:r.__getitem__(3):r.__getitem__(3)]),4,null),a.r=m[0],a.g=m[1],a.b=m[2],a.a=m[3]):(r=(null===(b=3===(h=d)&&null===h?!0:null===h?!1:"object"!=typeof h&&"function"!=typeof h||"function"!=typeof h.__cmp__?3==h:0===h.__cmp__(3))||!1===b||0===b||""===b?0:"object"==typeof b?"function"==typeof b.__nonzero__?b.__nonzero__():"function"==typeof b.__len__?0<b.__len__():1:1)?$p.__ass_unpack($p.tuple(["undefined"!=typeof(t=n).__array?"undefined"!=
typeof t.__array[0]?t.__array[0]:t.__getitem__(0):t.__getitem__(0),"undefined"!=typeof(q=n).__array?"undefined"!=typeof q.__array[1]?q.__array[1]:q.__getitem__(1):q.__getitem__(1),"undefined"!=typeof(m=n).__array?"undefined"!=typeof m.__array[2]?m.__array[2]:m.__getitem__(2):m.__getitem__(2),255]),4,null):$p.__ass_unpack($p.tuple([n>>16&255,n>>8&255,n&255,n>>24&255]),4,null),a.r=r[0],a.g=r[1],a.b=r[2],a.a=r[3]);return null},1,["color",null,["self"]]);p.__init__=f;f=$pyjs__bind_method2("__repr__",
function(a){a=!0===this.__is_instance__?this:a;return $p.sprintf("(%d,%d,%d,%d)",$p.tuple([a.r,a.g,a.b,a.a]))},1,[null,null,["self"]]);p.__repr__=f;f=$pyjs__bind_method2("__str__",function(a){a=!0===this.__is_instance__?this:a;return $p.sprintf("rgba(%d,%d,%d,%f)",$p.tuple([a.r,a.g,a.b,a.a/255]))},1,[null,null,["self"]]);p.__str__=f;f=$pyjs__bind_method2("__getitem__",function(a,n){if(!0===this.__is_instance__)var b=this;else b=a,a=n;var d,c;return"undefined"!=typeof(d=$p.dict([[0,b.r],[1,b.g],[2,
b.b],[3,b.a]])).__array?"undefined"!=typeof d.__array[c=a]?d.__array[c]:d.__getitem__(c):d.__getitem__(a)},1,[null,null,["self"],["index"]]);p.__getitem__=f;f=$pyjs__bind_method2("__setitem__",function(a,n,b){if(!0===this.__is_instance__)var d=this;else d=a,a=n,n=b;var c,e;d.__setattr__("undefined"!=typeof(c=$p.dict([[0,"r"],[1,"g"],[2,"b"],[3,"a"]])).__array?"undefined"!=typeof c.__array[e=a]?c.__array[e]:c.__getitem__(e):c.__getitem__(a),n);return null},1,[null,null,["self"],["index"],["val"]]);
p.__setitem__=f;f=$pyjs__bind_method2("__iter__",function(a){a=!0===this.__is_instance__?this:a;return $p.iter($p.list([a.r,a.g,a.b,a.a]))},1,[null,null,["self"]]);p.__iter__=f;f=$pyjs__bind_method2("__len__",function(a){return 4},1,[null,null,["self"]]);p.__len__=f;f=$pyjs__bind_method2("__eq__",function(a,n){if(!0===this.__is_instance__)var b=this;else b=a,a=n;var d,c,e,h,g,f,s,r,p,B,T,U,m,t,q,l,k,J,u,K,v,L,C,w,D,x,y,E,z,M,V,N,O,W,X,Y,Z,$,aa,ba,F,G,P,ca,Q,R,H,S,I;return(null===(y=$p.hasattr(a,"a"))||
!1===y||0===y||""===y?0:"object"==typeof y?"function"==typeof y.__nonzero__?y.__nonzero__():"function"==typeof y.__len__?0<y.__len__():1:1)?(null===(H=s=(P=b.r)===(F=a.r)&&null===P?!0:null===P?!1:null===F?!1:"object"!=typeof P&&"function"!=typeof P||"function"!=typeof P.__cmp__?"object"!=typeof F&&"function"!=typeof F||"function"!=typeof F.__cmp__?P==F:0===F.__cmp__(P):0===P.__cmp__(F))||!1===H||0===H||""===H?0:"object"==typeof H?"function"==typeof H.__nonzero__?H.__nonzero__():"function"==typeof H.__len__?
0<H.__len__():1:1)?(null===(I=r=(G=b.g)===(M=a.g)&&null===G?!0:null===G?!1:null===M?!1:"object"!=typeof G&&"function"!=typeof G||"function"!=typeof G.__cmp__?"object"!=typeof M&&"function"!=typeof M||"function"!=typeof M.__cmp__?G==M:0===M.__cmp__(G):0===G.__cmp__(M))||!1===I||0===I||""===I?0:"object"==typeof I?"function"==typeof I.__nonzero__?I.__nonzero__():"function"==typeof I.__len__?0<I.__len__():1:1)?(null===(C=p=(V=b.b)===(N=a.b)&&null===V?!0:null===V?!1:null===N?!1:"object"!=typeof V&&"function"!=
typeof V||"function"!=typeof V.__cmp__?"object"!=typeof N&&"function"!=typeof N||"function"!=typeof N.__cmp__?V==N:0===N.__cmp__(V):0===V.__cmp__(N))||!1===C||0===C||""===C?0:"object"==typeof C?"function"==typeof C.__nonzero__?C.__nonzero__():"function"==typeof C.__len__?0<C.__len__():1:1)?(O=b.a)===(W=a.a)&&null===O?!0:null===O?!1:null===W?!1:"object"!=typeof O&&"function"!=typeof O||"function"!=typeof O.__cmp__?"object"!=typeof W&&"function"!=typeof W||"function"!=typeof W.__cmp__?O==W:0===W.__cmp__(O):
0===O.__cmp__(W):p:r:s:(null===(w=4===(X=null===(Y=a)?0:"undefined"!=typeof Y.__array?Y.__array.length:"function"==typeof Y.__len__?Y.__len__():"undefined"!=typeof Y.length?Y.length:$p.len(Y))&&null===X?!0:null===X?!1:"object"!=typeof X&&"function"!=typeof X||"function"!=typeof X.__cmp__?4==X:0===X.__cmp__(4))||!1===w||0===w||""===w?0:"object"==typeof w?"function"==typeof w.__nonzero__?w.__nonzero__():"function"==typeof w.__len__?0<w.__len__():1:1)?(null===(d=B=(z=b.a)===(D="undefined"!=typeof($=
a).__array?"undefined"!=typeof $.__array[3]?$.__array[3]:$.__getitem__(3):$.__getitem__(3))&&null===z?!0:null===z?!1:null===D?!1:"object"!=typeof z&&"function"!=typeof z||"function"!=typeof z.__cmp__?"object"!=typeof D&&"function"!=typeof D||"function"!=typeof D.__cmp__?z==D:0===D.__cmp__(z):0===z.__cmp__(D))||!1===d||0===d||""===d?0:"object"==typeof d?"function"==typeof d.__nonzero__?d.__nonzero__():"function"==typeof d.__len__?0<d.__len__():1:1)?(null===(c=T=(x=b.r)===(t="undefined"!=typeof(S=a).__array?
"undefined"!=typeof S.__array[0]?S.__array[0]:S.__getitem__(0):S.__getitem__(0))&&null===x?!0:null===x?!1:null===t?!1:"object"!=typeof x&&"function"!=typeof x||"function"!=typeof x.__cmp__?"object"!=typeof t&&"function"!=typeof t||"function"!=typeof t.__cmp__?x==t:0===t.__cmp__(x):0===x.__cmp__(t))||!1===c||0===c||""===c?0:"object"==typeof c?"function"==typeof c.__nonzero__?c.__nonzero__():"function"==typeof c.__len__?0<c.__len__():1:1)?(null===(e=U=(m=b.g)===(l="undefined"!=typeof(aa=a).__array?
"undefined"!=typeof aa.__array[1]?aa.__array[1]:aa.__getitem__(1):aa.__getitem__(1))&&null===m?!0:null===m?!1:null===l?!1:"object"!=typeof m&&"function"!=typeof m||"function"!=typeof m.__cmp__?"object"!=typeof l&&"function"!=typeof l||"function"!=typeof l.__cmp__?m==l:0===l.__cmp__(m):0===m.__cmp__(l))||!1===e||0===e||""===e?0:"object"==typeof e?"function"==typeof e.__nonzero__?e.__nonzero__():"function"==typeof e.__len__?0<e.__len__():1:1)?(q=b.b)===(J="undefined"!=typeof(ba=a).__array?"undefined"!=
typeof ba.__array[2]?ba.__array[2]:ba.__getitem__(2):ba.__getitem__(2))&&null===q?!0:null===q?!1:null===J?!1:"object"!=typeof q&&"function"!=typeof q||"function"!=typeof q.__cmp__?"object"!=typeof J&&"function"!=typeof J||"function"!=typeof J.__cmp__?q==J:0===J.__cmp__(q):0===q.__cmp__(J):U:T:B:(null===(h=f=(k=b.r)===(K="undefined"!=typeof(Z=a).__array?"undefined"!=typeof Z.__array[0]?Z.__array[0]:Z.__getitem__(0):Z.__getitem__(0))&&null===k?!0:null===k?!1:null===K?!1:"object"!=typeof k&&"function"!=
typeof k||"function"!=typeof k.__cmp__?"object"!=typeof K&&"function"!=typeof K||"function"!=typeof K.__cmp__?k==K:0===K.__cmp__(k):0===k.__cmp__(K))||!1===h||0===h||""===h?0:"object"==typeof h?"function"==typeof h.__nonzero__?h.__nonzero__():"function"==typeof h.__len__?0<h.__len__():1:1)?(null===(g=ca=(u=b.g)===(L="undefined"!=typeof(R=a).__array?"undefined"!=typeof R.__array[1]?R.__array[1]:R.__getitem__(1):R.__getitem__(1))&&null===u?!0:null===u?!1:null===L?!1:"object"!=typeof u&&"function"!=
typeof u||"function"!=typeof u.__cmp__?"object"!=typeof L&&"function"!=typeof L||"function"!=typeof L.__cmp__?u==L:0===L.__cmp__(u):0===u.__cmp__(L))||!1===g||0===g||""===g?0:"object"==typeof g?"function"==typeof g.__nonzero__?g.__nonzero__():"function"==typeof g.__len__?0<g.__len__():1:1)?(v=b.b)===(E="undefined"!=typeof(Q=a).__array?"undefined"!=typeof Q.__array[2]?Q.__array[2]:Q.__getitem__(2):Q.__getitem__(2))&&null===v?!0:null===v?!1:null===E?!1:"object"!=typeof v&&"function"!=typeof v||"function"!=
typeof v.__cmp__?"object"!=typeof E&&"function"!=typeof E||"function"!=typeof E.__cmp__?v==E:0===E.__cmp__(v):0===v.__cmp__(E):ca:f},1,[null,null,["self"],["other"]]);p.__eq__=f;f=$pyjs__bind_method2("__ne__",function(a,f){if(!0===this.__is_instance__)var b=this;else b=a,a=f;var d,c,e,h,g,A,s,r,p,B,T,U,m,t,q,l,k,J,u,K,v,L,C,w,D,x,y,E,z,M,V,N,O,W,X,Y,Z,$,aa,ba,F,G,P,ca,Q,R,H,S,I;return(null===(e=$p.hasattr(a,"a"))||!1===e||0===e||""===e?0:"object"==typeof e?"function"==typeof e.__nonzero__?e.__nonzero__():
"function"==typeof e.__len__?0<e.__len__():1:1)?(null===(h=Z=!((k=b.r)===(q=a.r)&&null===k||(null===k?0:null===q?0:"object"!=typeof k&&"function"!=typeof k||"function"!=typeof k.__cmp__?"object"!=typeof q&&"function"!=typeof q||"function"!=typeof q.__cmp__?k==q:0===q.__cmp__(k):0===k.__cmp__(q))))||!1===h||0===h||""===h?0:"object"==typeof h?"function"==typeof h.__nonzero__?h.__nonzero__():"function"==typeof h.__len__?0<h.__len__():1:1)?Z:(null===(g=aa=!((l=b.g)===(K=a.g)&&null===l||(null===l?0:null===
K?0:"object"!=typeof l&&"function"!=typeof l||"function"!=typeof l.__cmp__?"object"!=typeof K&&"function"!=typeof K||"function"!=typeof K.__cmp__?l==K:0===K.__cmp__(l):0===l.__cmp__(K))))||!1===g||0===g||""===g?0:"object"==typeof g?"function"==typeof g.__nonzero__?g.__nonzero__():"function"==typeof g.__len__?0<g.__len__():1:1)?aa:(null===(d=$=!((v=b.b)===(J=a.b)&&null===v||(null===v?0:null===J?0:"object"!=typeof v&&"function"!=typeof v||"function"!=typeof v.__cmp__?"object"!=typeof J&&"function"!=
typeof J||"function"!=typeof J.__cmp__?v==J:0===J.__cmp__(v):0===v.__cmp__(J))))||!1===d||0===d||""===d?0:"object"==typeof d?"function"==typeof d.__nonzero__?d.__nonzero__():"function"==typeof d.__len__?0<d.__len__():1:1)?$:!((u=b.a)===(L=a.a)&&null===u||(null===u?0:null===L?0:"object"!=typeof u&&"function"!=typeof u||"function"!=typeof u.__cmp__?"object"!=typeof L&&"function"!=typeof L||"function"!=typeof L.__cmp__?u==L:0===L.__cmp__(u):0===u.__cmp__(L))):(null===(c=4===(C=null===(M=a)?0:"undefined"!=
typeof M.__array?M.__array.length:"function"==typeof M.__len__?M.__len__():"undefined"!=typeof M.length?M.length:$p.len(M))&&null===C?!0:null===C?!1:"object"!=typeof C&&"function"!=typeof C||"function"!=typeof C.__cmp__?4==C:0===C.__cmp__(4))||!1===c||0===c||""===c?0:"object"==typeof c?"function"==typeof c.__nonzero__?c.__nonzero__():"function"==typeof c.__len__?0<c.__len__():1:1)?(null===(x=W=!((Q=b.a)===(N="undefined"!=typeof(O=a).__array?"undefined"!=typeof O.__array[3]?O.__array[3]:O.__getitem__(3):
O.__getitem__(3))&&null===Q||(null===Q?0:null===N?0:"object"!=typeof Q&&"function"!=typeof Q||"function"!=typeof Q.__cmp__?"object"!=typeof N&&"function"!=typeof N||"function"!=typeof N.__cmp__?Q==N:0===N.__cmp__(Q):0===Q.__cmp__(N))))||!1===x||0===x||""===x?0:"object"==typeof x?"function"==typeof x.__nonzero__?x.__nonzero__():"function"==typeof x.__len__?0<x.__len__():1:1)?W:(null===(D=Y=!((z=b.r)===(I="undefined"!=typeof(ca=a).__array?"undefined"!=typeof ca.__array[0]?ca.__array[0]:ca.__getitem__(0):
ca.__getitem__(0))&&null===z||(null===z?0:null===I?0:"object"!=typeof z&&"function"!=typeof z||"function"!=typeof z.__cmp__?"object"!=typeof I&&"function"!=typeof I||"function"!=typeof I.__cmp__?z==I:0===I.__cmp__(z):0===z.__cmp__(I))))||!1===D||0===D||""===D?0:"object"==typeof D?"function"==typeof D.__nonzero__?D.__nonzero__():"function"==typeof D.__len__?0<D.__len__():1:1)?Y:(null===(E=X=!((S=b.g)===(H="undefined"!=typeof(P=a).__array?"undefined"!=typeof P.__array[1]?P.__array[1]:P.__getitem__(1):
P.__getitem__(1))&&null===S||(null===S?0:null===H?0:"object"!=typeof S&&"function"!=typeof S||"function"!=typeof S.__cmp__?"object"!=typeof H&&"function"!=typeof H||"function"!=typeof H.__cmp__?S==H:0===H.__cmp__(S):0===S.__cmp__(H))))||!1===E||0===E||""===E?0:"object"==typeof E?"function"==typeof E.__nonzero__?E.__nonzero__():"function"==typeof E.__len__?0<E.__len__():1:1)?X:!((R=b.b)===(G="undefined"!=typeof(U=a).__array?"undefined"!=typeof U.__array[2]?U.__array[2]:U.__getitem__(2):U.__getitem__(2))&&
null===R||(null===R?0:null===G?0:"object"!=typeof R&&"function"!=typeof R||"function"!=typeof R.__cmp__?"object"!=typeof G&&"function"!=typeof G||"function"!=typeof G.__cmp__?R==G:0===G.__cmp__(R):0===R.__cmp__(G))):(null===(y=ba=!((F=b.r)===(s="undefined"!=typeof(T=a).__array?"undefined"!=typeof T.__array[0]?T.__array[0]:T.__getitem__(0):T.__getitem__(0))&&null===F||(null===F?0:null===s?0:"object"!=typeof F&&"function"!=typeof F||"function"!=typeof F.__cmp__?"object"!=typeof s&&"function"!=typeof s||
"function"!=typeof s.__cmp__?F==s:0===s.__cmp__(F):0===F.__cmp__(s))))||!1===y||0===y||""===y?0:"object"==typeof y?"function"==typeof y.__nonzero__?y.__nonzero__():"function"==typeof y.__len__?0<y.__len__():1:1)?ba:(null===(w=V=!((r=b.g)===(p="undefined"!=typeof(t=a).__array?"undefined"!=typeof t.__array[1]?t.__array[1]:t.__getitem__(1):t.__getitem__(1))&&null===r||(null===r?0:null===p?0:"object"!=typeof r&&"function"!=typeof r||"function"!=typeof r.__cmp__?"object"!=typeof p&&"function"!=typeof p||
"function"!=typeof p.__cmp__?r==p:0===p.__cmp__(r):0===r.__cmp__(p))))||!1===w||0===w||""===w?0:"object"==typeof w?"function"==typeof w.__nonzero__?w.__nonzero__():"function"==typeof w.__len__?0<w.__len__():1:1)?V:!((B=b.b)===(A="undefined"!=typeof(m=a).__array?"undefined"!=typeof m.__array[2]?m.__array[2]:m.__getitem__(2):m.__getitem__(2))&&null===B||(null===B?0:null===A?0:"object"!=typeof B&&"function"!=typeof B||"function"!=typeof B.__cmp__?"object"!=typeof A&&"function"!=typeof A||"function"!=
typeof A.__cmp__?B==A:0===A.__cmp__(B):0===B.__cmp__(A)))},1,[null,null,["self"],["other"]]);p.__ne__=f;f=Array(ea._Color);var da=$p.dict(),fa;for(fa in p)da.__setitem__(fa,p[fa]);return $p._create_class("Color",$p.tuple(f),da)}();return this};
