$pyjs.loaded_modules["pyjsdl.event"]=function(I){if($pyjs.loaded_modules["pyjsdl.event"].__was_initialized__)return $pyjs.loaded_modules["pyjsdl.event"];"undefined"!=typeof $pyjs.loaded_modules.pyjsdl&&$pyjs.loaded_modules.pyjsdl.__was_initialized__||$p.___import___("pyjsdl",null);var b=$pyjs.loaded_modules["pyjsdl.event"];b.__repr__=function(){return"<module: pyjsdl.event>"};b.__was_initialized__=!0;if(null===I||"undefined"==typeof I)I="pyjsdl.event";b.__name__=I;$pyjs.loaded_modules.pyjsdl.event=
$pyjs.loaded_modules["pyjsdl.event"];b.env=$p.___import___("pyjsdl.env","pyjsdl",null,!1);b.Const=$p.___import___("pyjsdl.locals","pyjsdl",null,!1);b.__docformat__="restructuredtext";b.Event=function(){var h={},f;h.__module__="pyjsdl.event";f=$pyjs__bind_method2("__init__",function(d){d=!0===this.__is_instance__?this:d;var l;d.eventQueue=function(){var d,a,c,b,l;a=$p.list();c=$p.range(256);"undefined"!=typeof(l=c.__array)?d=0:(c=c.__iter__(),d="undefined"!=typeof(l=c.__array)?0:"function"==typeof c.$genfunc?
1:-1);for(b=0;"undefined"!=typeof(d?0<d?c.next(!0,!1):$p.wrapped_next(c):l[b++]);)a.append(null);return a}();d.eventNum=0;d.eventQueueTmp=function(){var d,a,c,b,l;c=$p.list();a=$p.range(256);"undefined"!=typeof(l=a.__array)?d=0:(a=a.__iter__(),d="undefined"!=typeof(l=a.__array)?0:"function"==typeof a.$genfunc?1:-1);for(b=0;"undefined"!=typeof(d?0<d?a.next(!0,!1):$p.wrapped_next(a):l[b++]);)c.append(null);return c}();d.eventNumTmp=0;d.queueLock=!1;d.queueAccess=!1;d.queue=$p.list([]);d.mousePress=
$p.dict([[0,!1],[1,!1],[2,!1]]);d.mouseMove=$p.dict([["x",-1],["y",-1]]);d.mouseMoveRel=$p.dict([["x",null],["y",null]]);d.keyPress=$p.dict([[b.Const.K_ALT,!1],[b.Const.K_CTRL,!1],[b.Const.K_SHIFT,!1]]);d.keyMod=$p.dict([[b.Const.K_ALT,$p.dict([[!0,b.Const.KMOD_ALT],[!1,0]])],[b.Const.K_CTRL,$p.dict([[!0,b.Const.KMOD_CTRL],[!1,0]])],[b.Const.K_SHIFT,$p.dict([[!0,b.Const.KMOD_SHIFT],[!1,0]])]]);d.eventName=$p.dict([["mousemove","MouseMotion"],["mousedown","MouseButtonDown"],["mouseup","MouseButtonUp"],
["keydown","KeyDown"],["keyup","KeyUp"]]);d.eventType=$p.list("mousemove mousedown mouseup wheel mousewheel DOMMouseScroll keydown keypress keyup".split(" "));d.events=$p.set(d.eventType);d.eventTypes=$p.dict([[b.Const.MOUSEMOTION,$p.list(["mousemove"])],[b.Const.MOUSEBUTTONDOWN,$p.list(["mousedown","wheel","mousewheel","DOMMouseScroll"])],[b.Const.MOUSEBUTTONUP,$p.list(["mouseup"])],[b.Const.KEYDOWN,$p.list(["keydown","keypress"])],[b.Const.KEYUP,$p.list(["keyup"])]]);(null===(l=b.env.pyjs_mode.optimized)||
!1===l||0===l||""===l?0:"object"==typeof l?"function"==typeof l.__nonzero__?l.__nonzero__():"function"==typeof l.__len__?0<l.__len__():1:1)?(d.modKey=$p.set($p.list([b.Const.K_ALT,b.Const.K_CTRL,b.Const.K_SHIFT])),d.specialKey=$p.set($p.list([b.Const.K_UP,b.Const.K_DOWN,b.Const.K_LEFT,b.Const.K_RIGHT,b.Const.K_HOME,b.Const.K_END,b.Const.K_PAGEDOWN,b.Const.K_PAGEUP,b.Const.K_BACKSPACE,b.Const.K_DELETE,b.Const.K_INSERT,b.Const.K_RETURN,b.Const.K_TAB,b.Const.K_ESCAPE]))):(d.modKey=$p.set(function(){var d,
a,c,l,g,m;l=$p.list();g=$p.tuple([b.Const.K_ALT,b.Const.K_CTRL,b.Const.K_SHIFT]);"undefined"!=typeof(m=g.__array)?c=0:(g=g.__iter__(),c="undefined"!=typeof(m=g.__array)?0:"function"==typeof g.$genfunc?1:-1);for(d=0;"undefined"!=typeof(a=c?0<c?g.next(!0,!1):$p.wrapped_next(g):m[d++]);)l.append(a.valueOf());return l}()),d.specialKey=$p.set(function(){var d,a,c,l,g,m;d=$p.list();c=$p.tuple([b.Const.K_UP,b.Const.K_DOWN,b.Const.K_LEFT,b.Const.K_RIGHT,b.Const.K_HOME,b.Const.K_END,b.Const.K_PAGEDOWN,b.Const.K_PAGEUP,
b.Const.K_BACKSPACE,b.Const.K_DELETE,b.Const.K_INSERT,b.Const.K_RETURN,b.Const.K_TAB,b.Const.K_ESCAPE]);"undefined"!=typeof(m=c.__array)?a=0:(c=c.__iter__(),a="undefined"!=typeof(m=c.__array)?0:"function"==typeof c.$genfunc?1:-1);for(g=0;"undefined"!=typeof(l=a?0<a?c.next(!0,!1):$p.wrapped_next(c):m[g++]);)d.append(l.valueOf());return d}()));d.touchlistener=null;d.Event="undefined"==typeof UserEvent?b.UserEvent:UserEvent;d._nonimplemented_methods();return null},1,[null,null,["self"]]);h.__init__=
f;f=$pyjs__bind_method2("_lock",function(d){(!0===this.__is_instance__?this:d).queueLock=!0;return null},1,[null,null,["self"]]);h._lock=f;f=$pyjs__bind_method2("_unlock",function(d){(!0===this.__is_instance__?this:d).queueLock=!1;return null},1,[null,null,["self"]]);h._unlock=f;f=$pyjs__bind_method2("_updateQueue",function(d,l){if(!0===this.__is_instance__)var e=this;else e=d,d=l;var a,c,b,g;if(null===(c=!e.events.__contains__(d.type))||!1===c||0===c||""===c?0:"object"==typeof c?"function"==typeof c.__nonzero__?
c.__nonzero__():"function"==typeof c.__len__?0<c.__len__():1:1)return null;e.queueAccess=!0;(null===(g=!(null===(b=e.queueLock)||!1===b||0===b||""===b?0:"object"==typeof b?"function"==typeof b.__nonzero__?b.__nonzero__():"function"==typeof b.__len__?0<b.__len__():1:1))||!1===g||0===g||""===g?0:"object"==typeof g?"function"==typeof g.__nonzero__?g.__nonzero__():"function"==typeof g.__len__?0<g.__len__():1:1)?((null===(a=e.eventNumTmp)||!1===a||0===a||""===a?0:"object"==typeof a?"function"==typeof a.__nonzero__?
a.__nonzero__():"function"==typeof a.__len__?0<a.__len__():1:1)&&e._appendMerge(),e._append(d)):e._appendTmp(d);e.queueAccess=!1;return null},1,[null,null,["self"],["event"]]);h._updateQueue=f;f=$pyjs__bind_method2("_append",function(d,b){if(!0===this.__is_instance__)var e=this;else e=d,d=b;var a,c;if(null===(c=-1==(255===(a=e.eventNum)?0:"number"!=typeof a||"number"!=typeof a&&"string"!=typeof a&&"boolean"!=typeof a?$p.cmp(a,255):255==a?0:255>a?-1:1))||!1===c||0===c||""===c?0:"object"==typeof c?
"function"==typeof c.__nonzero__?c.__nonzero__():"function"==typeof c.__len__?0<c.__len__():1:1)e.eventQueue.__setitem__(e.eventNum,d),e.eventNum+=1;return null},1,[null,null,["self"],["event"]]);h._append=f;f=$pyjs__bind_method2("_appendTmp",function(d,b){if(!0===this.__is_instance__)var e=this;else e=d,d=b;var a,c;if(null===(c=-1==(255===(a=e.eventNumTmp)?0:"number"!=typeof a||"number"!=typeof a&&"string"!=typeof a&&"boolean"!=typeof a?$p.cmp(a,255):255==a?0:255>a?-1:1))||!1===c||0===c||""===c?
0:"object"==typeof c?"function"==typeof c.__nonzero__?c.__nonzero__():"function"==typeof c.__len__?0<c.__len__():1:1)e.eventQueueTmp.__setitem__(e.eventNumTmp,d),e.eventNumTmp+=1;return null},1,[null,null,["self"],["event"]]);h._appendTmp=f;f=$pyjs__bind_method2("_appendMerge",function(d){d=!0===this.__is_instance__?this:d;var b,e,a,c,n,g,m;a=$p.range(d.eventNumTmp);"undefined"!=typeof(c=a.__array)?n=0:(a=a.__iter__(),n="undefined"!=typeof(c=a.__array)?0:"function"==typeof a.$genfunc?1:-1);for(e=
0;"undefined"!=typeof(b=n?0<n?a.next(!0,!1):$p.wrapped_next(a):c[e++]);)d._append("undefined"!=typeof(m=d.eventQueueTmp).__array?"undefined"!=typeof m.__array[g=b]?m.__array[g]:m.__getitem__(g):m.__getitem__(b)),d.eventQueueTmp.__setitem__(b,null);d.eventNumTmp=0;return null},1,[null,null,["self"]]);h._appendMerge=f;f=$pyjs__bind_method2("pump",function(d){d=!0===this.__is_instance__?this:d;var b,e;if(null===(e=1==(250===(b=d.eventNum)?0:"number"!=typeof b||"number"!=typeof b&&"string"!=typeof b&&
"boolean"!=typeof b?$p.cmp(b,250):250==b?0:250>b?-1:1))||!1===e||0===e||""===e?0:"object"==typeof e?"function"==typeof e.__nonzero__?e.__nonzero__():"function"==typeof e.__len__?0<e.__len__():1:1)d._lock(),d._pump(),d._unlock();return null},1,[null,null,["self"]]);h.pump=f;f=$pyjs__bind_method2("_pump",function(d){d=!0===this.__is_instance__?this:d;var b,e,a,c,n,g,m,k;g=$p.__getslice(d.eventQueue,50,d.eventNum);d.eventNum-=50;m=$p.range(d.eventNum);"undefined"!=typeof(n=m.__array)?a=0:(m=m.__iter__(),
a="undefined"!=typeof(n=m.__array)?0:"function"==typeof m.$genfunc?1:-1);for(e=0;"undefined"!=typeof(b=a?0<a?m.next(!0,!1):$p.wrapped_next(m):n[e++]);)d.eventQueue.__setitem__(b,"undefined"!=typeof(k=g).__array?"undefined"!=typeof k.__array[c=b]?k.__array[c]:k.__getitem__(c):k.__getitem__(b));return null},1,[null,null,["self"]]);h._pump=f;f=$pyjs__bind_method2("get",function(d){if(!0===this.__is_instance__)var l=this;else l=arguments[0],d=arguments[1];"undefined"==typeof d&&(d=arguments.callee.__args__[3][1]);
var e,a,c,n,g,m,k,f,r,t,p,h,w,D,y,x,q,s,v,E,C;l._lock();if(null===(e=!(null===(f=d)||!1===f||0===f||""===f?0:"object"==typeof f?"function"==typeof f.__nonzero__?f.__nonzero__():"function"==typeof f.__len__?0<f.__len__():1:1))||!1===e||0===e||""===e?0:"object"==typeof e?"function"==typeof e.__nonzero__?e.__nonzero__():"function"==typeof e.__len__?0<e.__len__():1:1)l.queue=function(){var d,a,e,c,g,k;e=$p.list();a=$p.__getslice(l.eventQueue,0,l.eventNum);"undefined"!=typeof(c=a.__array)?k=0:(a=a.__iter__(),
k="undefined"!=typeof(c=a.__array)?0:"function"==typeof a.$genfunc?1:-1);for(g=0;"undefined"!=typeof(d=k?0<k?a.next(!0,!1):$p.wrapped_next(a):c[g++]);)e.append(("undefined"==typeof JEvent?b.JEvent:JEvent)(d));return e}(),l.eventNum=0;else{e=(null===(a=!(null===(k=$p.isinstance(d,$p.tuple([$p.tuple,$p.list])))||!1===k||0===k||""===k?0:"object"==typeof k?"function"==typeof k.__nonzero__?k.__nonzero__():"function"==typeof k.__len__?0<k.__len__():1:1))||!1===a||0===a||""===a?0:"object"==typeof a?"function"==
typeof a.__nonzero__?a.__nonzero__():"function"==typeof a.__len__?0<a.__len__():1:1)?function(){var a,b,e,c,g,k;b=$p.list();g="undefined"!=typeof(e=l.eventTypes).__array?"undefined"!=typeof e.__array[a=d]?e.__array[a]:e.__getitem__(a):e.__getitem__(d);"undefined"!=typeof(c=g.__array)?e=0:(g=g.__iter__(),e="undefined"!=typeof(c=g.__array)?0:"function"==typeof g.$genfunc?1:-1);for(a=0;"undefined"!=typeof(k=e?0<e?g.next(!0,!1):$p.wrapped_next(g):c[a++]);)b.append(k);return b}():function(){var a,e,b,
c,g,k,n,f,p,m,h,r;b=$p.list();e=d;"undefined"!=typeof(r=e.__array)?n=0:(e=e.__iter__(),n="undefined"!=typeof(r=e.__array)?0:"function"==typeof e.$genfunc?1:-1);for(g=0;"undefined"!=typeof(c=n?0<n?e.next(!0,!1):$p.wrapped_next(e):r[g++]);)for(h="undefined"!=typeof(p=l.eventTypes).__array?"undefined"!=typeof p.__array[f=c]?p.__array[f]:p.__getitem__(f):p.__getitem__(c),"undefined"!=typeof(k=h.__array)?m=0:(h=h.__iter__(),m="undefined"!=typeof(k=h.__array)?0:"function"==typeof h.$genfunc?1:-1),c=0;"undefined"!=
typeof(a=m?0<m?h.next(!0,!1):$p.wrapped_next(h):k[c++]);)b.append(a);return b}();a=$p.list([]);l.queue=$p.list([]);h=$p.range(l.eventNum);"undefined"!=typeof(y=h.__array)?E=0:(h=h.__iter__(),E="undefined"!=typeof(y=h.__array)?0:"function"==typeof h.$genfunc?1:-1);for(f=0;"undefined"!=typeof(k=E?0<E?h.next(!0,!1):$p.wrapped_next(h):y[f++]);)(null===(r=!e.__contains__(("undefined"!=typeof(c=l.eventQueue).__array?"undefined"!=typeof c.__array[s=k]?c.__array[s]:c.__getitem__(s):c.__getitem__(k)).type))||
!1===r||0===r||""===r?0:"object"==typeof r?"function"==typeof r.__nonzero__?r.__nonzero__():"function"==typeof r.__len__?0<r.__len__():1:1)?a.append("undefined"!=typeof(x=l.eventQueue).__array?"undefined"!=typeof x.__array[v=k]?x.__array[v]:x.__getitem__(v):x.__getitem__(k)):l.queue.append(("undefined"==typeof JEvent?b.JEvent:JEvent)("undefined"!=typeof(C=l.eventQueue).__array?"undefined"!=typeof C.__array[q=k]?C.__array[q]:C.__getitem__(q):C.__getitem__(k)));if(null===(n=!((w=null===a?0:"undefined"!=
typeof a.__array?a.__array.length:"function"==typeof a.__len__?a.__len__():"undefined"!=typeof a.length?a.length:$p.len(a))===(p=l.eventNum)&&null===w||(null===w?0:null===p?0:"object"!=typeof w&&"function"!=typeof w||"function"!=typeof w.__cmp__?"object"!=typeof p&&"function"!=typeof p||"function"!=typeof p.__cmp__?w==p:0===p.__cmp__(w):0===w.__cmp__(p))))||!1===n||0===n||""===n?0:"object"==typeof n?"function"==typeof n.__nonzero__?n.__nonzero__():"function"==typeof n.__len__?0<n.__len__():1:1)for(l.eventNum=
null===a?0:"undefined"!=typeof a.__array?a.__array.length:"function"==typeof a.__len__?a.__len__():"undefined"!=typeof a.length?a.length:$p.len(a),c=$p.range(l.eventNum),"undefined"!=typeof(n=c.__array)?r=0:(c=c.__iter__(),r="undefined"!=typeof(n=c.__array)?0:"function"==typeof c.$genfunc?1:-1),p=0;"undefined"!=typeof(w=r?0<r?c.next(!0,!1):$p.wrapped_next(c):n[p++]);)k=w,l.eventQueue.__setitem__(k,"undefined"!=typeof(t=a).__array?"undefined"!=typeof t.__array[D=k]?t.__array[D]:t.__getitem__(D):t.__getitem__(k));
(null===(g=1==(250===(m=l.eventNum)?0:"number"!=typeof m||"number"!=typeof m&&"string"!=typeof m&&"boolean"!=typeof m?$p.cmp(m,250):250==m?0:250>m?-1:1))||!1===g||0===g||""===g?0:"object"==typeof g?"function"==typeof g.__nonzero__?g.__nonzero__():"function"==typeof g.__len__?0<g.__len__():1:1)&&l._pump()}l._unlock();return l.queue},1,[null,null,["self"],["eventType",null]]);h.get=f;f=$pyjs__bind_method2("poll",function(d){d=!0===this.__is_instance__?this:d;var l,e,a;d._lock();(null===(e=d.eventNum)||
!1===e||0===e||""===e?0:"object"==typeof e?"function"==typeof e.__nonzero__?e.__nonzero__():"function"==typeof e.__len__?0<e.__len__():1:1)?(e=("undefined"==typeof JEvent?b.JEvent:JEvent)(d.eventQueue.pop(0)),d.eventNum-=1,d.eventQueue.append(null),(null===(a=1==(250===(l=d.eventNum)?0:"number"!=typeof l||"number"!=typeof l&&"string"!=typeof l&&"boolean"!=typeof l?$p.cmp(l,250):250==l?0:250>l?-1:1))||!1===a||0===a||""===a?0:"object"==typeof a?"function"==typeof a.__nonzero__?a.__nonzero__():"function"==
typeof a.__len__?0<a.__len__():1:1)&&d._pump()):e=d.Event(b.Const.NOEVENT);d._unlock();return e},1,[null,null,["self"]]);h.poll=f;f=$pyjs__bind_method2("wait",function(d){d=!0===this.__is_instance__?this:d;for(var l,e,a;!0!==0&&!0!=="";){if(null===(l=d.eventNum)||!1===l||0===l||""===l?0:"object"==typeof l?"function"==typeof l.__nonzero__?l.__nonzero__():"function"==typeof l.__len__?0<l.__len__():1:1)return d._lock(),l=("undefined"==typeof JEvent?b.JEvent:JEvent)(d.eventQueue.pop(0)),d.eventNum-=1,
d.eventQueue.append(null),(null===(a=1==(250===(e=d.eventNum)?0:"number"!=typeof e||"number"!=typeof e&&"string"!=typeof e&&"boolean"!=typeof e?$p.cmp(e,250):250==e?0:250>e?-1:1))||!1===a||0===a||""===a?0:"object"==typeof a?"function"==typeof a.__nonzero__?a.__nonzero__():"function"==typeof a.__len__?0<a.__len__():1:1)&&d._pump(),d._unlock(),l;d._unlock();break}return null},1,[null,null,["self"]]);h.wait=f;f=$pyjs__bind_method2("peek",function(d,b){if(!0===this.__is_instance__)var e=this;else e=d,
d=b;var a,c,n,g,f,k,h;if(null===(n=!(null===(a=e.eventNum)||!1===a||0===a||""===a?0:"object"==typeof a?"function"==typeof a.__nonzero__?a.__nonzero__():"function"==typeof a.__len__?0<a.__len__():1:1))||!1===n||0===n||""===n?0:"object"==typeof n?"function"==typeof n.__nonzero__?n.__nonzero__():"function"==typeof n.__len__?0<n.__len__():1:1)return!1;a=(null===(f=!(null===(h=$p.isinstance(d,$p.tuple([$p.tuple,$p.list])))||!1===h||0===h||""===h?0:"object"==typeof h?"function"==typeof h.__nonzero__?h.__nonzero__():
"function"==typeof h.__len__?0<h.__len__():1:1))||!1===f||0===f||""===f?0:"object"==typeof f?"function"==typeof f.__nonzero__?f.__nonzero__():"function"==typeof f.__len__?0<f.__len__():1:1)?function(){var a,b,c,l,g,k;l=$p.list();c="undefined"!=typeof(a=e.eventTypes).__array?"undefined"!=typeof a.__array[g=d]?a.__array[g]:a.__getitem__(g):a.__getitem__(d);"undefined"!=typeof(k=c.__array)?a=0:(c=c.__iter__(),a="undefined"!=typeof(k=c.__array)?0:"function"==typeof c.$genfunc?1:-1);for(g=0;"undefined"!=
typeof(b=a?0<a?c.next(!0,!1):$p.wrapped_next(c):k[g++]);)l.append(b);return l}():function(){var a,b,c,l,g,k,f,n,h,m,u,E;l=$p.list();m=d;"undefined"!=typeof(a=m.__array)?b=0:(m=m.__iter__(),b="undefined"!=typeof(a=m.__array)?0:"function"==typeof m.$genfunc?1:-1);for(E=0;"undefined"!=typeof(c=b?0<b?m.next(!0,!1):$p.wrapped_next(m):a[E++]);)for(c="undefined"!=typeof(n=e.eventTypes).__array?"undefined"!=typeof n.__array[k=c]?n.__array[k]:n.__getitem__(k):n.__getitem__(c),"undefined"!=typeof(f=c.__array)?
u=0:(c=c.__iter__(),u="undefined"!=typeof(f=c.__array)?0:"function"==typeof c.$genfunc?1:-1),h=0;"undefined"!=typeof(g=u?0<u?c.next(!0,!1):$p.wrapped_next(c):f[h++]);)l.append(g);return l}();e._lock();f=function(){var a,d,b,c,l,g;c=$p.list();g=$p.__getslice(e.eventQueue,0,e.eventNum);"undefined"!=typeof(a=g.__array)?d=0:(g=g.__iter__(),d="undefined"!=typeof(a=g.__array)?0:"function"==typeof g.$genfunc?1:-1);for(b=0;"undefined"!=typeof(l=d?0<d?g.next(!0,!1):$p.wrapped_next(g):a[b++]);)c.append(l.type);
return c}();(null===(c=1==(250===(g=e.eventNum)?0:"number"!=typeof g||"number"!=typeof g&&"string"!=typeof g&&"boolean"!=typeof g?$p.cmp(g,250):250==g?0:250>g?-1:1))||!1===c||0===c||""===c?0:"object"==typeof c?"function"==typeof c.__nonzero__?c.__nonzero__():"function"==typeof c.__len__?0<c.__len__():1:1)&&e._pump();e._unlock();g=a;"undefined"!=typeof(h=g.__array)?c=0:(g=g.__iter__(),c="undefined"!=typeof(h=g.__array)?0:"function"==typeof g.$genfunc?1:-1);for(a=0;"undefined"!=typeof(n=c?0<c?g.next(!0,
!1):$p.wrapped_next(g):h[a++]);)if(null===(k=f.__contains__(n))||!1===k||0===k||""===k?0:"object"==typeof k?"function"==typeof k.__nonzero__?k.__nonzero__():"function"==typeof k.__len__?0<k.__len__():1:1)return!0;return!1},1,[null,null,["self"],["eventType"]]);h.peek=f;f=$pyjs__bind_method2("clear",function(d){if(!0===this.__is_instance__)var b=this;else b=arguments[0],d=arguments[1];"undefined"==typeof d&&(d=arguments.callee.__args__[3][1]);var e,a,c,f,g,h,k,u,r,t,p,J,w,D,y,x,q,s,v;if(null===(u=
!(null===(e=b.eventNum)||!1===e||0===e||""===e?0:"object"==typeof e?"function"==typeof e.__nonzero__?e.__nonzero__():"function"==typeof e.__len__?0<e.__len__():1:1))||!1===u||0===u||""===u?0:"object"==typeof u?"function"==typeof u.__nonzero__?u.__nonzero__():"function"==typeof u.__len__?0<u.__len__():1:1)return null;b._lock();if(null===(g=null===d)||!1===g||0===g||""===g?0:"object"==typeof g?"function"==typeof g.__nonzero__?g.__nonzero__():"function"==typeof g.__len__?0<g.__len__():1:1)b.eventNum=
0;else{e=(null===(p=!(null===(q=$p.isinstance(d,$p.tuple([$p.tuple,$p.list])))||!1===q||0===q||""===q?0:"object"==typeof q?"function"==typeof q.__nonzero__?q.__nonzero__():"function"==typeof q.__len__?0<q.__len__():1:1))||!1===p||0===p||""===p?0:"object"==typeof p?"function"==typeof p.__nonzero__?p.__nonzero__():"function"==typeof p.__len__?0<p.__len__():1:1)?function(){var a,e,c,g,k,f;k=$p.list();e="undefined"!=typeof(a=b.eventTypes).__array?"undefined"!=typeof a.__array[c=d]?a.__array[c]:a.__getitem__(c):
a.__getitem__(d);"undefined"!=typeof(c=e.__array)?a=0:(e=e.__iter__(),a="undefined"!=typeof(c=e.__array)?0:"function"==typeof e.$genfunc?1:-1);for(g=0;"undefined"!=typeof(f=a?0<a?e.next(!0,!1):$p.wrapped_next(e):c[g++]);)k.append(f);return k}():function(){var a,e,c,g,k,f,h,n,m,p,r,t;p=$p.list();h=d;"undefined"!=typeof(f=h.__array)?n=0:(h=h.__iter__(),n="undefined"!=typeof(f=h.__array)?0:"function"==typeof h.$genfunc?1:-1);for(c=0;"undefined"!=typeof(a=n?0<n?h.next(!0,!1):$p.wrapped_next(h):f[c++]);)for(a=
"undefined"!=typeof(k=b.eventTypes).__array?"undefined"!=typeof k.__array[m=a]?k.__array[m]:k.__getitem__(m):k.__getitem__(a),"undefined"!=typeof(t=a.__array)?r=0:(a=a.__iter__(),r="undefined"!=typeof(t=a.__array)?0:"function"==typeof a.$genfunc?1:-1),g=0;"undefined"!=typeof(e=r?0<r?a.next(!0,!1):$p.wrapped_next(a):t[g++]);)p.append(e);return p}();q=$p.list([]);y=$p.range(b.eventNum);"undefined"!=typeof(v=y.__array)?g=0:(y=y.__iter__(),g="undefined"!=typeof(v=y.__array)?0:"function"==typeof y.$genfunc?
1:-1);for(u=0;"undefined"!=typeof(p=g?0<g?y.next(!0,!1):$p.wrapped_next(y):v[u++]);)(null===(a=!e.__contains__(("undefined"!=typeof(c=b.eventQueue).__array?"undefined"!=typeof c.__array[k=p]?c.__array[k]:c.__getitem__(k):c.__getitem__(p)).type))||!1===a||0===a||""===a?0:"object"==typeof a?"function"==typeof a.__nonzero__?a.__nonzero__():"function"==typeof a.__len__?0<a.__len__():1:1)&&q.append("undefined"!=typeof(h=b.eventQueue).__array?"undefined"!=typeof h.__array[D=p]?h.__array[D]:h.__getitem__(D):
h.__getitem__(p));if(null===(s=!((t=null===q?0:"undefined"!=typeof q.__array?q.__array.length:"function"==typeof q.__len__?q.__len__():"undefined"!=typeof q.length?q.length:$p.len(q))===(J=b.eventNum)&&null===t||(null===t?0:null===J?0:"object"!=typeof t&&"function"!=typeof t||"function"!=typeof t.__cmp__?"object"!=typeof J&&"function"!=typeof J||"function"!=typeof J.__cmp__?t==J:0===J.__cmp__(t):0===t.__cmp__(J))))||!1===s||0===s||""===s?0:"object"==typeof s?"function"==typeof s.__nonzero__?s.__nonzero__():
"function"==typeof s.__len__?0<s.__len__():1:1)for(b.eventNum=null===q?0:"undefined"!=typeof q.__array?q.__array.length:"function"==typeof q.__len__?q.__len__():"undefined"!=typeof q.length?q.length:$p.len(q),k=$p.range(b.eventNum),"undefined"!=typeof(a=k.__array)?c=0:(k=k.__iter__(),c="undefined"!=typeof(a=k.__array)?0:"function"==typeof k.$genfunc?1:-1),h=0;"undefined"!=typeof(t=c?0<c?k.next(!0,!1):$p.wrapped_next(k):a[h++]);)p=t,b.eventQueue.__setitem__(p,"undefined"!=typeof(f=q).__array?"undefined"!=
typeof f.__array[x=p]?f.__array[x]:f.__getitem__(x):f.__getitem__(p));(null===(r=1==(250===(w=b.eventNum)?0:"number"!=typeof w||"number"!=typeof w&&"string"!=typeof w&&"boolean"!=typeof w?$p.cmp(w,250):250==w?0:250>w?-1:1))||!1===r||0===r||""===r?0:"object"==typeof r?"function"==typeof r.__nonzero__?r.__nonzero__():"function"==typeof r.__len__?0<r.__len__():1:1)&&b._pump()}b._unlock();return null},1,[null,null,["self"],["eventType",null]]);h.clear=f;f=$pyjs__bind_method2("event_name",function(d,b){if(!0===
this.__is_instance__)var e=this;else e=d,d=b;var a,c,f,g,h,k;a="undefined"!=typeof(g="undefined"!=typeof(h=e.eventTypes).__array?"undefined"!=typeof h.__array[f=d]?h.__array[f]:h.__getitem__(f):h.__getitem__(d)).__array?"undefined"!=typeof g.__array[0]?g.__array[0]:g.__getitem__(0):g.__getitem__(0);return(null===(k=e.eventName.__contains__(a))||!1===k||0===k||""===k?0:"object"==typeof k?"function"==typeof k.__nonzero__?k.__nonzero__():"function"==typeof k.__len__?0<k.__len__():1:1)?"undefined"!=typeof(c=
e.eventName).__array?"undefined"!=typeof c.__array[a]?c.__array[a]:c.__getitem__(a):c.__getitem__(a):null},1,[null,null,["self"],["eventType"]]);h.event_name=f;f=$pyjs__bind_method2("set_blocked",function(d,b){if(!0===this.__is_instance__)var e=this;else e=d,d=b;var a,c,f,g,h,k;if(null===(a=null!==d)||!1===a||0===a||""===a?0:"object"==typeof a?"function"==typeof a.__nonzero__?a.__nonzero__():"function"==typeof a.__len__?0<a.__len__():1:1)for(c=a=(null===(k=!(null===(g=$p.isinstance(d,$p.tuple([$p.tuple,
$p.list])))||!1===g||0===g||""===g?0:"object"==typeof g?"function"==typeof g.__nonzero__?g.__nonzero__():"function"==typeof g.__len__?0<g.__len__():1:1))||!1===k||0===k||""===k?0:"object"==typeof k?"function"==typeof k.__nonzero__?k.__nonzero__():"function"==typeof k.__len__?0<k.__len__():1:1)?function(){var a,b,c,g,f,k;k=$p.list();c="undefined"!=typeof(g=e.eventTypes).__array?"undefined"!=typeof g.__array[a=d]?g.__array[a]:g.__getitem__(a):g.__getitem__(d);"undefined"!=typeof(f=c.__array)?a=0:(c=
c.__iter__(),a="undefined"!=typeof(f=c.__array)?0:"function"==typeof c.$genfunc?1:-1);for(g=0;"undefined"!=typeof(b=a?0<a?c.next(!0,!1):$p.wrapped_next(c):f[g++]);)k.append(b);return k}():function(){var a,b,c,g,f,k,l,h,n,m,s,v;a=$p.list();v=d;"undefined"!=typeof(l=v.__array)?k=0:(v=v.__iter__(),k="undefined"!=typeof(l=v.__array)?0:"function"==typeof v.$genfunc?1:-1);for(b=0;"undefined"!=typeof(c=k?0<k?v.next(!0,!1):$p.wrapped_next(v):l[b++]);)for(f="undefined"!=typeof(n=e.eventTypes).__array?"undefined"!=
typeof n.__array[m=c]?n.__array[m]:n.__getitem__(m):n.__getitem__(c),"undefined"!=typeof(c=f.__array)?s=0:(f=f.__iter__(),s="undefined"!=typeof(c=f.__array)?0:"function"==typeof f.$genfunc?1:-1),h=0;"undefined"!=typeof(g=s?0<s?f.next(!0,!1):$p.wrapped_next(f):c[h++]);)a.append(g);return a}(),"undefined"!=typeof(a=c.__array)?k=0:(c=c.__iter__(),k="undefined"!=typeof(a=c.__array)?0:"function"==typeof c.$genfunc?1:-1),g=0;"undefined"!=typeof(h=k?0<k?c.next(!0,!1):$p.wrapped_next(c):a[g++]);)(null===
(f=e.events.__contains__(h))||!1===f||0===f||""===f?0:"object"==typeof f?"function"==typeof f.__nonzero__?f.__nonzero__():"function"==typeof f.__len__?0<f.__len__():1:1)&&e.events.remove(h);else for(a=e.eventType,"undefined"!=typeof(f=a.__array)?k=0:(a=a.__iter__(),k="undefined"!=typeof(f=a.__array)?0:"function"==typeof a.$genfunc?1:-1),g=0;"undefined"!=typeof(c=k?0<k?a.next(!0,!1):$p.wrapped_next(a):f[g++]);)e.events.add(c);return null},1,[null,null,["self"],["eventType"]]);h.set_blocked=f;f=$pyjs__bind_method2("set_allowed",
function(d,b){if(!0===this.__is_instance__)var e=this;else e=d,d=b;var a,c,f,g,h;if(null===(a=null!==d)||!1===a||0===a||""===a?0:"object"==typeof a?"function"==typeof a.__nonzero__?a.__nonzero__():"function"==typeof a.__len__?0<a.__len__():1:1)for(h=a=(null===(c=!(null===(f=$p.isinstance(d,$p.tuple([$p.tuple,$p.list])))||!1===f||0===f||""===f?0:"object"==typeof f?"function"==typeof f.__nonzero__?f.__nonzero__():"function"==typeof f.__len__?0<f.__len__():1:1))||!1===c||0===c||""===c?0:"object"==typeof c?
"function"==typeof c.__nonzero__?c.__nonzero__():"function"==typeof c.__len__?0<c.__len__():1:1)?function(){var a,b,c,f,g,h;f=$p.list();g="undefined"!=typeof(c=e.eventTypes).__array?"undefined"!=typeof c.__array[a=d]?c.__array[a]:c.__getitem__(a):c.__getitem__(d);"undefined"!=typeof(a=g.__array)?h=0:(g=g.__iter__(),h="undefined"!=typeof(a=g.__array)?0:"function"==typeof g.$genfunc?1:-1);for(c=0;"undefined"!=typeof(b=h?0<h?g.next(!0,!1):$p.wrapped_next(g):a[c++]);)f.append(b);return f}():function(){var a,
b,c,g,f,h,l,n,m,x,q,s;f=$p.list();g=d;"undefined"!=typeof(q=g.__array)?c=0:(g=g.__iter__(),c="undefined"!=typeof(q=g.__array)?0:"function"==typeof g.$genfunc?1:-1);for(m=0;"undefined"!=typeof(a=c?0<c?g.next(!0,!1):$p.wrapped_next(g):q[m++]);)for(x="undefined"!=typeof(l=e.eventTypes).__array?"undefined"!=typeof l.__array[s=a]?l.__array[s]:l.__getitem__(s):l.__getitem__(a),"undefined"!=typeof(h=x.__array)?a=0:(x=x.__iter__(),a="undefined"!=typeof(h=x.__array)?0:"function"==typeof x.$genfunc?1:-1),n=
0;"undefined"!=typeof(b=a?0<a?x.next(!0,!1):$p.wrapped_next(x):h[n++]);)f.append(b);return f}(),"undefined"!=typeof(f=h.__array)?a=0:(h=h.__iter__(),a="undefined"!=typeof(f=h.__array)?0:"function"==typeof h.$genfunc?1:-1),c=0;"undefined"!=typeof(g=a?0<a?h.next(!0,!1):$p.wrapped_next(h):f[c++]);)e.events.add(g);else e.events.clear();return null},1,[null,null,["self"],["eventType"]]);h.set_allowed=f;f=$pyjs__bind_method2("get_blocked",function(d,b){if(!0===this.__is_instance__)var e=this;else e=d,d=
b;var a,c,f,g,h,k,u;a=$p.list();k="undefined"!=typeof(g=e.eventTypes).__array?"undefined"!=typeof g.__array[f=d]?g.__array[f]:g.__getitem__(f):g.__getitem__(d);"undefined"!=typeof(u=k.__array)?f=0:(k=k.__iter__(),f="undefined"!=typeof(u=k.__array)?0:"function"==typeof k.$genfunc?1:-1);for(g=0;"undefined"!=typeof(h=f?0<f?k.next(!0,!1):$p.wrapped_next(k):u[g++]);)a.append(h);a="undefined"!=typeof a.__array?"undefined"!=typeof a.__array[0]?a.__array[0]:a.__getitem__(0):a.__getitem__(0);return(null===
(c=!e.events.__contains__(a))||!1===c||0===c||""===c?0:"object"==typeof c?"function"==typeof c.__nonzero__?c.__nonzero__():"function"==typeof c.__len__?0<c.__len__():1:1)?!0:!1},1,[null,null,["self"],["eventType"]]);h.get_blocked=f;f=$pyjs__bind_method2("post",function(d,b){if(!0===this.__is_instance__)var e=this;else e=d,d=b;var a;e._lock();e._append(d);(null===(a=!e.events.__contains__(d.type))||!1===a||0===a||""===a?0:"object"==typeof a?"function"==typeof a.__nonzero__?a.__nonzero__():"function"==
typeof a.__len__?0<a.__len__():1:1)&&e.eventTypes.__setitem__(d.type,$p.list([d.type]));e._unlock();return null},1,[null,null,["self"],["event"]]);h.post=f;f=$pyjs__bind_method2("_initiate_touch_listener",function(d,f){if(!0===this.__is_instance__)var e=this;else e=d,d=f;e.touchlistener=("undefined"==typeof TouchListener?b.TouchListener:TouchListener)(d);return null},1,[null,null,["self"],["canvas"]]);h._initiate_touch_listener=f;f=$pyjs__bind_method2("_nonimplemented_methods",function(d){d=!0===
this.__is_instance__?this:d;var b;b=function(){$p.tuple($pyjs_array_slice.call(arguments,0,arguments.length));return null};b.__name__="$lambda1";b.__bind_type__=0;b.__args__=["arg",null];d.set_grab=b;b=function(){$p.tuple($pyjs_array_slice.call(arguments,0,arguments.length));return!1};b.__name__="$lambda2";b.__bind_type__=0;b.__args__=["arg",null];d.get_grab=b;return null},1,[null,null,["self"]]);h._nonimplemented_methods=f;f=Array($p.object);var B=$p.dict(),z;for(z in h)B.__setitem__(z,h[z]);return $p._create_class("Event",
$p.tuple(f),B)}();b.UserEvent=function(){var b={},f;b.__module__="pyjsdl.event";b.__slots__=$p.list(["type","attr"]);f=$pyjs__bind_method2("__init__",function(d){if(!0===this.__is_instance__)var b=this,e=$p.tuple($pyjs_array_slice.call(arguments,1,arguments.length-1)),a=2<=arguments.length?arguments[arguments.length-1]:arguments[arguments.length];else b=arguments[0],d=arguments[1],e=$p.tuple($pyjs_array_slice.call(arguments,2,arguments.length-1)),a=3<=arguments.length?arguments[arguments.length-1]:
arguments[arguments.length];null===a||"object"!=typeof a||"dict"!=a.__name__||"undefined"==typeof a.$pyjs_is_kwarg?("undefined"!=typeof a&&e.__array.push(a),a=arguments[arguments.length+1]):delete a.$pyjs_is_kwarg;"undefined"==typeof a&&(a=$p.__empty_dict(),"undefined"!=typeof d?null!==d&&"undefined"!=typeof d.$pyjs_is_kwarg&&(a=d,d=arguments[2]):"undefined"!=typeof b&&null!==b&&"undefined"!=typeof b.$pyjs_is_kwarg&&(a=b,b=arguments[2]));var c,f,e=(null===(c=e)||!1===c||0===c||""===c?0:"object"==
typeof c?"function"==typeof c.__nonzero__?c.__nonzero__():"function"==typeof c.__len__?0<c.__len__():1:1)?"undefined"!=typeof(f=e).__array?"undefined"!=typeof f.__array[0]?f.__array[0]:f.__getitem__(0):f.__getitem__(0):a;$p.object.__setattr__(b,"type",d);$p.object.__setattr__(b,"attr",e);return null},1,["args",["kwargs"],["self"],["eventType"]]);b.__init__=f;f=$pyjs__bind_method2("__repr__",function(b){b=!0===this.__is_instance__?this:b;return $p.sprintf("%s(%s-UserEvent %r)",$p.tuple([b.__class__,
b.type,b.attr]))},1,[null,null,["self"]]);b.__repr__=f;f=$pyjs__bind_method2("__getattr__",function(b,f){if(!0===this.__is_instance__)var e=this;else e=b,b=f;var a,c,h;if(null===(a=e.attr.__contains__(b))||!1===a||0===a||""===a?0:"object"==typeof a?"function"==typeof a.__nonzero__?a.__nonzero__():"function"==typeof a.__len__?0<a.__len__():1:1)return"undefined"!=typeof(c=e.attr).__array?"undefined"!=typeof c.__array[h=b]?c.__array[h]:c.__getitem__(h):c.__getitem__(b);throw $p.AttributeError($p.sprintf("'Event' object has no attribute '%s'",
b));},1,[null,null,["self"],["attr"]]);b.__getattr__=f;f=$pyjs__bind_method2("__setattr__",function(b,f,e){!0!==this.__is_instance__&&(b=f);throw $p.AttributeError($p.sprintf("'Event' object has no attribute '%s'",b));},1,[null,null,["self"],["attr"],["value"]]);b.__setattr__=f;f=Array($p.object);var B=$p.dict(),z;for(z in b)B.__setitem__(z,b[z]);return $p._create_class("UserEvent",$p.tuple(f),B)}();b.JEvent=function(){var h={},f;h.__module__="pyjsdl.event";h._mouse_pos=$p.tuple([0,0]);h._types=$p.dict([["mousemove",
b.Const.MOUSEMOTION],["mousedown",b.Const.MOUSEBUTTONDOWN],["mouseup",b.Const.MOUSEBUTTONUP],["wheel",b.Const.MOUSEBUTTONDOWN],["mousewheel",b.Const.MOUSEBUTTONDOWN],["DOMMouseScroll",b.Const.MOUSEBUTTONDOWN],["keydown",b.Const.KEYDOWN],["keypress",b.Const.KEYDOWN],["keyup",b.Const.KEYUP]]);h._charCode=$p.dict([[33,b.Const.K_EXCLAIM],[34,b.Const.K_QUOTEDBL],[35,b.Const.K_HASH],[36,b.Const.K_DOLLAR],[38,b.Const.K_AMPERSAND],[39,b.Const.K_QUOTE],[40,b.Const.K_LEFTPAREN],[41,b.Const.K_RIGHTPAREN],[42,
b.Const.K_ASTERISK],[43,b.Const.K_PLUS],[44,b.Const.K_COMMA],[45,b.Const.K_MINUS],[46,b.Const.K_PERIOD],[97,b.Const.K_a],[98,b.Const.K_b],[99,b.Const.K_c],[100,b.Const.K_d],[101,b.Const.K_e],[102,b.Const.K_f],[103,b.Const.K_g],[104,b.Const.K_h],[105,b.Const.K_i],[106,b.Const.K_j],[107,b.Const.K_k],[108,b.Const.K_l],[109,b.Const.K_m],[110,b.Const.K_n],[111,b.Const.K_o],[112,b.Const.K_p],[113,b.Const.K_q],[114,b.Const.K_r],[115,b.Const.K_s],[116,b.Const.K_t],[117,b.Const.K_u],[118,b.Const.K_v],[119,
b.Const.K_w],[120,b.Const.K_x],[121,b.Const.K_y],[122,b.Const.K_z]]);f=$pyjs__bind_method2("__init__",function(d,f){if(!0===this.__is_instance__)var e=this;else e=d,d=f;var a,c,h,g,m,k,u,r,t,p,z,w,D,y,x,q,s,v,E,C,B,L,M,I,N,O,P,G,H,F,A,K;e.event=d;if(null===(y=$p.tuple(["mousedown","mouseup"]).__contains__(d.type))||!1===y||0===y||""===y?0:"object"==typeof y?"function"==typeof y.__nonzero__?y.__nonzero__():"function"==typeof y.__len__?0<y.__len__():1:1)e.type="undefined"!=typeof(g=e.__class__._types).__array?
"undefined"!=typeof g.__array[m=d.type]?g.__array[m]:g.__getitem__(m):g.__getitem__(d.type),e.button=d.button+1,e.pos=$p.tuple([("undefined"!=typeof(k=d.pos).__array?"undefined"!=typeof k.__array[0]?k.__array[0]:k.__getitem__(0):k.__getitem__(0))+b.env.frame.scrollLeft,("undefined"!=typeof(u=d.pos).__array?"undefined"!=typeof u.__array[1]?u.__array[1]:u.__getitem__(1):u.__getitem__(1))+b.env.frame.scrollTop]);else if(null===(v="mousemove"===(C=d.type)&&null===C?!0:null===C?!1:"object"!=typeof C&&
"function"!=typeof C||"function"!=typeof C.__cmp__?"mousemove"==C:0===C.__cmp__("mousemove"))||!1===v||0===v||""===v?0:"object"==typeof v?"function"==typeof v.__nonzero__?v.__nonzero__():"function"==typeof v.__len__?0<v.__len__():1:1)e.type="undefined"!=typeof(h=e.__class__._types).__array?"undefined"!=typeof h.__array[w=d.type]?h.__array[w]:h.__getitem__(w):h.__getitem__(d.type),e.button=d.button+1,e.pos=$p.tuple([("undefined"!=typeof(z=d.pos).__array?"undefined"!=typeof z.__array[0]?z.__array[0]:
z.__getitem__(0):z.__getitem__(0))+b.env.frame.scrollLeft,("undefined"!=typeof(D=d.pos).__array?"undefined"!=typeof D.__array[1]?D.__array[1]:D.__getitem__(1):D.__getitem__(1))+b.env.frame.scrollTop]),e.rel=$p.tuple([("undefined"!=typeof(t=e.pos).__array?"undefined"!=typeof t.__array[0]?t.__array[0]:t.__getitem__(0):t.__getitem__(0))-("undefined"!=typeof(p=e.__class__._mouse_pos).__array?"undefined"!=typeof p.__array[0]?p.__array[0]:p.__getitem__(0):p.__getitem__(0)),("undefined"!=typeof(r=e.pos).__array?
"undefined"!=typeof r.__array[1]?r.__array[1]:r.__getitem__(1):r.__getitem__(1))-("undefined"!=typeof(L=e.__class__._mouse_pos).__array?"undefined"!=typeof L.__array[1]?L.__array[1]:L.__getitem__(1):L.__getitem__(1))]),e.__class__._mouse_pos=e.pos;else if(null===(s=$p.tuple(["wheel","mousewheel","DOMMouseScroll"]).__contains__(d.type))||!1===s||0===s||""===s?0:"object"==typeof s?"function"==typeof s.__nonzero__?s.__nonzero__():"function"==typeof s.__len__?0<s.__len__():1:1)e.type="undefined"!=typeof(B=
e.__class__._types).__array?"undefined"!=typeof B.__array[I=d.type]?B.__array[I]:B.__getitem__(I):B.__getitem__(d.type),e.button=d.btn,e.pos=$p.tuple([("undefined"!=typeof(N=d.pos).__array?"undefined"!=typeof N.__array[0]?N.__array[0]:N.__getitem__(0):N.__getitem__(0))+b.env.frame.scrollLeft,("undefined"!=typeof(M=d.pos).__array?"undefined"!=typeof M.__array[1]?M.__array[1]:M.__getitem__(1):M.__getitem__(1))+b.env.frame.scrollTop]);else if(null===(G=$p.tuple(["keydown","keyup"]).__contains__(d.type))||
!1===G||0===G||""===G?0:"object"==typeof G?"function"==typeof G.__nonzero__?G.__nonzero__():"function"==typeof G.__len__?0<G.__len__():1:1)e.type="undefined"!=typeof(O=e.__class__._types).__array?"undefined"!=typeof O.__array[P=d.type]?O.__array[P]:O.__getitem__(P):O.__getitem__(d.type),e.key=d.keyCode;else if(null===(H="keypress"===(K=d.type)&&null===K?!0:null===K?!1:"object"!=typeof K&&"function"!=typeof K||"function"!=typeof K.__cmp__?"keypress"==K:0===K.__cmp__("keypress"))||!1===H||0===H||""===
H?0:"object"==typeof H?"function"==typeof H.__nonzero__?H.__nonzero__():"function"==typeof H.__len__?0<H.__len__():1:1)e.type="undefined"!=typeof(E=e.__class__._types).__array?"undefined"!=typeof E.__array[q=d.type]?E.__array[q]:E.__getitem__(q):E.__getitem__(d.type),a=(null===(F=d.keyCode)||!1===F||0===F||""===F?0:"object"==typeof F?"function"==typeof F.__nonzero__?F.__nonzero__():"function"==typeof F.__len__?0<F.__len__():1:1)?d.keyCode:d.which,(null===(A=e.__class__._charCode.__contains__(a))||
!1===A||0===A||""===A?0:"object"==typeof A?"function"==typeof A.__nonzero__?A.__nonzero__():"function"==typeof A.__len__?0<A.__len__():1:1)?e.key="undefined"!=typeof(c=e.__class__._charCode).__array?"undefined"!=typeof c.__array[a]?c.__array[a]:c.__getitem__(a):c.__getitem__(a):e.key=a;else for(e.type=d.type,A=d.attr,"undefined"!=typeof(F=A.__array)?c=0:(A=A.__iter__(),c="undefined"!=typeof(F=A.__array)?0:"function"==typeof A.$genfunc?1:-1),h=0;"undefined"!=typeof(g=c?0<c?A.next(!0,!1):$p.wrapped_next(A):
F[h++]);)$p.object.__setattr__(e,g,"undefined"!=typeof(x=d.attr).__array?"undefined"!=typeof x.__array[a=g]?x.__array[a]:x.__getitem__(a):x.__getitem__(g));return null},1,[null,null,["self"],["event"]]);h.__init__=f;f=$pyjs__bind_method2("__repr__",function(b){b=!0===this.__is_instance__?this:b;var f;return(null===(f=$p.hasattr(b.event,"toString"))||!1===f||0===f||""===f?0:"object"==typeof f?"function"==typeof f.__nonzero__?f.__nonzero__():"function"==typeof f.__len__?0<f.__len__():1:1)?$p.sprintf("%s(%s)",
$p.tuple([b.__class__,b.event.toString()])):b.event.__repr__()},1,[null,null,["self"]]);h.__repr__=f;f=$pyjs__bind_method2("getEvent",function(b){return(!0===this.__is_instance__?this:b).event},1,[null,null,["self"]]);h.getEvent=f;f=Array($p.object);var B=$p.dict(),z;for(z in h)B.__setitem__(z,h[z]);return $p._create_class("JEvent",$p.tuple(f),B)}();b.TouchListener=function(){var h={},f;h.__module__="pyjsdl.event";f=$pyjs__bind_method2("__init__",function(d,f){if(!0===this.__is_instance__)var e=this;
else e=d,d=f;b._canvas=d;e.element=d.getElement();e.element.addEventListener("touchstart","undefined"==typeof _touch_detect?b._touch_detect:_touch_detect);e.active=!1;e.callback=$p.list([]);return null},1,[null,null,["self"],["canvas"]]);h.__init__=f;f=$pyjs__bind_method2("activate",function(d){d=!0===this.__is_instance__?this:d;d.element.removeEventListener("touchstart","undefined"==typeof _touch_detect?b._touch_detect:_touch_detect);d.element.addEventListener("touchstart","undefined"==typeof _touch_start?
b._touch_start:_touch_start);d.element.addEventListener("touchend","undefined"==typeof _touch_end?b._touch_end:_touch_end);d.element.addEventListener("touchmove","undefined"==typeof _touch_move?b._touch_move:_touch_move);d.element.addEventListener("touchcancel","undefined"==typeof _touch_cancel?b._touch_cancel:_touch_cancel);d.active=!0;return null},1,[null,null,["self"]]);h.activate=f;f=$pyjs__bind_method2("add_callback",function(b,f){if(!0===this.__is_instance__)var e=this;else e=b,b=f;e.callback.append(b);
return null},1,[null,null,["self"],["callback"]]);h.add_callback=f;f=$pyjs__bind_method2("is_active",function(b){return(!0===this.__is_instance__?this:b).active},1,[null,null,["self"]]);h.is_active=f;f=Array(pyjslib.object);var B=$p.dict(),z;for(z in h)B.__setitem__(z,h[z]);return $p._create_class("TouchListener",$p.tuple(f),B)}();b._canvas=null;b._touch_detect=function(h){b._canvas.onTouchInitiate(h);return null};b._touch_detect.__name__="_touch_detect";b._touch_detect.__bind_type__=0;b._touch_detect.__args__=
[null,null,["event"]];b._touch_start=function(h){b._canvas.onTouchStart(h);return null};b._touch_start.__name__="_touch_start";b._touch_start.__bind_type__=0;b._touch_start.__args__=[null,null,["event"]];b._touch_end=function(h){b._canvas.onTouchEnd(h);return null};b._touch_end.__name__="_touch_end";b._touch_end.__bind_type__=0;b._touch_end.__args__=[null,null,["event"]];b._touch_move=function(h){b._canvas.onTouchMove(h);return null};b._touch_move.__name__="_touch_move";b._touch_move.__bind_type__=
0;b._touch_move.__args__=[null,null,["event"]];b._touch_cancel=function(h){b._canvas.onTouchCancel(h);return null};b._touch_cancel.__name__="_touch_cancel";b._touch_cancel.__bind_type__=0;b._touch_cancel.__args__=[null,null,["event"]];return this};
