$pyjs.loaded_modules["pyjsdl.draw"]=function(z){if($pyjs.loaded_modules["pyjsdl.draw"].__was_initialized__)return $pyjs.loaded_modules["pyjsdl.draw"];"undefined"!=typeof $pyjs.loaded_modules.pyjsdl&&$pyjs.loaded_modules.pyjsdl.__was_initialized__||$p.___import___("pyjsdl",null);var p=$pyjs.loaded_modules["pyjsdl.draw"];p.__repr__=function(){return"<module: pyjsdl.draw>"};p.__was_initialized__=!0;if(null===z||"undefined"==typeof z)z="pyjsdl.draw";p.__name__=z;$pyjs.loaded_modules.pyjsdl.draw=$pyjs.loaded_modules["pyjsdl.draw"];
p._pi=$p.___import___("math.pi","pyjsdl",null,!1);p.Rect=$p.___import___("pyjsdl.rect.Rect","pyjsdl",null,!1);p.Surface=$p.___import___("pyjsdl.surface.Surface","pyjsdl",null,!1);p.Color=$p.___import___("pyjsdl.color.Color","pyjsdl",null,!1);p.__docformat__="restructuredtext";p.Draw=function(){var v={},r;v.__module__="pyjsdl.draw";r=$pyjs__bind_method2("__init__",function(a){(!0===this.__is_instance__?this:a).rad_deg=180/p._pi;return null},1,[null,null,["self"]]);v.__init__=r;r=$pyjs__bind_method2("rect",
function(a,f,m,k){!0!==this.__is_instance__&&(a=arguments[1],f=arguments[2],m=arguments[3],k=arguments[4]);"undefined"==typeof k&&(k=arguments.callee.__args__[6][1]);var h,b,d,c,e,g;g=(null===(d=$p.hasattr(m,"width"))||!1===d||0===d||""===d?0:"object"==typeof d?"function"==typeof d.__nonzero__?d.__nonzero__():"function"==typeof d.__len__?0<d.__len__():1:1)?m:p.Rect(m);(null===(h=k)||!1===h||0===h||""===h?0:"object"==typeof h?"function"==typeof h.__nonzero__?h.__nonzero__():"function"==typeof h.__len__?
0<h.__len__():1:1)?(a.setLineWidth(k),(null===(b=$p.hasattr(f,"a"))||!1===b||0===b||""===b?0:"object"==typeof b?"function"==typeof b.__nonzero__?b.__nonzero__():"function"==typeof b.__len__?0<b.__len__():1:1)?a.setStrokeStyle(f):a.setStrokeStyle(p.Color(f)),a.strokeRect(g.x,g.y,g.width,g.height)):((null===(c=$p.hasattr(f,"a"))||!1===c||0===c||""===c?0:"object"==typeof c?"function"==typeof c.__nonzero__?c.__nonzero__():"function"==typeof c.__len__?0<c.__len__():1:1)?a.setFillStyle(f):a.setFillStyle(p.Color(f)),
a.fillRect(g.x,g.y,g.width,g.height));return(null===(e=a._display)||!1===e||0===e||""===e?0:"object"==typeof e?"function"==typeof e.__nonzero__?e.__nonzero__():"function"==typeof e.__len__?0<e.__len__():1:1)?a._display._surface_rect.clip(g):a.get_rect().clip(g)},1,[null,null,["self"],["surface"],["color"],["rect"],["width",0]]);v.rect=r;r=$pyjs__bind_method2("circle",function(a,f,m,k,h){!0!==this.__is_instance__&&(a=arguments[1],f=arguments[2],m=arguments[3],k=arguments[4],h=arguments[5]);"undefined"==
typeof h&&(h=arguments.callee.__args__[7][1]);var b,d,c,e,g,l,q,n,u,t;a.beginPath();a.arc("undefined"!=typeof(n=m).__array?"undefined"!=typeof n.__array[0]?n.__array[0]:n.__getitem__(0):n.__getitem__(0),"undefined"!=typeof(q=m).__array?"undefined"!=typeof q.__array[1]?q.__array[1]:q.__getitem__(1):q.__getitem__(1),k,0,2*p._pi,!1);(null===(b=h)||!1===b||0===b||""===b?0:"object"==typeof b?"function"==typeof b.__nonzero__?b.__nonzero__():"function"==typeof b.__len__?0<b.__len__():1:1)?(a.setLineWidth(h),
(null===(d=$p.hasattr(f,"a"))||!1===d||0===d||""===d?0:"object"==typeof d?"function"==typeof d.__nonzero__?d.__nonzero__():"function"==typeof d.__len__?0<d.__len__():1:1)?a.setStrokeStyle(f):a.setStrokeStyle(p.Color(f)),a.stroke()):((null===(g=$p.hasattr(f,"a"))||!1===g||0===g||""===g?0:"object"==typeof g?"function"==typeof g.__nonzero__?g.__nonzero__():"function"==typeof g.__len__?0<g.__len__():1:1)?a.setFillStyle(f):a.setFillStyle(p.Color(f)),a.fill());return(null===(t=a._display)||!1===t||0===
t||""===t?0:"object"==typeof t?"function"==typeof t.__nonzero__?t.__nonzero__():"function"==typeof t.__len__?0<t.__len__():1:1)?a._display._surface_rect.clip(p.Rect(("undefined"!=typeof(l=m).__array?"undefined"!=typeof l.__array[0]?l.__array[0]:l.__getitem__(0):l.__getitem__(0))-k,("undefined"!=typeof(e=m).__array?"undefined"!=typeof e.__array[1]?e.__array[1]:e.__getitem__(1):e.__getitem__(1))-k,2*k,2*k)):a.get_rect().clip(p.Rect(("undefined"!=typeof(c=m).__array?"undefined"!=typeof c.__array[0]?
c.__array[0]:c.__getitem__(0):c.__getitem__(0))-k,("undefined"!=typeof(u=m).__array?"undefined"!=typeof u.__array[1]?u.__array[1]:u.__getitem__(1):u.__getitem__(1))-k,2*k,2*k))},1,[null,null,["self"],["surface"],["color"],["position"],["radius"],["width",0]]);v.circle=r;r=$pyjs__bind_method2("ellipse",function(a,f,m,k){!0!==this.__is_instance__&&(a=arguments[1],f=arguments[2],m=arguments[3],k=arguments[4]);"undefined"==typeof k&&(k=arguments.callee.__args__[6][1]);var h,b,d,c,e,g,l,q,n;l=(null===
(e=$p.hasattr(m,"width"))||!1===e||0===e||""===e?0:"object"==typeof e?"function"==typeof e.__nonzero__?e.__nonzero__():"function"==typeof e.__len__?0<e.__len__():1:1)?m:p.Rect(m);a.saveContext();a.translate(l.x+$p.float_int(l.width/2),l.y+$p.float_int(l.height/2));(null===(h=1==(((q=l.width)===(n=l.height)?0:typeof q!=typeof n||"number"!=typeof q&&"string"!=typeof q&&"boolean"!=typeof q?$p.cmp(q,n):q==n?0:q<n?-1:1)|1))||!1===h||0===h||""===h?0:"object"==typeof h?"function"==typeof h.__nonzero__?h.__nonzero__():
"function"==typeof h.__len__?0<h.__len__():1:1)?(a.scale(l.width/(1*l.height),1),h=l.height/2):(a.scale(1,l.height/(1*l.width)),h=l.width/2);a.beginPath();a.arc(0,0,h,0,2*p._pi,!1);(null===(b=k)||!1===b||0===b||""===b?0:"object"==typeof b?"function"==typeof b.__nonzero__?b.__nonzero__():"function"==typeof b.__len__?0<b.__len__():1:1)?(a.setLineWidth(k),(null===(g=$p.hasattr(f,"a"))||!1===g||0===g||""===g?0:"object"==typeof g?"function"==typeof g.__nonzero__?g.__nonzero__():"function"==typeof g.__len__?
0<g.__len__():1:1)?a.setStrokeStyle(f):a.setStrokeStyle(p.Color(f)),a.stroke()):((null===(d=$p.hasattr(f,"a"))||!1===d||0===d||""===d?0:"object"==typeof d?"function"==typeof d.__nonzero__?d.__nonzero__():"function"==typeof d.__len__?0<d.__len__():1:1)?a.setFillStyle(f):a.setFillStyle(p.Color(f)),a.fill());a.restoreContext();return(null===(c=a._display)||!1===c||0===c||""===c?0:"object"==typeof c?"function"==typeof c.__nonzero__?c.__nonzero__():"function"==typeof c.__len__?0<c.__len__():1:1)?a._display._surface_rect.clip(l):
a.get_rect().clip(l)},1,[null,null,["self"],["surface"],["color"],["rect"],["width",0]]);v.ellipse=r;r=$pyjs__bind_method2("arc",function(a,f,m,k,h,b){!0!==this.__is_instance__&&(a=arguments[1],f=arguments[2],m=arguments[3],k=arguments[4],h=arguments[5],b=arguments[6]);"undefined"==typeof b&&(b=arguments.callee.__args__[8][1]);var d,c,e,g,l,q,n,u,t,A,y,w,x,s,r;s=(null===(x=$p.hasattr(m,"width"))||!1===x||0===x||""===x?0:"object"==typeof x?"function"==typeof x.__nonzero__?x.__nonzero__():"function"==
typeof x.__len__?0<x.__len__():1:1)?m:p.Rect(m);(null===(e=(w=s.width)===(y=s.height)&&null===w?!0:null===w?!1:null===y?!1:"object"!=typeof w&&"function"!=typeof w||"function"!=typeof w.__cmp__?"object"!=typeof y&&"function"!=typeof y||"function"!=typeof y.__cmp__?w==y:0===y.__cmp__(w):0===w.__cmp__(y))||!1===e||0===e||""===e?0:"object"==typeof e?"function"==typeof e.__nonzero__?e.__nonzero__():"function"==typeof e.__len__?0<e.__len__():1:1)?(a.beginPath(),a.arc(s.x+$p.float_int(s.width/2),s.y+$p.float_int(s.height/
2),$p.float_int(s.width/2),-k,-h,!0),(null===(d=b)||!1===d||0===d||""===d?0:"object"==typeof d?"function"==typeof d.__nonzero__?d.__nonzero__():"function"==typeof d.__len__?0<d.__len__():1:1)?(a.setLineWidth(b),(null===(c=$p.hasattr(f,"a"))||!1===c||0===c||""===c?0:"object"==typeof c?"function"==typeof c.__nonzero__?c.__nonzero__():"function"==typeof c.__len__?0<c.__len__():1:1)?a.setStrokeStyle(f):a.setStrokeStyle(p.Color(f)),a.stroke()):(a.closePath(),(null===(n=$p.hasattr(f,"a"))||!1===n||0===
n||""===n?0:"object"==typeof n?"function"==typeof n.__nonzero__?n.__nonzero__():"function"==typeof n.__len__?0<n.__len__():1:1)?a.setFillStyle(f):a.setFillStyle(p.Color(f)),a.fill())):(a.saveContext(),a.translate(s.x+$p.float_int(s.width/2),s.y+$p.float_int(s.height/2)),(null===(q=1==(((r=s.width)===(A=s.height)?0:typeof r!=typeof A||"number"!=typeof r&&"string"!=typeof r&&"boolean"!=typeof r?$p.cmp(r,A):r==A?0:r<A?-1:1)|1))||!1===q||0===q||""===q?0:"object"==typeof q?"function"==typeof q.__nonzero__?
q.__nonzero__():"function"==typeof q.__len__?0<q.__len__():1:1)?(a.scale(s.width/(1*s.height),1),d=s.height/2):(a.scale(1,s.height/(1*s.width)),d=s.width/2),a.beginPath(),a.arc(0,0,d,-k,-h,!0),(null===(t=b)||!1===t||0===t||""===t?0:"object"==typeof t?"function"==typeof t.__nonzero__?t.__nonzero__():"function"==typeof t.__len__?0<t.__len__():1:1)?(a.setLineWidth(b),(null===(u=$p.hasattr(f,"a"))||!1===u||0===u||""===u?0:"object"==typeof u?"function"==typeof u.__nonzero__?u.__nonzero__():"function"==
typeof u.__len__?0<u.__len__():1:1)?a.setStrokeStyle(f):a.setStrokeStyle(p.Color(f)),a.stroke()):(a.closePath(),(null===(g=$p.hasattr(f,"a"))||!1===g||0===g||""===g?0:"object"==typeof g?"function"==typeof g.__nonzero__?g.__nonzero__():"function"==typeof g.__len__?0<g.__len__():1:1)?a.setFillStyle(f):a.setFillStyle(p.Color(f)),a.fill()),a.restoreContext());return(null===(l=a._display)||!1===l||0===l||""===l?0:"object"==typeof l?"function"==typeof l.__nonzero__?l.__nonzero__():"function"==typeof l.__len__?
0<l.__len__():1:1)?a._display._surface_rect.clip(s):a.get_rect().clip(s)},1,[null,null,["self"],["surface"],["color"],["rect"],["start_angle"],["stop_angle"],["width",1]]);v.arc=r;r=$pyjs__bind_method2("polygon",function(a,f,m,k){!0!==this.__is_instance__&&(a=arguments[1],f=arguments[2],m=arguments[3],k=arguments[4]);"undefined"==typeof k&&(k=arguments.callee.__args__[6][1]);var h,b,d,c,e,g,l,q,n;a.beginPath();$pyjs_kwargs_call(a,"moveTo","undefined"!=typeof(b=m).__array?"undefined"!=typeof b.__array[0]?
b.__array[0]:b.__getitem__(0):b.__getitem__(0),null,[{}]);b=$p.__getslice(m,1,null);"undefined"!=typeof(g=b.__array)?q=0:(b=b.__iter__(),q="undefined"!=typeof(g=b.__array)?0:"function"==typeof b.$genfunc?1:-1);for(n=0;"undefined"!=typeof(h=q?0<q?b.next(!0,!1):$p.wrapped_next(b):g[n++]);)$pyjs_kwargs_call(a,"lineTo",h,null,[{}]);a.closePath();(null===(e=k)||!1===e||0===e||""===e?0:"object"==typeof e?"function"==typeof e.__nonzero__?e.__nonzero__():"function"==typeof e.__len__?0<e.__len__():1:1)?(a.setLineWidth(k),
(null===(d=$p.hasattr(f,"a"))||!1===d||0===d||""===d?0:"object"==typeof d?"function"==typeof d.__nonzero__?d.__nonzero__():"function"==typeof d.__len__?0<d.__len__():1:1)?a.setStrokeStyle(f):a.setStrokeStyle(p.Color(f)),a.stroke()):((null===(c=$p.hasattr(f,"a"))||!1===c||0===c||""===c?0:"object"==typeof c?"function"==typeof c.__nonzero__?c.__nonzero__():"function"==typeof c.__len__?0<c.__len__():1:1)?a.setFillStyle(f):a.setFillStyle(p.Color(f)),a.fill());d=function(){var a,d,c,b,e,g,f;e=$p.list();
b=m;"undefined"!=typeof(f=b.__array)?c=0:(b=b.__iter__(),c="undefined"!=typeof(f=b.__array)?0:"function"==typeof b.$genfunc?1:-1);for(g=0;"undefined"!=typeof(d=c?0<c?b.next(!0,!1):$p.wrapped_next(b):f[g++]);)e.append("undefined"!=typeof(a=d).__array?"undefined"!=typeof a.__array[0]?a.__array[0]:a.__getitem__(0):a.__getitem__(0));return e}();c=function(){var a,b,c,d,e,g,f;d=$p.list();g=m;"undefined"!=typeof(c=g.__array)?f=0:(g=g.__iter__(),f="undefined"!=typeof(c=g.__array)?0:"function"==typeof g.$genfunc?
1:-1);for(a=0;"undefined"!=typeof(b=f?0<f?g.next(!0,!1):$p.wrapped_next(g):c[a++]);)d.append("undefined"!=typeof(e=b).__array?"undefined"!=typeof e.__array[1]?e.__array[1]:e.__getitem__(1):e.__getitem__(1));return d}();e=$p.__ass_unpack($p.tuple([$p.min(d),$p.max(d)]),2,null);d=e[0];e=e[1];b=$p.__ass_unpack($p.tuple([$p.min(c),$p.max(c)]),2,null);c=b[0];b=b[1];return(null===(l=a._display)||!1===l||0===l||""===l?0:"object"==typeof l?"function"==typeof l.__nonzero__?l.__nonzero__():"function"==typeof l.__len__?
0<l.__len__():1:1)?a._display._surface_rect.clip(p.Rect(d,c,e-d+1,b-c+1)):a.get_rect().clip(p.Rect(d,c,e-d+1,b-c+1))},1,[null,null,["self"],["surface"],["color"],["pointlist"],["width",0]]);v.polygon=r;r=$pyjs__bind_method2("line",function(a,f,m,k,h){!0!==this.__is_instance__&&(a=arguments[1],f=arguments[2],m=arguments[3],k=arguments[4],h=arguments[5]);"undefined"==typeof h&&(h=arguments.callee.__args__[7][1]);var b,d,c,e,g;a.beginPath();$pyjs_kwargs_call(a,"moveTo",m,null,[{}]);$pyjs_kwargs_call(a,
"lineTo",k,null,[{}]);a.setLineWidth(h);(null===(b=$p.hasattr(f,"a"))||!1===b||0===b||""===b?0:"object"==typeof b?"function"==typeof b.__nonzero__?b.__nonzero__():"function"==typeof b.__len__?0<b.__len__():1:1)?a.setStrokeStyle(f):a.setStrokeStyle(p.Color(f));a.stroke();b=function(){var a,b,c,d,e,g,f;b=$p.list();f=$p.tuple([m,k]);"undefined"!=typeof(g=f.__array)?e=0:(f=f.__iter__(),e="undefined"!=typeof(g=f.__array)?0:"function"==typeof f.$genfunc?1:-1);for(d=0;"undefined"!=typeof(a=e?0<e?f.next(!0,
!1):$p.wrapped_next(f):g[d++]);)b.append("undefined"!=typeof(c=a).__array?"undefined"!=typeof c.__array[0]?c.__array[0]:c.__getitem__(0):c.__getitem__(0));return b}();g=function(){var a,b,c,d,e,g,f;d=$p.list();e=$p.tuple([m,k]);"undefined"!=typeof(g=e.__array)?f=0:(e=e.__iter__(),f="undefined"!=typeof(g=e.__array)?0:"function"==typeof e.$genfunc?1:-1);for(c=0;"undefined"!=typeof(a=f?0<f?e.next(!0,!1):$p.wrapped_next(e):g[c++]);)d.append("undefined"!=typeof(b=a).__array?"undefined"!=typeof b.__array[1]?
b.__array[1]:b.__getitem__(1):b.__getitem__(1));return d}();e=$p.__ass_unpack($p.tuple([$p.min(b),$p.max(b)]),2,null);b=e[0];e=e[1];d=$p.__ass_unpack($p.tuple([$p.min(g),$p.max(g)]),2,null);g=d[0];d=d[1];return(null===(c=a._display)||!1===c||0===c||""===c?0:"object"==typeof c?"function"==typeof c.__nonzero__?c.__nonzero__():"function"==typeof c.__len__?0<c.__len__():1:1)?a._display._surface_rect.clip(p.Rect(b,g,e-b+1,d-g+1)):a.get_rect().clip(p.Rect(b,g,e-b+1,d-g+1))},1,[null,null,["self"],["surface"],
["color"],["point1"],["point2"],["width",1]]);v.line=r;r=$pyjs__bind_method2("lines",function(a,f,m,k,h){!0!==this.__is_instance__&&(a=arguments[1],f=arguments[2],m=arguments[3],k=arguments[4],h=arguments[5]);"undefined"==typeof h&&(h=arguments.callee.__args__[7][1]);var b,d,c,e,g,l,q,n;a.beginPath();$pyjs_kwargs_call(a,"moveTo","undefined"!=typeof(c=k).__array?"undefined"!=typeof c.__array[0]?c.__array[0]:c.__getitem__(0):c.__getitem__(0),null,[{}]);c=$p.__getslice(k,1,null);"undefined"!=typeof(q=
c.__array)?e=0:(c=c.__iter__(),e="undefined"!=typeof(q=c.__array)?0:"function"==typeof c.$genfunc?1:-1);for(l=0;"undefined"!=typeof(b=e?0<e?c.next(!0,!1):$p.wrapped_next(c):q[l++]);)$pyjs_kwargs_call(a,"lineTo",b,null,[{}]);(null===(d=m)||!1===d||0===d||""===d?0:"object"==typeof d?"function"==typeof d.__nonzero__?d.__nonzero__():"function"==typeof d.__len__?0<d.__len__():1:1)&&a.closePath();a.setLineWidth(h);(null===(n=$p.hasattr(f,"a"))||!1===n||0===n||""===n?0:"object"==typeof n?"function"==typeof n.__nonzero__?
n.__nonzero__():"function"==typeof n.__len__?0<n.__len__():1:1)?a.setStrokeStyle(f):a.setStrokeStyle(p.Color(f));a.stroke();d=function(){var a,b,c,d,e,f,g;c=$p.list();b=k;"undefined"!=typeof(d=b.__array)?g=0:(b=b.__iter__(),g="undefined"!=typeof(d=b.__array)?0:"function"==typeof b.$genfunc?1:-1);for(f=0;"undefined"!=typeof(a=g?0<g?b.next(!0,!1):$p.wrapped_next(b):d[f++]);)c.append("undefined"!=typeof(e=a).__array?"undefined"!=typeof e.__array[0]?e.__array[0]:e.__getitem__(0):e.__getitem__(0));return c}();
c=function(){var a,b,c,d,e,g,f;c=$p.list();f=k;"undefined"!=typeof(e=f.__array)?d=0:(f=f.__iter__(),d="undefined"!=typeof(e=f.__array)?0:"function"==typeof f.$genfunc?1:-1);for(a=0;"undefined"!=typeof(b=d?0<d?f.next(!0,!1):$p.wrapped_next(f):e[a++]);)c.append("undefined"!=typeof(g=b).__array?"undefined"!=typeof g.__array[1]?g.__array[1]:g.__getitem__(1):g.__getitem__(1));return c}();n=$p.__ass_unpack($p.tuple([$p.min(d),$p.max(d)]),2,null);d=n[0];n=n[1];e=$p.__ass_unpack($p.tuple([$p.min(c),$p.max(c)]),
2,null);c=e[0];e=e[1];return(null===(g=a._display)||!1===g||0===g||""===g?0:"object"==typeof g?"function"==typeof g.__nonzero__?g.__nonzero__():"function"==typeof g.__len__?0<g.__len__():1:1)?a._display._surface_rect.clip(p.Rect(d,c,n-d+1,e-c+1)):a.get_rect().clip(p.Rect(d,c,n-d+1,e-c+1))},1,[null,null,["self"],["surface"],["color"],["closed"],["pointlist"],["width",1]]);v.lines=r;r=$pyjs__bind_method2("aaline",function(a,f,m,k,h){if(!0===this.__is_instance__)var b=this;else b=arguments[0],a=arguments[1],
f=arguments[2],m=arguments[3],k=arguments[4],h=arguments[5];"undefined"==typeof h&&(h=arguments.callee.__args__[7][1]);return b.line(a,f,m,k,h)},1,[null,null,["self"],["surface"],["color"],["point1"],["point2"],["blend",1]]);v.aaline=r;r=$pyjs__bind_method2("aalines",function(a,f,m,k,h){if(!0===this.__is_instance__)var b=this;else b=arguments[0],a=arguments[1],f=arguments[2],m=arguments[3],k=arguments[4],h=arguments[5];"undefined"==typeof h&&(h=arguments.callee.__args__[7][1]);return b.lines(a,f,
m,k,h)},1,[null,null,["self"],["surface"],["color"],["closed"],["pointlist"],["blend",1]]);v.aalines=r;r=Array($p.object);var z=$p.dict(),B;for(B in v)z.__setitem__(B,v[B]);return $p._create_class("Draw",$p.tuple(r),z)}();return this};
