$pyjs.loaded_modules["pyjsdl.surface"]=function(B){if($pyjs.loaded_modules["pyjsdl.surface"].__was_initialized__)return $pyjs.loaded_modules["pyjsdl.surface"];"undefined"!=typeof $pyjs.loaded_modules.pyjsdl&&$pyjs.loaded_modules.pyjsdl.__was_initialized__||$p.___import___("pyjsdl",null);var m=$pyjs.loaded_modules["pyjsdl.surface"];m.__repr__=function(){return"<module: pyjsdl.surface>"};m.__was_initialized__=!0;if(null===B||"undefined"==typeof B)B="pyjsdl.surface";m.__name__=B;$pyjs.loaded_modules.pyjsdl.surface=
$pyjs.loaded_modules["pyjsdl.surface"];m.HTML5Canvas=$p.___import___("pyjsdl.pyjsobj.HTML5Canvas","pyjsdl",null,!1);m.Rect=$p.___import___("pyjsdl.rect.Rect","pyjsdl",null,!1);m.rectPool=$p.___import___("pyjsdl.rect.rectPool","pyjsdl",null,!1);m.Color=$p.___import___("pyjsdl.color.Color","pyjsdl",null,!1);m.__docformat__="restructuredtext";m.Surface=function(){var e={},b;e.__module__="pyjsdl.surface";b=$pyjs__bind_method2("__init__",function(a){if(!0===this.__is_instance__)var f=this,d=$p.tuple($pyjs_array_slice.call(arguments,
1,arguments.length-1)),c=2<=arguments.length?arguments[arguments.length-1]:arguments[arguments.length];else f=arguments[0],a=arguments[1],d=$p.tuple($pyjs_array_slice.call(arguments,2,arguments.length-1)),c=3<=arguments.length?arguments[arguments.length-1]:arguments[arguments.length];null===c||"object"!=typeof c||"dict"!=c.__name__||"undefined"==typeof c.$pyjs_is_kwarg?("undefined"!=typeof c&&d.__array.push(c),c=arguments[arguments.length+1]):delete c.$pyjs_is_kwarg;"undefined"==typeof c&&($p.__empty_dict(),
"undefined"!=typeof a?null!==a&&"undefined"!=typeof a.$pyjs_is_kwarg&&(a=arguments[2]):"undefined"!=typeof f&&null!==f&&"undefined"!=typeof f.$pyjs_is_kwarg&&(f=arguments[2]));var l,n;f.width=$p.float_int("undefined"!=typeof(n=a).__array?"undefined"!=typeof n.__array[0]?n.__array[0]:n.__getitem__(0):n.__getitem__(0));f.height=$p.float_int("undefined"!=typeof(l=a).__array?"undefined"!=typeof l.__array[1]?l.__array[1]:l.__getitem__(1):l.__getitem__(1));m.HTML5Canvas.__init__(f,f.width,f.height);m.HTML5Canvas.resize(f,
f.width,f.height);f._display=null;f._super_surface=null;f._offset=$p.tuple([0,0]);f._colorkey=null;f._nonimplemented_methods();return null},1,["args",["kwargs"],["self"],["size"]]);e.__init__=b;b=$pyjs__bind_method2("__repr__",function(a){a=!0===this.__is_instance__?this:a;return $p.sprintf("%s(%d,%d)",$p.tuple([a.__class__,a.width,a.height]))},1,[null,null,["self"]]);e.__repr__=b;b=$pyjs__bind_method2("get_size",function(a){a=!0===this.__is_instance__?this:a;return $p.tuple([a.width,a.height])},
1,[null,null,["self"]]);e.get_size=b;b=$pyjs__bind_method2("get_width",function(a){return(!0===this.__is_instance__?this:a).width},1,[null,null,["self"]]);e.get_width=b;b=$pyjs__bind_method2("get_height",function(a){return(!0===this.__is_instance__?this:a).height},1,[null,null,["self"]]);e.get_height=b;b=$pyjs__bind_method2("resize",function(a,f,d){if(!0===this.__is_instance__)var c=this;else c=a,a=f,f=d;c.width=$p.float_int(a);c.height=$p.float_int(f);m.HTML5Canvas.resize(c,c.width,c.height);return null},
1,[null,null,["self"],["width"],["height"]]);e.resize=b;b=$pyjs__bind_method2("get_rect",function(){if(!0===this.__is_instance__)var a=this,f=1<=arguments.length?arguments[arguments.length-1]:arguments[arguments.length];else a=arguments[0],f=2<=arguments.length?arguments[arguments.length-1]:arguments[arguments.length];null===f||"object"!=typeof f||"dict"!=f.__name__||"undefined"==typeof f.$pyjs_is_kwarg?f=arguments[arguments.length+1]:delete f.$pyjs_is_kwarg;"undefined"==typeof f&&(f=$p.__empty_dict(),
"undefined"!=typeof a&&null!==a&&"undefined"!=typeof a.$pyjs_is_kwarg&&(f=a,a=arguments[1]));var d,c,l,n,b,g,k;g=m.Rect(0,0,a.width,a.height);c=f;"undefined"!=typeof(n=c.__array)?k=0:(c=c.__iter__(),k="undefined"!=typeof(n=c.__array)?0:"function"==typeof c.$genfunc?1:-1);for(a=0;"undefined"!=typeof(d=k?0<k?c.next(!0,!1):$p.wrapped_next(c):n[a++]);)g.__setattr__(d,"undefined"!=typeof(b=f).__array?"undefined"!=typeof b.__array[l=d]?b.__array[l]:b.__getitem__(l):b.__getitem__(d));return g},1,[null,["attr"],
["self"]]);e.get_rect=b;b=$pyjs__bind_method2("copy",function(a){a=!0===this.__is_instance__?this:a;var f;f=m.Surface($p.tuple([a.width,a.height]));f.drawImage(a.canvas,0,0);return f},1,[null,null,["self"]]);e.copy=b;b=$pyjs__bind_method2("subsurface",function(a,f){if(!0===this.__is_instance__)var d=this;else d=a,a=f;var c,l,n,b,g,k,e,p,h,r,t,u;if(null===(k=$p.tuple(["t","f"]).__contains__(a))||!1===k||0===k||""===k?0:"object"==typeof k?"function"==typeof k.__nonzero__?k.__nonzero__():"function"==
typeof k.__len__?0<k.__len__():1:1){if(null===(g=!(null===(b=d._super_surface)||!1===b||0===b||""===b?0:"object"==typeof b?"function"==typeof b.__nonzero__?b.__nonzero__():"function"==typeof b.__len__?0<b.__len__():1:1))||!1===g||0===g||""===g?0:"object"==typeof g?"function"==typeof g.__nonzero__?g.__nonzero__():"function"==typeof g.__len__?0<g.__len__():1:1)return null;(null===(c="t"===(n=a)&&null===n?!0:null===n?!1:"object"!=typeof n&&"function"!=typeof n||"function"!=typeof n.__cmp__?"t"==n:0===
n.__cmp__("t"))||!1===c||0===c||""===c?0:"object"==typeof c?"function"==typeof c.__nonzero__?c.__nonzero__():"function"==typeof c.__len__?0<c.__len__():1:1)?d.drawImage(d._super_surface.canvas,"undefined"!=typeof(h=d._offset).__array?"undefined"!=typeof h.__array[0]?h.__array[0]:h.__getitem__(0):h.__getitem__(0),"undefined"!=typeof(p=d._offset).__array?"undefined"!=typeof p.__array[1]?p.__array[1]:p.__getitem__(1):p.__getitem__(1),d.width,d.height,0,0,d.width,d.height):d._super_surface.drawImage(d.canvas,
"undefined"!=typeof(r=d._offset).__array?"undefined"!=typeof r.__array[0]?r.__array[0]:r.__getitem__(0):r.__getitem__(0),"undefined"!=typeof(t=d._offset).__array?"undefined"!=typeof t.__array[1]?t.__array[1]:t.__getitem__(1):t.__getitem__(1));return null}c=(null===(l=$p.hasattr(a,"width"))||!1===l||0===l||""===l?0:"object"==typeof l?"function"==typeof l.__nonzero__?l.__nonzero__():"function"==typeof l.__len__?0<l.__len__():1:1)?a:m.Rect(a);if(null===(e=!(null===(u=d.get_rect().contains(c))||!1===
u||0===u||""===u?0:"object"==typeof u?"function"==typeof u.__nonzero__?u.__nonzero__():"function"==typeof u.__len__?0<u.__len__():1:1))||!1===e||0===e||""===e?0:"object"==typeof e?"function"==typeof e.__nonzero__?e.__nonzero__():"function"==typeof e.__len__?0<e.__len__():1:1)throw $p.ValueError("subsurface outside surface area");l=d.getSubimage(c.x,c.y,c.width,c.height);l._super_surface=d;l._offset=$p.tuple([c.x,c.y]);l._colorkey=d._colorkey;return l},1,[null,null,["self"],["rect"]]);e.subsurface=
b;b=$pyjs__bind_method2("getSubimage",function(a,f,d,c,l){if(!0===this.__is_instance__)var b=this;else b=a,a=f,f=d,d=c,c=l;l=m.Surface($p.tuple([d,c]));l.drawImage(b.canvas,a,f,d,c,0,0,d,c);return l},1,[null,null,["self"],["x"],["y"],["width"],["height"]]);e.getSubimage=b;b=$pyjs__bind_method2("blit",function(a,f,d){if(!0===this.__is_instance__)var c=this;else c=arguments[0],a=arguments[1],f=arguments[2],d=arguments[3];"undefined"==typeof d&&(d=arguments.callee.__args__[5][1]);var l,b,e,g,k,s,p,h,
r,t,u,x,w,y,z;(null===(r=!(null===(h=d)||!1===h||0===h||""===h?0:"object"==typeof h?"function"==typeof h.__nonzero__?h.__nonzero__():"function"==typeof h.__len__?0<h.__len__():1:1))||!1===r||0===r||""===r?0:"object"==typeof r?"function"==typeof r.__nonzero__?r.__nonzero__():"function"==typeof r.__len__?0<r.__len__():1:1)?(h=m.rectPool.get("undefined"!=typeof(t=f).__array?"undefined"!=typeof t.__array[0]?t.__array[0]:t.__getitem__(0):t.__getitem__(0),"undefined"!=typeof(u=f).__array?"undefined"!=typeof u.__array[1]?
u.__array[1]:u.__getitem__(1):u.__getitem__(1),a.width,a.height),c.impl.canvasContext.drawImage(a.canvas,h.x,h.y)):(h=m.rectPool.get("undefined"!=typeof(x=f).__array?"undefined"!=typeof x.__array[0]?x.__array[0]:x.__getitem__(0):x.__getitem__(0),"undefined"!=typeof(g=f).__array?"undefined"!=typeof g.__array[1]?g.__array[1]:g.__getitem__(1):g.__getitem__(1),"undefined"!=typeof(z=d).__array?"undefined"!=typeof z.__array[2]?z.__array[2]:z.__getitem__(2):z.__getitem__(2),"undefined"!=typeof(k=d).__array?
"undefined"!=typeof k.__array[3]?k.__array[3]:k.__getitem__(3):k.__getitem__(3)),c.impl.canvasContext.drawImage(a.canvas,"undefined"!=typeof(s=d).__array?"undefined"!=typeof s.__array[0]?s.__array[0]:s.__getitem__(0):s.__getitem__(0),"undefined"!=typeof(p=d).__array?"undefined"!=typeof p.__array[1]?p.__array[1]:p.__getitem__(1):p.__getitem__(1),"undefined"!=typeof(w=d).__array?"undefined"!=typeof w.__array[2]?w.__array[2]:w.__getitem__(2):w.__getitem__(2),"undefined"!=typeof(b=d).__array?"undefined"!=
typeof b.__array[3]?b.__array[3]:b.__getitem__(3):b.__getitem__(3),h.x,h.y,"undefined"!=typeof(e=d).__array?"undefined"!=typeof e.__array[2]?e.__array[2]:e.__getitem__(2):e.__getitem__(2),"undefined"!=typeof(y=d).__array?"undefined"!=typeof y.__array[3]?y.__array[3]:y.__getitem__(3):y.__getitem__(3)));c=((null===(l=c._display)||!1===l||0===l||""===l?0:"object"==typeof l?"function"==typeof l.__nonzero__?l.__nonzero__():"function"==typeof l.__len__?0<l.__len__():1:1)?c._display._surface_rect:c.get_rect()).clip(h);
m.rectPool.append(h);return c},1,[null,null,["self"],["surface"],["position"],["area",null]]);e.blit=b;b=$pyjs__bind_method2("_blits",function(a,f){if(!0===this.__is_instance__)var d=this;else d=a,a=f;var c,l,b,e,g;l=d.impl.canvasContext;c=a;"undefined"!=typeof(g=c.__array)?d=0:(c=c.__iter__(),d="undefined"!=typeof(g=c.__array)?0:"function"==typeof c.$genfunc?1:-1);for(e=0;"undefined"!=typeof(b=d?0<d?c.next(!0,!1):$p.wrapped_next(c):g[e++]);)l.drawImage(b.image.canvas,b.rect.x,b.rect.y);return null},
1,[null,null,["self"],["surfaces"]]);e._blits=b;b=$pyjs__bind_method2("_blit_clear",function(a,f,d){if(!0===this.__is_instance__)var c=this;else c=a,a=f,f=d;var b,n,e;d=c.impl.canvasContext;b=f;"undefined"!=typeof(n=b.__array)?f=0:(b=b.__iter__(),f="undefined"!=typeof(n=b.__array)?0:"function"==typeof b.$genfunc?1:-1);for(c=0;"undefined"!=typeof(e=f?0<f?b.next(!0,!1):$p.wrapped_next(b):n[c++]);)d.drawImage(a.canvas,e.x,e.y,e.width,e.height,e.x,e.y,e.width,e.height);return null},1,[null,null,["self"],
["surface"],["rect_list"]]);e._blit_clear=b;b=$pyjs__bind_method2("set_colorkey",function(a,f){if(!0===this.__is_instance__)var d=this;else d=arguments[0],a=arguments[1],f=arguments[2];"undefined"==typeof f&&(f=arguments.callee.__args__[4][1]);var c,b;if(null===(c=d._colorkey)||!1===c||0===c||""===c?0:"object"==typeof c?"function"==typeof c.__nonzero__?c.__nonzero__():"function"==typeof c.__len__?0<c.__len__():1:1)d._colorkey=null;if(null===(b=a)||!1===b||0===b||""===b?0:"object"==typeof b?"function"==
typeof b.__nonzero__?b.__nonzero__():"function"==typeof b.__len__?0<b.__len__():1:1)try{a=m.Color(a),d._colorkey=a,d.replace_color($p.tuple([a.r,a.g,a.b]))}catch(e){$pyjs.__last_exception__={error:e,module:m}}return null},1,[null,null,["self"],["color"],["flags",null]]);e.set_colorkey=b;b=$pyjs__bind_method2("get_colorkey",function(a){a=!0===this.__is_instance__?this:a;try{return $p.tuple([a._colorkey.r,a._colorkey.g,a._colorkey.b,255])}catch(f){a="undefined"==typeof f.__name__?f.name:f.__name__;
$pyjs.__last_exception__={error:f,module:m};if(a==$p.TypeError.__name__||$p._isinstance(f,$p.TypeError)||a==$p.AttributeError.__name__||$p._isinstance(f,$p.AttributeError))return null;$pyjs.__active_exception_stack__=$pyjs.__last_exception_stack__;$pyjs.__last_exception_stack__=null;throw f;}},1,[null,null,["self"]]);e.get_colorkey=b;b=$pyjs__bind_method2("_getPixel",function(a,f,d){!0!==this.__is_instance__&&(a=f,f=d);return a.data[f]},1,[null,null,["self"],["imagedata"],["index"]]);e._getPixel=
b;b=$pyjs__bind_method2("_setPixel",function(a,f,d,c){!0!==this.__is_instance__&&(a=f,f=d,d=c);d=$p.str(d);a.data[f]=d;return null},1,[null,null,["self"],["imagedata"],["index"],["dat"]]);e._setPixel=b;b=$pyjs__bind_method2("replace_color",function(a,f){if(!0===this.__is_instance__)var d=this;else d=arguments[0],a=arguments[1],f=arguments[2];"undefined"==typeof f&&(f=arguments.callee.__args__[4][1]);var c,b,e,q,g,k,s,p,h,r,t,u,x,w,y,z,v,A;z=d.impl.getImageData(0,0,d.width,d.height);w=(null===(e=$p.hasattr(a,
"a"))||!1===e||0===e||""===e?0:"object"==typeof e?"function"==typeof e.__nonzero__?e.__nonzero__():"function"==typeof e.__len__?0<e.__len__():1:1)?a:m.Color(a);e=(null===(q=f)||!1===q||0===q||""===q?0:"object"==typeof q?"function"==typeof q.__nonzero__?q.__nonzero__():"function"==typeof q.__len__?0<q.__len__():1:1)?(null===(g=$p.hasattr(f,"a"))||!1===g||0===g||""===g?0:"object"==typeof g?"function"==typeof g.__nonzero__?g.__nonzero__():"function"==typeof g.__len__?0<g.__len__():1:1)?f:m.Color(f):
m.Color(w.r,w.g,w.b,0);q=$p.tuple([w.r,w.g,w.b,w.a]);w=$p.tuple([e.r,e.g,e.b,e.a]);g=$p.xrange(0,null===(p=z.data)?0:"undefined"!=typeof p.__array?p.__array.length:"function"==typeof p.__len__?p.__len__():"undefined"!=typeof p.length?p.length:$p.len(p),4);"undefined"!=typeof(A=g.__array)?p=0:(g=g.__iter__(),p="undefined"!=typeof(A=g.__array)?0:"function"==typeof g.$genfunc?1:-1);for(e=0;"undefined"!=typeof(b=p?0<p?g.next(!0,!1):$p.wrapped_next(g):A[e++]);)if(v=b,null===(k=(x=$p.tuple([d._getPixel(z,
v),d._getPixel(z,v+1),d._getPixel(z,v+2),d._getPixel(z,v+3)]))===(y=q)&&null===x?!0:null===x?!1:null===y?!1:"object"!=typeof x&&"function"!=typeof x||"function"!=typeof x.__cmp__?"object"!=typeof y&&"function"!=typeof y||"function"!=typeof y.__cmp__?x==y:0===y.__cmp__(x):0===x.__cmp__(y))||!1===k||0===k||""===k?0:"object"==typeof k?"function"==typeof k.__nonzero__?k.__nonzero__():"function"==typeof k.__len__?0<k.__len__():1:1)for(s=$p.range(4),"undefined"!=typeof(b=s.__array)?r=0:(s=s.__iter__(),
r="undefined"!=typeof(b=s.__array)?0:"function"==typeof s.$genfunc?1:-1),t=0;"undefined"!=typeof(c=r?0<r?s.next(!0,!1):$p.wrapped_next(s):b[t++]);)d._setPixel(z,v+c,"undefined"!=typeof(h=w).__array?"undefined"!=typeof h.__array[u=c]?h.__array[u]:h.__getitem__(u):h.__getitem__(c));d.impl.putImageData(z,0,0,0,0,d.width,d.height);return null},1,[null,null,["self"],["color"],["new_color",null]]);e.replace_color=b;b=$pyjs__bind_method2("get_at",function(a,f){if(!0===this.__is_instance__)var d=this;else d=
a,a=f;var c,b,e;e=d.impl.getImageData("undefined"!=typeof(b=a).__array?"undefined"!=typeof b.__array[0]?b.__array[0]:b.__getitem__(0):b.__getitem__(0),"undefined"!=typeof(c=a).__array?"undefined"!=typeof c.__array[1]?c.__array[1]:c.__getitem__(1):c.__getitem__(1),1,1);return $p.tuple([d._getPixel(e,0),d._getPixel(e,1),d._getPixel(e,2),d._getPixel(e,3)])},1,[null,null,["self"],["pos"]]);e.get_at=b;b=$pyjs__bind_method2("set_at",function(a,f,d){if(!0===this.__is_instance__)var c=this;else c=a,a=f,f=
d;var b,e,q;f=(null===(b=$p.hasattr(f,"a"))||!1===b||0===b||""===b?0:"object"==typeof b?"function"==typeof b.__nonzero__?b.__nonzero__():"function"==typeof b.__len__?0<b.__len__():1:1)?f:m.Color(f);c.setFillStyle(f);c.fillRect("undefined"!=typeof(q=a).__array?"undefined"!=typeof q.__array[0]?q.__array[0]:q.__getitem__(0):q.__getitem__(0),"undefined"!=typeof(e=a).__array?"undefined"!=typeof e.__array[1]?e.__array[1]:e.__getitem__(1):e.__getitem__(1),1,1);return null},1,[null,null,["self"],["pos"],
["color"]]);e.set_at=b;b=$pyjs__bind_method2("fill",function(a,f){if(!0===this.__is_instance__)var b=this;else b=arguments[0],a=arguments[1],f=arguments[2];"undefined"==typeof a&&(a=arguments.callee.__args__[3][1]);"undefined"==typeof f&&(f=arguments.callee.__args__[4][1]);var c,e,n,q,g,k,s,p,h,r,t,u;if(null===(c=null===a)||!1===c||0===c||""===c?0:"object"==typeof c?"function"==typeof c.__nonzero__?c.__nonzero__():"function"==typeof c.__len__?0<c.__len__():1:1)return m.HTML5Canvas.fill(b),null;if(null===
(e=a)||!1===e||0===e||""===e?0:"object"==typeof e?"function"==typeof e.__nonzero__?e.__nonzero__():"function"==typeof e.__len__?0<e.__len__():1:1){(null===(p=$p.hasattr(a,"a"))||!1===p||0===p||""===p?0:"object"==typeof p?"function"==typeof p.__nonzero__?p.__nonzero__():"function"==typeof p.__len__?0<p.__len__():1:1)?b.setFillStyle(a):b.setFillStyle(m.Color(a));if(null===(r=!(null===(s=f)||!1===s||0===s||""===s?0:"object"==typeof s?"function"==typeof s.__nonzero__?s.__nonzero__():"function"==typeof s.__len__?
0<s.__len__():1:1))||!1===r||0===r||""===r?0:"object"==typeof r?"function"==typeof r.__nonzero__?r.__nonzero__():"function"==typeof r.__len__?0<r.__len__():1:1)h=m.Rect(0,0,b.width,b.height);else if(c=(null===(h=b._display)||!1===h||0===h||""===h?0:"object"==typeof h?"function"==typeof h.__nonzero__?h.__nonzero__():"function"==typeof h.__len__?0<h.__len__():1:1)?b._display._surface_rect:b.get_rect(),h=(null===(q=$p.hasattr(f,"width"))||!1===q||0===q||""===q?0:"object"==typeof q?"function"==typeof q.__nonzero__?
q.__nonzero__():"function"==typeof q.__len__?0<q.__len__():1:1)?c.clip(f):c.clip(m.Rect(f)),null===(t=(null===(k=u=!(null===(n=h.width)||!1===n||0===n||""===n?0:"object"==typeof n?"function"==typeof n.__nonzero__?n.__nonzero__():"function"==typeof n.__len__?0<n.__len__():1:1))||!1===k||0===k||""===k?0:"object"==typeof k?"function"==typeof k.__nonzero__?k.__nonzero__():"function"==typeof k.__len__?0<k.__len__():1:1)?u:!(null===(g=h.height)||!1===g||0===g||""===g?0:"object"==typeof g?"function"==typeof g.__nonzero__?
g.__nonzero__():"function"==typeof g.__len__?0<g.__len__():1:1))||!1===t||0===t||""===t?0:"object"==typeof t?"function"==typeof t.__nonzero__?t.__nonzero__():"function"==typeof t.__len__?0<t.__len__():1:1)return h;b.fillRect(h.x,h.y,h.width,h.height)}else h=m.Rect(0,0,b.width,b.height),b.clear();return h},1,[null,null,["self"],["color",null],["rect",null]]);e.fill=b;b=$pyjs__bind_method2("get_parent",function(a){return(!0===this.__is_instance__?this:a)._super_surface},1,[null,null,["self"]]);e.get_parent=
b;b=$pyjs__bind_method2("get_offset",function(a){return(!0===this.__is_instance__?this:a)._offset},1,[null,null,["self"]]);e.get_offset=b;b=$pyjs__bind_method2("toDataURL",function(a){if(!0===this.__is_instance__)var b=this;else b=arguments[0],a=arguments[1];"undefined"==typeof a&&(a=arguments.callee.__args__[3][1]);var d,c;return(null===(c=!(null===(d=a)||!1===d||0===d||""===d?0:"object"==typeof d?"function"==typeof d.__nonzero__?d.__nonzero__():"function"==typeof d.__len__?0<d.__len__():1:1))||
!1===c||0===c||""===c?0:"object"==typeof c?"function"==typeof c.__nonzero__?c.__nonzero__():"function"==typeof c.__len__?0<c.__len__():1:1)?b.canvas.toDataURL():b.canvas.toDataURL(a)},1,[null,null,["self"],["datatype",null]]);e.toDataURL=b;b=$pyjs__bind_method2("_nonimplemented_methods",function(a){var b=!0===this.__is_instance__?this:a;a=function(){$p.tuple($pyjs_array_slice.call(arguments,0,arguments.length));return b};a.__name__="$lambda1";a.__bind_type__=0;a.__args__=["arg",null];b.convert=a;
a=function(){$p.tuple($pyjs_array_slice.call(arguments,0,arguments.length));return b};a.__name__="$lambda2";a.__bind_type__=0;a.__args__=["arg",null];b.convert_alpha=a;a=function(){$p.tuple($pyjs_array_slice.call(arguments,0,arguments.length));return null};a.__name__="$lambda3";a.__bind_type__=0;a.__args__=["arg",null];b.set_alpha=a;a=function(){$p.tuple($pyjs_array_slice.call(arguments,0,arguments.length));return null};a.__name__="$lambda4";a.__bind_type__=0;a.__args__=["arg",null];b.get_alpha=a;
a=function(){$p.tuple($pyjs_array_slice.call(arguments,0,arguments.length));return null};a.__name__="$lambda5";a.__bind_type__=0;a.__args__=["arg",null];b.lock=a;a=function(){$p.tuple($pyjs_array_slice.call(arguments,0,arguments.length));return null};a.__name__="$lambda6";a.__bind_type__=0;a.__args__=["arg",null];b.unlock=a;a=function(){$p.tuple($pyjs_array_slice.call(arguments,0,arguments.length));return!1};a.__name__="$lambda7";a.__bind_type__=0;a.__args__=["arg",null];b.mustlock=a;a=function(){$p.tuple($pyjs_array_slice.call(arguments,
0,arguments.length));return!1};a.__name__="$lambda8";a.__bind_type__=0;a.__args__=["arg",null];b.get_locked=a;a=function(){$p.tuple($pyjs_array_slice.call(arguments,0,arguments.length));return $p.tuple([])};a.__name__="$lambda9";a.__bind_type__=0;a.__args__=["arg",null];b.get_locks=a;return null},1,[null,null,["self"]]);e._nonimplemented_methods=b;b=Array(m.HTML5Canvas);var A=$p.dict(),v;for(v in e)A.__setitem__(v,e[v]);return $p._create_class("Surface",$p.tuple(b),A)}();m.Surf=function(){var e={},
b;e.__module__="pyjsdl.surface";b=$pyjs__bind_method2("__init__",function(a,b){if(!0===this.__is_instance__)var d=this;else d=a,a=b;d.canvas=a;var c=$p.__ass_unpack($p.tuple([d.canvas.width,d.canvas.height]),2,null);d.width=c[0];d.height=c[1];d._nonimplemented_methods();return null},1,[null,null,["self"],["image"]]);e.__init__=b;b=$pyjs__bind_method2("get_size",function(a){a=!0===this.__is_instance__?this:a;return $p.tuple([a.width,a.height])},1,[null,null,["self"]]);e.get_size=b;b=$pyjs__bind_method2("get_width",
function(a){return(!0===this.__is_instance__?this:a).width},1,[null,null,["self"]]);e.get_width=b;b=$pyjs__bind_method2("get_height",function(a){return(!0===this.__is_instance__?this:a).height},1,[null,null,["self"]]);e.get_height=b;b=$pyjs__bind_method2("get_rect",function(){if(!0===this.__is_instance__)var a=this,b=1<=arguments.length?arguments[arguments.length-1]:arguments[arguments.length];else a=arguments[0],b=2<=arguments.length?arguments[arguments.length-1]:arguments[arguments.length];null===
b||"object"!=typeof b||"dict"!=b.__name__||"undefined"==typeof b.$pyjs_is_kwarg?b=arguments[arguments.length+1]:delete b.$pyjs_is_kwarg;"undefined"==typeof b&&(b=$p.__empty_dict(),"undefined"!=typeof a&&null!==a&&"undefined"!=typeof a.$pyjs_is_kwarg&&(b=a,a=arguments[1]));var d,c,e,n,q,g,k;k=m.Rect(0,0,a.width,a.height);g=b;"undefined"!=typeof(e=g.__array)?c=0:(g=g.__iter__(),c="undefined"!=typeof(e=g.__array)?0:"function"==typeof g.$genfunc?1:-1);for(a=0;"undefined"!=typeof(n=c?0<c?g.next(!0,!1):
$p.wrapped_next(g):e[a++]);)k.__setattr__(n,"undefined"!=typeof(d=b).__array?"undefined"!=typeof d.__array[q=n]?d.__array[q]:d.__getitem__(q):d.__getitem__(n));return k},1,[null,["attr"],["self"]]);e.get_rect=b;b=$pyjs__bind_method2("_nonimplemented_methods",function(a){var b=!0===this.__is_instance__?this:a;a=function(){$p.tuple($pyjs_array_slice.call(arguments,0,arguments.length));return b};a.__name__="$lambda10";a.__bind_type__=0;a.__args__=["arg",null];b.convert=a;a=function(){$p.tuple($pyjs_array_slice.call(arguments,
0,arguments.length));return b};a.__name__="$lambda11";a.__bind_type__=0;a.__args__=["arg",null];b.convert_alpha=a;a=function(){$p.tuple($pyjs_array_slice.call(arguments,0,arguments.length));return null};a.__name__="$lambda12";a.__bind_type__=0;a.__args__=["arg",null];b.set_alpha=a;a=function(){$p.tuple($pyjs_array_slice.call(arguments,0,arguments.length));return null};a.__name__="$lambda13";a.__bind_type__=0;a.__args__=["arg",null];b.get_alpha=a;a=function(){$p.tuple($pyjs_array_slice.call(arguments,
0,arguments.length));return null};a.__name__="$lambda14";a.__bind_type__=0;a.__args__=["arg",null];b.lock=a;a=function(){$p.tuple($pyjs_array_slice.call(arguments,0,arguments.length));return null};a.__name__="$lambda15";a.__bind_type__=0;a.__args__=["arg",null];b.unlock=a;a=function(){$p.tuple($pyjs_array_slice.call(arguments,0,arguments.length));return!1};a.__name__="$lambda16";a.__bind_type__=0;a.__args__=["arg",null];b.mustlock=a;a=function(){$p.tuple($pyjs_array_slice.call(arguments,0,arguments.length));
return!1};a.__name__="$lambda17";a.__bind_type__=0;a.__args__=["arg",null];b.get_locked=a;a=function(){$p.tuple($pyjs_array_slice.call(arguments,0,arguments.length));return $p.tuple([])};a.__name__="$lambda18";a.__bind_type__=0;a.__args__=["arg",null];b.get_locks=a;return null},1,[null,null,["self"]]);e._nonimplemented_methods=b;b=Array($p.object);var A=$p.dict(),v;for(v in e)A.__setitem__(v,e[v]);return $p._create_class("Surf",$p.tuple(b),A)}();m.IndexSizeError=function(){var e={__module__:"pyjsdl.surface"},
b=Array($p.Exception),m=$p.dict(),v;for(v in e)m.__setitem__(v,e[v]);return $p._create_class("IndexSizeError",$p.tuple(b),m)}();return this};
