$pyjs.loaded_modules.chimp=function(t){if($pyjs.loaded_modules.chimp.__was_initialized__)return $pyjs.loaded_modules.chimp;var b=$pyjs.loaded_modules.chimp;b.__repr__=function(){return"<module: chimp>"};b.__was_initialized__=!0;if(null===t||"undefined"==typeof t)t="chimp";b.__name__=t;var r,V,L,W,X,P,Q,M,Y,N,Z,$,aa,O,z,H,F,I,J,S,ba;b.os=$p.___import___("os",null);b.sys=$p.___import___("sys",null);try{b.pg=$p.___import___("pygame",null,null,!1),b.geterror=$p.___import___("pygame.compat.geterror",null,
null,!1),b.engine="pygame"}catch(R){if(t="undefined"==typeof R.__name__?R.name:R.__name__,$pyjs.__last_exception__={error:R,module:b},t==$p.ImportError.__name__||$p._isinstance(R,$p.ImportError))b.pg=$p.___import___("pyjsdl",null,null,!1),t=function(){var e;return"undefined"!=typeof(e=b.sys.exc_info()).__array?"undefined"!=typeof e.__array[1]?e.__array[1]:e.__getitem__(1):e.__getitem__(1)},t.__name__="$lambda1",t.__bind_type__=0,t.__args__=[null,null],b.geterror=t,b.pg.sprite.__is_instance__&&"function"==
typeof b.pg.sprite.__setattr__?b.pg.sprite.__setattr__("RenderPlain",null==(P=(Q=b.pg.sprite).Group)||Q.__is_instance__&&"function"==typeof P||"function"==typeof P.__get__?$p.getattr(Q,"Group"):b.pg.sprite.Group):$p.setattr(b.pg.sprite,"RenderPlain",null==(P=(Q=b.pg.sprite).Group)||Q.__is_instance__&&"function"==typeof P||"function"==typeof P.__get__?$p.getattr(Q,"Group"):b.pg.sprite.Group),b.engine="pyjsdl";else throw $pyjs.__active_exception_stack__=$pyjs.__last_exception_stack__,$pyjs.__last_exception_stack__=
null,R;}null===(O=!(null===(H=null==(Y=($=b.pg).font)||$.__is_instance__&&"function"==typeof Y||"function"==typeof Y.__get__?$p.getattr($,"font"):b.pg.font)||!1===H||0===H||""===H?0:"object"==typeof H?"function"==typeof H.__nonzero__?H.__nonzero__():"function"==typeof H.__len__?0<H.__len__():1:1))||!1===O||0===O||""===O||"object"==typeof O&&("function"==typeof O.__nonzero__?O.__nonzero__():"function"==typeof O.__len__&&O.__len__());null===(I=!(null===(z=null==(Z=(aa=b.pg).mixer)||aa.__is_instance__&&
"function"==typeof Z||"function"==typeof Z.__get__?$p.getattr(aa,"mixer"):b.pg.mixer)||!1===z||0===z||""===z?0:"object"==typeof z?"function"==typeof z.__nonzero__?z.__nonzero__():"function"==typeof z.__len__?0<z.__len__():1:1))||!1===I||0===I||""===I||"object"==typeof I&&("function"==typeof I.__nonzero__?I.__nonzero__():"function"==typeof I.__len__&&I.__len__());if(null===(J="pygame"===(N=b.engine)&&null===N?!0:null===N?!1:"object"!=typeof N&&"function"!=typeof N||"function"!=typeof N.__cmp__?"pygame"==
N:0===N.__cmp__("pygame"))||!1===J||0===J||""===J?0:"object"==typeof J?"function"==typeof J.__nonzero__?J.__nonzero__():"function"==typeof J.__len__?0<J.__len__():1:1)b.main_dir="undefined"!=typeof(S=b.os.path.$$split(b.os.path.abspath("/home/jg/projects/webdev/pyjs/app/apps/webapp/demo-pack/chimp.py"))).__array?"undefined"!=typeof S.__array[0]?S.__array[0]:S.__getitem__(0):S.__getitem__(0),b.data_dir=b.os.path.join(b.main_dir,"public/data");else if(null===(F="pyjsdl"===(M=b.engine)&&null===M?!0:
null===M?!1:"object"!=typeof M&&"function"!=typeof M||"function"!=typeof M.__cmp__?"pyjsdl"==M:0===M.__cmp__("pyjsdl"))||!1===F||0===F||""===F?0:"object"==typeof F?"function"==typeof F.__nonzero__?F.__nonzero__():"function"==typeof F.__len__?0<F.__len__():1:1)b.main_dir="",b.data_dir=b.os.path.join(b.main_dir,"data");b.load_image=function(e,c){"undefined"==typeof c&&(c=arguments.callee.__args__[3][1]);var h,f,a,d,g,k,n,q,u,m,p;e=("undefined"!=typeof(q=e.$$split(".")).__array?"undefined"!=typeof q.__array[0]?
q.__array[0]:q.__getitem__(0):q.__getitem__(0))+".png";q=b.os.path.join(b.data_dir,e);try{a=b.pg.image.load(q)}catch(l){a="undefined"==typeof l.__name__?l.name:l.__name__;$pyjs.__last_exception__={error:l,module:b};if(a==(null==(d=(f=b.pg).error)||f.__is_instance__&&"function"==typeof d||"function"==typeof d.__get__?$p.getattr(f,"error"):b.pg.error).__name__||$p._isinstance(l,null==(h=(m=b.pg).error)||m.__is_instance__&&"function"==typeof h||"function"==typeof h.__get__?$p.getattr(m,"error"):b.pg.error))throw $p.SystemExit($p.str(b.geterror()));
$pyjs.__active_exception_stack__=$pyjs.__last_exception_stack__;$pyjs.__last_exception_stack__=null;throw l;}a=a.convert();if(null===(n=null!==c)||!1===n||0===n||""===n?0:"object"==typeof n?"function"==typeof n.__nonzero__?n.__nonzero__():"function"==typeof n.__len__?0<n.__len__():1:1){if(null===(k=-1===(g=c)&&null===g?!0:null===g?!1:"object"!=typeof g&&"function"!=typeof g||"function"!=typeof g.__cmp__?-1==g:0===g.__cmp__(-1))||!1===k||0===k||""===k?0:"object"==typeof k?"function"==typeof k.__nonzero__?
k.__nonzero__():"function"==typeof k.__len__?0<k.__len__():1:1)c=a.get_at($p.tuple([0,0]));a.set_colorkey(c,null==(u=(p=b.pg).RLEACCEL)||p.__is_instance__&&"function"==typeof u||"function"==typeof u.__get__?$p.getattr(p,"RLEACCEL"):b.pg.RLEACCEL)}return $p.tuple([a,a.get_rect()])};b.load_image.__name__="load_image";b.load_image.__bind_type__=0;b.load_image.__args__=[null,null,["name"],["colorkey",null]];b.load_sound=function(e){var c,h,f,a,d,g,k,n,q,u,m,p;b.NoneSound=function(){var a={},b;a.__module__=
"chimp";b=$pyjs__bind_method2("play",function(a){return null},1,[null,null,["self"]]);a.play=b;b=Array(pyjslib.object);var d=$p.dict(),g;for(g in a)d.__setitem__(g,a[g]);return $p._create_class("NoneSound",$p.tuple(b),d)}();if(null===(g=(null===(a=f=!(null===(m=null==(p=(u=b.pg).mixer)||u.__is_instance__&&"function"==typeof p||"function"==typeof p.__get__?$p.getattr(u,"mixer"):b.pg.mixer)||!1===m||0===m||""===m?0:"object"==typeof m?"function"==typeof m.__nonzero__?m.__nonzero__():"function"==typeof m.__len__?
0<m.__len__():1:1))||!1===a||0===a||""===a?0:"object"==typeof a?"function"==typeof a.__nonzero__?a.__nonzero__():"function"==typeof a.__len__?0<a.__len__():1:1)?f:!(null===(d=b.pg.mixer.get_init())||!1===d||0===d||""===d?0:"object"==typeof d?"function"==typeof d.__nonzero__?d.__nonzero__():"function"==typeof d.__len__?0<d.__len__():1:1))||!1===g||0===g||""===g?0:"object"==typeof g?"function"==typeof g.__nonzero__?g.__nonzero__():"function"==typeof g.__len__?0<g.__len__():1:1)return b.NoneSound();
e=b.os.path.join(b.data_dir,e);try{c=b.pg.mixer.Sound(e)}catch(l){c="undefined"==typeof l.__name__?l.name:l.__name__;$pyjs.__last_exception__={error:l,module:b};if(c==(null==(q=(h=b.pg).error)||h.__is_instance__&&"function"==typeof q||"function"==typeof q.__get__?$p.getattr(h,"error"):b.pg.error).__name__||$p._isinstance(l,null==(k=(n=b.pg).error)||n.__is_instance__&&"function"==typeof k||"function"==typeof k.__get__?$p.getattr(n,"error"):b.pg.error))throw $p.SystemExit($p.str(b.geterror()));$pyjs.__active_exception_stack__=
$pyjs.__last_exception_stack__;$pyjs.__last_exception_stack__=null;throw l;}return c};b.load_sound.__name__="load_sound";b.load_sound.__bind_type__=0;b.load_sound.__args__=[null,null,["name"]];b.Fist=function(){var e={},c;e.__module__="chimp";c=$pyjs__bind_method2("__init__",function(a){a=!0===this.__is_instance__?this:a;b.pg.sprite.Sprite.__init__(a);var d=$p.__ass_unpack(b.load_image("fist.bmp",-1),2,null);a.__is_instance__&&"function"==typeof a.__setattr__?a.__setattr__("image",d[0]):$p.setattr(a,
"image",d[0]);a.__is_instance__&&"function"==typeof a.__setattr__?a.__setattr__("rect",d[1]):$p.setattr(a,"rect",d[1]);a.__is_instance__&&"function"==typeof a.__setattr__?a.__setattr__("punching",0):$p.setattr(a,"punching",0);return null},1,[null,null,["self"]]);e.__init__=c;c=$pyjs__bind_method2("update",function(a){a=!0===this.__is_instance__?this:a;var d,g,c;c=b.pg.mouse.get_pos();a.rect.__is_instance__&&"function"==typeof a.rect.__setattr__?a.rect.__setattr__("midtop",c):$p.setattr(a.rect,"midtop",
c);(null===(g=null==(d=a.punching)||a.__is_instance__&&"function"==typeof d||"function"==typeof d.__get__?$p.getattr(a,"punching"):a.punching)||!1===g||0===g||""===g?0:"object"==typeof g?"function"==typeof g.__nonzero__?g.__nonzero__():"function"==typeof g.__len__?0<g.__len__():1:1)&&a.rect.move_ip(5,10);return null},1,[null,null,["self"]]);e.update=c;c=$pyjs__bind_method2("punch",function(a,b){if(!0===this.__is_instance__)var g=this;else g=a,a=b;var c,e,f,h,m,p;return(null===(e=!(null===(c=null==
(f=(h=g).punching)||h.__is_instance__&&"function"==typeof f||"function"==typeof f.__get__?$p.getattr(h,"punching"):g.punching)||!1===c||0===c||""===c?0:"object"==typeof c?"function"==typeof c.__nonzero__?c.__nonzero__():"function"==typeof c.__len__?0<c.__len__():1:1))||!1===e||0===e||""===e?0:"object"==typeof e?"function"==typeof e.__nonzero__?e.__nonzero__():"function"==typeof e.__len__?0<e.__len__():1:1)?(g.__is_instance__&&"function"==typeof g.__setattr__?g.__setattr__("punching",1):$p.setattr(g,
"punching",1),g=g.rect.inflate(-5,-5),g.colliderect(null==(m=(p=a).rect)||p.__is_instance__&&"function"==typeof m||"function"==typeof m.__get__?$p.getattr(p,"rect"):a.rect)):null},1,[null,null,["self"],["target"]]);e.punch=c;c=$pyjs__bind_method2("unpunch",function(a){a=!0===this.__is_instance__?this:a;a.__is_instance__&&"function"==typeof a.__setattr__?a.__setattr__("punching",0):$p.setattr(a,"punching",0);return null},1,[null,null,["self"]]);e.unpunch=c;c=Array(null==(ba=(V=b.pg.sprite).Sprite)||
V.__is_instance__&&"function"==typeof ba||"function"==typeof ba.__get__?$p.getattr(V,"Sprite"):b.pg.sprite.Sprite);var h=$p.dict(),f;for(f in e)h.__setitem__(f,e[f]);return $p._create_class("Fist",$p.tuple(c),h)}();b.Chimp=function(){var e={},c;e.__module__="chimp";c=$pyjs__bind_method2("__init__",function(a){a=!0===this.__is_instance__?this:a;var d;b.pg.sprite.Sprite.__init__(a);d=$p.__ass_unpack(b.load_image("chimp.bmp",-1),2,null);a.__is_instance__&&"function"==typeof a.__setattr__?a.__setattr__("image",
d[0]):$p.setattr(a,"image",d[0]);a.__is_instance__&&"function"==typeof a.__setattr__?a.__setattr__("rect",d[1]):$p.setattr(a,"rect",d[1]);d=b.pg.display.get_surface();a.__is_instance__&&"function"==typeof a.__setattr__?a.__setattr__("area",d.get_rect()):$p.setattr(a,"area",d.get_rect());a.rect.__is_instance__&&"function"==typeof a.rect.__setattr__?a.rect.__setattr__("topleft",$p.tuple([10,10])):$p.setattr(a.rect,"topleft",$p.tuple([10,10]));a.__is_instance__&&"function"==typeof a.__setattr__?a.__setattr__("move",
9):$p.setattr(a,"move",9);a.__is_instance__&&"function"==typeof a.__setattr__?a.__setattr__("dizzy",0):$p.setattr(a,"dizzy",0);return null},1,[null,null,["self"]]);e.__init__=c;c=$pyjs__bind_method2("update",function(a){a=!0===this.__is_instance__?this:a;var b,g;(null===(g=null==(b=a.dizzy)||a.__is_instance__&&"function"==typeof b||"function"==typeof b.__get__?$p.getattr(a,"dizzy"):a.dizzy)||!1===g||0===g||""===g?0:"object"==typeof g?"function"==typeof g.__nonzero__?g.__nonzero__():"function"==typeof g.__len__?
0<g.__len__():1:1)?a._spin():a._walk();return null},1,[null,null,["self"]]);e.update=c;c=$pyjs__bind_method2("_walk",function(a){a=!0===this.__is_instance__?this:a;var d,g,c,e,f,h,m,p,l,v,t,s,x,w,B,y,ca,r,K,D,C,A,G,E;E=a.rect.move($p.tuple([null==(x=a.move)||a.__is_instance__&&"function"==typeof x||"function"==typeof x.__get__?$p.getattr(a,"move"):a.move,0]));if(null===(d=!(null===(c=a.area.contains(E))||!1===c||0===c||""===c?0:"object"==typeof c?"function"==typeof c.__nonzero__?c.__nonzero__():"function"==
typeof c.__len__?0<c.__len__():1:1))||!1===d||0===d||""===d?0:"object"==typeof d?"function"==typeof d.__nonzero__?d.__nonzero__():"function"==typeof d.__len__?0<d.__len__():1:1){if(null===(v=(null===(g=t=-1==((C=null==(s=(ca=a.rect).left)||ca.__is_instance__&&"function"==typeof s||"function"==typeof s.__get__?$p.getattr(ca,"left"):a.rect.left)===(G=null==(y=(B=a.area).left)||B.__is_instance__&&"function"==typeof y||"function"==typeof y.__get__?$p.getattr(B,"left"):a.area.left)?0:typeof C!=typeof G||
"number"!=typeof C&&"string"!=typeof C&&"boolean"!=typeof C?$p.cmp(C,G):C==G?0:C<G?-1:1))||!1===g||0===g||""===g?0:"object"==typeof g?"function"==typeof g.__nonzero__?g.__nonzero__():"function"==typeof g.__len__?0<g.__len__():1:1)?t:1==((A=null==(w=(K=a.rect).right)||K.__is_instance__&&"function"==typeof w||"function"==typeof w.__get__?$p.getattr(K,"right"):a.rect.right)===(D=null==(r=(p=a.area).right)||p.__is_instance__&&"function"==typeof r||"function"==typeof r.__get__?$p.getattr(p,"right"):a.area.right)?
0:typeof A!=typeof D||"number"!=typeof A&&"string"!=typeof A&&"boolean"!=typeof A?$p.cmp(A,D):A==D?0:A<D?-1:1))||!1===v||0===v||""===v?0:"object"==typeof v?"function"==typeof v.__nonzero__?v.__nonzero__():"function"==typeof v.__len__?0<v.__len__():1:1)a.__is_instance__&&"function"==typeof a.__setattr__?a.__setattr__("move",-(null==(l=(h=a).move)||h.__is_instance__&&"function"==typeof l||"function"==typeof l.__get__?$p.getattr(h,"move"):a.move)):$p.setattr(a,"move",-(null==(l=(h=a).move)||h.__is_instance__&&
"function"==typeof l||"function"==typeof l.__get__?$p.getattr(h,"move"):a.move)),E=a.rect.move($p.tuple([null==(m=a.move)||a.__is_instance__&&"function"==typeof m||"function"==typeof m.__get__?$p.getattr(a,"move"):a.move,0])),a.__is_instance__&&"function"==typeof a.__setattr__?a.__setattr__("image",b.pg.transform.flip(null==(f=(e=a).image)||e.__is_instance__&&"function"==typeof f||"function"==typeof f.__get__?$p.getattr(e,"image"):a.image,1,0)):$p.setattr(a,"image",b.pg.transform.flip(null==(f=(e=
a).image)||e.__is_instance__&&"function"==typeof f||"function"==typeof f.__get__?$p.getattr(e,"image"):a.image,1,0));a.__is_instance__&&"function"==typeof a.__setattr__?a.__setattr__("rect",E):$p.setattr(a,"rect",E)}return null},1,[null,null,["self"]]);e._walk=c;c=$pyjs__bind_method2("_spin",function(a){a=!0===this.__is_instance__?this:a;var d,c,e,f,h,u,m,p,l,v,t,s,x,w,B,y;e=null==(t=(B=a.rect).center)||B.__is_instance__&&"function"==typeof t||"function"==typeof t.__get__?$p.getattr(B,"center"):a.rect.center;
a.__is_instance__&&"function"==typeof a.__setattr__?a.__setattr__("dizzy",(null==(y=(u=a).dizzy)||u.__is_instance__&&"function"==typeof y||"function"==typeof y.__get__?$p.getattr(u,"dizzy"):a.dizzy)+12):$p.setattr(a,"dizzy",(null==(y=(u=a).dizzy)||u.__is_instance__&&"function"==typeof y||"function"==typeof y.__get__?$p.getattr(u,"dizzy"):a.dizzy)+12);(null===(s=1==((360===(d=null==(h=a.dizzy)||a.__is_instance__&&"function"==typeof h||"function"==typeof h.__get__?$p.getattr(a,"dizzy"):a.dizzy)?0:"number"!=
typeof d||"number"!=typeof d&&"string"!=typeof d&&"boolean"!=typeof d?$p.cmp(d,360):360==d?0:360>d?-1:1)|1))||!1===s||0===s||""===s?0:"object"==typeof s?"function"==typeof s.__nonzero__?s.__nonzero__():"function"==typeof s.__len__?0<s.__len__():1:1)?(a.__is_instance__&&"function"==typeof a.__setattr__?a.__setattr__("dizzy",0):$p.setattr(a,"dizzy",0),a.__is_instance__&&"function"==typeof a.__setattr__?a.__setattr__("image",null==(w=(p=a).original)||p.__is_instance__&&"function"==typeof w||"function"==
typeof w.__get__?$p.getattr(p,"original"):a.original):$p.setattr(a,"image",null==(w=(p=a).original)||p.__is_instance__&&"function"==typeof w||"function"==typeof w.__get__?$p.getattr(p,"original"):a.original)):(d=null==(m=(v=b.pg.transform).rotate)||v.__is_instance__&&"function"==typeof m||"function"==typeof m.__get__?$p.getattr(v,"rotate"):b.pg.transform.rotate,a.__is_instance__&&"function"==typeof a.__setattr__?a.__setattr__("image",d(null==(l=(c=a).original)||c.__is_instance__&&"function"==typeof l||
"function"==typeof l.__get__?$p.getattr(c,"original"):a.original,null==(x=(f=a).dizzy)||f.__is_instance__&&"function"==typeof x||"function"==typeof x.__get__?$p.getattr(f,"dizzy"):a.dizzy)):$p.setattr(a,"image",d(null==(l=(c=a).original)||c.__is_instance__&&"function"==typeof l||"function"==typeof l.__get__?$p.getattr(c,"original"):a.original,null==(x=(f=a).dizzy)||f.__is_instance__&&"function"==typeof x||"function"==typeof x.__get__?$p.getattr(f,"dizzy"):a.dizzy)));a.__is_instance__&&"function"==
typeof a.__setattr__?a.__setattr__("rect",$pyjs_kwargs_call(a.image,"get_rect",null,null,[{center:e}])):$p.setattr(a,"rect",$pyjs_kwargs_call(a.image,"get_rect",null,null,[{center:e}]));return null},1,[null,null,["self"]]);e._spin=c;c=$pyjs__bind_method2("punched",function(a){a=!0===this.__is_instance__?this:a;var b,c,e,f,h;if(null===(f=!(null===(h=null==(c=a.dizzy)||a.__is_instance__&&"function"==typeof c||"function"==typeof c.__get__?$p.getattr(a,"dizzy"):a.dizzy)||!1===h||0===h||""===h?0:"object"==
typeof h?"function"==typeof h.__nonzero__?h.__nonzero__():"function"==typeof h.__len__?0<h.__len__():1:1))||!1===f||0===f||""===f?0:"object"==typeof f?"function"==typeof f.__nonzero__?f.__nonzero__():"function"==typeof f.__len__?0<f.__len__():1:1)a.__is_instance__&&"function"==typeof a.__setattr__?a.__setattr__("dizzy",1):$p.setattr(a,"dizzy",1),a.__is_instance__&&"function"==typeof a.__setattr__?a.__setattr__("original",null==(e=(b=a).image)||b.__is_instance__&&"function"==typeof e||"function"==
typeof e.__get__?$p.getattr(b,"image"):a.image):$p.setattr(a,"original",null==(e=(b=a).image)||b.__is_instance__&&"function"==typeof e||"function"==typeof e.__get__?$p.getattr(b,"image"):a.image);return null},1,[null,null,["self"]]);e.punched=c;c=Array(null==(W=(X=b.pg.sprite).Sprite)||X.__is_instance__&&"function"==typeof W||"function"==typeof W.__get__?$p.getattr(X,"Sprite"):b.pg.sprite.Sprite);var h=$p.dict(),f;for(f in e)h.__setitem__(f,e[f]);return $p._create_class("Chimp",$p.tuple(c),h)}();
b.$assign1=null;b.screen=b.$assign1;b.background=b.$assign1;b.clock=b.$assign1;b.$assign2=null;b.whiff_sound=b.$assign2;b.punch_sound=b.$assign2;b.chimp=b.$assign2;b.fist=b.$assign2;b.allsprites=b.$assign2;b.$assign3=!0;b.start=b.$assign3;b.going=b.$assign3;b.pause=function(){var e,c,h,f,a,d,g,k,n,q,u,m,p,l,v;d=b.pg.mouse.get_pos();if(null===(g=(null===(c=h=b.start)||!1===c||0===c||""===c?0:"object"==typeof c?"function"==typeof c.__nonzero__?c.__nonzero__():"function"==typeof c.__len__?0<c.__len__():
1:1)?!(d===(e=$p.tuple([-1,-1]))&&null===d||(null===d?0:null===e?0:"object"!=typeof d&&"function"!=typeof d||"function"!=typeof d.__cmp__?"object"!=typeof e&&"function"!=typeof e||"function"!=typeof e.__cmp__?d==e:0===e.__cmp__(d):0===d.__cmp__(e))):h)||!1===g||0===g||""===g?0:"object"==typeof g?"function"==typeof g.__nonzero__?g.__nonzero__():"function"==typeof g.__len__?0<g.__len__():1:1)b.start=!1;return(null===(q=(null===(k=f=!(null===(n=b.start)||!1===n||0===n||""===n?0:"object"==typeof n?"function"==
typeof n.__nonzero__?n.__nonzero__():"function"==typeof n.__len__?0<n.__len__():1:1))||!1===k||0===k||""===k?0:"object"==typeof k?"function"==typeof k.__nonzero__?k.__nonzero__():"function"==typeof k.__len__?0<k.__len__():1:1)?(null===(l=a=d===(m=$p.tuple([-1,-1]))&&null===d?!0:null===d?!1:null===m?!1:"object"!=typeof d&&"function"!=typeof d||"function"!=typeof d.__cmp__?"object"!=typeof m&&"function"!=typeof m||"function"!=typeof m.__cmp__?d==m:0===m.__cmp__(d):0===d.__cmp__(m))||!1===l||0===l||
""===l?0:"object"==typeof l?"function"==typeof l.__nonzero__?l.__nonzero__():"function"==typeof l.__len__?0<l.__len__():1:1)?!(null===(p=null==(u=(v=b.chimp).dizzy)||v.__is_instance__&&"function"==typeof u||"function"==typeof u.__get__?$p.getattr(v,"dizzy"):b.chimp.dizzy)||!1===p||0===p||""===p?0:"object"==typeof p?"function"==typeof p.__nonzero__?p.__nonzero__():"function"==typeof p.__len__?0<p.__len__():1:1):a:f)||!1===q||0===q||""===q?0:"object"==typeof q?"function"==typeof q.__nonzero__?q.__nonzero__():
"function"==typeof q.__len__?0<q.__len__():1:1)?(b.pg.time.wait(100),!0):!1};b.pause.__name__="pause";b.pause.__bind_type__=0;b.pause.__args__=[null,null];b.setup=function(){var e,c,h,f,a,d,g,k,n,q;b.pg.init();(null===(f="pyjsdl"===(k=b.engine)&&null===k?!0:null===k?!1:"object"!=typeof k&&"function"!=typeof k||"function"!=typeof k.__cmp__?"pyjsdl"==k:0===k.__cmp__("pyjsdl"))||!1===f||0===f||""===f?0:"object"==typeof f?"function"==typeof f.__nonzero__?f.__nonzero__():"function"==typeof f.__len__?0<
f.__len__():1:1)&&$pyjs_kwargs_call(b.pg.mixer,"init",null,null,[{size:-16,channels:2,buffer:1024},11025]);f=b.pg.display.set_mode($p.tuple([468,60]));b.pg.display.set_caption("Monkey Fever");b.pg.mouse.set_visible(0);k=b.pg.Surface(f.get_size());k=k.convert();k.fill($p.tuple([250,250,250]));if(null===(d=null==(a=(c=b.pg).font)||c.__is_instance__&&"function"==typeof a||"function"==typeof a.__get__?$p.getattr(c,"font"):b.pg.font)||!1===d||0===d||""===d?0:"object"==typeof d?"function"==typeof d.__nonzero__?
d.__nonzero__():"function"==typeof d.__len__?0<d.__len__():1:1){if(null===(g="pygame"===(n=b.engine)&&null===n?!0:null===n?!1:"object"!=typeof n&&"function"!=typeof n||"function"!=typeof n.__cmp__?"pygame"==n:0===n.__cmp__("pygame"))||!1===g||0===g||""===g?0:"object"==typeof g?"function"==typeof g.__nonzero__?g.__nonzero__():"function"==typeof g.__len__?0<g.__len__():1:1)e=b.pg.font.Font(null,36);else if(null===(h="pyjsdl"===(q=b.engine)&&null===q?!0:null===q?!1:"object"!=typeof q&&"function"!=typeof q||
"function"!=typeof q.__cmp__?"pyjsdl"==q:0===q.__cmp__("pyjsdl"))||!1===h||0===h||""===h?0:"object"==typeof h?"function"==typeof h.__nonzero__?h.__nonzero__():"function"==typeof h.__len__?0<h.__len__():1:1)e=b.pg.font.Font(null,24);e=e.render("Pummel The Chimp, And Win $$$",1,$p.tuple([10,10,10]));c=$pyjs_kwargs_call(e,"get_rect",null,null,[{centerx:k.get_width()/2}]);k.blit(e,c)}f.blit(k,$p.tuple([0,0]));b.pg.display.flip();return $p.tuple([f,k])};b.setup.__name__="setup";b.setup.__bind_type__=0;
b.setup.__args__=[null,null];b.prerun=function(){var e,c,h,f,a,d;b.clock=b.pg.time.Clock();if(null===(c="pygame"===(d=b.engine)&&null===d?!0:null===d?!1:"object"!=typeof d&&"function"!=typeof d||"function"!=typeof d.__cmp__?"pygame"==d:0===d.__cmp__("pygame"))||!1===c||0===c||""===c?0:"object"==typeof c?"function"==typeof c.__nonzero__?c.__nonzero__():"function"==typeof c.__len__?0<c.__len__():1:1)b.whiff_sound=b.load_sound("whiff-st.wav"),b.punch_sound=b.load_sound("punch-st.wav");else if(null===
(f="pyjsdl"===(h=b.engine)&&null===h?!0:null===h?!1:"object"!=typeof h&&"function"!=typeof h||"function"!=typeof h.__cmp__?"pyjsdl"==h:0===h.__cmp__("pyjsdl"))||!1===f||0===f||""===f?0:"object"==typeof f?"function"==typeof f.__nonzero__?f.__nonzero__():"function"==typeof f.__len__?0<f.__len__():1:1)b.whiff_sound=b.load_sound("whiff-st.mp3"),b.punch_sound=b.load_sound("punch-st.mp3");b.chimp=b.Chimp();b.fist=b.Fist();b.allsprites=b.pg.sprite.RenderPlain($p.tuple([b.fist,b.chimp]));(null===(a="pyjsdl"===
(e=b.engine)&&null===e?!0:null===e?!1:"object"!=typeof e&&"function"!=typeof e||"function"!=typeof e.__cmp__?"pyjsdl"==e:0===e.__cmp__("pyjsdl"))||!1===a||0===a||""===a?0:"object"==typeof a?"function"==typeof a.__nonzero__?a.__nonzero__():"function"==typeof a.__len__?0<a.__len__():1:1)&&b.pg.set_callback("undefined"==typeof run?b.run:run);return null};b.prerun.__name__="prerun";b.prerun.__bind_type__=0;b.prerun.__args__=[null,null];b.run=function(){var e,c,h,f,a,d,g,k,n,q,u,m,p,l,v,t,s,x,w,B,y,r,
O,K,D,C,A,G,E,z,H,F,I,J,L,M,N,P,Q,R,S,V,W,T,U;b.going=!0;b.clock.tick(60);e=b.pg.event.get();"undefined"!=typeof(t=e.__array)?F=0:(e=e.__iter__(),F="undefined"!=typeof(t=e.__array)?0:"function"==typeof e.$genfunc?1:-1);for(W=0;"undefined"!=typeof(d=F?0<F?e.next(!0,!1):$p.wrapped_next(e):t[W++]);)(null===(T=(K=null==(m=(V=d).type)||V.__is_instance__&&"function"==typeof m||"function"==typeof m.__get__?$p.getattr(V,"type"):d.type)===(C=null==(S=(R=b.pg).QUIT)||R.__is_instance__&&"function"==typeof S||
"function"==typeof S.__get__?$p.getattr(R,"QUIT"):b.pg.QUIT)&&null===K?!0:null===K?!1:null===C?!1:"object"!=typeof K&&"function"!=typeof K||"function"!=typeof K.__cmp__?"object"!=typeof C&&"function"!=typeof C||"function"!=typeof C.__cmp__?K==C:0===C.__cmp__(K):0===K.__cmp__(C))||!1===T||0===T||""===T?0:"object"==typeof T?"function"==typeof T.__nonzero__?T.__nonzero__():"function"==typeof T.__len__?0<T.__len__():1:1)?b.going=!1:(null===(r=(null===(U=O=(D=null==(Q=(P=d).type)||P.__is_instance__&&"function"==
typeof Q||"function"==typeof Q.__get__?$p.getattr(P,"type"):d.type)===(G=null==(N=(M=b.pg).KEYDOWN)||M.__is_instance__&&"function"==typeof N||"function"==typeof N.__get__?$p.getattr(M,"KEYDOWN"):b.pg.KEYDOWN)&&null===D?!0:null===D?!1:null===G?!1:"object"!=typeof D&&"function"!=typeof D||"function"!=typeof D.__cmp__?"object"!=typeof G&&"function"!=typeof G||"function"!=typeof G.__cmp__?D==G:0===G.__cmp__(D):0===D.__cmp__(G))||!1===U||0===U||""===U?0:"object"==typeof U?"function"==typeof U.__nonzero__?
U.__nonzero__():"function"==typeof U.__len__?0<U.__len__():1:1)?(A=null==(L=(J=d).key)||J.__is_instance__&&"function"==typeof L||"function"==typeof L.__get__?$p.getattr(J,"key"):d.key)===(z=null==(I=(n=b.pg).K_ESCAPE)||n.__is_instance__&&"function"==typeof I||"function"==typeof I.__get__?$p.getattr(n,"K_ESCAPE"):b.pg.K_ESCAPE)&&null===A?!0:null===A?!1:null===z?!1:"object"!=typeof A&&"function"!=typeof A||"function"!=typeof A.__cmp__?"object"!=typeof z&&"function"!=typeof z||"function"!=typeof z.__cmp__?
A==z:0===z.__cmp__(A):0===A.__cmp__(z):O)||!1===r||0===r||""===r?0:"object"==typeof r?"function"==typeof r.__nonzero__?r.__nonzero__():"function"==typeof r.__len__?0<r.__len__():1:1)?b.going=!1:(null===(y=(E=null==(q=(g=d).type)||g.__is_instance__&&"function"==typeof q||"function"==typeof q.__get__?$p.getattr(g,"type"):d.type)===(h=null==(k=(p=b.pg).MOUSEBUTTONDOWN)||p.__is_instance__&&"function"==typeof k||"function"==typeof k.__get__?$p.getattr(p,"MOUSEBUTTONDOWN"):b.pg.MOUSEBUTTONDOWN)&&null===
E?!0:null===E?!1:null===h?!1:"object"!=typeof E&&"function"!=typeof E||"function"!=typeof E.__cmp__?"object"!=typeof h&&"function"!=typeof h||"function"!=typeof h.__cmp__?E==h:0===h.__cmp__(E):0===E.__cmp__(h))||!1===y||0===y||""===y?0:"object"==typeof y?"function"==typeof y.__nonzero__?y.__nonzero__():"function"==typeof y.__len__?0<y.__len__():1:1)?(null===(B=b.fist.punch(b.chimp))||!1===B||0===B||""===B?0:"object"==typeof B?"function"==typeof B.__nonzero__?B.__nonzero__():"function"==typeof B.__len__?
0<B.__len__():1:1)?(b.punch_sound.play(),b.chimp.punched()):b.whiff_sound.play():(null===(a=(f=null==(l=(u=d).type)||u.__is_instance__&&"function"==typeof l||"function"==typeof l.__get__?$p.getattr(u,"type"):d.type)===(c=null==(H=(v=b.pg).MOUSEBUTTONUP)||v.__is_instance__&&"function"==typeof H||"function"==typeof H.__get__?$p.getattr(v,"MOUSEBUTTONUP"):b.pg.MOUSEBUTTONUP)&&null===f?!0:null===f?!1:null===c?!1:"object"!=typeof f&&"function"!=typeof f||"function"!=typeof f.__cmp__?"object"!=typeof c&&
"function"!=typeof c||"function"!=typeof c.__cmp__?f==c:0===c.__cmp__(f):0===f.__cmp__(c))||!1===a||0===a||""===a?0:"object"==typeof a?"function"==typeof a.__nonzero__?a.__nonzero__():"function"==typeof a.__len__?0<a.__len__():1:1)&&b.fist.unpunch();if(null===(x=!(null===(w=b.going)||!1===w||0===w||""===w?0:"object"==typeof w?"function"==typeof w.__nonzero__?w.__nonzero__():"function"==typeof w.__len__?0<w.__len__():1:1))||!1===x||0===x||""===x?0:"object"==typeof x?"function"==typeof x.__nonzero__?
x.__nonzero__():"function"==typeof x.__len__?0<x.__len__():1:1)return b.pg.quit(),null;if(null===(s=b.pause())||!1===s||0===s||""===s?0:"object"==typeof s?"function"==typeof s.__nonzero__?s.__nonzero__():"function"==typeof s.__len__?0<s.__len__():1:1)return null;b.allsprites.update();b.screen.blit(b.background,$p.tuple([0,0]));b.allsprites.draw(b.screen);b.pg.display.flip();return null};b.run.__name__="run";b.run.__bind_type__=0;b.run.__args__=[null,null];b.main=function(){var e,c,h,f,a,d=$p.__ass_unpack(b.setup(),
2,null);b.screen=d[0];b.background=d[1];if(null===(e="pygame"===(f=b.engine)&&null===f?!0:null===f?!1:"object"!=typeof f&&"function"!=typeof f||"function"!=typeof f.__cmp__?"pygame"==f:0===f.__cmp__("pygame"))||!1===e||0===e||""===e?0:"object"==typeof e?"function"==typeof e.__nonzero__?e.__nonzero__():"function"==typeof e.__len__?0<e.__len__():1:1)for(b.prerun();null===(h=b.going)||!1===h||0===h||""===h?0:"object"==typeof h?"function"==typeof h.__nonzero__?h.__nonzero__():"function"==typeof h.__len__?
0<h.__len__():1:1;)b.run();else(null===(c="pyjsdl"===(a=b.engine)&&null===a?!0:null===a?!1:"object"!=typeof a&&"function"!=typeof a||"function"!=typeof a.__cmp__?"pyjsdl"==a:0===a.__cmp__("pyjsdl"))||!1===c||0===c||""===c?0:"object"==typeof c?"function"==typeof c.__nonzero__?c.__nonzero__():"function"==typeof c.__len__?0<c.__len__():1:1)&&b.pg.setup(b.prerun,$p.list(["./data/chimp.png","./data/fist.png"]));return null};b.main.__name__="main";b.main.__bind_type__=0;b.main.__args__=[null,null];(null===
(r="__main__"===(L="undefined"==typeof __name__?b.__name__:__name__)&&null===L?!0:null===L?!1:"object"!=typeof L&&"function"!=typeof L||"function"!=typeof L.__cmp__?"__main__"==L:0===L.__cmp__("__main__"))||!1===r||0===r||""===r?0:"object"==typeof r?"function"==typeof r.__nonzero__?r.__nonzero__():"function"==typeof r.__len__?0<r.__len__():1:1)&&b.main();return this};
