$pyjs.loaded_modules["pyjamas.Canvas.GWTCanvas"]=function(l){if($pyjs.loaded_modules["pyjamas.Canvas.GWTCanvas"].__was_initialized__)return $pyjs.loaded_modules["pyjamas.Canvas.GWTCanvas"];"undefined"!=typeof $pyjs.loaded_modules["pyjamas.Canvas"]&&$pyjs.loaded_modules["pyjamas.Canvas"].__was_initialized__||$p.___import___("pyjamas.Canvas",null);var g=$pyjs.loaded_modules["pyjamas.Canvas.GWTCanvas"];g.__repr__=function(){return"<module: pyjamas.Canvas.GWTCanvas>"};g.__was_initialized__=!0;if(null===
l||"undefined"==typeof l)l="pyjamas.Canvas.GWTCanvas";g.__name__=l;$pyjs.loaded_modules["pyjamas.Canvas"].GWTCanvas=$pyjs.loaded_modules["pyjamas.Canvas.GWTCanvas"];g.DOM=$p.___import___("pyjamas.DOM","pyjamas.Canvas",null,!1);g.FocusWidget=$p.___import___("pyjamas.ui.FocusWidget.FocusWidget","pyjamas.Canvas",null,!1);g.Widget=$p.___import___("pyjamas.ui.Widget.Widget","pyjamas.Canvas",null,!1);g.Focus=$p.___import___("pyjamas.ui.Focus","pyjamas.Canvas",null,!1);g.Color=$p.___import___("pyjamas.Canvas.Color.Color",
"pyjamas.Canvas",null,!1);g.LinearGradientImplDefault=$p.___import___("pyjamas.Canvas.LinearGradientImplDefault.LinearGradientImplDefault","pyjamas.Canvas",null,!1);g.RadialGradientImplDefault=$p.___import___("pyjamas.Canvas.RadialGradientImplDefault.RadialGradientImplDefault","pyjamas.Canvas",null,!1);g.GWTCanvasImplDefault=$p.___import___("pyjamas.Canvas.GWTCanvasImplDefault.GWTCanvasImplDefault","pyjamas.Canvas",null,!1);g.LinearGradientImplIE6=$p.___import___("pyjamas.Canvas.LinearGradientImplIE6.LinearGradientImplIE6",
"pyjamas.Canvas",null,!1);g.RadialGradientImplIE6=$p.___import___("pyjamas.Canvas.RadialGradientImplIE6.RadialGradientImplIE6","pyjamas.Canvas",null,!1);g.GWTCanvasImplIE6=$p.___import___("pyjamas.Canvas.GWTCanvasImplIE6.GWTCanvasImplIE6","pyjamas.Canvas",null,!1);g.GWTCanvas=function(){var d={},a;d.__module__="pyjamas.Canvas.GWTCanvas";a=$pyjs__bind_method2("__init__",function(b,h,c,a){if(!0===this.__is_instance__)var e=this,f=5<=arguments.length?arguments[arguments.length-1]:arguments[arguments.length];
else e=arguments[0],b=arguments[1],h=arguments[2],c=arguments[3],a=arguments[4],f=6<=arguments.length?arguments[arguments.length-1]:arguments[arguments.length];null===f||"object"!=typeof f||"dict"!=f.__name__||"undefined"==typeof f.$pyjs_is_kwarg?f=arguments[arguments.length+1]:delete f.$pyjs_is_kwarg;"undefined"==typeof f&&(f=$p.__empty_dict(),"undefined"!=typeof a?null!==a&&"undefined"!=typeof a.$pyjs_is_kwarg&&(f=a,a=arguments[5]):"undefined"!=typeof c?null!==c&&"undefined"!=typeof c.$pyjs_is_kwarg&&
(f=c,c=arguments[5]):"undefined"!=typeof h?null!==h&&"undefined"!=typeof h.$pyjs_is_kwarg&&(f=h,h=arguments[5]):"undefined"!=typeof b?null!==b&&"undefined"!=typeof b.$pyjs_is_kwarg&&(f=b,b=arguments[5]):"undefined"!=typeof e&&null!==e&&"undefined"!=typeof e.$pyjs_is_kwarg&&(f=e,e=arguments[5]));"undefined"==typeof b&&(b=arguments.callee.__args__[3][1]);"undefined"==typeof h&&(h=arguments.callee.__args__[4][1]);"undefined"==typeof c&&(c=arguments.callee.__args__[5][1]);"undefined"==typeof a&&(a=arguments.callee.__args__[6][1]);
var d,k,m;e.__is_instance__&&"function"==typeof e.__setattr__?e.__setattr__("impl",e.getCanvasImpl()):$p.setattr(e,"impl",e.getCanvasImpl());e.__is_instance__&&"function"==typeof e.__setattr__?e.__setattr__("coordHeight",0):$p.setattr(e,"coordHeight",0);e.__is_instance__&&"function"==typeof e.__setattr__?e.__setattr__("coordWidth",0):$p.setattr(e,"coordWidth",0);m=g.Focus.createFocusable();e.__is_instance__&&"function"==typeof e.__setattr__?e.__setattr__("canvas",e.impl.createElement()):$p.setattr(e,
"canvas",e.impl.createElement());g.DOM.appendChild(m,null==(k=(d=e).canvas)||d.__is_instance__&&"function"==typeof k||"function"==typeof k.__get__?$p.getattr(d,"canvas"):e.canvas);$pyjs_kwargs_call(g.FocusWidget,"__init__",null,f,[{},e,m]);e.setPixelWidth(c);e.setPixelHeight(a);e.setCoordSize(b,h);return null},1,[null,["kwargs"],["self"],["coordX",300],["coordY",150],["pixelX",300],["pixelY",150]]);d.__init__=a;a=$pyjs__bind_method2("getCanvasElement",function(b){b=!0===this.__is_instance__?this:
b;var h;return null==(h=b.canvas)||b.__is_instance__&&"function"==typeof h||"function"==typeof h.__get__?$p.getattr(b,"canvas"):b.canvas},1,[null,null,["self"]]);d.getCanvasElement=a;a=$pyjs__bind_method2("getCanvasImpl",function(b){return g.GWTCanvasImplIE6()},1,[null,null,["self"]]);d.getCanvasImpl=a;a=$pyjs__bind_method2("setWidth",function(b,h){if(!0===this.__is_instance__)var c=this;else c=b,b=h;c.setPixelWidth(b);return null},1,[null,null,["self"],["width"]]);d.setWidth=a;a=$pyjs__bind_method2("setHeight",
function(b,h){if(!0===this.__is_instance__)var c=this;else c=b,b=h;c.setPixelHeight(b);return null},1,[null,null,["self"],["height"]]);d.setHeight=a;a=$pyjs__bind_method2("arc",function(b,h,c,a,e,d,g){if(!0===this.__is_instance__)var k=this;else k=b,b=h,h=c,c=a,a=e,e=d,d=g;k.impl.arc(b,h,c,a,e,d);return null},1,[null,null,["self"],["x"],["y"],["radius"],["startAngle"],["endAngle"],["antiClockwise"]]);d.arc=a;a=$pyjs__bind_method2("beginPath",function(b){(!0===this.__is_instance__?this:b).impl.beginPath();
return null},1,[null,null,["self"]]);d.beginPath=a;a=$pyjs__bind_method2("clear",function(b){b=!0===this.__is_instance__?this:b;var h,c;b.impl.clear(null==(h=b.coordWidth)||b.__is_instance__&&"function"==typeof h||"function"==typeof h.__get__?$p.getattr(b,"coordWidth"):b.coordWidth,null==(c=b.coordHeight)||b.__is_instance__&&"function"==typeof c||"function"==typeof c.__get__?$p.getattr(b,"coordHeight"):b.coordHeight);return null},1,[null,null,["self"]]);d.clear=a;a=$pyjs__bind_method2("closePath",
function(b){(!0===this.__is_instance__?this:b).impl.closePath();return null},1,[null,null,["self"]]);d.closePath=a;a=$pyjs__bind_method2("createLinearGradient",function(b,h,c,a,e){!0!==this.__is_instance__&&(b=h,h=c,c=a,a=e);return g.LinearGradientImplIE6(b,h,c,a)},1,[null,null,["self"],["x0"],["y0"],["x1"],["y1"]]);d.createLinearGradient=a;a=$pyjs__bind_method2("createRadialGradient",function(b,h,c,a,e,d,n){!0!==this.__is_instance__&&(b=h,h=c,c=a,a=e,e=d,d=n);return g.RadialGradientImplIE6(b,h,c,
a,e,d)},1,[null,null,["self"],["x0"],["y0"],["r0"],["x1"],["y1"],["r1"]]);d.createRadialGradient=a;a=$pyjs__bind_method2("cubicCurveTo",function(b,a,c,d,e,f,g){if(!0===this.__is_instance__)var k=this;else k=b,b=a,a=c,c=d,d=e,e=f,f=g;k.impl.cubicCurveTo(b,a,c,d,e,f);return null},1,[null,null,["self"],["cp1x"],["cp1y"],["cp2x"],["cp2y"],["x"],["y"]]);d.cubicCurveTo=a;a=$pyjs__bind_method2("drawImage",function(b){if(!0===this.__is_instance__)var a=this,c=$p.tuple($pyjs_array_slice.call(arguments,1,arguments.length));
else a=arguments[0],b=arguments[1],c=$p.tuple($pyjs_array_slice.call(arguments,2,arguments.length));var d,e,f,n,k,m,l,x,r,s,t,p,q,y,z,A,B,C,D,E,F,u,v,w,G;(null===(f=$p.isinstance(b,g.Widget))||!1===f||0===f||""===f?0:"object"==typeof f?"function"==typeof f.__nonzero__?f.__nonzero__():"function"==typeof f.__len__?0<f.__len__():1:1)?(e=b.getWidth(),f=b.getHeight()):(e=g.DOM.getIntAttribute(b,"offsetWidth"),f=g.DOM.getIntAttribute(b,"offsetHeight"));(null===(p=8===(s=null===(w=c)?0:"undefined"!=typeof w.__array?
w.__array.length:"function"==typeof w.__len__?w.__len__():"undefined"!=typeof w.length?w.length:$p.len(w))&&null===s?!0:null===s?!1:"object"!=typeof s&&"function"!=typeof s||"function"!=typeof s.__cmp__?8==s:0===s.__cmp__(8))||!1===p||0===p||""===p?0:"object"==typeof p?"function"==typeof p.__nonzero__?p.__nonzero__():"function"==typeof p.__len__?0<p.__len__():1:1)?a.impl.drawImage(b,"undefined"!=typeof(C=c).__array?"undefined"!=typeof C.__array[0]?C.__array[0]:C.__getitem__(0):C.__getitem__(0),"undefined"!=
typeof(B=c).__array?"undefined"!=typeof B.__array[1]?B.__array[1]:B.__getitem__(1):B.__getitem__(1),"undefined"!=typeof(A=c).__array?"undefined"!=typeof A.__array[2]?A.__array[2]:A.__getitem__(2):A.__getitem__(2),"undefined"!=typeof(z=c).__array?"undefined"!=typeof z.__array[3]?z.__array[3]:z.__getitem__(3):z.__getitem__(3),"undefined"!=typeof(y=c).__array?"undefined"!=typeof y.__array[4]?y.__array[4]:y.__getitem__(4):y.__getitem__(4),"undefined"!=typeof(E=c).__array?"undefined"!=typeof E.__array[5]?
E.__array[5]:E.__getitem__(5):E.__getitem__(5),"undefined"!=typeof(F=c).__array?"undefined"!=typeof F.__array[6]?F.__array[6]:F.__getitem__(6):F.__getitem__(6),"undefined"!=typeof(D=c).__array?"undefined"!=typeof D.__array[7]?D.__array[7]:D.__getitem__(7):D.__getitem__(7)):(null===(q=4===(r=null===(u=c)?0:"undefined"!=typeof u.__array?u.__array.length:"function"==typeof u.__len__?u.__len__():"undefined"!=typeof u.length?u.length:$p.len(u))&&null===r?!0:null===r?!1:"object"!=typeof r&&"function"!=
typeof r||"function"!=typeof r.__cmp__?4==r:0===r.__cmp__(4))||!1===q||0===q||""===q?0:"object"==typeof q?"function"==typeof q.__nonzero__?q.__nonzero__():"function"==typeof q.__len__?0<q.__len__():1:1)?(d=e,m="undefined"!=typeof(x=c).__array?"undefined"!=typeof x.__array[0]?x.__array[0]:x.__getitem__(0):x.__getitem__(0),x="undefined"!=typeof(n=c).__array?"undefined"!=typeof n.__array[1]?n.__array[1]:n.__getitem__(1):n.__getitem__(1),n="undefined"!=typeof(k=c).__array?"undefined"!=typeof k.__array[2]?
k.__array[2]:k.__getitem__(2):k.__getitem__(2),c="undefined"!=typeof(G=c).__array?"undefined"!=typeof G.__array[3]?G.__array[3]:G.__getitem__(3):G.__getitem__(3),a.impl.drawImage(b,0,0,d,f,m,x,n,c)):(null===(d=2===(t=null===(v=c)?0:"undefined"!=typeof v.__array?v.__array.length:"function"==typeof v.__len__?v.__len__():"undefined"!=typeof v.length?v.length:$p.len(v))&&null===t?!0:null===t?!1:"object"!=typeof t&&"function"!=typeof t||"function"!=typeof t.__cmp__?2==t:0===t.__cmp__(2))||!1===d||0===
d||""===d?0:"object"==typeof d?"function"==typeof d.__nonzero__?d.__nonzero__():"function"==typeof d.__len__?0<d.__len__():1:1)&&a.impl.drawImage(b,"undefined"!=typeof(m=c).__array?"undefined"!=typeof m.__array[0]?m.__array[0]:m.__getitem__(0):m.__getitem__(0),"undefined"!=typeof(l=c).__array?"undefined"!=typeof l.__array[1]?l.__array[1]:l.__getitem__(1):l.__getitem__(1));return null},1,["args",null,["self"],["img"]]);d.drawImage=a;a=$pyjs__bind_method2("fill",function(b){(!0===this.__is_instance__?
this:b).impl.fill();return null},1,[null,null,["self"]]);d.fill=a;a=$pyjs__bind_method2("fillRect",function(b,a,c,d,e){if(!0===this.__is_instance__)var f=this;else f=b,b=a,a=c,c=d,d=e;f.impl.fillRect(b,a,c,d);return null},1,[null,null,["self"],["startX"],["startY"],["width"],["height"]]);d.fillRect=a;a=$pyjs__bind_method2("fillText",function(b,a,c,d){if(!0===this.__is_instance__)var e=this;else e=arguments[0],b=arguments[1],a=arguments[2],c=arguments[3],d=arguments[4];"undefined"==typeof d&&(d=arguments.callee.__args__[6][1]);
e.impl.fillText(b,a,c,d);return null},1,[null,null,["self"],["text"],["startX"],["startY"],["maxWidth",null]]);d.fillText=a;a=$pyjs__bind_method2("getCoordHeight",function(b){b=!0===this.__is_instance__?this:b;var a;return null==(a=b.coordHeight)||b.__is_instance__&&"function"==typeof a||"function"==typeof a.__get__?$p.getattr(b,"coordHeight"):b.coordHeight},1,[null,null,["self"]]);d.getCoordHeight=a;a=$pyjs__bind_method2("getCoordWidth",function(b){b=!0===this.__is_instance__?this:b;var a;return null==
(a=b.coordWidth)||b.__is_instance__&&"function"==typeof a||"function"==typeof a.__get__?$p.getattr(b,"coordWidth"):b.coordWidth},1,[null,null,["self"]]);d.getCoordWidth=a;a=$pyjs__bind_method2("getGlobalAlpha",function(b){return(!0===this.__is_instance__?this:b).impl.getGlobalAlpha()},1,[null,null,["self"]]);d.getGlobalAlpha=a;a=$pyjs__bind_method2("getGlobalCompositeOperation",function(b){return(!0===this.__is_instance__?this:b).impl.getGlobalCompositeOperation()},1,[null,null,["self"]]);d.getGlobalCompositeOperation=
a;a=$pyjs__bind_method2("getLineCap",function(b){return(!0===this.__is_instance__?this:b).impl.getLineCap()},1,[null,null,["self"]]);d.getLineCap=a;a=$pyjs__bind_method2("getLineJoin",function(b){return(!0===this.__is_instance__?this:b).impl.getLineJoin()},1,[null,null,["self"]]);d.getLineJoin=a;a=$pyjs__bind_method2("getLineWidth",function(b){return(!0===this.__is_instance__?this:b).impl.getLineWidth()},1,[null,null,["self"]]);d.getLineWidth=a;a=$pyjs__bind_method2("getMiterLimit",function(b){return(!0===
this.__is_instance__?this:b).impl.getMiterLimit()},1,[null,null,["self"]]);d.getMiterLimit=a;a=$pyjs__bind_method2("lineTo",function(b,a,c){if(!0===this.__is_instance__)var d=this;else d=b,b=a,a=c;d.impl.lineTo(b,a);return null},1,[null,null,["self"],["x"],["y"]]);d.lineTo=a;a=$pyjs__bind_method2("moveTo",function(b,a,c){if(!0===this.__is_instance__)var d=this;else d=b,b=a,a=c;d.impl.moveTo(b,a);return null},1,[null,null,["self"],["x"],["y"]]);d.moveTo=a;a=$pyjs__bind_method2("quadraticCurveTo",function(b,
a,c,d,e){if(!0===this.__is_instance__)var f=this;else f=b,b=a,a=c,c=d,d=e;f.impl.quadraticCurveTo(b,a,c,d);return null},1,[null,null,["self"],["cpx"],["cpy"],["x"],["y"]]);d.quadraticCurveTo=a;a=$pyjs__bind_method2("rect",function(b,a,c,d,e){if(!0===this.__is_instance__)var f=this;else f=b,b=a,a=c,c=d,d=e;f.impl.rect(b,a,c,d);return null},1,[null,null,["self"],["startX"],["startY"],["width"],["height"]]);d.rect=a;a=$pyjs__bind_method2("resize",function(b,a,c){if(!0===this.__is_instance__)var d=this;
else d=b,b=a,a=c;d.setCoordSize(b,a);d.setPixelHeight(a);d.setPixelWidth(b);return null},1,[null,null,["self"],["width"],["height"]]);d.resize=a;a=$pyjs__bind_method2("restoreContext",function(b){(!0===this.__is_instance__?this:b).impl.restoreContext();return null},1,[null,null,["self"]]);d.restoreContext=a;a=$pyjs__bind_method2("rotate",function(b,a){if(!0===this.__is_instance__)var c=this;else c=b,b=a;c.impl.rotate(b);return null},1,[null,null,["self"],["angle"]]);d.rotate=a;a=$pyjs__bind_method2("saveContext",
function(b){(!0===this.__is_instance__?this:b).impl.saveContext();return null},1,[null,null,["self"]]);d.saveContext=a;a=$pyjs__bind_method2("scale",function(b,a,c){if(!0===this.__is_instance__)var d=this;else d=b,b=a,a=c;d.impl.scale(b,a);return null},1,[null,null,["self"],["x"],["y"]]);d.scale=a;a=$pyjs__bind_method2("setBackgroundColor",function(b,a){if(!0===this.__is_instance__)var c=this;else c=b,b=a;c.impl.setBackgroundColor(c.getCanvasElement(),$p.str(b));return null},1,[null,null,["self"],
["color"]]);d.setBackgroundColor=a;a=$pyjs__bind_method2("setCoordHeight",function(b,a){if(!0===this.__is_instance__)var c=this;else c=b,b=a;c.impl.setCoordHeight(c.getCanvasElement(),b);c.__is_instance__&&"function"==typeof c.__setattr__?c.__setattr__("coordHeight",b):$p.setattr(c,"coordHeight",b);return null},1,[null,null,["self"],["height"]]);d.setCoordHeight=a;a=$pyjs__bind_method2("setCoordSize",function(b,a,c){if(!0===this.__is_instance__)var d=this;else d=b,b=a,a=c;d.setCoordWidth(b);d.setCoordHeight(a);
return null},1,[null,null,["self"],["width"],["height"]]);d.setCoordSize=a;a=$pyjs__bind_method2("setCoordWidth",function(b,a){if(!0===this.__is_instance__)var c=this;else c=b,b=a;c.impl.setCoordWidth(c.getCanvasElement(),b);c.__is_instance__&&"function"==typeof c.__setattr__?c.__setattr__("coordWidth",b):$p.setattr(c,"coordWidth",b);return null},1,[null,null,["self"],["width"]]);d.setCoordWidth=a;a=$pyjs__bind_method2("setFillStyle",function(b,a){if(!0===this.__is_instance__)var c=this;else c=b,
b=a;c.impl.setFillStyle(b);return null},1,[null,null,["self"],["grad"]]);d.setFillStyle=a;a=$pyjs__bind_method2("setGlobalAlpha",function(b,a){if(!0===this.__is_instance__)var c=this;else c=b,b=a;c.impl.setGlobalAlpha(b);return null},1,[null,null,["self"],["alpha"]]);d.setGlobalAlpha=a;a=$pyjs__bind_method2("setFont",function(b,a){if(!0===this.__is_instance__)var c=this;else c=b,b=a;c.impl.setFont(b);return null},1,[null,null,["self"],["font"]]);d.setFont=a;a=$pyjs__bind_method2("setGlobalCompositeOperation",
function(b,a){if(!0===this.__is_instance__)var c=this;else c=b,b=a;c.impl.setGlobalCompositeOperation(b);return null},1,[null,null,["self"],["globalCompositeOperation"]]);d.setGlobalCompositeOperation=a;a=$pyjs__bind_method2("setLineCap",function(b,a){if(!0===this.__is_instance__)var c=this;else c=b,b=a;c.impl.setLineCap(b);return null},1,[null,null,["self"],["lineCap"]]);d.setLineCap=a;a=$pyjs__bind_method2("setLineJoin",function(b,a){if(!0===this.__is_instance__)var c=this;else c=b,b=a;c.impl.setLineJoin(b);
return null},1,[null,null,["self"],["lineJoin"]]);d.setLineJoin=a;a=$pyjs__bind_method2("setLineWidth",function(b,a){if(!0===this.__is_instance__)var c=this;else c=b,b=a;c.impl.setLineWidth(b);return null},1,[null,null,["self"],["width"]]);d.setLineWidth=a;a=$pyjs__bind_method2("setMiterLimit",function(b,a){if(!0===this.__is_instance__)var c=this;else c=b,b=a;c.impl.setMiterLimit(b);return null},1,[null,null,["self"],["miterLimit"]]);d.setMiterLimit=a;a=$pyjs__bind_method2("setPixelHeight",function(b,
a){if(!0===this.__is_instance__)var c=this;else c=b,b=a;g.FocusWidget.setHeight(c,$p.str(b)+"px");c.impl.setPixelHeight(c.getCanvasElement(),b);return null},1,[null,null,["self"],["height"]]);d.setPixelHeight=a;a=$pyjs__bind_method2("setPixelWidth",function(b,a){if(!0===this.__is_instance__)var c=this;else c=b,b=a;g.FocusWidget.setWidth(c,$p.str(b)+"px");c.impl.setPixelWidth(c.getCanvasElement(),b);return null},1,[null,null,["self"],["width"]]);d.setPixelWidth=a;a=$pyjs__bind_method2("setStrokeStyle",
function(b,a){if(!0===this.__is_instance__)var c=this;else c=b,b=a;c.impl.setStrokeStyle(b);return null},1,[null,null,["self"],["grad"]]);d.setStrokeStyle=a;a=$pyjs__bind_method2("stroke",function(b){(!0===this.__is_instance__?this:b).impl.stroke();return null},1,[null,null,["self"]]);d.stroke=a;a=$pyjs__bind_method2("strokeRect",function(b,a,c,d,e){if(!0===this.__is_instance__)var f=this;else f=b,b=a,a=c,c=d,d=e;f.impl.strokeRect(b,a,c,d);return null},1,[null,null,["self"],["startX"],["startY"],
["width"],["height"]]);d.strokeRect=a;a=$pyjs__bind_method2("transform",function(a,d,c,g,e,f,l){if(!0===this.__is_instance__)var k=this;else k=a,a=d,d=c,c=g,g=e,e=f,f=l;k.impl.transform(a,d,c,g,e,f);return null},1,[null,null,["self"],["m11"],["m12"],["m21"],["m22"],["dx"],["dy"]]);d.transform=a;a=$pyjs__bind_method2("translate",function(a,d,c){if(!0===this.__is_instance__)var g=this;else g=a,a=d,d=c;g.impl.translate(a,d);return null},1,[null,null,["self"],["x"],["y"]]);d.translate=a;a=Array(g.FocusWidget);
var l=$p.dict(),H;for(H in d)l.__setitem__(H,d[H]);return $p._create_class("GWTCanvas",$p.tuple(a),l)}();return this};
