$pyjs.loaded_modules["pyjamas.ui.Image"]=function(l){if($pyjs.loaded_modules["pyjamas.ui.Image"].__was_initialized__)return $pyjs.loaded_modules["pyjamas.ui.Image"];"undefined"!=typeof $pyjs.loaded_modules["pyjamas.ui"]&&$pyjs.loaded_modules["pyjamas.ui"].__was_initialized__||$p.___import___("pyjamas.ui",null);var c=$pyjs.loaded_modules["pyjamas.ui.Image"];c.__repr__=function(){return"<module: pyjamas.ui.Image>"};c.__was_initialized__=!0;if(null===l||"undefined"==typeof l)l="pyjamas.ui.Image";c.__name__=
l;$pyjs.loaded_modules["pyjamas.ui"].Image=$pyjs.loaded_modules["pyjamas.ui.Image"];c.DOM=$p.___import___("pyjamas.DOM","pyjamas.ui",null,!1);c.Factory=$p.___import___("pyjamas.Factory","pyjamas.ui",null,!1);c.Widget=$p.___import___("pyjamas.ui.Widget.Widget","pyjamas.ui",null,!1);c.Event=$p.___import___("pyjamas.ui.Event","pyjamas.ui",null,!1);c.MouseHandler=$p.___import___("pyjamas.ui.MouseListener.MouseHandler","pyjamas.ui",null,!1);c.ClickHandler=$p.___import___("pyjamas.ui.ClickListener.ClickHandler",
"pyjamas.ui",null,!1);c.prefetchImages=$p.dict([]);c.Image=function(){var g={},a;g.__module__="pyjamas.ui.Image";g._props=$p.list([$p.tuple(["url","Url","Url",null])]);a=$pyjs__bind_method2("__init__",function(b){if(!0===this.__is_instance__)var h=this,d=2<=arguments.length?arguments[arguments.length-1]:arguments[arguments.length];else h=arguments[0],b=arguments[1],d=3<=arguments.length?arguments[arguments.length-1]:arguments[arguments.length];null===d||"object"!=typeof d||"dict"!=d.__name__||"undefined"==
typeof d.$pyjs_is_kwarg?d=arguments[arguments.length+1]:delete d.$pyjs_is_kwarg;"undefined"==typeof d&&(d=$p.__empty_dict(),"undefined"!=typeof b?null!==b&&"undefined"!=typeof b.$pyjs_is_kwarg&&(d=b,b=arguments[2]):"undefined"!=typeof h&&null!==h&&"undefined"!=typeof h.$pyjs_is_kwarg&&(d=h,h=arguments[2]));"undefined"==typeof b&&(b=arguments.callee.__args__[3][1]);var a,f,e,g,k,m,n,p,l;(null===(k=!(null===(n=d.has_key("StyleName"))||!1===n||0===n||""===n?0:"object"==typeof n?"function"==typeof n.__nonzero__?
n.__nonzero__():"function"==typeof n.__len__?0<n.__len__():1:1))||!1===k||0===k||""===k?0:"object"==typeof k?"function"==typeof k.__nonzero__?k.__nonzero__():"function"==typeof k.__len__?0<k.__len__():1:1)&&d.__setitem__("StyleName","gwt-Image");(null===(m=b)||!1===m||0===m||""===m?0:"object"==typeof m?"function"==typeof m.__nonzero__?m.__nonzero__():"function"==typeof m.__len__?0<m.__len__():1:1)&&d.__setitem__("Url",b);h.setElement((null===(p=a=d.pop("Element",null))||!1===p||0===p||""===p?0:"object"==
typeof p?"function"==typeof p.__nonzero__?p.__nonzero__():"function"==typeof p.__len__?0<p.__len__():1:1)?a:c.DOM.createImg());$pyjs_kwargs_call(c.Widget,"__init__",null,d,[{},h]);c.MouseHandler.__init__(h);c.ClickHandler.__init__(h);h.sinkEvents((null==(e=(f=c.Event).ONLOAD)||f.__is_instance__&&"function"==typeof e||"function"==typeof e.__get__?$p.getattr(f,"ONLOAD"):c.Event.ONLOAD)|(null==(l=(g=c.Event).ONERROR)||g.__is_instance__&&"function"==typeof l||"function"==typeof l.__get__?$p.getattr(g,
"ONERROR"):c.Event.ONERROR));h.__is_instance__&&"function"==typeof h.__setattr__?h.__setattr__("loadListeners",$p.list([])):$p.setattr(h,"loadListeners",$p.list([]));return null},1,[null,["kwargs"],["self"],["url",""]]);g.__init__=a;a=$pyjs__bind_method2("_getProps",function(){var b=this.prototype,h;return c.Widget._getProps()+(null==(h=b._props)||b.__is_instance__&&"function"==typeof h||"function"==typeof h.__get__?$p.getattr(b,"_props"):b._props)},2,[null,null,["self"]]);g._getProps=a;a=$pyjs__bind_method2("addLoadListener",
function(b,c){if(!0===this.__is_instance__)var d=this;else d=b,b=c;d.loadListeners.append(b);return null},1,[null,null,["self"],["listener"]]);g.addLoadListener=a;a=$pyjs__bind_method2("removeLoadListener",function(b,c){if(!0===this.__is_instance__)var d=this;else d=b,b=c;d.loadListeners.remove(b);return null},1,[null,null,["self"],["listener"]]);g.removeLoadListener=a;a=$pyjs__bind_method2("getUrl",function(b){return c.DOM.getAttribute((!0===this.__is_instance__?this:b).getElement(),"src")},1,[null,
null,["self"]]);g.getUrl=a;a=$pyjs__bind_method2("onBrowserEvent",function(b,h){if(!0===this.__is_instance__)var d=this;else d=b,b=h;var a,f,e,g,k;c.Widget.onBrowserEvent(d,b);e=c.DOM.eventGetType(b);if(null===(f="load"===e&&null===e?!0:null===e?!1:"object"!=typeof e&&"function"!=typeof e||"function"!=typeof e.__cmp__?"load"==e:0===e.__cmp__("load"))||!1===f||0===f||""===f?0:"object"==typeof f?"function"==typeof f.__nonzero__?f.__nonzero__():"function"==typeof f.__len__?0<f.__len__():1:1)for(e=d.loadListeners,
"undefined"!=typeof(g=e.__array)?f=0:(e=e.__iter__(),f="undefined"!=typeof(g=e.__array)?0:"function"==typeof e.$genfunc?1:-1),k=0;"undefined"!=typeof(a=f?0<f?e.next(!0,!1):$p.wrapped_next(e):g[k++]);)a.onImageLoad(d);else if(null===(a="error"===e&&null===e?!0:null===e?!1:"object"!=typeof e&&"function"!=typeof e||"function"!=typeof e.__cmp__?"error"==e:0===e.__cmp__("error"))||!1===a||0===a||""===a?0:"object"==typeof a?"function"==typeof a.__nonzero__?a.__nonzero__():"function"==typeof a.__len__?0<
a.__len__():1:1)for(f=d.loadListeners,"undefined"!=typeof(k=f.__array)?g=0:(f=f.__iter__(),g="undefined"!=typeof(k=f.__array)?0:"function"==typeof f.$genfunc?1:-1),e=0;"undefined"!=typeof(a=g?0<g?f.next(!0,!1):$p.wrapped_next(f):k[e++]);)a.onImageError(d);return null},1,[null,null,["self"],["event"]]);g.onBrowserEvent=a;a=$pyjs__bind_method2("prefetch",function(b,a){!0!==this.__is_instance__&&(b=a);var d;d=c.DOM.createImg();c.DOM.setElemAttribute(d,"src",b);c.prefetchImages.__setitem__(b,d);return null},
1,[null,null,["self"],["url"]]);g.prefetch=a;a=$pyjs__bind_method2("setUrl",function(b,a){if(!0===this.__is_instance__)var d=this;else d=b,b=a;c.DOM.setElemAttribute(d.getElement(),"src",b);return null},1,[null,null,["self"],["url"]]);g.setUrl=a;a=[c.Widget,c.MouseHandler,c.ClickHandler];var l=$p.dict(),q;for(q in g)l.__setitem__(q,g[q]);return $p._create_class("Image",$p.tuple(a),l)}();c.Factory.registerClass("pyjamas.ui.Image","Image",c.Image);return this};
