$pyjs.loaded_modules["pyjamas.ui.CellPanel"]=function(k){if($pyjs.loaded_modules["pyjamas.ui.CellPanel"].__was_initialized__)return $pyjs.loaded_modules["pyjamas.ui.CellPanel"];"undefined"!=typeof $pyjs.loaded_modules["pyjamas.ui"]&&$pyjs.loaded_modules["pyjamas.ui"].__was_initialized__||$p.___import___("pyjamas.ui",null);var g=$pyjs.loaded_modules["pyjamas.ui.CellPanel"];g.__repr__=function(){return"<module: pyjamas.ui.CellPanel>"};g.__was_initialized__=!0;if(null===k||"undefined"==typeof k)k="pyjamas.ui.CellPanel";
g.__name__=k;$pyjs.loaded_modules["pyjamas.ui"].CellPanel=$pyjs.loaded_modules["pyjamas.ui.CellPanel"];g.DOM=$p.___import___("pyjamas.DOM","pyjamas.ui",null,!1);g.Factory=$p.___import___("pyjamas.Factory","pyjamas.ui",null,!1);g.ComplexPanel=$p.___import___("pyjamas.ui.ComplexPanel.ComplexPanel","pyjamas.ui",null,!1);g.HasHorizontalAlignment=$p.___import___("pyjamas.ui.HasHorizontalAlignment","pyjamas.ui",null,!1);g.HasVerticalAlignment=$p.___import___("pyjamas.ui.HasVerticalAlignment","pyjamas.ui",
null,!1);g.CellPanel=function(){var f={},b;f.__module__="pyjamas.ui.CellPanel";f._props=$p.list([$p.tuple(["horzAlign","Horizontal alignment","HorizontalAlignment",null]),$p.tuple(["vertAlign","Vertical alignment","VerticalAlignment",null]),$p.tuple(["border","Border width","BorderWidth",$p.float_int]),$p.tuple(["spacing","Spacing","Spacing",null]),$p.tuple(["padding","Padding","Padding",null])]);b=$pyjs__bind_method2("__init__",function(){if(!0===this.__is_instance__)var a=this,c=1<=arguments.length?
arguments[arguments.length-1]:arguments[arguments.length];else a=arguments[0],c=2<=arguments.length?arguments[arguments.length-1]:arguments[arguments.length];null===c||"object"!=typeof c||"dict"!=c.__name__||"undefined"==typeof c.$pyjs_is_kwarg?c=arguments[arguments.length+1]:delete c.$pyjs_is_kwarg;"undefined"==typeof c&&(c=$p.__empty_dict(),"undefined"!=typeof a&&null!==a&&"undefined"!=typeof a.$pyjs_is_kwarg&&(c=a,a=arguments[1]));var h,d,e,n,b,f,k,m,l,p,q,r;c.__setitem__("Spacing",c.get("Spacing",
0));c.__setitem__("Padding",c.get("Padding",0));c.__setitem__("HorizontalAlignment",c.get("HorizontalAlignment",null==(n=(b=g.HasHorizontalAlignment).ALIGN_LEFT)||b.__is_instance__&&"function"==typeof n||"function"==typeof n.__get__?$p.getattr(b,"ALIGN_LEFT"):g.HasHorizontalAlignment.ALIGN_LEFT));c.__setitem__("VerticalAlignment",c.get("VerticalAlignment",null==(r=(k=g.HasVerticalAlignment).ALIGN_TOP)||k.__is_instance__&&"function"==typeof r||"function"==typeof r.__get__?$p.getattr(k,"ALIGN_TOP"):
g.HasVerticalAlignment.ALIGN_TOP));n=(null===(m=e=c.pop("Element",null))||!1===m||0===m||""===m?0:"object"==typeof m?"function"==typeof m.__nonzero__?m.__nonzero__():"function"==typeof m.__len__?0<m.__len__():1:1)?e:g.DOM.createTable();e=g.DOM.getFirstChild(n);(null===e||!1===e||0===e||""===e?0:"object"==typeof e?"function"==typeof e.__nonzero__?e.__nonzero__():"function"==typeof e.__len__?0<e.__len__():1:1)?a.__is_instance__&&"function"==typeof a.__setattr__?a.__setattr__("body",e):$p.setattr(a,
"body",e):a.__is_instance__&&"function"==typeof a.__setattr__?a.__setattr__("body",g.DOM.createTBody()):$p.setattr(a,"body",g.DOM.createTBody());a.__is_instance__&&"function"==typeof a.__setattr__?a.__setattr__("table",n):$p.setattr(a,"table",n);a.setElement(null==(f=(q=a).table)||q.__is_instance__&&"function"==typeof f||"function"==typeof f.__get__?$p.getattr(q,"table"):a.table);g.DOM.appendChild(null==(l=(d=a).table)||d.__is_instance__&&"function"==typeof l||"function"==typeof l.__get__?$p.getattr(d,
"table"):a.table,null==(h=(p=a).body)||p.__is_instance__&&"function"==typeof h||"function"==typeof h.__get__?$p.getattr(p,"body"):a.body);$pyjs_kwargs_call(g.ComplexPanel,"__init__",null,c,[{},a]);return null},1,[null,["kwargs"],["self"]]);f.__init__=b;b=$pyjs__bind_method2("_getProps",function(){var a=this.prototype,c;return g.ComplexPanel._getProps()+(null==(c=a._props)||a.__is_instance__&&"function"==typeof c||"function"==typeof c.__get__?$p.getattr(a,"_props"):a._props)},2,[null,null,["self"]]);
f._getProps=b;b=$pyjs__bind_method2("getTable",function(a){a=!0===this.__is_instance__?this:a;var c;return null==(c=a.table)||a.__is_instance__&&"function"==typeof c||"function"==typeof c.__get__?$p.getattr(a,"table"):a.table},1,[null,null,["self"]]);f.getTable=b;b=$pyjs__bind_method2("getBody",function(a){a=!0===this.__is_instance__?this:a;var c;return null==(c=a.body)||a.__is_instance__&&"function"==typeof c||"function"==typeof c.__get__?$p.getattr(a,"body"):a.body},1,[null,null,["self"]]);f.getBody=
b;b=$pyjs__bind_method2("getBorderWidth",function(a){a=!0===this.__is_instance__?this:a;var c;return g.DOM.getAttribute(null==(c=a.table)||a.__is_instance__&&"function"==typeof c||"function"==typeof c.__get__?$p.getattr(a,"table"):a.table,"border")},1,[null,null,["self"]]);f.getBorderWidth=b;b=$pyjs__bind_method2("getCellHeight",function(a,c){!0!==this.__is_instance__&&(a=c);var h;h=g.DOM.getParent(a.getElement());return g.DOM.getAttribute(h,"height")},1,[null,null,["self"],["widget"]]);f.getCellHeight=
b;b=$pyjs__bind_method2("getCellWidth",function(a,c){!0!==this.__is_instance__&&(a=c);var h;h=g.DOM.getParent(a.getElement());return g.DOM.getAttribute(h,"width")},1,[null,null,["self"],["widget"]]);f.getCellWidth=b;b=$pyjs__bind_method2("getSpacing",function(a){a=!0===this.__is_instance__?this:a;var c;return null==(c=a.spacing)||a.__is_instance__&&"function"==typeof c||"function"==typeof c.__get__?$p.getattr(a,"spacing"):a.spacing},1,[null,null,["self"]]);f.getSpacing=b;b=$pyjs__bind_method2("getPadding",
function(a){a=!0===this.__is_instance__?this:a;var c;return null==(c=a.padding)||a.__is_instance__&&"function"==typeof c||"function"==typeof c.__get__?$p.getattr(a,"padding"):a.padding},1,[null,null,["self"]]);f.getPadding=b;b=$pyjs__bind_method2("getCellHorizontalAlignment",function(a,c){if(!0===this.__is_instance__)var h=this;else h=a,a=c;var d,h=h.getWidgetTd(a);return(null===(d=null===h)||!1===d||0===d||""===d?0:"object"==typeof d?"function"==typeof d.__nonzero__?d.__nonzero__():"function"==typeof d.__len__?
0<d.__len__():1:1)?null:g.DOM.getAttribute(h,"align")},1,[null,null,["self"],["widget"]]);f.getCellHorizontalAlignment=b;b=$pyjs__bind_method2("getCellVerticalAlignment",function(a,c){if(!0===this.__is_instance__)var h=this;else h=a,a=c;var d,h=h.getWidgetTd(a);return(null===(d=null===h)||!1===d||0===d||""===d?0:"object"==typeof d?"function"==typeof d.__nonzero__?d.__nonzero__():"function"==typeof d.__len__?0<d.__len__():1:1)?null:g.DOM.getStyleAttribute(h,"verticalAlign")},1,[null,null,["self"],
["widget"]]);f.getCellVerticalAlignment=b;b=$pyjs__bind_method2("getWidgetTd",function(a,c){if(!0===this.__is_instance__)var h=this;else h=a,a=c;var d,e,b;return(null===(b=!((e=a.getParent())===(d=h)&&null===e||(null===e?0:null===d?0:"object"!=typeof e&&"function"!=typeof e||"function"!=typeof e.__cmp__?"object"!=typeof d&&"function"!=typeof d||"function"!=typeof d.__cmp__?e==d:0===d.__cmp__(e):0===e.__cmp__(d))))||!1===b||0===b||""===b?0:"object"==typeof b?"function"==typeof b.__nonzero__?b.__nonzero__():
"function"==typeof b.__len__?0<b.__len__():1:1)?null:g.DOM.getParent(a.getElement())},1,[null,null,["self"],["widget"]]);f.getWidgetTd=b;b=$pyjs__bind_method2("setBorderWidth",function(a,c){if(!0===this.__is_instance__)var h=this;else h=a,a=c;var d,e,b,f,k;(null===(e=null===a)||!1===e||0===e||""===e?0:"object"==typeof e?"function"==typeof e.__nonzero__?e.__nonzero__():"function"==typeof e.__len__?0<e.__len__():1:1)?g.DOM.setAttribute(null==(d=(k=h).table)||k.__is_instance__&&"function"==typeof d||
"function"==typeof d.__get__?$p.getattr(k,"table"):h.table,"border",null):g.DOM.setAttribute(null==(b=(f=h).table)||f.__is_instance__&&"function"==typeof b||"function"==typeof b.__get__?$p.getattr(f,"table"):h.table,"border",$p.str(a));return null},1,[null,null,["self"],["width"]]);f.setBorderWidth=b;b=$pyjs__bind_method2("setCellHeight",function(a,c,h){!0!==this.__is_instance__&&(a=c,c=h);var d;a=g.DOM.getParent(a.getElement());(null===(d=null===c)||!1===d||0===d||""===d?0:"object"==typeof d?"function"==
typeof d.__nonzero__?d.__nonzero__():"function"==typeof d.__len__?0<d.__len__():1:1)?g.DOM.removeAttribute(a,"height"):g.DOM.setAttribute(a,"height",$p.str(c));return null},1,[null,null,["self"],["widget"],["height"]]);f.setCellHeight=b;b=$pyjs__bind_method2("setCellHorizontalAlignment",function(a,c,h){if(!0===this.__is_instance__)var d=this;else d=a,a=c,c=h;var e,b;a=d.getWidgetTd(a);if(null===(e=null!==a)||!1===e||0===e||""===e?0:"object"==typeof e?"function"==typeof e.__nonzero__?e.__nonzero__():
"function"==typeof e.__len__?0<e.__len__():1:1)(null===(b=null===c)||!1===b||0===b||""===b?0:"object"==typeof b?"function"==typeof b.__nonzero__?b.__nonzero__():"function"==typeof b.__len__?0<b.__len__():1:1)?g.DOM.removeAttribute(a,"align"):g.DOM.setAttribute(a,"align",c);return null},1,[null,null,["self"],["widget"],["align"]]);f.setCellHorizontalAlignment=b;b=$pyjs__bind_method2("setCellVerticalAlignment",function(a,c,b){if(!0===this.__is_instance__)var d=this;else d=a,a=c,c=b;var e,f;a=d.getWidgetTd(a);
if(null===(e=null!==a)||!1===e||0===e||""===e?0:"object"==typeof e?"function"==typeof e.__nonzero__?e.__nonzero__():"function"==typeof e.__len__?0<e.__len__():1:1)(null===(f=null===c)||!1===f||0===f||""===f?0:"object"==typeof f?"function"==typeof f.__nonzero__?f.__nonzero__():"function"==typeof f.__len__?0<f.__len__():1:1)?g.DOM.setStyleAttribute(a,"verticalAlign",""):g.DOM.setStyleAttribute(a,"verticalAlign",c);return null},1,[null,null,["self"],["widget"],["align"]]);f.setCellVerticalAlignment=
b;b=$pyjs__bind_method2("setCellWidth",function(a,c,b){!0!==this.__is_instance__&&(a=c,c=b);var d;a=g.DOM.getParent(a.getElement());(null===(d=null===c)||!1===d||0===d||""===d?0:"object"==typeof d?"function"==typeof d.__nonzero__?d.__nonzero__():"function"==typeof d.__len__?0<d.__len__():1:1)?g.DOM.removeAttribute(a,"width"):g.DOM.setAttribute(a,"width",$p.str(c));return null},1,[null,null,["self"],["widget"],["width"]]);f.setCellWidth=b;b=$pyjs__bind_method2("setSpacing",function(a,c){if(!0===this.__is_instance__)var b=
this;else b=a,a=c;var d,e,f,k,l;b.__is_instance__&&"function"==typeof b.__setattr__?b.__setattr__("spacing",a):$p.setattr(b,"spacing",a);(null===(d=null===a)||!1===d||0===d||""===d?0:"object"==typeof d?"function"==typeof d.__nonzero__?d.__nonzero__():"function"==typeof d.__len__?0<d.__len__():1:1)?g.DOM.removeAttribute(null==(f=(k=b).table)||k.__is_instance__&&"function"==typeof f||"function"==typeof f.__get__?$p.getattr(k,"table"):b.table,"cellSpacing"):g.DOM.setAttribute(null==(l=(e=b).table)||
e.__is_instance__&&"function"==typeof l||"function"==typeof l.__get__?$p.getattr(e,"table"):b.table,"cellSpacing",$p.str(a));return null},1,[null,null,["self"],["spacing"]]);f.setSpacing=b;b=$pyjs__bind_method2("setPadding",function(a,c){if(!0===this.__is_instance__)var b=this;else b=a,a=c;var d,e,f,k,l;b.__is_instance__&&"function"==typeof b.__setattr__?b.__setattr__("padding",a):$p.setattr(b,"padding",a);(null===(e=null===a)||!1===e||0===e||""===e?0:"object"==typeof e?"function"==typeof e.__nonzero__?
e.__nonzero__():"function"==typeof e.__len__?0<e.__len__():1:1)?g.DOM.removeAttribute(null==(k=(f=b).table)||f.__is_instance__&&"function"==typeof k||"function"==typeof k.__get__?$p.getattr(f,"table"):b.table,"cellPadding"):g.DOM.setAttribute(null==(d=(l=b).table)||l.__is_instance__&&"function"==typeof d||"function"==typeof d.__get__?$p.getattr(l,"table"):b.table,"cellPadding",$p.str(a));return null},1,[null,null,["self"],["padding"]]);f.setPadding=b;b=$pyjs__bind_method2("setHorizontalAlignment",
function(a,b){if(!0===this.__is_instance__)var f=this;else f=a,a=b;f.__is_instance__&&"function"==typeof f.__setattr__?f.__setattr__("horzAlign",a):$p.setattr(f,"horzAlign",a);return null},1,[null,null,["self"],["align"]]);f.setHorizontalAlignment=b;b=$pyjs__bind_method2("setVerticalAlignment",function(a,b){if(!0===this.__is_instance__)var f=this;else f=a,a=b;f.__is_instance__&&"function"==typeof f.__setattr__?f.__setattr__("vertAlign",a):$p.setattr(f,"vertAlign",a);return null},1,[null,null,["self"],
["align"]]);f.setVerticalAlignment=b;b=$pyjs__bind_method2("getHorizontalAlignment",function(a){a=!0===this.__is_instance__?this:a;var b;return null==(b=a.horzAlign)||a.__is_instance__&&"function"==typeof b||"function"==typeof b.__get__?$p.getattr(a,"horzAlign"):a.horzAlign},1,[null,null,["self"]]);f.getHorizontalAlignment=b;b=$pyjs__bind_method2("getVerticalAlignment",function(a){a=!0===this.__is_instance__?this:a;var b;return null==(b=a.vertAlign)||a.__is_instance__&&"function"==typeof b||"function"==
typeof b.__get__?$p.getattr(a,"vertAlign"):a.vertAlign},1,[null,null,["self"]]);f.getVerticalAlignment=b;b=Array(g.ComplexPanel);var k=$p.dict(),l;for(l in f)k.__setitem__(l,f[l]);return $p._create_class("CellPanel",$p.tuple(b),k)}();g.Factory.registerClass("pyjamas.ui.CellPanel","CellPanel",g.CellPanel);return this};
