$pyjs.loaded_modules["pyjamas.ui.Widget"]=function(r){if($pyjs.loaded_modules["pyjamas.ui.Widget"].__was_initialized__)return $pyjs.loaded_modules["pyjamas.ui.Widget"];"undefined"!=typeof $pyjs.loaded_modules["pyjamas.ui"]&&$pyjs.loaded_modules["pyjamas.ui"].__was_initialized__||$p.___import___("pyjamas.ui",null);var d=$pyjs.loaded_modules["pyjamas.ui.Widget"];d.__repr__=function(){return"<module: pyjamas.ui.Widget>"};d.__was_initialized__=!0;if(null===r||"undefined"==typeof r)r="pyjamas.ui.Widget";
d.__name__=r;$pyjs.loaded_modules["pyjamas.ui"].Widget=$pyjs.loaded_modules["pyjamas.ui.Widget"];d.DOM=$p.___import___("pyjamas.DOM","pyjamas.ui",null,!1);d.Factory=$p.___import___("pyjamas.Factory","pyjamas.ui",null,!1);d.UIObject=$p.___import___("pyjamas.ui.UIObject.UIObject","pyjamas.ui",null,!1);d.Event=$p.___import___("pyjamas.ui.Event","pyjamas.ui",null,!1);d.ClickHandler=$p.___import___("pyjamas.ui.ClickListener.ClickHandler","pyjamas.ui",null,!1);d.FocusHandler=$p.___import___("pyjamas.ui.FocusListener.FocusHandler",
"pyjamas.ui",null,!1);d.KeyboardHandler=$p.___import___("pyjamas.ui.KeyboardListener.KeyboardHandler","pyjamas.ui",null,!1);d.MouseHandler=$p.___import___("pyjamas.ui.MouseListener.MouseHandler","pyjamas.ui",null,!1);d.MouseWheelHandler=$p.___import___("pyjamas.ui.MouseListener.MouseWheelHandler","pyjamas.ui",null,!1);d.InputHandler=$p.___import___("pyjamas.ui.InputListener.InputHandler","pyjamas.ui",null,!1);d.ChangeHandler=$p.___import___("pyjamas.ui.ChangeListener.ChangeHandler","pyjamas.ui",null,
!1);d.DragHandler=$p.___import___("pyjamas.ui.DragHandler.DragHandler","pyjamas.ui",null,!1);d.DropHandler=$p.___import___("pyjamas.ui.DropHandler.DropHandler","pyjamas.ui",null,!1);d.Widget=function(){var f={},c;f.__module__="pyjamas.ui.Widget";c=$pyjs__bind_method2("__init__",function(){if(!0===this.__is_instance__)var a=this,e=1<=arguments.length?arguments[arguments.length-1]:arguments[arguments.length];else a=arguments[0],e=2<=arguments.length?arguments[arguments.length-1]:arguments[arguments.length];
null===e||"object"!=typeof e||"dict"!=e.__name__||"undefined"==typeof e.$pyjs_is_kwarg?e=arguments[arguments.length+1]:delete e.$pyjs_is_kwarg;"undefined"==typeof e&&(e=$p.__empty_dict(),"undefined"!=typeof a&&null!==a&&"undefined"!=typeof a.$pyjs_is_kwarg&&(e=a,a=arguments[1]));a.__is_instance__&&"function"==typeof a.__setattr__?a.__setattr__("attached",!1):$p.setattr(a,"attached",!1);a.__is_instance__&&"function"==typeof a.__setattr__?a.__setattr__("parent",null):$p.setattr(a,"parent",null);a.__is_instance__&&
"function"==typeof a.__setattr__?a.__setattr__("layoutData",null):$p.setattr(a,"layoutData",null);a.__is_instance__&&"function"==typeof a.__setattr__?a.__setattr__("contextMenu",null):$p.setattr(a,"contextMenu",null);$pyjs_kwargs_call(d.UIObject,"__init__",null,e,[{},a]);return null},1,[null,["kwargs"],["self"]]);f.__init__=c;c=$pyjs__bind_method2("getLayoutData",function(a){a=!0===this.__is_instance__?this:a;var e;return null==(e=a.layoutData)||a.__is_instance__&&"function"==typeof e||"function"==
typeof e.__get__?$p.getattr(a,"layoutData"):a.layoutData},1,[null,null,["self"]]);f.getLayoutData=c;c=$pyjs__bind_method2("getParent",function(a){a=!0===this.__is_instance__?this:a;var e;return null==(e=a.parent)||a.__is_instance__&&"function"==typeof e||"function"==typeof e.__get__?$p.getattr(a,"parent"):a.parent},1,[null,null,["self"]]);f.getParent=c;c=$pyjs__bind_method2("isAttached",function(a){a=!0===this.__is_instance__?this:a;var e;return null==(e=a.attached)||a.__is_instance__&&"function"==
typeof e||"function"==typeof e.__get__?$p.getattr(a,"attached"):a.attached},1,[null,null,["self"]]);f.isAttached=c;c=$pyjs__bind_method2("setContextMenu",function(a,e){if(!0===this.__is_instance__)var b=this;else b=a,a=e;var c,v,f,h,g;b.__is_instance__&&"function"==typeof b.__setattr__?b.__setattr__("contextMenu",a):$p.setattr(b,"contextMenu",a);(null===(h=null!==a)||!1===h||0===h||""===h?0:"object"==typeof h?"function"==typeof h.__nonzero__?h.__nonzero__():"function"==typeof h.__len__?0<h.__len__():
1:1)?b.sinkEvents(null==(f=(v=d.Event).ONCONTEXTMENU)||v.__is_instance__&&"function"==typeof f||"function"==typeof f.__get__?$p.getattr(v,"ONCONTEXTMENU"):d.Event.ONCONTEXTMENU):b.unsinkEvents(null==(c=(g=d.Event).ONCONTEXTMENU)||g.__is_instance__&&"function"==typeof c||"function"==typeof c.__get__?$p.getattr(g,"ONCONTEXTMENU"):d.Event.ONCONTEXTMENU);return null},1,[null,null,["self"],["menu"]]);f.setContextMenu=c;c=$pyjs__bind_method2("onBrowserEvent",function(a,e){if(!0===this.__is_instance__)var b=
this;else b=a,a=e;var c,f,t,h,g,k,l,m,n,p,q,s,r,u;if(null===(h=$p.hasattr(b,"_clickListeners"))||!1===h||0===h||""===h?0:"object"==typeof h?"function"==typeof h.__nonzero__?h.__nonzero__():"function"==typeof h.__len__?0<h.__len__():1:1)d.ClickHandler.onBrowserEvent(b,a);if(null===(g=$p.hasattr(b,"_keyboardListeners"))||!1===g||0===g||""===g?0:"object"==typeof g?"function"==typeof g.__nonzero__?g.__nonzero__():"function"==typeof g.__len__?0<g.__len__():1:1)d.KeyboardHandler.onBrowserEvent(b,a);if(null===
(n=$p.hasattr(b,"_mouseListeners"))||!1===n||0===n||""===n?0:"object"==typeof n?"function"==typeof n.__nonzero__?n.__nonzero__():"function"==typeof n.__len__?0<n.__len__():1:1)d.MouseHandler.onBrowserEvent(b,a);if(null===(p=$p.hasattr(b,"_mouseWheelListeners"))||!1===p||0===p||""===p?0:"object"==typeof p?"function"==typeof p.__nonzero__?p.__nonzero__():"function"==typeof p.__len__?0<p.__len__():1:1)d.MouseWheelHandler.onBrowserEvent(b,a);if(null===(l=$p.hasattr(b,"_focusListeners"))||!1===l||0===
l||""===l?0:"object"==typeof l?"function"==typeof l.__nonzero__?l.__nonzero__():"function"==typeof l.__len__?0<l.__len__():1:1)d.FocusHandler.onBrowserEvent(b,a);if(null===(m=$p.hasattr(b,"_dragListeners"))||!1===m||0===m||""===m?0:"object"==typeof m?"function"==typeof m.__nonzero__?m.__nonzero__():"function"==typeof m.__len__?0<m.__len__():1:1)d.DragHandler.onBrowserEvent(b,a);if(null===(q=$p.hasattr(b,"_changeListeners"))||!1===q||0===q||""===q?0:"object"==typeof q?"function"==typeof q.__nonzero__?
q.__nonzero__():"function"==typeof q.__len__?0<q.__len__():1:1)d.ChangeHandler.onBrowserEvent(b,a);if(null===(s=$p.hasattr(b,"_inputListeners"))||!1===s||0===s||""===s?0:"object"==typeof s?"function"==typeof s.__nonzero__?s.__nonzero__():"function"==typeof s.__len__?0<s.__len__():1:1)d.InputHandler.onBrowserEvent(b,a);if(null===(c=$p.hasattr(b,"_dropListeners"))||!1===c||0===c||""===c?0:"object"==typeof c?"function"==typeof c.__nonzero__?c.__nonzero__():"function"==typeof c.__len__?0<c.__len__():
1:1)d.DropHandler.onBrowserEvent(b,a);return(null===(f=null===(null==(r=(u=b).contextMenu)||u.__is_instance__&&"function"==typeof r||"function"==typeof r.__get__?$p.getattr(u,"contextMenu"):b.contextMenu))||!1===f||0===f||""===f?0:"object"==typeof f?"function"==typeof f.__nonzero__?f.__nonzero__():"function"==typeof f.__len__?0<f.__len__():1:1)?!0:(null===(k="contextmenu"===(t=d.DOM.eventGetType(a))&&null===t?!0:null===t?!1:"object"!=typeof t&&"function"!=typeof t||"function"!=typeof t.__cmp__?"contextmenu"==
t:0===t.__cmp__("contextmenu"))||!1===k||0===k||""===k?0:"object"==typeof k?"function"==typeof k.__nonzero__?k.__nonzero__():"function"==typeof k.__len__?0<k.__len__():1:1)?(d.DOM.eventCancelBubble(a,!0),d.DOM.eventPreventDefault(a),b.contextMenu.onContextMenu(b),!1):!0},1,[null,null,["self"],["event"]]);f.onBrowserEvent=c;c=$pyjs__bind_method2("onLoad",function(a){return null},1,[null,null,["self"]]);f.onLoad=c;c=$pyjs__bind_method2("doDetachChildren",function(a){return null},1,[null,null,["self"]]);
f.doDetachChildren=c;c=$pyjs__bind_method2("doAttachChildren",function(a){return null},1,[null,null,["self"]]);f.doAttachChildren=c;c=$pyjs__bind_method2("onAttach",function(a){a=!0===this.__is_instance__?this:a;var e;if(null===(e=a.isAttached())||!1===e||0===e||""===e?0:"object"==typeof e?"function"==typeof e.__nonzero__?e.__nonzero__():"function"==typeof e.__len__?0<e.__len__():1:1)return null;a.__is_instance__&&"function"==typeof a.__setattr__?a.__setattr__("attached",!0):$p.setattr(a,"attached",
!0);d.DOM.setEventListener(a.getElement(),a);a.doAttachChildren();a.onLoad();return null},1,[null,null,["self"]]);f.onAttach=c;c=$pyjs__bind_method2("onDetach",function(a){a=!0===this.__is_instance__?this:a;var e,b;if(null===(b=!(null===(e=a.isAttached())||!1===e||0===e||""===e?0:"object"==typeof e?"function"==typeof e.__nonzero__?e.__nonzero__():"function"==typeof e.__len__?0<e.__len__():1:1))||!1===b||0===b||""===b?0:"object"==typeof b?"function"==typeof b.__nonzero__?b.__nonzero__():"function"==
typeof b.__len__?0<b.__len__():1:1)return null;a.doDetachChildren();a.__is_instance__&&"function"==typeof a.__setattr__?a.__setattr__("attached",!1):$p.setattr(a,"attached",!1);d.DOM.setEventListener(a.getElement(),null);return null},1,[null,null,["self"]]);f.onDetach=c;c=$pyjs__bind_method2("setLayoutData",function(a,e){if(!0===this.__is_instance__)var b=this;else b=a,a=e;b.__is_instance__&&"function"==typeof b.__setattr__?b.__setattr__("layoutData",a):$p.setattr(b,"layoutData",a);return null},1,
[null,null,["self"],["layoutData"]]);f.setLayoutData=c;c=$pyjs__bind_method2("setParent",function(a,e){if(!0===this.__is_instance__)var b=this;else b=a,a=e;var c,d,f,h,g,k,l,m,n,p,q;f=null==(q=(n=b).parent)||n.__is_instance__&&"function"==typeof q||"function"==typeof q.__get__?$p.getattr(n,"parent"):b.parent;b.__is_instance__&&"function"==typeof b.__setattr__?b.__setattr__("parent",a):$p.setattr(b,"parent",a);if(null===(g=null===a)||!1===g||0===g||""===g?0:"object"==typeof g?"function"==typeof g.__nonzero__?
g.__nonzero__():"function"==typeof g.__len__?0<g.__len__():1:1){if(null===(c=(null===(k=h=null!==f)||!1===k||0===k||""===k?0:"object"==typeof k?"function"==typeof k.__nonzero__?k.__nonzero__():"function"==typeof k.__len__?0<k.__len__():1:1)?null==(m=f.attached)||f.__is_instance__&&"function"==typeof m||"function"==typeof m.__get__?$p.getattr(f,"attached"):f.attached:h)||!1===c||0===c||""===c?0:"object"==typeof c?"function"==typeof c.__nonzero__?c.__nonzero__():"function"==typeof c.__len__?0<c.__len__():
1:1)b.onDetach()}else if(null===(d=null==(p=(l=a).attached)||l.__is_instance__&&"function"==typeof p||"function"==typeof p.__get__?$p.getattr(l,"attached"):a.attached)||!1===d||0===d||""===d?0:"object"==typeof d?"function"==typeof d.__nonzero__?d.__nonzero__():"function"==typeof d.__len__?0<d.__len__():1:1)b.onAttach();return null},1,[null,null,["self"],["parent"]]);f.setParent=c;c=$pyjs__bind_method2("removeFromParent",function(a){a=!0===this.__is_instance__?this:a;var c,b;(null===(b=$p.hasattr(null==
(c=a.parent)||a.__is_instance__&&"function"==typeof c||"function"==typeof c.__get__?$p.getattr(a,"parent"):a.parent,"remove"))||!1===b||0===b||""===b?0:"object"==typeof b?"function"==typeof b.__nonzero__?b.__nonzero__():"function"==typeof b.__len__?0<b.__len__():1:1)&&a.parent.remove(a);return null},1,[null,null,["self"]]);f.removeFromParent=c;c=$pyjs__bind_method2("getID",function(a){return d.DOM.getAttribute((!0===this.__is_instance__?this:a).getElement(),"id")},1,[null,null,["self"]]);f.getID=
c;c=$pyjs__bind_method2("setID",function(a,c){if(!0===this.__is_instance__)var b=this;else b=a,a=c;d.DOM.setAttribute(b.getElement(),"id",a);return null},1,[null,null,["self"],["id"]]);f.setID=c;c=Array(d.UIObject);var r=$p.dict(),u;for(u in f)r.__setitem__(u,f[u]);return $p._create_class("Widget",$p.tuple(c),r)}();d.Factory.registerClass("pyjamas.ui.Widget","Widget",d.Widget);return this};
