$pyjs.loaded_modules["pyjamas.Window"]=function(h){if($pyjs.loaded_modules["pyjamas.Window"].__was_initialized__)return $pyjs.loaded_modules["pyjamas.Window"];"undefined"!=typeof $pyjs.loaded_modules.pyjamas&&$pyjs.loaded_modules.pyjamas.__was_initialized__||$p.___import___("pyjamas",null);var a=$pyjs.loaded_modules["pyjamas.Window"];a.__repr__=function(){return"<module: pyjamas.Window>"};a.__was_initialized__=!0;if(null===h||"undefined"==typeof h)h="pyjamas.Window";a.__name__=h;$pyjs.loaded_modules.pyjamas.Window=
$pyjs.loaded_modules["pyjamas.Window"];a.closingListeners=$p.list([]);a.resizeListeners=$p.list([]);a.Location=$p.___import___("pyjamas.Location","pyjamas",null,!1);a.init_listeners=function(){return null};a.init_listeners.__name__="init_listeners";a.init_listeners.__bind_type__=0;a.init_listeners.__args__=[null,null];a.addWindowCloseListener=function(e){a.closingListeners.append(e);return null};a.addWindowCloseListener.__name__="addWindowCloseListener";a.addWindowCloseListener.__bind_type__=0;a.addWindowCloseListener.__args__=
[null,null,["listener"]];a.addWindowResizeListener=function(e){a.resizeListeners.append(e);return null};a.addWindowResizeListener.__name__="addWindowResizeListener";a.addWindowResizeListener.__bind_type__=0;a.addWindowResizeListener.__args__=[null,null,["listener"]];a.removeWindowCloseListener=function(e){a.closingListeners.remove(e);return null};a.removeWindowCloseListener.__name__="removeWindowCloseListener";a.removeWindowCloseListener.__bind_type__=0;a.removeWindowCloseListener.__args__=[null,
null,["listener"]];a.removeWindowResizeListener=function(e){a.resizeListeners.remove(e);return null};a.removeWindowResizeListener.__name__="removeWindowResizeListener";a.removeWindowResizeListener.__bind_type__=0;a.removeWindowResizeListener.__args__=[null,null,["listener"]];a.alert=function(e){a.get_main_frame()._alert(e);return null};a.alert.__name__="alert";a.alert.__bind_type__=0;a.alert.__args__=[null,null,["txt"]];a.confirm=function(a){return $wnd.confirm(a)};a.confirm.__name__="confirm";a.confirm.__bind_type__=
0;a.confirm.__args__=[null,null,["msg"]];a.prompt=function(a,b){"undefined"==typeof b&&(b=arguments.callee.__args__[3][1]);return $wnd.prompt(a,b,"",0)};a.prompt.__name__="prompt";a.prompt.__bind_type__=0;a.prompt.__args__=[null,null,["msg"],["defaultReply",""]];a.enableScrolling=function(a){var b,d,c,f;$doc.body.style.__is_instance__&&"function"==typeof $doc.body.style.__setattr__?$doc.body.style.__setattr__("overflow",(null===(c=b=(null===(f=d=a)||!1===f||0===f||""===f?0:"object"==typeof f?"function"==
typeof f.__nonzero__?f.__nonzero__():"function"==typeof f.__len__?0<f.__len__():1:1)?"auto":d)||!1===c||0===c||""===c?0:"object"==typeof c?"function"==typeof c.__nonzero__?c.__nonzero__():"function"==typeof c.__len__?0<c.__len__():1:1)?b:"hidden"):$p.setattr($doc.body.style,"overflow",(null===(c=b=(null===(f=d=a)||!1===f||0===f||""===f?0:"object"==typeof f?"function"==typeof f.__nonzero__?f.__nonzero__():"function"==typeof f.__len__?0<f.__len__():1:1)?"auto":d)||!1===c||0===c||""===c?0:"object"==
typeof c?"function"==typeof c.__nonzero__?c.__nonzero__():"function"==typeof c.__len__?0<c.__len__():1:1)?b:"hidden");return null};a.enableScrolling.__name__="enableScrolling";a.enableScrolling.__bind_type__=0;a.enableScrolling.__args__=[null,null,["enable"]];a.scrollBy=function(a,b){$wnd.scrollBy(a,b);return null};a.scrollBy.__name__="scrollBy";a.scrollBy.__bind_type__=0;a.scrollBy.__args__=[null,null,["x"],["y"]];a.scroll=function(a,b){$wnd.scroll(a,b);return null};a.scroll.__name__="scroll";a.scroll.__bind_type__=
0;a.scroll.__args__=[null,null,["x"],["y"]];a.getClientHeight=function(){var e,b,d,c;try{return null==(e=(d=$wnd).innerHeight)||d.__is_instance__&&"function"==typeof e||"function"==typeof e.__get__?$p.getattr(d,"innerHeight"):$wnd.innerHeight}catch(f){return $pyjs.__last_exception__={error:f,module:a},null==(b=(c=$doc.body).clientHeight)||c.__is_instance__&&"function"==typeof b||"function"==typeof b.__get__?$p.getattr(c,"clientHeight"):$doc.body.clientHeight}};a.getClientHeight.__name__="getClientHeight";
a.getClientHeight.__bind_type__=0;a.getClientHeight.__args__=[null,null];a.getClientWidth=function(){var e,b,d,c;try{return null==(b=(c=$wnd).innerWidth)||c.__is_instance__&&"function"==typeof b||"function"==typeof b.__get__?$p.getattr(c,"innerWidth"):$wnd.innerWidth}catch(f){return $pyjs.__last_exception__={error:f,module:a},null==(d=(e=$doc.body).clientWidth)||e.__is_instance__&&"function"==typeof d||"function"==typeof d.__get__?$p.getattr(e,"clientWidth"):$doc.body.clientWidth}};a.getClientWidth.__name__=
"getClientWidth";a.getClientWidth.__bind_type__=0;a.getClientWidth.__args__=[null,null];a.getScrollLeft=function(){var e,b;return null==(e=(b=a.getDocumentRoot()).scrollLeft)||b.__is_instance__&&"function"==typeof e||"function"==typeof e.__get__?$p.getattr(b,"scrollLeft"):a.getDocumentRoot().scrollLeft};a.getScrollLeft.__name__="getScrollLeft";a.getScrollLeft.__bind_type__=0;a.getScrollLeft.__args__=[null,null];a.getScrollTop=function(){var e,b;return null==(e=(b=a.getDocumentRoot()).scrollTop)||
b.__is_instance__&&"function"==typeof e||"function"==typeof e.__get__?$p.getattr(b,"scrollTop"):a.getDocumentRoot().scrollTop};a.getScrollTop.__name__="getScrollTop";a.getScrollTop.__bind_type__=0;a.getScrollTop.__args__=[null,null];a.getDocumentRoot=function(){var a,b,d,c,f,g,k,h;return(null===(b="CSS1Compat"===(a=null==(h=(f=$doc).compatMode)||f.__is_instance__&&"function"==typeof h||"function"==typeof h.__get__?$p.getattr(f,"compatMode"):$doc.compatMode)&&null===a?!0:null===a?!1:"object"!=typeof a&&
"function"!=typeof a||"function"!=typeof a.__cmp__?"CSS1Compat"==a:0===a.__cmp__("CSS1Compat"))||!1===b||0===b||""===b?0:"object"==typeof b?"function"==typeof b.__nonzero__?b.__nonzero__():"function"==typeof b.__len__?0<b.__len__():1:1)?null==(c=(k=$doc).documentElement)||k.__is_instance__&&"function"==typeof c||"function"==typeof c.__get__?$p.getattr(k,"documentElement"):$doc.documentElement:null==(g=(d=$doc).body)||d.__is_instance__&&"function"==typeof g||"function"==typeof g.__get__?$p.getattr(d,
"body"):$doc.body};a.getDocumentRoot.__name__="getDocumentRoot";a.getDocumentRoot.__bind_type__=0;a.getDocumentRoot.__args__=[null,null];a.setLocation=function(a){var b;b=$wnd;b.__is_instance__&&"function"==typeof b.__setattr__?b.__setattr__("location",a):$p.setattr(b,"location",a);return null};a.setLocation.__name__="setLocation";a.setLocation.__bind_type__=0;a.setLocation.__args__=[null,null,["url"]];a.location=null;a.getLocation=function(){var e,b,d,c;if(null===(c=!(null===(d=a.location)||!1===
d||0===d||""===d?0:"object"==typeof d?"function"==typeof d.__nonzero__?d.__nonzero__():"function"==typeof d.__len__?0<d.__len__():1:1))||!1===c||0===c||""===c?0:"object"==typeof c?"function"==typeof c.__nonzero__?c.__nonzero__():"function"==typeof c.__len__?0<c.__len__():1:1)a.location=a.Location.Location(null==(b=(e=$wnd).location)||e.__is_instance__&&"function"==typeof b||"function"==typeof b.__get__?$p.getattr(e,"location"):$wnd.location);return a.location};a.getLocation.__name__="getLocation";
a.getLocation.__bind_type__=0;a.getLocation.__args__=[null,null];a.getTitle=function(){var a,b;return null==(a=(b=$doc).title)||b.__is_instance__&&"function"==typeof a||"function"==typeof a.__get__?$p.getattr(b,"title"):$doc.title};a.getTitle.__name__="getTitle";a.getTitle.__bind_type__=0;a.getTitle.__args__=[null,null];a.open=function(a,b,d){return $wnd.open(a,b,d)};a.open.__name__="open";a.open.__bind_type__=0;a.open.__args__=[null,null,["url"],["name"],["features"]];a.setMargin=function(a){$doc.body.style.__is_instance__&&
"function"==typeof $doc.body.style.__setattr__?$doc.body.style.__setattr__("margin",a):$p.setattr($doc.body.style,"margin",a);return null};a.setMargin.__name__="setMargin";a.setMargin.__bind_type__=0;a.setMargin.__args__=[null,null,["size"]];a.setTitle=function(a){var b;b=$doc;b.__is_instance__&&"function"==typeof b.__setattr__?b.__setattr__("title",a):$p.setattr(b,"title",a);return null};a.setTitle.__name__="setTitle";a.setTitle.__bind_type__=0;a.setTitle.__args__=[null,null,["title"]];a.setOnError=
function(a){return null};a.setOnError.__name__="setOnError";a.setOnError.__bind_type__=0;a.setOnError.__args__=[null,null,["onError"]];a.onError=function(a,b,d){return null};a.onError.__name__="onError";a.onError.__bind_type__=0;a.onError.__args__=[null,null,["msg"],["url"],["linenumber"]];a.onClosed=function(){("undefined"==typeof fireClosedImpl?a.fireClosedImpl:fireClosedImpl)();return null};a.onClosed.__name__="onClosed";a.onClosed.__bind_type__=0;a.onClosed.__args__=[null,null];a.onClosing=function(){("undefined"==
typeof fireClosingImpl?a.fireClosingImpl:fireClosingImpl)();return null};a.onClosing.__name__="onClosing";a.onClosing.__bind_type__=0;a.onClosing.__args__=[null,null];a.onResize=function(){("undefined"==typeof fireResizedImpl?a.fireResizedImpl:fireResizedImpl)();return null};a.onResize.__name__="onResize";a.onResize.__bind_type__=0;a.onResize.__args__=[null,null];a.fireClosedAndCatch=function(a){return null};a.fireClosedAndCatch.__name__="fireClosedAndCatch";a.fireClosedAndCatch.__bind_type__=0;a.fireClosedAndCatch.__args__=
[null,null,["handler"]];a.fireClosedImpl=function(){var e,b,d,c,f;d=a.closingListeners;"undefined"!=typeof(c=d.__array)?b=0:(d=d.__iter__(),b="undefined"!=typeof(c=d.__array)?0:"function"==typeof d.$genfunc?1:-1);for(f=0;"undefined"!=typeof(e=b?0<b?d.next(!0,!1):$p.wrapped_next(d):c[f++]);)e.onWindowClosed();return null};a.fireClosedImpl.__name__="fireClosedImpl";a.fireClosedImpl.__bind_type__=0;a.fireClosedImpl.__args__=[null,null];a.fireClosingAndCatch=function(a){return null};a.fireClosingAndCatch.__name__=
"fireClosingAndCatch";a.fireClosingAndCatch.__bind_type__=0;a.fireClosingAndCatch.__args__=[null,null,["handler"]];a.resize=function(a,b){$wnd.resizeTo(a,b);return null};a.resize.__name__="resize";a.resize.__bind_type__=0;a.resize.__args__=[null,null,["width"],["height"]];a.resizeBy=function(a,b){$wnd.resizeBy(a,b);return null};a.resizeBy.__name__="resizeBy";a.resizeBy.__bind_type__=0;a.resizeBy.__args__=[null,null,["width"],["height"]];a.fireClosingImpl=function(){var e,b,d,c,f,g,h;c=null;d=a.closingListeners;
"undefined"!=typeof(h=d.__array)?b=0:(d=d.__iter__(),b="undefined"!=typeof(h=d.__array)?0:"function"==typeof d.$genfunc?1:-1);for(f=0;"undefined"!=typeof(e=b?0<b?d.next(!0,!1):$p.wrapped_next(d):h[f++]);)if(e=e.onWindowClosing(),null===(g=null===c)||!1===g||0===g||""===g?0:"object"==typeof g?"function"==typeof g.__nonzero__?g.__nonzero__():"function"==typeof g.__len__?0<g.__len__():1:1)c=e;return c};a.fireClosingImpl.__name__="fireClosingImpl";a.fireClosingImpl.__bind_type__=0;a.fireClosingImpl.__args__=
[null,null];a.fireResizedAndCatch=function(a){return null};a.fireResizedAndCatch.__name__="fireResizedAndCatch";a.fireResizedAndCatch.__bind_type__=0;a.fireResizedAndCatch.__args__=[null,null,["handler"]];a.fireResizedImpl=function(){var e,b,d,c,f;c=a.resizeListeners;"undefined"!=typeof(f=c.__array)?d=0:(c=c.__iter__(),d="undefined"!=typeof(f=c.__array)?0:"function"==typeof c.$genfunc?1:-1);for(e=0;"undefined"!=typeof(b=d?0<d?c.next(!0,!1):$p.wrapped_next(c):f[e++]);)b.onWindowResized(a.getClientWidth(),
a.getClientHeight());return null};a.fireResizedImpl.__name__="fireResizedImpl";a.fireResizedImpl.__bind_type__=0;a.fireResizedImpl.__args__=[null,null];a.init=function(){return null};a.init.__name__="init";a.init.__bind_type__=0;a.init.__args__=[null,null];a.init();return this};
