$pyjs.loaded_modules["pyjsdl.image"]=function(f){if($pyjs.loaded_modules["pyjsdl.image"].__was_initialized__)return $pyjs.loaded_modules["pyjsdl.image"];"undefined"!=typeof $pyjs.loaded_modules.pyjsdl&&$pyjs.loaded_modules.pyjsdl.__was_initialized__||$p.___import___("pyjsdl",null);var b=$pyjs.loaded_modules["pyjsdl.image"];b.__repr__=function(){return"<module: pyjsdl.image>"};b.__was_initialized__=!0;if(null===f||"undefined"==typeof f)f="pyjsdl.image";b.__name__=f;$pyjs.loaded_modules.pyjsdl.image=
$pyjs.loaded_modules["pyjsdl.image"];b.os=$p.___import___("os","pyjsdl");b.Surface=$p.___import___("pyjsdl.surface.Surface","pyjsdl",null,!1);b.Surf=$p.___import___("pyjsdl.surface.Surf","pyjsdl",null,!1);b.env=$p.___import___("pyjsdl.env","pyjsdl",null,!1);b.pyjsdl=$p.___import___("pyjsdl","pyjsdl");b.__docformat__="restructuredtext";b.Image=function(){var g={},h;g.__module__="pyjsdl.image";h=$pyjs__bind_method2("__init__",function(d){d=!0===this.__is_instance__?this:d;d.__is_instance__&&"function"==
typeof d.__setattr__?d.__setattr__("images",null):$p.setattr(d,"images",null);return null},1,[null,null,["self"]]);g.__init__=h;h=$pyjs__bind_method2("load",function(d,b){if(!0===this.__is_instance__)var c=this;else c=arguments[0],d=arguments[1],b=arguments[2];"undefined"==typeof b&&(b=arguments.callee.__args__[4][1]);var e,a,m;m=(null===(e=!(null===(a=b)||!1===a||0===a||""===a?0:"object"==typeof a?"function"==typeof a.__nonzero__?a.__nonzero__():"function"==typeof a.__len__?0<a.__len__():1:1))||
!1===e||0===e||""===e?0:"object"==typeof e?"function"==typeof e.__nonzero__?e.__nonzero__():"function"==typeof e.__len__?0<e.__len__():1:1)?c.get_image(d):c.get_image(b);return c.convert_image(m)},1,[null,null,["self"],["img_file"],["namehint",null]]);g.load=h;h=$pyjs__bind_method2("get_image",function(d,h){if(!0===this.__is_instance__)var c=this;else c=d,d=h;var e,a,m,n,f,g,l,t,u,v,k,w,x,q,r,y;if(null===(k=null===(null==(a=(n=c).images)||n.__is_instance__&&"function"==typeof a||"function"==typeof a.__get__?
$p.getattr(n,"images"):c.images))||!1===k||0===k||""===k?0:"object"==typeof k?"function"==typeof k.__nonzero__?k.__nonzero__():"function"==typeof k.__len__?0<k.__len__():1:1)for(c.__is_instance__&&"function"==typeof c.__setattr__?c.__setattr__("images",$p.dict([])):$p.setattr(c,"images",$p.dict([])),a=b.env.canvas.images,"undefined"!=typeof(n=a.__array)?k=0:(a=a.__iter__(),k="undefined"!=typeof(n=a.__array)?0:"function"==typeof a.$genfunc?1:-1),y=0;"undefined"!=typeof(m=k?0<k?a.next(!0,!1):$p.wrapped_next(a):
n[y++]);)(null==(l=(v=c).images)||v.__is_instance__&&"function"==typeof l||"function"==typeof l.__get__?$p.getattr(v,"images"):c.images).__setitem__(b.os.path.normpath(m),"undefined"!=typeof(r=null==(g=(t=b.env.canvas).images)||t.__is_instance__&&"function"==typeof g||"function"==typeof g.__get__?$p.getattr(t,"images"):b.env.canvas.images).__array?"undefined"!=typeof r.__array[x=m]?r.__array[x]:r.__getitem__(x):r.__getitem__(m));d=b.os.path.normpath(d);try{e="undefined"!=typeof(q=null==(u=(f=c).images)||
f.__is_instance__&&"function"==typeof u||"function"==typeof u.__get__?$p.getattr(f,"images"):c.images).__array?"undefined"!=typeof q.__array[w=d]?q.__array[w]:q.__getitem__(w):q.__getitem__(d)}catch(p){c="undefined"==typeof p.__name__?p.name:p.__name__;$pyjs.__last_exception__={error:p,module:b};if(c==$p.KeyError.__name__||$p._isinstance(p,$p.KeyError))throw b.pyjsdl.error($p.sprintf("Failed to retrieve image file %s",d));$pyjs.__active_exception_stack__=$pyjs.__last_exception_stack__;$pyjs.__last_exception_stack__=
null;throw p;}return e},1,[null,null,["self"],["img_file"]]);g.get_image=h;h=$pyjs__bind_method2("convert_image",function(d,h){!0!==this.__is_instance__&&(d=h);var c,e,a,f,g,l,s;(null===(a=null==(c=(e=b.env.canvas)._isCanvas)||e.__is_instance__&&"function"==typeof c||"function"==typeof c.__get__?$p.getattr(e,"_isCanvas"):b.env.canvas._isCanvas)||!1===a||0===a||""===a?0:"object"==typeof a?"function"==typeof a.__nonzero__?a.__nonzero__():"function"==typeof a.__len__?0<a.__len__():1:1)?(c=b.Surface($p.tuple([null==
(g=(s=d).width)||s.__is_instance__&&"function"==typeof g||"function"==typeof g.__get__?$p.getattr(s,"width"):d.width,null==(l=(f=d).height)||f.__is_instance__&&"function"==typeof l||"function"==typeof l.__get__?$p.getattr(f,"height"):d.height])),c.drawImage(d,0,0)):c=b.Surf(d);return c},1,[null,null,["self"],["image"]]);g.convert_image=h;h=Array($p.object);var f=$p.dict(),l;for(l in g)f.__setitem__(l,g[l]);return $p._create_class("Image",$p.tuple(h),f)}();return this};
