$pyjs.loaded_modules["pyjsdl.cursors"]=function(G){if($pyjs.loaded_modules["pyjsdl.cursors"].__was_initialized__)return $pyjs.loaded_modules["pyjsdl.cursors"];"undefined"!=typeof $pyjs.loaded_modules.pyjsdl&&$pyjs.loaded_modules.pyjsdl.__was_initialized__||$p.___import___("pyjsdl",null);var a=$pyjs.loaded_modules["pyjsdl.cursors"];a.__repr__=function(){return"<module: pyjsdl.cursors>"};a.__was_initialized__=!0;if(null===G||"undefined"==typeof G)G="pyjsdl.cursors";a.__name__=G;$pyjs.loaded_modules.pyjsdl.cursors=
$pyjs.loaded_modules["pyjsdl.cursors"];a.Surface=$p.___import___("pyjsdl.surface.Surface","pyjsdl",null,!1);a.Color=$p.___import___("pyjsdl.color.Color","pyjsdl",null,!1);a.Const=$p.___import___("pyjsdl.locals","pyjsdl",null,!1);a.$assign1=$p.tuple([]);a.arrow=a.$assign1;a.diamond=a.$assign1;a.broken_x=a.$assign1;a.tri_left=a.$assign1;a.tri_right=a.$assign1;a.compile=function(a,e,H,q){"undefined"==typeof e&&(e=arguments.callee.__args__[3][1]);"undefined"==typeof H&&(H=arguments.callee.__args__[4][1]);
"undefined"==typeof q&&(q=arguments.callee.__args__[5][1]);var f,m,g,r,s,M,v,b,w,I,t,h,c,u,n,d,z,p,k,J,x,A,D,E,y,l,B,L,F,C;J=$p.list([]);B=$p.list([]);M=$p.dict([[e,1],[H,0],[q,1]]);D=$p.dict([[e,1],[H,1],[q,0]]);b="".join(a);f=$p.range(0,null===b?0:"undefined"!=typeof b.__array?b.__array.length:"function"==typeof b.__len__?b.__len__():"undefined"!=typeof b.length?b.length:$p.len(b),8);"undefined"!=typeof(s=f.__array)?E=0:(f=f.__iter__(),E="undefined"!=typeof(s=f.__array)?0:"function"==typeof f.$genfunc?
1:-1);for(F=0;"undefined"!=typeof(m=E?0<E?f.next(!0,!1):$p.wrapped_next(f):s[F++]);){L=$p.__getslice(b,m,m+8);y=I=0;if(null===(n=!("        "===(v=L)&&null===v||(null===v?0:"object"!=typeof v&&"function"!=typeof v||"function"!=typeof v.__cmp__?"        "==v:0===v.__cmp__("        "))))||!1===n||0===n||""===n?0:"object"==typeof n?"function"==typeof n.__nonzero__?n.__nonzero__():"function"==typeof n.__len__?0<n.__len__():1:1)for(g=$p.range(8),"undefined"!=typeof(C=g.__array)?m=0:(g=g.__iter__(),m="undefined"!=
typeof(C=g.__array)?0:"function"==typeof g.$genfunc?1:-1),u=0;"undefined"!=typeof(t=m?0<m?g.next(!0,!1):$p.wrapped_next(g):C[u++]);)if(l=t,t="undefined"!=typeof(A=L).__array?"undefined"!=typeof A.__array[r=l]?A.__array[r]:A.__getitem__(r):A.__getitem__(l),!(null===(h=" "===(w=t)&&null===w?!0:null===w?!1:"object"!=typeof w&&"function"!=typeof w||"function"!=typeof w.__cmp__?" "==w:0===w.__cmp__(" "))||!1===h||0===h||""===h?0:"object"==typeof h?"function"==typeof h.__nonzero__?h.__nonzero__():"function"==
typeof h.__len__?0<h.__len__():1:1)){if(null===(c="undefined"!=typeof(x=M).__array?"undefined"!=typeof x.__array[p=t]?x.__array[p]:x.__getitem__(p):x.__getitem__(t))||!1===c||0===c||""===c?0:"object"==typeof c?"function"==typeof c.__nonzero__?c.__nonzero__():"function"==typeof c.__len__?0<c.__len__():1:1)I|=1<<7-l;if(null===(d="undefined"!=typeof(k=D).__array?"undefined"!=typeof k.__array[z=t]?k.__array[z]:k.__getitem__(z):k.__getitem__(t))||!1===d||0===d||""===d?0:"object"==typeof d?"function"==
typeof d.__nonzero__?d.__nonzero__():"function"==typeof d.__len__?0<d.__len__():1:1)y|=1<<7-l}J.append($p.float_int(I));B.append($p.float_int(y))}return $p.tuple([$p.tuple(J),$p.tuple(B)])};a.compile.__name__="compile";a.compile.__bind_type__=0;a.compile.__args__=[null,null,["strings"],["black","X"],["white","."],["xor","o"]];a.create_cursor=function(G,e,H){var q,f,m,g,r,s,M,v,b,w,I,t,h,c,u,n,d,z,p,k,J,x,A,D,E,y,l,B,L,F,C,K;m=a.Surface(G,null==(q=(f=a.Const).SRCALPHA)||f.__is_instance__&&"function"==
typeof q||"function"==typeof q.__get__?$p.getattr(f,"SRCALPHA"):a.Const.SRCALPHA);v=a.Color(0,0,0,255);w=a.Color(255,255,255,255);C=K=0;b=$p.range(null===e?0:"undefined"!=typeof e.__array?e.__array.length:"function"==typeof e.__len__?e.__len__():"undefined"!=typeof e.length?e.length:$p.len(e));"undefined"!=typeof(f=b.__array)?q=0:(b=b.__iter__(),q="undefined"!=typeof(f=b.__array)?0:"function"==typeof b.$genfunc?1:-1);for(M=0;"undefined"!=typeof(g=q?0<q?b.next(!0,!1):$p.wrapped_next(b):f[M++]);){l=
g;if(null===(c=(null===(d=I="undefined"!=typeof(z=e).__array?"undefined"!=typeof z.__array[n=l]?z.__array[n]:z.__getitem__(n):z.__getitem__(l))||!1===d||0===d||""===d?0:"object"==typeof d?"function"==typeof d.__nonzero__?d.__nonzero__():"function"==typeof d.__len__?0<d.__len__():1:1)?I:"undefined"!=typeof(h=H).__array?"undefined"!=typeof h.__array[A=l]?h.__array[A]:h.__getitem__(A):h.__getitem__(l))||!1===c||0===c||""===c?0:"object"==typeof c?"function"==typeof c.__nonzero__?c.__nonzero__():"function"==
typeof c.__len__?0<c.__len__():1:1)for(r=$p.range(8),"undefined"!=typeof(t=r.__array)?g=0:(r=r.__iter__(),g="undefined"!=typeof(t=r.__array)?0:"function"==typeof r.$genfunc?1:-1),L=0;"undefined"!=typeof(B=g?0<g?r.next(!0,!1):$p.wrapped_next(r):t[L++]);)if(null===(u=("undefined"!=typeof(D=e).__array?"undefined"!=typeof D.__array[E=l]?D.__array[E]:D.__getitem__(E):D.__getitem__(l))&1<<7-B)||!1===u||0===u||""===u?0:"object"==typeof u?"function"==typeof u.__nonzero__?u.__nonzero__():"function"==typeof u.__len__?
0<u.__len__():1:1)m.setFillStyle(v),m.fillRect(K+B,C,1,1);else if(null===(p=("undefined"!=typeof(y=H).__array?"undefined"!=typeof y.__array[J=l]?y.__array[J]:y.__getitem__(J):y.__getitem__(l))&1<<7-B)||!1===p||0===p||""===p?0:"object"==typeof p?"function"==typeof p.__nonzero__?p.__nonzero__():"function"==typeof p.__len__?0<p.__len__():1:1)m.setFillStyle(w),m.fillRect(K+B,C,1,1);K+=8;if(null===(k=1==(((s=K)===(F="undefined"!=typeof(x=G).__array?"undefined"!=typeof x.__array[0]?x.__array[0]:x.__getitem__(0):
x.__getitem__(0))?0:typeof s!=typeof F||"number"!=typeof s&&"string"!=typeof s&&"boolean"!=typeof s?$p.cmp(s,F):s==F?0:s<F?-1:1)|1))||!1===k||0===k||""===k?0:"object"==typeof k?"function"==typeof k.__nonzero__?k.__nonzero__():"function"==typeof k.__len__?0<k.__len__():1:1)K=0,C+=1}return m};a.create_cursor.__name__="create_cursor";a.create_cursor.__bind_type__=0;a.create_cursor.__args__=[null,null,["size"],["data"],["mask"]];return this};
