$pyjs.loaded_modules["pyjsdl.mouse"]=function(w){if($pyjs.loaded_modules["pyjsdl.mouse"].__was_initialized__)return $pyjs.loaded_modules["pyjsdl.mouse"];"undefined"!=typeof $pyjs.loaded_modules.pyjsdl&&$pyjs.loaded_modules.pyjsdl.__was_initialized__||$p.___import___("pyjsdl",null);var k=$pyjs.loaded_modules["pyjsdl.mouse"];k.__repr__=function(){return"<module: pyjsdl.mouse>"};k.__was_initialized__=!0;if(null===w||"undefined"==typeof w)w="pyjsdl.mouse";k.__name__=w;$pyjs.loaded_modules.pyjsdl.mouse=
$pyjs.loaded_modules["pyjsdl.mouse"];k.env=$p.___import___("pyjsdl.env","pyjsdl",null,!1);k.cursors=$p.___import___("pyjsdl.cursors","pyjsdl",null,!1);k.DOM=$p.___import___("pyjsdl.pyjsobj.DOM","pyjsdl",null,!1);k.__docformat__="restructuredtext";k.Mouse=function(){var l={},c;l.__module__="pyjsdl.mouse";c=$pyjs__bind_method2("__init__",function(a){a=!0===this.__is_instance__?this:a;var b,d,g,f,e,h;a.__is_instance__&&"function"==typeof a.__setattr__?a.__setattr__("mousePress",null==(b=(d=k.env.event).mousePress)||
d.__is_instance__&&"function"==typeof b||"function"==typeof b.__get__?$p.getattr(d,"mousePress"):k.env.event.mousePress):$p.setattr(a,"mousePress",null==(b=(d=k.env.event).mousePress)||d.__is_instance__&&"function"==typeof b||"function"==typeof b.__get__?$p.getattr(d,"mousePress"):k.env.event.mousePress);a.__is_instance__&&"function"==typeof a.__setattr__?a.__setattr__("mouseMove",null==(h=(f=k.env.event).mouseMove)||f.__is_instance__&&"function"==typeof h||"function"==typeof h.__get__?$p.getattr(f,
"mouseMove"):k.env.event.mouseMove):$p.setattr(a,"mouseMove",null==(h=(f=k.env.event).mouseMove)||f.__is_instance__&&"function"==typeof h||"function"==typeof h.__get__?$p.getattr(f,"mouseMove"):k.env.event.mouseMove);a.__is_instance__&&"function"==typeof a.__setattr__?a.__setattr__("mouseMoveRel",null==(g=(e=k.env.event).mouseMoveRel)||e.__is_instance__&&"function"==typeof g||"function"==typeof g.__get__?$p.getattr(e,"mouseMoveRel"):k.env.event.mouseMoveRel):$p.setattr(a,"mouseMoveRel",null==(g=(e=
k.env.event).mouseMoveRel)||e.__is_instance__&&"function"==typeof g||"function"==typeof g.__get__?$p.getattr(e,"mouseMoveRel"):k.env.event.mouseMoveRel);a.__is_instance__&&"function"==typeof a.__setattr__?a.__setattr__("_cursorVisible",!0):$p.setattr(a,"_cursorVisible",!0);a.__is_instance__&&"function"==typeof a.__setattr__?a.__setattr__("_cursor","default"):$p.setattr(a,"_cursor","default");a._nonimplemented_methods();return null},1,[null,null,["self"]]);l.__init__=c;c=$pyjs__bind_method2("get_pressed",
function(a){a=!0===this.__is_instance__?this:a;var b,d,g,f,e,h;return $p.tuple(["undefined"!=typeof(h=null==(f=a.mousePress)||a.__is_instance__&&"function"==typeof f||"function"==typeof f.__get__?$p.getattr(a,"mousePress"):a.mousePress).__array?"undefined"!=typeof h.__array[0]?h.__array[0]:h.__getitem__(0):h.__getitem__(0),"undefined"!=typeof(e=null==(b=a.mousePress)||a.__is_instance__&&"function"==typeof b||"function"==typeof b.__get__?$p.getattr(a,"mousePress"):a.mousePress).__array?"undefined"!=
typeof e.__array[1]?e.__array[1]:e.__getitem__(1):e.__getitem__(1),"undefined"!=typeof(d=null==(g=a.mousePress)||a.__is_instance__&&"function"==typeof g||"function"==typeof g.__get__?$p.getattr(a,"mousePress"):a.mousePress).__array?"undefined"!=typeof d.__array[2]?d.__array[2]:d.__getitem__(2):d.__getitem__(2)])},1,[null,null,["self"]]);l.get_pressed=c;c=$pyjs__bind_method2("get_pos",function(a){a=!0===this.__is_instance__?this:a;var b,d,g,f,e,h,K,R,c,n,s,q,t,m,r,p;return(null===(h=!(-1===(e="undefined"!=
typeof(s=null==(t=a.mouseMove)||a.__is_instance__&&"function"==typeof t||"function"==typeof t.__get__?$p.getattr(a,"mouseMove"):a.mouseMove).__array?"undefined"!=typeof s.__array.x?s.__array.x:s.__getitem__("x"):s.__getitem__("x"))&&null===e||(null===e?0:"object"!=typeof e&&"function"!=typeof e||"function"!=typeof e.__cmp__?-1==e:0===e.__cmp__(-1))))||!1===h||0===h||""===h?0:"object"==typeof h?"function"==typeof h.__nonzero__?h.__nonzero__():"function"==typeof h.__len__?0<h.__len__():1:1)?$p.tuple([("undefined"!=
typeof(c=null==(n=a.mouseMove)||a.__is_instance__&&"function"==typeof n||"function"==typeof n.__get__?$p.getattr(a,"mouseMove"):a.mouseMove).__array?"undefined"!=typeof c.__array.x?c.__array.x:c.__getitem__("x"):c.__getitem__("x"))+(null==(q=(R=k.env.frame).scrollLeft)||R.__is_instance__&&"function"==typeof q||"function"==typeof q.__get__?$p.getattr(R,"scrollLeft"):k.env.frame.scrollLeft),("undefined"!=typeof(r=null==(K=a.mouseMove)||a.__is_instance__&&"function"==typeof K||"function"==typeof K.__get__?
$p.getattr(a,"mouseMove"):a.mouseMove).__array?"undefined"!=typeof r.__array.y?r.__array.y:r.__getitem__("y"):r.__getitem__("y"))+(null==(b=(d=k.env.frame).scrollTop)||d.__is_instance__&&"function"==typeof b||"function"==typeof b.__get__?$p.getattr(d,"scrollTop"):k.env.frame.scrollTop)]):$p.tuple(["undefined"!=typeof(p=null==(g=a.mouseMove)||a.__is_instance__&&"function"==typeof g||"function"==typeof g.__get__?$p.getattr(a,"mouseMove"):a.mouseMove).__array?"undefined"!=typeof p.__array.x?p.__array.x:
p.__getitem__("x"):p.__getitem__("x"),"undefined"!=typeof(m=null==(f=a.mouseMove)||a.__is_instance__&&"function"==typeof f||"function"==typeof f.__get__?$p.getattr(a,"mouseMove"):a.mouseMove).__array?"undefined"!=typeof m.__array.y?m.__array.y:m.__getitem__("y"):m.__getitem__("y")])},1,[null,null,["self"]]);l.get_pos=c;c=$pyjs__bind_method2("get_rel",function(a){a=!0===this.__is_instance__?this:a;var b,d,g,f,e,h,K,c,l,n,s,q,t,m,r,p,x,y,z,u,v,A,G,H,C;try{t=$p.tuple([("undefined"!=typeof(v=null==(h=
a.mouseMove)||a.__is_instance__&&"function"==typeof h||"function"==typeof h.__get__?$p.getattr(a,"mouseMove"):a.mouseMove).__array?"undefined"!=typeof v.__array.x?v.__array.x:v.__getitem__("x"):v.__getitem__("x"))-("undefined"!=typeof(G=null==(K=a.mouseMoveRel)||a.__is_instance__&&"function"==typeof K||"function"==typeof K.__get__?$p.getattr(a,"mouseMoveRel"):a.mouseMoveRel).__array?"undefined"!=typeof G.__array.x?G.__array.x:G.__getitem__("x"):G.__getitem__("x")),("undefined"!=typeof(n=null==(p=
a.mouseMove)||a.__is_instance__&&"function"==typeof p||"function"==typeof p.__get__?$p.getattr(a,"mouseMove"):a.mouseMove).__array?"undefined"!=typeof n.__array.y?n.__array.y:n.__getitem__("y"):n.__getitem__("y"))-("undefined"!=typeof(C=null==(r=a.mouseMoveRel)||a.__is_instance__&&"function"==typeof r||"function"==typeof r.__get__?$p.getattr(a,"mouseMoveRel"):a.mouseMoveRel).__array?"undefined"!=typeof C.__array.y?C.__array.y:C.__getitem__("y"):C.__getitem__("y"))]);var I=$p.__ass_unpack($p.tuple(["undefined"!=
typeof(s=null==(y=a.mouseMove)||a.__is_instance__&&"function"==typeof y||"function"==typeof y.__get__?$p.getattr(a,"mouseMove"):a.mouseMove).__array?"undefined"!=typeof s.__array.x?s.__array.x:s.__getitem__("x"):s.__getitem__("x"),"undefined"!=typeof(q=null==(x=a.mouseMove)||a.__is_instance__&&"function"==typeof x||"function"==typeof x.__get__?$p.getattr(a,"mouseMove"):a.mouseMove).__array?"undefined"!=typeof q.__array.y?q.__array.y:q.__getitem__("y"):q.__getitem__("y")]),2,null);(null==(z=a.mouseMoveRel)||
a.__is_instance__&&"function"==typeof z||"function"==typeof z.__get__?$p.getattr(a,"mouseMoveRel"):a.mouseMoveRel).__setitem__("x",I[0]);(null==(b=a.mouseMoveRel)||a.__is_instance__&&"function"==typeof b||"function"==typeof b.__get__?$p.getattr(a,"mouseMoveRel"):a.mouseMoveRel).__setitem__("y",I[1])}catch(B){if(t="undefined"==typeof B.__name__?B.name:B.__name__,$pyjs.__last_exception__={error:B,module:k},t==$p.TypeError.__name__||$p._isinstance(B,$p.TypeError)){if(t=$p.tuple([0,0]),null===(u=!(-1===
(m="undefined"!=typeof(l=null==(e=a.mouseMove)||a.__is_instance__&&"function"==typeof e||"function"==typeof e.__get__?$p.getattr(a,"mouseMove"):a.mouseMove).__array?"undefined"!=typeof l.__array.x?l.__array.x:l.__getitem__("x"):l.__getitem__("x"))&&null===m||(null===m?0:"object"!=typeof m&&"function"!=typeof m||"function"!=typeof m.__cmp__?-1==m:0===m.__cmp__(-1))))||!1===u||0===u||""===u?0:"object"==typeof u?"function"==typeof u.__nonzero__?u.__nonzero__():"function"==typeof u.__len__?0<u.__len__():
1:1)e=$p.__ass_unpack($p.tuple(["undefined"!=typeof(H=null==(f=a.mouseMove)||a.__is_instance__&&"function"==typeof f||"function"==typeof f.__get__?$p.getattr(a,"mouseMove"):a.mouseMove).__array?"undefined"!=typeof H.__array.x?H.__array.x:H.__getitem__("x"):H.__getitem__("x"),"undefined"!=typeof(d=null==(g=a.mouseMove)||a.__is_instance__&&"function"==typeof g||"function"==typeof g.__get__?$p.getattr(a,"mouseMove"):a.mouseMove).__array?"undefined"!=typeof d.__array.y?d.__array.y:d.__getitem__("y"):
d.__getitem__("y")]),2,null),(null==(c=a.mouseMoveRel)||a.__is_instance__&&"function"==typeof c||"function"==typeof c.__get__?$p.getattr(a,"mouseMoveRel"):a.mouseMoveRel).__setitem__("x",e[0]),(null==(A=a.mouseMoveRel)||a.__is_instance__&&"function"==typeof A||"function"==typeof A.__get__?$p.getattr(a,"mouseMoveRel"):a.mouseMoveRel).__setitem__("y",e[1])}else throw $pyjs.__active_exception_stack__=$pyjs.__last_exception_stack__,$pyjs.__last_exception_stack__=null,B;}return t},1,[null,null,["self"]]);
l.get_rel=c;c=$pyjs__bind_method2("set_visible",function(a,b){if(!0===this.__is_instance__)var d=this;else d=a,a=b;var g,f,e,h,c,l;c=null==(l=(e=d)._cursorVisible)||e.__is_instance__&&"function"==typeof l||"function"==typeof l.__get__?$p.getattr(e,"_cursorVisible"):d._cursorVisible;(null===(g=a)||!1===g||0===g||""===g?0:"object"==typeof g?"function"==typeof g.__nonzero__?g.__nonzero__():"function"==typeof g.__len__?0<g.__len__():1:1)?(k.DOM.setStyleAttribute(k.env.canvas.getElement(),"cursor",null==
(f=(h=d)._cursor)||h.__is_instance__&&"function"==typeof f||"function"==typeof f.__get__?$p.getattr(h,"_cursor"):d._cursor),d.__is_instance__&&"function"==typeof d.__setattr__?d.__setattr__("_cursorVisible",!0):$p.setattr(d,"_cursorVisible",!0)):(k.DOM.setStyleAttribute(k.env.canvas.getElement(),"cursor","none"),d.__is_instance__&&"function"==typeof d.__setattr__?d.__setattr__("_cursorVisible",!1):$p.setattr(d,"_cursorVisible",!1));return c},1,[null,null,["self"],["visible"]]);l.set_visible=c;c=$pyjs__bind_method2("set_cursor",
function(){if(!0===this.__is_instance__)var a=this,b=$p.tuple($pyjs_array_slice.call(arguments,0,arguments.length));else a=arguments[0],b=$p.tuple($pyjs_array_slice.call(arguments,1,arguments.length));var d,g,f,e,h,c,l,w,n,s,q,t,m,r,p,x,y,z,u,v,A,G,H,C,I,B,D,L,E,F,J,M,N,O,P,Q;t=null===(J=b)?0:"undefined"!=typeof J.__array?J.__array.length:"function"==typeof J.__len__?J.__len__():"undefined"!=typeof J.length?J.length:$p.len(J);(null===(y=1===(r=t)&&null===r?!0:null===r?!1:"object"!=typeof r&&"function"!=
typeof r||"function"!=typeof r.__cmp__?1==r:0===r.__cmp__(1))||!1===y||0===y||""===y?0:"object"==typeof y?"function"==typeof y.__nonzero__?y.__nonzero__():"function"==typeof y.__len__?0<y.__len__():1:1)?a.__is_instance__&&"function"==typeof a.__setattr__?a.__setattr__("_cursor","undefined"!=typeof(D=b).__array?"undefined"!=typeof D.__array[I=0]?D.__array[I]:D.__getitem__(I):D.__getitem__(0)):$p.setattr(a,"_cursor","undefined"!=typeof(D=b).__array?"undefined"!=typeof D.__array[I=0]?D.__array[I]:D.__getitem__(I):
D.__getitem__(0)):(null===(z=$p.tuple([2,3]).__contains__(t))||!1===z||0===z||""===z?0:"object"==typeof z?"function"==typeof z.__nonzero__?z.__nonzero__():"function"==typeof z.__len__?0<z.__len__():1:1)?(f=(null===(p=$p.isinstance("undefined"!=typeof(B=b).__array?"undefined"!=typeof B.__array[0]?B.__array[0]:B.__getitem__(0):B.__getitem__(0),$p.str))||!1===p||0===p||""===p?0:"object"==typeof p?"function"==typeof p.__nonzero__?p.__nonzero__():"function"==typeof p.__len__?0<p.__len__():1:1)?"undefined"!=
typeof(C=b).__array?"undefined"!=typeof C.__array[0]?C.__array[0]:C.__getitem__(0):C.__getitem__(0):("undefined"!=typeof(c=b).__array?"undefined"!=typeof c.__array[0]?c.__array[0]:c.__getitem__(0):c.__getitem__(0)).toDataURL(),c="undefined"!=typeof(w=b).__array?"undefined"!=typeof w.__array[1]?w.__array[1]:w.__getitem__(1):w.__getitem__(1),b=(null===(x=2===(m=t)&&null===m?!0:null===m?!1:"object"!=typeof m&&"function"!=typeof m||"function"!=typeof m.__cmp__?2==m:0===m.__cmp__(2))||!1===x||0===x||""===
x?0:"object"==typeof x?"function"==typeof x.__nonzero__?x.__nonzero__():"function"==typeof x.__len__?0<x.__len__():1:1)?"default":"undefined"!=typeof(s=b).__array?"undefined"!=typeof s.__array[2]?s.__array[2]:s.__getitem__(2):s.__getitem__(2),a.__is_instance__&&"function"==typeof a.__setattr__?a.__setattr__("_cursor",$p.sprintf('url("%s") %d %d, %s',$p.tuple([f,"undefined"!=typeof(n=c).__array?"undefined"!=typeof n.__array[l=0]?n.__array[l]:n.__getitem__(l):n.__getitem__(0),"undefined"!=typeof(e=
c).__array?"undefined"!=typeof e.__array[M=1]?e.__array[M]:e.__getitem__(M):e.__getitem__(1),b]))):$p.setattr(a,"_cursor",$p.sprintf('url("%s") %d %d, %s',$p.tuple([f,"undefined"!=typeof(n=c).__array?"undefined"!=typeof n.__array[l=0]?n.__array[l]:n.__getitem__(l):n.__getitem__(0),"undefined"!=typeof(e=c).__array?"undefined"!=typeof e.__array[M=1]?e.__array[M]:e.__getitem__(M):e.__getitem__(1),b])))):(null===(v=$p.tuple([4,5]).__contains__(t))||!1===v||0===v||""===v?0:"object"==typeof v?"function"==
typeof v.__nonzero__?v.__nonzero__():"function"==typeof v.__len__?0<v.__len__():1:1)?(e="undefined"!=typeof(N=b).__array?"undefined"!=typeof N.__array[0]?N.__array[0]:N.__getitem__(0):N.__getitem__(0),c="undefined"!=typeof(O=b).__array?"undefined"!=typeof O.__array[1]?O.__array[1]:O.__getitem__(1):O.__getitem__(1),l="undefined"!=typeof(P=b).__array?"undefined"!=typeof P.__array[2]?P.__array[2]:P.__getitem__(2):P.__getitem__(2),n="undefined"!=typeof(Q=b).__array?"undefined"!=typeof Q.__array[3]?Q.__array[3]:
Q.__getitem__(3):Q.__getitem__(3),b=(null===(A=4===(q=t)&&null===q?!0:null===q?!1:"object"!=typeof q&&"function"!=typeof q||"function"!=typeof q.__cmp__?4==q:0===q.__cmp__(4))||!1===A||0===A||""===A?0:"object"==typeof A?"function"==typeof A.__nonzero__?A.__nonzero__():"function"==typeof A.__len__?0<A.__len__():1:1)?"default":"undefined"!=typeof(f=b).__array?"undefined"!=typeof f.__array[4]?f.__array[4]:f.__getitem__(4):f.__getitem__(4),f=k.cursors.create_cursor(e,l,n),f=f.toDataURL(),a.__is_instance__&&
"function"==typeof a.__setattr__?a.__setattr__("_cursor",$p.sprintf('url("%s") %d %d, %s',$p.tuple([f,"undefined"!=typeof(E=c).__array?"undefined"!=typeof E.__array[g=0]?E.__array[g]:E.__getitem__(g):E.__getitem__(0),"undefined"!=typeof(F=c).__array?"undefined"!=typeof F.__array[u=1]?F.__array[u]:F.__getitem__(u):F.__getitem__(1),b]))):$p.setattr(a,"_cursor",$p.sprintf('url("%s") %d %d, %s',$p.tuple([f,"undefined"!=typeof(E=c).__array?"undefined"!=typeof E.__array[g=0]?E.__array[g]:E.__getitem__(g):
E.__getitem__(0),"undefined"!=typeof(F=c).__array?"undefined"!=typeof F.__array[u=1]?F.__array[u]:F.__getitem__(u):F.__getitem__(1),b])))):a.__is_instance__&&"function"==typeof a.__setattr__?a.__setattr__("_cursor","default"):$p.setattr(a,"_cursor","default");(null===(d=null==(L=(H=a)._cursorVisible)||H.__is_instance__&&"function"==typeof L||"function"==typeof L.__get__?$p.getattr(H,"_cursorVisible"):a._cursorVisible)||!1===d||0===d||""===d?0:"object"==typeof d?"function"==typeof d.__nonzero__?d.__nonzero__():
"function"==typeof d.__len__?0<d.__len__():1:1)&&k.DOM.setStyleAttribute(k.env.canvas.getElement(),"cursor",null==(G=(h=a)._cursor)||h.__is_instance__&&"function"==typeof G||"function"==typeof G.__get__?$p.getattr(h,"_cursor"):a._cursor);return null},1,["cursor",null,["self"]]);l.set_cursor=c;c=$pyjs__bind_method2("get_cursor",function(a){a=!0===this.__is_instance__?this:a;var b;return null==(b=a._cursor)||a.__is_instance__&&"function"==typeof b||"function"==typeof b.__get__?$p.getattr(a,"_cursor"):
a._cursor},1,[null,null,["self"]]);l.get_cursor=c;c=$pyjs__bind_method2("_nonimplemented_methods",function(a){a=!0===this.__is_instance__?this:a;var b;b=function(){$p.tuple($pyjs_array_slice.call(arguments,0,arguments.length));return null};b.__name__="$lambda1";b.__bind_type__=0;b.__args__=["arg",null];a.__is_instance__&&"function"==typeof a.__setattr__?a.__setattr__("set_pos",b):$p.setattr(a,"set_pos",b);b=function(){$p.tuple($pyjs_array_slice.call(arguments,0,arguments.length));return!0};b.__name__=
"$lambda2";b.__bind_type__=0;b.__args__=["arg",null];a.__is_instance__&&"function"==typeof a.__setattr__?a.__setattr__("get_focused",b):$p.setattr(a,"get_focused",b);return null},1,[null,null,["self"]]);l._nonimplemented_methods=c;c=Array($p.object);var w=$p.dict(),L;for(L in l)w.__setitem__(L,l[L]);return $p._create_class("Mouse",$p.tuple(c),w)}();return this};
