$pyjs.loaded_modules["pyjsdl.time"]=function(z){if($pyjs.loaded_modules["pyjsdl.time"].__was_initialized__)return $pyjs.loaded_modules["pyjsdl.time"];"undefined"!=typeof $pyjs.loaded_modules.pyjsdl&&$pyjs.loaded_modules.pyjsdl.__was_initialized__||$p.___import___("pyjsdl",null);var d=$pyjs.loaded_modules["pyjsdl.time"];d.__repr__=function(){return"<module: pyjsdl.time>"};d.__was_initialized__=!0;if(null===z||"undefined"==typeof z)z="pyjsdl.time";d.__name__=z;$pyjs.loaded_modules.pyjsdl.time=$pyjs.loaded_modules["pyjsdl.time"];
d.env=$p.___import___("pyjsdl.env","pyjsdl",null,!1);d.performanceNowInit=$p.___import___("pyjsdl.pyjsobj.performanceNowInit","pyjsdl",null,!1);d.__docformat__="restructuredtext";d.Clock=function(){var e={},c;e.__module__="pyjsdl.time";e._wnd=null;c=$pyjs__bind_method2("__init__",function(a){a=!0===this.__is_instance__?this:a;var b,h;a.__is_instance__&&"function"==typeof a.__setattr__?a.__setattr__("_time",a.time()):$p.setattr(a,"_time",a.time());a.__is_instance__&&"function"==typeof a.__setattr__?
a.__setattr__("_time_init",null==(b=(h=a)._time)||h.__is_instance__&&"function"==typeof b||"function"==typeof b.__get__?$p.getattr(h,"_time"):a._time):$p.setattr(a,"_time_init",null==(b=(h=a)._time)||h.__is_instance__&&"function"==typeof b||"function"==typeof b.__get__?$p.getattr(h,"_time"):a._time);a.__is_instance__&&"function"==typeof a.__setattr__?a.__setattr__("_time_diff",0):$p.setattr(a,"_time_diff",0);a.__is_instance__&&"function"==typeof a.__setattr__?a.__setattr__("_framerate",0):$p.setattr(a,
"_framerate",0);return null},1,[null,null,["self"]]);e.__init__=c;c=$pyjs__bind_method2("get_time",function(a){a=!0===this.__is_instance__?this:a;var b;return null==(b=a._time_diff)||a.__is_instance__&&"function"==typeof b||"function"==typeof b.__get__?$p.getattr(a,"_time_diff"):a._time_diff},1,[null,null,["self"]]);e.get_time=c;c=$pyjs__bind_method2("tick",function(a){if(!0===this.__is_instance__)var b=this;else b=arguments[0],a=arguments[1];"undefined"==typeof a&&(a=arguments.callee.__args__[3][1]);
var h,g,q,B,f,c,e,t,p,s,m,n,k,u,l,v,w,x,y;if(null===(s=(null===(m=B=!((f=null==(c=(t=b)._framerate)||t.__is_instance__&&"function"==typeof c||"function"==typeof c.__get__?$p.getattr(t,"_framerate"):b._framerate)===(q=a)&&null===f||(null===f?0:null===q?0:"object"!=typeof f&&"function"!=typeof f||"function"!=typeof f.__cmp__?"object"!=typeof q&&"function"!=typeof q||"function"!=typeof q.__cmp__?f==q:0===q.__cmp__(f):0===f.__cmp__(q))))||!1===m||0===m||""===m?0:"object"==typeof m?"function"==typeof m.__nonzero__?
m.__nonzero__():"function"==typeof m.__len__?0<m.__len__():1:1)?!(null===(p=null==(e=(g=d.env.canvas)._pause)||g.__is_instance__&&"function"==typeof e||"function"==typeof e.__get__?$p.getattr(g,"_pause"):d.env.canvas._pause)||!1===p||0===p||""===p?0:"object"==typeof p?"function"==typeof p.__nonzero__?p.__nonzero__():"function"==typeof p.__len__?0<p.__len__():1:1):B)||!1===s||0===s||""===s?0:"object"==typeof s?"function"==typeof s.__nonzero__?s.__nonzero__():"function"==typeof s.__len__?0<s.__len__():
1:1)b.__is_instance__&&"function"==typeof b.__setattr__?b.__setattr__("_framerate",a):$p.setattr(b,"_framerate",a),(null===(n=a)||!1===n||0===n||""===n?0:"object"==typeof n?"function"==typeof n.__nonzero__?n.__nonzero__():"function"==typeof n.__len__?0<n.__len__():1:1)?d.env.canvas.__is_instance__&&"function"==typeof d.env.canvas.__setattr__?d.env.canvas.__setattr__("_framerate",1E3/a):$p.setattr(d.env.canvas,"_framerate",1E3/a):d.env.canvas.__is_instance__&&"function"==typeof d.env.canvas.__setattr__?
d.env.canvas.__setattr__("_framerate",0):$p.setattr(d.env.canvas,"_framerate",0);b.__is_instance__&&"function"==typeof b.__setattr__?b.__setattr__("_time",b.time()):$p.setattr(b,"_time",b.time());b.__is_instance__&&"function"==typeof b.__setattr__?b.__setattr__("_time_diff",(null==(h=(w=b)._time)||w.__is_instance__&&"function"==typeof h||"function"==typeof h.__get__?$p.getattr(w,"_time"):b._time)-(null==(v=(y=b)._time_init)||y.__is_instance__&&"function"==typeof v||"function"==typeof v.__get__?$p.getattr(y,
"_time_init"):b._time_init)):$p.setattr(b,"_time_diff",(null==(h=(w=b)._time)||w.__is_instance__&&"function"==typeof h||"function"==typeof h.__get__?$p.getattr(w,"_time"):b._time)-(null==(v=(y=b)._time_init)||y.__is_instance__&&"function"==typeof v||"function"==typeof v.__get__?$p.getattr(y,"_time_init"):b._time_init));b.__is_instance__&&"function"==typeof b.__setattr__?b.__setattr__("_time_init",null==(x=(u=b)._time)||u.__is_instance__&&"function"==typeof x||"function"==typeof x.__get__?$p.getattr(u,
"_time"):b._time):$p.setattr(b,"_time_init",null==(x=(u=b)._time)||u.__is_instance__&&"function"==typeof x||"function"==typeof x.__get__?$p.getattr(u,"_time"):b._time);return null==(k=(l=b)._time_diff)||l.__is_instance__&&"function"==typeof k||"function"==typeof k.__get__?$p.getattr(l,"_time_diff"):b._time_diff},1,[null,null,["self"],["framerate",0]]);e.tick=c;c=$pyjs__bind_method2("tick_busy_loop",function(a){if(!0===this.__is_instance__)var b=this;else b=arguments[0],a=arguments[1];"undefined"==
typeof a&&(a=arguments.callee.__args__[3][1]);return b.tick(a)},1,[null,null,["self"],["framerate",0]]);e.tick_busy_loop=c;c=$pyjs__bind_method2("get_fps",function(a){var b,h,g,q,c,f;return(null===(c=!(null===(q=null==(f=(g=d.env.canvas)._pause)||g.__is_instance__&&"function"==typeof f||"function"==typeof f.__get__?$p.getattr(g,"_pause"):d.env.canvas._pause)||!1===q||0===q||""===q?0:"object"==typeof q?"function"==typeof q.__nonzero__?q.__nonzero__():"function"==typeof q.__len__?0<q.__len__():1:1))||
!1===c||0===c||""===c?0:"object"==typeof c?"function"==typeof c.__nonzero__?c.__nonzero__():"function"==typeof c.__len__?0<c.__len__():1:1)?1E3/(null==(h=(b=d.env.canvas)._frametime)||b.__is_instance__&&"function"==typeof h||"function"==typeof h.__get__?$p.getattr(b,"_frametime"):d.env.canvas._frametime):0},1,[null,null,["self"]]);e.get_fps=c;c=$pyjs__bind_method2("time",function(a){return(!0===this.__is_instance__?this:a)._wnd.performance.now()},1,[null,null,["self"]]);e.time=c;c=Array($p.object);
var l=$p.dict(),k;for(k in e)l.__setitem__(k,e[k]);return $p._create_class("Clock",$p.tuple(c),l)}();d.Time=function(){var e={},c;e.__module__="pyjsdl.time";e._wnd=null;c=$pyjs__bind_method2("__init__",function(a){var b=!0===this.__is_instance__?this:a,h,g;b.__is_instance__&&"function"==typeof b.__setattr__?b.__setattr__("Clock",d.Clock):$p.setattr(b,"Clock",d.Clock);d.Time.__is_instance__&&"function"==typeof d.Time.__setattr__?d.Time.__setattr__("_wnd",d.performanceNowInit()):$p.setattr(d.Time,"_wnd",
d.performanceNowInit());d.Clock.__is_instance__&&"function"==typeof d.Clock.__setattr__?d.Clock.__setattr__("_wnd",null==(h=(g=d.Time)._wnd)||g.__is_instance__&&"function"==typeof h||"function"==typeof h.__get__?$p.getattr(g,"_wnd"):d.Time._wnd):$p.setattr(d.Clock,"_wnd",null==(h=(g=d.Time)._wnd)||g.__is_instance__&&"function"==typeof h||"function"==typeof h.__get__?$p.getattr(g,"_wnd"):d.Time._wnd);b.__is_instance__&&"function"==typeof b.__setattr__?b.__setattr__("_time_init",b.time()):$p.setattr(b,
"_time_init",b.time());b.__is_instance__&&"function"==typeof b.__setattr__?b.__setattr__("_framerate",0):$p.setattr(b,"_framerate",0);b.__is_instance__&&"function"==typeof b.__setattr__?b.__setattr__("_timers",$p.dict([])):$p.setattr(b,"_timers",$p.dict([]));a=function(){return b.wait()};a.__name__="$lambda1";a.__bind_type__=0;a.__args__=[null,null];b.__is_instance__&&"function"==typeof b.__setattr__?b.__setattr__("run",a):$p.setattr(b,"run",a);return null},1,[null,null,["self"]]);e.__init__=c;c=
$pyjs__bind_method2("get_ticks",function(a){a=!0===this.__is_instance__?this:a;var b;return a.time()-(null==(b=a._time_init)||a.__is_instance__&&"function"==typeof b||"function"==typeof b.__get__?$p.getattr(a,"_time_init"):a._time_init)},1,[null,null,["self"]]);e.get_ticks=c;c=$pyjs__bind_method2("delay",function(a,b){if(!0===this.__is_instance__)var h=this;else h=a,a=b;var g,d,c,f;for(c=h.time();!0!==0&&!0!=="";)if(null===(f=1==((g=h.time()-c)===(d=a)?0:typeof g!=typeof d||"number"!=typeof g&&"string"!=
typeof g&&"boolean"!=typeof g?$p.cmp(g,d):g==d?0:g<d?-1:1))||!1===f||0===f||""===f?0:"object"==typeof f?"function"==typeof f.__nonzero__?f.__nonzero__():"function"==typeof f.__len__?0<f.__len__():1:1)return h.time()-c;return null},1,[null,null,["self"],["time"]]);e.delay=c;c=$pyjs__bind_method2("wait",function(a){if(!0===this.__is_instance__)var b=this;else b=arguments[0],a=arguments[1];"undefined"==typeof a&&(a=arguments.callee.__args__[3][1]);var h,g,c,e,f,r,k,t,p,s,m,n;if(null===(m=a)||!1===m||
0===m||""===m?0:"object"==typeof m?"function"==typeof m.__nonzero__?m.__nonzero__():"function"==typeof m.__len__?0<m.__len__():1:1){if(null===(g=!(null===(h=null==(k=(t=d.env.canvas)._pause)||t.__is_instance__&&"function"==typeof k||"function"==typeof k.__get__?$p.getattr(t,"_pause"):d.env.canvas._pause)||!1===h||0===h||""===h?0:"object"==typeof h?"function"==typeof h.__nonzero__?h.__nonzero__():"function"==typeof h.__len__?0<h.__len__():1:1))||!1===g||0===g||""===g?0:"object"==typeof g?"function"==
typeof g.__nonzero__?g.__nonzero__():"function"==typeof g.__len__?0<g.__len__():1:1)b.__is_instance__&&"function"==typeof b.__setattr__?b.__setattr__("_framerate",null==(c=(p=d.env.canvas)._framerate)||p.__is_instance__&&"function"==typeof c||"function"==typeof c.__get__?$p.getattr(p,"_framerate"):d.env.canvas._framerate):$p.setattr(b,"_framerate",null==(c=(p=d.env.canvas)._framerate)||p.__is_instance__&&"function"==typeof c||"function"==typeof c.__get__?$p.getattr(p,"_framerate"):d.env.canvas._framerate),
d.env.canvas.__is_instance__&&"function"==typeof d.env.canvas.__setattr__?d.env.canvas.__setattr__("_framerate",10*a):$p.setattr(d.env.canvas,"_framerate",10*a),d.env.canvas.__is_instance__&&"function"==typeof d.env.canvas.__setattr__?d.env.canvas.__setattr__("_pause",!0):$p.setattr(d.env.canvas,"_pause",!0),b.timeout(a,b)}else if(null===(n=null==(s=(r=d.env.canvas)._pause)||r.__is_instance__&&"function"==typeof s||"function"==typeof s.__get__?$p.getattr(r,"_pause"):d.env.canvas._pause)||!1===n||
0===n||""===n?0:"object"==typeof n?"function"==typeof n.__nonzero__?n.__nonzero__():"function"==typeof n.__len__?0<n.__len__():1:1)d.env.canvas.__is_instance__&&"function"==typeof d.env.canvas.__setattr__?d.env.canvas.__setattr__("_framerate",null==(f=(e=b)._framerate)||e.__is_instance__&&"function"==typeof f||"function"==typeof f.__get__?$p.getattr(e,"_framerate"):b._framerate):$p.setattr(d.env.canvas,"_framerate",null==(f=(e=b)._framerate)||e.__is_instance__&&"function"==typeof f||"function"==typeof f.__get__?
$p.getattr(e,"_framerate"):b._framerate),d.env.canvas.__is_instance__&&"function"==typeof d.env.canvas.__setattr__?d.env.canvas.__setattr__("_rendertime",b.time()):$p.setattr(d.env.canvas,"_rendertime",b.time()),d.env.canvas.__is_instance__&&"function"==typeof d.env.canvas.__setattr__?d.env.canvas.__setattr__("_pause",!1):$p.setattr(d.env.canvas,"_pause",!1);return a},1,[null,null,["self"],["time",0]]);e.wait=c;c=$pyjs__bind_method2("set_timer",function(a,b,h){if(!0===this.__is_instance__)var g=this;
else g=arguments[0],a=arguments[1],b=arguments[2],h=arguments[3];"undefined"==typeof h&&(h=arguments.callee.__args__[5][1]);var c,e,f,r,k,t,p,s,m,n,l,u,z,v,w,x,y,A;if(null===(c=$p.hasattr(a,"type"))||!1===c||0===c||""===c?0:"object"==typeof c?"function"==typeof c.__nonzero__?c.__nonzero__():"function"==typeof c.__len__?0<c.__len__():1:1)c=null==(n=(v=a).type)||v.__is_instance__&&"function"==typeof n||"function"==typeof n.__get__?$p.getattr(v,"type"):a.type,(null===(e=!(null==(z=(u=g)._timers)||u.__is_instance__&&
"function"==typeof z||"function"==typeof z.__get__?$p.getattr(u,"_timers"):g._timers).__contains__(c))||!1===e||0===e||""===e?0:"object"==typeof e?"function"==typeof e.__nonzero__?e.__nonzero__():"function"==typeof e.__len__?0<e.__len__():1:1)&&(null==(l=(x=g)._timers)||x.__is_instance__&&"function"==typeof l||"function"==typeof l.__get__?$p.getattr(x,"_timers"):g._timers).__setitem__(c,("undefined"==typeof _EventTimer?d._EventTimer:_EventTimer)(a));else if(c=a,null===(f=!(null==(w=(s=g)._timers)||
s.__is_instance__&&"function"==typeof w||"function"==typeof w.__get__?$p.getattr(s,"_timers"):g._timers).__contains__(c))||!1===f||0===f||""===f?0:"object"==typeof f?"function"==typeof f.__nonzero__?f.__nonzero__():"function"==typeof f.__len__?0<f.__len__():1:1)e=d.env.event.Event(c),(null==(m=(t=g)._timers)||t.__is_instance__&&"function"==typeof m||"function"==typeof m.__get__?$p.getattr(t,"_timers"):g._timers).__setitem__(c,("undefined"==typeof _EventTimer?d._EventTimer:_EventTimer)(e));t=!(null===
(r=h)||!1===r||0===r||""===r?0:"object"==typeof r?"function"==typeof r.__nonzero__?r.__nonzero__():"function"==typeof r.__len__?0<r.__len__():1:1);("undefined"!=typeof(A=null==(p=(k=g)._timers)||k.__is_instance__&&"function"==typeof p||"function"==typeof p.__get__?$p.getattr(k,"_timers"):g._timers).__array?"undefined"!=typeof A.__array[y=c]?A.__array[y]:A.__getitem__(y):A.__getitem__(c)).set_timer(b,t);return null},1,[null,null,["self"],["event"],["time"],["once",!1]]);e.set_timer=c;c=$pyjs__bind_method2("_stop_timers",
function(a){a=!0===this.__is_instance__?this:a;var b,c,d,e,k,f,r,l,t;d=a._timers;"undefined"!=typeof(f=d.__array)?c=0:(d=d.__iter__(),c="undefined"!=typeof(f=d.__array)?0:"function"==typeof d.$genfunc?1:-1);for(t=0;"undefined"!=typeof(b=c?0<c?d.next(!0,!1):$p.wrapped_next(d):f[t++]);)("undefined"!=typeof(l=null==(k=(e=a)._timers)||e.__is_instance__&&"function"==typeof k||"function"==typeof k.__get__?$p.getattr(e,"_timers"):a._timers).__array?"undefined"!=typeof l.__array[r=b]?l.__array[r]:l.__getitem__(r):
l.__getitem__(b)).set_timer(0,!1);return null},1,[null,null,["self"]]);e._stop_timers=c;c=$pyjs__bind_method2("time",function(a){return(!0===this.__is_instance__?this:a)._wnd.performance.now()},1,[null,null,["self"]]);e.time=c;c=$pyjs__bind_method2("timeout",function(a,b){!0!==this.__is_instance__&&(a=arguments[1],b=arguments[2]);"undefined"==typeof a&&(a=arguments.callee.__args__[3][1]);"undefined"==typeof b&&(b=arguments.callee.__args__[4][1]);var c;c=function(){return b.run()};c.__name__="$lambda2";
c.__bind_type__=0;c.__args__=[null,null];$wnd.setTimeout(c,a)},1,[null,null,["self"],["time",null],["obj",null]]);e.timeout=c;c=Array($p.object);var l=$p.dict(),k;for(k in e)l.__setitem__(k,e[k]);return $p._create_class("Time",$p.tuple(c),l)}();d._EventTimer=function(){var e={},c;e.__module__="pyjsdl.time";c=$pyjs__bind_method2("__init__",function(a,b){if(!0===this.__is_instance__)var c=this;else c=a,a=b;c.__is_instance__&&"function"==typeof c.__setattr__?c.__setattr__("event",a):$p.setattr(c,"event",
a);c.__is_instance__&&"function"==typeof c.__setattr__?c.__setattr__("timer",null):$p.setattr(c,"timer",null);c.__is_instance__&&"function"==typeof c.__setattr__?c.__setattr__("time",0):$p.setattr(c,"time",0);c.__is_instance__&&"function"==typeof c.__setattr__?c.__setattr__("repeat",!0):$p.setattr(c,"repeat",!0);return null},1,[null,null,["self"],["event"]]);e.__init__=c;c=$pyjs__bind_method2("set_timer",function(a,b,c){if(!0===this.__is_instance__)var d=this;else d=a,a=b,b=c;var e,k,f,l;if(null===
(k=null==(f=(l=d).timer)||l.__is_instance__&&"function"==typeof f||"function"==typeof f.__get__?$p.getattr(l,"timer"):d.timer)||!1===k||0===k||""===k?0:"object"==typeof k?"function"==typeof k.__nonzero__?k.__nonzero__():"function"==typeof k.__len__?0<k.__len__():1:1)d.__is_instance__&&"function"==typeof d.__setattr__?d.__setattr__("repeat",!1):$p.setattr(d,"repeat",!1),d.clear_timeout();if(null===(e=a)||!1===e||0===e||""===e?0:"object"==typeof e?"function"==typeof e.__nonzero__?e.__nonzero__():"function"==
typeof e.__len__?0<e.__len__():1:1)d.__is_instance__&&"function"==typeof d.__setattr__?d.__setattr__("time",a):$p.setattr(d,"time",a),d.__is_instance__&&"function"==typeof d.__setattr__?d.__setattr__("repeat",b):$p.setattr(d,"repeat",b),d.set_timeout();return null},1,[null,null,["self"],["time"],["repeat"]]);e.set_timer=c;c=$pyjs__bind_method2("set_timeout",function(a){var b=!0===this.__is_instance__?this:a;a=function(){return b.run()};a.__name__="$lambda3";a.__bind_type__=0;a.__args__=[null,null];
a=$wnd.setTimeout(a,b.time);b.__is_instance__&&"function"==typeof b.__setattr__?b.__setattr__("timer",a):$p.setattr(b,"timer",a);return null},1,[null,null,["self"]]);e.set_timeout=c;c=$pyjs__bind_method2("clear_timeout",function(a){a=!0===this.__is_instance__?this:a;$wnd.clearTimeout(a.timer);a.__is_instance__&&"function"==typeof a.__setattr__?a.__setattr__("timer",null):$p.setattr(a,"timer",null);return null},1,[null,null,["self"]]);e.clear_timeout=c;c=$pyjs__bind_method2("run",function(a){a=!0===
this.__is_instance__?this:a;var b,c,e;d.env.event.post(null==(e=a.event)||a.__is_instance__&&"function"==typeof e||"function"==typeof e.__get__?$p.getattr(a,"event"):a.event);(null===(b=null==(c=a.repeat)||a.__is_instance__&&"function"==typeof c||"function"==typeof c.__get__?$p.getattr(a,"repeat"):a.repeat)||!1===b||0===b||""===b?0:"object"==typeof b?"function"==typeof b.__nonzero__?b.__nonzero__():"function"==typeof b.__len__?0<b.__len__():1:1)&&a.set_timeout();return null},1,[null,null,["self"]]);
e.run=c;c=Array(pyjslib.object);var l=$p.dict(),k;for(k in e)l.__setitem__(k,e[k]);return $p._create_class("_EventTimer",$p.tuple(c),l)}();return this};
