$pyjs.loaded_modules["pyjsdl.surface"]=function(ha){if($pyjs.loaded_modules["pyjsdl.surface"].__was_initialized__)return $pyjs.loaded_modules["pyjsdl.surface"];"undefined"!=typeof $pyjs.loaded_modules.pyjsdl&&$pyjs.loaded_modules.pyjsdl.__was_initialized__||$p.___import___("pyjsdl",null);var k=$pyjs.loaded_modules["pyjsdl.surface"];k.__repr__=function(){return"<module: pyjsdl.surface>"};k.__was_initialized__=!0;if(null===ha||"undefined"==typeof ha)ha="pyjsdl.surface";k.__name__=ha;$pyjs.loaded_modules.pyjsdl.surface=
$pyjs.loaded_modules["pyjsdl.surface"];var aa,ba,na,oa,x;k.HTML5Canvas=$p.___import___("pyjsdl.pyjsobj.HTML5Canvas","pyjsdl",null,!1);k.Rect=$p.___import___("pyjsdl.rect.Rect","pyjsdl",null,!1);k.rectPool=$p.___import___("pyjsdl.rect.rectPool","pyjsdl",null,!1);k.Color=$p.___import___("pyjsdl.color.Color","pyjsdl",null,!1);k.sys=$p.___import___("sys","pyjsdl");if(null===(x=-1==((aa=null==(oa=(na=k.sys).version_info)||na.__is_instance__&&"function"==typeof oa||"function"==typeof oa.__get__?$p.getattr(na,
"version_info"):k.sys.version_info)===(ba=$p.tuple([3]))?0:typeof aa!=typeof ba||"number"!=typeof aa&&"string"!=typeof aa&&"boolean"!=typeof aa?$p.cmp(aa,ba):aa==ba?0:aa<ba?-1:1))||!1===x||0===x||""===x?0:"object"==typeof x?"function"==typeof x.__nonzero__?x.__nonzero__():"function"==typeof x.__len__?0<x.__len__():1:1)k.range=$p.xrange;k.__docformat__="restructuredtext";k.Surface=function(){var g={},e;g.__module__="pyjsdl.surface";e=$pyjs__bind_method2("__init__",function(a){if(!0===this.__is_instance__)var b=
this,c=$p.tuple($pyjs_array_slice.call(arguments,1,arguments.length-1)),d=2<=arguments.length?arguments[arguments.length-1]:arguments[arguments.length];else b=arguments[0],a=arguments[1],c=$p.tuple($pyjs_array_slice.call(arguments,2,arguments.length-1)),d=3<=arguments.length?arguments[arguments.length-1]:arguments[arguments.length];null===d||"object"!=typeof d||"dict"!=d.__name__||"undefined"==typeof d.$pyjs_is_kwarg?("undefined"!=typeof d&&c.__array.push(d),d=arguments[arguments.length+1]):delete d.$pyjs_is_kwarg;
"undefined"==typeof d&&($p.__empty_dict(),"undefined"!=typeof a?null!==a&&"undefined"!=typeof a.$pyjs_is_kwarg&&(a=arguments[2]):"undefined"!=typeof b&&null!==b&&"undefined"!=typeof b.$pyjs_is_kwarg&&(b=arguments[2]));var h,E,f,s,e,q,p,n,g,B,m,v;b.__is_instance__&&"function"==typeof b.__setattr__?b.__setattr__("width",$p.float_int("undefined"!=typeof(v=a).__array?"undefined"!=typeof v.__array[B=0]?v.__array[B]:v.__getitem__(B):v.__getitem__(0))):$p.setattr(b,"width",$p.float_int("undefined"!=typeof(v=
a).__array?"undefined"!=typeof v.__array[B=0]?v.__array[B]:v.__getitem__(B):v.__getitem__(0)));b.__is_instance__&&"function"==typeof b.__setattr__?b.__setattr__("height",$p.float_int("undefined"!=typeof(m=a).__array?"undefined"!=typeof m.__array[g=1]?m.__array[g]:m.__getitem__(g):m.__getitem__(1))):$p.setattr(b,"height",$p.float_int("undefined"!=typeof(m=a).__array?"undefined"!=typeof m.__array[g=1]?m.__array[g]:m.__getitem__(g):m.__getitem__(1)));k.HTML5Canvas.__init__(b,null==(f=(e=b).width)||e.__is_instance__&&
"function"==typeof f||"function"==typeof f.__get__?$p.getattr(e,"width"):b.width,null==(s=(p=b).height)||p.__is_instance__&&"function"==typeof s||"function"==typeof s.__get__?$p.getattr(p,"height"):b.height);k.HTML5Canvas.resize(b,null==(q=(E=b).width)||E.__is_instance__&&"function"==typeof q||"function"==typeof q.__get__?$p.getattr(E,"width"):b.width,null==(h=(n=b).height)||n.__is_instance__&&"function"==typeof h||"function"==typeof h.__get__?$p.getattr(n,"height"):b.height);b.__is_instance__&&"function"==
typeof b.__setattr__?b.__setattr__("_display",null):$p.setattr(b,"_display",null);b.__is_instance__&&"function"==typeof b.__setattr__?b.__setattr__("_super_surface",null):$p.setattr(b,"_super_surface",null);b.__is_instance__&&"function"==typeof b.__setattr__?b.__setattr__("_offset",$p.tuple([0,0])):$p.setattr(b,"_offset",$p.tuple([0,0]));b.__is_instance__&&"function"==typeof b.__setattr__?b.__setattr__("_colorkey",null):$p.setattr(b,"_colorkey",null);b.__is_instance__&&"function"==typeof b.__setattr__?
b.__setattr__("_stroke_style",null):$p.setattr(b,"_stroke_style",null);b.__is_instance__&&"function"==typeof b.__setattr__?b.__setattr__("_fill_style",null):$p.setattr(b,"_fill_style",null);b._nonimplemented_methods();return null},1,["args",["kwargs"],["self"],["size"]]);g.__init__=e;e=$pyjs__bind_method2("__str__",function(a){a=!0===this.__is_instance__?this:a;var b,c,d;return $p.sprintf("%s(%d,%d)",$p.tuple([null==(c=a.__class__)||a.__is_instance__&&"function"==typeof c||"function"==typeof c.__get__?
$p.getattr(a,"__class__"):a.__class__,null==(d=a.width)||a.__is_instance__&&"function"==typeof d||"function"==typeof d.__get__?$p.getattr(a,"width"):a.width,null==(b=a.height)||a.__is_instance__&&"function"==typeof b||"function"==typeof b.__get__?$p.getattr(a,"height"):a.height]))},1,[null,null,["self"]]);g.__str__=e;e=$pyjs__bind_method2("__repr__",function(a){a=!0===this.__is_instance__?this:a;var b,c,d;return $p.sprintf("%s(%d,%d)",$p.tuple([null==(d=a.__class__)||a.__is_instance__&&"function"==
typeof d||"function"==typeof d.__get__?$p.getattr(a,"__class__"):a.__class__,null==(c=a.width)||a.__is_instance__&&"function"==typeof c||"function"==typeof c.__get__?$p.getattr(a,"width"):a.width,null==(b=a.height)||a.__is_instance__&&"function"==typeof b||"function"==typeof b.__get__?$p.getattr(a,"height"):a.height]))},1,[null,null,["self"]]);g.__repr__=e;e=$pyjs__bind_method2("get_size",function(a){a=!0===this.__is_instance__?this:a;var b,c;return $p.tuple([null==(b=a.width)||a.__is_instance__&&
"function"==typeof b||"function"==typeof b.__get__?$p.getattr(a,"width"):a.width,null==(c=a.height)||a.__is_instance__&&"function"==typeof c||"function"==typeof c.__get__?$p.getattr(a,"height"):a.height])},1,[null,null,["self"]]);g.get_size=e;e=$pyjs__bind_method2("get_width",function(a){a=!0===this.__is_instance__?this:a;var b;return null==(b=a.width)||a.__is_instance__&&"function"==typeof b||"function"==typeof b.__get__?$p.getattr(a,"width"):a.width},1,[null,null,["self"]]);g.get_width=e;e=$pyjs__bind_method2("get_height",
function(a){a=!0===this.__is_instance__?this:a;var b;return null==(b=a.height)||a.__is_instance__&&"function"==typeof b||"function"==typeof b.__get__?$p.getattr(a,"height"):a.height},1,[null,null,["self"]]);g.get_height=e;e=$pyjs__bind_method2("resize",function(a,b,c){if(!0===this.__is_instance__)var d=this;else d=a,a=b,b=c;var h,E,f,s;d.__is_instance__&&"function"==typeof d.__setattr__?d.__setattr__("width",$p.float_int(a)):$p.setattr(d,"width",$p.float_int(a));d.__is_instance__&&"function"==typeof d.__setattr__?
d.__setattr__("height",$p.float_int(b)):$p.setattr(d,"height",$p.float_int(b));k.HTML5Canvas.resize(d,null==(f=(h=d).width)||h.__is_instance__&&"function"==typeof f||"function"==typeof f.__get__?$p.getattr(h,"width"):d.width,null==(E=(s=d).height)||s.__is_instance__&&"function"==typeof E||"function"==typeof E.__get__?$p.getattr(s,"height"):d.height);return null},1,[null,null,["self"],["width"],["height"]]);g.resize=e;e=$pyjs__bind_method2("get_rect",function(){if(!0===this.__is_instance__)var a=this,
b=1<=arguments.length?arguments[arguments.length-1]:arguments[arguments.length];else a=arguments[0],b=2<=arguments.length?arguments[arguments.length-1]:arguments[arguments.length];null===b||"object"!=typeof b||"dict"!=b.__name__||"undefined"==typeof b.$pyjs_is_kwarg?b=arguments[arguments.length+1]:delete b.$pyjs_is_kwarg;"undefined"==typeof b&&(b=$p.__empty_dict(),"undefined"!=typeof a&&null!==a&&"undefined"!=typeof a.$pyjs_is_kwarg&&(b=a,a=arguments[1]));var c,d,h,E,f,s,e,a=k.Rect(0,0,null==(f=(E=
a).width)||E.__is_instance__&&"function"==typeof f||"function"==typeof f.__get__?$p.getattr(E,"width"):a.width,null==(d=(e=a).height)||e.__is_instance__&&"function"==typeof d||"function"==typeof d.__get__?$p.getattr(e,"height"):a.height);f=b;"undefined"!=typeof(d=f.__array)?e=0:(f=f.__iter__(),e="undefined"!=typeof(d=f.__array)?0:"function"==typeof f.$genfunc?1:-1);for(E=0;"undefined"!=typeof(c=e?0<e?f.next(!0,!1):$p.wrapped_next(f):d[E++]);)$p.setattr(a,c,"undefined"!=typeof(h=b).__array?"undefined"!=
typeof h.__array[s=c]?h.__array[s]:h.__getitem__(s):h.__getitem__(c));return a},1,[null,["attr"],["self"]]);g.get_rect=e;e=$pyjs__bind_method2("copy",function(a){a=!0===this.__is_instance__?this:a;var b,c,d,h;b=k.Surface($p.tuple([null==(h=a.width)||a.__is_instance__&&"function"==typeof h||"function"==typeof h.__get__?$p.getattr(a,"width"):a.width,null==(d=a.height)||a.__is_instance__&&"function"==typeof d||"function"==typeof d.__get__?$p.getattr(a,"height"):a.height]));b.drawImage(null==(c=a.canvas)||
a.__is_instance__&&"function"==typeof c||"function"==typeof c.__get__?$p.getattr(a,"canvas"):a.canvas,0,0);return b},1,[null,null,["self"]]);g.copy=e;e=$pyjs__bind_method2("subsurface",function(a,b){if(!0===this.__is_instance__)var c=this;else c=a,a=b;var d,h,E,f,e,A,q,p,n,g,B,m,v,l,J,y,H,w,N,t,I,r,C,D,F,K,$,G,U,u,z,L,S,O,P,T,V,W,R,Q,M,X,Y,x;if(null===(C=$p.tuple(["t","f"]).__contains__(a))||!1===C||0===C||""===C?0:"object"==typeof C?"function"==typeof C.__nonzero__?C.__nonzero__():"function"==typeof C.__len__?
0<C.__len__():1:1){if(null===(d=!(null===(D=null==(q=(e=c)._super_surface)||e.__is_instance__&&"function"==typeof q||"function"==typeof q.__get__?$p.getattr(e,"_super_surface"):c._super_surface)||!1===D||0===D||""===D?0:"object"==typeof D?"function"==typeof D.__nonzero__?D.__nonzero__():"function"==typeof D.__len__?0<D.__len__():1:1))||!1===d||0===d||""===d?0:"object"==typeof d?"function"==typeof d.__nonzero__?d.__nonzero__():"function"==typeof d.__len__?0<d.__len__():1:1)return null;(null===(E="t"===
(r=a)&&null===r?!0:null===r?!1:"object"!=typeof r&&"function"!=typeof r||"function"!=typeof r.__cmp__?"t"==r:0===r.__cmp__("t"))||!1===E||0===E||""===E?0:"object"==typeof E?"function"==typeof E.__nonzero__?E.__nonzero__():"function"==typeof E.__len__?0<E.__len__():1:1)?c.drawImage(null==(A=(g=c._super_surface).canvas)||g.__is_instance__&&"function"==typeof A||"function"==typeof A.__get__?$p.getattr(g,"canvas"):c._super_surface.canvas,"undefined"!=typeof($=null==(B=(O=c)._offset)||O.__is_instance__&&
"function"==typeof B||"function"==typeof B.__get__?$p.getattr(O,"_offset"):c._offset).__array?"undefined"!=typeof $.__array[0]?$.__array[0]:$.__getitem__(0):$.__getitem__(0),"undefined"!=typeof(K=null==(S=(T=c)._offset)||T.__is_instance__&&"function"==typeof S||"function"==typeof S.__get__?$p.getattr(T,"_offset"):c._offset).__array?"undefined"!=typeof K.__array[1]?K.__array[1]:K.__getitem__(1):K.__getitem__(1),null==(P=(W=c).width)||W.__is_instance__&&"function"==typeof P||"function"==typeof P.__get__?
$p.getattr(W,"width"):c.width,null==(V=(Q=c).height)||Q.__is_instance__&&"function"==typeof V||"function"==typeof V.__get__?$p.getattr(Q,"height"):c.height,0,0,null==(R=(u=c).width)||u.__is_instance__&&"function"==typeof R||"function"==typeof R.__get__?$p.getattr(u,"width"):c.width,null==(U=(H=c).height)||H.__is_instance__&&"function"==typeof U||"function"==typeof U.__get__?$p.getattr(H,"height"):c.height):c._super_surface.drawImage(null==(w=(N=c).canvas)||N.__is_instance__&&"function"==typeof w||
"function"==typeof w.__get__?$p.getattr(N,"canvas"):c.canvas,"undefined"!=typeof(z=null==(t=(l=c)._offset)||l.__is_instance__&&"function"==typeof t||"function"==typeof t.__get__?$p.getattr(l,"_offset"):c._offset).__array?"undefined"!=typeof z.__array[0]?z.__array[0]:z.__getitem__(0):z.__getitem__(0),"undefined"!=typeof(L=null==(J=(x=c)._offset)||x.__is_instance__&&"function"==typeof J||"function"==typeof J.__get__?$p.getattr(x,"_offset"):c._offset).__array?"undefined"!=typeof L.__array[1]?L.__array[1]:
L.__getitem__(1):L.__getitem__(1));return null}d=(null===(f=$p.hasattr(a,"width"))||!1===f||0===f||""===f?0:"object"==typeof f?"function"==typeof f.__nonzero__?f.__nonzero__():"function"==typeof f.__len__?0<f.__len__():1:1)?a:k.Rect(a);if(null===(G=!(null===(F=c.get_rect().contains(d))||!1===F||0===F||""===F?0:"object"==typeof F?"function"==typeof F.__nonzero__?F.__nonzero__():"function"==typeof F.__len__?0<F.__len__():1:1))||!1===G||0===G||""===G?0:"object"==typeof G?"function"==typeof G.__nonzero__?
G.__nonzero__():"function"==typeof G.__len__?0<G.__len__():1:1)throw $p.ValueError("subsurface outside surface area");f=c.getSubimage(null==(y=d.x)||d.__is_instance__&&"function"==typeof y||"function"==typeof y.__get__?$p.getattr(d,"x"):d.x,null==(v=d.y)||d.__is_instance__&&"function"==typeof v||"function"==typeof v.__get__?$p.getattr(d,"y"):d.y,null==(p=d.width)||d.__is_instance__&&"function"==typeof p||"function"==typeof p.__get__?$p.getattr(d,"width"):d.width,null==(h=d.height)||d.__is_instance__&&
"function"==typeof h||"function"==typeof h.__get__?$p.getattr(d,"height"):d.height);f.__is_instance__&&"function"==typeof f.__setattr__?f.__setattr__("_super_surface",c):$p.setattr(f,"_super_surface",c);f.__is_instance__&&"function"==typeof f.__setattr__?f.__setattr__("_offset",$p.tuple([null==(X=(Y=d).x)||Y.__is_instance__&&"function"==typeof X||"function"==typeof X.__get__?$p.getattr(Y,"x"):d.x,null==(M=(I=d).y)||I.__is_instance__&&"function"==typeof M||"function"==typeof M.__get__?$p.getattr(I,
"y"):d.y])):$p.setattr(f,"_offset",$p.tuple([null==(X=(Y=d).x)||Y.__is_instance__&&"function"==typeof X||"function"==typeof X.__get__?$p.getattr(Y,"x"):d.x,null==(M=(I=d).y)||I.__is_instance__&&"function"==typeof M||"function"==typeof M.__get__?$p.getattr(I,"y"):d.y]));f.__is_instance__&&"function"==typeof f.__setattr__?f.__setattr__("_colorkey",null==(n=(m=c)._colorkey)||m.__is_instance__&&"function"==typeof n||"function"==typeof n.__get__?$p.getattr(m,"_colorkey"):c._colorkey):$p.setattr(f,"_colorkey",
null==(n=(m=c)._colorkey)||m.__is_instance__&&"function"==typeof n||"function"==typeof n.__get__?$p.getattr(m,"_colorkey"):c._colorkey);return f},1,[null,null,["self"],["rect"]]);g.subsurface=e;e=$pyjs__bind_method2("getSubimage",function(a,b,c,d,h){if(!0===this.__is_instance__)var E=this;else E=a,a=b,b=c,c=d,d=h;var f,e;h=k.Surface($p.tuple([c,d]));h.drawImage(null==(e=(f=E).canvas)||f.__is_instance__&&"function"==typeof e||"function"==typeof e.__get__?$p.getattr(f,"canvas"):E.canvas,a,b,c,d,0,0,
c,d);return h},1,[null,null,["self"],["x"],["y"],["width"],["height"]]);g.getSubimage=e;e=$pyjs__bind_method2("blit",function(a,b,c){if(!0===this.__is_instance__)var d=this;else d=arguments[0],a=arguments[1],b=arguments[2],c=arguments[3];"undefined"==typeof c&&(c=arguments.callee.__args__[5][1]);var h,e,f,s,A,g,p,n,qa,B,m,v,l,J,y,H,w,N,t,I,r,C,D,F,K,$,G,U,u,z,L,S,O,P,T;(null===(h=!(null===(C=c)||!1===C||0===C||""===C?0:"object"==typeof C?"function"==typeof C.__nonzero__?C.__nonzero__():"function"==
typeof C.__len__?0<C.__len__():1:1))||!1===h||0===h||""===h?0:"object"==typeof h?"function"==typeof h.__nonzero__?h.__nonzero__():"function"==typeof h.__len__?0<h.__len__():1:1)?(h=k.rectPool.get("undefined"!=typeof(K=b).__array?"undefined"!=typeof K.__array[0]?K.__array[0]:K.__getitem__(0):K.__getitem__(0),"undefined"!=typeof($=b).__array?"undefined"!=typeof $.__array[1]?$.__array[1]:$.__getitem__(1):$.__getitem__(1),null==(A=(n=a).width)||n.__is_instance__&&"function"==typeof A||"function"==typeof A.__get__?
$p.getattr(n,"width"):a.width,null==(S=(g=a).height)||g.__is_instance__&&"function"==typeof S||"function"==typeof S.__get__?$p.getattr(g,"height"):a.height),d.impl.canvasContext.drawImage(null==(p=(T=a).canvas)||T.__is_instance__&&"function"==typeof p||"function"==typeof p.__get__?$p.getattr(T,"canvas"):a.canvas,null==(B=(U=h).x)||U.__is_instance__&&"function"==typeof B||"function"==typeof B.__get__?$p.getattr(U,"x"):h.x,null==(G=(z=h).y)||z.__is_instance__&&"function"==typeof G||"function"==typeof G.__get__?
$p.getattr(z,"y"):h.y)):(h=k.rectPool.get("undefined"!=typeof(O=b).__array?"undefined"!=typeof O.__array[0]?O.__array[0]:O.__getitem__(0):O.__getitem__(0),"undefined"!=typeof(qa=b).__array?"undefined"!=typeof qa.__array[1]?qa.__array[1]:qa.__getitem__(1):qa.__getitem__(1),"undefined"!=typeof(D=c).__array?"undefined"!=typeof D.__array[2]?D.__array[2]:D.__getitem__(2):D.__getitem__(2),"undefined"!=typeof(m=c).__array?"undefined"!=typeof m.__array[3]?m.__array[3]:m.__getitem__(3):m.__getitem__(3)),d.impl.canvasContext.drawImage(null==
(u=(N=a).canvas)||N.__is_instance__&&"function"==typeof u||"function"==typeof u.__get__?$p.getattr(N,"canvas"):a.canvas,"undefined"!=typeof(v=c).__array?"undefined"!=typeof v.__array[0]?v.__array[0]:v.__getitem__(0):v.__getitem__(0),"undefined"!=typeof(s=c).__array?"undefined"!=typeof s.__array[1]?s.__array[1]:s.__getitem__(1):s.__getitem__(1),"undefined"!=typeof(P=c).__array?"undefined"!=typeof P.__array[2]?P.__array[2]:P.__getitem__(2):P.__getitem__(2),"undefined"!=typeof(e=c).__array?"undefined"!=
typeof e.__array[3]?e.__array[3]:e.__getitem__(3):e.__getitem__(3),null==(F=(r=h).x)||r.__is_instance__&&"function"==typeof F||"function"==typeof F.__get__?$p.getattr(r,"x"):h.x,null==(I=(H=h).y)||H.__is_instance__&&"function"==typeof I||"function"==typeof I.__get__?$p.getattr(H,"y"):h.y,"undefined"!=typeof(f=c).__array?"undefined"!=typeof f.__array[2]?f.__array[2]:f.__getitem__(2):f.__getitem__(2),"undefined"!=typeof(L=c).__array?"undefined"!=typeof L.__array[3]?L.__array[3]:L.__getitem__(3):L.__getitem__(3)));
d=((null===(y=null==(w=(J=d)._display)||J.__is_instance__&&"function"==typeof w||"function"==typeof w.__get__?$p.getattr(J,"_display"):d._display)||!1===y||0===y||""===y?0:"object"==typeof y?"function"==typeof y.__nonzero__?y.__nonzero__():"function"==typeof y.__len__?0<y.__len__():1:1)?null==(t=(l=d._display)._surface_rect)||l.__is_instance__&&"function"==typeof t||"function"==typeof t.__get__?$p.getattr(l,"_surface_rect"):d._display._surface_rect:d.get_rect()).clip(h);k.rectPool.append(h);return d},
1,[null,null,["self"],["surface"],["position"],["area",null]]);g.blit=e;e=$pyjs__bind_method2("_blits",function(a,b){if(!0===this.__is_instance__)var c=this;else c=a,a=b;var d,h,e,f,s,g,q,p,n,k,B,m,c=null==(f=(e=c.impl).canvasContext)||e.__is_instance__&&"function"==typeof f||"function"==typeof f.__get__?$p.getattr(e,"canvasContext"):c.impl.canvasContext;f=a;"undefined"!=typeof(B=f.__array)?e=0:(f=f.__iter__(),e="undefined"!=typeof(B=f.__array)?0:"function"==typeof f.$genfunc?1:-1);for(g=0;"undefined"!=
typeof(h=e?0<e?f.next(!0,!1):$p.wrapped_next(f):B[g++]);)q=$p.__ass_unpack(h,2,null),h=q[0],q=q[1],c.drawImage(null==(n=(d=h).canvas)||d.__is_instance__&&"function"==typeof n||"function"==typeof n.__get__?$p.getattr(d,"canvas"):h.canvas,null==(p=(k=q).x)||k.__is_instance__&&"function"==typeof p||"function"==typeof p.__get__?$p.getattr(k,"x"):q.x,null==(m=(s=q).y)||s.__is_instance__&&"function"==typeof m||"function"==typeof m.__get__?$p.getattr(s,"y"):q.y);return null},1,[null,null,["self"],["surfaces"]]);
g._blits=e;e=$pyjs__bind_method2("_blit_clear",function(a,b,c){if(!0===this.__is_instance__)var d=this;else d=a,a=b,b=c;var h,e,f,s,g,q,p,n,k,B,m,v,l,J,y,H,w,N,t,I,r;c=null==(e=(n=d.impl).canvasContext)||n.__is_instance__&&"function"==typeof e||"function"==typeof e.__get__?$p.getattr(n,"canvasContext"):d.impl.canvasContext;n=b;"undefined"!=typeof(d=n.__array)?b=0:(n=n.__iter__(),b="undefined"!=typeof(d=n.__array)?0:"function"==typeof n.$genfunc?1:-1);for(e=0;"undefined"!=typeof(r=b?0<b?n.next(!0,
!1):$p.wrapped_next(n):d[e++]);)c.drawImage(null==(H=(N=a).canvas)||N.__is_instance__&&"function"==typeof H||"function"==typeof H.__get__?$p.getattr(N,"canvas"):a.canvas,null==(w=(I=r).x)||I.__is_instance__&&"function"==typeof w||"function"==typeof w.__get__?$p.getattr(I,"x"):r.x,null==(t=(y=r).y)||y.__is_instance__&&"function"==typeof t||"function"==typeof t.__get__?$p.getattr(y,"y"):r.y,null==(J=(f=r).width)||f.__is_instance__&&"function"==typeof J||"function"==typeof J.__get__?$p.getattr(f,"width"):
r.width,null==(s=(g=r).height)||g.__is_instance__&&"function"==typeof s||"function"==typeof s.__get__?$p.getattr(g,"height"):r.height,null==(q=(p=r).x)||p.__is_instance__&&"function"==typeof q||"function"==typeof q.__get__?$p.getattr(p,"x"):r.x,null==(l=(k=r).y)||k.__is_instance__&&"function"==typeof l||"function"==typeof l.__get__?$p.getattr(k,"y"):r.y,null==(B=(m=r).width)||m.__is_instance__&&"function"==typeof B||"function"==typeof B.__get__?$p.getattr(m,"width"):r.width,null==(v=(h=r).height)||
h.__is_instance__&&"function"==typeof v||"function"==typeof v.__get__?$p.getattr(h,"height"):r.height);return null},1,[null,null,["self"],["surface"],["rect_list"]]);g._blit_clear=e;e=$pyjs__bind_method2("set_colorkey",function(a,b){if(!0===this.__is_instance__)var c=this;else c=arguments[0],a=arguments[1],b=arguments[2];"undefined"==typeof b&&(b=arguments.callee.__args__[4][1]);var d,h,e,f,s,g,q,p;if(null===(p=null==(f=(e=c)._colorkey)||e.__is_instance__&&"function"==typeof f||"function"==typeof f.__get__?
$p.getattr(e,"_colorkey"):c._colorkey)||!1===p||0===p||""===p?0:"object"==typeof p?"function"==typeof p.__nonzero__?p.__nonzero__():"function"==typeof p.__len__?0<p.__len__():1:1)c.replace_color($p.tuple([0,0,0,0]),null==(h=(q=c)._colorkey)||q.__is_instance__&&"function"==typeof h||"function"==typeof h.__get__?$p.getattr(q,"_colorkey"):c._colorkey),c.__is_instance__&&"function"==typeof c.__setattr__?c.__setattr__("_colorkey",null):$p.setattr(c,"_colorkey",null);if(null===(d=a)||!1===d||0===d||""===
d?0:"object"==typeof d?"function"==typeof d.__nonzero__?d.__nonzero__():"function"==typeof d.__len__?0<d.__len__():1:1)c.__is_instance__&&"function"==typeof c.__setattr__?c.__setattr__("_colorkey",k.Color(a)):$p.setattr(c,"_colorkey",k.Color(a)),c.replace_color(null==(g=(s=c)._colorkey)||s.__is_instance__&&"function"==typeof g||"function"==typeof g.__get__?$p.getattr(s,"_colorkey"):c._colorkey);return null},1,[null,null,["self"],["color"],["flags",null]]);g.set_colorkey=e;e=$pyjs__bind_method2("get_colorkey",
function(a){a=!0===this.__is_instance__?this:a;var b,c,d,h,e,f,g,k,q,p;return(null===(k=null==(q=a._colorkey)||a.__is_instance__&&"function"==typeof q||"function"==typeof q.__get__?$p.getattr(a,"_colorkey"):a._colorkey)||!1===k||0===k||""===k?0:"object"==typeof k?"function"==typeof k.__nonzero__?k.__nonzero__():"function"==typeof k.__len__?0<k.__len__():1:1)?$p.tuple([null==(p=(d=a._colorkey).r)||d.__is_instance__&&"function"==typeof p||"function"==typeof p.__get__?$p.getattr(d,"r"):a._colorkey.r,
null==(h=(b=a._colorkey).g)||b.__is_instance__&&"function"==typeof h||"function"==typeof h.__get__?$p.getattr(b,"g"):a._colorkey.g,null==(c=(f=a._colorkey).b)||f.__is_instance__&&"function"==typeof c||"function"==typeof c.__get__?$p.getattr(f,"b"):a._colorkey.b,null==(g=(e=a._colorkey).a)||e.__is_instance__&&"function"==typeof g||"function"==typeof g.__get__?$p.getattr(e,"a"):a._colorkey.a]):null},1,[null,null,["self"]]);g.get_colorkey=e;e=$pyjs__bind_method2("_getPixel",function(a,b,c){!0!==this.__is_instance__&&
(a=b,b=c);return a.data[b]},1,[null,null,["self"],["imagedata"],["index"]]);g._getPixel=e;e=$pyjs__bind_method2("_setPixel",function(a,b,c,d){!0!==this.__is_instance__&&(a=b,b=c,c=d);c=$p.str(c);a.data[b]=c;return null},1,[null,null,["self"],["imagedata"],["index"],["dat"]]);g._setPixel=e;e=$pyjs__bind_method2("replace_color",function(a,b){if(!0===this.__is_instance__)var c=this;else c=arguments[0],a=arguments[1],b=arguments[2];"undefined"==typeof b&&(b=arguments.callee.__args__[4][1]);var d,h,e,
f,g,A,q,p,n,x,B,m,v,l,J,y,H,w,N,t,I,r,C,D,F,K,$,G,U,u,z,L,S,O,P,T,V,W,R,Q,M,X,Y,Z,ca,aa,ba,pa,ua,ha,na,oa,ra,ia,ja,sa,ka,da,ea,la,fa,ma,ga,ta;u=c.impl.getImageData(0,0,null==(l=(aa=c).width)||aa.__is_instance__&&"function"==typeof l||"function"==typeof l.__get__?$p.getattr(aa,"width"):c.width,null==(ba=(na=c).height)||na.__is_instance__&&"function"==typeof ba||"function"==typeof ba.__get__?$p.getattr(na,"height"):c.height);l=(null===(f=$p.hasattr(a,"a"))||!1===f||0===f||""===f?0:"object"==typeof f?
"function"==typeof f.__nonzero__?f.__nonzero__():"function"==typeof f.__len__?0<f.__len__():1:1)?a:k.Color(a);(null===(g=null===b)||!1===g||0===g||""===g?0:"object"==typeof g?"function"==typeof g.__nonzero__?g.__nonzero__():"function"==typeof g.__len__?0<g.__len__():1:1)?f=!0:(J=(null===(A=$p.hasattr(b,"a"))||!1===A||0===A||""===A?0:"object"==typeof A?"function"==typeof A.__nonzero__?A.__nonzero__():"function"==typeof A.__len__?0<A.__len__():1:1)?b:k.Color(b),f=!1);if(null===(d=f)||!1===d||0===d||
""===d?0:"object"==typeof d?"function"==typeof d.__nonzero__?d.__nonzero__():"function"==typeof d.__len__?0<d.__len__():1:1)for(m=$p.__ass_unpack($p.tuple([null==(ha=l.r)||l.__is_instance__&&"function"==typeof ha||"function"==typeof ha.__get__?$p.getattr(l,"r"):l.r,null==(oa=l.g)||l.__is_instance__&&"function"==typeof oa||"function"==typeof oa.__get__?$p.getattr(l,"g"):l.g,null==(pa=l.b)||l.__is_instance__&&"function"==typeof pa||"function"==typeof pa.__get__?$p.getattr(l,"b"):l.b,null==(ua=l.a)||
l.__is_instance__&&"function"==typeof ua||"function"==typeof ua.__get__?$p.getattr(l,"a"):l.a]),4,null),C=m[0],n=m[1],N=m[2],pa=m[3],I=0,m=k.range(0,null===(ja=null==(ra=u.data)||u.__is_instance__&&"function"==typeof ra||"function"==typeof ra.__get__?$p.getattr(u,"data"):u.data)?0:"undefined"!=typeof ja.__array?ja.__array.length:"function"==typeof ja.__len__?ja.__len__():"undefined"!=typeof ja.length?ja.length:$p.len(ja),4),"undefined"!=typeof(v=m.__array)?q=0:(m=m.__iter__(),q="undefined"!=typeof(v=
m.__array)?0:"function"==typeof m.$genfunc?1:-1),r=0;"undefined"!=typeof(y=q?0<q?m.next(!0,!1):$p.wrapped_next(m):v[r++]);)z=y,(null===(t=(null===(h=p=(ea=c._getPixel(u,z))===(ma=C)&&null===ea?!0:null===ea?!1:null===ma?!1:"object"!=typeof ea&&"function"!=typeof ea||"function"!=typeof ea.__cmp__?"object"!=typeof ma&&"function"!=typeof ma||"function"!=typeof ma.__cmp__?ea==ma:0===ma.__cmp__(ea):0===ea.__cmp__(ma))||!1===h||0===h||""===h?0:"object"==typeof h?"function"==typeof h.__nonzero__?h.__nonzero__():
"function"==typeof h.__len__?0<h.__len__():1:1)?(null===(w=x=(ga=c._getPixel(u,z+1))===(la=n)&&null===ga?!0:null===ga?!1:null===la?!1:"object"!=typeof ga&&"function"!=typeof ga||"function"!=typeof ga.__cmp__?"object"!=typeof la&&"function"!=typeof la||"function"!=typeof la.__cmp__?ga==la:0===la.__cmp__(ga):0===ga.__cmp__(la))||!1===w||0===w||""===w?0:"object"==typeof w?"function"==typeof w.__nonzero__?w.__nonzero__():"function"==typeof w.__len__?0<w.__len__():1:1)?(null===(e=B=(fa=c._getPixel(u,z+
2))===(ka=N)&&null===fa?!0:null===fa?!1:null===ka?!1:"object"!=typeof fa&&"function"!=typeof fa||"function"!=typeof fa.__cmp__?"object"!=typeof ka&&"function"!=typeof ka||"function"!=typeof ka.__cmp__?fa==ka:0===ka.__cmp__(fa):0===fa.__cmp__(ka))||!1===e||0===e||""===e?0:"object"==typeof e?"function"==typeof e.__nonzero__?e.__nonzero__():"function"==typeof e.__len__?0<e.__len__():1:1)?(da=c._getPixel(u,z+3))===(H=pa)&&null===da?!0:null===da?!1:null===H?!1:"object"!=typeof da&&"function"!=typeof da||
"function"!=typeof da.__cmp__?"object"!=typeof H&&"function"!=typeof H||"function"!=typeof H.__cmp__?da==H:0===H.__cmp__(da):0===da.__cmp__(H):B:x:p)||!1===t||0===t||""===t?0:"object"==typeof t?"function"==typeof t.__nonzero__?t.__nonzero__():"function"==typeof t.__len__?0<t.__len__():1:1)&&c._setPixel(u,z+3,I);else for(h=$p.__ass_unpack($p.tuple([null==(N=l.r)||l.__is_instance__&&"function"==typeof N||"function"==typeof N.__get__?$p.getattr(l,"r"):l.r,null==(C=l.g)||l.__is_instance__&&"function"==
typeof C||"function"==typeof C.__get__?$p.getattr(l,"g"):l.g,null==(ta=l.b)||l.__is_instance__&&"function"==typeof ta||"function"==typeof ta.__get__?$p.getattr(l,"b"):l.b,null==(n=l.a)||l.__is_instance__&&"function"==typeof n||"function"==typeof n.__get__?$p.getattr(l,"a"):l.a]),4,null),C=h[0],n=h[1],N=h[2],pa=h[3],h=$p.__ass_unpack($p.tuple([null==(I=(W=J).r)||W.__is_instance__&&"function"==typeof I||"function"==typeof I.__get__?$p.getattr(W,"r"):J.r,null==(V=(T=J).g)||T.__is_instance__&&"function"==
typeof V||"function"==typeof V.__get__?$p.getattr(T,"g"):J.g,null==(P=(O=J).b)||O.__is_instance__&&"function"==typeof P||"function"==typeof P.__get__?$p.getattr(O,"b"):J.b,null==(S=(L=J).a)||L.__is_instance__&&"function"==typeof S||"function"==typeof S.__get__?$p.getattr(L,"a"):J.a]),4,null),B=h[0],p=h[1],x=h[2],I=h[3],h=k.range(0,null===(ia=null==(z=u.data)||u.__is_instance__&&"function"==typeof z||"function"==typeof z.__get__?$p.getattr(u,"data"):u.data)?0:"undefined"!=typeof ia.__array?ia.__array.length:
"function"==typeof ia.__len__?ia.__len__():"undefined"!=typeof ia.length?ia.length:$p.len(ia),4),"undefined"!=typeof(w=h.__array)?t=0:(h=h.__iter__(),t="undefined"!=typeof(w=h.__array)?0:"function"==typeof h.$genfunc?1:-1),e=0;"undefined"!=typeof(H=t?0<t?h.next(!0,!1):$p.wrapped_next(h):w[e++]);)if(z=H,null===(F=(null===(K=m=(Q=c._getPixel(u,z))===(M=C)&&null===Q?!0:null===Q?!1:null===M?!1:"object"!=typeof Q&&"function"!=typeof Q||"function"!=typeof Q.__cmp__?"object"!=typeof M&&"function"!=typeof M||
"function"!=typeof M.__cmp__?Q==M:0===M.__cmp__(Q):0===Q.__cmp__(M))||!1===K||0===K||""===K?0:"object"==typeof K?"function"==typeof K.__nonzero__?K.__nonzero__():"function"==typeof K.__len__?0<K.__len__():1:1)?(null===(D=q=(X=c._getPixel(u,z+1))===(r=n)&&null===X?!0:null===X?!1:null===r?!1:"object"!=typeof X&&"function"!=typeof X||"function"!=typeof X.__cmp__?"object"!=typeof r&&"function"!=typeof r||"function"!=typeof r.__cmp__?X==r:0===r.__cmp__(X):0===X.__cmp__(r))||!1===D||0===D||""===D?0:"object"==
typeof D?"function"==typeof D.__nonzero__?D.__nonzero__():"function"==typeof D.__len__?0<D.__len__():1:1)?(null===(y=v=(Y=c._getPixel(u,z+2))===(Z=N)&&null===Y?!0:null===Y?!1:null===Z?!1:"object"!=typeof Y&&"function"!=typeof Y||"function"!=typeof Y.__cmp__?"object"!=typeof Z&&"function"!=typeof Z||"function"!=typeof Z.__cmp__?Y==Z:0===Z.__cmp__(Y):0===Y.__cmp__(Z))||!1===y||0===y||""===y?0:"object"==typeof y?"function"==typeof y.__nonzero__?y.__nonzero__():"function"==typeof y.__len__?0<y.__len__():
1:1)?(ca=c._getPixel(u,z+3))===(R=pa)&&null===ca?!0:null===ca?!1:null===R?!1:"object"!=typeof ca&&"function"!=typeof ca||"function"!=typeof ca.__cmp__?"object"!=typeof R&&"function"!=typeof R||"function"!=typeof R.__cmp__?ca==R:0===R.__cmp__(ca):0===ca.__cmp__(R):v:q:m)||!1===F||0===F||""===F?0:"object"==typeof F?"function"==typeof F.__nonzero__?F.__nonzero__():"function"==typeof F.__len__?0<F.__len__():1:1)c._setPixel(u,z,B),c._setPixel(u,z+1,p),c._setPixel(u,z+2,x),c._setPixel(u,z+3,I);c.impl.putImageData(u,
0,0,0,0,null==(sa=(G=c).width)||G.__is_instance__&&"function"==typeof sa||"function"==typeof sa.__get__?$p.getattr(G,"width"):c.width,null==(U=($=c).height)||$.__is_instance__&&"function"==typeof U||"function"==typeof U.__get__?$p.getattr($,"height"):c.height);return null},1,[null,null,["self"],["color"],["new_color",null]]);g.replace_color=e;e=$pyjs__bind_method2("get_at",function(a,b){if(!0===this.__is_instance__)var c=this;else c=a,a=b;var d,e,g;g=c.impl.getImageData("undefined"!=typeof(d=a).__array?
"undefined"!=typeof d.__array[0]?d.__array[0]:d.__getitem__(0):d.__getitem__(0),"undefined"!=typeof(e=a).__array?"undefined"!=typeof e.__array[1]?e.__array[1]:e.__getitem__(1):e.__getitem__(1),1,1);return k.Color(function(){var a,b,d,e,h,k;d=$p.list();k=$p.tuple([0,1,2,3]);"undefined"!=typeof(h=k.__array)?b=0:(k=k.__iter__(),b="undefined"!=typeof(h=k.__array)?0:"function"==typeof k.$genfunc?1:-1);for(a=0;"undefined"!=typeof(e=b?0<b?k.next(!0,!1):$p.wrapped_next(k):h[a++]);)d.append(c._getPixel(g,
e));return d}())},1,[null,null,["self"],["pos"]]);g.get_at=e;e=$pyjs__bind_method2("set_at",function(a,b,c){if(!0===this.__is_instance__)var d=this;else d=a,a=b,b=c;var e,g,f,s,A,q,p,n;if(null===(A=!((s=null==(f=(p=d)._fill_style)||p.__is_instance__&&"function"==typeof f||"function"==typeof f.__get__?$p.getattr(p,"_fill_style"):d._fill_style)===(g=b)&&null===s||(null===s?0:null===g?0:"object"!=typeof s&&"function"!=typeof s||"function"!=typeof s.__cmp__?"object"!=typeof g&&"function"!=typeof g||"function"!=
typeof g.__cmp__?s==g:0===g.__cmp__(s):0===s.__cmp__(g))))||!1===A||0===A||""===A?0:"object"==typeof A?"function"==typeof A.__nonzero__?A.__nonzero__():"function"==typeof A.__len__?0<A.__len__():1:1)d.__is_instance__&&"function"==typeof d.__setattr__?d.__setattr__("_fill_style",b):$p.setattr(d,"_fill_style",b),b=(null===(e=$p.hasattr(b,"a"))||!1===e||0===e||""===e?0:"object"==typeof e?"function"==typeof e.__nonzero__?e.__nonzero__():"function"==typeof e.__len__?0<e.__len__():1:1)?b:k.Color(b),d.setFillStyle(b);
d.fillRect("undefined"!=typeof(q=a).__array?"undefined"!=typeof q.__array[0]?q.__array[0]:q.__getitem__(0):q.__getitem__(0),"undefined"!=typeof(n=a).__array?"undefined"!=typeof n.__array[1]?n.__array[1]:n.__getitem__(1):n.__getitem__(1),1,1);return null},1,[null,null,["self"],["pos"],["color"]]);g.set_at=e;e=$pyjs__bind_method2("fill",function(a,b){if(!0===this.__is_instance__)var c=this;else c=arguments[0],a=arguments[1],b=arguments[2];"undefined"==typeof a&&(a=arguments.callee.__args__[3][1]);"undefined"==
typeof b&&(b=arguments.callee.__args__[4][1]);var d,e,g,f,s,A,q,p,n,x,B,m,v,l,J,y,H,w,N,t,I,r,C,D,F,K,Z,G,U,u,z,L,S,O,P,T,V,W,R,Q,M;if(null===(w=null===a)||!1===w||0===w||""===w?0:"object"==typeof w?"function"==typeof w.__nonzero__?w.__nonzero__():"function"==typeof w.__len__?0<w.__len__():1:1)return k.HTML5Canvas.fill(c),null;if(null===(O=a)||!1===O||0===O||""===O?0:"object"==typeof O?"function"==typeof O.__nonzero__?O.__nonzero__():"function"==typeof O.__len__?0<O.__len__():1:1){if(null===(P=!((G=
null==(Z=(F=c)._fill_style)||F.__is_instance__&&"function"==typeof Z||"function"==typeof Z.__get__?$p.getattr(F,"_fill_style"):c._fill_style)===(U=a)&&null===G||(null===G?0:null===U?0:"object"!=typeof G&&"function"!=typeof G||"function"!=typeof G.__cmp__?"object"!=typeof U&&"function"!=typeof U||"function"!=typeof U.__cmp__?G==U:0===U.__cmp__(G):0===G.__cmp__(U))))||!1===P||0===P||""===P?0:"object"==typeof P?"function"==typeof P.__nonzero__?P.__nonzero__():"function"==typeof P.__len__?0<P.__len__():
1:1)c.__is_instance__&&"function"==typeof c.__setattr__?c.__setattr__("_fill_style",a):$p.setattr(c,"_fill_style",a),(null===(L=$p.hasattr(a,"a"))||!1===L||0===L||""===L?0:"object"==typeof L?"function"==typeof L.__nonzero__?L.__nonzero__():"function"==typeof L.__len__?0<L.__len__():1:1)?c.setFillStyle(a):c.setFillStyle(k.Color(a));if(null===(W=!(null===(S=b)||!1===S||0===S||""===S?0:"object"==typeof S?"function"==typeof S.__nonzero__?S.__nonzero__():"function"==typeof S.__len__?0<S.__len__():1:1))||
!1===W||0===W||""===W?0:"object"==typeof W?"function"==typeof W.__nonzero__?W.__nonzero__():"function"==typeof W.__len__?0<W.__len__():1:1)d=k.Rect(0,0,null==(K=(C=c).width)||C.__is_instance__&&"function"==typeof K||"function"==typeof K.__get__?$p.getattr(C,"width"):c.width,null==(D=(e=c).height)||e.__is_instance__&&"function"==typeof D||"function"==typeof D.__get__?$p.getattr(e,"height"):c.height);else if(e=(null===(R=null==(d=(f=c)._display)||f.__is_instance__&&"function"==typeof d||"function"==
typeof d.__get__?$p.getattr(f,"_display"):c._display)||!1===R||0===R||""===R?0:"object"==typeof R?"function"==typeof R.__nonzero__?R.__nonzero__():"function"==typeof R.__len__?0<R.__len__():1:1)?null==(g=(A=c._display)._surface_rect)||A.__is_instance__&&"function"==typeof g||"function"==typeof g.__get__?$p.getattr(A,"_surface_rect"):c._display._surface_rect:c.get_rect(),d=(null===(T=$p.hasattr(b,"width"))||!1===T||0===T||""===T?0:"object"==typeof T?"function"==typeof T.__nonzero__?T.__nonzero__():
"function"==typeof T.__len__?0<T.__len__():1:1)?e.clip(b):e.clip(k.Rect(b)),null===(t=(null===(Q=r=!(null===(V=null==(s=(p=d).width)||p.__is_instance__&&"function"==typeof s||"function"==typeof s.__get__?$p.getattr(p,"width"):d.width)||!1===V||0===V||""===V?0:"object"==typeof V?"function"==typeof V.__nonzero__?V.__nonzero__():"function"==typeof V.__len__?0<V.__len__():1:1))||!1===Q||0===Q||""===Q?0:"object"==typeof Q?"function"==typeof Q.__nonzero__?Q.__nonzero__():"function"==typeof Q.__len__?0<
Q.__len__():1:1)?r:!(null===(M=null==(q=(n=d).height)||n.__is_instance__&&"function"==typeof q||"function"==typeof q.__get__?$p.getattr(n,"height"):d.height)||!1===M||0===M||""===M?0:"object"==typeof M?"function"==typeof M.__nonzero__?M.__nonzero__():"function"==typeof M.__len__?0<M.__len__():1:1))||!1===t||0===t||""===t?0:"object"==typeof t?"function"==typeof t.__nonzero__?t.__nonzero__():"function"==typeof t.__len__?0<t.__len__():1:1)return d;c.fillRect(null==(B=(N=d).x)||N.__is_instance__&&"function"==
typeof B||"function"==typeof B.__get__?$p.getattr(N,"x"):d.x,null==(z=(I=d).y)||I.__is_instance__&&"function"==typeof z||"function"==typeof z.__get__?$p.getattr(I,"y"):d.y,null==(x=(J=d).width)||J.__is_instance__&&"function"==typeof x||"function"==typeof x.__get__?$p.getattr(J,"width"):d.width,null==(l=(H=d).height)||H.__is_instance__&&"function"==typeof l||"function"==typeof l.__get__?$p.getattr(H,"height"):d.height)}else d=k.Rect(0,0,null==(y=(v=c).width)||v.__is_instance__&&"function"==typeof y||
"function"==typeof y.__get__?$p.getattr(v,"width"):c.width,null==(m=(u=c).height)||u.__is_instance__&&"function"==typeof m||"function"==typeof m.__get__?$p.getattr(u,"height"):c.height),c.clear();return d},1,[null,null,["self"],["color",null],["rect",null]]);g.fill=e;e=$pyjs__bind_method2("get_parent",function(a){a=!0===this.__is_instance__?this:a;var b;return null==(b=a._super_surface)||a.__is_instance__&&"function"==typeof b||"function"==typeof b.__get__?$p.getattr(a,"_super_surface"):a._super_surface},
1,[null,null,["self"]]);g.get_parent=e;e=$pyjs__bind_method2("get_offset",function(a){a=!0===this.__is_instance__?this:a;var b;return null==(b=a._offset)||a.__is_instance__&&"function"==typeof b||"function"==typeof b.__get__?$p.getattr(a,"_offset"):a._offset},1,[null,null,["self"]]);g.get_offset=e;e=$pyjs__bind_method2("toDataURL",function(a){if(!0===this.__is_instance__)var b=this;else b=arguments[0],a=arguments[1];"undefined"==typeof a&&(a=arguments.callee.__args__[3][1]);var c,d;return(null===
(c=!(null===(d=a)||!1===d||0===d||""===d?0:"object"==typeof d?"function"==typeof d.__nonzero__?d.__nonzero__():"function"==typeof d.__len__?0<d.__len__():1:1))||!1===c||0===c||""===c?0:"object"==typeof c?"function"==typeof c.__nonzero__?c.__nonzero__():"function"==typeof c.__len__?0<c.__len__():1:1)?b.canvas.toDataURL():b.canvas.toDataURL(a)},1,[null,null,["self"],["datatype",null]]);g.toDataURL=e;e=$pyjs__bind_method2("_nonimplemented_methods",function(a){var b=!0===this.__is_instance__?this:a;a=
function(){$p.tuple($pyjs_array_slice.call(arguments,0,arguments.length));return b};a.__name__="$lambda1";a.__bind_type__=0;a.__args__=["arg",null];b.__is_instance__&&"function"==typeof b.__setattr__?b.__setattr__("convert",a):$p.setattr(b,"convert",a);a=function(){$p.tuple($pyjs_array_slice.call(arguments,0,arguments.length));return b};a.__name__="$lambda2";a.__bind_type__=0;a.__args__=["arg",null];b.__is_instance__&&"function"==typeof b.__setattr__?b.__setattr__("convert_alpha",a):$p.setattr(b,
"convert_alpha",a);a=function(){$p.tuple($pyjs_array_slice.call(arguments,0,arguments.length));return null};a.__name__="$lambda3";a.__bind_type__=0;a.__args__=["arg",null];b.__is_instance__&&"function"==typeof b.__setattr__?b.__setattr__("set_alpha",a):$p.setattr(b,"set_alpha",a);a=function(){$p.tuple($pyjs_array_slice.call(arguments,0,arguments.length));return null};a.__name__="$lambda4";a.__bind_type__=0;a.__args__=["arg",null];b.__is_instance__&&"function"==typeof b.__setattr__?b.__setattr__("get_alpha",
a):$p.setattr(b,"get_alpha",a);a=function(){$p.tuple($pyjs_array_slice.call(arguments,0,arguments.length));return null};a.__name__="$lambda5";a.__bind_type__=0;a.__args__=["arg",null];b.__is_instance__&&"function"==typeof b.__setattr__?b.__setattr__("lock",a):$p.setattr(b,"lock",a);a=function(){$p.tuple($pyjs_array_slice.call(arguments,0,arguments.length));return null};a.__name__="$lambda6";a.__bind_type__=0;a.__args__=["arg",null];b.__is_instance__&&"function"==typeof b.__setattr__?b.__setattr__("unlock",
a):$p.setattr(b,"unlock",a);a=function(){$p.tuple($pyjs_array_slice.call(arguments,0,arguments.length));return!1};a.__name__="$lambda7";a.__bind_type__=0;a.__args__=["arg",null];b.__is_instance__&&"function"==typeof b.__setattr__?b.__setattr__("mustlock",a):$p.setattr(b,"mustlock",a);a=function(){$p.tuple($pyjs_array_slice.call(arguments,0,arguments.length));return!1};a.__name__="$lambda8";a.__bind_type__=0;a.__args__=["arg",null];b.__is_instance__&&"function"==typeof b.__setattr__?b.__setattr__("get_locked",
a):$p.setattr(b,"get_locked",a);a=function(){$p.tuple($pyjs_array_slice.call(arguments,0,arguments.length));return $p.tuple([])};a.__name__="$lambda9";a.__bind_type__=0;a.__args__=["arg",null];b.__is_instance__&&"function"==typeof b.__setattr__?b.__setattr__("get_locks",a):$p.setattr(b,"get_locks",a);return null},1,[null,null,["self"]]);g._nonimplemented_methods=e;e=Array(k.HTML5Canvas);var x=$p.dict(),Z;for(Z in g)x.__setitem__(Z,g[Z]);return $p._create_class("Surface",$p.tuple(e),x)}();k.Surf=function(){var g=
{},e;g.__module__="pyjsdl.surface";e=$pyjs__bind_method2("__init__",function(a,b){if(!0===this.__is_instance__)var c=this;else c=a,a=b;var d,e,g,f;c.__is_instance__&&"function"==typeof c.__setattr__?c.__setattr__("canvas",a):$p.setattr(c,"canvas",a);var k=$p.__ass_unpack($p.tuple([null==(f=(e=c.canvas).width)||e.__is_instance__&&"function"==typeof f||"function"==typeof f.__get__?$p.getattr(e,"width"):c.canvas.width,null==(g=(d=c.canvas).height)||d.__is_instance__&&"function"==typeof g||"function"==
typeof g.__get__?$p.getattr(d,"height"):c.canvas.height]),2,null);c.__is_instance__&&"function"==typeof c.__setattr__?c.__setattr__("width",k[0]):$p.setattr(c,"width",k[0]);c.__is_instance__&&"function"==typeof c.__setattr__?c.__setattr__("height",k[1]):$p.setattr(c,"height",k[1]);c._nonimplemented_methods();return null},1,[null,null,["self"],["image"]]);g.__init__=e;e=$pyjs__bind_method2("get_size",function(a){a=!0===this.__is_instance__?this:a;var b,c;return $p.tuple([null==(b=a.width)||a.__is_instance__&&
"function"==typeof b||"function"==typeof b.__get__?$p.getattr(a,"width"):a.width,null==(c=a.height)||a.__is_instance__&&"function"==typeof c||"function"==typeof c.__get__?$p.getattr(a,"height"):a.height])},1,[null,null,["self"]]);g.get_size=e;e=$pyjs__bind_method2("get_width",function(a){a=!0===this.__is_instance__?this:a;var b;return null==(b=a.width)||a.__is_instance__&&"function"==typeof b||"function"==typeof b.__get__?$p.getattr(a,"width"):a.width},1,[null,null,["self"]]);g.get_width=e;e=$pyjs__bind_method2("get_height",
function(a){a=!0===this.__is_instance__?this:a;var b;return null==(b=a.height)||a.__is_instance__&&"function"==typeof b||"function"==typeof b.__get__?$p.getattr(a,"height"):a.height},1,[null,null,["self"]]);g.get_height=e;e=$pyjs__bind_method2("_nonimplemented_methods",function(a){var b=!0===this.__is_instance__?this:a;a=function(){$p.tuple($pyjs_array_slice.call(arguments,0,arguments.length));return b};a.__name__="$lambda10";a.__bind_type__=0;a.__args__=["arg",null];b.__is_instance__&&"function"==
typeof b.__setattr__?b.__setattr__("convert",a):$p.setattr(b,"convert",a);a=function(){$p.tuple($pyjs_array_slice.call(arguments,0,arguments.length));return b};a.__name__="$lambda11";a.__bind_type__=0;a.__args__=["arg",null];b.__is_instance__&&"function"==typeof b.__setattr__?b.__setattr__("convert_alpha",a):$p.setattr(b,"convert_alpha",a);a=function(){$p.tuple($pyjs_array_slice.call(arguments,0,arguments.length));return null};a.__name__="$lambda12";a.__bind_type__=0;a.__args__=["arg",null];b.__is_instance__&&
"function"==typeof b.__setattr__?b.__setattr__("set_alpha",a):$p.setattr(b,"set_alpha",a);a=function(){$p.tuple($pyjs_array_slice.call(arguments,0,arguments.length));return null};a.__name__="$lambda13";a.__bind_type__=0;a.__args__=["arg",null];b.__is_instance__&&"function"==typeof b.__setattr__?b.__setattr__("get_alpha",a):$p.setattr(b,"get_alpha",a);a=function(){$p.tuple($pyjs_array_slice.call(arguments,0,arguments.length));return null};a.__name__="$lambda14";a.__bind_type__=0;a.__args__=["arg",
null];b.__is_instance__&&"function"==typeof b.__setattr__?b.__setattr__("lock",a):$p.setattr(b,"lock",a);a=function(){$p.tuple($pyjs_array_slice.call(arguments,0,arguments.length));return null};a.__name__="$lambda15";a.__bind_type__=0;a.__args__=["arg",null];b.__is_instance__&&"function"==typeof b.__setattr__?b.__setattr__("unlock",a):$p.setattr(b,"unlock",a);a=function(){$p.tuple($pyjs_array_slice.call(arguments,0,arguments.length));return!1};a.__name__="$lambda16";a.__bind_type__=0;a.__args__=["arg",
null];b.__is_instance__&&"function"==typeof b.__setattr__?b.__setattr__("mustlock",a):$p.setattr(b,"mustlock",a);a=function(){$p.tuple($pyjs_array_slice.call(arguments,0,arguments.length));return!1};a.__name__="$lambda17";a.__bind_type__=0;a.__args__=["arg",null];b.__is_instance__&&"function"==typeof b.__setattr__?b.__setattr__("get_locked",a):$p.setattr(b,"get_locked",a);a=function(){$p.tuple($pyjs_array_slice.call(arguments,0,arguments.length));return $p.tuple([])};a.__name__="$lambda18";a.__bind_type__=
0;a.__args__=["arg",null];b.__is_instance__&&"function"==typeof b.__setattr__?b.__setattr__("get_locks",a):$p.setattr(b,"get_locks",a);return null},1,[null,null,["self"]]);g._nonimplemented_methods=e;e=Array($p.object);var k=$p.dict(),x;for(x in g)k.__setitem__(x,g[x]);return $p._create_class("Surf",$p.tuple(e),k)}();k.IndexSizeError=function(){var g={__module__:"pyjsdl.surface"},e=Array($p.Exception),k=$p.dict(),x;for(x in g)k.__setitem__(x,g[x]);return $p._create_class("IndexSizeError",$p.tuple(e),
k)}();return this};
