$pyjs.loaded_modules["pyjsdl.mask"]=function(K){if($pyjs.loaded_modules["pyjsdl.mask"].__was_initialized__)return $pyjs.loaded_modules["pyjsdl.mask"];"undefined"!=typeof $pyjs.loaded_modules.pyjsdl&&$pyjs.loaded_modules.pyjsdl.__was_initialized__||$p.___import___("pyjsdl",null);var n=$pyjs.loaded_modules["pyjsdl.mask"];n.__repr__=function(){return"<module: pyjsdl.mask>"};n.__was_initialized__=!0;if(null===K||"undefined"==typeof K)K="pyjsdl.mask";n.__name__=K;$pyjs.loaded_modules.pyjsdl.mask=$pyjs.loaded_modules["pyjsdl.mask"];
var w,H,J,L,z;n.BitSet=$p.___import___("pyjsdl.pyjsarray.BitSet","pyjsdl",null,!1);n.Color=$p.___import___("pyjsdl.color.Color","pyjsdl",null,!1);n.sys=$p.___import___("sys","pyjsdl");if(null===(z=-1==((w=null==(L=(J=n.sys).version_info)||J.__is_instance__&&"function"==typeof L||"function"==typeof L.__get__?$p.getattr(J,"version_info"):n.sys.version_info)===(H=$p.tuple([3]))?0:typeof w!=typeof H||"number"!=typeof w&&"string"!=typeof w&&"boolean"!=typeof w?$p.cmp(w,H):w==H?0:w<H?-1:1))||!1===z||0===
z||""===z?0:"object"==typeof z?"function"==typeof z.__nonzero__?z.__nonzero__():"function"==typeof z.__len__?0<z.__len__():1:1)n.range=$p.xrange;n.__docformat__="restructuredtext";n.from_surface=function(a,c){"undefined"==typeof c&&(c=arguments.callee.__args__[3][1]);var q,l,g,A,b,e,f,d,I,h,k,m,W,t,p,O,r,x;p=("undefined"==typeof Mask?n.Mask:Mask)($p.tuple([null==(f=a.width)||a.__is_instance__&&"function"==typeof f||"function"==typeof f.__get__?$p.getattr(a,"width"):a.width,null==(d=a.height)||a.__is_instance__&&
"function"==typeof d||"function"==typeof d.__get__?$p.getattr(a,"height"):a.height]));if(null===(b=!(null===(l=null==(q=p.bit)||p.__is_instance__&&"function"==typeof q||"function"==typeof q.__get__?$p.getattr(p,"bit"):p.bit)||!1===l||0===l||""===l?0:"object"==typeof l?"function"==typeof l.__nonzero__?l.__nonzero__():"function"==typeof l.__len__?0<l.__len__():1:1))||!1===b||0===b||""===b?0:"object"==typeof b?"function"==typeof b.__nonzero__?b.__nonzero__():"function"==typeof b.__len__?0<b.__len__():
1:1)return null;f=a.impl.getImageData(0,0,null==(e=a.width)||a.__is_instance__&&"function"==typeof e||"function"==typeof e.__get__?$p.getattr(a,"width"):a.width,null==(k=a.height)||a.__is_instance__&&"function"==typeof k||"function"==typeof k.__get__?$p.getattr(a,"height"):a.height);e=$p.__ass_unpack($p.tuple([4*(null==(A=a.width)||a.__is_instance__&&"function"==typeof A||"function"==typeof A.__get__?$p.getattr(a,"width"):a.width),null==(g=a.height)||a.__is_instance__&&"function"==typeof g||"function"==
typeof g.__get__?$p.getattr(a,"height"):a.height]),2,null);g=e[0];k=n.range(0,e[1]);"undefined"!=typeof(A=k.__array)?e=0:(k=k.__iter__(),e="undefined"!=typeof(A=k.__array)?0:"function"==typeof k.$genfunc?1:-1);for(d=0;"undefined"!=typeof(q=e?0<e?k.next(!0,!1):$p.wrapped_next(k):A[d++]);)for(r=q,b=0,O=r*g+3,l=n.range(0,g,4),"undefined"!=typeof(x=l.__array)?q=0:(l=l.__iter__(),q="undefined"!=typeof(x=l.__array)?0:"function"==typeof l.$genfunc?1:-1),I=0;"undefined"!=typeof(W=q?0<q?l.next(!0,!1):$p.wrapped_next(l):
x[I++]);)(null===(h=1==((t=a._getPixel(f,O+W))===(m=c)?0:typeof t!=typeof m||"number"!=typeof t&&"string"!=typeof t&&"boolean"!=typeof t?$p.cmp(t,m):t==m?0:t<m?-1:1))||!1===h||0===h||""===h?0:"object"==typeof h?"function"==typeof h.__nonzero__?h.__nonzero__():"function"==typeof h.__len__?0<h.__len__():1:1)&&p.set_at($p.tuple([b,r])),b+=1;return p};n.from_surface.__name__="from_surface";n.from_surface.__bind_type__=0;n.from_surface.__args__=[null,null,["surface"],["threshold",127]];n.from_threshold=
function(a,c,q){"undefined"==typeof q&&(q=arguments.callee.__args__[4][1]);var l,g,A,b,e,f,d,I,h,k,m,W,t,p,O,r,x,ob,M,z,y,w,u,P,B,C,H,s,E,F,pb,X,D,qb,Q,Y,K,R,ra,Z,G,sa,J,Qa,Ra,$,L,pa,aa,Ta,Ua,Va,Wa,Xa,ta,ua,va,wa,Ya,xa,Za,ya,$a,za,ab,Aa,bb,Ba,ba,cb,N,Ca,ca,Da,db,eb,fb,gb,hb,ib,rb,Ea,sb,Fa,jb,Ga,kb,Ha,Ia,da,ea,S,T,fa,U,ga,V,ha,Ja,ia,Ka,lb,ja,Sa,mb,ka,La,la,ma,na,Ma,v,Na,nb,oa,Oa,Pa,tb,qa;oa=("undefined"==typeof Mask?n.Mask:Mask)($p.tuple([null==(mb=a.width)||a.__is_instance__&&"function"==typeof mb||
"function"==typeof mb.__get__?$p.getattr(a,"width"):a.width,null==(lb=a.height)||a.__is_instance__&&"function"==typeof lb||"function"==typeof lb.__get__?$p.getattr(a,"height"):a.height]));if(null===(B=!(null===(s=null==(db=oa.bit)||oa.__is_instance__&&"function"==typeof db||"function"==typeof db.__get__?$p.getattr(oa,"bit"):oa.bit)||!1===s||0===s||""===s?0:"object"==typeof s?"function"==typeof s.__nonzero__?s.__nonzero__():"function"==typeof s.__len__?0<s.__len__():1:1))||!1===B||0===B||""===B?0:
"object"==typeof B?"function"==typeof B.__nonzero__?B.__nonzero__():"function"==typeof B.__len__?0<B.__len__():1:1)return null;R=a.impl.getImageData(0,0,null==(eb=a.width)||a.__is_instance__&&"function"==typeof eb||"function"==typeof eb.__get__?$p.getattr(a,"width"):a.width,null==(fb=a.height)||a.__is_instance__&&"function"==typeof fb||"function"==typeof fb.__get__?$p.getattr(a,"height"):a.height);if(null===(C=(T=q)===(ea=$p.tuple([0,0,0,255]))&&null===T?!0:null===T?!1:null===ea?!1:"object"!=typeof T&&
"function"!=typeof T||"function"!=typeof T.__cmp__?"object"!=typeof ea&&"function"!=typeof ea||"function"!=typeof ea.__cmp__?T==ea:0===ea.__cmp__(T):0===T.__cmp__(ea))||!1===C||0===C||""===C?0:"object"==typeof C?"function"==typeof C.__nonzero__?C.__nonzero__():"function"==typeof C.__len__?0<C.__len__():1:1){c=n.Color(c);c=$p.tuple([null==(gb=(hb=c).r)||hb.__is_instance__&&"function"==typeof gb||"function"==typeof gb.__get__?$p.getattr(hb,"r"):c.r,null==(ib=(Wa=c).g)||Wa.__is_instance__&&"function"==
typeof ib||"function"==typeof ib.__get__?$p.getattr(Wa,"g"):c.g,null==(Va=(Ua=c).b)||Ua.__is_instance__&&"function"==typeof Va||"function"==typeof Va.__get__?$p.getattr(Ua,"b"):c.b]);var ub=$p.__ass_unpack($p.tuple([4*(null==(Ta=a.width)||a.__is_instance__&&"function"==typeof Ta||"function"==typeof Ta.__get__?$p.getattr(a,"width"):a.width),null==(l=a.height)||a.__is_instance__&&"function"==typeof l||"function"==typeof l.__get__?$p.getattr(a,"height"):a.height]),2,null);pa=ub[0];Qa=ub[1];p=n.range(0,
Qa);"undefined"!=typeof(J=p.__array)?Sa=0:(p=p.__iter__(),Sa="undefined"!=typeof(J=p.__array)?0:"function"==typeof p.$genfunc?1:-1);for(sb=0;"undefined"!=typeof(L=Sa?0<Sa?p.next(!0,!1):$p.wrapped_next(p):J[sb++]);)for(qa=L,la=0,v=qa*pa,$=n.range(0,pa,4),"undefined"!=typeof(cb=$.__array)?k=0:($=$.__iter__(),k="undefined"!=typeof(cb=$.__array)?0:"function"==typeof $.$genfunc?1:-1),tb=0;"undefined"!=typeof(X=k?0<k?$.next(!0,!1):$p.wrapped_next($):cb[tb++]);)D=X,N=v+D,(null===(A=(null===(E=ob=(S=a._getPixel(R,
N))===(ga="undefined"!=typeof(wa=c).__array?"undefined"!=typeof wa.__array[0]?wa.__array[0]:wa.__getitem__(0):wa.__getitem__(0))&&null===S?!0:null===S?!1:null===ga?!1:"object"!=typeof S&&"function"!=typeof S||"function"!=typeof S.__cmp__?"object"!=typeof ga&&"function"!=typeof ga||"function"!=typeof ga.__cmp__?S==ga:0===ga.__cmp__(S):0===S.__cmp__(ga))||!1===E||0===E||""===E?0:"object"==typeof E?"function"==typeof E.__nonzero__?E.__nonzero__():"function"==typeof E.__len__?0<E.__len__():1:1)?(null===
(F=M=(V=a._getPixel(R,N+1))===(fa="undefined"!=typeof(va=c).__array?"undefined"!=typeof va.__array[1]?va.__array[1]:va.__getitem__(1):va.__getitem__(1))&&null===V?!0:null===V?!1:null===fa?!1:"object"!=typeof V&&"function"!=typeof V||"function"!=typeof V.__cmp__?"object"!=typeof fa&&"function"!=typeof fa||"function"!=typeof fa.__cmp__?V==fa:0===fa.__cmp__(V):0===V.__cmp__(fa))||!1===F||0===F||""===F?0:"object"==typeof F?"function"==typeof F.__nonzero__?F.__nonzero__():"function"==typeof F.__len__?
0<F.__len__():1:1)?(null===(g=z=(U=a._getPixel(R,N+2))===(da="undefined"!=typeof(ua=c).__array?"undefined"!=typeof ua.__array[2]?ua.__array[2]:ua.__getitem__(2):ua.__getitem__(2))&&null===U?!0:null===U?!1:null===da?!1:"object"!=typeof U&&"function"!=typeof U||"function"!=typeof U.__cmp__?"object"!=typeof da&&"function"!=typeof da||"function"!=typeof da.__cmp__?U==da:0===da.__cmp__(U):0===U.__cmp__(da))||!1===g||0===g||""===g?0:"object"==typeof g?"function"==typeof g.__nonzero__?g.__nonzero__():"function"==
typeof g.__len__?0<g.__len__():1:1)?1==(((ma=a._getPixel(R,N+3))===(Ma="undefined"!=typeof(ta=q).__array?"undefined"!=typeof ta.__array[3]?ta.__array[3]:ta.__getitem__(3):ta.__getitem__(3))?0:typeof ma!=typeof Ma||"number"!=typeof ma&&"string"!=typeof ma&&"boolean"!=typeof ma?$p.cmp(ma,Ma):ma==Ma?0:ma<Ma?-1:1)|1):z:M:ob)||!1===A||0===A||""===A?0:"object"==typeof A?"function"==typeof A.__nonzero__?A.__nonzero__():"function"==typeof A.__len__?0<A.__len__():1:1)&&oa.set_at($p.tuple([la,qa])),la+=1}else{c=
n.Color(c);G=$p.dict([]);ba=$p.enumerate($p.tuple(["r","g","b"]));"undefined"!=typeof(Q=ba.__array)?Ra=0:(ba=ba.__iter__(),Ra="undefined"!=typeof(Q=ba.__array)?0:"function"==typeof ba.$genfunc?1:-1);for(O=0;"undefined"!=typeof(qb=Ra?0<Ra?ba.next(!0,!1):$p.wrapped_next(ba):Q[O++]);){var vb=$p.__ass_unpack(qb,2,null);v=vb[0];ra=vb[1];(null===(b="undefined"!=typeof(e=q).__array?"undefined"!=typeof e.__array[$a=v]?e.__array[$a]:e.__getitem__($a):e.__getitem__(v))||!1===b||0===b||""===b?0:"object"==typeof b?
"function"==typeof b.__nonzero__?b.__nonzero__():"function"==typeof b.__len__?0<b.__len__():1:1)?(G.__setitem__(ra+"1",("undefined"!=typeof(za=c).__array?"undefined"!=typeof za.__array[ab=v]?za.__array[ab]:za.__getitem__(ab):za.__getitem__(v))-("undefined"!=typeof(Aa=q).__array?"undefined"!=typeof Aa.__array[Ya=v]?Aa.__array[Ya]:Aa.__getitem__(Ya):Aa.__getitem__(v))-1),G.__setitem__(ra+"2",("undefined"!=typeof(xa=c).__array?"undefined"!=typeof xa.__array[Za=v]?xa.__array[Za]:xa.__getitem__(Za):xa.__getitem__(v))+
("undefined"!=typeof(ya=q).__array?"undefined"!=typeof ya.__array[bb=v]?ya.__array[bb]:ya.__getitem__(bb):ya.__getitem__(v))+1)):(G.__setitem__(ra+"1",("undefined"!=typeof(Ba=c).__array?"undefined"!=typeof Ba.__array[jb=v]?Ba.__array[jb]:Ba.__getitem__(jb):Ba.__getitem__(v))-1),G.__setitem__(ra+"2",("undefined"!=typeof(Fa=c).__array?"undefined"!=typeof Fa.__array[kb=v]?Fa.__array[kb]:Fa.__getitem__(kb):Fa.__getitem__(v))+1))}G.__setitem__("a",("undefined"!=typeof(Ga=q).__array?"undefined"!=typeof Ga.__array[3]?
Ga.__array[3]:Ga.__getitem__(3):Ga.__getitem__(3))-1);var wb=$p.__ass_unpack($p.tuple([4*(null==(Xa=a.width)||a.__is_instance__&&"function"==typeof Xa||"function"==typeof Xa.__get__?$p.getattr(a,"width"):a.width),null==(m=a.height)||a.__is_instance__&&"function"==typeof m||"function"==typeof m.__get__?$p.getattr(a,"height"):a.height]),2,null);pa=wb[0];Qa=wb[1];Y=n.range(0,Qa);"undefined"!=typeof(P=Y.__array)?t=0:(Y=Y.__iter__(),t="undefined"!=typeof(P=Y.__array)?0:"function"==typeof Y.$genfunc?1:
-1);for(K=0;"undefined"!=typeof(rb=t?0<t?Y.next(!0,!1):$p.wrapped_next(Y):P[K++]);)for(qa=rb,la=0,v=qa*pa,aa=n.range(0,pa,4),"undefined"!=typeof(nb=aa.__array)?r=0:(aa=aa.__iter__(),r="undefined"!=typeof(nb=aa.__array)?0:"function"==typeof aa.$genfunc?1:-1),H=0;"undefined"!=typeof(pb=r?0<r?aa.next(!0,!1):$p.wrapped_next(aa):nb[H++]);)D=pb,N=v+D,(null===(I=(null===(x=y=-1==((na="undefined"!=typeof(Ha=G).__array?"undefined"!=typeof Ha.__array.r1?Ha.__array.r1:Ha.__getitem__("r1"):Ha.__getitem__("r1"))===
(Oa=$compare1=a._getPixel(R,N))?0:typeof na!=typeof Oa||"number"!=typeof na&&"string"!=typeof na&&"boolean"!=typeof na?$p.cmp(na,Oa):na==Oa?0:na<Oa?-1:1)&&-1==((ca=$compare1)===(sa=$compare2="undefined"!=typeof(Ia=G).__array?"undefined"!=typeof Ia.__array.r2?Ia.__array.r2:Ia.__getitem__("r2"):Ia.__getitem__("r2"))?0:typeof ca!=typeof sa||"number"!=typeof ca&&"string"!=typeof ca&&"boolean"!=typeof ca?$p.cmp(ca,sa):ca==sa?0:ca<sa?-1:1))||!1===x||0===x||""===x?0:"object"==typeof x?"function"==typeof x.__nonzero__?
x.__nonzero__():"function"==typeof x.__len__?0<x.__len__():1:1)?(null===(f=w=-1==((Z="undefined"!=typeof(Ea=G).__array?"undefined"!=typeof Ea.__array.g1?Ea.__array.g1:Ea.__getitem__("g1"):Ea.__getitem__("g1"))===(W=$compare3=a._getPixel(R,N+1))?0:typeof Z!=typeof W||"number"!=typeof Z&&"string"!=typeof Z&&"boolean"!=typeof Z?$p.cmp(Z,W):Z==W?0:Z<W?-1:1)&&-1==((ja=$compare3)===(Ja=$compare4="undefined"!=typeof(Pa=G).__array?"undefined"!=typeof Pa.__array.g2?Pa.__array.g2:Pa.__getitem__("g2"):Pa.__getitem__("g2"))?
0:typeof ja!=typeof Ja||"number"!=typeof ja&&"string"!=typeof ja&&"boolean"!=typeof ja?$p.cmp(ja,Ja):ja==Ja?0:ja<Ja?-1:1))||!1===f||0===f||""===f?0:"object"==typeof f?"function"==typeof f.__nonzero__?f.__nonzero__():"function"==typeof f.__len__?0<f.__len__():1:1)?(null===(d=u=-1==((ha="undefined"!=typeof(Da=G).__array?"undefined"!=typeof Da.__array.b1?Da.__array.b1:Da.__getitem__("b1"):Da.__getitem__("b1"))===(Ka=$compare5=a._getPixel(R,N+2))?0:typeof ha!=typeof Ka||"number"!=typeof ha&&"string"!=
typeof ha&&"boolean"!=typeof ha?$p.cmp(ha,Ka):ha==Ka?0:ha<Ka?-1:1)&&-1==((ia=$compare5)===(La=$compare6="undefined"!=typeof(Ca=G).__array?"undefined"!=typeof Ca.__array.b2?Ca.__array.b2:Ca.__getitem__("b2"):Ca.__getitem__("b2"))?0:typeof ia!=typeof La||"number"!=typeof ia&&"string"!=typeof ia&&"boolean"!=typeof ia?$p.cmp(ia,La):ia==La?0:ia<La?-1:1))||!1===d||0===d||""===d?0:"object"==typeof d?"function"==typeof d.__nonzero__?d.__nonzero__():"function"==typeof d.__len__?0<d.__len__():1:1)?1==((ka=
a._getPixel(R,N+3))===(h="undefined"!=typeof(Na=G).__array?"undefined"!=typeof Na.__array.a?Na.__array.a:Na.__getitem__("a"):Na.__getitem__("a"))?0:typeof ka!=typeof h||"number"!=typeof ka&&"string"!=typeof ka&&"boolean"!=typeof ka?$p.cmp(ka,h):ka==h?0:ka<h?-1:1):u:w:y)||!1===I||0===I||""===I?0:"object"==typeof I?"function"==typeof I.__nonzero__?I.__nonzero__():"function"==typeof I.__len__?0<I.__len__():1:1)&&oa.set_at($p.tuple([la,qa])),la+=1}return oa};n.from_threshold.__name__="from_threshold";
n.from_threshold.__bind_type__=0;n.from_threshold.__args__=[null,null,["surface"],["color"],["threshold",$p.tuple([0,0,0,255])]];n.Mask=function(){var a={},c;a.__module__="pyjsdl.mask";c=$pyjs__bind_method2("__init__",function(g,a){if(!0===this.__is_instance__)var b=this;else b=g,g=a;var e,f,d,c,h,k,m,l;b.__is_instance__&&"function"==typeof b.__setattr__?b.__setattr__("width",$p.float_int("undefined"!=typeof(d=g).__array?"undefined"!=typeof d.__array[l=0]?d.__array[l]:d.__getitem__(l):d.__getitem__(0))):
$p.setattr(b,"width",$p.float_int("undefined"!=typeof(d=g).__array?"undefined"!=typeof d.__array[l=0]?d.__array[l]:d.__getitem__(l):d.__getitem__(0)));b.__is_instance__&&"function"==typeof b.__setattr__?b.__setattr__("height",$p.float_int("undefined"!=typeof(m=g).__array?"undefined"!=typeof m.__array[k=1]?m.__array[k]:m.__getitem__(k):m.__getitem__(1))):$p.setattr(b,"height",$p.float_int("undefined"!=typeof(m=g).__array?"undefined"!=typeof m.__array[k=1]?m.__array[k]:m.__getitem__(k):m.__getitem__(1)));
b.__is_instance__&&"function"==typeof b.__setattr__?b.__setattr__("bit",$p.list([])):$p.setattr(b,"bit",$p.list([]));d=n.range(null==(c=(f=b).height)||f.__is_instance__&&"function"==typeof c||"function"==typeof c.__get__?$p.getattr(f,"height"):b.height);"undefined"!=typeof(c=d.__array)?k=0:(d=d.__iter__(),k="undefined"!=typeof(c=d.__array)?0:"function"==typeof d.$genfunc?1:-1);for(f=0;"undefined"!=typeof(k?0<k?d.next(!0,!1):$p.wrapped_next(d):c[f++]);)b.bit.append(n.BitSet(null==(e=(h=b).width)||
h.__is_instance__&&"function"==typeof e||"function"==typeof e.__get__?$p.getattr(h,"width"):b.width));return null},1,[null,null,["self"],["size"]]);a.__init__=c;c=$pyjs__bind_method2("__str__",function(g){return(!0===this.__is_instance__?this:g).toString()},1,[null,null,["self"]]);a.__str__=c;c=$pyjs__bind_method2("__repr__",function(g){g=!0===this.__is_instance__?this:g;var a,b;return $p.sprintf("%s(%r)",$p.tuple([null==(b=g.__class__)||g.__is_instance__&&"function"==typeof b||"function"==typeof b.__get__?
$p.getattr(g,"__class__"):g.__class__,null==(a=g.__dict__)||g.__is_instance__&&"function"==typeof a||"function"==typeof a.__get__?$p.getattr(g,"__dict__"):g.__dict__]))},1,[null,null,["self"]]);a.__repr__=c;c=$pyjs__bind_method2("get_size",function(g){g=!0===this.__is_instance__?this:g;var a,b;return $p.tuple([null==(b=g.width)||g.__is_instance__&&"function"==typeof b||"function"==typeof b.__get__?$p.getattr(g,"width"):g.width,null==(a=g.height)||g.__is_instance__&&"function"==typeof a||"function"==
typeof a.__get__?$p.getattr(g,"height"):g.height])},1,[null,null,["self"]]);a.get_size=c;c=$pyjs__bind_method2("get_at",function(g,a){if(!0===this.__is_instance__)var b=this;else b=g,g=a;var e,f,d,c,h,k,m;return("undefined"!=typeof(k=null==(e=(f=b).bit)||f.__is_instance__&&"function"==typeof e||"function"==typeof e.__get__?$p.getattr(f,"bit"):b.bit).__array?"undefined"!=typeof k.__array[c="undefined"!=typeof(d=g).__array?"undefined"!=typeof d.__array[m=1]?d.__array[m]:d.__getitem__(m):d.__getitem__(1)]?
k.__array[c]:k.__getitem__(c):k.__getitem__("undefined"!=typeof(d=g).__array?"undefined"!=typeof d.__array[m=1]?d.__array[m]:d.__getitem__(m):d.__getitem__(1))).get("undefined"!=typeof(h=g).__array?"undefined"!=typeof h.__array[0]?h.__array[0]:h.__getitem__(0):h.__getitem__(0))},1,[null,null,["self"],["pos"]]);a.get_at=c;c=$pyjs__bind_method2("set_at",function(g,a){if(!0===this.__is_instance__)var b=this;else b=arguments[0],g=arguments[1],a=arguments[2];"undefined"==typeof a&&(a=arguments.callee.__args__[4][1]);
var e,f,d,c,h,k,m;("undefined"!=typeof(h=null==(e=(f=b).bit)||f.__is_instance__&&"function"==typeof e||"function"==typeof e.__get__?$p.getattr(f,"bit"):b.bit).__array?"undefined"!=typeof h.__array[k="undefined"!=typeof(d=g).__array?"undefined"!=typeof d.__array[c=1]?d.__array[c]:d.__getitem__(c):d.__getitem__(1)]?h.__array[k]:h.__getitem__(k):h.__getitem__("undefined"!=typeof(d=g).__array?"undefined"!=typeof d.__array[c=1]?d.__array[c]:d.__getitem__(c):d.__getitem__(1))).set("undefined"!=typeof(m=
g).__array?"undefined"!=typeof m.__array[0]?m.__array[0]:m.__getitem__(0):m.__getitem__(0),a);return null},1,[null,null,["self"],["pos"],["value",1]]);a.set_at=c;c=$pyjs__bind_method2("fill",function(a){var c,b,e,f;a=(!0===this.__is_instance__?this:a).bit;"undefined"!=typeof(f=a.__array)?e=0:(a=a.__iter__(),e="undefined"!=typeof(f=a.__array)?0:"function"==typeof a.$genfunc?1:-1);for(b=0;"undefined"!=typeof(c=e?0<e?a.next(!0,!1):$p.wrapped_next(a):f[b++]);)c.fill();return null},1,[null,null,["self"]]);
a.fill=c;c=$pyjs__bind_method2("clear",function(a){var c,b,e,f;e=(!0===this.__is_instance__?this:a).bit;"undefined"!=typeof(a=e.__array)?b=0:(e=e.__iter__(),b="undefined"!=typeof(a=e.__array)?0:"function"==typeof e.$genfunc?1:-1);for(f=0;"undefined"!=typeof(c=b?0<b?e.next(!0,!1):$p.wrapped_next(e):a[f++]);)c.clear();return null},1,[null,null,["self"]]);a.clear=c;c=$pyjs__bind_method2("invert",function(a){a=!0===this.__is_instance__?this:a;var c,b,e,f,d,n,h;b=a.bit;"undefined"!=typeof(n=b.__array)?
e=0:(b=b.__iter__(),e="undefined"!=typeof(n=b.__array)?0:"function"==typeof b.$genfunc?1:-1);for(h=0;"undefined"!=typeof(d=e?0<e?b.next(!0,!1):$p.wrapped_next(b):n[h++]);)d.flip(0,null==(f=(c=a).width)||c.__is_instance__&&"function"==typeof f||"function"==typeof f.__get__?$p.getattr(c,"width"):a.width);return null},1,[null,null,["self"]]);a.invert=c;c=$pyjs__bind_method2("count",function(a){var c=!0===this.__is_instance__?this:a,b,e,f,d;a=0;f=c.bit;"undefined"!=typeof(b=f.__array)?c=0:(f=f.__iter__(),
c="undefined"!=typeof(b=f.__array)?0:"function"==typeof f.$genfunc?1:-1);for(d=0;"undefined"!=typeof(e=c?0<c?f.next(!0,!1):$p.wrapped_next(f):b[d++]);)a+=e.cardinality();return a},1,[null,null,["self"]]);a.count=c;c=$pyjs__bind_method2("overlap",function(a,c,b){if(!0===this.__is_instance__)var e=this;else e=a,a=c,c=b;var f,d,l,h,k,m,q,t,p,O,r,x,z,M,w,y,H,u,P,B,C,K,s,E,F,J,X,D,L,Q;(null===(l=1==(0===(h="undefined"!=typeof(Q=c).__array?"undefined"!=typeof Q.__array[0]?Q.__array[0]:Q.__getitem__(0):
Q.__getitem__(0))?0:"number"!=typeof h||"number"!=typeof h&&"string"!=typeof h&&"boolean"!=typeof h?$p.cmp(h,0):0==h?0:0>h?-1:1))||!1===l||0===l||""===l?0:"object"==typeof l?"function"==typeof l.__nonzero__?l.__nonzero__():"function"==typeof l.__len__?0<l.__len__():1:1)?(b="undefined"!=typeof(s=c).__array?"undefined"!=typeof s.__array[0]?s.__array[0]:s.__getitem__(0):s.__getitem__(0),s=0):(b=0,s=-("undefined"!=typeof(X=c).__array?"undefined"!=typeof X.__array[0]?X.__array[0]:X.__getitem__(0):X.__getitem__(0)));
(null===(f=1==(0===(k="undefined"!=typeof(B=c).__array?"undefined"!=typeof B.__array[1]?B.__array[1]:B.__getitem__(1):B.__getitem__(1))?0:"number"!=typeof k||"number"!=typeof k&&"string"!=typeof k&&"boolean"!=typeof k?$p.cmp(k,0):0==k?0:0>k?-1:1))||!1===f||0===f||""===f?0:"object"==typeof f?"function"==typeof f.__nonzero__?f.__nonzero__():"function"==typeof f.__len__?0<f.__len__():1:1)?(f="undefined"!=typeof(C=c).__array?"undefined"!=typeof C.__array[1]?C.__array[1]:C.__getitem__(1):C.__getitem__(1),
c=0):(f=0,c=-("undefined"!=typeof(u=c).__array?"undefined"!=typeof u.__array[1]?u.__array[1]:u.__getitem__(1):u.__getitem__(1)));u=$p.min((null==(E=(r=e).width)||r.__is_instance__&&"function"==typeof E||"function"==typeof E.__get__?$p.getattr(r,"width"):e.width)-b,(null==(x=(z=a).width)||z.__is_instance__&&"function"==typeof x||"function"==typeof x.__get__?$p.getattr(z,"width"):a.width)-s);r=$p.min((null==(M=(t=e).height)||t.__is_instance__&&"function"==typeof M||"function"==typeof M.__get__?$p.getattr(t,
"height"):e.height)-f,(null==(p=(H=a).height)||H.__is_instance__&&"function"==typeof p||"function"==typeof p.__get__?$p.getattr(H,"height"):a.height)-c);if(null===(y=(null===(d=K=1==(0===u?0:"number"!=typeof u||"number"!=typeof u&&"string"!=typeof u&&"boolean"!=typeof u?$p.cmp(u,0):0==u?0:0>u?-1:1))||!1===d||0===d||""===d?0:"object"==typeof d?"function"==typeof d.__nonzero__?d.__nonzero__():"function"==typeof d.__len__?0<d.__len__():1:1)?1==(0===r?0:"number"!=typeof r||"number"!=typeof r&&"string"!=
typeof r&&"boolean"!=typeof r?$p.cmp(r,0):0==r?0:0>r?-1:1):K)||!1===y||0===y||""===y?0:"object"==typeof y?"function"==typeof y.__nonzero__?y.__nonzero__():"function"==typeof y.__len__?0<y.__len__():1:1)for(p=n.range(r),"undefined"!=typeof(d=p.__array)?M=0:(p=p.__iter__(),M="undefined"!=typeof(d=p.__array)?0:"function"==typeof p.$genfunc?1:-1),t=0;"undefined"!=typeof(y=M?0<M?p.next(!0,!1):$p.wrapped_next(p):d[t++]);)if(null===(D=("undefined"!=typeof(P=null==(O=(m=e).bit)||m.__is_instance__&&"function"==
typeof O||"function"==typeof O.__get__?$p.getattr(m,"bit"):e.bit).__array?"undefined"!=typeof P.__array[F=f+y]?P.__array[F]:P.__getitem__(F):P.__getitem__(f+y)).get(b,b+u).intersects(("undefined"!=typeof(w=null==(q=(L=a).bit)||L.__is_instance__&&"function"==typeof q||"function"==typeof q.__get__?$p.getattr(L,"bit"):a.bit).__array?"undefined"!=typeof w.__array[J=c+y]?w.__array[J]:w.__getitem__(J):w.__getitem__(c+y)).get(s,s+u)))||!1===D||0===D||""===D?0:"object"==typeof D?"function"==typeof D.__nonzero__?
D.__nonzero__():"function"==typeof D.__len__?0<D.__len__():1:1)return!0;return null},1,[null,null,["self"],["mask"],["offset"]]);a.overlap=c;c=$pyjs__bind_method2("toString",function(a){if(!0===this.__is_instance__)var c=this;else c=arguments[0],a=arguments[1];"undefined"==typeof a&&(a=arguments.callee.__args__[3][1]);var b,e,f,d,l,h,k,m;f=$p.dict([[!0,"undefined"!=typeof(e=a).__array?"undefined"!=typeof e.__array[0]?e.__array[0]:e.__getitem__(0):e.__getitem__(0)],[!1,"undefined"!=typeof(b=a).__array?
"undefined"!=typeof b.__array[1]?b.__array[1]:b.__getitem__(1):b.__getitem__(1)]]);d=$p.list([]);h=c.bit;"undefined"!=typeof(b=h.__array)?e=0:(h=h.__iter__(),e="undefined"!=typeof(b=h.__array)?0:"function"==typeof h.$genfunc?1:-1);for(k=0;"undefined"!=typeof(m=e?0<e?h.next(!0,!1):$p.wrapped_next(h):b[k++]);)l=m,d.append("\n"),d.extend(function(){var a,b,d,e,g,h,k,m;h=$p.list();b=n.range(null==(k=(g=c).width)||g.__is_instance__&&"function"==typeof k||"function"==typeof k.__get__?$p.getattr(g,"width"):
c.width);"undefined"!=typeof(g=b.__array)?m=0:(b=b.__iter__(),m="undefined"!=typeof(g=b.__array)?0:"function"==typeof b.$genfunc?1:-1);for(k=0;"undefined"!=typeof(e=m?0<m?b.next(!0,!1):$p.wrapped_next(b):g[k++]);)h.append("undefined"!=typeof(d=f).__array?"undefined"!=typeof d.__array[a=l.get(e)]?d.__array[a]:d.__getitem__(a):d.__getitem__(l.get(e)));return h}());return"".join(d)},1,[null,null,["self"],["bit",$p.tuple(["1","0"])]]);a.toString=c;c=Array($p.object);var q=$p.dict(),l;for(l in a)q.__setitem__(l,
a[l]);return $p._create_class("Mask",$p.tuple(c),q)}();return this};
