$pyjs.loaded_modules["pyjsdl.color"]=function(K){if($pyjs.loaded_modules["pyjsdl.color"].__was_initialized__)return $pyjs.loaded_modules["pyjsdl.color"];"undefined"!=typeof $pyjs.loaded_modules.pyjsdl&&$pyjs.loaded_modules.pyjsdl.__was_initialized__||$p.___import___("pyjsdl",null);var E=$pyjs.loaded_modules["pyjsdl.color"];E.__repr__=function(){return"<module: pyjsdl.color>"};E.__was_initialized__=!0;if(null===K||"undefined"==typeof K)K="pyjsdl.color";E.__name__=K;$pyjs.loaded_modules.pyjsdl.color=
$pyjs.loaded_modules["pyjsdl.color"];E._Color=$p.___import___("pyjsdl.pyjsobj.Color","pyjsdl",null,!1);E.__docformat__="restructuredtext";E.Color=function(){var g={},c;g.__module__="pyjsdl.color";c=$pyjs__bind_method2("__init__",function(){if(!0===this.__is_instance__)var a=this,f=$p.tuple($pyjs_array_slice.call(arguments,0,arguments.length));else a=arguments[0],f=$p.tuple($pyjs_array_slice.call(arguments,1,arguments.length));var b,d,e,Ha,l,m,h,k,p,c,t,s,g,$,u,y,n,z,v,q,r;e=null===(r=f)?0:"undefined"!=
typeof r.__array?r.__array.length:"function"==typeof r.__len__?r.__len__():"undefined"!=typeof r.length?r.length:$p.len(r);if(null===(c=1===(m=e)&&null===m?!0:null===m?!1:"object"!=typeof m&&"function"!=typeof m||"function"!=typeof m.__cmp__?1==m:0===m.__cmp__(1))||!1===c||0===c||""===c?0:"object"==typeof c?"function"==typeof c.__nonzero__?c.__nonzero__():"function"==typeof c.__len__?0<c.__len__():1:1)if(f="undefined"!=typeof(y=f).__array?"undefined"!=typeof y.__array[0]?y.__array[0]:y.__getitem__(0):
y.__getitem__(0),null===(k=$p.hasattr(f,"__len__"))||!1===k||0===k||""===k?0:"object"==typeof k?"function"==typeof k.__nonzero__?k.__nonzero__():"function"==typeof k.__len__?0<k.__len__():1:1)e=null===(q=f)?0:"undefined"!=typeof q.__array?q.__array.length:"function"==typeof q.__len__?q.__len__():"undefined"!=typeof q.length?q.length:$p.len(q);if(null===(p=4===(l=e)&&null===l?!0:null===l?!1:"object"!=typeof l&&"function"!=typeof l||"function"!=typeof l.__cmp__?4==l:0===l.__cmp__(4))||!1===p||0===p||
""===p?0:"object"==typeof p?"function"==typeof p.__nonzero__?p.__nonzero__():"function"==typeof p.__len__?0<p.__len__():1:1)n=$p.__ass_unpack($p.tuple(["undefined"!=typeof(u=f).__array?"undefined"!=typeof u.__array[0]?u.__array[0]:u.__getitem__(0):u.__getitem__(0),"undefined"!=typeof($=f).__array?"undefined"!=typeof $.__array[1]?$.__array[1]:$.__getitem__(1):$.__getitem__(1),"undefined"!=typeof(g=f).__array?"undefined"!=typeof g.__array[2]?g.__array[2]:g.__getitem__(2):g.__getitem__(2),"undefined"!=
typeof(s=f).__array?"undefined"!=typeof s.__array[3]?s.__array[3]:s.__getitem__(3):s.__getitem__(3)]),4,null),a.__is_instance__&&"function"==typeof a.__setattr__?a.__setattr__("r",n[0]):$p.setattr(a,"r",n[0]),a.__is_instance__&&"function"==typeof a.__setattr__?a.__setattr__("g",n[1]):$p.setattr(a,"g",n[1]),a.__is_instance__&&"function"==typeof a.__setattr__?a.__setattr__("b",n[2]):$p.setattr(a,"b",n[2]),a.__is_instance__&&"function"==typeof a.__setattr__?a.__setattr__("a",n[3]):$p.setattr(a,"a",n[3]);
else{if(null===(b=3===(h=e)&&null===h?!0:null===h?!1:"object"!=typeof h&&"function"!=typeof h||"function"!=typeof h.__cmp__?3==h:0===h.__cmp__(3))||!1===b||0===b||""===b?0:"object"==typeof b?"function"==typeof b.__nonzero__?b.__nonzero__():"function"==typeof b.__len__?0<b.__len__():1:1)s=$p.__ass_unpack($p.tuple(["undefined"!=typeof(z=f).__array?"undefined"!=typeof z.__array[0]?z.__array[0]:z.__getitem__(0):z.__getitem__(0),"undefined"!=typeof(v=f).__array?"undefined"!=typeof v.__array[1]?v.__array[1]:
v.__getitem__(1):v.__getitem__(1),"undefined"!=typeof(n=f).__array?"undefined"!=typeof n.__array[2]?n.__array[2]:n.__getitem__(2):n.__getitem__(2),255]),4,null);else{if(null===(t=(null===(d=Ha=$p.hasattr(f,"startswith"))||!1===d||0===d||""===d?0:"object"==typeof d?"function"==typeof d.__nonzero__?d.__nonzero__():"function"==typeof d.__len__?0<d.__len__():1:1)?f.startswith("#"):Ha)||!1===t||0===t||""===t?0:"object"==typeof t?"function"==typeof t.__nonzero__?t.__nonzero__():"function"==typeof t.__len__?
0<t.__len__():1:1)f="0x"+$p.__getslice(f,1,null);s=$p.__ass_unpack($p.tuple([f>>16&255,f>>8&255,f&255,f>>24&255]),4,null)}a.__is_instance__&&"function"==typeof a.__setattr__?a.__setattr__("r",s[0]):$p.setattr(a,"r",s[0]);a.__is_instance__&&"function"==typeof a.__setattr__?a.__setattr__("g",s[1]):$p.setattr(a,"g",s[1]);a.__is_instance__&&"function"==typeof a.__setattr__?a.__setattr__("b",s[2]):$p.setattr(a,"b",s[2]);a.__is_instance__&&"function"==typeof a.__setattr__?a.__setattr__("a",s[3]):$p.setattr(a,
"a",s[3])}return null},1,["color",null,["self"]]);g.__init__=c;c=$pyjs__bind_method2("__str__",function(a){a=!0===this.__is_instance__?this:a;var f,b,d,e;return $p.sprintf("rgba(%d, %d, %d, %f)",$p.tuple([null==(f=a.r)||a.__is_instance__&&"function"==typeof f||"function"==typeof f.__get__?$p.getattr(a,"r"):a.r,null==(e=a.g)||a.__is_instance__&&"function"==typeof e||"function"==typeof e.__get__?$p.getattr(a,"g"):a.g,null==(b=a.b)||a.__is_instance__&&"function"==typeof b||"function"==typeof b.__get__?
$p.getattr(a,"b"):a.b,(null==(d=a.a)||a.__is_instance__&&"function"==typeof d||"function"==typeof d.__get__?$p.getattr(a,"a"):a.a)/255]))},1,[null,null,["self"]]);g.__str__=c;c=$pyjs__bind_method2("__repr__",function(a){a=!0===this.__is_instance__?this:a;var f,b,d,e;return $p.sprintf("(%d, %d, %d, %d)",$p.tuple([null==(f=a.r)||a.__is_instance__&&"function"==typeof f||"function"==typeof f.__get__?$p.getattr(a,"r"):a.r,null==(d=a.g)||a.__is_instance__&&"function"==typeof d||"function"==typeof d.__get__?
$p.getattr(a,"g"):a.g,null==(e=a.b)||a.__is_instance__&&"function"==typeof e||"function"==typeof e.__get__?$p.getattr(a,"b"):a.b,null==(b=a.a)||a.__is_instance__&&"function"==typeof b||"function"==typeof b.__get__?$p.getattr(a,"a"):a.a]))},1,[null,null,["self"]]);g.__repr__=c;c=$pyjs__bind_method2("__getitem__",function(a,f){if(!0===this.__is_instance__)var b=this;else b=a,a=f;var d,e,c,l,m,h,k,p,g,t;return"undefined"!=typeof(d=$p.dict([[0,null==(t=(p=b).r)||p.__is_instance__&&"function"==typeof t||
"function"==typeof t.__get__?$p.getattr(p,"r"):b.r],[1,null==(k=(c=b).g)||c.__is_instance__&&"function"==typeof k||"function"==typeof k.__get__?$p.getattr(c,"g"):b.g],[2,null==(l=(m=b).b)||m.__is_instance__&&"function"==typeof l||"function"==typeof l.__get__?$p.getattr(m,"b"):b.b],[3,null==(h=(g=b).a)||g.__is_instance__&&"function"==typeof h||"function"==typeof h.__get__?$p.getattr(g,"a"):b.a]])).__array?"undefined"!=typeof d.__array[e=a]?d.__array[e]:d.__getitem__(e):d.__getitem__(a)},1,[null,null,
["self"],["index"]]);g.__getitem__=c;c=$pyjs__bind_method2("__setitem__",function(a,f,b){if(!0===this.__is_instance__)var d=this;else d=a,a=f,f=b;var e,c;d.__setattr__("undefined"!=typeof(e=$p.dict([[0,"r"],[1,"g"],[2,"b"],[3,"a"]])).__array?"undefined"!=typeof e.__array[c=a]?e.__array[c]:e.__getitem__(c):e.__getitem__(a),f);return null},1,[null,null,["self"],["index"],["val"]]);g.__setitem__=c;c=$pyjs__bind_method2("__iter__",function(a){a=!0===this.__is_instance__?this:a;var f,b,d,e;return $p.iter($p.list([null==
(b=a.r)||a.__is_instance__&&"function"==typeof b||"function"==typeof b.__get__?$p.getattr(a,"r"):a.r,null==(d=a.g)||a.__is_instance__&&"function"==typeof d||"function"==typeof d.__get__?$p.getattr(a,"g"):a.g,null==(e=a.b)||a.__is_instance__&&"function"==typeof e||"function"==typeof e.__get__?$p.getattr(a,"b"):a.b,null==(f=a.a)||a.__is_instance__&&"function"==typeof f||"function"==typeof f.__get__?$p.getattr(a,"a"):a.a]))},1,[null,null,["self"]]);g.__iter__=c;c=$pyjs__bind_method2("__len__",function(a){return 4},
1,[null,null,["self"]]);g.__len__=c;c=$pyjs__bind_method2("__eq__",function(a,f){if(!0===this.__is_instance__)var b=this;else b=a,a=f;var d,e,c,l,m,h,k,p,g,t,s,K,$,u,y,n,z,v,q,r,L,F,aa,O,P,ba,Q,ca,E,sa,ta,R,da,S,T,ea,U,fa,V,ga,ha,ua,va,wa,xa,ya,za,Aa,W,X,A,w,B,x,C,ia,Y,ja,Ca,ka,oa,Da,Ea,Fa,Ga,na,pa,qa,G,M,la,Z,H,ra,ma,I,N,J,D;return(null===(q=$p.hasattr(a,"a"))||!1===q||0===q||""===q?0:"object"==typeof q?"function"==typeof q.__nonzero__?q.__nonzero__():"function"==typeof q.__len__?0<q.__len__():1:
1)?(null===(O=t=(H=null==(Ca=(Ea=b).r)||Ea.__is_instance__&&"function"==typeof Ca||"function"==typeof Ca.__get__?$p.getattr(Ea,"r"):b.r)===(la=null==(Da=(oa=a).r)||oa.__is_instance__&&"function"==typeof Da||"function"==typeof Da.__get__?$p.getattr(oa,"r"):a.r)&&null===H?!0:null===H?!1:null===la?!1:"object"!=typeof H&&"function"!=typeof H||"function"!=typeof H.__cmp__?"object"!=typeof la&&"function"!=typeof la||"function"!=typeof la.__cmp__?H==la:0===la.__cmp__(H):0===H.__cmp__(la))||!1===O||0===O||
""===O?0:"object"==typeof O?"function"==typeof O.__nonzero__?O.__nonzero__():"function"==typeof O.__len__?0<O.__len__():1:1)?(null===(P=s=(Z=null==(ka=(Ga=b).g)||Ga.__is_instance__&&"function"==typeof ka||"function"==typeof ka.__get__?$p.getattr(Ga,"g"):b.g)===(A=null==(Fa=(W=a).g)||W.__is_instance__&&"function"==typeof Fa||"function"==typeof Fa.__get__?$p.getattr(W,"g"):a.g)&&null===Z?!0:null===Z?!1:null===A?!1:"object"!=typeof Z&&"function"!=typeof Z||"function"!=typeof Z.__cmp__?"object"!=typeof A&&
"function"!=typeof A||"function"!=typeof A.__cmp__?Z==A:0===A.__cmp__(Z):0===Z.__cmp__(A))||!1===P||0===P||""===P?0:"object"==typeof P?"function"==typeof P.__nonzero__?P.__nonzero__():"function"==typeof P.__len__?0<P.__len__():1:1)?(null===(d=K=(w=null==(X=(za=b).b)||za.__is_instance__&&"function"==typeof X||"function"==typeof X.__get__?$p.getattr(za,"b"):b.b)===(B=null==(Aa=(xa=a).b)||xa.__is_instance__&&"function"==typeof Aa||"function"==typeof Aa.__get__?$p.getattr(xa,"b"):a.b)&&null===w?!0:null===
w?!1:null===B?!1:"object"!=typeof w&&"function"!=typeof w||"function"!=typeof w.__cmp__?"object"!=typeof B&&"function"!=typeof B||"function"!=typeof B.__cmp__?w==B:0===B.__cmp__(w):0===w.__cmp__(B))||!1===d||0===d||""===d?0:"object"==typeof d?"function"==typeof d.__nonzero__?d.__nonzero__():"function"==typeof d.__len__?0<d.__len__():1:1)?(x=null==(ya=(va=b).a)||va.__is_instance__&&"function"==typeof ya||"function"==typeof ya.__get__?$p.getattr(va,"a"):b.a)===(C=null==(wa=(Y=a).a)||Y.__is_instance__&&
"function"==typeof wa||"function"==typeof wa.__get__?$p.getattr(Y,"a"):a.a)&&null===x?!0:null===x?!1:null===C?!1:"object"!=typeof x&&"function"!=typeof x||"function"!=typeof x.__cmp__?"object"!=typeof C&&"function"!=typeof C||"function"!=typeof C.__cmp__?x==C:0===C.__cmp__(x):0===x.__cmp__(C):K:s:t:(null===(e=4===(ia=null===(na=a)?0:"undefined"!=typeof na.__array?na.__array.length:"function"==typeof na.__len__?na.__len__():"undefined"!=typeof na.length?na.length:$p.len(na))&&null===ia?!0:null===ia?
!1:"object"!=typeof ia&&"function"!=typeof ia||"function"!=typeof ia.__cmp__?4==ia:0===ia.__cmp__(4))||!1===e||0===e||""===e?0:"object"==typeof e?"function"==typeof e.__nonzero__?e.__nonzero__():"function"==typeof e.__len__?0<e.__len__():1:1)?(null===(c=$=(R=null==(ja=(ea=b).a)||ea.__is_instance__&&"function"==typeof ja||"function"==typeof ja.__get__?$p.getattr(ea,"a"):b.a)===(ba="undefined"!=typeof(qa=a).__array?"undefined"!=typeof qa.__array[3]?qa.__array[3]:qa.__getitem__(3):qa.__getitem__(3))&&
null===R?!0:null===R?!1:null===ba?!1:"object"!=typeof R&&"function"!=typeof R||"function"!=typeof R.__cmp__?"object"!=typeof ba&&"function"!=typeof ba||"function"!=typeof ba.__cmp__?R==ba:0===ba.__cmp__(R):0===R.__cmp__(ba))||!1===c||0===c||""===c?0:"object"==typeof c?"function"==typeof c.__nonzero__?c.__nonzero__():"function"==typeof c.__len__?0<c.__len__():1:1)?(null===(l=p=(Q=null==(T=(fa=b).r)||fa.__is_instance__&&"function"==typeof T||"function"==typeof T.__get__?$p.getattr(fa,"r"):b.r)===(y=
"undefined"!=typeof(J=a).__array?"undefined"!=typeof J.__array[0]?J.__array[0]:J.__getitem__(0):J.__getitem__(0))&&null===Q?!0:null===Q?!1:null===y?!1:"object"!=typeof Q&&"function"!=typeof Q||"function"!=typeof Q.__cmp__?"object"!=typeof y&&"function"!=typeof y||"function"!=typeof y.__cmp__?Q==y:0===y.__cmp__(Q):0===Q.__cmp__(y))||!1===l||0===l||""===l?0:"object"==typeof l?"function"==typeof l.__nonzero__?l.__nonzero__():"function"==typeof l.__len__?0<l.__len__():1:1)?(null===(m=g=(u=null==(U=(ga=
b).g)||ga.__is_instance__&&"function"==typeof U||"function"==typeof U.__get__?$p.getattr(ga,"g"):b.g)===(z="undefined"!=typeof(G=a).__array?"undefined"!=typeof G.__array[1]?G.__array[1]:G.__getitem__(1):G.__getitem__(1))&&null===u?!0:null===u?!1:null===z?!1:"object"!=typeof u&&"function"!=typeof u||"function"!=typeof u.__cmp__?"object"!=typeof z&&"function"!=typeof z||"function"!=typeof z.__cmp__?u==z:0===z.__cmp__(u):0===u.__cmp__(z))||!1===m||0===m||""===m?0:"object"==typeof m?"function"==typeof m.__nonzero__?
m.__nonzero__():"function"==typeof m.__len__?0<m.__len__():1:1)?(n=null==(V=(ua=b).b)||ua.__is_instance__&&"function"==typeof V||"function"==typeof V.__get__?$p.getattr(ua,"b"):b.b)===(D="undefined"!=typeof(M=a).__array?"undefined"!=typeof M.__array[2]?M.__array[2]:M.__getitem__(2):M.__getitem__(2))&&null===n?!0:null===n?!1:null===D?!1:"object"!=typeof n&&"function"!=typeof n||"function"!=typeof n.__cmp__?"object"!=typeof D&&"function"!=typeof D||"function"!=typeof D.__cmp__?n==D:0===D.__cmp__(n):
0===n.__cmp__(D):g:p:$:(null===(h=ma=(v=null==(ha=(S=b).r)||S.__is_instance__&&"function"==typeof ha||"function"==typeof ha.__get__?$p.getattr(S,"r"):b.r)===(L="undefined"!=typeof(pa=a).__array?"undefined"!=typeof pa.__array[0]?pa.__array[0]:pa.__getitem__(0):pa.__getitem__(0))&&null===v?!0:null===v?!1:null===L?!1:"object"!=typeof v&&"function"!=typeof v||"function"!=typeof v.__cmp__?"object"!=typeof L&&"function"!=typeof L||"function"!=typeof L.__cmp__?v==L:0===L.__cmp__(v):0===v.__cmp__(L))||!1===
h||0===h||""===h?0:"object"==typeof h?"function"==typeof h.__nonzero__?h.__nonzero__():"function"==typeof h.__len__?0<h.__len__():1:1)?(null===(k=ra=(r=null==(da=(E=b).g)||E.__is_instance__&&"function"==typeof da||"function"==typeof da.__get__?$p.getattr(E,"g"):b.g)===(aa="undefined"!=typeof(N=a).__array?"undefined"!=typeof N.__array[1]?N.__array[1]:N.__getitem__(1):N.__getitem__(1))&&null===r?!0:null===r?!1:null===aa?!1:"object"!=typeof r&&"function"!=typeof r||"function"!=typeof r.__cmp__?"object"!=
typeof aa&&"function"!=typeof aa||"function"!=typeof aa.__cmp__?r==aa:0===aa.__cmp__(r):0===r.__cmp__(aa))||!1===k||0===k||""===k?0:"object"==typeof k?"function"==typeof k.__nonzero__?k.__nonzero__():"function"==typeof k.__len__?0<k.__len__():1:1)?(F=null==(sa=(ta=b).b)||ta.__is_instance__&&"function"==typeof sa||"function"==typeof sa.__get__?$p.getattr(ta,"b"):b.b)===(ca="undefined"!=typeof(I=a).__array?"undefined"!=typeof I.__array[2]?I.__array[2]:I.__getitem__(2):I.__getitem__(2))&&null===F?!0:
null===F?!1:null===ca?!1:"object"!=typeof F&&"function"!=typeof F||"function"!=typeof F.__cmp__?"object"!=typeof ca&&"function"!=typeof ca||"function"!=typeof ca.__cmp__?F==ca:0===ca.__cmp__(F):0===F.__cmp__(ca):ra:ma},1,[null,null,["self"],["other"]]);g.__eq__=c;c=$pyjs__bind_method2("__ne__",function(a,c){if(!0===this.__is_instance__)var b=this;else b=a,a=c;var d,e,g,l,m,h,k,p,E,t,s,K,$,u,y,n,z,v,q,r,L,F,aa,O,P,ba,Q,ca,Ba,sa,ta,R,da,S,T,ea,U,fa,V,ga,ha,ua,va,wa,xa,ya,za,Aa,W,X,A,w,B,x,C,ia,Y,ja,
Ca,ka,oa,Da,Ea,Fa,Ga,na,pa,qa,G,M,la,Z,H,ra,ma,I,N,J,D;return(null===(g=$p.hasattr(a,"a"))||!1===g||0===g||""===g?0:"object"==typeof g?"function"==typeof g.__nonzero__?g.__nonzero__():"function"==typeof g.__len__?0<g.__len__():1:1)?(null===(d=Ga=!((T=null==(Aa=(wa=b).r)||wa.__is_instance__&&"function"==typeof Aa||"function"==typeof Aa.__get__?$p.getattr(wa,"r"):b.r)===(da=null==(xa=(ya=a).r)||ya.__is_instance__&&"function"==typeof xa||"function"==typeof xa.__get__?$p.getattr(ya,"r"):a.r)&&null===
T||(null===T?0:null===da?0:"object"!=typeof T&&"function"!=typeof T||"function"!=typeof T.__cmp__?"object"!=typeof da&&"function"!=typeof da||"function"!=typeof da.__cmp__?T==da:0===da.__cmp__(T):0===T.__cmp__(da))))||!1===d||0===d||""===d?0:"object"==typeof d?"function"==typeof d.__nonzero__?d.__nonzero__():"function"==typeof d.__len__?0<d.__len__():1:1)?Ga:(null===(e=pa=!((S=null==(za=(ua=b).g)||ua.__is_instance__&&"function"==typeof za||"function"==typeof za.__get__?$p.getattr(ua,"g"):b.g)===(fa=
null==(va=(R=a).g)||R.__is_instance__&&"function"==typeof va||"function"==typeof va.__get__?$p.getattr(R,"g"):a.g)&&null===S||(null===S?0:null===fa?0:"object"!=typeof S&&"function"!=typeof S||"function"!=typeof S.__cmp__?"object"!=typeof fa&&"function"!=typeof fa||"function"!=typeof fa.__cmp__?S==fa:0===fa.__cmp__(S):0===S.__cmp__(fa))))||!1===e||0===e||""===e?0:"object"==typeof e?"function"==typeof e.__nonzero__?e.__nonzero__():"function"==typeof e.__len__?0<e.__len__():1:1)?pa:(null===(B=na=!((V=
null==(ta=(sa=b).b)||sa.__is_instance__&&"function"==typeof ta||"function"==typeof ta.__get__?$p.getattr(sa,"b"):b.b)===(ea=null==(Ba=(ca=a).b)||ca.__is_instance__&&"function"==typeof Ba||"function"==typeof Ba.__get__?$p.getattr(ca,"b"):a.b)&&null===V||(null===V?0:null===ea?0:"object"!=typeof V&&"function"!=typeof V||"function"!=typeof V.__cmp__?"object"!=typeof ea&&"function"!=typeof ea||"function"!=typeof ea.__cmp__?V==ea:0===ea.__cmp__(V):0===V.__cmp__(ea))))||!1===B||0===B||""===B?0:"object"==
typeof B?"function"==typeof B.__nonzero__?B.__nonzero__():"function"==typeof B.__len__?0<B.__len__():1:1)?na:!((U=null==(Q=(ba=b).a)||ba.__is_instance__&&"function"==typeof Q||"function"==typeof Q.__get__?$p.getattr(ba,"a"):b.a)===(ga=null==(P=(O=a).a)||O.__is_instance__&&"function"==typeof P||"function"==typeof P.__get__?$p.getattr(O,"a"):a.a)&&null===U||(null===U?0:null===ga?0:"object"!=typeof U&&"function"!=typeof U||"function"!=typeof U.__cmp__?"object"!=typeof ga&&"function"!=typeof ga||"function"!=
typeof ga.__cmp__?U==ga:0===ga.__cmp__(U):0===U.__cmp__(ga))):(null===(w=4===(ha=null===(ja=a)?0:"undefined"!=typeof ja.__array?ja.__array.length:"function"==typeof ja.__len__?ja.__len__():"undefined"!=typeof ja.length?ja.length:$p.len(ja))&&null===ha?!0:null===ha?!1:"object"!=typeof ha&&"function"!=typeof ha||"function"!=typeof ha.__cmp__?4==ha:0===ha.__cmp__(4))||!1===w||0===w||""===w?0:"object"==typeof w?"function"==typeof w.__nonzero__?w.__nonzero__():"function"==typeof w.__len__?0<w.__len__():
1:1)?(null===(C=Da=!((ma=null==(aa=(s=b).a)||s.__is_instance__&&"function"==typeof aa||"function"==typeof aa.__get__?$p.getattr(s,"a"):b.a)===(ka="undefined"!=typeof(oa=a).__array?"undefined"!=typeof oa.__array[3]?oa.__array[3]:oa.__getitem__(3):oa.__getitem__(3))&&null===ma||(null===ma?0:null===ka?0:"object"!=typeof ma&&"function"!=typeof ma||"function"!=typeof ma.__cmp__?"object"!=typeof ka&&"function"!=typeof ka||"function"!=typeof ka.__cmp__?ma==ka:0===ka.__cmp__(ma):0===ma.__cmp__(ka))))||!1===
C||0===C||""===C?0:"object"==typeof C?"function"==typeof C.__nonzero__?C.__nonzero__():"function"==typeof C.__len__?0<C.__len__():1:1)?Da:(null===(x=Fa=!((Y=null==(K=(E=b).r)||E.__is_instance__&&"function"==typeof K||"function"==typeof K.__get__?$p.getattr(E,"r"):b.r)===(D="undefined"!=typeof(ra=a).__array?"undefined"!=typeof ra.__array[0]?ra.__array[0]:ra.__getitem__(0):ra.__getitem__(0))&&null===Y||(null===Y?0:null===D?0:"object"!=typeof Y&&"function"!=typeof Y||"function"!=typeof Y.__cmp__?"object"!=
typeof D&&"function"!=typeof D||"function"!=typeof D.__cmp__?Y==D:0===D.__cmp__(Y):0===Y.__cmp__(D))))||!1===x||0===x||""===x?0:"object"==typeof x?"function"==typeof x.__nonzero__?x.__nonzero__():"function"==typeof x.__len__?0<x.__len__():1:1)?Fa:(null===(X=Ea=!((J=null==(t=(y=b).g)||y.__is_instance__&&"function"==typeof t||"function"==typeof t.__get__?$p.getattr(y,"g"):b.g)===(N="undefined"!=typeof(H=a).__array?"undefined"!=typeof H.__array[1]?H.__array[1]:H.__getitem__(1):H.__getitem__(1))&&null===
J||(null===J?0:null===N?0:"object"!=typeof J&&"function"!=typeof J||"function"!=typeof J.__cmp__?"object"!=typeof N&&"function"!=typeof N||"function"!=typeof N.__cmp__?J==N:0===N.__cmp__(J):0===J.__cmp__(N))))||!1===X||0===X||""===X?0:"object"==typeof X?"function"==typeof X.__nonzero__?X.__nonzero__():"function"==typeof X.__len__?0<X.__len__():1:1)?Ea:!((I=null==(n=($=b).b)||$.__is_instance__&&"function"==typeof n||"function"==typeof n.__get__?$p.getattr($,"b"):b.b)===(M="undefined"!=typeof(r=a).__array?
"undefined"!=typeof r.__array[2]?r.__array[2]:r.__getitem__(2):r.__getitem__(2))&&null===I||(null===I?0:null===M?0:"object"!=typeof I&&"function"!=typeof I||"function"!=typeof I.__cmp__?"object"!=typeof M&&"function"!=typeof M||"function"!=typeof M.__cmp__?I==M:0===M.__cmp__(I):0===I.__cmp__(M))):(null===(W=qa=!((G=null==(u=(z=b).r)||z.__is_instance__&&"function"==typeof u||"function"==typeof u.__get__?$p.getattr(z,"r"):b.r)===(m="undefined"!=typeof(q=a).__array?"undefined"!=typeof q.__array[0]?q.__array[0]:
q.__getitem__(0):q.__getitem__(0))&&null===G||(null===G?0:null===m?0:"object"!=typeof G&&"function"!=typeof G||"function"!=typeof G.__cmp__?"object"!=typeof m&&"function"!=typeof m||"function"!=typeof m.__cmp__?G==m:0===m.__cmp__(G):0===G.__cmp__(m))))||!1===W||0===W||""===W?0:"object"==typeof W?"function"==typeof W.__nonzero__?W.__nonzero__():"function"==typeof W.__len__?0<W.__len__():1:1)?qa:(null===(A=Ca=!((h=null==(v=(Z=b).g)||Z.__is_instance__&&"function"==typeof v||"function"==typeof v.__get__?
$p.getattr(Z,"g"):b.g)===(k="undefined"!=typeof(F=a).__array?"undefined"!=typeof F.__array[1]?F.__array[1]:F.__getitem__(1):F.__getitem__(1))&&null===h||(null===h?0:null===k?0:"object"!=typeof h&&"function"!=typeof h||"function"!=typeof h.__cmp__?"object"!=typeof k&&"function"!=typeof k||"function"!=typeof k.__cmp__?h==k:0===k.__cmp__(h):0===h.__cmp__(k))))||!1===A||0===A||""===A?0:"object"==typeof A?"function"==typeof A.__nonzero__?A.__nonzero__():"function"==typeof A.__len__?0<A.__len__():1:1)?
Ca:!((p=null==(la=(ia=b).b)||ia.__is_instance__&&"function"==typeof la||"function"==typeof la.__get__?$p.getattr(ia,"b"):b.b)===(l="undefined"!=typeof(L=a).__array?"undefined"!=typeof L.__array[2]?L.__array[2]:L.__getitem__(2):L.__getitem__(2))&&null===p||(null===p?0:null===l?0:"object"!=typeof p&&"function"!=typeof p||"function"!=typeof p.__cmp__?"object"!=typeof l&&"function"!=typeof l||"function"!=typeof l.__cmp__?p==l:0===l.__cmp__(p):0===p.__cmp__(l)))},1,[null,null,["self"],["other"]]);g.__ne__=
c;c=Array(E._Color);var K=$p.dict(),Ba;for(Ba in g)K.__setitem__(Ba,g[Ba]);return $p._create_class("Color",$p.tuple(c),K)}();return this};
