$pyjs.loaded_modules.stars=function(D){if($pyjs.loaded_modules.stars.__was_initialized__)return $pyjs.loaded_modules.stars;var b=$pyjs.loaded_modules.stars;b.__repr__=function(){return"<module: stars>"};b.__was_initialized__=!0;if(null===D||"undefined"==typeof D)D="stars";b.__name__=D;var p,q;b.random=$p.___import___("random",null);b.math=$p.___import___("math",null);try{b.pg=$p.___import___("pygame",null,null,!1),b.sys=$p.___import___("sys",null),b.engine="pygame"}catch(E){if(D="undefined"==typeof E.__name__?
E.name:E.__name__,$pyjs.__last_exception__={error:E,module:b},D==$p.ImportError.__name__||$p._isinstance(E,$p.ImportError))b.pg=$p.___import___("pyjsdl",null,null,!1),b.engine="pyjsdl";else throw $pyjs.__active_exception_stack__=$pyjs.__last_exception_stack__,$pyjs.__last_exception_stack__=null,E;}b.WINSIZE=$p.list([480,480]);b.WINCENTER=$p.list([240,240]);b.NUMSTARS=150;b.init_star=function(){var d,c;c=b.random.randrange(1E5);d=0.6*b.random.random()+0.4;d=$p.list([b.math.sin(c)*d,b.math.cos(c)*d]);
return $p.tuple([d,$p.__getslice(b.WINCENTER,0,null)])};b.init_star.__name__="init_star";b.init_star.__bind_type__=0;b.init_star.__args__=[null,null];b.initialize_stars=function(){var d,c,g,e,a,h,l,f,x,C,r,t,s,m,n,v;a=$p.list([]);c=$p.range(b.NUMSTARS);"undefined"!=typeof(e=c.__array)?s=0:(c=c.__iter__(),s="undefined"!=typeof(e=c.__array)?0:"function"==typeof c.$genfunc?1:-1);for(v=0;"undefined"!=typeof(s?0<s?c.next(!0,!1):$p.wrapped_next(c):e[v++]);)g=b.init_star(),d=$p.__ass_unpack(g,2,null),l=
d[0],d=d[1],n=b.random.randint(0,"undefined"!=typeof(t=b.WINCENTER).__array?"undefined"!=typeof t.__array[0]?t.__array[0]:t.__getitem__(0):t.__getitem__(0)),d.__setitem__(0,("undefined"!=typeof(r=d).__array?"undefined"!=typeof r.__array[0]?r.__array[0]:r.__getitem__(0):r.__getitem__(0))+("undefined"!=typeof(C=l).__array?"undefined"!=typeof C.__array[0]?C.__array[0]:C.__getitem__(0):C.__getitem__(0))*n),d.__setitem__(1,("undefined"!=typeof(x=d).__array?"undefined"!=typeof x.__array[1]?x.__array[1]:
x.__getitem__(1):x.__getitem__(1))+("undefined"!=typeof(f=l).__array?"undefined"!=typeof f.__array[1]?f.__array[1]:f.__getitem__(1):f.__getitem__(1))*n),l.__setitem__(0,0.09*("undefined"!=typeof(h=l).__array?"undefined"!=typeof h.__array[0]?h.__array[0]:h.__getitem__(0):h.__getitem__(0))*n),l.__setitem__(1,0.09*("undefined"!=typeof(m=l).__array?"undefined"!=typeof m.__array[1]?m.__array[1]:m.__getitem__(1):m.__getitem__(1))*n),a.append(g);("undefined"==typeof move_stars?b.move_stars:move_stars)(a);
return a};b.initialize_stars.__name__="initialize_stars";b.initialize_stars.__bind_type__=0;b.initialize_stars.__args__=[null,null];b.draw_stars=function(b,c,g){var e,a,h,l,f,x;h=c;"undefined"!=typeof(x=h.__array)?c=0:(h=h.__iter__(),c="undefined"!=typeof(x=h.__array)?0:"function"==typeof h.$genfunc?1:-1);for(l=0;"undefined"!=typeof(a=c?0<c?h.next(!0,!1):$p.wrapped_next(h):x[l++]);)a=$p.__ass_unpack(a,2,null)[1],a=$p.tuple([$p.float_int("undefined"!=typeof(e=a).__array?"undefined"!=typeof e.__array[0]?
e.__array[0]:e.__getitem__(0):e.__getitem__(0)),$p.float_int("undefined"!=typeof(f=a).__array?"undefined"!=typeof f.__array[1]?f.__array[1]:f.__getitem__(1):f.__getitem__(1))]),b.set_at(a,g);return null};b.draw_stars.__name__="draw_stars";b.draw_stars.__bind_type__=0;b.draw_stars.__args__=[null,null,["surface"],["stars"],["color"]];b.move_stars=function(d){var c,g,e,a,h,l,f,x,C,r,t,s,m,n,v,p,R,w,F,A,G,u,y,z,H,q;r=d;"undefined"!=typeof(d=r.__array)?p=0:(r=r.__iter__(),p="undefined"!=typeof(d=r.__array)?
0:"function"==typeof r.$genfunc?1:-1);for(h=0;"undefined"!=typeof(f=p?0<p?r.next(!0,!1):$p.wrapped_next(r):d[h++]);)if(c=$p.__ass_unpack(f,2,null),f=c[0],c=c[1],c.__setitem__(0,("undefined"!=typeof(z=c).__array?"undefined"!=typeof z.__array[0]?z.__array[0]:z.__getitem__(0):z.__getitem__(0))+("undefined"!=typeof(l=f).__array?"undefined"!=typeof l.__array[0]?l.__array[0]:l.__getitem__(0):l.__getitem__(0))),c.__setitem__(1,("undefined"!=typeof(q=c).__array?"undefined"!=typeof q.__array[1]?q.__array[1]:
q.__getitem__(1):q.__getitem__(1))+("undefined"!=typeof(x=f).__array?"undefined"!=typeof x.__array[1]?x.__array[1]:x.__getitem__(1):x.__getitem__(1))),null===(v=(null===(s=t=!(null===(n=1>(0===(G=$compare1="undefined"!=typeof(C=c).__array?"undefined"!=typeof C.__array[0]?C.__array[0]:C.__getitem__(0):C.__getitem__(0))?0:"number"==typeof G?0==G?0:0<G?-1:1:$p.cmp(0,G))&&1>((A=$compare1)===(R=$compare2="undefined"!=typeof(a=b.WINSIZE).__array?"undefined"!=typeof a.__array[0]?a.__array[0]:a.__getitem__(0):
a.__getitem__(0))?0:typeof A!=typeof R||"number"!=typeof A&&"string"!=typeof A&&"boolean"!=typeof A?$p.cmp(A,R):A==R?0:A<R?-1:1))||!1===n||0===n||""===n?0:"object"==typeof n?"function"==typeof n.__nonzero__?n.__nonzero__():"function"==typeof n.__len__?0<n.__len__():1:1))||!1===s||0===s||""===s?0:"object"==typeof s?"function"==typeof s.__nonzero__?s.__nonzero__():"function"==typeof s.__len__?0<s.__len__():1:1)?t:!(null===(m=1>(0===(F=$compare3="undefined"!=typeof(H=c).__array?"undefined"!=typeof H.__array[1]?
H.__array[1]:H.__getitem__(1):H.__getitem__(1))?0:"number"==typeof F?0==F?0:0<F?-1:1:$p.cmp(0,F))&&1>((w=$compare3)===(e=$compare4="undefined"!=typeof(g=b.WINSIZE).__array?"undefined"!=typeof g.__array[1]?g.__array[1]:g.__getitem__(1):g.__getitem__(1))?0:typeof w!=typeof e||"number"!=typeof w&&"string"!=typeof w&&"boolean"!=typeof w?$p.cmp(w,e):w==e?0:w<e?-1:1))||!1===m||0===m||""===m?0:"object"==typeof m?"function"==typeof m.__nonzero__?m.__nonzero__():"function"==typeof m.__len__?0<m.__len__():
1:1))||!1===v||0===v||""===v?0:"object"==typeof v?"function"==typeof v.__nonzero__?v.__nonzero__():"function"==typeof v.__len__?0<v.__len__():1:1){var B=$p.__ass_unpack(b.init_star(),2,null);$p.__setslice(f,0,null,B[0]);$p.__setslice(c,0,null,B[1])}else f.__setitem__(0,1.05*("undefined"!=typeof(y=f).__array?"undefined"!=typeof y.__array[0]?y.__array[0]:y.__getitem__(0):y.__getitem__(0))),f.__setitem__(1,1.05*("undefined"!=typeof(u=f).__array?"undefined"!=typeof u.__array[1]?u.__array[1]:u.__getitem__(1):
u.__getitem__(1)));return null};b.move_stars.__name__="move_stars";b.move_stars.__bind_type__=0;b.move_stars.__args__=[null,null,["stars"]];b.App=function(){var d={},c;d.__module__="stars";c=$pyjs__bind_method2("__init__",function(a){a=!0===this.__is_instance__?this:a;var c;a.__is_instance__&&"function"==typeof a.__setattr__?a.__setattr__("stars",b.initialize_stars()):$p.setattr(a,"stars",b.initialize_stars());a.__is_instance__&&"function"==typeof a.__setattr__?a.__setattr__("clock",b.pg.time.Clock()):
$p.setattr(a,"clock",b.pg.time.Clock());b.pg.init();a.__is_instance__&&"function"==typeof a.__setattr__?a.__setattr__("screen",b.pg.display.set_mode(b.WINSIZE)):$p.setattr(a,"screen",b.pg.display.set_mode(b.WINSIZE));b.pg.display.set_caption("pygame Stars Example");a.__is_instance__&&"function"==typeof a.__setattr__?a.__setattr__("white",$p.tuple([255,240,200])):$p.setattr(a,"white",$p.tuple([255,240,200]));a.__is_instance__&&"function"==typeof a.__setattr__?a.__setattr__("black",$p.tuple([20,20,
40])):$p.setattr(a,"black",$p.tuple([20,20,40]));a.screen.fill(null==(c=a.black)||a.__is_instance__&&"function"==typeof c||"function"==typeof c.__get__?$p.getattr(a,"black"):a.black);a.__is_instance__&&"function"==typeof a.__setattr__?a.__setattr__("done",0):$p.setattr(a,"done",0);return null},1,[null,null,["self"]]);d.__init__=c;c=$pyjs__bind_method2("run",function(a){a=!0===this.__is_instance__?this:a;var c,d,f,e,g,r,t,s,m,n,v,p,q,w,F,A,G,u,y,z,H,D,B,N,E,da,O,I,J,S,Q,T,U,V,W,k,X,K,Y,Z,$,aa,ba,P,
L,ca,M;if(null===(k=!(null===(K=null==(u=a.done)||a.__is_instance__&&"function"==typeof u||"function"==typeof u.__get__?$p.getattr(a,"done"):a.done)||!1===K||0===K||""===K?0:"object"==typeof K?"function"==typeof K.__nonzero__?K.__nonzero__():"function"==typeof K.__len__?0<K.__len__():1:1))||!1===k||0===k||""===k?0:"object"==typeof k?"function"==typeof k.__nonzero__?k.__nonzero__():"function"==typeof k.__len__?0<k.__len__():1:1){b.draw_stars(null==(S=a.screen)||a.__is_instance__&&"function"==typeof S||
"function"==typeof S.__get__?$p.getattr(a,"screen"):a.screen,null==(Q=a.stars)||a.__is_instance__&&"function"==typeof Q||"function"==typeof Q.__get__?$p.getattr(a,"stars"):a.stars,null==(w=a.black)||a.__is_instance__&&"function"==typeof w||"function"==typeof w.__get__?$p.getattr(a,"black"):a.black);b.move_stars(null==($=a.stars)||a.__is_instance__&&"function"==typeof $||"function"==typeof $.__get__?$p.getattr(a,"stars"):a.stars);b.draw_stars(null==(aa=a.screen)||a.__is_instance__&&"function"==typeof aa||
"function"==typeof aa.__get__?$p.getattr(a,"screen"):a.screen,null==(Y=a.stars)||a.__is_instance__&&"function"==typeof Y||"function"==typeof Y.__get__?$p.getattr(a,"stars"):a.stars,null==(Z=a.white)||a.__is_instance__&&"function"==typeof Z||"function"==typeof Z.__get__?$p.getattr(a,"white"):a.white);b.pg.display.update();u=b.pg.event.get();"undefined"!=typeof(Q=u.__array)?w=0:(u=u.__iter__(),w="undefined"!=typeof(Q=u.__array)?0:"function"==typeof u.$genfunc?1:-1);for(S=0;"undefined"!=typeof(k=w?0<
w?u.next(!0,!1):$p.wrapped_next(u):Q[S++]);)if(null===(z=(null===(M=da=(J=null==(ca=(s=k).type)||s.__is_instance__&&"function"==typeof ca||"function"==typeof ca.__get__?$p.getattr(s,"type"):k.type)===(O=null==(m=(n=b.pg).QUIT)||n.__is_instance__&&"function"==typeof m||"function"==typeof m.__get__?$p.getattr(n,"QUIT"):b.pg.QUIT)&&null===J?!0:null===J?!1:null===O?!1:"object"!=typeof J&&"function"!=typeof J||"function"!=typeof J.__cmp__?"object"!=typeof O&&"function"!=typeof O||"function"!=typeof O.__cmp__?
J==O:0===O.__cmp__(J):0===J.__cmp__(O))||!1===M||0===M||""===M?0:"object"==typeof M?"function"==typeof M.__nonzero__?M.__nonzero__():"function"==typeof M.__len__?0<M.__len__():1:1)?da:(null===(y=D=(I=null==(v=(p=k).type)||p.__is_instance__&&"function"==typeof v||"function"==typeof v.__get__?$p.getattr(p,"type"):k.type)===(P=null==(q=(f=b.pg).KEYUP)||f.__is_instance__&&"function"==typeof q||"function"==typeof q.__get__?$p.getattr(f,"KEYUP"):b.pg.KEYUP)&&null===I?!0:null===I?!1:null===P?!1:"object"!=
typeof I&&"function"!=typeof I||"function"!=typeof I.__cmp__?"object"!=typeof P&&"function"!=typeof P||"function"!=typeof P.__cmp__?I==P:0===P.__cmp__(I):0===I.__cmp__(P))||!1===y||0===y||""===y?0:"object"==typeof y?"function"==typeof y.__nonzero__?y.__nonzero__():"function"==typeof y.__len__?0<y.__len__():1:1)?(L=null==(F=(A=k).key)||A.__is_instance__&&"function"==typeof F||"function"==typeof F.__get__?$p.getattr(A,"key"):k.key)===(t=null==(G=(W=b.pg).K_ESCAPE)||W.__is_instance__&&"function"==typeof G||
"function"==typeof G.__get__?$p.getattr(W,"K_ESCAPE"):b.pg.K_ESCAPE)&&null===L?!0:null===L?!1:null===t?!1:"object"!=typeof L&&"function"!=typeof L||"function"!=typeof L.__cmp__?"object"!=typeof t&&"function"!=typeof t||"function"!=typeof t.__cmp__?L==t:0===t.__cmp__(L):0===L.__cmp__(t):D)||!1===z||0===z||""===z?0:"object"==typeof z?"function"==typeof z.__nonzero__?z.__nonzero__():"function"==typeof z.__len__?0<z.__len__():1:1){a.__is_instance__&&"function"==typeof a.__setattr__?a.__setattr__("done",
1):$p.setattr(a,"done",1);break}else(null===(g=(null===(e=E=(B=null==(V=(U=k).type)||U.__is_instance__&&"function"==typeof V||"function"==typeof V.__get__?$p.getattr(U,"type"):k.type)===(N=null==(T=(r=b.pg).MOUSEBUTTONDOWN)||r.__is_instance__&&"function"==typeof T||"function"==typeof T.__get__?$p.getattr(r,"MOUSEBUTTONDOWN"):b.pg.MOUSEBUTTONDOWN)&&null===B?!0:null===B?!1:null===N?!1:"object"!=typeof B&&"function"!=typeof B||"function"!=typeof B.__cmp__?"object"!=typeof N&&"function"!=typeof N||"function"!=
typeof N.__cmp__?B==N:0===N.__cmp__(B):0===B.__cmp__(N))||!1===e||0===e||""===e?0:"object"==typeof e?"function"==typeof e.__nonzero__?e.__nonzero__():"function"==typeof e.__len__?0<e.__len__():1:1)?1===(c=null==(X=(d=k).button)||d.__is_instance__&&"function"==typeof X||"function"==typeof X.__get__?$p.getattr(d,"button"):k.button)&&null===c?!0:null===c?!1:"object"!=typeof c&&"function"!=typeof c||"function"!=typeof c.__cmp__?1==c:0===c.__cmp__(1):E)||!1===g||0===g||""===g?0:"object"==typeof g?"function"==
typeof g.__nonzero__?g.__nonzero__():"function"==typeof g.__len__?0<g.__len__():1:1)&&$p.__setslice(b.WINCENTER,0,null,$p.list(null==(H=(ba=k).pos)||ba.__is_instance__&&"function"==typeof H||"function"==typeof H.__get__?$p.getattr(ba,"pos"):k.pos));a.clock.tick(50)}return null},1,[null,null,["self"]]);d.run=c;c=Array(pyjslib.object);var g=$p.dict(),e;for(e in d)g.__setitem__(e,d[e]);return $p._create_class("App",$p.tuple(c),g)}();b.main=function(){var d,c,g,e,a,h,l,f;if(null===(e="pygame"===(h=b.engine)&&
null===h?!0:null===h?!1:"object"!=typeof h&&"function"!=typeof h||"function"!=typeof h.__cmp__?"pygame"==h:0===h.__cmp__("pygame"))||!1===e||0===e||""===e?0:"object"==typeof e?"function"==typeof e.__nonzero__?e.__nonzero__():"function"==typeof e.__len__?0<e.__len__():1:1)for(d=b.App();null===(g=!(null===(c=null==(l=(a=d).done)||a.__is_instance__&&"function"==typeof l||"function"==typeof l.__get__?$p.getattr(a,"done"):d.done)||!1===c||0===c||""===c?0:"object"==typeof c?"function"==typeof c.__nonzero__?
c.__nonzero__():"function"==typeof c.__len__?0<c.__len__():1:1))||!1===g||0===g||""===g?0:"object"==typeof g?"function"==typeof g.__nonzero__?g.__nonzero__():"function"==typeof g.__len__?0<g.__len__():1:1;)d.run();else if(null===(d="pyjsdl"===(f=b.engine)&&null===f?!0:null===f?!1:"object"!=typeof f&&"function"!=typeof f||"function"!=typeof f.__cmp__?"pyjsdl"==f:0===f.__cmp__("pyjsdl"))||!1===d||0===d||""===d?0:"object"==typeof d?"function"==typeof d.__nonzero__?d.__nonzero__():"function"==typeof d.__len__?
0<d.__len__():1:1)d=b.App(),b.pg.set_callback(d);return null};b.main.__name__="main";b.main.__bind_type__=0;b.main.__args__=[null,null];(null===(p="__main__"===(q="undefined"==typeof __name__?b.__name__:__name__)&&null===q?!0:null===q?!1:"object"!=typeof q&&"function"!=typeof q||"function"!=typeof q.__cmp__?"__main__"==q:0===q.__cmp__("__main__"))||!1===p||0===p||""===p?0:"object"==typeof p?"function"==typeof p.__nonzero__?p.__nonzero__():"function"==typeof p.__len__?0<p.__len__():1:1)&&b.main();
return this};
