$pyjs.loaded_modules.sys=function(v){if($pyjs.loaded_modules.sys.__was_initialized__)return $pyjs.loaded_modules.sys;var a=sys=$pyjs.loaded_modules.sys;a.__repr__=function(){return"<module: sys>"};a.__was_initialized__=!0;if(null===v||"undefined"==typeof v)v="sys";a.__name__=v;a.overrides=null;a.loadpath=null;a.stacktrace=null;a.appname=null;a.version_info=$p.tuple([2,7,2,"pyjamas",0]);a.subversion=$p.tuple(["Pyjamas","",""]);a.path=$p.list([]);a.argv=$p.list([]);a.platform=$pyjs.platform;a.byteorder=
"little";a.maxint=2147483647;a.setloadpath=function(e){a.loadpath=e;return null};a.setloadpath.__name__="setloadpath";a.setloadpath.__bind_type__=0;a.setloadpath.__args__=[null,null,["lp"]];a.setappname=function(e){a.appname=e;return null};a.setappname.__name__="setappname";a.setappname.__bind_type__=0;a.setappname.__args__=[null,null,["an"]];a.getloadpath=function(){return a.loadpath};a.getloadpath.__name__="getloadpath";a.getloadpath.__bind_type__=0;a.getloadpath.__args__=[null,null];a.addoverride=
function(e,b){a.overrides.__setitem__(e,b);return null};a.addoverride.__name__="addoverride";a.addoverride.__bind_type__=0;a.addoverride.__args__=[null,null,["module_name"],["path"]];a.exc_info=function(){var a,b,c,d,f,g,r,k,q,t,u,l,h,m,n,p,s;a=$pyjs.__last_exception__;if(null===(d=!(null===a||!1===a||0===a||""===a?0:"object"==typeof a?"function"==typeof a.__nonzero__?a.__nonzero__():"function"==typeof a.__len__?0<a.__len__():1:1))||!1===d||0===d||""===d?0:"object"==typeof d?"function"==typeof d.__nonzero__?
d.__nonzero__():"function"==typeof d.__len__?0<d.__len__():1:1)return $p.tuple([null,null,null]);d=(null===(p=!(null===(h=$p.hasattr(null==(c=a.error)||a.__is_instance__&&"function"==typeof c||"function"==typeof c.__get__?$p.getattr(a,"error"):a.error,"__class__"))||!1===h||0===h||""===h?0:"object"==typeof h?"function"==typeof h.__nonzero__?h.__nonzero__():"function"==typeof h.__len__?0<h.__len__():1:1))||!1===p||0===p||""===p?0:"object"==typeof p?"function"==typeof p.__nonzero__?p.__nonzero__():
"function"==typeof p.__len__?0<p.__len__():1:1)?null:null==(k=(t=a.error).__class__)||t.__is_instance__&&"function"==typeof k||"function"==typeof k.__get__?$p.getattr(t,"__class__"):a.error.__class__;c=$pyjs.__last_exception_stack__;if(null===(b=c)||!1===b||0===b||""===b?0:"object"==typeof b?"function"==typeof b.__nonzero__?b.__nonzero__():"function"==typeof b.__len__?0<b.__len__():1:1)for(b=null==(q=(l=c).start)||l.__is_instance__&&"function"==typeof q||"function"==typeof q.__get__?$p.getattr(l,
"start"):c.start;null===(n=(null===(m=r=c)||!1===m||0===m||""===m?0:"object"==typeof m?"function"==typeof m.__nonzero__?m.__nonzero__():"function"==typeof m.__len__?0<m.__len__():1:1)?1==(0===(s=b)?0:"number"!=typeof s||"number"!=typeof s&&"string"!=typeof s&&"boolean"!=typeof s?$p.cmp(s,0):0==s?0:0>s?-1:1):r)||!1===n||0===n||""===n?0:"object"==typeof n?"function"==typeof n.__nonzero__?n.__nonzero__():"function"==typeof n.__len__?0<n.__len__():1:1;)c=null==(u=(g=c).tb_next)||g.__is_instance__&&"function"==
typeof u||"function"==typeof u.__get__?$p.getattr(g,"tb_next"):c.tb_next,b-=1;return $p.tuple([d,null==(f=a.error)||a.__is_instance__&&"function"==typeof f||"function"==typeof f.__get__?$p.getattr(a,"error"):a.error,c])};a.exc_info.__name__="exc_info";a.exc_info.__bind_type__=0;a.exc_info.__args__=[null,null];a.exc_clear=function(){$pyjs.__last_exception_stack__=$pyjs.__last_exception__=null};a.exc_clear.__name__="exc_clear";a.exc_clear.__bind_type__=0;a.exc_clear.__args__=[null,null];a._exception_from_trackstack=
function(a,b){"undefined"==typeof b&&(b=0);for(var c=null,d=null,f=0;f<$pyjs.trackstack.length;f++){var g={},r;for(r in $pyjs.trackstack[f])g[r]=$pyjs.trackstack[f][r];if("undefined"!=typeof $pyjs.loaded_modules[g.module].__track_lines__){var k=$p.dict(),q;for(q in $pyjs.loaded_modules[g.module])k.__setitem__(q,$pyjs.loaded_modules[g.module][q]);g.tb_frame={f_globals:k}}null==c?c=g:d.tb_next=g;d=g}d.tb_next=null;c.start=b;return c};a.save_exception_stack=function(e){if($pyjs.__active_exception_stack__)return $pyjs.__active_exception_stack__.start=
e,$pyjs.__active_exception_stack__;$pyjs.__active_exception_stack__=a._exception_from_trackstack($pyjs.trackstack,e);return $pyjs.__active_exception_stack__};a.trackstacklist=function(e,b){"undefined"==typeof e&&(e=arguments.callee.__args__[2][1]);"undefined"==typeof b&&(b=arguments.callee.__args__[3][1]);var c,d,f,g,r,k,q,t,u,l,h,m,n,p;if(null===(l=null===e)||!1===l||0===l||""===l?0:"object"==typeof l?"function"==typeof l.__nonzero__?l.__nonzero__():"function"==typeof l.__len__?0<l.__len__():1:1)e=
$pyjs.__active_exception_stack__;else if(null===(h=e instanceof Array)||!1===h||0===h||""===h?0:"object"==typeof h?"function"==typeof h.__nonzero__?h.__nonzero__():"function"==typeof h.__len__?0<h.__len__():1:1)e=("undefined"==typeof _exception_from_trackstack?a._exception_from_trackstack:_exception_from_trackstack)(e);if(null===(d=null===e)||!1===d||0===d||""===d?0:"object"==typeof d?"function"==typeof d.__nonzero__?d.__nonzero__():"function"==typeof d.__len__?0<d.__len__():1:1)return"";d=$p.list([]);
if(null===(f=null===b)||!1===f||0===f||""===f?0:"object"==typeof f?"function"==typeof f.__nonzero__?f.__nonzero__():"function"==typeof f.__len__?0<f.__len__():1:1)b=-1;for(;null===(c=(null===(g=r=e)||!1===g||0===g||""===g?0:"object"==typeof g?"function"==typeof g.__nonzero__?g.__nonzero__():"function"==typeof g.__len__?0<g.__len__():1:1)?b:r)||!1===c||0===c||""===c?0:"object"==typeof c?"function"==typeof c.__nonzero__?c.__nonzero__():"function"==typeof c.__len__?0<c.__len__():1:1;)f=$pyjs.loaded_modules[e.module].__track_lines__[e.lineno],
"undefined"==typeof f&&(f=null),(null===(k=f)||!1===k||0===k||""===k?0:"object"==typeof k?"function"==typeof k.__nonzero__?k.__nonzero__():"function"==typeof k.__len__?0<k.__len__():1:1)?d.append(f+"\n"):d.append($p.sprintf("%s.py, line %d\n",$p.tuple([null==(m=(p=e).module)||p.__is_instance__&&"function"==typeof m||"function"==typeof m.__get__?$p.getattr(p,"module"):e.module,null==(n=(u=e).lineno)||u.__is_instance__&&"function"==typeof n||"function"==typeof n.__get__?$p.getattr(u,"lineno"):e.lineno]))),
e=null==(t=(q=e).tb_next)||q.__is_instance__&&"function"==typeof t||"function"==typeof t.__get__?$p.getattr(q,"tb_next"):e.tb_next,b-=1;return d};a.trackstacklist.__name__="trackstacklist";a.trackstacklist.__bind_type__=0;a.trackstacklist.__args__=[null,null,["stack",null],["limit",null]];a.trackstackstr=function(e,b){"undefined"==typeof e&&(e=arguments.callee.__args__[2][1]);"undefined"==typeof b&&(b=arguments.callee.__args__[3][1]);var c;c=$pyjs_kwargs_call(null,a.trackstacklist,null,null,[{limit:b},
e]);return"".join(c)};a.trackstackstr.__name__="trackstackstr";a.trackstackstr.__bind_type__=0;a.trackstackstr.__args__=[null,null,["stack",null],["limit",null]];a._get_traceback_list=function(e,b,c){"undefined"==typeof b&&(b=arguments.callee.__args__[3][1]);"undefined"==typeof c&&(c=arguments.callee.__args__[4][1]);var d;d=$p.getattr($p.getattr(e,"__class__",null),"__name__","Unknown exception");d=$p.list([$p.sprintf("%s: %s\n",$p.tuple([d,e])),"Traceback:\n"]);try{d.extend($pyjs_kwargs_call(null,
a.trackstacklist,null,null,[{limit:c},b]))}catch(f){$pyjs.__last_exception__={error:f,module:a}}return d};a._get_traceback_list.__name__="_get_traceback_list";a._get_traceback_list.__bind_type__=0;a._get_traceback_list.__args__=[null,null,["err"],["tb",null],["limit",null]];a._get_traceback=function(e,b,c){"undefined"==typeof b&&(b=arguments.callee.__args__[3][1]);"undefined"==typeof c&&(c=arguments.callee.__args__[4][1]);return"".join($pyjs_kwargs_call(null,a._get_traceback_list,null,null,[{limit:c},
e,b]))};a._get_traceback.__name__="_get_traceback";a._get_traceback.__bind_type__=0;a._get_traceback.__args__=[null,null,["err"],["tb",null],["limit",null]];a.exit=function(a){"undefined"==typeof a&&(a=arguments.callee.__args__[2][1]);throw $p.SystemExit(a);};a.exit.__name__="exit";a.exit.__bind_type__=0;a.exit.__args__=[null,null,["val",null]];a._StdStream=function(){var a={},b;a.__module__="sys";b=$pyjs__bind_method2("__init__",function(a){a=!0===this.__is_instance__?this:a;a.__is_instance__&&"function"==
typeof a.__setattr__?a.__setattr__("content",""):$p.setattr(a,"content","");return null},1,[null,null,["self"]]);a.__init__=b;b=$pyjs__bind_method2("flush",function(a){a=!0===this.__is_instance__?this:a;var b,c;b=null==(c=a.content)||a.__is_instance__&&"function"==typeof c||"function"==typeof c.__get__?$p.getattr(a,"content"):a.content;$p._print_to_console(b);a.__is_instance__&&"function"==typeof a.__setattr__?a.__setattr__("content",""):$p.setattr(a,"content","");return null},1,[null,null,["self"]]);
a.flush=b;b=$pyjs__bind_method2("write",function(a,b){if(!0===this.__is_instance__)var c=this;else c=a,a=b;var d;c.content+=a;(null===(d=c.content.endswith("\n"))||!1===d||0===d||""===d?0:"object"==typeof d?"function"==typeof d.__nonzero__?d.__nonzero__():"function"==typeof d.__len__?0<d.__len__():1:1)&&c.flush();return null},1,[null,null,["self"],["output"]]);a.write=b;b=Array($p.object);var c=$p.dict(),d;for(d in a)c.__setitem__(d,a[d]);return $p._create_class("_StdStream",$p.tuple(b),c)}();a.stdin=
null;a.stdout=null;a.stderr=null;a.sys_init=function(){a.stdout=a._StdStream();a.stderr=a._StdStream();return null};a.sys_init.__name__="sys_init";a.sys_init.__bind_type__=0;a.sys_init.__args__=[null,null];a.sys_init();return this};
